### ISSUE TITLE
[Usage]: Error executing method determine_num_available_blocks. This might cause deadlock in distributed execution.

### ISSUE THREAD

**Issue by SamuelScc** [vllm-project/vllm#10151]
### Your current environment

I want to deply neuralmagic/DeepSeek-Coder-V2-Instruct-FP8 with 8 x NVIDIA L20，

use -tensor-parallel-size=8 --enforce-eager --trust-remote-code --quantization=fp8 --kv-cache-dtype=fp8 

but i get logs：

![20241108-181536](https://github.com/user-attachments/assets/b1ad9d16-0c6c-49d6-bfbc-510273342010)

### How would you like to use vllm

I want to deply neuralmagic/DeepSeek-Coder-V2-Instruct-FP8 with 8 x NVIDIA L20，

use -tensor-parallel-size=8 --enforce-eager --trust-remote-code --quantization=fp8 --kv-cache-dtype=fp8 

but i get logs：

![20241108-181536](https://github.com/user-attachments/assets/537a5320-e512-41d0-9d78-64dd4479a3ae)

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Sonsal** [comment]
Same issue with CUDA 12.4 and M40 GPU x2 cluster with pipeline parallelization. Full log:
```
root@192:/vllm-workspace# GLOO_SOCKET_IFNAME=eth0 NCCL_SOCKET_IFNAME=eth0 NCCL_DEBUG=INFO vllm serve "Qwen/Qwen2.5-Coder-3B-Instruct" --pipeline-parallel-size 2  --dtype "float16" --enforce-eager
INFO 11-15 01:06:10 api_server.py:528] vLLM API server version 0.6.3.post1
INFO 11-15 01:06:10 api_server.py:529] args: Namespace(subparser='serve', model_tag='Qwen/Qwen2.5-Coder-3B-Instruct', config='', host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='Qwen/Qwen2.5-Coder-3B-Instruct', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='float16', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=2, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=True, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, override_neuron_config=None, scheduling_policy='fcfs', disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, dispatch_function=<function serve at 0x7f5190369ee0>)
WARNING 11-15 01:06:10 config.py:1668] Casting torch.bfloat16 to torch.float16.
INFO 11-15 01:06:17 config.py:905] Defaulting to use ray for distributed inference
WARNING 11-15 01:06:17 arg_utils.py:1019] [DEPRECATED] Block manager v1 has been removed, and setting --use-v2-block-manager to True or False has no effect on vLLM behavior. Please remove --use-v2-block-manager in your engine argument. If your use case is not supported by SelfAttnBlockSpaceManager (i.e. block manager v2), please file an issue with detailed information.
WARNING 11-15 01:06:17 config.py:372] Async output processing can not be enabled with pipeline parallel
2024-11-15 01:06:17,808 INFO worker.py:1601 -- Connecting to existing Ray cluster at address: 192.168.12.211:6379...
2024-11-15 01:06:17,820 INFO worker.py:1786 -- Connected to Ray cluster.
INFO 11-15 01:06:18 llm_engine.py:237] Initializing an LLM engine (v0.6.3.post1) with config: model='Qwen/Qwen2.5-Coder-3B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-Coder-3B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=2, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen/Qwen2.5-Coder-3B-Instruct, num_scheduler_steps=1, chunked_prefill_enabled=False multi_step_stream_outputs=True, enable_prefix_caching=False, use_async_output_proc=False, use_cached_outputs=False, mm_processor_kwargs=None)
INFO 11-15 01:06:18 ray_gpu_executor.py:134] use_ray_spmd_worker: False
INFO 11-15 01:06:29 selector.py:224] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 11-15 01:06:29 selector.py:115] Using XFormers backend.
/usr/local/lib/python3.12/dist-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to 
`torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.  @torch.library.impl_abstract("xformers_flash::flash_fwd")
(RayWorkerWrapper pid=515, ip=192.168.12.212) /usr/local/lib/python3.12/dist-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
(RayWorkerWrapper pid=515, ip=192.168.12.212)   @torch.library.impl_abstract("xformers_flash::flash_fwd")
(RayWorkerWrapper pid=515, ip=192.168.12.212) INFO 11-15 01:06:30 selector.py:224] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
(RayWorkerWrapper pid=515, ip=192.168.12.212) INFO 11-15 01:06:30 selector.py:115] Using XFormers backend.
/usr/local/lib/python3.12/dist-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to 
`torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.  @torch.library.impl_abstract("xformers_flash::flash_bwd")
(RayWorkerWrapper pid=515, ip=192.168.12.212) /usr/local/lib/python3.12/dist-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
(RayWorkerWrapper pid=515, ip=192.168.12.212)   @torch.library.impl_abstract("xformers_flash::flash_bwd")
INFO 11-15 01:06:31 utils.py:1008] Found nccl from library libnccl.so.2
INFO 11-15 01:06:31 pynccl.py:63] vLLM is using nccl==2.20.5
192:828:828 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
192:828:828 [0] NCCL INFO Bootstrap : Using eth0:192.168.12.211<0>
192:828:828 [0] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
192:828:828 [0] NCCL INFO cudaDriverVersion 12040
NCCL version 2.20.5+cuda12.4
(RayWorkerWrapper pid=515, ip=192.168.12.212) INFO 11-15 01:06:31 utils.py:1008] Found nccl from library libnccl.so.2
(RayWorkerWrapper pid=515, ip=192.168.12.212) INFO 11-15 01:06:31 pynccl.py:63] vLLM is using nccl==2.20.5
192:828:828 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
192:828:828 [0] NCCL INFO NET/IB : No device found.
192:828:828 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to eth0
192:828:828 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.12.211<0>
192:828:828 [0] NCCL INFO Using non-device net plugin version 0
192:828:828 [0] NCCL INFO Using network Socket
192:828:828 [0] NCCL INFO comm 0xd672cb0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 50 commId 0x40746147317c0581 - Init START        
192:828:828 [0] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.
192:828:828 [0] NCCL INFO comm 0xd672cb0 rank 0 nRanks 2 nNodes 2 localRanks 1 localRank 0 MNNVL 0
192:828:828 [0] NCCL INFO Channel 00/02 :    0   1
192:828:828 [0] NCCL INFO Channel 01/02 :    0   1
192:828:828 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1
192:828:828 [0] NCCL INFO P2P Chunksize set to 131072
192:828:828 [0] NCCL INFO Channel 00/0 : 1[0] -> 0[0] [receive] via NET/Socket/0
192:828:828 [0] NCCL INFO Channel 01/0 : 1[0] -> 0[0] [receive] via NET/Socket/0
192:828:828 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[0] [send] via NET/Socket/0
192:828:828 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[0] [send] via NET/Socket/0
192:828:828 [0] NCCL INFO Connected all rings
192:828:828 [0] NCCL INFO Connected all trees
192:828:828 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
192:828:828 [0] NCCL INFO 2 coll channels, 0 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
192:828:828 [0] NCCL INFO comm 0xd672cb0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 50 commId 0x40746147317c0581 - Init COMPLETE
INFO 11-15 01:06:31 model_runner.py:1056] Starting to load model Qwen/Qwen2.5-Coder-3B-Instruct...
(RayWorkerWrapper pid=515, ip=192.168.12.212) INFO 11-15 01:06:31 model_runner.py:1056] Starting to load model Qwen/Qwen2.5-Coder-3B-Instruct...
INFO 11-15 01:06:31 selector.py:224] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 11-15 01:06:31 selector.py:115] Using XFormers backend.
(RayWorkerWrapper pid=515, ip=192.168.12.212) INFO 11-15 01:06:32 selector.py:224] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
(RayWorkerWrapper pid=515, ip=192.168.12.212) INFO 11-15 01:06:32 selector.py:115] Using XFormers backend.
INFO 11-15 01:06:32 weight_utils.py:243] Using model weights format ['*.safetensors']
(RayWorkerWrapper pid=515, ip=192.168.12.212) INFO 11-15 01:06:32 weight_utils.py:243] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:03<00:03,  3.29s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:03<00:00,  1.49s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:03<00:00,  1.76s/it]

INFO 11-15 01:06:36 model_runner.py:1067] Loading model weights took 3.1897 GB
(RayWorkerWrapper pid=515, ip=192.168.12.212) INFO 11-15 01:06:40 model_runner.py:1067] Loading model weights took 3.1897 GB
INFO 11-15 01:06:40 model_runner_base.py:120] Writing input of failed execution to /tmp/err_execute_model_input_20241115-010640.pkl...
INFO 11-15 01:06:40 model_runner_base.py:149] Completed writing input of failed execution to /tmp/err_execute_model_input_20241115-010640.pkl.
ERROR 11-15 01:06:40 worker_base.py:464] Error executing method determine_num_available_blocks. This might cause deadlock in distributed execution.
ERROR 11-15 01:06:40 worker_base.py:464] Traceback (most recent call last):
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner_base.py", line 116, in _wrapper
ERROR 11-15 01:06:40 worker_base.py:464]     return func(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1658, in execute_model
ERROR 11-15 01:06:40 worker_base.py:464]     hidden_or_intermediate_states = model_executable(
ERROR 11-15 01:06:40 worker_base.py:464]                                     ^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1553, in 
_wrapped_call_impl
ERROR 11-15 01:06:40 worker_base.py:464]     return self._call_impl(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1562, in 
_call_impl
ERROR 11-15 01:06:40 worker_base.py:464]     return forward_call(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 
415, in forward
ERROR 11-15 01:06:40 worker_base.py:464]     hidden_states = self.model(input_ids, positions, kv_caches,
ERROR 11-15 01:06:40 worker_base.py:464]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1553, in 
_wrapped_call_impl
ERROR 11-15 01:06:40 worker_base.py:464]     return self._call_impl(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1562, in 
_call_impl
ERROR 11-15 01:06:40 worker_base.py:464]     return forward_call(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 
288, in forward
ERROR 11-15 01:06:40 worker_base.py:464]     hidden_states, residual = layer(
ERROR 11-15 01:06:40 worker_base.py:464]                               ^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1553, in 
_wrapped_call_impl
ERROR 11-15 01:06:40 worker_base.py:464]     return self._call_impl(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1562, in 
_call_impl
ERROR 11-15 01:06:40 worker_base.py:464]     return forward_call(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 
210, in forward
ERROR 11-15 01:06:40 worker_base.py:464]     hidden_states = self.self_attn(
ERROR 11-15 01:06:40 worker_base.py:464]                     ^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1553, in 
_wrapped_call_impl
ERROR 11-15 01:06:40 worker_base.py:464]     return self._call_impl(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1562, in 
_call_impl
ERROR 11-15 01:06:40 worker_base.py:464]     return forward_call(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 
154, in forward
ERROR 11-15 01:06:40 worker_base.py:464]     qkv, _ = self.qkv_proj(hidden_states)
ERROR 11-15 01:06:40 worker_base.py:464]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1553, in 
_wrapped_call_impl
ERROR 11-15 01:06:40 worker_base.py:464]     return self._call_impl(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1562, in 
_call_impl
ERROR 11-15 01:06:40 worker_base.py:464]     return forward_call(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/linear.py", line 371, in forward
ERROR 11-15 01:06:40 worker_base.py:464]     output_parallel = self.quant_method.apply(self, input_, bias)
ERROR 11-15 01:06:40 worker_base.py:464]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/linear.py", line 135, in apply
ERROR 11-15 01:06:40 worker_base.py:464]     return F.linear(x, layer.weight, bias)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464] RuntimeError: CUDA error: no kernel image is available for execution on the device
ERROR 11-15 01:06:40 worker_base.py:464] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
ERROR 11-15 01:06:40 worker_base.py:464] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
ERROR 11-15 01:06:40 worker_base.py:464] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
ERROR 11-15 01:06:40 worker_base.py:464]
ERROR 11-15 01:06:40 worker_base.py:464]
ERROR 11-15 01:06:40 worker_base.py:464] The above exception was the direct cause of the following exception:
ERROR 11-15 01:06:40 worker_base.py:464]
ERROR 11-15 01:06:40 worker_base.py:464] Traceback (most recent call last):
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 456, in execute_method
ERROR 11-15 01:06:40 worker_base.py:464]     return executor(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 11-15 01:06:40 worker_base.py:464]     return func(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker.py", line 223, in determine_num_available_blocks
ERROR 11-15 01:06:40 worker_base.py:464]     self.model_runner.profile_run()
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 11-15 01:06:40 worker_base.py:464]     return func(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1305, in profile_run
ERROR 11-15 01:06:40 worker_base.py:464]     self.execute_model(model_input, kv_caches, intermediate_tensors)
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 11-15 01:06:40 worker_base.py:464]     return func(*args, **kwargs)
ERROR 11-15 01:06:40 worker_base.py:464]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 11-15 01:06:40 worker_base.py:464]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner_base.py", line 152, in _wrapper
ERROR 11-15 01:06:40 worker_base.py:464]     raise type(err)(
ERROR 11-15 01:06:40 worker_base.py:464] RuntimeError: Error in model execution (input dumped to /tmp/err_execute_model_input_20241115-010640.pkl): CUDA error: no kernel image is available for execution on the device
ERROR 11-15 01:06:40 worker_base.py:464] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
ERROR 11-15 01:06:40 worker_base.py:464] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
ERROR 11-15 01:06:40 worker_base.py:464] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
ERROR 11-15 01:06:40 worker_base.py:464]
(RayWorkerWrapper pid=515, ip=192.168.12.212) INFO 11-15 01:06:40 model_runner_base.py:120] Writing input of failed execution to /tmp/err_execute_model_input_20241115-010640.pkl...
[rank0]: Traceback (most recent call last):
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner_base.py", line 116, in _wrapper
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1658, in execute_model
[rank0]:     hidden_or_intermediate_states = model_executable(
[rank0]:                                     ^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 415, in forward
[rank0]:     hidden_states = self.model(input_ids, positions, kv_caches,
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 288, in forward
[rank0]:     hidden_states, residual = layer(
[rank0]:                               ^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 210, in forward
[rank0]:     hidden_states = self.self_attn(
[rank0]:                     ^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen2.py", line 154, in forward
[rank0]:     qkv, _ = self.qkv_proj(hidden_states)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/linear.py", line 371, in forward
[rank0]:     output_parallel = self.quant_method.apply(self, input_, bias)
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/linear.py", line 135, in apply
[rank0]:     return F.linear(x, layer.weight, bias)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: no kernel image is available for execution on the device
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.    
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/usr/local/bin/vllm", line 8, in <module>
[rank0]:     sys.exit(main())
[rank0]:              ^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/scripts.py", line 195, in main
[rank0]:     args.dispatch_function(args)
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/scripts.py", line 41, in serve
[rank0]:     uvloop.run(run_server(args))
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 109, in run
[rank0]:     return __asyncio.run(
[rank0]:            ^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
[rank0]:     return runner.run(main)
[rank0]:            ^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
[rank0]:     return self._loop.run_until_complete(task)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 61, in wrapper
[rank0]:     return await main
[rank0]:            ^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 552, in run_server
[rank0]:     async with build_async_engine_client(args) as engine_client:
[rank0]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
[rank0]:     return await anext(self.gen)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 107, in build_async_engine_client
[rank0]:     async with build_async_engine_client_from_engine_args(
[rank0]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
[rank0]:     return await anext(self.gen)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 139, in build_async_engine_client_from_engine_args
[rank0]:     engine_client = build_engine()
[rank0]:                     ^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/async_llm_engine.py", line 672, in from_engine_args
[rank0]:     engine = cls(
[rank0]:              ^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/async_llm_engine.py", line 567, in __init__
[rank0]:     self.engine = self._engine_class(*args, **kwargs)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/async_llm_engine.py", line 263, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 348, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 483, in _initialize_kv_caches
[rank0]:     self.model_executor.determine_num_available_blocks())
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/distributed_gpu_executor.py", line 39, in determine_num_available_blocks
[rank0]:     num_blocks = self._run_workers("determine_num_available_blocks", )
[rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/ray_gpu_executor.py", line 411, in _run_workers
[rank0]:     self.driver_worker.execute_method(method, *driver_args,
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 465, in execute_method
[rank0]:     raise e
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 456, in execute_method
[rank0]:     return executor(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker.py", line 223, in determine_num_available_blocks        
[rank0]:     self.model_runner.profile_run()
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1305, in profile_run
[rank0]:     self.execute_model(model_input, kv_caches, intermediate_tensors)
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner_base.py", line 152, in _wrapper
[rank0]:     raise type(err)(
[rank0]: RuntimeError: Error in model execution (input dumped to /tmp/err_execute_model_input_20241115-010640.pkl): CUDA error: no kernel image is available for execution on the device
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.    
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by myliutian** [comment]
Same Problem.

My running code is 
```shell
CUDA_VISIBLE_DEVICES=$2 HEAD_NODE=1 HEAD_NODE_IP=127.0.0.1 python3 ./sllm/inference/entrypoints/vllm/api_server.py \
--config-file ./sllm/inference/config/base.yml \
--host 127.0.0.1 \
--port $1 \
--initial-instances 1 \
--launch-ray-cluster \
--model /data/models/LLaMa2-7B/ \
--engine-use-ray \
--worker-use-ray \
--request-output-queue-port $(($1 + 1000)) \
--disable-custom-all-reduce \
--tensor-parallel-size 2
``` 

But I get error as follows:
```
(Llumlet pid=207224) INFO 11-20 11:23:35 utils.py:784] Found nccl from library libnccl.so.2
(Llumlet pid=207224) INFO 11-20 11:23:35 pynccl.py:63] vLLM is using nccl==2.20.5
(Llumlet pid=207224) INFO 11-20 11:23:35 shm_broadcast.py:241] vLLM message queue communication handle: Handle(connect_ip='127.0.0.1', local_reader_ranks=[1], buffer=<vllm.distributed.device_communicators.shm_broadcast.ShmRingBuffer object at 0x7f5743a0be50>, local_subscribe_port=38967, local_sync_port=56143, remote_subscribe_port=None, remote_sync_port=None)
(Llumlet pid=207224) INFO 11-20 11:23:35 model_runner.py:680] Starting to load model /data/models/LLaMa2-7B/...
(Llumlet pid=207224) INFO 11-20 11:23:41 model_runner.py:692] Loading model weights took 6.3101 GB
(RayWorkerWrapper pid=207382) INFO 11-20 11:23:35 utils.py:784] Found nccl from library libnccl.so.2
(RayWorkerWrapper pid=207382) INFO 11-20 11:23:35 pynccl.py:63] vLLM is using nccl==2.20.5
(RayWorkerWrapper pid=207382) INFO 11-20 11:23:35 model_runner.py:680] Starting to load model /data/models/LLaMa2-7B/...
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382] Error executing method determine_num_available_blocks. This might cause deadlock in distributed execution.
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382] Traceback (most recent call last):
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 374, in execute_method
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     return executor(*args, **kwargs)
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context       
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     return func(*args, **kwargs)
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/vllm/worker/worker.py", line 179, in determine_num_available_blocks
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     self.model_runner.profile_run()
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context       
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     return func(*args, **kwargs)
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 896, in profile_run
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     self.execute_model(model_input, kv_caches, intermediate_tensors)
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context       
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     return func(*args, **kwargs)
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1314, in execute_model        
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     hidden_or_intermediate_states = model_executable(
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl    
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     return forward_call(*args, **kwargs)
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 422, in forward       
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     model_output = self.model(input_ids, positions, kv_caches,
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl    
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     return self._call_impl(*args, **kwargs)
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     return forward_call(*args, **kwargs)
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 313, in forward       
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     hidden_states = self.get_input_embeddings(input_ids)
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 298, in get_input_embeddings
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     return self.embed_tokens(input_ids)
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl    
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     return self._call_impl(*args, **kwargs)
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]   File "/root/.cache/pypoetry/virtualenvs/sllm-UVFv1iVc-py3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(RayWorkerWrapper pid=207382) ERROR 11-20 11:23:41 worker_base.py:382]     return forward_call(*args, **kwargs)
```

**Comment by R-Tars** [comment]
I encountered the same issue. Does anyone have a solution for this?

**Comment by myliutian** [comment]
My problem has been solved.
Since my model uses Llama2-7B, one model needs to occupy one card when using a 4090 card. If the -tensor-parallel-size parameter is set to 2, multiple cards are required to run the model. Therefore, if the environment variable CUDA_VISIBLE_DEVICES is set to one, it will cause a situation where no available blocks can be found. Therefore, my solution is to pass this environment variable to 0 and 1 for two available GPUs (use nvitop to view available GPUs). If -tensor-parallel-size is set to more, more GPU numbers need to be passed in, and commas are used to separate the parameters. # #

**Comment by R-Tars** [comment]
**Thank you for your response.**

I am working with three machines, each equipped with 8 GPUs (a total of 24 4090 GPUs). Following your advice, I set the environment variable `CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7` on all three machines. However, I am still encountering the following error.

Here is the command I am using:

```bash
vllm serve /model/DeepSeek-V2.5-1210 \
--tensor-parallel-size 8 \
--pipeline-parallel-size 3 \
--trust_remote_code \
--enforce-eager
```

Do you have any suggestions on how to resolve this?

error as follows:
```bash
Loading safetensors checkpoint shards:  93% Completed | 51/55 [00:08<00:00, 20.06it/s]
Loading safetensors checkpoint shards: 100% Completed | 55/55 [00:08<00:00, 23.65it/s]
Loading safetensors checkpoint shards: 100% Completed | 55/55 [00:08<00:00,  6.47it/s]

INFO 01-13 19:02:49 model_runner.py:1099] Loading model weights took 18.3100 GB
(RayWorkerWrapper pid=320, ip=10.10.10.115) INFO 01-13 19:02:51 model_runner.py:1099] Loading model weights took 19.0328 GB
(RayWorkerWrapper pid=913) INFO 01-13 19:02:40 utils.py:918] Found nccl from library libnccl.so.2 [repeated 45x across cluster]
(RayWorkerWrapper pid=913) INFO 01-13 19:02:40 pynccl.py:69] vLLM is using nccl==2.21.5 [repeated 45x across cluster]
(RayWorkerWrapper pid=321, ip=10.10.10.115) WARNING 01-13 19:02:39 custom_all_reduce.py:134] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly. [repeated 22x across cluster]
(RayWorkerWrapper pid=318, ip=10.10.10.115) INFO 01-13 19:02:39 shm_broadcast.py:255] vLLM message queue communication handle: Handle(connect_ip='127.0.0.1', local_reader_ranks=[1, 2, 3, 4, 5, 6, 7], buffer_handle=(7, 4194304, 6, 'psm_d59283a5'), local_subscribe_port=44431, remote_subscribe_port=None)
(RayWorkerWrapper pid=913) INFO 01-13 19:02:40 model_runner.py:1094] Starting to load model /model/DeepSeek-V2.5-1210... [repeated 22x across cluster]
(RayWorkerWrapper pid=321, ip=10.10.10.115) Cache shape torch.Size([163840, 64]) [repeated 22x across cluster]
(RayWorkerWrapper pid=318, ip=10.10.10.114) WARNING 01-13 19:02:52 fused_moe.py:374] Using default MoE config. Performance might be sub-optimal! Config file not found at /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=160,N=192,device_name=NVIDIA_GeForce_RTX_4090.json
(RayWorkerWrapper pid=318, ip=10.10.10.114) INFO 01-13 19:02:52 model_runner_base.py:120] Writing input of failed execution to /tmp/err_execute_model_input_20250113-190252.pkl...
(RayWorkerWrapper pid=318, ip=10.10.10.114) INFO 01-13 19:02:53 model_runner_base.py:149] Completed writing input of failed execution to /tmp/err_execute_model_input_20250113-190252.pkl.
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467] Error executing method determine_num_available_blocks. This might cause deadlock in distributed execution.
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467] Traceback (most recent call last):
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner_base.py", line 116, in _wrapper
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return func(*args, **kwargs)
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1691, in execute_model
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     hidden_or_intermediate_states = model_executable(
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]                                     ^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return self._call_impl(*args, **kwargs)
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return forward_call(*args, **kwargs)
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/deepseek_v2.py", line 518, in forward
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     hidden_states = self.model(input_ids, positions, kv_caches,
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py", line 168, in __call__
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return self.forward(*args, **kwargs)
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/deepseek_v2.py", line 474, in forward
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     hidden_states, residual = layer(positions, hidden_states,
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return self._call_impl(*args, **kwargs)
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return forward_call(*args, **kwargs)
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/deepseek_v2.py", line 404, in forward
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     hidden_states = self.mlp(hidden_states)
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]                     ^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return self._call_impl(*args, **kwargs)
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return forward_call(*args, **kwargs)
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/deepseek_v2.py", line 150, in forward
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     final_hidden_states = self.experts(
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]                           ^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return self._call_impl(*args, **kwargs)
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return forward_call(*args, **kwargs)
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/layer.py", line 511, in forward
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     final_hidden_states = self.quant_method.apply(
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]                           ^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/layer.py", line 89, in apply
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return self.forward(x=x,
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/custom_op.py", line 24, in forward
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return self._forward_method(*args, **kwargs)
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/layer.py", line 127, in forward_cuda
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return fused_experts(hidden_states=x,
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/fused_moe.py", line 635, in fused_experts
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     torch.ops.vllm.inplace_fused_experts(hidden_states, w1, w2,
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/torch/_ops.py", line 1116, in __call__
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return self._op(*args, **(kwargs or {}))
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/fused_moe.py", line 550, in inplace_fused_experts
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     fused_experts_impl(hidden_states, w1, w2, topk_weights, topk_ids, True,
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/fused_moe.py", line 736, in fused_experts_impl
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     moe_align_block_size(curr_topk_ids, config['BLOCK_SIZE_M'], E))
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/fused_moe.py", line 259, in moe_align_block_size
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     ops.moe_align_block_size(topk_ids, num_experts, block_size, sorted_ids,
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/_custom_ops.py", line 953, in moe_align_block_size
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     torch.ops._moe_C.moe_align_block_size(topk_ids, num_experts, block_size,
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/torch/_ops.py", line 1116, in __call__
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return self._op(*args, **(kwargs or {}))
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467] RuntimeError: CUDA error: invalid argument
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467] 
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467] 
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467] The above exception was the direct cause of the following exception:
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467] 
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467] Traceback (most recent call last):
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 459, in execute_method
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]     return executor(*args, **kwargs)
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]            ^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=318, ip=10.10.10.114) ERROR 01-13 19:02:53 worker_base.py:467]   File "
```

**Comment by myliutian** [comment]
Sorry, I used a single machine with multiple GPUs for testing, and did not use the pipeline-parallel-size parameter (probably the default 1). Consider whether you need to treat the entire cluster (3 machines) as a whole, and then define a number for each GPU. Here, the CUDA_VISIBLE_DEVICES parameter needs to be set to 0, 1, ... 23 for the three machines, so that each vllm code can find all GPUs for deployment when it is started. This is just a suggestion, and I have not actually tested it.

**Comment by R-Tars** [comment]
Thanks for getting back to me! I’ve already tried that, but I’m still running into the same error. I’ll keep exploring other solutions.

**Comment by ahellpoet** [comment]
> Thanks for getting back to me! I’ve already tried that, but I’m still running into the same error. I’ll keep exploring other solutions.

Do you have a solution? I also have the same problem

**Comment by liu316484231** [comment]
i encountered the same error，any suggestions?

**Comment by hyowon-moon** [comment]
I solved it as follows.
Before running the code, I examined the error in detail by applying the following settings:
import os
os.environ["TORCH_LOGS"] = "+dynamo"
os.environ["TORCHDYNAMO_VERBOSE"] = "1"

In my case, I found that the error originated from the Triton package.
I confirmed that the error occurred at

def libcuda_dirs():
    env_libcuda_path = os.getenv("TRITON_LIBCUDA_PATH")
    if env_libcuda_path:
        return [env_libcuda_path]
    **libs = subprocess.check_output(["/sbin/ldconfig", "-p"]).decode()**

in ... site-packages/triton/backends/nvidia/driver.py 

and I identified a conflict between the terminal's encoding and the decoding process in the code.
By modifying the code as follows:
**libs = subprocess.check_output(["/sbin/ldconfig", "-p"]).decode(locale.getpreferredencoding())**
The issue was resolved.
