### ISSUE TITLE
[Bug]:  (vllm serve Qwen/Qwen2.5-1.5B-Instruct) is generating error torch.distributed.DistBackendError: File name too long and same thing is happening with other models

### ISSUE THREAD

**Issue by Diksha06122** [vllm-project/vllm#10734]
### Your current environment

torch                             2.5.1
torchvision                       0.20.1
vllm                              0.6.4.post1

### Model Input Dumps

 vllm serve Qwen/Qwen2.5-1.5B-Instruct
INFO 11-28 06:43:46 api_server.py:585] vLLM API server version 0.6.4.post1
INFO 11-28 06:43:46 api_server.py:586] args: Namespace(subparser='serve', model_tag='Qwen/Qwen2.5-1.5B-Instruct', config='', host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='Qwen/Qwen2.5-1.5B-Instruct', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', chat_template_text_format='string', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', override_neuron_config=None, override_pooler_config=None, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, dispatch_function=<function serve at 0x763b8c700b80>)
INFO 11-28 06:43:46 api_server.py:175] Multiprocessing frontend to use ipc:///tmp/c1b4af4f-eb12-4c58-829e-eef5a50511ee for IPC Path.
INFO 11-28 06:43:46 api_server.py:194] Started engine process with PID 6086
config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 660/660 [00:00<00:00, 2.42MB/s]
INFO 11-28 06:43:55 config.py:350] This model supports multiple tasks: {'embedding', 'generate'}. Defaulting to 'generate'.
WARNING 11-28 06:43:55 arg_utils.py:1075] [DEPRECATED] Block manager v1 has been removed, and setting --use-v2-block-manager to True or False has no effect on vLLM behavior. Please remove --use-v2-block-manager in your engine argument. If your use case is not supported by SelfAttnBlockSpaceManager (i.e. block manager v2), please file an issue with detailed information.
tokenizer_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 7.30k/7.30k [00:00<00:00, 38.3MB/s]
vocab.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.78M/2.78M [00:01<00:00, 2.50MB/s]
merges.txt: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.67M/1.67M [00:00<00:00, 8.61MB/s]
tokenizer.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7.03M/7.03M [00:01<00:00, 6.28MB/s]
INFO 11-28 06:44:00 config.py:350] This model supports multiple tasks: {'generate', 'embedding'}. Defaulting to 'generate'.
WARNING 11-28 06:44:00 arg_utils.py:1075] [DEPRECATED] Block manager v1 has been removed, and setting --use-v2-block-manager to True or False has no effect on vLLM behavior. Please remove --use-v2-block-manager in your engine argument. If your use case is not supported by SelfAttnBlockSpaceManager (i.e. block manager v2), please file an issue with detailed information.
INFO 11-28 06:44:00 llm_engine.py:249] Initializing an LLM engine (v0.6.4.post1) with config: model='Qwen/Qwen2.5-1.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-1.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen/Qwen2.5-1.5B-Instruct, num_scheduler_steps=1, chunked_prefill_enabled=False multi_step_stream_outputs=True, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=True, chat_template_text_format=string, mm_processor_kwargs=None, pooler_config=None)
generation_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 242/242 [00:00<00:00, 1.63MB/s]
INFO 11-28 06:44:01 selector.py:135] Using Flash Attention backend.
ERROR 11-28 06:44:02 engine.py:366] File name too long
ERROR 11-28 06:44:02 engine.py:366] Traceback (most recent call last):
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
ERROR 11-28 06:44:02 engine.py:366]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 11-28 06:44:02 engine.py:366]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
ERROR 11-28 06:44:02 engine.py:366]     return cls(ipc_path=ipc_path,
ERROR 11-28 06:44:02 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 71, in __init__
ERROR 11-28 06:44:02 engine.py:366]     self.engine = LLMEngine(*args, **kwargs)
ERROR 11-28 06:44:02 engine.py:366]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 347, in __init__
ERROR 11-28 06:44:02 engine.py:366]     self.model_executor = executor_class(vllm_config=vllm_config, )
ERROR 11-28 06:44:02 engine.py:366]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 36, in __init__
ERROR 11-28 06:44:02 engine.py:366]     self._init_executor()
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/executor/gpu_executor.py", line 39, in _init_executor
ERROR 11-28 06:44:02 engine.py:366]     self.driver_worker.init_device()
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/worker/worker.py", line 145, in init_device
ERROR 11-28 06:44:02 engine.py:366]     init_worker_distributed_environment(self.parallel_config, self.rank,
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/worker/worker.py", line 459, in init_worker_distributed_environment
ERROR 11-28 06:44:02 engine.py:366]     init_distributed_environment(parallel_config.world_size, rank,
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/distributed/parallel_state.py", line 1010, in init_distributed_environment
ERROR 11-28 06:44:02 engine.py:366]     _WORLD = init_world_group(ranks, local_rank, backend)
ERROR 11-28 06:44:02 engine.py:366]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/distributed/parallel_state.py", line 885, in init_world_group
ERROR 11-28 06:44:02 engine.py:366]     return GroupCoordinator(
ERROR 11-28 06:44:02 engine.py:366]            ^^^^^^^^^^^^^^^^^
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/distributed/parallel_state.py", line 198, in __init__
ERROR 11-28 06:44:02 engine.py:366]     cpu_group = torch.distributed.new_group(ranks, backend="gloo")
ERROR 11-28 06:44:02 engine.py:366]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 97, in wrapper
ERROR 11-28 06:44:02 engine.py:366]     func_return = func(*args, **kwargs)
ERROR 11-28 06:44:02 engine.py:366]                   ^^^^^^^^^^^^^^^^^^^^^
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 4565, in new_group
ERROR 11-28 06:44:02 engine.py:366]     return _new_group_with_tag(
ERROR 11-28 06:44:02 engine.py:366]            ^^^^^^^^^^^^^^^^^^^^
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 4648, in _new_group_with_tag
ERROR 11-28 06:44:02 engine.py:366]     pg, pg_store = _new_process_group_helper(
ERROR 11-28 06:44:02 engine.py:366]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 11-28 06:44:02 engine.py:366]   File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 1744, in _new_process_group_helper
ERROR 11-28 06:44:02 engine.py:366]     backend_class = ProcessGroupGloo(
ERROR 11-28 06:44:02 engine.py:366]                     ^^^^^^^^^^^^^^^^^
ERROR 11-28 06:44:02 engine.py:366] torch.distributed.DistBackendError: File name too long
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 368, in run_mp_engine
    raise e
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
    return cls(ipc_path=ipc_path,
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/engine/multiprocessing/engine.py", line 71, in __init__
    self.engine = LLMEngine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 347, in __init__
    self.model_executor = executor_class(vllm_config=vllm_config, )
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 36, in __init__
    self._init_executor()
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/executor/gpu_executor.py", line 39, in _init_executor
    self.driver_worker.init_device()
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/worker/worker.py", line 145, in init_device
    init_worker_distributed_environment(self.parallel_config, self.rank,
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/worker/worker.py", line 459, in init_worker_distributed_environment
    init_distributed_environment(parallel_config.world_size, rank,
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/distributed/parallel_state.py", line 1010, in init_distributed_environment
    _WORLD = init_world_group(ranks, local_rank, backend)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/distributed/parallel_state.py", line 885, in init_world_group
    return GroupCoordinator(
           ^^^^^^^^^^^^^^^^^
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/distributed/parallel_state.py", line 198, in __init__
    cpu_group = torch.distributed.new_group(ranks, backend="gloo")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 97, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 4565, in new_group
    return _new_group_with_tag(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 4648, in _new_group_with_tag
    pg, pg_store = _new_process_group_helper(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 1744, in _new_process_group_helper
    backend_class = ProcessGroupGloo(
                    ^^^^^^^^^^^^^^^^^
torch.distributed.DistBackendError: File name too long
[rank0]:[W1128 06:44:02.440670175 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
Traceback (most recent call last):
  File "/home/diksha/Diksha/venv/bin/vllm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/scripts.py", line 195, in main
    args.dispatch_function(args)
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/scripts.py", line 41, in serve
    uvloop.run(run_server(args))
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 609, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 113, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/diksha/Diksha/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 210, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.

### 🐛 Describe the bug

torch.distributed.DistBackendError: File name too long

**Comment by DarkLight1337** [comment]
cc @youkaichao

**Comment by Diksha06122** [comment]
Problem Resolved :
The environment variable GLOO_SOCKET_IFNAME is used by PyTorch’s backend communication library, Gloo, to specify which network interface should be used for inter-process communication. By setting GLOO_SOCKET_IFNAME=lo, you are instructing Gloo to use the loopback interface (lo) for communication, which is restricted to the local machine.

set environment variable: export GLOO_SOCKET_IFNAME=lo
than run: vllm serve model --gpu_memory_utilization=0.98 --max-model-len=4096 --enable-chunked-prefill=False --num_scheduler_steps=2

**Comment by youkaichao** [comment]
@Diksha06122 how is it solved? I didn't know this error before.

**Comment by CamWang** [comment]
> Problem Resolved : The environment variable GLOO_SOCKET_IFNAME is used by PyTorch’s backend communication library, Gloo, to specify which network interface should be used for inter-process communication. By setting GLOO_SOCKET_IFNAME=lo, you are instructing Gloo to use the loopback interface (lo) for communication, which is restricted to the local machine.
> 
> set environment variable: export GLOO_SOCKET_IFNAME=lo than run: vllm serve model --gpu_memory_utilization=0.98 --max-model-len=4096 --enable-chunked-prefill=False --num_scheduler_steps=2

Solve my problem.

Environment: Ubuntu 24.04
Python Version: 3.12
Conda: miniconda
VLLM Version: 0.66patch1

**Comment by youkaichao** [comment]
close as it is solved now.

**Comment by CamWang** [comment]
> close as it is solved now.

No it still presents in the current version, but need to follow @Diksha06122 's solution to set a environment variable.

**Comment by youkaichao** [comment]
@CamWang that's out of vLLM's scope. it is pytorch gloo backend's issue.

**Comment by d4l3k** [comment]
@CamWang , @Diksha06122 do you have a repro w/ logs for this issue?

Also if you can set `TORCH_SHOW_CPP_STACKTRACES=1` to get the C++ stack trace that would greatly help us fix the underlying issue
