### ISSUE TITLE
通过命令行启动api_serverException in worker VllmWorkerProcess while processing method determine_num_available_blocks: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by wMonster** [vllm-project/vllm#11485]
pytorch 2.3.0    vllm 0.5.0.post1
transformers 4.40.0
cuda12.1
cuda设备Tesla t4

系统信息:

Linux ubuntu-13 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

root@ubuntu-13:/app# nvidia-smi
Wed Dec 25 15:06:57 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:04:00.0 Off |                    0 |
| N/A   31C    P8               9W /  70W |      6MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla T4                       Off | 00000000:05:00.0 Off |                    0 |
| N/A   31C    P8               9W /  70W |      6MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

(python31013new) root@ubuntu-13:/app/dms_GLM4#   python -m vllm.entrypoints.openai.api_server \
>   --model /app/models/glm-4-9b-chat \
>   --served-model-name glm-api \
>   --trust-remote-code \
>   --enforce-eager \
>   --enable-lora \
>   --lora-modules 'ldjh=/app/ldjh/ldjh_20241219_1' \
>   --max-model-len 6552 \
>   --tensor-parallel-size 2 \
>   --gpu-memory-utilization 0.95 \
>   --dtype float16 \
>   --block-size 8 \
>   --port 8001 \
>   --host 20.10.1.13
INFO 12-25 12:04:04 api_server.py:177] vLLM API server version 0.5.0.post1
INFO 12-25 12:04:04 api_server.py:178] args: Namespace(host='20.10.1.13', port=8001, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=[LoRAModulePath(name='ldjh', local_path='/app/ldjh/ldjh_20241219_1')], chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/app/models/glm-4-9b-chat', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='float16', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=6552, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=8, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=0.95, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=True, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=True, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, image_processor=None, image_processor_revision=None, disable_image_processor=False, scheduler_delay_factor=0.0, enable_chunked_prefill=False, speculative_model=None, num_speculative_tokens=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, model_loader_extra_config=None, preemption_mode=None, served_model_name=['glm-api'], qlora_adapter_name_or_path=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
WARNING 12-25 12:04:04 config.py:1222] Casting torch.bfloat16 to torch.float16.
2024-12-25 12:04:07,754	INFO worker.py:1816 -- Started a local Ray instance.
INFO 12-25 12:04:08 config.py:623] Defaulting to use mp for distributed inference
INFO 12-25 12:04:08 llm_engine.py:161] Initializing an LLM engine (v0.5.0.post1) with config: model='/app/models/glm-4-9b-chat', speculative_config=None, tokenizer='/app/models/glm-4-9b-chat', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=6552, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=glm-api)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
WARNING 12-25 12:04:09 tokenizer.py:126] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 12-25 12:04:10 selector.py:131] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 12-25 12:04:10 selector.py:51] Using XFormers backend.
(VllmWorkerProcess pid=8498) INFO 12-25 12:04:16 selector.py:131] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
(VllmWorkerProcess pid=8498) INFO 12-25 12:04:16 selector.py:51] Using XFormers backend.
(VllmWorkerProcess pid=8498) INFO 12-25 12:04:17 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=8498) INFO 12-25 12:04:18 utils.py:637] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=8498) INFO 12-25 12:04:18 pynccl.py:63] vLLM is using nccl==2.20.5
INFO 12-25 12:04:18 utils.py:637] Found nccl from library libnccl.so.2
INFO 12-25 12:04:18 pynccl.py:63] vLLM is using nccl==2.20.5
Traceback (most recent call last):
  File "/app/anaconda3/envs/python31013new/lib/python3.10/multiprocessing/resource_tracker.py", line 209, in main
    cache[rtype].remove(name)
KeyError: '/psm_8d17116d'
INFO 12-25 12:04:18 custom_all_reduce_utils.py:179] reading GPU P2P access cache from /root/.config/vllm/gpu_p2p_access_cache_for_0,1.json
(VllmWorkerProcess pid=8498) INFO 12-25 12:04:18 custom_all_reduce_utils.py:179] reading GPU P2P access cache from /root/.config/vllm/gpu_p2p_access_cache_for_0,1.json
(VllmWorkerProcess pid=8498) INFO 12-25 12:04:19 selector.py:131] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
(VllmWorkerProcess pid=8498) INFO 12-25 12:04:19 selector.py:51] Using XFormers backend.
INFO 12-25 12:04:19 selector.py:131] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 12-25 12:04:19 selector.py:51] Using XFormers backend.
INFO 12-25 12:05:56 model_runner.py:160] Loading model weights took 8.8289 GB
(VllmWorkerProcess pid=8498) INFO 12-25 12:05:56 model_runner.py:160] Loading model weights took 8.8289 GB
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226] Exception in worker VllmWorkerProcess while processing method determine_num_available_blocks: CUDA error: no kernel image is available for execution on the device
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226] For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226] , Traceback (most recent call last):
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 223, in _run_worker_process
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     output = executor(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/worker/worker.py", line 162, in determine_num_available_blocks
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     self.model_runner.profile_run()
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 844, in profile_run
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     self.execute_model(seqs, kv_caches)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return func(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 749, in execute_model
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     hidden_states = model_executable(
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/model_executor/models/chatglm.py", line 364, in forward
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     hidden_states = self.transformer(input_ids, positions, kv_caches,
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/model_executor/models/chatglm.py", line 316, in forward
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     hidden_states = self.encoder(
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/model_executor/models/chatglm.py", line 272, in forward
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     hidden_states = layer(
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/model_executor/models/chatglm.py", line 207, in forward
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     attention_output = self.self_attention(
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/model_executor/models/chatglm.py", line 106, in forward
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     context_layer = self.attn(
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/attention/layer.py", line 89, in forward
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     return self.impl.forward(query, key, value, kv_cache, attn_metadata,
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/attention/backends/xformers.py", line 279, in forward
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226]     output = torch.empty_like(query)
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226] RuntimeError: CUDA error: no kernel image is available for execution on the device
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226] For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226] 
(VllmWorkerProcess pid=8498) ERROR 12-25 12:05:59 multiproc_worker_utils.py:226] 
[rank0]: Traceback (most recent call last):
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 196, in <module>
[rank0]:     engine = AsyncLLMEngine.from_engine_args(
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 398, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 349, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 473, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 236, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 313, in _initialize_kv_caches
[rank0]:     self.model_executor.determine_num_available_blocks())
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 38, in determine_num_available_blocks
[rank0]:     num_blocks = self._run_workers("determine_num_available_blocks", )
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 119, in _run_workers
[rank0]:     driver_worker_output = driver_worker_method(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/worker/worker.py", line 162, in determine_num_available_blocks
[rank0]:     self.model_runner.profile_run()
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 844, in profile_run
[rank0]:     self.execute_model(seqs, kv_caches)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 749, in execute_model
[rank0]:     hidden_states = model_executable(
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/model_executor/models/chatglm.py", line 364, in forward
[rank0]:     hidden_states = self.transformer(input_ids, positions, kv_caches,
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/model_executor/models/chatglm.py", line 316, in forward
[rank0]:     hidden_states = self.encoder(
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/model_executor/models/chatglm.py", line 272, in forward
[rank0]:     hidden_states = layer(
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/model_executor/models/chatglm.py", line 207, in forward
[rank0]:     attention_output = self.self_attention(
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/model_executor/models/chatglm.py", line 106, in forward
[rank0]:     context_layer = self.attn(
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/attention/layer.py", line 89, in forward
[rank0]:     return self.impl.forward(query, key, value, kv_cache, attn_metadata,
[rank0]:   File "/app/anaconda3/envs/python31013new/lib/python3.10/site-packages/vllm/attention/backends/xformers.py", line 279, in forward
[rank0]:     output = torch.empty_like(query)
[rank0]: RuntimeError: CUDA error: no kernel image is available for execution on the device
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

INFO 12-25 12:06:02 multiproc_worker_utils.py:123] Killing local vLLM worker processes
Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x0000000001ae78c0)

Current thread 0x0000740556f53600 (most recent call first):
  <no Python frame>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, yaml._yaml, psutil._psutil_linux, psutil._psutil_posix, msgpack._cmsgpack, google._upb._message, setproctitle, uvloop.loop, ray._raylet, sentencepiece._sentencepiece, ujson, regex._regex, scipy._lib._ccallback_c, numba.core.typeconv._typeconv, numba._helperlib, numba._dynfunc, numba._dispatcher, numba.core.runtime._nrt_python, numba.np.ufunc._internal, numba.experimental.jitclass._box, pyarrow.lib, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.strptime, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.lib, pyarrow._compute, pandas._libs.ops, pandas._libs.hashing, pandas._libs.arrays, pandas._libs.tslib, pandas._libs.sparse, pandas._libs.internals, pandas._libs.indexing, pandas._libs.index, pandas._libs.writers, pandas._libs.join, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.json, pandas._libs.parsers, pandas._libs.testing, pyarrow._parquet, pyarrow._fs, pyarrow._azurefs, pyarrow._hdfs, pyarrow._gcsfs, pyarrow._s3fs, multidict._multidict, yarl._quoting_c, propcache._helpers_c, aiohttp._helpers, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket, frozenlist._frozenlist, xxhash._xxhash, pyarrow._json, markupsafe._speedups, PIL._imaging, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.optimize._group_columns, scipy._lib.messagestream, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.spatial._ckdtree, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial.transform._rotation, scipy.optimize._direct (total: 158)
Aborted (core dumped)
[lora_error.txt](https://github.com/user-attachments/files/18244286/lora_error.txt)
启动命令：nohup python -m vllm.entrypoints.openai.api_server \
  --model /data/dms/models/glm-4-9b-chat-1m \
  --served-model-name glm-4 \
  --trust-remote-code \
  --enforce-eager \
  --enable-lora \
  --lora-modules 'ldjh=/data/dms/LLaMA-Factory-0.9.1/saves/GLM-4-9B-Chat/lora/ldjh_20241218' \
  --max-model-len 65528 \
  --tensor-parallel-size 2 \
  --gpu-memory-utilization 0.8 \
  --dtype float16 \
  --block-size 32 \
  --port 8001 \
  --host 172.29.xx.xxx \
  > "$LOG_FILE" 2>&1 &

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Leander-wang** [comment]
这个错误我遇到过，一般来说如果你采用源码编译的手段就会出现这个问题，例如，如果你在v100，编译后，如果需要在a100等其他型号的gpu上跑，则需要重新编译，当然官方也给出了预编译的方法，具体可以参考：https://docs.vllm.ai/en/latest/getting_started/installation.html#python-only-build-without-compilation

**Comment by wMonster** [comment]
我没有编译过，是通过pip install 安装的，启动命令如果不加lora-modules配置，可以正常启动，环境信息:   Linux ubuntu-13 6.8.0-49-generic https://github.com/vllm-project/vllm/pull/49 -Ubuntu SMP PREEMPT_DYNAMIC 星期一 11 月 4 日 02:06:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux                           pytorch 2.3.0    vllm 0.5.0.post1
transformers 4.40.0
cuda12.1
cuda设备Tesla t4

**Comment by jeejeelee** [comment]
Your vLLM version (0.5.0) is too old. Please upgrade to at least version 0.5.4.
