### ISSUE TITLE
[Bug]: Cutlass 2:4 Sparsity + FP8/Int8 Quant RuntimeError: Error Internal

### ISSUE THREAD

**Issue by leoyuppieqnew** [vllm-project/vllm#11756]
[root workflow_47400355 /ossfs/workspace] 一 1月 06 15:46:05 
$CUDA_LAUNCH_BLOCKING=1 vllm serve /mntfn/yanyi/sparse/mntfn-FP8-Dynamic/
INFO 01-06 15:46:27 api_server.py:647] vLLM API server version 0.1.dev3896+ga491d6f.d20250103
INFO 01-06 15:46:27 api_server.py:648] args: Namespace(subparser='serve', model_tag='/mntfn/yanyi/sparse/mntfn-FP8-Dynamic/', config='', host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='/mntfn/yanyi/sparse/mntfn-FP8-Dynamic/', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='xgrammar', logits_processor_pattern=None, distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=None, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', generation_config=None, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, dispatch_function=<function serve at 0x7fd3d1634c10>)
INFO 01-06 15:46:27 api_server.py:195] Started engine process with PID 65910
INFO 01-06 15:46:40 config.py:518] This model supports multiple tasks: {'reward', 'score', 'embed', 'classify', 'generate'}. Defaulting to 'generate'.
INFO 01-06 15:46:50 config.py:518] This model supports multiple tasks: {'reward', 'classify', 'generate', 'embed', 'score'}. Defaulting to 'generate'.
INFO 01-06 15:46:53 llm_engine.py:234] Initializing an LLM engine (v0.1.dev3896+ga491d6f.d20250103) with config: model='/mntfn/yanyi/sparse/mntfn-FP8-Dynamic/', speculative_config=None, tokenizer='/mntfn/yanyi/sparse/mntfn-FP8-Dynamic/', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=compressed-tensors, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/mntfn/yanyi/sparse/mntfn-FP8-Dynamic/, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"candidate_compile_sizes":[],"compile_sizes":[],"capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=True, 
INFO 01-06 15:46:57 selector.py:120] Using Flash Attention backend.
INFO 01-06 15:46:59 model_runner.py:1094] Starting to load model /mntfn/yanyi/sparse/mntfn-FP8-Dynamic/...
Loading safetensors checkpoint shards:   0% Completed | 0/16 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   6% Completed | 1/16 [00:01<00:16,  1.08s/it]
Loading safetensors checkpoint shards:  12% Completed | 2/16 [00:02<00:17,  1.27s/it]
Loading safetensors checkpoint shards:  19% Completed | 3/16 [00:03<00:17,  1.38s/it]
Loading safetensors checkpoint shards:  25% Completed | 4/16 [00:05<00:16,  1.37s/it]
Loading safetensors checkpoint shards:  31% Completed | 5/16 [00:06<00:14,  1.32s/it]
Loading safetensors checkpoint shards:  38% Completed | 6/16 [00:07<00:12,  1.29s/it]
Loading safetensors checkpoint shards:  44% Completed | 7/16 [00:09<00:11,  1.26s/it]
Loading safetensors checkpoint shards:  50% Completed | 8/16 [00:10<00:09,  1.25s/it]
Loading safetensors checkpoint shards:  56% Completed | 9/16 [00:11<00:08,  1.24s/it]
Loading safetensors checkpoint shards:  62% Completed | 10/16 [00:12<00:07,  1.24s/it]
Loading safetensors checkpoint shards:  69% Completed | 11/16 [00:13<00:06,  1.25s/it]
Loading safetensors checkpoint shards:  75% Completed | 12/16 [00:15<00:05,  1.26s/it]
Loading safetensors checkpoint shards:  81% Completed | 13/16 [00:16<00:03,  1.24s/it]
Loading safetensors checkpoint shards:  88% Completed | 14/16 [00:17<00:02,  1.20s/it]
Loading safetensors checkpoint shards:  94% Completed | 15/16 [00:18<00:01,  1.16s/it]
Loading safetensors checkpoint shards: 100% Completed | 16/16 [00:19<00:00,  1.03s/it]
Loading safetensors checkpoint shards: 100% Completed | 16/16 [00:19<00:00,  1.21s/it]

INFO 01-06 15:47:21 model_runner.py:1099] Loading model weights took 45.6023 GB
INFO 01-06 15:47:24 model_runner_base.py:120] Writing input of failed execution to /tmp/err_execute_model_input_20250106-154724.pkl...
WARNING 01-06 15:47:24 model_runner_base.py:143] Failed to pickle inputs of failed execution: CUDA error: an illegal memory access was encountered
WARNING 01-06 15:47:24 model_runner_base.py:143] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
WARNING 01-06 15:47:24 model_runner_base.py:143] 
ERROR 01-06 15:47:24 engine.py:366] Error in model execution: Error Internal
ERROR 01-06 15:47:24 engine.py:366] Traceback (most recent call last):
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/worker/model_runner_base.py", line 116, in _wrapper
ERROR 01-06 15:47:24 engine.py:366]     return func(*args, **kwargs)
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/worker/model_runner.py", line 1691, in execute_model
ERROR 01-06 15:47:24 engine.py:366]     hidden_or_intermediate_states = model_executable(
ERROR 01-06 15:47:24 engine.py:366]   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 01-06 15:47:24 engine.py:366]     return self._call_impl(*args, **kwargs)
ERROR 01-06 15:47:24 engine.py:366]   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 01-06 15:47:24 engine.py:366]     return forward_call(*args, **kwargs)
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/model_executor/models/qwen2.py", line 477, in forward
ERROR 01-06 15:47:24 engine.py:366]     hidden_states = self.model(input_ids, positions, kv_caches,
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/compilation/decorators.py", line 168, in __call__
ERROR 01-06 15:47:24 engine.py:366]     return self.forward(*args, **kwargs)
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/model_executor/models/qwen2.py", line 340, in forward
ERROR 01-06 15:47:24 engine.py:366]     hidden_states, residual = layer(
ERROR 01-06 15:47:24 engine.py:366]   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 01-06 15:47:24 engine.py:366]     return self._call_impl(*args, **kwargs)
ERROR 01-06 15:47:24 engine.py:366]   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 01-06 15:47:24 engine.py:366]     return forward_call(*args, **kwargs)
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/model_executor/models/qwen2.py", line 247, in forward
ERROR 01-06 15:47:24 engine.py:366]     hidden_states = self.self_attn(
ERROR 01-06 15:47:24 engine.py:366]   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 01-06 15:47:24 engine.py:366]     return self._call_impl(*args, **kwargs)
ERROR 01-06 15:47:24 engine.py:366]   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 01-06 15:47:24 engine.py:366]     return forward_call(*args, **kwargs)
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/model_executor/models/qwen2.py", line 173, in forward
ERROR 01-06 15:47:24 engine.py:366]     qkv, _ = self.qkv_proj(hidden_states)
ERROR 01-06 15:47:24 engine.py:366]   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 01-06 15:47:24 engine.py:366]     return self._call_impl(*args, **kwargs)
ERROR 01-06 15:47:24 engine.py:366]   File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 01-06 15:47:24 engine.py:366]     return forward_call(*args, **kwargs)
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/model_executor/layers/linear.py", line 373, in forward
ERROR 01-06 15:47:24 engine.py:366]     output_parallel = self.quant_method.apply(self, input_, bias)
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py", line 511, in apply
ERROR 01-06 15:47:24 engine.py:366]     return scheme.apply_weights(layer, x, bias=bias)
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_24.py", line 172, in apply_weights
ERROR 01-06 15:47:24 engine.py:366]     out = ops.cutlass_scaled_sparse_mm(a=q_input,
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/_custom_ops.py", line 628, in cutlass_scaled_sparse_mm
ERROR 01-06 15:47:24 engine.py:366]     torch.ops._C.cutlass_scaled_sparse_mm(out, a, bt_nzs, bt_meta, scale_a,
ERROR 01-06 15:47:24 engine.py:366]   File "/opt/conda/lib/python3.10/site-packages/torch/_ops.py", line 1116, in __call__
ERROR 01-06 15:47:24 engine.py:366]     return self._op(*args, **(kwargs or {}))
ERROR 01-06 15:47:24 engine.py:366] RuntimeError: Error Internal
ERROR 01-06 15:47:24 engine.py:366] 
ERROR 01-06 15:47:24 engine.py:366] The above exception was the direct cause of the following exception:
ERROR 01-06 15:47:24 engine.py:366] 
ERROR 01-06 15:47:24 engine.py:366] Traceback (most recent call last):
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
ERROR 01-06 15:47:24 engine.py:366]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
ERROR 01-06 15:47:24 engine.py:366]     return cls(ipc_path=ipc_path,
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/engine/multiprocessing/engine.py", line 71, in __init__
ERROR 01-06 15:47:24 engine.py:366]     self.engine = LLMEngine(*args, **kwargs)
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/engine/llm_engine.py", line 276, in __init__
ERROR 01-06 15:47:24 engine.py:366]     self._initialize_kv_caches()
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/engine/llm_engine.py", line 416, in _initialize_kv_caches
ERROR 01-06 15:47:24 engine.py:366]     self.model_executor.determine_num_available_blocks())
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/executor/gpu_executor.py", line 68, in determine_num_available_blocks
ERROR 01-06 15:47:24 engine.py:366]     return self.driver_worker.determine_num_available_blocks()
ERROR 01-06 15:47:24 engine.py:366]   File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 01-06 15:47:24 engine.py:366]     return func(*args, **kwargs)
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/worker/worker.py", line 202, in determine_num_available_blocks
ERROR 01-06 15:47:24 engine.py:366]     self.model_runner.profile_run()
ERROR 01-06 15:47:24 engine.py:366]   File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 01-06 15:47:24 engine.py:366]     return func(*args, **kwargs)
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/worker/model_runner.py", line 1331, in profile_run
ERROR 01-06 15:47:24 engine.py:366]     self.execute_model(model_input, kv_caches, intermediate_tensors)
ERROR 01-06 15:47:24 engine.py:366]   File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 01-06 15:47:24 engine.py:366]     return func(*args, **kwargs)
ERROR 01-06 15:47:24 engine.py:366]   File "/ossfs/workspace/ant_vllm/vllm/worker/model_runner_base.py", line 146, in _wrapper
ERROR 01-06 15:47:24 engine.py:366]     raise type(err)(f"Error in model execution: "
ERROR 01-06 15:47:24 engine.py:366] RuntimeError: Error in model execution: Error Internal
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/ossfs/workspace/ant_vllm/vllm/worker/model_runner_base.py", line 116, in _wrapper
    return func(*args, **kwargs)
  File "/ossfs/workspace/ant_vllm/vllm/worker/model_runner.py", line 1691, in execute_model
    hidden_or_intermediate_states = model_executable(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ossfs/workspace/ant_vllm/vllm/model_executor/models/qwen2.py", line 477, in forward
    hidden_states = self.model(input_ids, positions, kv_caches,
  File "/ossfs/workspace/ant_vllm/vllm/compilation/decorators.py", line 168, in __call__
    return self.forward(*args, **kwargs)
  File "/ossfs/workspace/ant_vllm/vllm/model_executor/models/qwen2.py", line 340, in forward
    hidden_states, residual = layer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ossfs/workspace/ant_vllm/vllm/model_executor/models/qwen2.py", line 247, in forward
    hidden_states = self.self_attn(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ossfs/workspace/ant_vllm/vllm/model_executor/models/qwen2.py", line 173, in forward
    qkv, _ = self.qkv_proj(hidden_states)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/ossfs/workspace/ant_vllm/vllm/model_executor/layers/linear.py", line 373, in forward
    output_parallel = self.quant_method.apply(self, input_, bias)
  File "/ossfs/workspace/ant_vllm/vllm/model_executor/layers/quantization/compressed_tensors/compressed_tensors.py", line 511, in apply
    return scheme.apply_weights(layer, x, bias=bias)
  File "/ossfs/workspace/ant_vllm/vllm/model_executor/layers/quantization/compressed_tensors/schemes/compressed_tensors_24.py", line 172, in apply_weights
    out = ops.cutlass_scaled_sparse_mm(a=q_input,
  File "/ossfs/workspace/ant_vllm/vllm/_custom_ops.py", line 628, in cutlass_scaled_sparse_mm
    torch.ops._C.cutlass_scaled_sparse_mm(out, a, bt_nzs, bt_meta, scale_a,
  File "/opt/conda/lib/python3.10/site-packages/torch/_ops.py", line 1116, in __call__
    return self._op(*args, **(kwargs or {}))
RuntimeError: Error Internal

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/ossfs/workspace/ant_vllm/vllm/engine/multiprocessing/engine.py", line 368, in run_mp_engine
    raise e
  File "/ossfs/workspace/ant_vllm/vllm/engine/multiprocessing/engine.py", line 357, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
  File "/ossfs/workspace/ant_vllm/vllm/engine/multiprocessing/engine.py", line 119, in from_engine_args
    return cls(ipc_path=ipc_path,
  File "/ossfs/workspace/ant_vllm/vllm/engine/multiprocessing/engine.py", line 71, in __init__
    self.engine = LLMEngine(*args, **kwargs)
  File "/ossfs/workspace/ant_vllm/vllm/engine/llm_engine.py", line 276, in __init__
    self._initialize_kv_caches()
  File "/ossfs/workspace/ant_vllm/vllm/engine/llm_engine.py", line 416, in _initialize_kv_caches
    self.model_executor.determine_num_available_blocks())
  File "/ossfs/workspace/ant_vllm/vllm/executor/gpu_executor.py", line 68, in determine_num_available_blocks
    return self.driver_worker.determine_num_available_blocks()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/ossfs/workspace/ant_vllm/vllm/worker/worker.py", line 202, in determine_num_available_blocks
    self.model_runner.profile_run()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/ossfs/workspace/ant_vllm/vllm/worker/model_runner.py", line 1331, in profile_run
    self.execute_model(model_input, kv_caches, intermediate_tensors)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/ossfs/workspace/ant_vllm/vllm/worker/model_runner_base.py", line 146, in _wrapper
    raise type(err)(f"Error in model execution: "
RuntimeError: Error in model execution: Error Internal
[rank0]:[W106 15:47:25.908723004 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<MQLLMEngineClient.run_output_handler_loop() done, defined at /ossfs/workspace/ant_vllm/vllm/engine/multiprocessing/client.py:178> exception=ZMQError('Operation not supported')>
Traceback (most recent call last):
  File "/ossfs/workspace/ant_vllm/vllm/engine/multiprocessing/client.py", line 184, in run_output_handler_loop
    while await self.output_socket.poll(timeout=VLLM_RPC_TIMEOUT
  File "/opt/conda/lib/python3.10/site-packages/zmq/_future.py", line 400, in poll
    raise _zmq.ZMQError(_zmq.ENOTSUP)
zmq.error.ZMQError: Operation not supported
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<MQLLMEngineClient.run_output_handler_loop() done, defined at /ossfs/workspace/ant_vllm/vllm/engine/multiprocessing/client.py:178> exception=ZMQError('Operation not supported')>
Traceback (most recent call last):
  File "/ossfs/workspace/ant_vllm/vllm/engine/multiprocessing/client.py", line 184, in run_output_handler_loop
    while await self.output_socket.poll(timeout=VLLM_RPC_TIMEOUT
  File "/opt/conda/lib/python3.10/site-packages/zmq/_future.py", line 400, in poll
    raise _zmq.ZMQError(_zmq.ENOTSUP)
zmq.error.ZMQError: Operation not supported
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<MQLLMEngineClient.run_output_handler_loop() done, defined at /ossfs/workspace/ant_vllm/vllm/engine/multiprocessing/client.py:178> exception=ZMQError('Operation not supported')>
Traceback (most recent call last):
  File "/ossfs/workspace/ant_vllm/vllm/engine/multiprocessing/client.py", line 184, in run_output_handler_loop
    while await self.output_socket.poll(timeout=VLLM_RPC_TIMEOUT
  File "/opt/conda/lib/python3.10/site-packages/zmq/_future.py", line 400, in poll
    raise _zmq.ZMQError(_zmq.ENOTSUP)
zmq.error.ZMQError: Operation not supported
Traceback (most recent call last):
  File "/opt/conda/bin/vllm", line 8, in <module>
    sys.exit(main())
  File "/ossfs/workspace/ant_vllm/vllm/scripts.py", line 201, in main
    args.dispatch_function(args)
  File "/ossfs/workspace/ant_vllm/vllm/scripts.py", line 42, in serve
    uvloop.run(run_server(args))
  File "/opt/conda/lib/python3.10/site-packages/uvloop/__init__.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/opt/conda/lib/python3.10/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "/ossfs/workspace/ant_vllm/vllm/entrypoints/openai/api_server.py", line 671, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/opt/conda/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/ossfs/workspace/ant_vllm/vllm/entrypoints/openai/api_server.py", line 114, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/opt/conda/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/ossfs/workspace/ant_vllm/vllm/entrypoints/openai/api_server.py", line 219, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.

**Comment by DefTruth** [comment]
same error, can you have any idea to fix this error: RuntimeError: Error Internal ?

**Comment by leoyuppieqnew** [comment]
> same error, can you have any idea to fix this error: cutlass_scaled_mm, RuntimeError: Error Internal ?

I recompiled it last week using the code from the master branch, and the problem was fixed.
