### ISSUE TITLE
[Bug]: “limit-mm-per-prompt” can't be set correctly as in 0.6.5

### ISSUE THREAD

**Issue by Yukino256** [vllm-project/vllm#11842]
### Your current environment

```text
vllm==0.6.6.post1
cuda==12.4
ubuntu==22.04
```

### 🐛 Describe the bug

when I run the following server command in v0.6.6.post1:

```bash
python -m vllm.entrypoints.openai.api_server \
--model "./Qwen2-VL-7B-Instruct" \
--served-model-name "Qwen2-VL-7B-Instruct" \
--device cuda \
--limit-mm-per-prompt image=8 
```

it warns that:

```text
WARNING 01-08 18:59:14 model_runner.py:1279] Computed max_num_seqs (min(256, 32768 // 180224)) to be less than 1. Setting it to the minimum value of 1.
Token indices sequence length is longer than the specified maximum sequence length for this model (163840 > 32768). Running this sequence through the model will result in indexing errors
WARNING 01-08 18:59:32 processing.py:878] The context length (32768) of the model is too short to hold the multi-modal embeddings in the worst case (163840 tokens in total, out of which {'image': 163840} are reserved for multi-modal embeddings). This may cause certain multi-modal inputs to fail during inference, even when the input text is short. To avoid this, you should increase `max_model_len`, reduce `max_num_seqs`, and/or reduce `mm_counts`.
```
and the the cuda error occurs:

```text
......
../aten/src/ATen/native/cuda/IndexKernel.cu:93: operator(): block: [8274,0,0], thread: [123,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:93: operator(): block: [8274,0,0], thread: [124,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:93: operator(): block: [8274,0,0], thread: [125,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:93: operator(): block: [8274,0,0], thread: [126,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:93: operator(): block: [8274,0,0], thread: [127,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
INFO 01-08 19:15:31 model_runner_base.py:120] Writing input of failed execution to /tmp/err_execute_model_input_20250108-191531.pkl...
WARNING 01-08 19:15:31 model_runner_base.py:143] Failed to pickle inputs of failed execution: CUDA error: device-side assert triggered
WARNING 01-08 19:15:31 model_runner_base.py:143] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
.....
WARNING 01-08 19:15:31 model_runner_base.py:143] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
WARNING 01-08 19:15:31 model_runner_base.py:143] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
WARNING 01-08 19:15:31 model_runner_base.py:143] 
```

But when i degrade the vllm to 0.6.5, everything runs ok.
And i tried post 4 images to the server, it works well, and didn't occur any OOM error.

Is their any reasons why 0.6.6 pre-compute multi-modal token counts ? It seems that the compute method is too restrictive, or not support Naive Dynamic Resolution ?

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
The profiling code has been updated since then to be less restrictive. Can you try using latest main?

**Comment by andrePankraz** [comment]
same problem with v0.6.6.post1.
even setting to images=4 creates these problems, even though with 0.6.4 i could set it to 8 and it worked just fine for 8.

**Comment by DarkLight1337** [comment]
> same problem with v0.6.6.post1.

Can you update to latest main?

**Comment by andrePankraz** [comment]
> > same problem with v0.6.6.post1.
> 
> Can you update to latest main?

Sry must always wait for Docker release - and there  v0.6.6.post1 is the final one.

On a sidenote I dont understand these checks at all - they dont seem to make much sense for Qwen VL2 ?
Qwen translates images into patch-tokens in a dynamic way.
28x28 pixels are a patch (14x14 and 2x2 pooling). So 280x280 pxl image are around 100 tokens. 2800x2800 are around 10_000 tokens - which is quite a large image and not the default case by far as VLLM input (may be for single OCR-sytle images). So I can at max process 3 images 2800x2800 in the default context window with some text-task on top. But I could pocess like dozens of normal sized images - or many low resolution video frames. What is your heuristic assumption for image sizes?! We cannot really apply pre-flight heuristics to text (only max context window size) - why do we even try it for images? Either the context window gets too large during inference or it doesn't - we cannot really tell before ?
You could easily change the "context window too large" during inference message to signal, that the problem was the image/video input - and not have this strange "image number" and additional-checks thing?

**Comment by DarkLight1337** [comment]
We have Docker image for latest code: https://docs.vllm.ai/en/latest/getting_started/installation/gpu-cuda.html#install-the-latest-code-using-docker

> What is your heuristic assumption for image sizes?!

To avoid false negatives, we assume the maximum possible input image size after HF processor is applied to the input when calculating how many images can fix inside the context.

**Comment by andrePankraz** [comment]
> We have Docker image for latest code: https://docs.vllm.ai/en/latest/getting_started/installation/gpu-cuda.html#install-the-latest-code-using-docker
> 
> > What is your heuristic assumption for image sizes?!
> 
> To avoid false negatives, we assume the maximum possible input image size after HF processor is applied to the input when calculating how many images can fix inside the context.

But does this make sense as a pre-check during startup?
Typically with normal images you rarely input images that go to the range of "maximum possible input image size after HF processor is applied". Most images are much smaller with less tokens! So it's no wonder that you only can fit like 3 images into 32k default context window.  Yes - you must know what you are doing in the client and it's  a bit more unclear, why you context window size gets too large - but this could easily be differentiated during inference time error messaging.

This feels is like a "max sentences setting" and you check before during startup: Oh you can only enter 3 sentences, because the max sentence size is 10.000 tokens.

But may be I get the idea wrong.

**Comment by DarkLight1337** [comment]
I agree, that is why we only emit a warning (instead of crashing) if we find that the inputs can potentially exceed the max context length. Actually, even before this version, we profiled the model based on the maximum possible image size, but we didn't have checks to verify this.

**Comment by DarkLight1337** [comment]
We do have plans to expand the limit_mm_per_prompt option in the future to allow users to specify the maximum image size, among other things

**Comment by prompteus** [comment]
Hi @DarkLight1337,
I've also stumbled upon this issue with `Qwen/Qwen2.5-VL-7B-Instruct`.

How do I interpret the warning: "Computed max_num_seqs (min(256, 5120 [//](https://github.com/vllm-project/vllm/issues/11842) 16384)) to be less than 1. Setting it to the minimum value of 1."

For completeness, vLLM logs: "Maximum concurrency for 512 tokens per request: 864.12x"

Does this mean that the vLLM instance will refuse to batch inputs in offline inference?

**Comment by redagavin** [comment]
@DarkLight1337 How can I override the maximum multi-modal (image) tokens? I would like to set it manually so that I can do batch inference without increasing `max_model_len`.

**Comment by DarkLight1337** [comment]
The number of multi-modal tokens is based on `limit-mm-per-prompt` (e.g. more image means more tokens allocated to images), but ultimately it is limited by `max_model_len`.

**Comment by redagavin** [comment]
@DarkLight1337 Thanks for your prompt response. Yes, I understand that. What I want to change is the number of (max) tokens allocated to each image so that I can have both a small max_model_len and batch inference.

**Comment by 1556900941lizerui** [comment]
> The profiling code has been updated since then to be less restrictive. Can you try using latest main?配置文件代码自那时起已更新，限制更少。您能否尝试使用最新的主分支？

我现在使用了最新的版本，在ARM架构下编译，但是仍然会有这个问题，我使用的模型是Qwen2-vl,vllm版本信息如下：
root@24910fd4f95f:/workspace/vllm# pip show vllm
Name: vllm
Version: 0.7.4.dev0+ged6e9075.d20250307.cu122
Summary: A high-throughput and memory-efficient inference and serving engine for LLMs
Home-page: https://github.com/vllm-project/vllm
Author: vLLM Team
Author-email: 
License: Apache License

**Comment by DarkLight1337** [comment]
> > The profiling code has been updated since then to be less restrictive. Can you try using latest main?配置文件代码自那时起已更新，限制更少。您能否尝试使用最新的主分支？
> 
> 我现在使用了最新的版本，在ARM架构下编译，但是仍然会有这个问题，我使用的模型是Qwen2-vl,vllm版本信息如下：
> root@24910fd4f95f:/workspace/vllm# pip show vllm
> Name: vllm
> Version: 0.7.4.dev0+ged6e9075.d20250307.cu122
> Summary: A high-throughput and memory-efficient inference and serving engine for LLMs
> Home-page: https://github.com/vllm-project/vllm
> Author: vLLM Team
> Author-email: 
> License: Apache License

Can you share the logs?

**Comment by 1556900941lizerui** [comment]
> > > The profiling code has been updated since then to be less restrictive. Can you try using latest main?配置文件代码自那时起已更新，限制更少。您能否尝试使用最新的主分支？
> > 
> > 
> > 我现在使用了最新的版本，在ARM架构下编译，但是仍然会有这个问题，我使用的模型是Qwen2-vl,vllm版本信息如下：
> > root@24910fd4f95f:/workspace/vllm# pip show vllm
> > Name: vllm
> > Version: 0.7.4.dev0+ged6e9075.d20250307.cu122
> > Summary: A high-throughput and memory-efficient inference and serving engine for LLMs
> > Home-page: https://github.com/vllm-project/vllm
> > Author: vLLM Team
> > Author-email:
> > License: Apache License
> 
> Can you share the logs?

NFO 03-07 11:12:33 model_runner.py:1115] Loading model weights took 6.4649 GB
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
WARNING 03-07 11:12:34 model_runner.py:1288] Computed max_num_seqs (min(256, 5120 // 32768)) to be less than 1. Setting it to the minimum value of 1.
It looks like you are trying to rescale already rescaled images. If the input images have pixel values between 0 and 1, set `do_rescale=False` to avoid rescaling them again.
WARNING 03-07 11:12:39 profiling.py:192] The context length (5120) of the model is too short to hold the multi-modal embeddings in the worst case (32768 tokens in total, out of which {'image': 16384, 'video': 16384} are reserved for multi-modal embeddings). This may cause certain multi-modal inputs to fail during inference, even when the input text is short. To avoid this, you should increase `max_model_len`, reduce `max_num_seqs`, and/or reduce `mm_counts`.

**Comment by 1556900941lizerui** [comment]
> > > The profiling code has been updated since then to be less restrictive. Can you try using latest main?配置文件代码自那时起已更新，限制更少。您能否尝试使用最新的主分支？
> > 
> > 
> > 我现在使用了最新的版本，在ARM架构下编译，但是仍然会有这个问题，我使用的模型是Qwen2-vl,vllm版本信息如下：
> > root@24910fd4f95f:/workspace/vllm# pip show vllm
> > Name: vllm
> > Version: 0.7.4.dev0+ged6e9075.d20250307.cu122
> > Summary: A high-throughput and memory-efficient inference and serving engine for LLMs
> > Home-page: https://github.com/vllm-project/vllm
> > Author: vLLM Team
> > Author-email:
> > License: Apache License
> 
> Can you share the logs?

I have a question, can I force it not to use Xformers for acceleration? Xformers do not support ARM architecture, and I don't want to recompile flash-attn, as it takes too much time

**Comment by DarkLight1337** [comment]
> > > > The profiling code has been updated since then to be less restrictive. Can you try using latest main?配置文件代码自那时起已更新，限制更少。您能否尝试使用最新的主分支？
> > > 
> > > 
> > > 我现在使用了最新的版本，在ARM架构下编译，但是仍然会有这个问题，我使用的模型是Qwen2-vl,vllm版本信息如下：
> > > root@24910fd4f95f:/workspace/vllm# pip show vllm
> > > Name: vllm
> > > Version: 0.7.4.dev0+ged6e9075.d20250307.cu122
> > > Summary: A high-throughput and memory-efficient inference and serving engine for LLMs
> > > Home-page: https://github.com/vllm-project/vllm
> > > Author: vLLM Team
> > > Author-email:
> > > License: Apache License
> > 
> > Can you share the logs?
> 
> NFO 03-07 11:12:33 model_runner.py:1115] Loading model weights took 6.4649 GB
> Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
> WARNING 03-07 11:12:34 model_runner.py:1288] Computed max_num_seqs (min(256, 5120 // 32768)) to be less than 1. Setting it to the minimum value of 1.
> It looks like you are trying to rescale already rescaled images. If the input images have pixel values between 0 and 1, set `do_rescale=False` to avoid rescaling them again.
> WARNING 03-07 11:12:39 profiling.py:192] The context length (5120) of the model is too short to hold the multi-modal embeddings in the worst case (32768 tokens in total, out of which {'image': 16384, 'video': 16384} are reserved for multi-modal embeddings). This may cause certain multi-modal inputs to fail during inference, even when the input text is short. To avoid this, you should increase `max_model_len`, reduce `max_num_seqs`, and/or reduce `mm_counts`.

I mean the error logs as well.

**Comment by DarkLight1337** [comment]
This looks like a different error from the original post. It seems that your pytorch version is not compatible with what is being used for `torch.compile`. Please check out [this section of the troubleshooting guide](https://docs.vllm.ai/en/latest/getting_started/troubleshooting.html#torch-compile-error).

**Comment by 1556900941lizerui** [comment]
> This looks like a different error from the original post. It seems that your pytorch version is not compatible with what is being used for `torch.compile`. Please check out [this section of the troubleshooting guide](https://docs.vllm.ai/en/latest/getting_started/troubleshooting.html#torch-compile-error).

Yes, because I am using the nightly version, I resolved this issue by modifying the source code, but I encountered a new bug.
ERROR 03-07 14:35:07 core.py:291] EngineCore hit an exception: Traceback (most recent call last):
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/v1/engine/core.py", line 283, in run_engine_core
ERROR 03-07 14:35:07 core.py:291]     engine_core = EngineCoreProc(*args, **kwargs)
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/v1/engine/core.py", line 238, in __init__
ERROR 03-07 14:35:07 core.py:291]     super().__init__(vllm_config, executor_class, log_stats)
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/v1/engine/core.py", line 59, in __init__
ERROR 03-07 14:35:07 core.py:291]     num_gpu_blocks, num_cpu_blocks = self._initialize_kv_caches(
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/v1/engine/core.py", line 99, in _initialize_kv_caches
ERROR 03-07 14:35:07 core.py:291]     available_gpu_memory = self.model_executor.determine_available_memory()
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/v1/executor/abstract.py", line 61, in determine_available_memory
ERROR 03-07 14:35:07 core.py:291]     output = self.collective_rpc("determine_available_memory")
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
ERROR 03-07 14:35:07 core.py:291]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/utils.py", line 2196, in run_method
ERROR 03-07 14:35:07 core.py:291]     return func(*args, **kwargs)
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 03-07 14:35:07 core.py:291]     return func(*args, **kwargs)
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/v1/worker/gpu_worker.py", line 154, in determine_available_memory
ERROR 03-07 14:35:07 core.py:291]     self.model_runner.profile_run()
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/v1/worker/gpu_model_runner.py", line 1301, in profile_run
ERROR 03-07 14:35:07 core.py:291]     hidden_states = self._dummy_run(self.max_num_tokens,
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 03-07 14:35:07 core.py:291]     return func(*args, **kwargs)
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/v1/worker/gpu_model_runner.py", line 1168, in _dummy_run
ERROR 03-07 14:35:07 core.py:291]     hidden_states = model(
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
ERROR 03-07 14:35:07 core.py:291]     return self._call_impl(*args, **kwargs)
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
ERROR 03-07 14:35:07 core.py:291]     return forward_call(*args, **kwargs)
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/model_executor/models/qwen2_vl.py", line 1372, in forward
ERROR 03-07 14:35:07 core.py:291]     hidden_states = self.language_model.model(
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/compilation/decorators.py", line 238, in __call__
ERROR 03-07 14:35:07 core.py:291]     output = self.compiled_callable(*args, **kwargs)
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 580, in _fn
ERROR 03-07 14:35:07 core.py:291]     raise e.remove_dynamo_frames() from None  # see TORCHDYNAMO_VERBOSE=1
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1494, in _call_user_compiler
ERROR 03-07 14:35:07 core.py:291]     raise BackendCompilerFailed(
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/output_graph.py", line 1473, in _call_user_compiler
ERROR 03-07 14:35:07 core.py:291]     compiled_fn = compiler_fn(gm, self.example_inputs())
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
ERROR 03-07 14:35:07 core.py:291]     compiled_gm = compiler_fn(gm, example_inputs)
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_dynamo.py", line 130, in __call__
ERROR 03-07 14:35:07 core.py:291]     compiled_gm = compiler_fn(gm, example_inputs)
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/__init__.py", line 2359, in __call__
ERROR 03-07 14:35:07 core.py:291]     return self.compiler_fn(model_, inputs_, **self.kwargs)
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/compilation/backends.py", line 447, in __call__
ERROR 03-07 14:35:07 core.py:291]     PiecewiseCompileInterpreter(self.split_gm, submod_names_to_compile,
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/compilation/backends.py", line 245, in run
ERROR 03-07 14:35:07 core.py:291]     return super().run(*fake_args)
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/fx/interpreter.py", line 167, in run
ERROR 03-07 14:35:07 core.py:291]     self.env[node] = self.run_node(node)
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/fx/interpreter.py", line 230, in run_node
ERROR 03-07 14:35:07 core.py:291]     return getattr(self, n.op)(n.target, args, kwargs)
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/compilation/backends.py", line 260, in call_module
ERROR 03-07 14:35:07 core.py:291]     compiled_graph_for_general_shape = self.vllm_backend.\
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/compilation/backends.py", line 121, in compile
ERROR 03-07 14:35:07 core.py:291]     compiled_graph, handle = self.compiler.compile(
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/compilation/compiler_interface.py", line 262, in compile
ERROR 03-07 14:35:07 core.py:291]     compiled_graph = compile_fx(
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1566, in compile_fx
ERROR 03-07 14:35:07 core.py:291]     return compile_fx(
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1896, in compile_fx
ERROR 03-07 14:35:07 core.py:291]     return aot_autograd(
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/backends/common.py", line 83, in __call__
ERROR 03-07 14:35:07 core.py:291]     cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 1170, in aot_module_simplified
ERROR 03-07 14:35:07 core.py:291]     compiled_fn = AOTAutogradCache.load(
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/autograd_cache.py", line 754, in load
ERROR 03-07 14:35:07 core.py:291]     compiled_fn = dispatch_and_compile()
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 1155, in dispatch_and_compile
ERROR 03-07 14:35:07 core.py:291]     compiled_fn, _ = create_aot_dispatcher_function(
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 582, in create_aot_dispatcher_function
ERROR 03-07 14:35:07 core.py:291]     return _create_aot_dispatcher_function(
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 832, in _create_aot_dispatcher_function
ERROR 03-07 14:35:07 core.py:291]     compiled_fn, fw_metadata = compiler_fn(
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 201, in aot_dispatch_base
ERROR 03-07 14:35:07 core.py:291]     compiled_fw = compiler(fw_module, updated_flat_args)
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_functorch/aot_autograd.py", line 491, in __call__
ERROR 03-07 14:35:07 core.py:291]     return self.compiler_fn(gm, example_inputs)
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 1773, in fw_compiler_base
ERROR 03-07 14:35:07 core.py:291]     return inner_compile(
ERROR 03-07 14:35:07 core.py:291]   File "/usr/lib/python3.10/contextlib.py", line 79, in inner
ERROR 03-07 14:35:07 core.py:291]     return func(*args, **kwds)
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/compilation/compiler_interface.py", line 213, in hijacked_compile_fx_inner
ERROR 03-07 14:35:07 core.py:291]     output = torch._inductor.compile_fx.compile_fx_inner(
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 578, in compile_fx_inner
ERROR 03-07 14:35:07 core.py:291]     return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/repro/after_aot.py", line 102, in debug_wrapper
ERROR 03-07 14:35:07 core.py:291]     inner_compiled_fn = compiler_fn(gm, example_inputs)
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_fx.py", line 658, in _compile_fx_inner
ERROR 03-07 14:35:07 core.py:291]     (key_info, cache_info) = FxGraphCache.prepare_key(
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 1240, in prepare_key
ERROR 03-07 14:35:07 core.py:291]     key, debug_lines = compiled_fx_graph_hash(
ERROR 03-07 14:35:07 core.py:291]   File "/workspace/vllm/vllm/compilation/compiler_interface.py", line 224, in hijack_compiled_fx_graph_hash
ERROR 03-07 14:35:07 core.py:291]     out = compiled_fx_graph_hash(*args, **kwargs)
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 872, in compiled_fx_graph_hash
ERROR 03-07 14:35:07 core.py:291]     details = FxGraphHashDetails(gm, example_inputs, fx_kwargs, inputs_to_check)
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 845, in __init__
ERROR 03-07 14:35:07 core.py:291]     self.post_grad_custom_post_pass = self._get_custom_pass_detail(
ERROR 03-07 14:35:07 core.py:291]   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/codecache.py", line 854, in _get_custom_pass_detail
ERROR 03-07 14:35:07 core.py:291]     assert isinstance(custom_pass, CustomGraphPass)
ERROR 03-07 14:35:07 core.py:291] torch._dynamo.exc.BackendCompilerFailed: backend='<vllm.compilation.backends.VllmBackend object at 0xfffe119be4d0>' raised:
ERROR 03-07 14:35:07 core.py:291] AssertionError: While executing %submod_0 : [num_users=4] = call_module[target=submod_0](args = (%l_inputs_embeds_, %s0, %l_self_modules_layers_modules_0_modules_input_layernorm_parameters_weight_, %l_self_modules_layers_modules_0_modules_self_attn_modules_qkv_proj_parameters_qweight_, %l_self_modules_layers_modules_0_modules_self_attn_modules_qkv_proj_parameters_scales_, %l_self_modules_layers_modules_0_modules_self_attn_modules_qkv_proj_parameters_qzeros_, %l_self_modules_layers_modules_0_modules_self_attn_modules_qkv_proj_parameters_g_idx_, %l_self_modules_layers_modules_0_modules_self_attn_modules_qkv_proj_parameters_g_idx_sort_indices_, %l_self_modules_layers_modules_0_modules_self_attn_modules_qkv_proj_quant_method_kernel_workspace, %l_self_modules_layers_modules_0_modules_self_attn_modules_qkv_proj_parameters_bias_, %l_self_modules_layers_modules_0_modules_self_attn_modules_rotary_emb_buffers_cos_sin_cache_, %l_positions_, %s2), kwargs = {})

**Comment by DarkLight1337** [comment]
Can you open a new issue for this? It still looks like an error related to `torch.compile`.

**Comment by 1556900941lizerui** [comment]
> Can you open a new issue for this? It still looks like an error related to `torch.compile`.

Of course, I will submit a new issue later, but I still have a question to ask. Because my server expired after 12 o'clock, I can no longer perform environment configuration. I manually commented out this part of the code to stop the warning about setting max_seq_num to 1, but I still keep getting the following warning. After actual testing, I found that the concurrency processing speed has not increased either. I'm not sure if it's a device performance issue, but is it feasible to comment out this part?

![Image](https://github.com/user-attachments/assets/90ae0888-ac30-4089-aff3-86ae9b8a17be)

**Comment by DarkLight1337** [comment]
You can ignore the warning. It just means it's possible for OOM to occur during inference.

**Comment by 1556900941lizerui** [comment]
You can ignore the warning. It just means it's possible for OOM to occur during inference.

Thank you, but does this mean that I have resolved the issue of increasing concurrency processing capability by setting max_num_seqs to 1, even though there was no speed improvement in my own tests?

**Comment by DarkLight1337** [comment]
`max_num_seqs=1` means the batch size is capped to 1, so no concurrency can happen. This is because there is not enough memory to fit additional batches.

**Comment by 1556900941lizerui** [comment]
> `max_num_seqs=1` means the batch size is capped to 1, so no concurrency can happen (at least inside `model.forward`). This is because there is not enough memory to fit additional batches.

OK，Thanks
