### ISSUE TITLE
[Bug]:  vLLM gets stuck at pynccl.py during startup

### ISSUE THREAD

**Issue by KatUsagi** [vllm-project/vllm#12292]
### Your current environment

<summary>When I start vLLM, it gets stuck at a step in pynccl.py and cannot proceed to model loading. At this point, I have to enable the export NCCL_P2P_DISABLE=1 parameter to load the model, but this significantly reduces inference speed. After rebooting the server, vLLM can start normally again. I am unsure of the reason for this issue and how to resolve it. Here is the version information of my server, NVIDIA driver, NCCL, and PyTorch, along with specific log details:</summary>

<details> 
Server：Ubuntu 24.04 LTS
nVidia Driver：
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 560.28.03              Driver Version: 560.28.03      CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+

nvidia-smi topo -m
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    NIC0    NIC1    NIC2    NIC3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PIX     PXB     SYS     SYS     SYS     PXB     PXB     SYS     SYS     0-27,56-83      0               N/A
GPU1    PIX      X      PXB     SYS     SYS     SYS     PXB     PXB     SYS     SYS     0-27,56-83      0               N/A
GPU2    PXB     PXB      X      SYS     SYS     SYS     PXB     PXB     SYS     SYS     0-27,56-83      0               N/A
GPU3    SYS     SYS     SYS      X      PXB     PXB     SYS     SYS     PXB     PXB     28-55,84-111    1               N/A
GPU4    SYS     SYS     SYS     PXB      X      PXB     SYS     SYS     PIX     PIX     28-55,84-111    1               N/A
GPU5    SYS     SYS     SYS     PXB     PXB      X      SYS     SYS     PXB     PXB     28-55,84-111    1               N/A
NIC0    PXB     PXB     PXB     SYS     SYS     SYS      X      PIX     SYS     SYS
NIC1    PXB     PXB     PXB     SYS     SYS     SYS     PIX      X      SYS     SYS
NIC2    SYS     SYS     SYS     PXB     PIX     PXB     SYS     SYS      X      PIX
NIC3    SYS     SYS     SYS     PXB     PIX     PXB     SYS     SYS     PIX      X 

nccl version: 2.21.5
torch version: 2.5.1+cu124
torch.version.cuda: 12.4

Abnormal startup log information：
(vllm) shujubu@gpu05:~$ vllm serve /data/shujubu/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B --tensor-parallel-size 4 --max-model-len 16384 --enforce-eager
INFO 01-21 17:15:39 api_server.py:339] vLLM API server version 0.5.4
INFO 01-21 17:15:39 api_server.py:340] args: Namespace(model_tag='/data/shujubu/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B', host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, model='/data/shujubu/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=16384, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=4, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=True, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None, dispatch_function=<function serve at 0x7579968f6f80>)
WARNING 01-21 17:15:39 config.py:1454] Casting torch.bfloat16 to torch.float16.
INFO 01-21 17:15:42 config.py:729] Defaulting to use mp for distributed inference
INFO 01-21 17:15:42 llm_engine.py:174] Initializing an LLM engine (v0.5.4) with config: model='/data/shujubu/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B', speculative_config=None, tokenizer='/data/shujubu/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=16384, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=/data/shujubu/models/deepseek-ai/DeepSeek-R1-Distill-Qwen-32B, use_v2_block_manager=False, enable_prefix_caching=False)
WARNING 01-21 17:15:43 multiproc_gpu_executor.py:59] Reducing Torch parallelism from 56 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 01-21 17:15:43 custom_cache_manager.py:17] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
(VllmWorkerProcess pid=23041) INFO 01-21 17:15:43 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=23042) INFO 01-21 17:15:43 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=23043) INFO 01-21 17:15:43 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
INFO 01-21 17:15:44 utils.py:841] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=23041) INFO 01-21 17:15:44 utils.py:841] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=23043) INFO 01-21 17:15:44 utils.py:841] Found nccl from library libnccl.so.2
INFO 01-21 17:15:44 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=23041) INFO 01-21 17:15:44 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=23042) INFO 01-21 17:15:44 utils.py:841] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=23043) INFO 01-21 17:15:44 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=23042) INFO 01-21 17:15:44 pynccl.py:63] vLLM is using nccl==2.20.5

(stucked here).....

nccl log detail:
(VllmWorkerProcess pid=24153) INFO 01-21 17:23:12 pynccl.py:63] vLLM is using nccl==2.20.5 gpu05:24037:24037 [0] NCCL INFO Bootstrap : Using bond0:172.30.52.37<0> gpu05:24037:24037 [0] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation gpu05:24037:24037 [0] NCCL INFO cudaDriverVersion 12060 NCCL version 2.20.5+cuda12.4 gpu05:24154:24154 [3] NCCL INFO cudaDriverVersion 12060 gpu05:24154:24154 [3] NCCL INFO Bootstrap : Using bond0:172.30.52.37<0> gpu05:24154:24154 [3] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation gpu05:24152:24152 [1] NCCL INFO cudaDriverVersion 12060 gpu05:24152:24152 [1] NCCL INFO Bootstrap : Using bond0:172.30.52.37<0> gpu05:24152:24152 [1] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation gpu05:24153:24153 [2] NCCL INFO cudaDriverVersion 12060 gpu05:24153:24153 [2] NCCL INFO Bootstrap : Using bond0:172.30.52.37<0> gpu05:24153:24153 [2] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation gpu05:24037:24037 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/RoCE [RO]; OOB bond0:172.30.52.37<0> gpu05:24037:24037 [0] NCCL INFO Using non-device net plugin version 0 gpu05:24037:24037 [0] NCCL INFO Using network IB gpu05:24037:24037 [0] NCCL INFO DMA-BUF is available on GPU device 0 gpu05:24154:24154 [3] NCCL INFO NET/IB : Using [0]mlx5_0:1/RoCE [RO]; OOB bond0:172.30.52.37<0> gpu05:24154:24154 [3] NCCL INFO Using non-device net plugin version 0 gpu05:24154:24154 [3] NCCL INFO Using network IB gpu05:24154:24154 [3] NCCL INFO DMA-BUF is available on GPU device 3 gpu05:24152:24152 [1] NCCL INFO NET/IB : Using [0]mlx5_0:1/RoCE [RO]; OOB bond0:172.30.52.37<0> gpu05:24152:24152 [1] NCCL INFO Using non-device net plugin version 0 gpu05:24152:24152 [1] NCCL INFO Using network IB gpu05:24152:24152 [1] NCCL INFO DMA-BUF is available on GPU device 1 gpu05:24153:24153 [2] NCCL INFO NET/IB : Using [0]mlx5_0:1/RoCE [RO]; OOB bond0:172.30.52.37<0> gpu05:24153:24153 [2] NCCL INFO Using non-device net plugin version 0 gpu05:24153:24153 [2] NCCL INFO Using network IB gpu05:24153:24153 [2] NCCL INFO DMA-BUF is available on GPU device 2 gpu05:24152:24152 [1] NCCL INFO comm 0x584005a0c8b0 rank 1 nranks 4 cudaDev 1 nvmlDev 1 busId 50000 commId 0x113a38829bb5d30c - Init START gpu05:24153:24153 [2] NCCL INFO comm 0x584005a0cba0 rank 2 nranks 4 cudaDev 2 nvmlDev 2 busId 53000 commId 0x113a38829bb5d30c - Init START gpu05:24154:24154 [3] NCCL INFO comm 0x584005a0c750 rank 3 nranks 4 cudaDev 3 nvmlDev 3 busId 9d000 commId 0x113a38829bb5d30c - Init START gpu05:24037:24037 [0] NCCL INFO comm 0x584005a0bb90 rank 0 nranks 4 cudaDev 0 nvmlDev 0 busId 4f000 commId 0x113a38829bb5d30c - Init START gpu05:24152:24152 [1] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0. gpu05:24037:24037 [0] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0. gpu05:24152:24152 [1] NCCL INFO Setting affinity for GPU 1 to 0fffff,ff000000,0fffffff gpu05:24152:24152 [1] NCCL INFO NVLS multicast support is not available on dev 1 gpu05:24154:24154 [3] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0. gpu05:24037:24037 [0] NCCL INFO Setting affinity for GPU 0 to 0fffff,ff000000,0fffffff gpu05:24037:24037 [0] NCCL INFO NVLS multicast support is not available on dev 0 gpu05:24153:24153 [2] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0. gpu05:24154:24154 [3] NCCL INFO Setting affinity for GPU 3 to ffff,fff00000,00ffffff,f0000000 gpu05:24154:24154 [3] NCCL INFO NVLS multicast support is not available on dev 3 gpu05:24153:24153 [2] NCCL INFO Setting affinity for GPU 2 to 0fffff,ff000000,0fffffff gpu05:24153:24153 [2] NCCL INFO NVLS multicast support is not available on dev 2 gpu05:24037:24037 [0] NCCL INFO comm 0x584005a0bb90 rank 0 nRanks 4 nNodes 1 localRanks 4 localRank 0 MNNVL 0 gpu05:24154:24154 [3] NCCL INFO comm 0x584005a0c750 rank 3 nRanks 4 nNodes 1 localRanks 4 localRank 3 MNNVL 0 gpu05:24037:24037 [0] NCCL INFO Channel 00/02 : 0 1 2 3 gpu05:24037:24037 [0] NCCL INFO Channel 01/02 : 0 1 2 3 gpu05:24037:24037 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1 gpu05:24037:24037 [0] NCCL INFO P2P Chunksize set to 131072 gpu05:24154:24154 [3] NCCL INFO Trees [0] -1/-1/-1->3->2 [1] -1/-1/-1->3->2 gpu05:24154:24154 [3] NCCL INFO P2P Chunksize set to 131072 gpu05:24152:24152 [1] NCCL INFO comm 0x584005a0c8b0 rank 1 nRanks 4 nNodes 1 localRanks 4 localRank 1 MNNVL 0 gpu05:24153:24153 [2] NCCL INFO comm 0x584005a0cba0 rank 2 nRanks 4 nNodes 1 localRanks 4 localRank 2 MNNVL 0 gpu05:24152:24152 [1] NCCL INFO Trees [0] 2/-1/-1->1->0 [1] 2/-1/-1->1->0 gpu05:24153:24153 [2] NCCL INFO Trees [0] 3/-1/-1->2->1 [1] 3/-1/-1->2->1 gpu05:24152:24152 [1] NCCL INFO P2P Chunksize set to 131072 gpu05:24153:24153 [2] NCCL INFO P2P Chunksize set to 131072 gpu05:24153:24153 [2] NCCL INFO Channel 00 : 2[2] -> 3[3] via SHM/direct/direct gpu05:24153:24153 [2] NCCL INFO Channel 01 : 2[2] -> 3[3] via SHM/direct/direct gpu05:24152:24152 [1] NCCL INFO Channel 00/0 : 1[1] -> 2[2] via P2P/IPC gpu05:24152:24152 [1] NCCL INFO Channel 01/0 : 1[1] -> 2[2] via P2P/IPC gpu05:24037:24037 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[1] via P2P/IPC gpu05:24154:24154 [3] NCCL INFO Channel 00 : 3[3] -> 0[0] via SHM/direct/direct gpu05:24154:24154 [3] NCCL INFO Channel 01 : 3[3] -> 0[0] via SHM/direct/direct gpu05:24037:24037 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[1] via P2P/IPC gpu05:24152:24152 [1] NCCL INFO Connected all rings gpu05:24037:24037 [0] NCCL INFO Connected all rings gpu05:24153:24153 [2] NCCL INFO Connected all rings gpu05:24154:24154 [3] NCCL INFO Connected all rings gpu05:24152:24152 [1] NCCL INFO Channel 00/0 : 1[1] -> 0[0] via P2P/IPC gpu05:24154:24154 [3] NCCL INFO Channel 00 : 3[3] -> 2[2] via SHM/direct/direct gpu05:24154:24154 [3] NCCL INFO Channel 01 : 3[3] -> 2[2] via SHM/direct/direct gpu05:24152:24152 [1] NCCL INFO Channel 01/0 : 1[1] -> 0[0] via P2P/IPC gpu05:24153:24153 [2] NCCL INFO Channel 00/0 : 2[2] -> 1[1] via P2P/IPC gpu05:24153:24153 [2] NCCL INFO Channel 01/0 : 2[2] -> 1[1] via P2P/IPC gpu05:24037:24037 [0] NCCL INFO Connected all trees gpu05:24037:24037 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512 gpu05:24037:24037 [0] NCCL INFO 2 coll channels, 0 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer gpu05:24152:24152 [1] NCCL INFO Connected all trees gpu05:24152:24152 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512 gpu05:24152:24152 [1] NCCL INFO 2 coll channels, 0 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer gpu05:24153:24153 [2] NCCL INFO Connected all trees gpu05:24153:24153 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512 gpu05:24153:24153 [2] NCCL INFO 2 coll channels, 0 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer gpu05:24154:24154 [3] NCCL INFO Connected all trees gpu05:24154:24154 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512 gpu05:24154:24154 [3] NCCL INFO 2 coll channels, 0 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer gpu05:24037:24037 [0] NCCL INFO comm 0x584005a0bb90 rank 0 nranks 4 cudaDev 0 nvmlDev 0 busId 4f000 commId 0x113a38829bb5d30c - Init COMPLETE gpu05:24153:24153 [2] NCCL INFO comm 0x584005a0cba0 rank 2 nranks 4 cudaDev 2 nvmlDev 2 busId 53000 commId 0x113a38829bb5d30c - Init COMPLETE gpu05:24154:24154 [3] NCCL INFO comm 0x584005a0c750 rank 3 nranks 4 cudaDev 3 nvmlDev 3 busId 9d000 commId 0x113a38829bb5d30c - Init COMPLETE gpu05:24152:24152 [1] NCCL INFO comm 0x584005a0c8b0 rank 1 nranks 4 cudaDev 1 nvmlDev 1 busId 50000 commId 0x113a38829bb5d30c - Init COMPLETE

</details>

### 🐛 Describe the bug

When I start vLLM, it gets stuck at a step in pynccl.py and cannot proceed to model loading. At this point, I have to enable the export NCCL_P2P_DISABLE=1 parameter to load the model, but this significantly reduces inference speed. After rebooting the server, vLLM can start normally again. I am unsure of the reason for this issue and how to resolve it. 

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by tchang1997** [comment]
Just adding that I'm experiencing what appears to be the same issue on a setup with `nccl==2.20.5`, `torch==2.4.0+cu118`, and `torch.version.cuda==11.8`. I get stuck at the same place in my logs.

**Comment by KatUsagi** [comment]
> Just adding that I'm experiencing what appears to be the same issue on a setup with `nccl==2.20.5`, `torch==2.4.0+cu118`, and `torch.version.cuda==11.8`. I get stuck at the same place in my logs.

Initially, I was using vllm==0.5.4 and encountered this issue. After updating to 0.6.6, it still persists :(

**Comment by rachit8bit** [comment]
facing the same issue of getting stuck at vLLM startup where it's unable to load model weights on gpu:

INFO 01-23 05:28:08 custom_cache_manager.py:17] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
INFO 01-23 05:28:08 selector.py:135] Using Flash Attention backend.
(VllmWorkerProcess pid=35577) INFO 01-23 05:28:13 selector.py:135] Using Flash Attention backend.
(VllmWorkerProcess pid=35577) INFO 01-23 05:28:13 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=35579) INFO 01-23 05:28:13 selector.py:135] Using Flash Attention backend.
(VllmWorkerProcess pid=35579) INFO 01-23 05:28:13 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=35574) INFO 01-23 05:28:13 selector.py:135] Using Flash Attention backend.
(VllmWorkerProcess pid=35574) INFO 01-23 05:28:13 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=35576) INFO 01-23 05:28:13 selector.py:135] Using Flash Attention backend.
(VllmWorkerProcess pid=35576) INFO 01-23 05:28:13 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=35580) INFO 01-23 05:28:13 selector.py:135] Using Flash Attention backend.
(VllmWorkerProcess pid=35580) INFO 01-23 05:28:13 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=35575) INFO 01-23 05:28:13 selector.py:135] Using Flash Attention backend.
(VllmWorkerProcess pid=35575) INFO 01-23 05:28:13 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=35578) INFO 01-23 05:28:13 selector.py:135] Using Flash Attention backend.
(VllmWorkerProcess pid=35578) INFO 01-23 05:28:13 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
INFO 01-23 05:28:17 utils.py:961] Found nccl from library libnccl.so.2
INFO 01-23 05:28:17 pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=35574) INFO 01-23 05:28:17 utils.py:961] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=35574) INFO 01-23 05:28:17 pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=35575) INFO 01-23 05:28:17 utils.py:961] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=35575) INFO 01-23 05:28:17 pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=35576) INFO 01-23 05:28:17 utils.py:961] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=35577) INFO 01-23 05:28:17 utils.py:961] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=35576) INFO 01-23 05:28:17 pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=35578) INFO 01-23 05:28:17 utils.py:961] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=35577) INFO 01-23 05:28:17 pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=35580) INFO 01-23 05:28:17 utils.py:961] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=35579) INFO 01-23 05:28:17 utils.py:961] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=35578) INFO 01-23 05:28:17 pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=35580) INFO 01-23 05:28:17 pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=35579) INFO 01-23 05:28:17 pynccl.py:69] vLLM is using nccl==2.21.5

**Comment by drikster80** [comment]
I've been fighting with this issue for months and finally figured out last week.
**NOTE:** There are a lot of possible causes to NCCL issues, so this might not be your exact problem, but sharing in case it is.

## Solution for me
I had to manually set the correct GID using environment variable (in my case RoCEv2) `NCCL_IB_GID_INDEX=1`. This was due to an issue using NCCL in containers... there has been a recent [patch](https://github.com/NVIDIA/nccl/issues/1573#issuecomment-2589867643) for the automatic GID selection that solves it, but **you DON'T need to patch NCCL** if you manually set the GID. Also had to ensure my switch was setup to do RoCEv2 (it defaulted to v1... which is fine, but would have been a different GID to set and I couldn't get it to work properly). I also set `NCCL_SOCKET_IFNAME=eth0` because I'm in a k8s container.

## NCCL Troubleshooting Steps
Assuming you're going for RDMA with NCCL (both normal or GPUDirect/GDRDMA), and using Nvidia/Mellanox NICs, there are a few things that should really be done before launching VLLM:
 
1. (Only for Nvidia NICS) Install the MOFED Drivers/SW on the host. Nvidia's docs will talk about downloading binaries and install scripts, but MUCH easier to simply use their APT repo. Not sure why they don't put this in their docs...
```bash
wget -qO - http://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox | gpg --dearmor -o /usr/share/keyrings/GPG-KEY-Mellanox.gpg
'echo "deb [signed-by=/usr/share/keyrings/GPG-KEY-Mellanox.gpg] https://linux.mellanox.com/public/repo/mlnx_ofed/latest/ubuntu22.04/amd64 /" > /etc/apt/sources.list.d/mlnx.list'
apt-get install -y mlnx-fw-updater mlnx-ofed-all
```
2. Ensure RoCE is enabled on your switch, and pay attention to whether your using lossless (RoCEv1) or lossy (RoCEv2).

3. Test RDMA is working between the 2 hosts using `ib_write_bw`. 
```bash
# Get list of relevant devices
ibv_devices
# Node 1 (listener):
ib_write_bw -d <device> --bidirectional
# Node 1 (client):
ib_write_bw -d <device> --bidirectional <IP of listener>
```
4. If it's working, then use [NCCL-Tests](https://github.com/NVIDIA/nccl-tests) to validate NCCL is able to use the RDMA path to communicate between the nodes (or containers in my case). You'll want to use `mpirun` and can set different environment variables. Here is what I use to test with:
```bash
mpirun --allow-run-as-root -np 2 -host localhost,<IP of other host> -x NCCL_IB_GID_INDEX=5 -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=eth0 ./nccl-tests/build/all_reduce_perf -b 8 -e 2048M -f 2 -g <num_gpus>
```
If that hangs or fails, then you'll need to figure out why and fix it before VLLM will work.
A common problem is improper GID setting. You can see what the GIDs represent on your system with the command `ibv_devinfo -v | grep 'hca_id\|GID'`

If all of this works and VLLM still hangs, recommend turning on all the debugging to get better visibility into what's going on:
Best Environment Variables for that:
```bash
export VLLM_LOGGING_LEVEL=DEBUG
export NCCL_DEBUG=TRACE
```

**Comment by KatUsagi** [comment]
> I've been fighting with this issue for months and finally figured out last week. **NOTE:** There are a lot of possible causes to NCCL issues, so this might not be your exact problem, but sharing in case it is, with some good troubleshooting steps in case that doesn't work.
> 
> ## Solution for me
> I had to manually set the correct GID using environment variable (in my case RoCEv2) `NCCL_IB_GID_INDEX=1` (you might need to use `'3'` if you are using RoCEv1). This was due to an issue using NCCL in containers... there has been a recent [patch](https://github.com/NVIDIA/nccl/issues/1573#issuecomment-2589867643) for the automatic GID selection that solves it, but **you DON'T need to patch NCCL** if you manually set the GID. Also had to ensure my switch was setup to do RoCEv2 (it defaulted to v1... which is fine, but would have been a different GID to set and I couldn't get it to work properly). I also set `NCCL_SOCKET_IFNAME=eth0` because I'm in a k8s container.
> 
> ## NCCL Troubleshooting Steps
> Assuming you're going for RDMA with NCCL (both normal or GPUDirect/GDRDMA), and using Nvidia/Mellanox NICs, there are a few things that should really be done before launching VLLM:
> 
> 1. (Only for Nvidia NICS) Install the MOFED Drivers/SW on the host. Nvidia's docs will talk about downloading binaries and install scripts, but MUCH easier to simply use their APT repo. Not sure why they don't put this in their docs...
> 
> wget -qO - http://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox | gpg --dearmor -o /usr/share/keyrings/GPG-KEY-Mellanox.gpg
> 'echo "deb [signed-by=/usr/share/keyrings/GPG-KEY-Mellanox.gpg] https://linux.mellanox.com/public/repo/mlnx_ofed/latest/ubuntu22.04/amd64 /" > /etc/apt/sources.list.d/mlnx.list'
> apt-get install -y mlnx-fw-updater mlnx-ofed-all
> 2. Ensure RoCE is enabled on your switch, and pay attention to whether your using lossless (RoCEv1) or lossy (RoCEv2).
> 3. Test RDMA is working between the 2 hosts using `ib_write_bw`.
> 
> # Get list of relevant devices
> ibv_devices
> # Node 1 (listener):
> ib_write_bw -d <device> --bidirectional
> # Node 1 (client):
> ib_write_bw -d <device> --bidirectional <IP of listener>
> 4. If it's working, then use [NCCL-Tests](https://github.com/NVIDIA/nccl-tests) to validate NCCL is able to use the RDMA path to communicate between the nodes (or containers in my case). You'll want to use `mpirun` and can set different environment variables. Here is what I use to test with:
> 
> mpirun --allow-run-as-root -np 2 -host localhost,<IP of other host> -x NCCL_IB_GID_INDEX=5 -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=eth0 ./nccl-tests/build/all_reduce_perf -b 8 -e 2048M -f 2 -g <num_gpus>
> If that hangs or fails, then you'll need to figure out why and fix it before VLLM will work. A common problem is improper GID setting. You can see what the GIDs represent on your system with the command `ibv_devinfo -v | grep 'hca_id\|GID'`
> 
> If all of this works and VLLM still hangs, recommend turning on all the debugging to get better visibility into what's going on: Best Environment Variables for that:
> 
> export VLLM_LOGGING_LEVEL=DEBUG
> export NCCL_DEBUG=TRACE

Thank you very much for your response! My vLLM is not deployed on a virtual machine or Kubernetes, so perhaps I can give it a try. However, I noticed that after encountering the vLLM stucking issue, even when I deployed the model on two GPUs connected to the same PCIe bridge (without crossing NUMA nodes), vLLM still stucked. I'm not sure what the reason might be.

**Comment by KatUsagi** [comment]
> I've been fighting with this issue for months and finally figured out last week. **NOTE:** There are a lot of possible causes to NCCL issues, so this might not be your exact problem, but sharing in case it is, with some good troubleshooting steps in case that doesn't work.
> 
> ## Solution for me
> I had to manually set the correct GID using environment variable (in my case RoCEv2) `NCCL_IB_GID_INDEX=1` (you might need to use `'3'` if you are using RoCEv1). This was due to an issue using NCCL in containers... there has been a recent [patch](https://github.com/NVIDIA/nccl/issues/1573#issuecomment-2589867643) for the automatic GID selection that solves it, but **you DON'T need to patch NCCL** if you manually set the GID. Also had to ensure my switch was setup to do RoCEv2 (it defaulted to v1... which is fine, but would have been a different GID to set and I couldn't get it to work properly). I also set `NCCL_SOCKET_IFNAME=eth0` because I'm in a k8s container.
> 
> ## NCCL Troubleshooting Steps
> Assuming you're going for RDMA with NCCL (both normal or GPUDirect/GDRDMA), and using Nvidia/Mellanox NICs, there are a few things that should really be done before launching VLLM:
> 
> 1. (Only for Nvidia NICS) Install the MOFED Drivers/SW on the host. Nvidia's docs will talk about downloading binaries and install scripts, but MUCH easier to simply use their APT repo. Not sure why they don't put this in their docs...
> 
> wget -qO - http://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox | gpg --dearmor -o /usr/share/keyrings/GPG-KEY-Mellanox.gpg
> 'echo "deb [signed-by=/usr/share/keyrings/GPG-KEY-Mellanox.gpg] https://linux.mellanox.com/public/repo/mlnx_ofed/latest/ubuntu22.04/amd64 /" > /etc/apt/sources.list.d/mlnx.list'
> apt-get install -y mlnx-fw-updater mlnx-ofed-all
> 2. Ensure RoCE is enabled on your switch, and pay attention to whether your using lossless (RoCEv1) or lossy (RoCEv2).
> 3. Test RDMA is working between the 2 hosts using `ib_write_bw`.
> 
> # Get list of relevant devices
> ibv_devices
> # Node 1 (listener):
> ib_write_bw -d <device> --bidirectional
> # Node 1 (client):
> ib_write_bw -d <device> --bidirectional <IP of listener>
> 4. If it's working, then use [NCCL-Tests](https://github.com/NVIDIA/nccl-tests) to validate NCCL is able to use the RDMA path to communicate between the nodes (or containers in my case). You'll want to use `mpirun` and can set different environment variables. Here is what I use to test with:
> 
> mpirun --allow-run-as-root -np 2 -host localhost,<IP of other host> -x NCCL_IB_GID_INDEX=5 -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=eth0 ./nccl-tests/build/all_reduce_perf -b 8 -e 2048M -f 2 -g <num_gpus>
> If that hangs or fails, then you'll need to figure out why and fix it before VLLM will work. A common problem is improper GID setting. You can see what the GIDs represent on your system with the command `ibv_devinfo -v | grep 'hca_id\|GID'`
> 
> If all of this works and VLLM still hangs, recommend turning on all the debugging to get better visibility into what's going on: Best Environment Variables for that:
> 
> export VLLM_LOGGING_LEVEL=DEBUG
> export NCCL_DEBUG=TRACE

Addition: Even starting with a single GPU causes it to stucking, which suggests that this issue is likely unrelated to RDMA.

**Comment by yuqie** [comment]
Same with this error for vllm 0.7.1

**Comment by HaoLiu6101** [comment]
> > I've been fighting with this issue for months and finally figured out last week. **NOTE:** There are a lot of possible causes to NCCL issues, so this might not be your exact problem, but sharing in case it is, with some good troubleshooting steps in case that doesn't work.
> > ## Solution for me
> > I had to manually set the correct GID using environment variable (in my case RoCEv2) `NCCL_IB_GID_INDEX=1` (you might need to use `'3'` if you are using RoCEv1). This was due to an issue using NCCL in containers... there has been a recent [patch](https://github.com/NVIDIA/nccl/issues/1573#issuecomment-2589867643) for the automatic GID selection that solves it, but **you DON'T need to patch NCCL** if you manually set the GID. Also had to ensure my switch was setup to do RoCEv2 (it defaulted to v1... which is fine, but would have been a different GID to set and I couldn't get it to work properly). I also set `NCCL_SOCKET_IFNAME=eth0` because I'm in a k8s container.
> > ## NCCL Troubleshooting Steps
> > Assuming you're going for RDMA with NCCL (both normal or GPUDirect/GDRDMA), and using Nvidia/Mellanox NICs, there are a few things that should really be done before launching VLLM:
> > 
> > 1. (Only for Nvidia NICS) Install the MOFED Drivers/SW on the host. Nvidia's docs will talk about downloading binaries and install scripts, but MUCH easier to simply use their APT repo. Not sure why they don't put this in their docs...
> > 
> > wget -qO - http://www.mellanox.com/downloads/ofed/RPM-GPG-KEY-Mellanox | gpg --dearmor -o /usr/share/keyrings/GPG-KEY-Mellanox.gpg
> > 'echo "deb [signed-by=/usr/share/keyrings/GPG-KEY-Mellanox.gpg] https://linux.mellanox.com/public/repo/mlnx_ofed/latest/ubuntu22.04/amd64 /" > /etc/apt/sources.list.d/mlnx.list'
> > apt-get install -y mlnx-fw-updater mlnx-ofed-all
> > 2. Ensure RoCE is enabled on your switch, and pay attention to whether your using lossless (RoCEv1) or lossy (RoCEv2).
> > 3. Test RDMA is working between the 2 hosts using `ib_write_bw`.
> > # Get list of relevant devices
> > ibv_devices
> > # Node 1 (listener):
> > ib_write_bw -d  --bidirectional
> > # Node 1 (client):
> > ib_write_bw -d  --bidirectional 
> > 4. If it's working, then use [NCCL-Tests](https://github.com/NVIDIA/nccl-tests) to validate NCCL is able to use the RDMA path to communicate between the nodes (or containers in my case). You'll want to use `mpirun` and can set different environment variables. Here is what I use to test with:
> > mpirun --allow-run-as-root -np 2 -host localhost, -x NCCL_IB_GID_INDEX=5 -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=eth0 ./nccl-tests/build/all_reduce_perf -b 8 -e 2048M -f 2 -g <num_gpus>
> > If that hangs or fails, then you'll need to figure out why and fix it before VLLM will work. A common problem is improper GID setting. You can see what the GIDs represent on your system with the command `ibv_devinfo -v | grep 'hca_id\|GID'`
> > If all of this works and VLLM still hangs, recommend turning on all the debugging to get better visibility into what's going on: Best Environment Variables for that:
> > export VLLM_LOGGING_LEVEL=DEBUG
> > export NCCL_DEBUG=TRACE
> 
> Addition: Even starting with a single GPU causes it to stucking, which suggests that this issue is likely unrelated to RDMA. I'm not sure if there was any anomaly when exiting vLLM before it stucked that might have caused this issue. Have you ever experienced vLLM stucking during startup in a non-container environment? When I force quit vLLM during the stucking situation, I can see from nvidia-smi that the vLLM process cannot be completely killed, and it occupies around 300MB of GPU memory.

I have exactly the same situation. I tried to serve the a model across two GPUs. It is normally ok after a reboot. 
If I stop the service and restart the service, it hangs for sure. Then, I forced stop the vllm service and I tried to check the GPU using Nvidia-smi. Both GPUs are occupied around 600MB memory. And then, I tried to kill the processes to release the GPU memory. The memory was released but anyway it still hang if I restart a vllm service.
So far, i only manage to reboot and re-serve again.

**Comment by mikolysz** [comment]
For me, this problem was due to page faults somewhere in the mlx5_core (Mellanox networking) driver. You can quickly verify if this is the cause by running `dmesg` as root, if there are some lines at the bottom that mention page faults, that's probably it. You might also want to run [nccl tests](https://github.com/NVIDIA/nccl-tests) and see if they hang (if it's the same problem, they *should hang*).

As [mentioned on Nvidia developer forums](https://forums.developer.nvidia.com/t/mlx5-core-will-cause-a-leak-of-a-command-resource/226808), this problem is due to the IOMMU present on some AMD CPUs. You can prevent it by adding the `iommu=pt` argument to your kernel command line (requires reboot to take effect). On my distribution (Alma Linux / Rhel 9.6), this can be done as follows:
```
grubby --update-kernel=DEFAULT --args="iommu=pt"
```
