### ISSUE TITLE
AWQ broken when trying to add Mistral

### ISSUE THREAD

**Issue by casper-hansen** [vllm-project/vllm#1236]
I am getting illegal memory access after building from `main`. I am not sure if this is because of the cast from torch.bfloat16 to torch.float16 or if it is something else. Llama models still work without any problem.

I simply added `MistralForCausalLM` here since the model definition is exactly the same as Llama and just works:

https://github.com/vllm-project/vllm/blob/0967102c6de874902d973f0bcb98d48149a8eb49/vllm/model_executor/model_loader.py#L36-L38

Testing with an example:

```
CUDA_LAUNCH_BLOCKING=1 python examples/llm_engine_example.py --model TheBloke/Mistral-7B-Instruct-v0.1-AWQ --quantization awq --dtype half
```

Traceback:

```
root@d185de394aeb:/workspace/vllm# CUDA_LAUNCH_BLOCKING=1 python examples/llm_engine_example.py --model TheBloke/Mistral-7B-Instruct-v0.1-AWQ --quantization awq --dtype half
WARNING 09-30 19:56:00 config.py:341] Casting torch.bfloat16 to torch.float16.
INFO 09-30 19:56:00 llm_engine.py:72] Initializing an LLM engine with config: model='TheBloke/Mistral-7B-Instruct-v0.1-AWQ', tokenizer='TheBloke/Mistral-7B-Instruct-v0.1-AWQ', tokenizer_mode=auto, revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=awq, seed=0)
Traceback (most recent call last):
  File "/workspace/vllm/examples/llm_engine_example.py", line 51, in <module>
    main(args)
  File "/workspace/vllm/examples/llm_engine_example.py", line 9, in main
    engine = LLMEngine.from_engine_args(engine_args)
  File "/workspace/vllm/vllm/engine/llm_engine.py", line 229, in from_engine_args
    engine = cls(*engine_configs,
  File "/workspace/vllm/vllm/engine/llm_engine.py", line 111, in __init__
    self._init_cache()
  File "/workspace/vllm/vllm/engine/llm_engine.py", line 191, in _init_cache
    num_blocks = self._run_workers(
  File "/workspace/vllm/vllm/engine/llm_engine.py", line 692, in _run_workers
    output = executor(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/vllm/vllm/worker/worker.py", line 109, in profile_num_available_blocks
    self.model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/vllm/vllm/model_executor/models/mistral.py", line 290, in forward
    hidden_states = self.model(input_ids, positions, kv_caches,
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/vllm/vllm/model_executor/models/mistral.py", line 250, in forward
    hidden_states = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/vllm/vllm/model_executor/models/mistral.py", line 209, in forward
    hidden_states = self.mlp(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/vllm/vllm/model_executor/models/mistral.py", line 81, in forward
    gate_up, _ = self.gate_up_proj(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/vllm/vllm/model_executor/parallel_utils/tensor_parallel/layers.py", line 238, in forward
    output_parallel = self.apply_weights(input_parallel, bias)
  File "/workspace/vllm/vllm/model_executor/layers/quantized_linear/awq.py", line 55, in apply_weights
    out = quantization_ops.awq_gemm(reshaped_x, self.qweight, self.scales,
RuntimeError: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by mapa17** [comment]
I am not an expert, but from the error message you can see that the issue lies with the Cuda kernels ins `https://github.com/vllm-project/vllm/blob/main/csrc/quantization/awq/gemm_kernels.cu` 
I guess there is some architecture difference between Mistral and Llama that needs to be reflected in the cuda kernel implementation.

**Comment by casper-hansen** [comment]
@mapa17 This can happen for many reasons and is not an expression of the kernel being the culprit but rather the operations taking place before the AWQ kernel executes

**Comment by hverma-forrester** [comment]
I can see the max_sequence is initialized to 32K, not sure but can this be the culprit? I will try to decrease it and let you know.

**Comment by casper-hansen** [comment]
@WoosukKwon It may be worthwhile to explore why there are multiple bugs. Some are getting OOM issues on 7B models that should not be happening - others are getting this error explained in this issue. I believe it is currently the `rotary_embedding` causing this issue. 

This code was used to solve this issue in AutoAWQ back when we used the CUDA kernel. Essentially, as long as the shapes were incorrect, rotary embedding would run fine but then the AWQ GEMM kernel would silently fail afterward for no apparent reason. There may be some niche interaction that I do not understand yet, but here is the code that was used to solve my issue if it is of any help to you:

```python
# [num_tokens, num_heads * head_size]
query_batch_size, query_len, _ = query.shape
query = query.view(query_len*query_batch_size, self.num_heads * self.head_dim)

# [num_tokens, num_kv_heads * head_size]
key_batch_size, key_len, _ = key.shape
key = key.view(key_len*key_batch_size, self.num_kv_heads * self.head_dim)

# [num_tokens]
positions = position_ids.view(-1).to(query.device)

query, key = self.rotary_emb(query, key, positions)
```

I used the rotary embedding implementation from Huggingface to figure out that the AWQ GEMM kernel actually ran fine when the CUDA kernel from vLLM was not used until I fixed it. Here is my old reference implementation: https://github.com/casper-hansen/AutoAWQ/blob/562c0d52b465aaee5a03ebbf84483f1907233457/awq/modules/fused_attn.py

**Comment by WoosukKwon** [comment]
Hi @casper-hansen Thanks for the advice.

I've run `CUDA_LAUNCH_BLOCKING=1 python examples/llm_engine_example.py --model TheBloke/Mistral-7B-Instruct-v0.1-AWQ --quantization awq --dtype half` after commenting out this line.
https://github.com/vllm-project/vllm/blob/ebe4d1db3a42096cebcc2b2d289143bc0ef02d3d/vllm/model_executor/layers/attention.py#L333

However, I got the same CUDA illegal memory access error.

**Comment by casper-hansen** [comment]
I am a bit puzzled on this one. When I get the time, I will try to backtrack this. I had one user report to me that AWQ was working on the Mistral PR itself, so that’s a starting point.

**Comment by hverma-forrester** [comment]
> I can see the max_sequence is initialized to 32K, not sure but can this be the culprit? I will try to decrease it and let you know.

I tried with lower "max_model_len" and it loaded successfully. This is what I used as config:

MODEL_ID = "casperhansen/mistral-7b-instruct-v0.1-awq"

llm = LLM(
    model=MODEL_ID,
    dtype="half",
    quantization="awq",
    max_model_len=8096
)

<img width="1143" alt="Screenshot 2023-10-03 at 6 24 46 PM" src="https://github.com/vllm-project/vllm/assets/68223988/c7ae9667-ec86-46ba-af5b-6f4273f279cb">

**Comment by casper-hansen** [comment]
@hverma-forrester Thanks for discovering this. I can see your generation works just fine here. Did you compile from main?

**Comment by hverma-forrester** [comment]
> @hverma-forrester Thanks for discovering this. I can see your generation works just fine here. Did you compile from main?

Yes, I did and I am using Sagemaker with this config:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A10G         Off  | 00000000:00:1E.0 Off |                    0 |
|  0%   29C    P0    57W / 300W |  16996MiB / 22731MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by casper-hansen** [comment]
After debugging a bit, I found the cutoff where the error is triggered. 

No error: 10696 or below
Error: 10697 or above

```python
MODEL_ID = "casperhansen/mistral-7b-instruct-v0.1-awq"

llm = LLM(
    model=MODEL_ID,
    dtype="half",
    quantization="awq",
    max_model_len=10696 # 10697 triggers error
)
```

**Comment by gesanqiu** [comment]
> I can get this same error to trigger on a Llama model:
> 
> ```python
> MODEL_ID = "TheBloke/Llama-2-7B-32K-Instruct-AWQ"
> 
> llm = LLM(
>     model=MODEL_ID,
>     dtype="half",
>     quantization="awq",
>     max_model_len=13928 # 13929 triggers error
> )
> ```

Yes, I got same issue with CodeLlama-13B, which has 16K context length.

**Comment by WoosukKwon** [comment]
Fixed by #1295 thanks to @chu-tianxiang

**Comment by mckbrchill** [comment]
@WoosukKwon 
I guess this fix is included in the latest 0.2.1.post1 version?
I'm using 0.2.1.post1 and still cannot launch  
```
CUDA_LAUNCH_BLOCKING=1 python examples/llm_engine_example.py --download-dir ./data --model TheBloke/Mistral-7B-Instruct-v0.1-AWQ --quantization awq --dtype
```
beacause of ```Compile with `TORCH_USE_CUDA_DSA```` error
