### ISSUE TITLE
[Bug]: Error while capturing CUDA graph

### ISSUE THREAD

**Issue by llsj14** [vllm-project/vllm#12438]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.27.6
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-4.19.93-1.nbp.el7.x86_64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY

Nvidia driver version: 535.129.03
```

</details>

### 🐛 Describe the bug

# vLLM version
My last commit is as follows:
```
commit 324960a95c00112ce6b9b858d9311da1597cfb8b (HEAD -> main, upstream/main, origin/main, origin/HEAD)
    [TPU][CI] Update torchxla version in requirement-tpu.txt (#12422)
```
It is just making an error right after I rebased my code to the latest version of vLLM.

# What I did

```
python -m vllm.entrypoints.openai.api_server \
     --model meta-llama/Llama-2-7b-hf \
     --port 8087 \
     --disable-custom-all-reduce \
     --swap-space 0 \
     --gpu-memory-utilization 0.8
```

# Error message

```
Capturing CUDA graph shapes:   0%|                                                                           | 0/35 [00:00<?, ?it/s]
ERROR 01-26 05:16:05 engine.py:387] CUDA error: operation failed due to a previous error during capture
ERROR 01-26 05:16:05 engine.py:387] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
ERROR 01-26 05:16:05 engine.py:387] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
ERROR 01-26 05:16:05 engine.py:387] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
ERROR 01-26 05:16:05 engine.py:387] Traceback (most recent call last):
ERROR 01-26 05:16:05 engine.py:387]   File "/vllm/vllm/worker/model_runner.py", line 1914, in capture
ERROR 01-26 05:16:05 engine.py:387]     output_hidden_or_intermediate_states = self.model(
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 01-26 05:16:05 engine.py:387]     return self._call_impl(*args, **kwargs)
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 01-26 05:16:05 engine.py:387]     return forward_call(*args, **kwargs)
ERROR 01-26 05:16:05 engine.py:387]   File "/vllm/vllm/model_executor/models/llama.py", line 538, in forward
ERROR 01-26 05:16:05 engine.py:387]     model_output = self.model(input_ids, positions, kv_caches,
ERROR 01-26 05:16:05 engine.py:387]   File "/vllm/vllm/compilation/decorators.py", line 170, in __call__
ERROR 01-26 05:16:05 engine.py:387]     return self.forward(*args, **kwargs)
ERROR 01-26 05:16:05 engine.py:387]   File "/vllm/vllm/model_executor/models/llama.py", line 363, in forward
ERROR 01-26 05:16:05 engine.py:387]     hidden_states, residual = layer(positions, hidden_states,
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 01-26 05:16:05 engine.py:387]     return self._call_impl(*args, **kwargs)
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 01-26 05:16:05 engine.py:387]     return forward_call(*args, **kwargs)
ERROR 01-26 05:16:05 engine.py:387]   File "/vllm/vllm/model_executor/models/llama.py", line 277, in forward
ERROR 01-26 05:16:05 engine.py:387]     hidden_states = self.self_attn(positions=positions,
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 01-26 05:16:05 engine.py:387]     return self._call_impl(*args, **kwargs)
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 01-26 05:16:05 engine.py:387]     return forward_call(*args, **kwargs)
ERROR 01-26 05:16:05 engine.py:387]   File "/vllm/vllm/model_executor/models/llama.py", line 201, in forward
ERROR 01-26 05:16:05 engine.py:387]     attn_output = self.attn(q, k, v, kv_cache, attn_metadata)
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 01-26 05:16:05 engine.py:387]     return self._call_impl(*args, **kwargs)
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 01-26 05:16:05 engine.py:387]     return forward_call(*args, **kwargs)
ERROR 01-26 05:16:05 engine.py:387]   File "/vllm/vllm/attention/layer.py", line 177, in forward
ERROR 01-26 05:16:05 engine.py:387]     return torch.ops.vllm.unified_attention(
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 1116, in __call__
ERROR 01-26 05:16:05 engine.py:387]     return self._op(*args, **(kwargs or {}))
ERROR 01-26 05:16:05 engine.py:387]   File "/vllm/vllm/attention/layer.py", line 285, in unified_attention
ERROR 01-26 05:16:05 engine.py:387]     return self.impl.forward(self, query, key, value, kv_cache, attn_metadata)
ERROR 01-26 05:16:05 engine.py:387]   File "/vllm/vllm/attention/backends/xformers.py", line 529, in forward
ERROR 01-26 05:16:05 engine.py:387]     PagedAttention.write_to_paged_cache(
ERROR 01-26 05:16:05 engine.py:387]   File "/vllm/vllm/attention/ops/paged_attn.py", line 75, in write_to_paged_cache
ERROR 01-26 05:16:05 engine.py:387]     ops.reshape_and_cache(
ERROR 01-26 05:16:05 engine.py:387]   File "/vllm/vllm/_custom_ops.py", line 962, in reshape_and_cache
ERROR 01-26 05:16:05 engine.py:387]     torch.ops._C_cache_ops.reshape_and_cache(key, value, key_cache,
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 1116, in __call__
ERROR 01-26 05:16:05 engine.py:387]     return self._op(*args, **(kwargs or {}))
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 523, in __repr__
ERROR 01-26 05:16:05 engine.py:387]     return torch._tensor_str._str(self, tensor_contents=tensor_contents)
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 708, in _str
ERROR 01-26 05:16:05 engine.py:387]     return _str_intern(self, tensor_contents=tensor_contents)
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 625, in _str_intern
ERROR 01-26 05:16:05 engine.py:387]     tensor_str = _tensor_str(self, indent)
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 357, in _tensor_str
ERROR 01-26 05:16:05 engine.py:387]     formatter = _Formatter(get_summarized_data(self) if summarize else self)
ERROR 01-26 05:16:05 engine.py:387]   File "/usr/local/lib/python3.10/dist-packages/torch/_tensor_str.py", line 146, in __init__
ERROR 01-26 05:16:05 engine.py:387]     tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0)
ERROR 01-26 05:16:05 engine.py:387] RuntimeError: CUDA error: operation failed due to a previous error during capture

```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by llsj14** [comment]
The error came out while I'm rebasing my code and I guess there was a compatibility issue while changing my code.
The error disappeared after I rebuilt vLLM.
