### ISSUE TITLE
[Bug]: Getting torch.distributed.DistStoreError: wait timeout after 600000ms on Multi GPU instance (NC96 - 4xA100s)

### ISSUE THREAD

**Issue by adityavyasbme** [vllm-project/vllm#12526]
### Your current environment

```
DEBUG 01-28 20:44:23 __init__.py:26] No plugins for group vllm.platform_plugins found.
INFO 01-28 20:44:23 __init__.py:183] Automatically detected platform cuda.
Collecting environment information...
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 12 (bookworm) (x86_64)
GCC version: (Debian 12.2.0-14) 12.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.36

Python version: 3.12.8 (main, Jan 24 2025, 19:38:26) [GCC 12.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1078-azure-x86_64-with-glibc2.36
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100 80GB PCIe
GPU 1: NVIDIA A100 80GB PCIe
GPU 2: NVIDIA A100 80GB PCIe
GPU 3: NVIDIA A100 80GB PCIe

Nvidia driver version: 550.127.08
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        48 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               96
On-line CPU(s) list:                  0-95
Vendor ID:                            AuthenticAMD
Model name:                           AMD EPYC 7V13 64-Core Processor
CPU family:                           25
Model:                                1
Thread(s) per core:                   1
Core(s) per socket:                   48
Socket(s):                            2
Stepping:                             1
BogoMIPS:                             4890.87
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core invpcid_single vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr rdpru arat umip vaes vpclmulqdq rdpid fsrm
Hypervisor vendor:                    Microsoft
Virtualization type:                  full
L1d cache:                            3 MiB (96 instances)
L1i cache:                            3 MiB (96 instances)
L2 cache:                             48 MiB (96 instances)
L3 cache:                             384 MiB (12 instances)
NUMA node(s):                         4
NUMA node0 CPU(s):                    0-23
NUMA node1 CPU(s):                    24-47
NUMA node2 CPU(s):                    48-71
NUMA node3 CPU(s):                    72-95
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Mitigation; safe RET, no microcode
Vulnerability Spec store bypass:      Vulnerable
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; STIBP disabled; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-ml-py==12.570.86
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] pyzmq==26.2.0
[pip3] torch==2.5.1
[pip3] torchaudio==2.5.1
[pip3] torchvision==0.20.1
[pip3] transformers==4.48.1
[pip3] triton==3.1.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.7.0
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0	GPU1	GPU2	GPU3	NIC0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV12	SYS	SYS	NODE	0-23	0		N/A
GPU1	NV12	 X 	SYS	SYS	SYS	24-47	1		N/A
GPU2	SYS	SYS	 X 	NV12	SYS	48-71	2		N/A
GPU3	SYS	SYS	NV12	 X 	SYS	72-95	3		N/A
NIC0	NODE	SYS	SYS	SYS	 X 				

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0

NVIDIA_VISIBLE_DEVICES=GPU-71fe4202-8e66-d717-7098-0de2d050eb09,GPU-e44ff697-59b5-9d2c-cd5b-3e40261c468f,GPU-e9098448-3117-29c1-bdde-ab1ab9fad405,GPU-1e527b83-3a4d-fbe6-1833-d17aace8bc87
NCCL_P2P_DISABLE=1
TORCH_DISTRIBUTED_DEBUG=DETAIL
NCCL_SOCKET_IFNAME=eth0
NCCL_DEBUG_SUBSYS=ALL
NCCL_DEBUG=DEBUG
VLLM_WORKER_MULTIPROC_METHOD=spawn
CUDA_LAUNCH_BLOCKING=1
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
CUDA_VISIBLE_DEVICES=0,1,2,3
CUDA_VISIBLE_DEVICES=0,1,2,3
VLLM_TRACE_FUNCTION=1
LD_LIBRARY_PATH=/usr/local/lib/python3.12/site-packages/cv2/../../lib64:/usr/local/cuda/lib64:
CUDA_HOME=/usr/local/cuda
CUDA_HOME=/usr/local/cuda
VLLM_LOGGING_LEVEL=DEBUG
VLLM_HOST_IP=127.0.0.1
NCCL_CUMEM_ENABLE=0
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY
```

### 🐛 Describe the bug

I am trying to run Vllm with BentoML on NC24 and NC96 
When I run this with NC24 (i.e., single A100 GPU) it works perfectly well 

When I switch to NC96 (i.e., 4xA100s GPUs) it runs for a while as you can see in the logs, and then it throws time out in the end after 30 mins. 

I tried different debugging env variables but cannot find the root cause; I presume this is some kind of networking issue. I tried debugging NCCL as well but couldn't resolve it. Any help would be appreciated.  

I am using recent version of VLLM, i.e., vllm==0.7.0

```
2025-01-28T20:08:19+0000 [INFO] [:1] Initializing llama2 Service... GPU INDEX: 0
DEBUG 01-28 20:08:19 __init__.py:26] No plugins for group vllm.general_plugins found.
WARNING 01-28 20:08:19 config.py:2318] Casting torch.float16 to torch.bfloat16.
INFO 01-28 20:08:26 config.py:520] This model supports multiple tasks: {'embed', 'generate', 'score', 'classify', 'reward'}. Defaulting to 'generate'.
INFO 01-28 20:08:26 config.py:1328] Defaulting to use mp for distributed inference
INFO 01-28 20:08:26 llm_engine.py:232] Initializing an LLM engine (v0.7.0) with config: model='/tmp/tfhb-use-case/llama2/1', speculative_config=None, tokenizer='/tmp/tfhb-use-case/llama2/1', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/tmp/tfhb-use-case/llama2/1, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False, 
/usr/local/lib/python3.12/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/transformers/generation/configuration_utils.py:633: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`. This was detected when initializing the generation config instance, which means the corresponding file may hold incorrect parameterization and should be fixed.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/transformers/generation/configuration_utils.py:628: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
/usr/local/lib/python3.12/site-packages/transformers/generation/configuration_utils.py:633: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.6` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
WARNING 01-28 20:08:26 multiproc_worker_utils.py:298] Reducing Torch parallelism from 96 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 01-28 20:08:26 custom_cache_manager.py:17] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
WARNING 01-28 20:08:26 logger.py:201] VLLM_TRACE_FUNCTION is enabled. It will record every function executed by Python. This will slow down the code. It is suggested to be used for debugging hang or crashes only.
INFO 01-28 20:08:26 logger.py:205] Trace frame log is saved to /tmp/bentoml/vllm/vllm-instance-dd764/VLLM_TRACE_FUNCTION_for_process_963177_thread_140362346515328_at_2025-01-28_20:08:26.835763.log
/usr/local/lib/python3.12/site-packages/transformers/utils/hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
DEBUG 01-28 20:08:30 __init__.py:26] No plugins for group vllm.platform_plugins found.
INFO 01-28 20:08:30 __init__.py:183] Automatically detected platform cuda.
(VllmWorkerProcess pid=963948) INFO 01-28 20:08:31 multiproc_worker_utils.py:227] Worker ready; awaiting tasks
(VllmWorkerProcess pid=963948) WARNING 01-28 20:08:31 logger.py:201] VLLM_TRACE_FUNCTION is enabled. It will record every function executed by Python. This will slow down the code. It is suggested to be used for debugging hang or crashes only.
(VllmWorkerProcess pid=963948) INFO 01-28 20:08:31 logger.py:205] Trace frame log is saved to /tmp/bentoml/vllm/vllm-instance-dd764/VLLM_TRACE_FUNCTION_for_process_963948_thread_140058639784832_at_2025-01-28_20:08:31.670702.log
(VllmWorkerProcess pid=963948) DEBUG 01-28 20:08:32 __init__.py:26] No plugins for group vllm.general_plugins found.
INFO 01-28 20:09:18 cuda.py:225] Using Flash Attention backend.
(VllmWorkerProcess pid=963948) INFO 01-28 20:09:23 cuda.py:225] Using Flash Attention backend.
(VllmWorkerProcess pid=963948) DEBUG 01-28 20:09:24 parallel_state.py:951] world_size=2 rank=1 local_rank=1 distributed_init_method=tcp://127.0.0.1:41577 backend=nccl
DEBUG 01-28 20:09:24 parallel_state.py:951] world_size=2 rank=0 local_rank=0 distributed_init_method=tcp://127.0.0.1:41577 backend=nccl
[W128 20:09:24.923040958 CUDAAllocatorConfig.h:28] Warning: expandable_segments not supported on this platform (function operator())
[W128 20:09:24.937361194 CUDAAllocatorConfig.h:28] Warning: expandable_segments not supported on this platform (function **operator())**
[rank1]:[W128 20:19:24.005155935 socket.cpp:462] [c10d] waitForInput: poll for socket SocketImpl(fd=69, addr=[localhost]:41380, remote=[localhost]:41577) returned 0, likely a timeout
[rank1]:[W128 20:19:24.072980603 socket.cpp:487] [c10d] waitForInput: socket SocketImpl(fd=69, addr=[localhost]:41380, remote=[localhost]:41577) timed out after 600000ms
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240] Exception in worker VllmWorkerProcess while processing method init_device.
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240] Traceback (most recent call last):
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]   File "/usr/local/lib/python3.12/site-packages/vllm/executor/multiproc_worker_utils.py", line 234, in _run_worker_process
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]     output = run_method(worker, method, args, kwargs)
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]   File "/usr/local/lib/python3.12/site-packages/vllm/utils.py", line 2208, in run_method
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]     return func(*args, **kwargs)
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]   File "/usr/local/lib/python3.12/site-packages/vllm/worker/worker.py", line 165, in init_device
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]     init_worker_distributed_environment(self.vllm_config, self.rank,
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]   File "/usr/local/lib/python3.12/site-packages/vllm/worker/worker.py", line 506, in init_worker_distributed_environment
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]     init_distributed_environment(parallel_config.world_size, rank,
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]   File "/usr/local/lib/python3.12/site-packages/vllm/distributed/parallel_state.py", line 978, in init_distributed_environment
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]     _WORLD = init_world_group(ranks, local_rank, backend)
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]   File "/usr/local/lib/python3.12/site-packages/vllm/distributed/parallel_state.py", line 842, in init_world_group
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]     return GroupCoordinator(
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]            ^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]   File "/usr/local/lib/python3.12/site-packages/vllm/distributed/parallel_state.py", line 181, in __init__
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]     device_group = torch.distributed.new_group(
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]   File "/usr/local/lib/python3.12/site-packages/torch/distributed/c10d_logger.py", line 97, in wrapper
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]     func_return = func(*args, **kwargs)
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]                   ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]   File "/usr/local/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 4565, in new_group
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]     return _new_group_with_tag(
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]            ^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]   File "/usr/local/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 4648, in _new_group_with_tag
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]     pg, pg_store = _new_process_group_helper(
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]   File "/usr/local/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 1840, in _new_process_group_helper
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]     backend_class = _create_process_group_wrapper(
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]   File "/usr/local/lib/python3.12/site-packages/torch/distributed/distributed_c10d.py", line 4255, in _create_process_group_wrapper
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]     helper_pg = ProcessGroupGloo(store, rank, world_size, timeout=timeout)
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=963948) ERROR 01-28 20:19:24 multiproc_worker_utils.py:240]   torch.distributed.DistStoreError: wait timeout after 600000ms, keys: /default_pg/0//1//cuda//pg_wrapper:1/0/0

```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by adityavyasbme** [comment]
Nevermind; it was a shared memory issue 
shm was mounted to /dev/shm and it had 64M memory; I Increased it to say 512M and it worked

**Comment by taohui** [comment]
I also get the error, while my /dev/shm size is 1.2T
