### ISSUE TITLE
[Bug]: 'CUDAGraphBatchDecodeWithPagedKVCacheWrapper' object has no attribute 'plan' when serving QwenMoE model

### ISSUE THREAD

**Issue by anhnh2002** [vllm-project/vllm#12821]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
INFO 02-06 10:15:06 __init__.py:183] Automatically detected platform cuda.
Collecting environment information...
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: version 3.29.3
Libc version: glibc-2.31

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-193-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 10.1.243
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-PCIE-40GB
GPU 1: NVIDIA A100-PCIE-40GB

Nvidia driver version: 535.183.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      40 bits physical, 57 bits virtual
CPU(s):                             52
On-line CPU(s) list:                0-51
Thread(s) per core:                 1
Core(s) per socket:                 52
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              134
Model name:                         Intel Xeon Processor (Icelake)
Stepping:                           0
CPU MHz:                            2194.848
BogoMIPS:                           4389.69
Virtualisation:                     VT-x
Hypervisor vendor:                  KVM
Virtualisation type:                full
L1d cache:                          1.6 MiB
L1i cache:                          1.6 MiB
L2 cache:                           208 MiB
L3 cache:                           16 MiB
NUMA node0 CPU(s):                  0-51
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS Not affected; BHI SW loop, KVM SW loop
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Mitigation; TSX disabled
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid md_clear arch_capabilities

Versions of relevant libraries:
[pip3] flake8==7.0.0
[pip3] flake8-bugbear==24.4.26
[pip3] flashinfer==0.1.2+cu124torch2.4
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] onnx==1.16.2
[pip3] onnx2torch==1.5.15
[pip3] onnxruntime==1.18.1
[pip3] onnxruntime-gpu==1.19.2
[pip3] pytorch-lightning==2.4.0
[pip3] pytorch-metric-learning==2.6.0
[pip3] pytorch_revgrad==0.2.0
[pip3] pyzmq==25.1.2
[pip3] rotary-embedding-torch==0.6.5
[pip3] sentence-transformers==3.0.1
[pip3] torch==2.5.1
[pip3] torch-audiomentations==0.11.1
[pip3] torch_pitch_shift==1.2.5
[pip3] torch-stoi==0.2.1
[pip3] torchaudio==2.5.1
[pip3] torchmetrics==1.4.2
[pip3] torchtext==0.18.0
[pip3] torchvision==0.20.1
[pip3] transformers==4.48.2
[pip3] triton==3.1.0
[conda] flashinfer                0.1.2+cu124torch2.4          pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
[conda] nvidia-ml-py              12.560.30                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
[conda] onnx2torch                1.5.15                   pypi_0    pypi
[conda] pytorch-lightning         2.4.0                    pypi_0    pypi
[conda] pytorch-metric-learning   2.6.0                    pypi_0    pypi
[conda] pytorch-revgrad           0.2.0                    pypi_0    pypi
[conda] pyzmq                     25.1.2          py310h6a678d5_0  
[conda] rotary-embedding-torch    0.6.5                    pypi_0    pypi
[conda] sentence-transformers     3.0.1                    pypi_0    pypi
[conda] torch                     2.5.1                    pypi_0    pypi
[conda] torch-audiomentations     0.11.1                   pypi_0    pypi
[conda] torch-pitch-shift         1.2.5                    pypi_0    pypi
[conda] torch-stoi                0.2.1                    pypi_0    pypi
[conda] torchaudio                2.5.1                    pypi_0    pypi
[conda] torchmetrics              1.4.2                    pypi_0    pypi
[conda] torchtext                 0.18.0                   pypi_0    pypi
[conda] torchvision               0.20.1                   pypi_0    pypi
[conda] transformers              4.48.2                   pypi_0    pypi
[conda] triton                    3.1.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.7.1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV12    0-51    0               N/A
GPU1    NV12     X      0-51    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

VLLM_ATTENTION_BACKEND=FLASHINFER
LD_LIBRARY_PATH=/mnt/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/cv2/../../lib64:/usr/local/cuda-11.0/lib64:/usr/local/cuda-11.0/lib64:
CUDA_HOME=/usr/local/cuda-11.0
CUDA_HOME=/usr/local/cuda-11.0
NCCL_CUMEM_ENABLE=0
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY
```

</details>

### 🐛 Describe the bug

* CMD: `CUDA_VISIBLE_DEVICES=1 vllm serve ./raw-moes/qwen2_5-8x0_5B-it --port 8787 --max-model-len 1024 --gpu-memory-utilization 0.6`
* Logs:
```
INFO 02-06 10:07:10 __init__.py:183] Automatically detected platform cuda.
INFO 02-06 10:07:11 api_server.py:838] vLLM API server version 0.7.1
INFO 02-06 10:07:11 api_server.py:839] args: Namespace(subparser='serve', model_tag='./raw-moes/qwen2_5-8x0_5B-it', config='', host=None, port=8787, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, enable_reasoning=False, reasoning_parser=None, tool_call_parser=None, tool_parser_plugin='', model='./raw-moes/qwen2_5-8x0_5B-it', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', max_model_len=1024, guided_decoding_backend='xgrammar', logits_processor_pattern=None, distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.6, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=None, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', generation_config=None, override_generation_config=None, enable_sleep_mode=False, calculate_kv_scales=False, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, dispatch_function=<function serve at 0x7f5ea4b73b50>)
INFO 02-06 10:07:11 api_server.py:204] Started engine process with PID 3414749
INFO 02-06 10:07:17 __init__.py:183] Automatically detected platform cuda.
INFO 02-06 10:07:20 config.py:526] This model supports multiple tasks: {'generate', 'embed', 'score', 'reward', 'classify'}. Defaulting to 'generate'.
INFO 02-06 10:07:28 config.py:526] This model supports multiple tasks: {'generate', 'classify', 'score', 'embed', 'reward'}. Defaulting to 'generate'.
INFO 02-06 10:07:28 llm_engine.py:232] Initializing a V0 LLM engine (v0.7.1) with config: model='./raw-moes/qwen2_5-8x0_5B-it', speculative_config=None, tokenizer='./raw-moes/qwen2_5-8x0_5B-it', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=1024, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=./raw-moes/qwen2_5-8x0_5B-it, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=True, 
INFO 02-06 10:07:30 cuda.py:169] Using FlashInfer backend.
INFO 02-06 10:07:31 model_runner.py:1111] Starting to load model ./raw-moes/qwen2_5-8x0_5B-it...
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:00<00:00,  1.07it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:01<00:00,  1.95it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:01<00:00,  1.73it/s]

INFO 02-06 10:07:33 model_runner.py:1116] Loading model weights took 5.0188 GB
WARNING 02-06 10:07:35 fused_moe.py:647] Using default MoE config. Performance might be sub-optimal! Config file not found at /mnt/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/model_executor/layers/fused_moe/configs/E=7,N=4864,device_name=NVIDIA_A100-PCIE-40GB.json
INFO 02-06 10:07:37 worker.py:266] Memory profiling takes 2.81 seconds
INFO 02-06 10:07:37 worker.py:266] the current vLLM instance can use total_gpu_memory (39.39GiB) x gpu_memory_utilization (0.60) = 23.64GiB
INFO 02-06 10:07:37 worker.py:266] model weights take 5.02GiB; non_torch_memory takes 0.09GiB; PyTorch activation peak memory takes 1.64GiB; the rest of the memory reserved for KV Cache is 16.89GiB.
INFO 02-06 10:07:37 executor_base.py:108] # CUDA blocks: 92219, # CPU blocks: 21845
INFO 02-06 10:07:37 executor_base.py:113] Maximum concurrency for 1024 tokens per request: 1440.92x
INFO 02-06 10:07:45 model_runner.py:1435] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
Capturing CUDA graph shapes:   0%|                                                                                      | 0/35 [00:00<?, ?it/s]
ERROR 02-06 10:07:45 engine.py:387] 'CUDAGraphBatchDecodeWithPagedKVCacheWrapper' object has no attribute 'plan'
ERROR 02-06 10:07:45 engine.py:387] Traceback (most recent call last):
ERROR 02-06 10:07:45 engine.py:387]   File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/engine/multiprocessing/engine.py", line 378, in run_mp_engine
ERROR 02-06 10:07:45 engine.py:387]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 02-06 10:07:45 engine.py:387]   File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/engine/multiprocessing/engine.py", line 121, in from_engine_args
ERROR 02-06 10:07:45 engine.py:387]     return cls(ipc_path=ipc_path,
ERROR 02-06 10:07:45 engine.py:387]   File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/engine/multiprocessing/engine.py", line 73, in __init__
ERROR 02-06 10:07:45 engine.py:387]     self.engine = LLMEngine(*args, **kwargs)
ERROR 02-06 10:07:45 engine.py:387]   File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 274, in __init__
ERROR 02-06 10:07:45 engine.py:387]     self._initialize_kv_caches()
ERROR 02-06 10:07:45 engine.py:387]   File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 427, in _initialize_kv_caches
ERROR 02-06 10:07:45 engine.py:387]     self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
ERROR 02-06 10:07:45 engine.py:387]   File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 119, in initialize_cache
ERROR 02-06 10:07:45 engine.py:387]     self.collective_rpc("initialize_cache",
ERROR 02-06 10:07:45 engine.py:387]   File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 49, in collective_rpc
ERROR 02-06 10:07:45 engine.py:387]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 02-06 10:07:45 engine.py:387]   File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/utils.py", line 2208, in run_method
ERROR 02-06 10:07:45 engine.py:387]     return func(*args, **kwargs)
ERROR 02-06 10:07:45 engine.py:387]   File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/worker/worker.py", line 306, in initialize_cache
ERROR 02-06 10:07:45 engine.py:387]     self._warm_up_model()
ERROR 02-06 10:07:45 engine.py:387]   File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/worker/worker.py", line 336, in _warm_up_model
ERROR 02-06 10:07:45 engine.py:387]     self.model_runner.capture_model(self.gpu_cache)
ERROR 02-06 10:07:45 engine.py:387]   File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 02-06 10:07:45 engine.py:387]     return func(*args, **kwargs)
ERROR 02-06 10:07:45 engine.py:387]   File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1491, in capture_model
ERROR 02-06 10:07:45 engine.py:387]     self.attn_state.graph_capture_get_metadata_for_batch(
ERROR 02-06 10:07:45 engine.py:387]   File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/attention/backends/flashinfer.py", line 323, in graph_capture_get_metadata_for_batch
ERROR 02-06 10:07:45 engine.py:387]     attn_metadata.begin_forward()
ERROR 02-06 10:07:45 engine.py:387]   File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/attention/backends/flashinfer.py", line 496, in begin_forward
ERROR 02-06 10:07:45 engine.py:387]     self.decode_wrapper.plan(
ERROR 02-06 10:07:45 engine.py:387] AttributeError: 'CUDAGraphBatchDecodeWithPagedKVCacheWrapper' object has no attribute 'plan'
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/engine/multiprocessing/engine.py", line 389, in run_mp_engine
    raise e
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/engine/multiprocessing/engine.py", line 378, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/engine/multiprocessing/engine.py", line 121, in from_engine_args
    return cls(ipc_path=ipc_path,
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/engine/multiprocessing/engine.py", line 73, in __init__
    self.engine = LLMEngine(*args, **kwargs)
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 274, in __init__
    self._initialize_kv_caches()
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 427, in _initialize_kv_caches
    self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 119, in initialize_cache
    self.collective_rpc("initialize_cache",
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 49, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/utils.py", line 2208, in run_method
    return func(*args, **kwargs)
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/worker/worker.py", line 306, in initialize_cache
    self._warm_up_model()
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/worker/worker.py", line 336, in _warm_up_model
    self.model_runner.capture_model(self.gpu_cache)
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1491, in capture_model
    self.attn_state.graph_capture_get_metadata_for_batch(
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/attention/backends/flashinfer.py", line 323, in graph_capture_get_metadata_for_batch
    attn_metadata.begin_forward()
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/attention/backends/flashinfer.py", line 496, in begin_forward
    self.decode_wrapper.plan(
AttributeError: 'CUDAGraphBatchDecodeWithPagedKVCacheWrapper' object has no attribute 'plan'
[rank0]:[W206 10:07:45.391373257 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
Traceback (most recent call last):
  File "/mnt/anhnh/miniconda3/envs/commonenv/bin/vllm", line 8, in <module>
    sys.exit(main())
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/scripts.py", line 202, in main
    args.dispatch_function(args)
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/scripts.py", line 42, in serve
    uvloop.run(run_server(args))
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/uvloop/__init__.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 873, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 134, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/anhnh/miniconda3/envs/commonenv/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 228, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by ZIYU-DEEP** [comment]
updating [flashinfer](https://docs.flashinfer.ai/installation.html) works for me, e.g.,
```
pip install flashinfer-python -i https://flashinfer.ai/whl/cu124/torch2.5/
```
