### ISSUE TITLE
[Bug]: Runtime error occurs when running deepseek v3

### ISSUE THREAD

**Issue by m404notfound** [vllm-project/vllm#12827]
### Your current environment

When I use the following command：
    python3 -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --port 9111 --model /deepseek_v3 --max-num-batched-tokens 16384 --gpu-memory-utilization 0.97 --tensor-parallel-size 8  --disable-log-requests --trust-remote-code --enable-chunked-prefill

it shows runtimeerror: nccl error 1:unhandled cuda error (run with nccl_debug=info for details)

model: deepseek v3
vllm : v0.7.1--->pip3 install vllm
how can i do?

![Image](https://github.com/user-attachments/assets/38427d33-1fb5-435c-a537-95a2b736250b)

![Image](https://github.com/user-attachments/assets/b18f8b9f-b58a-48cd-bba2-3d3bec2dc664)

### 🐛 Describe the bug

When I use the following command：
    python3 -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --port 9111 --model /deepseek_v3 --max-num-batched-tokens 16384 --gpu-memory-utilization 0.97 --tensor-parallel-size 8  --disable-log-requests --trust-remote-code --enable-chunked-prefill

it shows runtimeerror: nccl error 1:unhandled cuda error (run with nccl_debug=info for details)

model: deepseek v3
vllm : v0.7.1--->pip3 install vllm
how can i do?

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Kevin-XiongC** [comment]
with NCCL_DEBUG_SUBSYS=ALL NCCL_DEBUG=TRACE env, I found that it turned out to be OOM when capturing the graph
