### ISSUE TITLE
Build failure due to CUDA version mismatch

### ISSUE THREAD

**Issue by WoosukKwon** [vllm-project/vllm#129]
I failed to build the system with the latest NVIDIA PyTorch docker image. The reason is PyTorch installed by `pip` is built with CUDA 11.7 while the container uses CUDA 12.1.

```
RuntimeError:
The detected CUDA version (12.1) mismatches the version that was used to compile
PyTorch (11.7). Please make sure to use the same CUDA versions.
```

**Comment by Joejoequ** [comment]
Same Issue Here. It looks like it did not use CUDA 11.8 in the conda environmnent.




File "/tmp/pip-build-env-_5k66uxz/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.0) mismatches the version that was used to compile
      PyTorch (11.7). Please make sure to use the same CUDA versions.



(vllm) x@x:~/xx$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by WoosukKwon** [comment]
@Joejoequ Thanks for reporting it! I think in your case, the problem can be easily solved by installing CUDA 11.8 version of PyTorch:
```bash
pip3 install torch --index-url https://download.pytorch.org/whl/cu118
```

**Comment by Joejoequ** [comment]
@WoosukKwon Thanks for the quick response! But the issue still exists after using the command above. It is weird that the detected version is 12.0 since the cudatookit installed in the env is 11.8. Looks like it will access Cuda outside the env.

**Comment by Joejoequ** [comment]
> @WoosukKwon Thanks for the quick response! But the issue still exists after using the command above. It is weird that the detected version is 12.0 since the cudatookit installed in the env is 11.8. Looks like it will access Cuda outside the env.

Finally i installed successfully by changing module env and use "module load" on linux server.

**Comment by mosheduminer** [comment]
I have the same problem. Pytorch using cuda 11.8 installed, yet I get this error when installing.

```sh
The detected CUDA version (12.1) mismatches the version that was used to compile
      PyTorch (11.8). Please make sure to use the same CUDA versions.
```

**Comment by DavidPeleg6** [comment]
im also having the same issue:
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

and i have installed nightly version of pytorch with cuda 12.1 support

**Comment by antonpolishko** [comment]
`nvcr.io/nvidia/pytorch:22.12-py3` images is the last one with CUDA 11.8 according to [compatibility matrix](https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html#framework-matrix-2022). Then images switched to CUDA 12+

**Comment by Ikkyu321** [comment]
> > @WoosukKwon Thanks for the quick response! But the issue still exists after using the command above. It is weird that the detected version is 12.0 since the cudatookit installed in the env is 11.8. Looks like it will access Cuda outside the env.
> 
> Finally i installed successfully by changing module env and use "module load" on linux server.
I got the same problem. Can you show me how to solve this？

**Comment by valentin-fngr** [comment]
> I have the same problem. Pytorch using cuda 11.8 installed, yet I get this error when installing.
> 
> ```shell
> The detected CUDA version (12.1) mismatches the version that was used to compile
>       PyTorch (11.8). Please make sure to use the same CUDA versions.
> ```

**Option 1 :** You have cuda 12.1 therefore you should simply uninstall the current binaries of pytorch that you have and then reinstall it using : 

`pip3 install torch torchvision torchaudio
`

**Option 2 :** If you do not want to use the cuda 12.1 that you have installed, you can use another version of cuda (11.7, 11.8, ...). 
First you need to uninstall your current cuda (https://stackoverflow.com/a/56827564) and then select the one you want on the cuda install website

**Comment by xunfeng1980** [comment]
same problem:
The detected CUDA version (12.3) mismatches the version that was used to compile
      PyTorch (11.7). Please make sure to use the same CUDA versions.

**Comment by Kkkassini** [comment]
Possible to use cuda 11.7? there's other services that require 11.7

**Comment by Lumingous** [comment]
I'm having the same problem. I've re-installed my pytorch to support cuda 11.8. Don't know why still shows this error

**Comment by jaesuny** [comment]
Removing pyproject.toml may be a solution.
In my case, the build system was using the version of pytorch from pyproject.toml rather than the pytorch already installed.

**Comment by xunfeng1980** [comment]
> Removing pyproject.toml may be a solution. In my case, the build system was using the version of pytorch from pyproject.toml rather than the pytorch already installed.

think,it work for me.

**Comment by StevenZ-G** [comment]
RuntimeError:
The detected CUDA version (12.3) mismatches the version that was used to compile
PyTorch (11.6). Please make sure to use the same CUDA versions.

**Comment by quanhephia** [comment]
> RuntimeError: The detected CUDA version (12.3) mismatches the version that was used to compile PyTorch (11.6). Please make sure to use the same CUDA versions.

I resolved this error by downgrading the version of vllm from 0.2.2 to 0.2.1

**Comment by Mruduldhawley** [comment]
> > @WoosukKwon Thanks for the quick response! But the issue still exists after using the command above. It is weird that the detected version is 12.0 since the cudatookit installed in the env is 11.8. Looks like it will access Cuda outside the env.
> 
> Finally i installed successfully by changing module env and use "module load" on linux server.

please elaborate.

**Comment by 0-hero** [comment]
1. Changed  env to run with CUDA 11.7
2. Install vllm with `pip install vllm` Without this step I face another error
3. Then install from source with `pip install -e .`

This solved it for me

**Comment by DuAooo** [comment]
For my problem, I found the the code used /usr/bin/nvcc which will print a different version
The right nvcc is in /usr/local/cuda/bin,
So I delete /usr/bin/nvcc, now my code works fine.

**Comment by 4daJKong** [comment]
> Possible to use cuda 11.7? there's other services that require 11.7

Is it possible to use vllm in cuda 11.7 ?
I tried `pip install vllm` in an conda environment, but still cannot install successfully.

**Comment by DrAlexLiu** [comment]
I solve this by running this:
conda install nvidia/label/cuda-11.8.0::cuda-nvcc

looks like your conda env has no nvcc installed, and it calls your system-based nvcc, which is not 11.8 or the cuda version you installed.

**Comment by Daishijun** [comment]
> Removing pyproject.toml may be a solution. In my case, the build system was using the version of pytorch from pyproject.toml rather than the pytorch already installed.

Thanks! You are a true hero.

**Comment by hmellor** [comment]
@WoosukKwon is this resolved now?

**Comment by hmellor** [comment]
Closing because the build system has changed dramatically since this was opened

**Comment by oJro** [comment]
> Removing pyproject.toml may be a solution. In my case, the build system was using the version of pytorch from pyproject.toml rather than the pytorch already installed.



> Removing pyproject.toml may be a solution. In my case, the build system was using the version of pytorch from pyproject.toml rather than the pytorch already installed.

how to remove pyproject.toml
