### ISSUE TITLE
[Bug]: torchvision.libs/libcudart.41118559.so.12 (deleted): cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wuyifan18** [vllm-project/vllm#13040]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
INFO 02-10 22:35:02 __init__.py:190] Automatically detected platform cuda.
Collecting environment information...
PyTorch version: 2.5.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Rocky Linux release 8.6 (Green Obsidian) (x86_64)
GCC version: (GCC) 11.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.11.11 (main, Dec 11 2024, 16:28:39) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 525.60.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              104
On-line CPU(s) list: 0-103
Thread(s) per core:  2
Core(s) per socket:  26
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Gold 5320 CPU @ 2.20GHz
Stepping:            6
CPU MHz:             3400.000
CPU max MHz:         3400.0000
CPU min MHz:         800.0000
BogoMIPS:            4400.00
Virtualization:      VT-x
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            39936K
NUMA node0 CPU(s):   0-25,52-77
NUMA node1 CPU(s):   26-51,78-103
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-ml-py==12.570.86
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pyzmq==26.2.1
[pip3] torch==2.5.1+cu121
[pip3] torchaudio==2.5.1
[pip3] torchvision==0.20.1
[pip3] transformers==4.48.3
[pip3] triton==3.1.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
[conda] nvidia-ml-py              12.570.86                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
[conda] pyzmq                     26.2.1                   pypi_0    pypi
[conda] torch                     2.5.1+cu121              pypi_0    pypi
[conda] torchaudio                2.5.1                    pypi_0    pypi
[conda] torchvision               0.20.1                   pypi_0    pypi
[conda] transformers              4.48.3                   pypi_0    pypi
[conda] triton                    3.1.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.7.2
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    CPU Affinity    NUMA Affinity
GPU0     X      0-25,52-77      0

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

CUDA_INC_PATH=/cm/shared/apps/cuda12.1/toolkit/12.1.1
LD_LIBRARY_PATH=/cm/local/apps/cuda/libs/current/lib64:/cm/shared/apps/cuda12.1/toolkit/12.1.1/targets/x86_64-linux/lib:/cm/shared/apps/slurm/current/lib64/slurm:/cm/shared/apps/slurm/current/lib64:/cm/local/apps/gcc/11.2.0/lib:/cm/local/apps/gcc/11.2.0/lib64:/cm/local/apps/gcc/11.2.0/lib32
CUDA_CMLOCAL_ROOT=/cm/local/apps/cuda/libs/current
CUDA_PATH=/cm/shared/apps/cuda12.1/toolkit/12.1.1
CUDA_INSTALL_PATH=/cm/shared/apps/cuda12.1/toolkit/12.1.1
CUDA_HOME=/cm/shared/apps/cuda12.1/toolkit/12.1.1
CUDA_HOME=/cm/shared/apps/cuda12.1/toolkit/12.1.1
CUDA_INC_PATH_modshare=/cm/shared/apps/cuda12.1/toolkit/12.1.1:1
CUDA_ROOT=/cm/shared/apps/cuda12.1/toolkit/12.1.1
CUDA_VISIBLE_DEVICES=0
CUDA_VISIBLE_DEVICES=0
CUDA_CACHE_DISABLE=1
CUDA_SDK=/cm/shared/apps/cuda12.1/sdk/12.1.1
NCCL_CUMEM_ENABLE=0
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY
```

</details>

### 🐛 Describe the bug

```python
from vllm import LLM
llm = LLM(model='/ceph/home/tong01/wyf/model/Qwen2.5-Coder-0.5B')
```

The error message:
```
INFO 02-10 22:19:29 config.py:542] This model supports multiple tasks: {'score', 'embed', 'classify', 'generate', 'reward'}. Defaulting to 'generate'.
INFO 02-10 22:19:29 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.2) with config: model='/ceph/home/tong01/wyf/model/Qwen2.5-Coder-0.5B', speculative_config=None, tokenizer='/ceph/home/tong01/wyf/model/Qwen2.5-Coder-0.5B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/ceph/home/tong01/wyf/model/Qwen2.5-Coder-0.5B, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/site-packages/vllm/utils.py", line 1051, in inner
    return fn(*args, **kwargs)
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 242, in __init__
    self.llm_engine = self.engine_class.from_engine_args(
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 484, in from_engine_args
    engine = cls(
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 273, in __init__
    self.model_executor = executor_class(vllm_config=vllm_config, )
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 51, in __init__
    self._init_executor()
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 40, in _init_executor
    self.collective_rpc("init_worker", args=([kwargs], ))
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 51, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/site-packages/vllm/utils.py", line 2220, in run_method
    return func(*args, **kwargs)
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/site-packages/vllm/worker/worker_base.py", line 551, in init_worker
    worker_class = resolve_obj_by_qualname(
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/site-packages/vllm/utils.py", line 1906, in resolve_obj_by_qualname
    module = importlib.import_module(module_name)
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/site-packages/vllm/worker/worker.py", line 12, in <module>
    from vllm.device_allocator.cumem import CuMemAllocator
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/site-packages/vllm/device_allocator/cumem.py", line 52, in <module>
    libcudart = CudaRTLibrary()
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/site-packages/vllm/distributed/device_communicators/cuda_wrapper.py", line 111, in __init__
    lib = ctypes.CDLL(so_file)
  File "/ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /ceph/home/tong01/miniconda3/envs/test-vllm/lib/python3.11/site-packages/torchvision.libs/libcudart.41118559.so.12 (deleted): cannot open shared object file: No such file or directory
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by l837948074** [comment]
same error +1

**Comment by kindernerd** [comment]
Same error, any suggestions?

**Comment by haotong-yang** [comment]
Meet the same error.

**Comment by robertzengcn** [comment]
similar problem with vllm : /~*/libcudart.*.so.12 (deleted): cannot open shared object file: No such file or directory

**Comment by kang-0909** [comment]
I think this is an issue with the ceph file system. I resolved it by copying the corresponding .so file to the /tmp directory and setting `export LD_LIBRARY_PATH=/tmp:$LD_LIBRARY_PATH`.

**Comment by Toyoid** [comment]
I think this issue may be caused by the interaction between pip + vLLM and certain filesystems. 

I encountered this error when running vLLM on a cluster with AFS (Andrew File System) storage. Here are my analysis assisted with claude opus 4.6:

## My Environment Details

- **Cluster**: Server with AFS storage
- **Python**: 3.12
- **vLLM**: 0.8.5.post1
- **PyTorch**: 2.6.0+cu124
- **Torchvision**: 0.21.0

## The Cause

### The Chain of Events

1. **AFS Cache Behavior**: When pip installs/upgrades packages on AFS, the AFS client cache can retain stale file metadata
2. **Package Installation Order**: 
   - First install creates `torchvision` with `torchvision.libs/libcudart.HASH_A.so.12`
   - Later install upgrades `torchvision`, deleting old libs and creating new ones with different hashes
   - AFS cache still references the old inode
3. **vLLM's Library Detection**:
   - vLLM's `cuda_wrapper.py` scans `/proc/self/maps` to find `libcudart`
   - It finds the path with `(deleted)` marker (stale AFS cache entry)
   - Tries to load it with `ctypes.CDLL()` → **OSError**

### Code Flow in vLLM
My vllm version is 0.8.5.post1:
```python
# vllm/distributed/device_communicators/cuda_wrapper.py
def __init__(self, so_file: Optional[str] = None):
    if so_file is None:
        so_file = find_loaded_library("libcudart")  # ← Reads /proc/self/maps
        if so_file is None:      # ← Never reaches here if find_loaded_library returns "(deleted)" path
            so_file = envs.VLLM_CUDART_SO_PATH
        assert so_file is not None, \
            (
                "libcudart is not loaded in the current process, "
                "try setting VLLM_CUDART_SO_PATH"
            )
    if so_file not in CudaRTLibrary.path_to_library_cache:
        lib = ctypes.CDLL(so_file)        # ← FAILS with "(deleted)" path
```

## The Fix

### Step 1: Check VLLM_CUDART_SO_PATH First in vLLM's `cuda_wrapper.py`

Edit `vllm/distributed/device_communicators/cuda_wrapper.py` in around line 104 to:
```python
def __init__(self, so_file: Optional[str] = None):
    # Check environment variable FIRST before scanning /proc/self/maps
    if so_file is None and envs.VLLM_CUDART_SO_PATH:
        so_file = envs.VLLM_CUDART_SO_PATH
    if so_file is None:
        so_file = find_loaded_library("libcudart")
        if so_file is None:
            so_file = envs.VLLM_CUDART_SO_PATH
```

### Step 2: Set Environment Variable

Add to your `~/.bashrc` or training launch script:

```bash
export VLLM_CUDART_SO_PATH=/path/to/conda/envs/YOUR_ENV/lib/python3.x/site-packages/nvidia/cuda_runtime/lib/libcudart.so.12
```

You may find your conda/virtual env's libcudart path by:

```bash
find /path/to/conda/envs/YOUR_ENV -name "libcudart.so*" -not -path "*.libs*"
```

### Step 3: Verify the Fix

```bash
python3 -c "from vllm.device_allocator.cumem import CuMemAllocator; print('OK')"
```

Should print `OK` without errors.
