### ISSUE TITLE
[Feature]: Support for RTX 5090 (CUDA 12.8)

### ISSUE THREAD

**Issue by rubentorresbonet** [vllm-project/vllm#13306]
### 🚀 The feature, motivation and pitch

Currently only nightlies from torch targeting 12.8 support blackwell such as the rtx 5090.
I tried using VLLM with a rtx 5090 and no dice. Vanilla vllm installation ends in:
```
NVIDIA GeForce RTX 5090 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
RuntimeError: CUDA error: no kernel image is available for execution on the device
```
Thanks

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by cyril23** [comment]
If anyone has any ideas, I can try it out.

Apparently:
- I guess you need https://github.com/vllm-project/vllm/pull/12702/files
- Adapt the Dockerfile:
  - Replace [this](https://github.com/vllm-project/vllm/blob/992e5c3d34776cae25a9fecf0a45d51fa69d6dbc/Dockerfile#L58) with the nightly 12.8 (`pip install --upgrade --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128`, and maybe update `"torch==2.7.0.dev20250121+cu126" "torchvision==0.22.0.dev20250121"` to newer versions too?)
  - Update CUDA Version to some 12.8 e.g. [here](https://github.com/vllm-project/vllm/blob/992e5c3d34776cae25a9fecf0a45d51fa69d6dbc/Dockerfile#L157C5-L157C17)
- Adapt the `requirements-build.txt` [torch version](https://github.com/vllm-project/vllm/blob/992e5c3d34776cae25a9fecf0a45d51fa69d6dbc/requirements-build.txt#L7) to the new one
- Adapt the `requirements-cuda.txt` too, [torch](https://github.com/vllm-project/vllm/blob/992e5c3d34776cae25a9fecf0a45d51fa69d6dbc/requirements-cuda.txt#L6), torchvision, torchaudio versions

But not sure how exactly to do it. Can anyone help me out?

**Comment by hxssgaa** [comment]
> If anyone has any ideas, I can try it out on a RTX 5090.
> 
> Apparently:
> 
> * I guess you need https://github.com/vllm-project/vllm/pull/12702/files
> * Adapt the Dockerfile:
>   
>   * Replace [this](https://github.com/vllm-project/vllm/blob/992e5c3d34776cae25a9fecf0a45d51fa69d6dbc/Dockerfile#L58) with the nightly 12.8 (`pip install --upgrade --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128`, and maybe update `"torch==2.7.0.dev20250121+cu126" "torchvision==0.22.0.dev20250121"` to newer versions too?)
>   * Update CUDA Version to some 12.8 e.g. [here](https://github.com/vllm-project/vllm/blob/992e5c3d34776cae25a9fecf0a45d51fa69d6dbc/Dockerfile#L157C5-L157C17)
> * Adapt the `requirements-build.txt` [torch version](https://github.com/vllm-project/vllm/blob/992e5c3d34776cae25a9fecf0a45d51fa69d6dbc/requirements-build.txt#L7) to the new one
> * Adapt the `requirements-cuda.txt` too, [torch](https://github.com/vllm-project/vllm/blob/992e5c3d34776cae25a9fecf0a45d51fa69d6dbc/requirements-cuda.txt#L6), torchvision, torchaudio versions
> 
> But not sure how exactly to do it. Can anyone help me out? ideally open up a Pullrequest and I'll try to build it, report back any errors, until we get it to run some inference e.g.

The above method doesn't work for me because of a cutlass compilation error

**Comment by shahizat** [comment]
hello @rubentorresbonet, any updates? Were you able to run it?

**Comment by rubentorresbonet** [comment]
nope, switched to tabbyapi

**Comment by JiapengLi** [comment]
https://github.com/vllm-project/vllm/issues/14452 anyone tried this?

**Comment by bryantbiggs** [comment]
FYI for Blackwell - https://github.com/pytorch/pytorch/issues/145949#issuecomment-2708878649

**Comment by g0t4** [comment]
BTW, cu128 nightly now has `pytorch-triton 3.3.0` which fixes a failure I had using speculative decoding on a 5090:

```log 
'sm_120' is not a recognized processor for this target (ignoring processor)
LLVM ERROR: Cannot select: intrinsic %llvm.nvvm.shfl.sync.bfly.i32 
```

Here are my notes:

https://github.com/triton-lang/triton/issues/5950#issuecomment-2728386276

**Comment by ssakar** [comment]
I have written a [tutorial](https://github.com/ssakar/tutorial/tree/main/vllm) for setting up vLLM for the rtx 5090.

**Comment by cyril23** [comment]
> [#14452](https://github.com/vllm-project/vllm/issues/14452) anyone tried this?

- yes, the custom build presented in https://github.com/vllm-project/vllm/issues/14452 works for me. I can build and run VLLM like that.

> I have written a [tutorial](https://github.com/ssakar/tutorial/tree/main/vllm) for setting up vLLM for the rtx 5090.

- thanks! Just tried it out, it works for me, too. 
- The solution is pretty similar to the one presented in https://github.com/vllm-project/vllm/issues/14452#issue-2903636026 but makes things a little bit easier, and you used better flags, like max jobs 4 etc. So maybe you post it in in https://github.com/vllm-project/vllm/issues/14452 too?
- Maybe in the https://github.com/ssakar/tutorial/tree/main/vllm#prerequisites you could give a hint for Ubuntu 22 users: they need to use a special repo in order to get podman 4+ which supports GPU etc., see https://github.com/containers/podman/issues/21249#issuecomment-1890753225 - else one is [stuck at podman 3](https://forums.developer.nvidia.com/t/nvidia-container-toolkit-podman-error-error-setting-up-cdi-devices-unresolvable-cdi-devices-nvidia-com-gpu-all/272286/3)

I would suggest a mod closes this issue here, and the discussion goes on in https://github.com/vllm-project/vllm/issues/14452 because that seems to be the main discussion now for 50XX Blackwell GPUs, and we don't need 2 separate issues?

**Comment by MrVolts** [comment]
> I have written a [tutorial](https://github.com/ssakar/tutorial/tree/main/vllm) for setting up vLLM for the rtx 5090.

Would this work with multi 5090 setups? I have two 5090's an am struggling with NCCL. Thanks

**Comment by ssakar** [comment]
> Would this work with multi 5090 setups? I have two 5090's and am struggling with NCCL. Thanks

Yes, that should work. Only difference would be the additional vllm args to use more than one gpu.

**Comment by MrVolts** [comment]
> > Would this work with multi 5090 setups? I have two 5090's and am struggling with NCCL. Thanks
> 
> Yes, that should work. Only difference would be the additional vllm args to use more than one gpu.

I've been trying to get it working, and while it works on a single 5090 using AWQ or BNB format, it does not work on fp8 due to CUTLASS errors and GPU unless I install the latest NCCL. So I'm currently trying to get it to work with fp8, which the 5090 natively supports, and multi-GPU, which is proving incredibly tricky.

**Comment by ExtReMLapin** [comment]
Gave a test with my 3 rtx 5090, slow as hell generation on 30k prompt with command-r 2024 (3 tokens per second)

With pytorch nightly + triton compiled with SM120 support

**Comment by MrVolts** [comment]
> Gave a test with my 3 rtx 5090, slow as hell generation on 30k tokens prompt with command-r 2024 (3 tokens per second)
> 
> With pytorch nightly + triton compiled with SM120 support
Would you mind sharing your dockerfile?

**Comment by ExtReMLapin** [comment]
Not using docker, built on ubuntu 24 04

**Comment by thad0ctor** [comment]
> Gave a test with my 3 rtx 5090, slow as hell generation on 30k tokens prompt with command-r 2024 (3 tokens per second)
> 
> With pytorch nightly + triton compiled with SM120 support

Yike that's no good.

I tried to get docker working from the linked example but it wouldn't work on Qwen3.

**Comment by cyril23** [comment]
> I tried to get docker working from the linked example but it wouldn't work on Qwen3.

Running vllm with RTX 5090 becomes easier and easier. Try that one: 
```
# 1. download github repo
git clone https://github.com/vllm-project/vllm
cd vllm/
git checkout tags/v0.9.0 -b mybranch

# 2. build
DOCKER_BUILDKIT=1 sudo docker build . --target vllm-openai \
  --tag myvllm --file docker/Dockerfile --build-arg max_jobs=4 \
  --build-arg nvcc_threads=1  \
  --build-arg torch_cuda_arch_list="12.0 12.1" \
  --build-arg RUN_WHEEL_CHECK=false

# 3. run
sudo docker run --runtime nvidia --gpus all \
	-v ~/.cache/huggingface:/root/.cache/huggingface \
	-p 8000:8000 \
	--env "HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN" \
	myvllm --model Qwen/Qwen3-8B \
	--enable-reasoning --reasoning-parser deepseek_r1
```
- check https://github.com/ssakar/tutorial/tree/main/vllm#run-vllm for optimization flags like
```
--env "VLLM_ATTENTION_BACKEND=FLASHINFER"
[...]
--gpu-memory-utilization 0.9 \
--enable-prefix-caching \
--enable-chunked-prefill \
--max-model-len 32768 \
--enable-auto-tool-choice --tool-call-parser hermes 
```

Once v0.9.0 is out on Dockerhub (a matter of days I guess) you can skip straight to step 3, see  https://github.com/vllm-project/vllm/issues/16901#issuecomment-2889080503

**Comment by julbra** [comment]
> Once v0.9.0 is out on Dockerhub (a matter of days I guess) you can skip straight to step 3, see [#16901 (comment)](https://github.com/vllm-project/vllm/issues/16901#issuecomment-2889080503)

Thank you @cyril23 using the steps you provided I made a local build using tag `v0.9.0.1` and that works fine on RTX 5090.
However for some reason, the official `0.9.0.1` image still does not work. I get the same:
` RuntimeError: CUDA error: no kernel image is available for execution on the device`

Wondering what's different with the official image.

**Comment by cyril23** [comment]
> However for some reason, the official `0.9.0.1` image still does not work. I get the same: ` RuntimeError: CUDA error: no kernel image is available for execution on the device`
> 
> Wondering what's different with the official image.

I've tried it out too today and got the same problem like you with `vllm/vllm-openai:latest` from [Dockerhub](https://hub.docker.com/r/vllm/vllm-openai). I don't know for sure, but checking this workflow for the [**Build wheel - CUDA 12.8**](https://github.com/vllm-project/vllm/blob/c8dcc159214a20650451dcd64b226f56671763f1/.buildkite/release-pipeline.yaml#L6):
https://github.com/vllm-project/vllm/blob/c8dcc159214a20650451dcd64b226f56671763f1/.buildkite/release-pipeline.yaml#L6 
- I  don't see any `--build-arg torch_cuda_arch_list=xxxx` being defined. But the workflows for building wheels for older CUDA versions do define it like [**Build wheel - CUDA 12.6**](https://github.com/vllm-project/vllm/blob/c8dcc159214a20650451dcd64b226f56671763f1/.buildkite/release-pipeline.yaml#L17) or [**Build wheel - CUDA 11.8**](https://github.com/vllm-project/vllm/blob/c8dcc159214a20650451dcd64b226f56671763f1/.buildkite/release-pipeline.yaml#L34).
- Maybe that's why it falls back to bulding kernels that are too old for RTX 5090 / sm_120. 
- Thus maybe one should add `--build-arg torch_cuda_arch_list="12.0 12.1"` or `--build-arg torch_cuda_arch_list="7.0 7.5 8.0 8.9 9.0+PTX 12.0 12.1"` to the CUDA 12.8 build workflow?
- edit: What I've mentioned previously just affects the **python wheels**. Probably they don't work either for that reason, havn't tried them yet.

But I can't say for sure and can't find the right Github action in the history https://github.com/vllm-project/vllm/actions which built a docker image and pushed it to https://hub.docker.com/r/vllm/vllm-openai at about [May 30, 2025 at 10:28 pm](https://github.com/user-attachments/assets/8e75001a-1448-4e60-b2fe-8ad94c314d2e) apparently. Maybe someone did it on their own computer and thus the publishing hasn't triggered a Github Action here?

edit: 
- Check out this [note within `vllm/.github/workflows/publish.yml`](https://github.com/vllm-project/vllm/blob/d459fae0a2c464e28680bc6d564c1de1b295029e/.github/workflows/publish.yml#L42)
  > NOTE(simon): No longer build wheel using GitHub Actions. See buildkite's release workflow. 
- So that's why I don't see wheels being built in Github Actions. Probably same goes for pushing to the Docker Hub.
- I can see in the [**Build release image**](https://github.com/vllm-project/vllm/blob/c8dcc159214a20650451dcd64b226f56671763f1/.buildkite/release-pipeline.yaml#L51) buildkite Workflow that they build and push a Docker image to https://gallery.ecr.aws/q9t5s3a7/vllm-release-repo too, and there is no `--build-arg torch_cuda_arch_list=xxxx` defined there either. So probably this AWS Docker Image does not work either for RTX 5090 / SM 120.  edit: Yes, I've tried out `sudo docker run --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface -p 8000:8000 public.ecr.aws/q9t5s3a7/vllm-release-repo:5fbbfe9a4c13094ad72ed3d6b4ef208a7ddc0fd7 --model TinyLlama/TinyLlama-1.1B-Chat-v1.0` and it fails too.
  > CUDA error: no kernel image is available for execution on the device
- Currently there is no `docker push vllm/vllm-openai:latest` defined anywhere in the Codebase. But according to https://github.com/vllm-project/vllm/pull/1709#issue-1999733628 maybe someone does it manually or maybe has setup a sync mechanism so once the Docker image is pushed to AWS, it is automatically pushed to Dockerhub, too.

edit again:
- In summary, the problem is that the [**Build release image**](https://github.com/vllm-project/vllm/blob/d459fae0a2c464e28680bc6d564c1de1b295029e/.buildkite/release-pipeline.yaml#L51) builtkite workflow does not define a `--build-arg torch_cuda_arch_list=xxxx` and thus the [default value `ARG torch_cuda_arch_list='7.0 7.5 8.0 8.9 9.0 10.0+PTX'`](https://github.com/vllm-project/vllm/blob/d459fae0a2c464e28680bc6d564c1de1b295029e/docker/Dockerfile#L80C1-L81C49) is being used (see [Docker docs about ARG default values](https://docs.docker.com/reference/dockerfile/#default-values)).
- RTX 5090 / SM 120 needs more recent compute capabilities 12.0 or 12.1. Therefore we still get the well-known
  > CUDA error: no kernel image is available for execution on the device

I'll open a Pull Request about it later on tonight. edit: I'm currently trying out what I've changed [here](https://github.com/cyril23/vllm/commit/fca70e61059ccb4ae403058874c2e1c441ae4737) and build Docker and Docker nightly for all those architectures.. it will take a while

edit again: maybe they havn't included 12.0, 12.1 yet because it might **increase the python wheel size > 400 MB** and vLLM's current pypi limit is hard stuck at <=400 MB. They're trying to increase the limit since 3 weeks, see https://github.com/pypi/support/issues/6326 - I'll add a notice about the resulting wheel size for `ARG torch_cuda_arch_list='7.0 7.5 8.0 8.9 9.0 10.0+PTX 10.1 12.0 12.1'` tomorrow when my build is finished

edit again: building with my current settings [`ARG torch_cuda_arch_list='7.0 7.5 8.0 8.9 9.0 10.0+PTX 10.1 12.0 12.1'`](https://github.com/cyril23/vllm/blob/fca70e61059ccb4ae403058874c2e1c441ae4737/docker/Dockerfile#L80C5-L80C25) resulted in a nearly 1 GB wheel: 
> `Not allowed: Wheel dist/dist/vllm-0.1.dev6949+gfca70e6.d20250605-cp38-abi3-linux_x86_64.whl is larger (922.18 MB) than the limit (400 MB).`

So that's why it hasn't been integrated yet. I'll try again with `12.0` only and check for a lower bound of Blackwell compatible wheels. 
edit: `torch_cuda_arch_list='12.0'` still results in a 548 MB file..

> ```
> sudo ls -la dist/dist
> total 535172
> drwxr-xr-x 2 root root      4096 Jun  5 12:13 .
> drwx------ 3 root root      4096 Jun  5 12:14 ..
> -rw-r--r-- 1 root root 548002550 Jun  5 12:14 vllm-0.1.dev6949+gfca70e6.d20250605-cp38-abi3-linux_x86_64.whl
> ```

edit: So in order to get SM120 Blackwell support at least in the Docker AWS image, the workaround would be to:
- either add `--build-arg torch_cuda_arch_list='7.0 7.5 8.0 8.9 9.0+PTX'` to [**Build wheel - CUDA 12.8**](https://github.com/vllm-project/vllm/blob/c48c6c4008ab3ba0a2ab2d9c04b285a5d6a58b88/.buildkite/release-pipeline.yaml#L7) (to keep wheelsize small) and add "12.0" to the [Dockerfile](https://github.com/vllm-project/vllm/blob/main/docker/Dockerfile) to make it the new default
- or add `--build-arg torch_cuda_arch_list='7.0 7.5 8.0 8.6 8.9 9.0 10.0 10.1 12.0+PTX'` to the Docker [**Build release image**](https://github.com/vllm-project/vllm/blob/c48c6c4008ab3ba0a2ab2d9c04b285a5d6a58b88/.buildkite/release-pipeline.yaml#L55) args which only affect the Docker image being pushed to AWS and not the wheels

**Comment by voipmonitor** [comment]
Hello, is anybody able to run it on two 5090 in parallel --tensor-parallel-size 2  without crashing? 


It is crashing in (VllmWorker rank=0 pid=602) ERROR 06-04 12:58:12 [multiproc_executor.py:523] RuntimeError: CUDA error: an illegal memory access was encountered

Ubuntu 24 lts -  Driver Version: 575.57.08, Kernel 6.11.0-26-generic 

How to reproduce 

DOCKER_BUILDKIT=1 docker build . --target vllm-openai   --tag myvllm --file docker/Dockerfile --build-arg max_jobs=36   --build-arg nvcc_threads=4    --build-arg torch_cuda_arch_list="12.0 12.1"   --build-arg RUN_WHEEL_CHECK=false

 docker run -v /root/models:/root/models -v /root/.cache/ccache/:/root/.cache/ccache/ -it --rm --gpus all  --ipc=host --ulimit memlock=-1 -p 8000:8000 --ulimit stack=67108864 --runtime nvidia --entrypoint bash myvllm:latest

VLLM_ATTENTION_BACKEND=FLASHINFER vllm serve /root/models/cognitivecomputations/Qwen3-30B-A3B-AWQ/ --enable-prefix-caching --enable-chunked-prefill --enable-reasoning --reasoning-parser deepseek_r1  --max-model-len 8192   --tensor-parallel-size 2 

is there any trick how to workaround this crash when -tensor-parallel-size is 2 ? (I know I can run it on one 5090, but I want to run larger models)

**Comment by mgoin** [comment]
This will be resolved in the next release! We landed support for SM120 in the wheel and docker image https://github.com/vllm-project/vllm/pull/19794

**Comment by baturgezici** [comment]
> Hello, is anybody able to run it on two 5090 in parallel --tensor-parallel-size 2 without crashing?
> 
> It is crashing in (VllmWorker rank=0 pid=602) ERROR 06-04 12:58:12 [multiproc_executor.py:523] RuntimeError: CUDA error: an illegal memory access was encountered
> 
> Ubuntu 24 lts - Driver Version: 575.57.08, Kernel 6.11.0-26-generic
> 
> How to reproduce
> 
> DOCKER_BUILDKIT=1 docker build . --target vllm-openai --tag myvllm --file docker/Dockerfile --build-arg max_jobs=36 --build-arg nvcc_threads=4 --build-arg torch_cuda_arch_list="12.0 12.1" --build-arg RUN_WHEEL_CHECK=false
> 
> docker run -v /root/models:/root/models -v /root/.cache/ccache/:/root/.cache/ccache/ -it --rm --gpus all --ipc=host --ulimit memlock=-1 -p 8000:8000 --ulimit stack=67108864 --runtime nvidia --entrypoint bash myvllm:latest
> 
> VLLM_ATTENTION_BACKEND=FLASHINFER vllm serve /root/models/cognitivecomputations/Qwen3-30B-A3B-AWQ/ --enable-prefix-caching --enable-chunked-prefill --enable-reasoning --reasoning-parser deepseek_r1 --max-model-len 8192 --tensor-parallel-size 2
> 
> is there any trick how to workaround this crash when -tensor-parallel-size is 2 ? (I know I can run it on one 5090, but I want to run larger models)

Were you able to use vLLM with two RTX 5090, using --tensor-parallel-size 2?

**Comment by ExtReMLapin** [comment]
yes it works, juts compile it yourself from scratch

**Comment by baturgezici** [comment]
@ExtReMLapin thank you! I managed to run it too
