### ISSUE TITLE
[Bug]: Error while running Deepseek-R1: vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly.

### ISSUE THREAD

**Issue by Wats0ns** [vllm-project/vllm#13676]
### Your current environment

<details>
Was working 10minutes ago, seems like after vllm crash whole GPUs are stuck ?

```
Traceback (most recent call last):
  File "/root/collect_env.py", line 17, in <module>
    from vllm.envs import environment_variables
  File "/usr/local/lib/python3.10/dist-packages/vllm/__init__.py", line 7, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 20, in <module>
    from vllm.executor.executor_base import ExecutorBase
  File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 15, in <module>
    from vllm.platforms import current_platform
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/dist-packages/vllm/platforms/__init__.py", line 222, in __getattr__
    _current_platform = resolve_obj_by_qualname(
  File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 1906, in resolve_obj_by_qualname
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/vllm/platforms/cuda.py", line 390, in <module>
    CudaPlatform.log_warnings()
  File "/usr/local/lib/python3.10/dist-packages/vllm/platforms/cuda.py", line 63, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/platforms/cuda.py", line 331, in log_warnings
    device_names = [
  File "/usr/local/lib/python3.10/dist-packages/vllm/platforms/cuda.py", line 332, in <listcomp>
    cls._get_physical_device_name(i) for i in range(device_ids)
  File "/usr/local/lib/python3.10/dist-packages/vllm/platforms/cuda.py", line 324, in _get_physical_device_name
    return pynvml.nvmlDeviceGetName(handle)
  File "/usr/local/lib/python3.10/dist-packages/pynvml.py", line 2342, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pynvml.py", line 2639, in nvmlDeviceGetName
    _nvmlCheckReturn(ret)
  File "/usr/local/lib/python3.10/dist-packages/pynvml.py", line 1042, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_Unknown: Unknown Error
```
</details>

### 🐛 Describe the bug

While running vllm as OpenAI compatible server to server Deepseek-R1 across 2 DGX-H100 with LWS, following error happened:
```
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581] Error executing method 'start_worker_execution_loop'. This might cause deadlock in distributed execution.
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581] Traceback (most recent call last):
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 573, in execute_method
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return run_method(target, method, args, kwargs)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 2196, in run_method
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return func(*args, **kwargs)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 91, in start_worker_exe
cution_loop
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     output = self.execute_model(execute_model_req=None)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 420, in execute_model
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     output = self.model_runner.execute_model(
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_contex
t
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return func(*args, **kwargs)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1724, in execute_model
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     hidden_or_intermediate_states = model_executable(
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]                                     ^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_
impl
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return self._call_impl(*args, **kwargs)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return forward_call(*args, **kwargs)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/deepseek_v2.py", line 677, in 
forward

(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     hidden_states = self.model(input_ids, positions, kv_caches,
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py", line 172, in __call__
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return self.forward(*args, **kwargs)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/deepseek_v2.py", line 633, in 
forward
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     hidden_states, residual = layer(positions, hidden_states,
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_
impl
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return self._call_impl(*args, **kwargs)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return forward_call(*args, **kwargs)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/deepseek_v2.py", line 550, in 
forward
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     hidden_states = self.self_attn(
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]                     ^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_
impl
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return self._call_impl(*args, **kwargs)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return forward_call(*args, **kwargs)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/deepseek_v2.py", line 469, in 
forward
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return self.mla_attn(hidden_states_or_q_c, kv_c_normed, k_pe, kv_cache,
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl

(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return self._call_impl(*args, **kwargs)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return forward_call(*args, **kwargs)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/vllm/attention/layer.py", line 201, in forward
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return torch.ops.vllm.unified_attention(
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/torch/_ops.py", line 1116, in __call__
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return self._op(*args, **(kwargs or {}))
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/vllm/attention/layer.py", line 307, in unified_attention
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return self.impl.forward(self, query, key, value, kv_cache, attn_metadata)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/vllm/attention/backends/mla/utils.py", line 457, in forward
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     self.rotary_emb(
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return self._call_impl(*args, **kwargs)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     return forward_call(*args, **kwargs)
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/rotary_embedding.py", line 710, in forward
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]     query_rot = query_rot * cos + rotate_fn(query_rot) * sin
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581]                 ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581] RuntimeError: CUDA error: unspecified launch failure
(RayWorkerWrapper pid=570) ERROR 02-21 08:03:30 worker_base.py:581] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.

ERROR 02-21 08:05:44 async_llm_engine.py:68] Engine background task failed
ERROR 02-21 08:05:44 async_llm_engine.py:68] Traceback (most recent call last):
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/async_llm_engine.py", line 58, in _log_task_completion
ERROR 02-21 08:05:44 async_llm_engine.py:68]     return_value = task.result()
ERROR 02-21 08:05:44 async_llm_engine.py:68]                    ^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/async_llm_engine.py", line 825, in run_engine_loop
ERROR 02-21 08:05:44 async_llm_engine.py:68]     result = task.result()
ERROR 02-21 08:05:44 async_llm_engine.py:68]              ^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/async_llm_engine.py", line 748, in engine_step
ERROR 02-21 08:05:44 async_llm_engine.py:68]     request_outputs = await self.engine.step_async(virtual_engine)
ERROR 02-21 08:05:44 async_llm_engine.py:68]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/async_llm_engine.py", line 353, in step_async
ERROR 02-21 08:05:44 async_llm_engine.py:68]     outputs = await self.model_executor.execute_model_async(
ERROR 02-21 08:05:44 async_llm_engine.py:68]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/ray_distributed_executor.py", line 583, in execute_model_async
ERROR 02-21 08:05:44 async_llm_engine.py:68]     return await super().execute_model_async(execute_model_req)
ERROR 02-21 08:05:44 async_llm_engine.py:68]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 354, in execute_model_async
ERROR 02-21 08:05:44 async_llm_engine.py:68]     return await self._driver_execute_model_async(execute_model_req)
ERROR 02-21 08:05:44 async_llm_engine.py:68]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/ray_distributed_executor.py", line 625, in _driver_execute_model_a
sync
ERROR 02-21 08:05:44 async_llm
ERROR 02-21 08:05:44 async_llm_engine.py:68]     results = await asyncio.gather(*tasks)
ERROR 02-21 08:05:44 async_llm_engine.py:68]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 1312, in _run_task_with_lock
ERROR 02-21 08:05:44 async_llm_engine.py:68]     return await task(*args, **kwargs)
ERROR 02-21 08:05:44 async_llm_engine.py:68]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68] ray.exceptions.RayTaskError(RuntimeError): ray::RayWorkerWrapper.execute_method() (pid=256, ip=172.29.46.242, actor_id=b18ba8248
d2f7d0a697062b002000000, repr=<vllm.executor.ray_utils.RayWorkerWrapper object at 0x7ffade21c6b0>)
ERROR 02-21 08:05:44 async_llm_engine.py:68]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 582, in execute_method
ERROR 02-21 08:05:44 async_llm_engine.py:68]     raise e
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 573, in execute_method
ERROR 02-21 08:05:44 async_llm_engine.py:68]     return run_method(target, method, args, kwargs)
ERROR 02-21 08:05:44 async_llm_engine.py:68]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 2196, in run_method
ERROR 02-21 08:05:44 async_llm_engine.py:68]     return func(*args, **kwargs)
ERROR 02-21 08:05:44 async_llm_engine.py:68]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 413, in execute_model
ERROR 02-21 08:05:44 async_llm_engine.py:68]     get_pp_group().recv_tensor_dict(
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/vllm/distributed/parallel_state.py", line 626, in recv_tensor_dict
ERROR 02-21 08:05:44 async_llm_engine.py:68]     recv_metadata_list = self.recv_object(src=src)
ERROR 02-21 08:05:44 async_llm_engine.py:68]                          ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/vllm/distributed/parallel_state.py", line 440, in recv_object
ERROR 02-21 08:05:44 async_llm_engine.py:68]     rank_size = torch.distributed.recv(size_tensor,
ERROR 02-21 08:05:44 async_llm_engine.py:68]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
ERROR 02-21 08:05:44 async_llm_engine.py:68]     return func(*args, **kwargs)
ERROR 02-21 08:05:44 async_llm_engine.py:68]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 02-21 08:05:44 async_llm_engine.py:68]   File "/usr/local/lib/python3.12/dist-packages/torch/distributed/distributed_c10d.py", line 2203, in recv
ERROR 02-21 08:05:44 async_llm_engine.py:68]     pg.recv([tensor], group_src_rank, tag).wait()

ERROR 02-21 08:05:44 async_llm_engine.py:68] RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to co
mplete
Exception in callback functools.partial(<function _log_task_completion at 0x7ffe81c3aac0>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_
llm_engine.AsyncLLMEngine object at 0x7ffe697ecda0>>)
handle: <Handle functools.partial(<function _log_task_completion at 0x7ffe81c3aac0>, error_callback=<bound method AsyncLLMEngine._error_callback of <vllm.engine.async_llm_en
gine.AsyncLLMEngine object at 0x7ffe697ecda0>>)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/async_llm_engine.py", line 58, in _log_task_completion
    return_value = task.result()
                   ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/async_llm_engine.py", line 825, in run_engine_loop
    result = task.result()
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/async_llm_engine.py", line 748, in engine_step
    request_outputs = await self.engine.step_async(virtual_engine)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/async_llm_engine.py", line 353, in step_async
    outputs = await self.model_executor.execute_model_async(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/ray_distributed_executor.py", line 583, in execute_model_async
    return await super().execute_model_async(execute_model_req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 354, in execute_model_async
    return await self._driver_execute_model_async(execute_model_req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/ray_distributed_executor.py", line 625, in _driver_execute_model_async
    results = await asyncio.gather(*tasks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 1312, in _run_task_with_lock
    return await task(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ray.exceptions.RayTaskError(RuntimeError): ray::RayWorkerWrapper.execute_method() (pid=256, ip=172.29.46.242, actor_id=b18ba8248d2f7d0a697062b002000000, repr=<vllm.executor.
ray_utils.RayWorkerWrapper object at 0x7ffade21c6b0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 582, in execute_method
    raise e
  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 573, in execute_method
    return run_method(target, method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 2196, in run_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 413, in execute_model
    get_pp_group().recv_tensor_dict(
  File "/usr/local/lib/python3.12/dist-packages/vllm/distributed/parallel_state.py", line 626, in recv_tensor_dict
    recv_metadata_list = self.recv_object(src=src)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/distributed/parallel_state.py", line 440, in recv_object
    rank_size = torch.distributed.recv(size_tensor,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/distributed_c10d.py", line 2203, in recv
    pg.recv([tensor], group_src_rank, tag).wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 63, in uvloop.loop.Handle._run
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/async_llm_engine.py", line 70, in _log_task_completion
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
```
vLLM launched with:
```python3 -m vllm.entrypoints.openai.api_server --port 8080 --model deepseek-ai/DeepSeek-R1 --tensor-parallel-size 8 --pipeline_parallel_size 2 --trust-remote-code --max-model-len 16384 --gpu-memory-utilization 0.85 --max-num-seqs 4 --served-model-name DeepSeek-R1-671b --disable-log-requests```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by z-w-wang** [comment]
Hello!Have you solved this problem? I am getting the same log.

**Comment by Wats0ns** [comment]
This was due to a hardware/driver issue, fixed by upgrading cuda+NVIDIA drivers
