### ISSUE TITLE
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by DoliteMatheo** [vllm-project/vllm#1369]
When I used vllm to serve my local model, the terminal displayed the following message:
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
The traceback pointed to the following code in site-packages/vllm/utils.py and the execution of the single line could also trigger the same error:

"from vllm import cuda_utils"

I suppose it may be caused by the mismatch between vllm and my CUDA version or Pytorch version. The CUDA version is 12.2 (only this version installed) on my machine and installing a new version 11 is not so convenient, the Pytorch version is 2.1.0, vllm version is 0.2.0
How could I solve the problem without re-install CUDA 11?
Many thanks!

**Comment by alan1989** [comment]
I encountered the same problem, did you solve it?

**Comment by DoliteMatheo** [comment]
> I encountered the same problem, did you solve it?

Unfortunately, I didn't find a better solution than installing CUDA 11, but I don't want to make any change about the CUDA version since the machine is not my private, and re-installing CUDA often cause many more unexpected problems. If you have got any solution, please tell me, much appreciated.

**Comment by bhupendrathore** [comment]
I tried with cuda 12.2. I get  the same error, when trying with cuda 11.7 getting the following error : 
`RuntimeError: The NVIDIA driver on your system is too old (found version 11070). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org/ to install a PyTorch version that has been compiled with your version of the CUDA driver.`

**Comment by alan1989** [comment]
i have sloved it. first find the libcudart.so.11.0 path on your disk.then write it into LD_LIBRARY_PATH

locate libcudart.so.11.0
export LD_LIBRARY_PATH=(the libcudart.so.11.0 path you find):$LD_LIBRARY_PATH

**Comment by vemonet** [comment]
We are getting the same "error", but with CUDA `12.1`

I am not sure who's fault is it, but throwing an error for the reason that "we cannot find a file we installed ourselves so we crash everything" is a bit ridiculous  

Here is the code to reproduce (cf. below to see in which docker image to run this)

```python
from langchain.chains import ConversationChain
from langchain.memory import ConversationBufferMemory
from langchain.llms import VLLM

llm = VLLM(
    model="mistralai/Mistral-7B-Instruct-v0.1",
    max_new_tokens=8000,
    top_k=10,
    top_p=0.95,
    temperature=0.8,
)

conversation = ConversationChain(
    llm=llm, verbose=True, memory=ConversationBufferMemory()
)

print(conversation.predict(input="Hi mom!"))
```

Here is the full error we get:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/vllm.py", line 79, in validate_environment
    from vllm import LLM as VLLModel
  File "/usr/local/lib/python3.10/dist-packages/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 6, in <module>
    from vllm.config import (CacheConfig, ModelConfig, ParallelConfig,
  File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 8, in <module>
    from vllm.utils import get_cpu_memory
  File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 8, in <module>
    from vllm import cuda_utils
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/share/code-llama/run_vllm.py", line 5, in <module>
    llm = VLLM(
  File "/usr/local/lib/python3.10/dist-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1102, in pydantic.main.validate_model
  File "/usr/local/lib/python3.10/dist-packages/langchain/llms/vllm.py", line 81, in validate_environment
    raise ImportError(
ImportError: Could not import vllm python package. Please install it with `pip install vllm`.
```

### 1. We use official nvidia images

Here is our setup: **We are literally using the official CUDA image from nvidia**: `nvcr.io/nvidia/cuda:12.1.0-devel-ubuntu22.04`

Starting from that the message "can't find libcudart" has no reason to exist, or the Nvidia devs who have built this image are highly incompetent.


### 2. We made sure to have the right CUDA version

We don't use the pytorch one like recommended by vllm docs because with the pytorch one we can't control exactly which CUDA version gets installed, and then we get error like "muuuuh pytorch was compiled with a different CUDA version" . Also pytorch GPU image is like ~9G vs ~3G for CUDA 

`nvidia-smi` shows we are using CUDA 12.1:

```bash
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
```

`pip list | grep cuda` shows we have the CUDA version 12.1 installed everywhere:


```bash
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
```

### 3. It was working last week 🫠

We managed to make it work last week when running in a old pytorch docker image that was still on py 3.8. But now it is broken when running on up-to-date images (what a mess), always complaining about this non-existing error with libcudart location

### 4. Trying the fix

Running `locate libcudart.so.11.0` does not find anything inside the CUDA docker image. So we could not even try the proposed fix.

But it would be really ridiculous if that would work, it should be handled during the image build time. 

If Nvidia devs are not competent enough to write down a working Dockerfile, then they should just make it open source, so we can teach them

**Comment by vemonet** [comment]
A potential approach to fix it:  it could be due to the `torch` version which is fixed to 2.0.1 : https://github.com/vllm-project/vllm/blob/main/pyproject.toml#L6

Because `torch` 2.0.1 does not have a variant for CUDA 12 (only CUDA 11)
Maybe installing a new `torch` version should work

I'll try to re-build `vllm` without version limitations for torch to see if that helps

**Comment by copasseron** [comment]
> A potential approach to fix it: it could be due to the `torch` version which is fixed to 2.0.1 : https://github.com/vllm-project/vllm/blob/main/pyproject.toml#L6
> 
> Because `torch` 2.0.1 does not have a variant for CUDA 12 (only CUDA 11) Maybe installing a new `torch` version should work
> 
> I'll try to re-build `vllm` without version limitations for torch to see if that helps

let me know if you've got any news here. 

I've got the same problem since this morning, with nvidia image as well `nvcr.io/nvidia/tritonserver:23.09-py3`.

**Comment by gesanqiu** [comment]
> If I understand the problem correctly, the issue was because v0.2.0 didn't fix the pytorch and xformers version. In v0.2.1 which was released today, we pinned their versions. So the error should not happen as long as you use CUDA 11.8.
> 
> We will support CUDA 12 once `xformers` releases a new stable version with CUDA 12 support. (While `xformers==0.0.22.post4` seems to include CUDA 12 binaries, I feel it's a bit unstable at the moment).

Right now Pytorch 2.0.1 is binded to CUDA 11.7, compile vLLM with CUDA 11.8 will get fialed, just the same issue like #1283 
I use `nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04` install vLLM with `pip install -e .`.

**Comment by DoliteMatheo** [comment]
> If I understand the problem correctly, the issue was because v0.2.0 didn't fix the pytorch and xformers version. In v0.2.1 which was released today, we pinned their versions. So the error should not happen as long as you use CUDA 11.8.
> 
> We will support CUDA 12 once `xformers` releases a new stable version with CUDA 12 support. (While `xformers==0.0.22.post4` seems to include CUDA 12 binaries, I feel it's a bit unstable at the moment).

Finally I installed CUDA 11.7 manually and the problem got fixed immediately. It seemed that vllm cannot work if there is only CUDA 12 installed on the machine.

**Comment by s-natsubori** [comment]
I encountered the same problem,
- docker base image : `nvcr.io/nvidia/pytorch:22.12-py3`
- `vllm==0.2.0`

and I solved this error with
add requirements.txt
`xformers==0.0.22`

`xformers==0.0.22` requires `nvidia-cuda-runtime-cu11==11.7.99` and etc.
Unfortunately it uninstall PyTorch2.1.0(originally installed)
but my code is working!!

**Comment by sanjana-sudo** [comment]
> I'm getting the same error on colab with `TheBloke-Dolphin-2.1-mistral-7B-GPTQ` which was working...

@bitsnaps same problem here. did you find any solution?

**Comment by bitsnaps** [comment]
> > I'm getting the same error on colab with `TheBloke-Dolphin-2.1-mistral-7B-GPTQ` which was working...
> 
> @bitsnaps same problem here. did you find any solution?

Not yet, I believe this is something to do with mistral/transformer/huggingface issue (not vllm), I'm not even able to run mistral-7b on colab which was working fine last week.

**Comment by sanjana-sudo** [comment]
> > > I'm getting the same error on colab with `TheBloke-Dolphin-2.1-mistral-7B-GPTQ` which was working...
> > 
> > 
> > @bitsnaps same problem here. did you find any solution?
> 
> Not yet, I believe this is something to do with mistral/transformer/huggingface issue (not vllm), I'm not even able to run mistral-7b on colab which was working fine last week.

@bitsnaps I tried to run the Mistral_7B_Instruct_v0_1_GGUF now and its working. I just downgraded gradio to ` gradio==3.32.0 ` and did not change anything related to flash.

**Comment by s-natsubori** [comment]
Currently, AutoAWQ deliver two versions. (cuda11 and cudda12）
I recommend that you try a combination of both to suit your environment.
and chek other pakeges too.

``
pip install autoawq  (torch 2.1.0 + CUDA 12.1.1)
``
from github(cuda11）
``
pip install https://github.com/casper-hansen/AutoAWQ/releases/download/v0.1.6/autoawq-0.1.6+cu118-cp310-cp310-linux_x86_64.whl
``

**Comment by D-Octopus** [comment]
You may want to consider **updating vllm to version 0.2.2**, as it appears this issue has been resolved in that version.
[v0.2.2 Major changes](https://github.com/vllm-project/vllm/releases/tag/v0.2.2)
[Upgrade to CUDA 12 #1527](https://github.com/vllm-project/vllm/pull/1527)

**Comment by D-Octopus** [comment]
> I encountered the same problem, did you solve it?
We gave the v0.2.2 update for vllm a shot, and it worked for us.
[v0.2.2 Major changes](https://github.com/vllm-project/vllm/releases/tag/v0.2.2)
https://github.com/vllm-project/vllm/pull/1527

**Comment by LI-ZHAODONG** [comment]
I'm using **llmware library** and was facing the same error. I upgraded toch _(2.0.1 -> 2.1.0)_ and solved the prob.

**Comment by ibnzahoor98** [comment]
> pip install xformers==v0.0.22

Thank you! Worked like a charm!

**Comment by Provemj** [comment]
It's probably just a cuda or torch version problem, try downgrading it

**Comment by HarikrishnanK9** [comment]
> i have sloved it. first find the libcudart.so.11.0 path on your disk.then write it into LD_LIBRARY_PATH
> 
> locate libcudart.so.11.0 export LD_LIBRARY_PATH=(the libcudart.so.11.0 path you find):$LD_LIBRARY_PATH
Thank You @alan1989  It Worked for me. export LD_LIBRARY_PATH=/home/hari/anaconda3/envs/prod_env/lib
