### ISSUE TITLE
[Usage]: Low GPU utilization when running Deepseek-r1-distill-llama-8B

### ISSUE THREAD

**Issue by xuuHuang** [vllm-project/vllm#14022]
### Your current environment

```text
The output of `python collect_env.py`

PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.1
Libc version: glibc-2.35

Python version: 3.11.11 (main, Dec 11 2024, 16:28:39) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.10.134-16.101.al8.x86_64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA L20Y
GPU 1: NVIDIA L20Y
GPU 2: NVIDIA L20Y
GPU 3: NVIDIA L20Y
GPU 4: NVIDIA L20Y
GPU 5: NVIDIA L20Y
GPU 6: NVIDIA L20Y
GPU 7: NVIDIA L20Y

Nvidia driver version: 535.183.06
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
架构：                           x86_64
CPU 运行模式：                   32-bit, 64-bit
Address sizes:                   46 bits physical, 57 bits virtual
字节序：                         Little Endian
CPU:                             192
在线 CPU 列表：                  0-191
厂商 ID：                        GenuineIntel
型号名称：                       Intel(R) Xeon(R) Platinum 8468V
CPU 系列：                       6
型号：                           143
每个核的线程数：                 2
每个座的核数：                   48
座：                             2
步进：                           8
CPU 最大 MHz：                   3800.0000
CPU 最小 MHz：                   800.0000
BogoMIPS：                       4800.00
标记：                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req hfi avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm uintr md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
虚拟化：                         VT-x
L1d 缓存：                       4.5 MiB (96 instances)
L1i 缓存：                       3 MiB (96 instances)
L2 缓存：                        192 MiB (96 instances)
L3 缓存：                        195 MiB (2 instances)
NUMA 节点：                      2
NUMA 节点0 CPU：                 0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102,104,106,108,110,112,114,116,118,120,122,124,126,128,130,132,134,136,138,140,142,144,146,148,150,152,154,156,158,160,162,164,166,168,170,172,174,176,178,180,182,184,186,188,190
NUMA 节点1 CPU：                 1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103,105,107,109,111,113,115,117,119,121,123,125,127,129,131,133,135,137,139,141,143,145,147,149,151,153,155,157,159,161,163,165,167,169,171,173,175,177,179,181,183,185,187,189,191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-ml-py==12.570.86
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] pyzmq==26.2.1
[pip3] torch==2.5.1
[pip3] torchaudio==2.5.1
[pip3] torchvision==0.20.1
[pip3] transformers==4.49.0
[pip3] triton==3.1.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
[conda] nvidia-ml-py              12.570.86                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
[conda] pyzmq                     26.2.1                   pypi_0    pypi
[conda] torch                     2.5.1                    pypi_0    pypi
[conda] torchaudio                2.5.1                    pypi_0    pypi
[conda] torchvision               0.20.1                   pypi_0    pypi
[conda] transformers              4.49.0                   pypi_0    pypi
[conda] triton                    3.1.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.7.3
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	NIC0	NIC1	NIC2	NIC3	NIC4	NIC5	NIC6	NIC7	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV8	NV8	NV8	NV8	NV8	NV8	NV8	PIX	NODE	NODE	NODE	SYS	SYS	SYS	SYS	0,2,4,6,8,10	0N/A
GPU1	NV8	 X 	NV8	NV8	NV8	NV8	NV8	NV8	NODE	PIX	NODE	NODE	SYS	SYS	SYS	SYS	0,2,4,6,8,10	0N/A
GPU2	NV8	NV8	 X 	NV8	NV8	NV8	NV8	NV8	NODE	NODE	PIX	NODE	SYS	SYS	SYS	SYS	0,2,4,6,8,10	0N/A
GPU3	NV8	NV8	NV8	 X 	NV8	NV8	NV8	NV8	NODE	NODE	NODE	PIX	SYS	SYS	SYS	SYS	0,2,4,6,8,10	0N/A
GPU4	NV8	NV8	NV8	NV8	 X 	NV8	NV8	NV8	SYS	SYS	SYS	SYS	PIX	NODE	NODE	NODE	1,3,5,7,9,11	1N/A
GPU5	NV8	NV8	NV8	NV8	NV8	 X 	NV8	NV8	SYS	SYS	SYS	SYS	NODE	PIX	NODE	NODE	1,3,5,7,9,11	1N/A
GPU6	NV8	NV8	NV8	NV8	NV8	NV8	 X 	NV8	SYS	SYS	SYS	SYS	NODE	NODE	PIX	NODE	1,3,5,7,9,11	1N/A
GPU7	NV8	NV8	NV8	NV8	NV8	NV8	NV8	 X 	SYS	SYS	SYS	SYS	NODE	NODE	NODE	PIX	1,3,5,7,9,11	1N/A
NIC0	PIX	NODE	NODE	NODE	SYS	SYS	SYS	SYS	 X 	NODE	NODE	NODE	SYS	SYS	SYS	SYS
NIC1	NODE	PIX	NODE	NODE	SYS	SYS	SYS	SYS	NODE	 X 	NODE	NODE	SYS	SYS	SYS	SYS
NIC2	NODE	NODE	PIX	NODE	SYS	SYS	SYS	SYS	NODE	NODE	 X 	NODE	SYS	SYS	SYS	SYS
NIC3	NODE	NODE	NODE	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	 X 	SYS	SYS	SYS	SYS
NIC4	SYS	SYS	SYS	SYS	PIX	NODE	NODE	NODE	SYS	SYS	SYS	SYS	 X 	NODE	NODE	NODE
NIC5	SYS	SYS	SYS	SYS	NODE	PIX	NODE	NODE	SYS	SYS	SYS	SYS	NODE	 X 	NODE	NODE
NIC6	SYS	SYS	SYS	SYS	NODE	NODE	PIX	NODE	SYS	SYS	SYS	SYS	NODE	NODE	 X 	NODE
NIC7	SYS	SYS	SYS	SYS	NODE	NODE	NODE	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	 X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_bond_0
  NIC1: mlx5_bond_1
  NIC2: mlx5_bond_2
  NIC3: mlx5_bond_3
  NIC4: mlx5_bond_4
  NIC5: mlx5_bond_5
  NIC6: mlx5_bond_6
  NIC7: mlx5_bond_7

NVIDIA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
NCCL_IB_TC=136
NVIDIA_REQUIRE_CUDA=cuda>=12.1 brand=tesla,driver>=450,driver<451 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=510,driver<511 brand=unknown,driver>=510,driver<511 brand=nvidia,driver>=510,driver<511 brand=nvidiartx,driver>=510,driver<511 brand=geforce,driver>=510,driver<511 brand=geforcertx,driver>=510,driver<511 brand=quadro,driver>=510,driver<511 brand=quadrortx,driver>=510,driver<511 brand=titan,driver>=510,driver<511 brand=titanrtx,driver>=510,driver<511 brand=tesla,driver>=515,driver<516 brand=unknown,driver>=515,driver<516 brand=nvidia,driver>=515,driver<516 brand=nvidiartx,driver>=515,driver<516 brand=geforce,driver>=515,driver<516 brand=geforcertx,driver>=515,driver<516 brand=quadro,driver>=515,driver<516 brand=quadrortx,driver>=515,driver<516 brand=titan,driver>=515,driver<516 brand=titanrtx,driver>=515,driver<516 brand=tesla,driver>=525,driver<526 brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526 brand=nvidiartx,driver>=525,driver<526 brand=geforce,driver>=525,driver<526 brand=geforcertx,driver>=525,driver<526 brand=quadro,driver>=525,driver<526 brand=quadrortx,driver>=525,driver<526 brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526
NCCL_MIN_NCHANNELS=4
NCCL_NET_PLUGIN=none
NCCL_VERSION=2.17.1-1
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NCCL_DEBUG=INFO
NCCL_IB_HCA=mlx5
VLLM_USE_MODELSCOPE=0
NVIDIA_PRODUCT_NAME=CUDA
NCCL_IB_GID_INDEX=3
NVIDIA_CUDA_END_OF_LIFE=1
CUDA_VERSION=12.1.0
NCCL_IB_QPS_PER_CONNECTION=8
NCCL_IB_TIMEOUT=22
NCCL_IB_SL=5
LD_LIBRARY_PATH=/cpfs01/shared/XNLP_H800/huangxu/envs/benchmax2/lib/python3.11/site-packages/cv2/../../lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
NCCL_CUMEM_ENABLE=0
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY
```

### How would you like to use vllm

The gpu utilization is **extremely low, about 20%,** when I am running inference of DeepSeek-R1-Distill-Llama-8B on a code benchmark.

The initialization of LLM and sampling parameters  is

```python
self.llm = LLM(
    model="DeepSeek-R1-Distill-Llama-8B",
    tensor_parallel_size=8,
    dtype="bfloat16",
    enforce_eager=True,
    disable_custom_all_reduce=True,
    enable_prefix_caching=True,
    max_num_seqs=600,
    gpu_memory_utilization=0.92,
    disable_log_stats=False,
)
self.sampling_params = SamplingParams(
    n=10,
    max_tokens=8192,
    temperature=0.2,
    top_p=0.95,
    frequency_penalty=0,
    presence_penalty=0,
)
```

And some of the logs are shown below:

```
INFO 02-28 15:02:09 metrics.py:455] Avg prompt throughput: 307.6 tokens/s, Avg generation throughput: 3210.7 tokens/s, Running: 600 reqs, Swapped: 0 reqs, Pending: 4475 reqs, GPU KV cache usage: 59.2%, CPU KV cache usage: 0.0%.
INFO 02-28 15:02:09 metrics.py:471] Prefix cache hit rate: GPU: 91.98%, CPU: 0.00%
INFO 02-28 15:02:14 metrics.py:455] Avg prompt throughput: 224.7 tokens/s, Avg generation throughput: 3126.7 tokens/s, Running: 600 reqs, Swapped: 0 reqs, Pending: 4472 reqs, GPU KV cache usage: 59.0%, CPU KV cache usage: 0.0%.
INFO 02-28 15:02:14 metrics.py:471] Prefix cache hit rate: GPU: 91.98%, CPU: 0.00%
INFO 02-28 15:02:19 metrics.py:455] Avg prompt throughput: 153.3 tokens/s, Avg generation throughput: 3200.1 tokens/s, Running: 600 reqs, Swapped: 0 reqs, Pending: 4470 reqs, GPU KV cache usage: 59.3%, CPU KV cache usage: 0.0%.
INFO 02-28 15:02:19 metrics.py:471] Prefix cache hit rate: GPU: 91.99%, CPU: 0.00%
INFO 02-28 15:02:24 metrics.py:455] Avg prompt throughput: 263.1 tokens/s, Avg generation throughput: 3259.7 tokens/s, Running: 600 reqs, Swapped: 0 reqs, Pending: 4468 reqs, GPU KV cache usage: 59.3%, CPU KV cache usage: 0.0%.
INFO 02-28 15:02:24 metrics.py:471] Prefix cache hit rate: GPU: 91.96%, CPU: 0.00%
INFO 02-28 15:02:29 metrics.py:455] Avg prompt throughput: 266.6 tokens/s, Avg generation throughput: 3184.8 tokens/s, Running: 600 reqs, Swapped: 0 reqs, Pending: 4466 reqs, GPU KV cache usage: 59.5%, CPU KV cache usage: 0.0%.
INFO 02-28 15:02:29 metrics.py:471] Prefix cache hit rate: GPU: 91.97%, CPU: 0.00%
Processed prompts:   3%|▊                             | 192/7130 [1:03:32<41:39:48, 21.62s/it, est. speed input: 28.86 toks/s, output: 2829.56 toks/s]INFO 02-28 15:02:34 metrics.py:455] Avg prompt throughput: 399.8 tokens/s, Avg generation throughput: 3184.1 tokens/s, Running: 600 reqs, Swapped: 0 reqs, Pending: 4463 reqs, GPU KV cache usage: 59.4%, CPU KV cache usage: 0.0%.
INFO 02-28 15:02:34 metrics.py:471] Prefix cache hit rate: GPU: 91.98%, CPU: 0.00%
INFO 02-28 15:02:39 metrics.py:455] Avg prompt throughput: 472.9 tokens/s, Avg generation throughput: 3185.5 tokens/s, Running: 600 reqs, Swapped: 0 reqs, Pending: 4459 reqs, GPU KV cache usage: 59.2%, CPU KV cache usage: 0.0%.
INFO 02-28 15:02:39 metrics.py:471] Prefix cache hit rate: GPU: 91.97%, CPU: 0.00%
INFO 02-28 15:02:44 metrics.py:455] Avg prompt throughput: 296.4 tokens/s, Avg generation throughput: 3236.1 tokens/s, Running: 600 reqs, Swapped: 0 reqs, Pending: 4455 reqs, GPU KV cache usage: 59.1%, CPU KV cache usage: 0.0%.
INFO 02-28 15:02:44 metrics.py:471] Prefix cache hit rate: GPU: 91.98%, CPU: 0.00%
INFO 02-28 15:02:49 metrics.py:455] Avg prompt throughput: 215.6 tokens/s, Avg generation throughput: 3138.0 tokens/s, Running: 600 reqs, Swapped: 0 reqs, Pending: 4452 reqs, GPU KV cache usage: 59.1%, CPU KV cache usage: 0.0%.
INFO 02-28 15:02:49 metrics.py:471] Prefix cache hit rate: GPU: 91.99%, CPU: 0.00%
INFO 02-28 15:02:54 metrics.py:455] Avg prompt throughput: 387.2 tokens/s, Avg generation throughput: 3235.1 tokens/s, Running: 600 reqs, Swapped: 0 reqs, Pending: 4447 reqs, GPU KV cache usage: 58.8%, CPU KV cache usage: 0.0%.
INFO 02-28 15:02:54 metrics.py:471] Prefix cache hit rate: GPU: 91.98%, CPU: 0.00%
INFO 02-28 15:02:59 metrics.py:455] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 3278.9 tokens/s, Running: 600 reqs, Swapped: 0 reqs, Pending: 4447 reqs, GPU KV cache usage: 59.2%, CPU KV cache usage: 0.0%.
INFO 02-28 15:02:59 metrics.py:471] Prefix cache hit rate: GPU: 91.98%, CPU: 0.00%
Processed prompts:   3%|▊                             | 193/7130 [1:04:00<45:27:25, 23.59s/it, est. speed input: 28.81 toks/s, output: 2830.12 toks/s]INFO 02-28 15:03:05 metrics.py:455] Avg prompt throughput: 465.1 tokens/s, Avg generation throughput: 3263.9 tokens/s, Running: 599 reqs, Swapped: 0 reqs, Pending: 4441 reqs, GPU KV cache usage: 58.5%, CPU KV cache usage: 0.0%.
INFO 02-28 15:03:05 metrics.py:471] Prefix cache hit rate: GPU: 91.99%, CPU: 0.00%
INFO 02-28 15:03:10 metrics.py:455] Avg prompt throughput: 239.4 tokens/s, Avg generation throughput: 3229.4 tokens/s, Running: 599 reqs, Swapped: 0 reqs, Pending: 4438 reqs, GPU KV cache usage: 58.6%, CPU KV cache usage: 0.0%.
INFO 02-28 15:03:10 metrics.py:471] Prefix cache hit rate: GPU: 91.98%, CPU: 0.00%
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by hmellor** [comment]
> tensor_parallel_size=8,

This model is too small for TP8 to make sense. Use multiple instances of `LLM` with a smaller TP size.

>    enforce_eager=True,

This disables graph compilation, which will cause more CPU overhead

>    disable_custom_all_reduce=True,

This will slow down the inter-GPU comminucations introduced by using TP

**Comment by xuuHuang** [comment]
Thanks for your response. I set `enforce_eager=False` and `disable_custom_all_reduce=False`, but the gpu utilization does not grow obviously. I also tried `tp=4` and `tp=2`, and the gpu utilization goes up to around 40%. I think it is still very low.

**Comment by hmellor** [comment]
Are you passing prompts one at a time or are you passing them in batches?

Passing them one at a time could be a reason for low utilisation of the GPU.

**Comment by xuuHuang** [comment]
No, I passed all of prompts together to the server, and set `max_num_seqs=600`. The server log above shows the throughput.

**Comment by hmellor** [comment]
Is the throughput higher or lower without `max_num_seqs`?

Also, does your model run if you use `VLLM_USE_V1=1`? That should speed things up if it's compatible with your config (eventually it will be compatible with everything, but it's in beta today)

**Comment by xuuHuang** [comment]
Based on the logs, I find the default value of `max_num_seqs` is 256. The throughput will be higher with larger `max_num_seqs`. However, setting it too high can increase the probability of preemption, which may negatively impact performance. So `max_num_seqs=600` might be a suitable balance.

`VLLM_USE_V1=1` is not compatible with `n=10` as reported in [https://github.com/vllm-project/vllm/issues/12584](url).

**Comment by hmellor** [comment]
I believe `n=10` is supported on the nightly wheel, it'll be in the next release too.

Also, what does the utilisation look like when you don't use tp?

**Comment by xuuHuang** [comment]
The utilization goes up to 60% without tp. If I further set `enforce_eager=False` and `disable_custom_all_reduce=False`, the utilization is around 80%.

BTW, I find that the utilization is related with the data. On other tasks, the utilization seems normal when `tp=8`, above 70%.

**Comment by hmellor** [comment]
Ok, in that case do you consider your issue resolved now that you are seeing more sensible numbers for GPU utilisation?
