### ISSUE TITLE
[Bug]:use vllm in docker

### ISSUE THREAD

**Issue by iwaitu** [vllm-project/vllm#14075]
### Your current environment

<details>
<summary>use vllm in docker</summary>

```text
(VllmWorkerProcess pid=216) INFO 03-01 07:34:33 model_runner.py:1110] Starting to load model models/Qwen2.5-72B-Instruct-FP8...
Loading safetensors checkpoint shards:   0% Completed | 0/16 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   6% Completed | 1/16 [00:00<00:13,  1.10it/s]
Loading safetensors checkpoint shards:  12% Completed | 2/16 [00:01<00:13,  1.01it/s]
Loading safetensors checkpoint shards:  19% Completed | 3/16 [00:02<00:12,  1.03it/s]
Loading safetensors checkpoint shards:  25% Completed | 4/16 [00:03<00:11,  1.04it/s]
Loading safetensors checkpoint shards:  31% Completed | 5/16 [00:04<00:10,  1.05it/s]
Loading safetensors checkpoint shards:  38% Completed | 6/16 [00:05<00:09,  1.05it/s]
Loading safetensors checkpoint shards:  44% Completed | 7/16 [00:06<00:06,  1.32it/s]
Loading safetensors checkpoint shards:  50% Completed | 8/16 [00:07<00:06,  1.18it/s]
Loading safetensors checkpoint shards:  56% Completed | 9/16 [00:08<00:06,  1.10it/s]
Loading safetensors checkpoint shards:  62% Completed | 10/16 [00:09<00:05,  1.08it/s]
Loading safetensors checkpoint shards:  69% Completed | 11/16 [00:10<00:04,  1.04it/s]
Loading safetensors checkpoint shards:  75% Completed | 12/16 [00:11<00:03,  1.02it/s]
Loading safetensors checkpoint shards:  81% Completed | 13/16 [00:12<00:03,  1.00s/it]
Loading safetensors checkpoint shards:  88% Completed | 14/16 [00:13<00:02,  1.02s/it]
Loading safetensors checkpoint shards:  94% Completed | 15/16 [00:14<00:00,  1.00it/s]
Loading safetensors checkpoint shards: 100% Completed | 16/16 [00:14<00:00,  1.10it/s]
Loading safetensors checkpoint shards: 100% Completed | 16/16 [00:14<00:00,  1.07it/s]

(VllmWorkerProcess pid=216) INFO 03-01 07:34:49 model_runner.py:1115] Loading model weights took 35.1441 GB
INFO 03-01 07:34:49 model_runner.py:1115] Loading model weights took 35.1441 GB
[rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1446, in _call_user_compiler
[rank0]:     compiled_fn = compiler_fn(gm, self.example_inputs())
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/repro/after_dynamo.py", line 129, in __call__
[rank0]:     compiled_gm = compiler_fn(gm, example_inputs)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/__init__.py", line 2234, in __call__
[rank0]:     return compile_fx(model_, inputs_, config_patches=self.config)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1521, in compile_fx
[rank0]:     return aot_autograd(
[rank0]:            ^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/backends/common.py", line 72, in __call__
[rank0]:     cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
[rank0]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 1071, in aot_module_simplified
[rank0]:     compiled_fn = dispatch_and_compile()
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 1056, in dispatch_and_compile
[rank0]:     compiled_fn, _ = create_aot_dispatcher_function(
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 522, in create_aot_dispatcher_function
[rank0]:     return _create_aot_dispatcher_function(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 759, in _create_aot_dispatcher_function
[rank0]:     compiled_fn, fw_metadata = compiler_fn(
[rank0]:                                ^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 179, in aot_dispatch_base
[rank0]:     compiled_fw = compiler(fw_module, updated_flat_args)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1350, in fw_compiler_base
[rank0]:     return _fw_compiler_base(model, example_inputs, is_inference)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1421, in _fw_compiler_base
[rank0]:     return inner_compile(
[rank0]:            ^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 475, in compile_fx_inner
[rank0]:     return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/repro/after_aot.py", line 85, in debug_wrapper
[rank0]:     inner_compiled_fn = compiler_fn(gm, example_inputs)
[rank0]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 661, in _compile_fx_inner
[rank0]:     compiled_graph = FxGraphCache.load(
[rank0]:                      ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 1334, in load
[rank0]:     compiled_graph = compile_fx_fn(
[rank0]:                      ^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 570, in codegen_and_compile
[rank0]:     compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 878, in fx_codegen_and_compile
[rank0]:     compiled_fn = graph.compile_to_fn()
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1913, in compile_to_fn
[rank0]:     return self.compile_to_module().call
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1839, in compile_to_module
[rank0]:     return self._compile_to_module()
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1845, in _compile_to_module
[rank0]:     self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
[rank0]:                                                              ^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1784, in codegen
[rank0]:     self.scheduler.codegen()
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/scheduler.py", line 3383, in codegen
[rank0]:     return self._codegen()
[rank0]:            ^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/scheduler.py", line 3461, in _codegen
[rank0]:     self.get_backend(device).codegen_node(node)
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codegen/cuda_combined_scheduling.py", line 80, in codegen_node
[rank0]:     return self._triton_scheduling.codegen_node(node)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codegen/simd.py", line 1155, in codegen_node
[rank0]:     return self.codegen_node_schedule(node_schedule, buf_accesses, numel, rnumel)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codegen/simd.py", line 1364, in codegen_node_schedule
[rank0]:     src_code = kernel.codegen_kernel()
[rank0]:                ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codegen/triton.py", line 2661, in codegen_kernel
[rank0]:     **self.inductor_meta_common(),
[rank0]:       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codegen/triton.py", line 2532, in inductor_meta_common
[rank0]:     "backend_hash": torch.utils._triton.triton_hash_with_backend(),
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_triton.py", line 53, in triton_hash_with_backend
[rank0]:     backend = triton_backend()
[rank0]:               ^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_triton.py", line 45, in triton_backend
[rank0]:     target = driver.active.get_current_target()
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/triton/runtime/driver.py", line 23, in __getattr__
[rank0]:     self._initialize_obj()
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/triton/runtime/driver.py", line 20, in _initialize_obj
[rank0]:     self._obj = self._init_fn()
[rank0]:                 ^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/triton/runtime/driver.py", line 9, in _create_driver
[rank0]:     return actives[0]()
[rank0]:            ^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/triton/backends/nvidia/driver.py", line 371, in __init__
[rank0]:     self.utils = CudaUtils()  # TODO: make static
[rank0]:                  ^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/triton/backends/nvidia/driver.py", line 80, in __init__
[rank0]:     mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/triton/backends/nvidia/driver.py", line 57, in compile_module_from_src
[rank0]:     so = _build(name, src_path, tmpdir, library_dirs(), include_dir, libraries)
[rank0]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/triton/runtime/build.py", line 32, in _build
[rank0]:     raise RuntimeError("Failed to find C compiler. Please specify via CC environment variable.")
[rank0]: RuntimeError: Failed to find C compiler. Please specify via CC environment variable.

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/qwen/api_server.py", line 21, in <module>
[rank0]:     chat_model = ChatModel(args_dict)
[rank0]:                  ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/qwen/llamafactory/chat/chat_model.py", line 54, in __init__
[rank0]:     self.engine: "BaseEngine" = VllmEngine(model_args, data_args, finetuning_args, generating_args)
[rank0]:                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/root/qwen/llamafactory/chat/vllm_engine.py", line 95, in __init__
[rank0]:     self.model = AsyncLLMEngine.from_engine_args(AsyncEngineArgs(**engine_args))
[rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 644, in from_engine_args
[rank0]:     engine = cls(
[rank0]:              ^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 594, in __init__
[rank0]:     self.engine = self._engine_class(*args, **kwargs)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 267, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 276, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 416, in _initialize_kv_caches
[rank0]:     self.model_executor.determine_num_available_blocks())
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 101, in determine_num_available_blocks
[rank0]:     results = self.collective_rpc("determine_num_available_blocks")
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/executor/executor_base.py", line 307, in collective_rpc
[rank0]:     return self._run_workers(method, *args, **(kwargs or {}))
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/executor/mp_distributed_executor.py", line 185, in _run_workers
[rank0]:     driver_worker_output = run_method(self.driver_worker, sent_method,
[rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/utils.py", line 2220, in run_method
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/worker/worker.py", line 229, in determine_num_available_blocks
[rank0]:     self.model_runner.profile_run()
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1235, in profile_run
[rank0]:     self._dummy_run(max_num_batched_tokens, max_num_seqs)
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1346, in _dummy_run
[rank0]:     self.execute_model(model_input, kv_caches, intermediate_tensors)
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1719, in execute_model
[rank0]:     hidden_or_intermediate_states = model_executable(
[rank0]:                                     ^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 486, in forward
[rank0]:     hidden_states = self.model(input_ids, positions, kv_caches,
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/compilation/decorators.py", line 172, in __call__
[rank0]:     return self.forward(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 340, in forward
[rank0]:     hidden_states = self.get_input_embeddings(input_ids)
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 325, in get_input_embeddings
[rank0]:     return self.embed_tokens(input_ids)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/vllm/model_executor/layers/vocab_parallel_embedding.py", line 406, in forward
[rank0]:     masked_input, input_mask = get_masked_input_and_mask(
[rank0]:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1269, in __call__
[rank0]:     return self._torchdynamo_orig_callable(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1064, in __call__
[rank0]:     result = self._inner_convert(
[rank0]:              ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 526, in __call__
[rank0]:     return _compile(
[rank0]:            ^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 924, in _compile
[rank0]:     guarded_code = compile_inner(code, one_graph, hooks, transform)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 666, in compile_inner
[rank0]:     return _compile_inner(code, one_graph, hooks, transform)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_utils_internal.py", line 87, in wrapper_function
[rank0]:     return function(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 699, in _compile_inner
[rank0]:     out_code = transform_code_object(code, transform)
[rank0]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
[rank0]:     transformations(instructions, code_options)
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 219, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 634, in transform
[rank0]:     tracer.run()
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2796, in run
[rank0]:     super().run()
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 983, in run
[rank0]:     while self.step():
[rank0]:           ^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 895, in step
[rank0]:     self.dispatch_table[inst.opcode](self, inst)
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2987, in RETURN_VALUE
[rank0]:     self._return(inst)
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2972, in _return
[rank0]:     self.output.compile_subgraph(
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1142, in compile_subgraph
[rank0]:     self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1369, in compile_and_call_fx_graph
[rank0]:     compiled_fn = self.call_user_compiler(gm)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1416, in call_user_compiler
[rank0]:     return self._call_user_compiler(gm)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1465, in _call_user_compiler
[rank0]:     raise BackendCompilerFailed(self.compiler_fn, e) from e
[rank0]: torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
[rank0]: RuntimeError: Failed to find C compiler. Please specify via CC environment variable.

[rank0]: Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


[rank0]: You can suppress this exception and fall back to eager by setting:
[rank0]:     import torch._dynamo
[rank0]:     torch._dynamo.config.suppress_errors = True

(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] Exception in worker VllmWorkerProcess while processing method determine_num_available_blocks.
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] Traceback (most recent call last):
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1446, in _call_user_compiler
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     compiled_fn = compiler_fn(gm, self.example_inputs())
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/repro/after_dynamo.py", line 129, in __call__
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     compiled_gm = compiler_fn(gm, example_inputs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/__init__.py", line 2234, in __call__
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return compile_fx(model_, inputs_, config_patches=self.config)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1521, in compile_fx
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return aot_autograd(
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/backends/common.py", line 72, in __call__
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 1071, in aot_module_simplified
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     compiled_fn = dispatch_and_compile()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                   ^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 1056, in dispatch_and_compile
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     compiled_fn, _ = create_aot_dispatcher_function(
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 522, in create_aot_dispatcher_function
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return _create_aot_dispatcher_function(
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 759, in _create_aot_dispatcher_function
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     compiled_fn, fw_metadata = compiler_fn(
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                                ^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 179, in aot_dispatch_base
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     compiled_fw = compiler(fw_module, updated_flat_args)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1350, in fw_compiler_base
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return _fw_compiler_base(model, example_inputs, is_inference)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 1421, in _fw_compiler_base
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return inner_compile(
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 475, in compile_fx_inner
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return wrap_compiler_debug(_compile_fx_inner, compiler_name="inductor")(
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/repro/after_aot.py", line 85, in debug_wrapper
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     inner_compiled_fn = compiler_fn(gm, example_inputs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 661, in _compile_fx_inner
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     compiled_graph = FxGraphCache.load(
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                      ^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codecache.py", line 1334, in load
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     compiled_graph = compile_fx_fn(
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                      ^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 570, in codegen_and_compile
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     compiled_graph = fx_codegen_and_compile(gm, example_inputs, **fx_kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 878, in fx_codegen_and_compile
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     compiled_fn = graph.compile_to_fn()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                   ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1913, in compile_to_fn
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return self.compile_to_module().call
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1839, in compile_to_module
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return self._compile_to_module()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1845, in _compile_to_module
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     self.codegen_with_cpp_wrapper() if self.cpp_wrapper else self.codegen()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                                                              ^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/graph.py", line 1784, in codegen
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     self.scheduler.codegen()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/scheduler.py", line 3383, in codegen
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return self._codegen()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/scheduler.py", line 3461, in _codegen
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     self.get_backend(device).codegen_node(node)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codegen/cuda_combined_scheduling.py", line 80, in codegen_node
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return self._triton_scheduling.codegen_node(node)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codegen/simd.py", line 1155, in codegen_node
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return self.codegen_node_schedule(node_schedule, buf_accesses, numel, rnumel)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codegen/simd.py", line 1364, in codegen_node_schedule
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     src_code = kernel.codegen_kernel()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                ^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codegen/triton.py", line 2661, in codegen_kernel
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     **self.inductor_meta_common(),
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_inductor/codegen/triton.py", line 2532, in inductor_meta_common
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     "backend_hash": torch.utils._triton.triton_hash_with_backend(),
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_triton.py", line 53, in triton_hash_with_backend
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     backend = triton_backend()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]               ^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_triton.py", line 45, in triton_backend
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     target = driver.active.get_current_target()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/triton/runtime/driver.py", line 23, in __getattr__
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     self._initialize_obj()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/triton/runtime/driver.py", line 20, in _initialize_obj
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     self._obj = self._init_fn()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                 ^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/triton/runtime/driver.py", line 9, in _create_driver
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return actives[0]()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/triton/backends/nvidia/driver.py", line 371, in __init__
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     self.utils = CudaUtils()  # TODO: make static
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                  ^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/triton/backends/nvidia/driver.py", line 80, in __init__
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/triton/backends/nvidia/driver.py", line 57, in compile_module_from_src
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     so = _build(name, src_path, tmpdir, library_dirs(), include_dir, libraries)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/triton/runtime/build.py", line 32, in _build
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     raise RuntimeError("Failed to find C compiler. Please specify via CC environment variable.")
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] RuntimeError: Failed to find C compiler. Please specify via CC environment variable.
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] 
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] The above exception was the direct cause of the following exception:
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] 
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] Traceback (most recent call last):
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/vllm/executor/multiproc_worker_utils.py", line 236, in _run_worker_process
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     output = run_method(worker, method, args, kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/vllm/utils.py", line 2220, in run_method
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/vllm/worker/worker.py", line 229, in determine_num_available_blocks
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     self.model_runner.profile_run()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1235, in profile_run
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     self._dummy_run(max_num_batched_tokens, max_num_seqs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1346, in _dummy_run
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     self.execute_model(model_input, kv_caches, intermediate_tensors)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1719, in execute_model
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     hidden_or_intermediate_states = model_executable(
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                                     ^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 486, in forward
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     hidden_states = self.model(input_ids, positions, kv_caches,
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/vllm/compilation/decorators.py", line 172, in __call__
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return self.forward(*args, **kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 340, in forward
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     hidden_states = self.get_input_embeddings(input_ids)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 325, in get_input_embeddings
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return self.embed_tokens(input_ids)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/vllm/model_executor/layers/vocab_parallel_embedding.py", line 406, in forward
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     masked_input, input_mask = get_masked_input_and_mask(
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 465, in _fn
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return fn(*args, **kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1269, in __call__
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return self._torchdynamo_orig_callable(
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 1064, in __call__
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     result = self._inner_convert(
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]              ^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 526, in __call__
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return _compile(
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 924, in _compile
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     guarded_code = compile_inner(code, one_graph, hooks, transform)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 666, in compile_inner
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return _compile_inner(code, one_graph, hooks, transform)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_utils_internal.py", line 87, in wrapper_function
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return function(*args, **kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 699, in _compile_inner
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     out_code = transform_code_object(code, transform)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/bytecode_transformation.py", line 1322, in transform_code_object
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     transformations(instructions, code_options)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 219, in _fn
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return fn(*args, **kwargs)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/convert_frame.py", line 634, in transform
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     tracer.run()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2796, in run
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     super().run()
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 983, in run
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     while self.step():
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]           ^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 895, in step
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     self.dispatch_table[inst.opcode](self, inst)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2987, in RETURN_VALUE
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     self._return(inst)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/symbolic_convert.py", line 2972, in _return
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     self.output.compile_subgraph(
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1142, in compile_subgraph
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1369, in compile_and_call_fx_graph
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     compiled_fn = self.call_user_compiler(gm)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1416, in call_user_compiler
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     return self._call_user_compiler(gm)
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]   File "/opt/conda/lib/python3.11/site-packages/torch/_dynamo/output_graph.py", line 1465, in _call_user_compiler
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     raise BackendCompilerFailed(self.compiler_fn, e) from e
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] RuntimeError: Failed to find C compiler. Please specify via CC environment variable.
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] 
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] 
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] 
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] You can suppress this exception and fall back to eager by setting:
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     import torch._dynamo
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242]     torch._dynamo.config.suppress_errors = True
(VllmWorkerProcess pid=216) ERROR 03-01 07:34:52 multiproc_worker_utils.py:242] 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.11/site-packages/vllm/executor/multiproc_worker_utils.py", line 88, in run
    for result in iter(self.result_queue.get, _TERMINATE):
  File "/opt/conda/lib/python3.11/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BackendCompilerFailed.__init__() missing 1 required positional argument: 'inner_exception'
INFO 03-01 07:34:52 multiproc_worker_utils.py:128] Killing local vLLM worker processes
[rank0]:[W301 07:34:53.320660799 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
/opt/conda/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/opt/conda/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

</details>

### 🐛 Describe the bug

It work fine on conda envirentment ,but I build a docker image and run it, something was wrong. 
````
vllm:0.7.2
model: qwen2.5 72b  fp8,
gpu: H100x2  nvlink
ram: 256 gb
docker base: pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime

**Comment by iwaitu** [comment]
I have identified the cause of the issue. It is not due to vllm, but rather because, in a multi-GPU environment, factors such as power supply and temperature cause the clock frequencies of the two GPUs to differ during parallel computation, leading to errors. By using nvidia-smi -lgc 800,1600 to lock the minimum and maximum frequencies of both cards, the problem is resolved.
