### ISSUE TITLE
Does vllm support the Mac/Metal/MPS? 

### ISSUE THREAD

**Issue by Phil-U-U** [vllm-project/vllm#1441]
I ran into the error when pip install vllm in Mac: 
    RuntimeError: Cannot find CUDA_HOME. CUDA must be available to build the package.

**Comment by WoosukKwon** [comment]
Hi @Phil-U-U, vLLM does not support MPS backend at the moment as its main target scenario is to be deployed as a high-throughput server running on powerful accelerators like NVIDIA A100/H100.

**Comment by ibehnam** [comment]
> Hi @Phil-U-U, vLLM does not support MPS backend at the moment as its main target scenario is to be deployed as a high-throughput server running on powerful accelerators like NVIDIA A100/H100.

That's understandable. Although, with Mac Studio, many people and companies are starting to use the Mac as LLM servers. I get very good t/s on Mac Studio M2 Ultra using llama.cpp, but something like vLLM on the Mac would be a game changer. I hope the dev team considers this.

**Comment by willtejeda** [comment]
I'm with @ibehnam , Mac studio would be great for vllm

**Comment by oushu1zhangxiangxuan1** [comment]
+1

**Comment by joeywen** [comment]
+1

**Comment by vincent-pli** [comment]
+1

**Comment by jtoy** [comment]
+1

**Comment by csmac3144** [comment]
+1

**Comment by N8python** [comment]
+1

**Comment by evolu8** [comment]
Right, many developers are on Macs while testing out architectures. Yes we'll commonly deploy to linux, but if we can't quickly test and experiment locally on our daily use machines... we'll mostly like look elsewhere for an inference engine. Would be great if it could be supported, even if performance suffers on 'Apple Metal'.

**Comment by anisingh1** [comment]
+1

**Comment by antahiap** [comment]
Does this issue still exist?

**Comment by ibehnam** [comment]
@evolu8 Other solutions such as `llama.cpp`, LLM-MLC, Apple MLX, etc.?

**Comment by sameenislam** [comment]
Does anyone know about any alternatives to VLLM until this is supported?

**Comment by bluenevus** [comment]
same here please +1

**Comment by shushenghong** [comment]
+1
pip install vllm failed on my mac m1 pro
<img width="1163" alt="image" src="https://github.com/vllm-project/vllm/assets/3275714/ccec3c1f-9521-4958-bea8-bb969ca47f0f">

**Comment by jtoy** [comment]
+1On Feb 20, 2024, at 3:13 AM, Ather Shu ***@***.***> wrote:﻿
+1
pip install vllm failed on my mac m1 pro
image.png (view on web)

**Comment by bluenevus** [comment]
+1

**Comment by WH2zzZ** [comment]
+1

**Comment by emitrokhin** [comment]
+1

**Comment by csawtelle** [comment]
+1 I use a macbook and a mac studio. With the M3 architecture's unified memory these are very capable and cost effective systems for development and testing.

**Comment by bluenevus** [comment]
I'm willing to sponsor that effort because what we pay will be in savings in simply hardware on a mac.

**Comment by chen-bowen** [comment]
+10000

**Comment by NicolaDonelli** [comment]
+1 It would be very useful

**Comment by balasaajay** [comment]
+1 mac support will be very useful for experimentation

**Comment by AllanOricil** [comment]
I was about to try it with Snowflake arctic AI on my mac M2 Max hosted in AWS and I couldn't :/

**Comment by KE7** [comment]
More reason to support Mac. Best in class $/token: https://x.com/awnihannun/status/1786069640948719956

**Comment by Semihal** [comment]
> it is not possible for vllm to support mac when triton https://github.com/openai/triton does not support mac.

It already supports it if you install it from the source code.
```
(vllm) ~/Projects/triton/python/dist git:[main]
ll
-rw-r--r--  1 <user>:<group>    97M May 29 12:03 triton-3.0.0-cp311-cp311-macosx_14_0_arm64.whl
```

**Comment by MagMueller** [comment]
I am also on **darwin**, when I build from source 

```
git clone https://github.com/vllm-project/vllm.git
cd vllm
pip install -e .
```

I still get
```
 AssertionError: vLLM only supports Linux platform (including WSL).
```

**Comment by brando90** [comment]
can we support mac?

**Comment by JohnsonWoo** [comment]
can we support mac?

**Comment by password36** [comment]
+1

**Comment by wqlfff** [comment]
+1

**Comment by miketrimmel** [comment]
+1

**Comment by pzdkn** [comment]
+1

**Comment by brash6** [comment]
+1

**Comment by bjb19** [comment]
+1 While high throughput servers will be the main target on deployments the need for these in the debug experiment stage is highly needed

**Comment by tiboun** [comment]
+1

**Comment by pengjunlu** [comment]
+1

**Comment by MrMegaMango** [comment]
+1

**Comment by lucasdengcn** [comment]
+1

**Comment by SmallGaoX** [comment]
+1

**Comment by Ishankhan21** [comment]
Support for Mac M1, M2 ➕

**Comment by kongjiellx** [comment]
+1

**Comment by kaushikabhishek87** [comment]
+1

**Comment by AllanOricil** [comment]
Guys, please add a "like" in the main comment.

**Comment by kaushikabhishek87** [comment]
okay

**Comment by SynthpX** [comment]
+1

**Comment by sd3ntato** [comment]
+1

**Comment by wangyikewxgm** [comment]
+1

**Comment by atbe** [comment]
+1

**Comment by cderfvc** [comment]
> Support for Mac M1, M2 ➕

I wish install vllm in m1 mac pro 

how to install ?

**Comment by flockrushbot** [comment]
> > Support for Mac M1, M2 ➕
> 
> I wish install vllm in m1 mac pro
> 
> how to install ?

Not supported :(

**Comment by stephanj** [comment]
If on Apple silicon, then have a look at Exo Platform (OSS), which supports MLX (using python) and allows inference with LLM sharding using multiple Macs @ https://github.com/exoplatform

**Comment by clearsitedesigns** [comment]
Yeah, this is common, in my experience of running so many models locally, cuda and GPUs is way worse than a simple M1 pro.

**Comment by nmadhire** [comment]
+1
this is needed to test out basic models locally before deploying

**Comment by sokoloveai** [comment]
+1

**Comment by webboty** [comment]
+1

**Comment by dzlabs** [comment]
+1

**Comment by ExtraTon618** [comment]
+1

**Comment by willtejeda** [comment]
+1

**Comment by kevin1193** [comment]
+1 would love to have vllm support for mac

**Comment by achrafmam2** [comment]
+1

**Comment by x-0D** [comment]
+1

**Comment by willtejeda** [comment]
+1

**Comment by stormstone** [comment]
+10086

**Comment by zuozuo** [comment]
+10087

**Comment by white-spring** [comment]
+10088

**Comment by valenradovich** [comment]
+1111111

**Comment by youkaichao** [comment]
I think https://github.com/vllm-project/vllm/pull/9228 should solve it now. You can build and run using macos.

That's not for performance though, mainly for developing.

**Comment by mjtechguy** [comment]
+1

**Comment by wangxiyuan** [comment]
> I think #9228 should solve it now. You can build and run using macos.
> 
> That's not for performance though, mainly for developing.

Compile failed on mac m3. There are a few problem I found:
1. hard limit to linux sysytem: https://github.com/vllm-project/vllm/blob/main/setup.py#L36
2. hard limit to use linux command "/proc/cpuinfo" https://github.com/vllm-project/vllm/blob/main/cmake/cpu_extension.cmake#L29

Let's make vLLM avaliable on mac CPU first.

**Comment by YeonwooSung** [comment]
Even if the vllm's main target scenario is to be deployed as a high-throughput server, most developers might want to `test` locally before deploying it to the actual server.

**Comment by youkaichao** [comment]
https://github.com/vllm-project/vllm/pull/11696 should fix it now, please have a try!

**Comment by nikithakriz** [comment]
Hi, Any update on this? It would be good if its supported in Macs with silicon chipset

**Comment by youkaichao** [comment]
@nikithakriz please check https://docs.vllm.ai/en/latest/getting_started/installation/cpu/index.html , the latest code supports macos, but you need to build yourself.

**Comment by arjOman** [comment]
That's still a CPU-only support, but Metal GPU support is highly appreciated

**Comment by renaldrozario** [comment]
+1

**Comment by YeonwooSung** [comment]
+1

**Comment by ExtraTon618** [comment]
+200 ( again)

**Comment by masmau** [comment]
+1

**Comment by unizhu** [comment]
+1

**Comment by attentionmech** [comment]
+1

**Comment by cmuyaol** [comment]
+1

**Comment by disk0Dancer** [comment]
+1

**Comment by xsank** [comment]
pip install  on mac with the error:
```shell
 × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Looking in indexes: https://download.pytorch.org/whl/
      ERROR: Could not find a version that satisfies the requirement cmake>=3.26 (from versions: 3.25.0)
      ERROR: No matching distribution found for cmake>=3.26
      [end of output]

```

**Comment by xsank** [comment]
> pip install on mac with the error:
> 
>  × pip subprocess to install build dependencies did not run successfully.
>   │ exit code: 1
>   ╰─> [3 lines of output]
>       Looking in indexes: https://download.pytorch.org/whl/
>       ERROR: Could not find a version that satisfies the requirement cmake>=3.26 (from versions: 3.25.0)
>       ERROR: No matching distribution found for cmake>=3.26
>       [end of output]

after upgrade the system version, compile with the error:
```shell
CMake Error at cmake/cpu_extension.cmake:142 (message):
  vLLM CPU backend requires AVX512, AVX2, Power9+ ISA, S390X ISA or ARMv8
  support.
Call Stack (most recent call first):
  CMakeLists.txt:89 (include)
```

**Comment by xsank** [comment]
> > pip install on mac with the error:
> > × pip subprocess to install build dependencies did not run successfully.
> > │ exit code: 1
> > ╰─> [3 lines of output]
> > Looking in indexes: https://download.pytorch.org/whl/
> > ERROR: Could not find a version that satisfies the requirement cmake>=3.26 (from versions: 3.25.0)
> > ERROR: No matching distribution found for cmake>=3.26
> > [end of output]
> 
> after upgrade the system version, compile with the error, M1:
> 
> CMake Error at cmake/cpu_extension.cmake:142 (message):
>   vLLM CPU backend requires AVX512, AVX2, Power9+ ISA, S390X ISA or ARMv8
>   support.
> Call Stack (most recent call first):
>   CMakeLists.txt:89 (include)

Rosetta cause the problem, now it works on mac M1~

**Comment by lakshminarasimmanv** [comment]
What is the python version you are using? Because I got the same issue, saw that i was using python 3.13.x and i switched to 3.12.9 and it worked.

**Comment by JUSTINMKAUFMAN** [comment]
> +1

+1

**Comment by zengqingfu1442** [comment]
+1

**Comment by davzoku** [comment]
+1

**Comment by yihong0618** [comment]
> I'm confused. Why do these docs exist in the quickstart guide for installing vllm on Apple silicon: https://docs.vllm.ai/en/stable/getting_started/installation/cpu.html#build-wheel-from-source/apple
> 
> Following those steps, I'm getting the error from pip during the dependency install that the requirement triton==3.2.0; platform_machine != "ppc64le". Previous comments on this Issue indicate triton isn't supported for Mac

you can use latest code

**Comment by GDAmitha** [comment]
What is the latest code you're referring to? I believe I've cloned the latest update from vllm but I still get the same error.

ERROR: Could not find a version that satisfies the requirement triton==3.2.0; platform_machine != "ppc64le" (from vllm) (from versions: none)
ERROR: No matching distribution found for triton==3.2.0; platform_machine != "ppc64le"

**Comment by magic-YuanTian** [comment]
+1

**Comment by sooth** [comment]
VLLM not supporting MacOS is kind of a big deal. They're the cheapest, most widely available inferencing machines on the market right now. I appreciate what an annoyance it must be to support Apple's system, but it seems you're potentially missing out on half the market.

I am in the process of building AI systems for several companies right now, and VLLM not supporting running on any of the Macs is kind of taking it out of the conversation and we're currently using LM Studio as a temporary solution.

**Comment by otarkhan** [comment]
+1

**Comment by atbe** [comment]
+1

**Comment by Karthik777** [comment]
can't you use multipass to get an ubuntu server up and run vllm in that and expose the ports to the host machine?

**Comment by Force1ess** [comment]
+1

**Comment by adamhill** [comment]
+1

**Comment by ExtraTon618** [comment]
Check out my App Tess.AI for Mac

https://apps.apple.com/us/app/tess-ai/id6746819605?mt=12

**Comment by erhangundogan** [comment]
You can use MLX https://github.com/ml-explore/mlx-lm or https://github.com/mlc-ai/mlc-llm

**Comment by keyvez** [comment]
> +10000

This comment has 15 upvotes, so that makes it +10000 x 15 = +150000 which I believe makes it a P0 issue.

**Comment by manonthegithub** [comment]
+1

**Comment by keyvez** [comment]
+1

**Comment by chickenandpork** [comment]
If it helps, there's a (March, 2025) walk thru of vLLM on Mac: https://medium.com/@rohitkhatana/installing-vllm-on-macos-a-step-by-step-guide-bbbf673461af. (caveat: I'm not the author, and my skill isn't sufficient to judge the content)

**Comment by edhemphill** [comment]
support AMD also. Everyone is tired of paying the nvidia tax.

**Comment by x-0D** [comment]
> If it helps, there's a (March, 2025) walk thru of vLLM on Mac: https://medium.com/@rohitkhatana/installing-vllm-on-macos-a-step-by-step-guide-bbbf673461af. (caveat: I'm not the author, and my skill isn't sufficient to judge the content)

here are cite from the guide:
> When running vLLM on macOS, keep in mind:
> 
> Limited acceleration: Without CUDA, performance will be significantly slower than on NVIDIA GPUs

So, it's only uses CPU...

**Comment by BoltzmannEntropy** [comment]
Not all promising beginnings yield results ...  but I've developed a Qwen3 implementation using Metal Shaders over at https://github.com/BoltzmannEntropy/metalQwen3 . Obviously, it's no match for vLLM and stays pretty rudimentary, though the Metal Shaders do function as intended. Early on, I attempted to build MPS support into vLLM, but that turned out to be an incredibly challenging effort. Maybe it's worth revisiting at this point. Still work in progress.
