### ISSUE TITLE
[Bug]: `vllm serve Qwen/QwQ-32B-AWQ  --tensor-parallel-size 2` hangs with both RTX A6000 GPUs at max utilization

### ISSUE THREAD

**Issue by ubergarm** [vllm-project/vllm#14449]
## tl;dr;

Using `--tensor-parallel-size 2` hangs with both GPUs at 100% utilization and no debug logs explaining anything.

## Details

I know all the devs are hyper-focused on `R1` optimizations right now, which I appreciate. Just dropping this here for when there is time and for anyone else rushing to get [Qwen/QwQ-32B](https://huggingface.co/Qwen/QwQ-32B/discussions/11) running right now.

The AWQ quant runs fine on a single A6000 GPU like so:
```
# https://docs.astral.sh/uv/getting-started/installation/
curl -LsSf https://astral.sh/uv/install.sh | sh

# https://docs.vllm.ai/en/stable/getting_started/quickstart.html
mkdir vllm
cd vllm/
uv venv ./venv --python=3.12 --python-preference=only-managed
source  venv/bin/activate
uv pip install vllm
vllm --version
# INFO 03-07 11:13:15 __init__.py:207] Automatically detected platform cuda.
# 0.7.3

# 1x GPU works good!
OMP_NUM_THREADS=1 \
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
vllm serve \
    Qwen/QwQ-32B-AWQ \
    --download-dir /mnt/raid/models/ \
    --load-format auto \
    --dtype auto \
    --kv-cache-dtype auto \
    --max-model-len 32768 \
    --host 127.0.0.1 \
    --port 8080

# VRAM 35.46GiB / 47.99GiB
# INFO 03-07 11:41:10 metrics.py:455] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 33.3 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 1.0%, CPU KV cache usage: 0.0%.
```

However, as soon as I try to use both Tensor Parallel 2 for both GPU (no nvlink) running the same command as above with the single additional argument `--tensor-parallel-size 2` both GPUs go to 100% utilization and it hangs there. I have to `control+c` and then `ps aux | grep -i vllm` and manually kill two hung processes to get to to clean up.

![Image](https://github.com/user-attachments/assets/89e326cb-dc11-4368-86d6-7a7858158f83)

Thanks!

## Environment Info

<details>
<summary>`collect_env.py`</summary>

```bash
$ uv pip install pip
$ python ./venv/lib/python3.12/site-packages/torch/utils/collect_env.py | tee -a env.txt
$ uv pip uninstall pip
$ cat env.txt
```

```text
Collecting environment information...
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 24.04.1 LTS (x86_64)
GCC version: (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Clang version: Could not collect
CMake version: version 3.28.3
Libc version: glibc-2.39

Python version: 3.12.9 (main, Feb 12 2025, 14:50:50) [Clang 19.1.6 ] (64-bit runtime)
Python platform: Linux-6.13.0-061300-generic-x86_64-with-glibc2.39
Is CUDA available: True
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000

Nvidia driver version: 570.86.15
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        52 bits physical, 57 bits virtual
Byte Order:                           Little Endian
CPU(s):                               48
On-line CPU(s) list:                  0-47
Vendor ID:                            AuthenticAMD
Model name:                           AMD Ryzen Threadripper PRO 7965WX 24-Cores
CPU family:                           25
Model:                                24
Thread(s) per core:                   2
Core(s) per socket:                   24
Socket(s):                            1
Stepping:                             1
Frequency boost:                      enabled
CPU(s) scaling MHz:                   56%
CPU max MHz:                          5362.0000
CPU min MHz:                          545.0000
BogoMIPS:                             8399.77
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp ibrs_enhanced vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local user_shstk avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic vgif x2avic v_spec_ctrl vnmi avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid overflow_recov succor smca fsrm flush_l1d debug_swap
Virtualization:                       AMD-V
L1d cache:                            768 KiB (24 instances)
L1i cache:                            768 KiB (24 instances)
L2 cache:                             24 MiB (24 instances)
L3 cache:                             128 MiB (4 instances)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-47
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Mitigation; Safe RET
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.5.1
[pip3] torchaudio==2.5.1
[pip3] torchvision==0.20.1
[pip3] triton==3.1.0
[conda] Could not collect
```

</details>

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by mofanke** [comment]
I encountered the same issue: while the RTX 4090 performs well, the A6000 hangs

**Comment by ubergarm** [comment]
Thanks @mofanke for the confirmation.

I enabled a bunch of extra logging and tried to disable the custom all reduce but it still hangs. Looks like it is trying to do something maybe? Does it have to do some JIT model tiling to support tensor parallel? It is complaining about a missing lib `libnccl-net.so` 

```
INFO 03-10 11:17:53 pynccl.py:69] vLLM is using nccl==2.21.5                                                                        11:17:53 [34/1822]
wTR24:410550:410550 [0] NCCL INFO Bootstrap : Using enp2s0f0np0:10.200.0.67<0>
wTR24:410550:410550 [0] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
wTR24:410550:410550 [0] NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : whe
n loading libnccl-net.so
wTR24:410550:410550 [0] NCCL INFO NET/Plugin: Using internal network plugin.
wTR24:410550:410550 [0] NCCL INFO cudaDriverVersion 12080
NCCL version 2.21.5+cuda12.4
wTR24:410601:410601 [1] NCCL INFO cudaDriverVersion 12080
wTR24:410601:410601 [1] NCCL INFO Bootstrap : Using enp2s0f0np0:10.200.0.67<0>
wTR24:410601:410601 [1] NCCL INFO NET/Plugin: No plugin found (libnccl-net.so)
wTR24:410601:410601 [1] NCCL INFO NET/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : whe
n loading libnccl-net.so
wTR24:410601:410601 [1] NCCL INFO NET/Plugin: Using internal network plugin.
wTR24:410550:410550 [0] NCCL INFO NET/IB : No device found.
wTR24:410550:410550 [0] NCCL INFO NET/Socket : Using [0]enp2s0f0np0:10.10.0.67<0> [1]enp2s0f1np1:192.168.43.239<0>
wTR24:410550:410550 [0] NCCL INFO Using non-device net plugin version 0
wTR24:410550:410550 [0] NCCL INFO Using network Socket
wTR24:410601:410601 [1] NCCL INFO NET/IB : No device found.
wTR24:410601:410601 [1] NCCL INFO NET/Socket : Using [0]enp2s0f0np0:10.10.0.67<0> [1]enp2s0f1np1:192.168.43.239<0>
wTR24:410601:410601 [1] NCCL INFO Using non-device net plugin version 0
wTR24:410601:410601 [1] NCCL INFO Using network Socket
wTR24:410601:410601 [1] NCCL INFO ncclCommInitRank comm 0x44a7db00 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId e1000 commId 0x82ed0e4e7044de20 - Init ST
ART
wTR24:410550:410550 [0] NCCL INFO ncclCommInitRank comm 0x30a04ca0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 1000 commId 0x82ed0e4e7044de20 - Init STA
RT
wTR24:410550:410550 [0] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.
wTR24:410601:410601 [1] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.
wTR24:410550:410550 [0] NCCL INFO comm 0x30a04ca0 rank 0 nRanks 2 nNodes 1 localRanks 2 localRank 0 MNNVL 0
wTR24:410601:410601 [1] NCCL INFO comm 0x44a7db00 rank 1 nRanks 2 nNodes 1 localRanks 2 localRank 1 MNNVL 0
wTR24:410550:410550 [0] NCCL INFO Channel 00/04 :    0   1
wTR24:410550:410550 [0] NCCL INFO Channel 01/04 :    0   1
wTR24:410601:410601 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] 0/-1/-1->1->-1 [2] -1/-1/-1->1->0 [3] 0/-1/-1->1->-1
wTR24:410550:410550 [0] NCCL INFO Channel 02/04 :    0   1
wTR24:410601:410601 [1] NCCL INFO P2P Chunksize set to 131072
wTR24:410550:410550 [0] NCCL INFO Channel 03/04 :    0   1
wTR24:410550:410550 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1 [2] 1/-1/-1->0->-1 [3] -1/-1/-1->0->1
wTR24:410601:410601 [1] NCCL INFO P2P Chunksize set to 131072                                                                                 [0/1822]
wTR24:410550:410550 [0] NCCL INFO Channel 03/04 :    0   1
wTR24:410550:410550 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1 [2] 1/-1/-1->0->-1 [3] -1/-1/-1->0->1
wTR24:410550:410550 [0] NCCL INFO P2P Chunksize set to 131072
wTR24:410550:410550 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[1] via P2P/IPC
wTR24:410550:410550 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[1] via P2P/IPC
wTR24:410601:410601 [1] NCCL INFO Channel 00/0 : 1[1] -> 0[0] via P2P/IPC
wTR24:410550:410550 [0] NCCL INFO Channel 02/0 : 0[0] -> 1[1] via P2P/IPC
wTR24:410601:410601 [1] NCCL INFO Channel 01/0 : 1[1] -> 0[0] via P2P/IPC
wTR24:410550:410550 [0] NCCL INFO Channel 03/0 : 0[0] -> 1[1] via P2P/IPC
wTR24:410601:410601 [1] NCCL INFO Channel 02/0 : 1[1] -> 0[0] via P2P/IPC
wTR24:410601:410601 [1] NCCL INFO Channel 03/0 : 1[1] -> 0[0] via P2P/IPC
wTR24:410550:410550 [0] NCCL INFO Connected all rings
wTR24:410550:410550 [0] NCCL INFO Connected all trees
wTR24:410550:410550 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
wTR24:410550:410550 [0] NCCL INFO 4 coll channels, 4 collnet channels, 0 nvls channels, 4 p2p channels, 2 p2p channels per peer
wTR24:410601:410601 [1] NCCL INFO Connected all rings
wTR24:410601:410601 [1] NCCL INFO Connected all trees
wTR24:410601:410601 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
wTR24:410601:410601 [1] NCCL INFO 4 coll channels, 4 collnet channels, 0 nvls channels, 4 p2p channels, 2 p2p channels per peer
wTR24:410601:410601 [1] NCCL INFO TUNER/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : w
hen loading libnccl-tuner.so
wTR24:410601:410601 [1] NCCL INFO TUNER/Plugin: Using internal tuner plugin.
wTR24:410601:410601 [1] NCCL INFO ncclCommInitRank comm 0x44a7db00 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId e1000 commId 0x82ed0e4e7044de20 - Init CO
MPLETE
wTR24:410550:410550 [0] NCCL INFO TUNER/Plugin: Plugin load returned 2 : libnccl-net.so: cannot open shared object file: No such file or directory : w
hen loading libnccl-tuner.so
wTR24:410550:410550 [0] NCCL INFO TUNER/Plugin: Using internal tuner plugin.
wTR24:410550:410550 [0] NCCL INFO ncclCommInitRank comm 0x30a04ca0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 1000 commId 0x82ed0e4e7044de20 - Init COM
PLETE
DEBUG 03-10 11:17:56 client.py:192] Waiting for output from MQLLMEngine.
DEBUG 03-10 11:18:06 client.py:192] Waiting for output from MQLLMEngine.
DEBUG 03-10 11:18:16 client.py:192] Waiting for output from MQLLMEngine.
DEBUG 03-10 11:18:26 client.py:192] Waiting for output from MQLLMEngine.
DEBUG 03-10 11:18:36 client.py:192] Waiting for output from MQLLMEngine.
DEBUG 03-10 11:18:46 client.py:192] Waiting for output from MQLLMEngine.
DEBUG 03-10 11:18:57 client.py:192] Waiting for output from MQLLMEngine.
```

![Image](https://github.com/user-attachments/assets/80f09d1f-75b1-4ff0-bc44-4325e4289565)

**Comment by ubergarm** [comment]
I tried to install it like so, but it did not help:
```
sudo apt-get install libnccl2 libnccl-dev
```

I tried to install it with:
```
$ find . -name "libnccl*"
./venv/lib/python3.12/site-packages/nvidia/nccl/lib/libnccl.so.2

$ apt-file search libnccl-net.so
# nothing
```

I don't *think* this should matter as I'm running a single node with 2x GPUs locally?? Seems odd it would try to use RDMA networking to itself?? not sure...

**Comment by ubergarm** [comment]
See also #12664 https://github.com/vllm-project/vllm/issues/12664

I'll try to prepend:
```
NCCL_P2P_DISABLE=1
```

**Comment by ubergarm** [comment]
Hah, it finally spit out this ERROR:

```
VLLM_LOGGING_LEVEL=DEBUG \
CUDA_LAUNCH_BLOCKING=1 \
NCCL_DEBUG=TRACE \
NCCL_P2P_DISABLE=1 \
vllm serve \
    unsloth/QwQ-32B-unsloth-bnb-4bit \
    --download-dir /mnt/raid/models/ \
    --load-format bitsandbytes \
    --quantization bitsandbytes \
    --dtype auto \
    --kv-cache-dtype auto \
    --max-model-len 32768 \
    --tensor-parallel-size 2 \
    --pipeline-parallel-size 1 \
    --disable-custom-all-reduce \
    --enforce-eager \
    --enable-chunked-prefill \
    --host 127.0.0.1 \
    --port 8080

.
.
.

(VllmWorkerProcess pid=417579) ERROR 03-10 11:41:39 multiproc_worker_utils.py:242] ValueError: Prequant BitsAndBytes models with tensor parallelism is
 not supported. Please try with pipeline parallelism.
```

**Comment by ubergarm** [comment]
## tl;dr;

Apparently BitsAndBytes models are not supported with tensor parallelism... good to know!

**Comment by MseSpotlite** [comment]
my secret program windows “warp”  your welcome IG @MainStreamEnt.www.MstreamEnt.com  book your photoshoot music video, web skit with us On Mar 10, 2025, at 1:03 AM, mofanke ***@***.***> wrote:﻿
  I encountered the same issue: while the RTX 4090 performs well, the A6000 hangs—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



mofanke left a comment (vllm-project/vllm#14449)
I encountered the same issue: while the RTX 4090 performs well, the A6000 hangs

**Comment by ubergarm** [comment]
> I encountered the same issue: while the RTX 4090 performs well, the A6000 hangs

I ran `nvidia-smi --query-gpu=compute_cap --format=csv` which gives `8.6` so possibly tensor-parallel is only good for >= 9.0? 

Just a hunch, but didn't see a note on the documentation page.

**Comment by luciaganlulu** [comment]
> See also [#12664](https://github.com/vllm-project/vllm/issues/12664) [#12664](https://github.com/vllm-project/vllm/issues/12664)
> 
> I'll try to prepend:
> 
> ```
> NCCL_P2P_DISABLE=1
> ```

Thanks, this works for me. I encountered same hanging problem. I am running deepseek-r1-32B model on AMD MI210 GPU with multiple gpu cards using `rocm/vllm:rocm6.3.1_instinct_vllm0.7.3_20250311` docker images. It works fine on a single card but hanging with 1% gpu-utilization of each card if I set `tensor-parallel-size` as 2 or 4 or more. ` export NCCL_P2P_DISABLE=1` first in the container works.

**Comment by MattTheCuber** [comment]
This should be reopened

**Comment by sammysun0711** [comment]
> This should be reopened

Agree, thanks @ubergarm for details investigation and provide useful workaround, but still this issue need to root cause and fixed properly.
