### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'triton' when building docker image for Arm64

### ISSUE THREAD

**Issue by kunalchamoli** [vllm-project/vllm#14605]
### Your current environment

N/A

### 🐛 Describe the bug

While building the vLLM Docker image for ARM64 (Nvidia GH200 instance) as per the official [documentation](https://docs.vllm.ai/en/stable/deployment/docker.html#building-for-arm64-aarch64), I encountered the following issues:

1. PyTorch CUDA Version Mismatch
The [Dockerfile](https://github.com/vllm-project/vllm/blob/main/Dockerfile) installs different PyTorch nightly versions with inconsistent CUDA versions in different stages:

- **Base Image Installation**: Installs PyTorch nightly with CUDA 12.6

```
uv pip install --index-url https://download.pytorch.org/whl/nightly/cu126 "torch==2.7.0.dev20250121+cu126" "torchvision==0.22.0.dev20250121";
```

- **vLLM Installation Image**: Installs PyTorch nightly with CUDA 12.4
```
uv pip install --index-url https://download.pytorch.org/whl/nightly/cu124 "torch==2.6.0.dev20241210+cu124" "torchvision==0.22.0.dev20241215";
```

This mismatch caused build failures. Updating both installations to use CUDA 12.6 resolved the issue.

2. Missing **triton** Module During Container Execution 

After successfully building the image and running the container with the model **DeepSeek-R1-Distill-Llama-70B-bnb-4bit**, the following error occurred:
```
ModuleNotFoundError: No module named 'triton'
```

Complete logs for reference are
```
INFO 03-11 09:21:02 [__init__.py:256] Automatically detected platform cuda.
INFO 03-11 09:21:04 [api_server.py:912] vLLM API server version 0.7.4.dev365+g70b808fe.d20250311
INFO 03-11 09:21:04 [api_server.py:913] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, enable_ssl_refresh=False, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='/data/DeepSeek-R1-Distill-Llama-70B-bnb-4bit', task='auto', tokenizer=None, hf_config_path=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', max_model_len=8192, guided_decoding_backend='xgrammar', logits_processor_pattern=None, model_impl='auto', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=1, enable_expert_parallel=False, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=None, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_partial_prefills=1, max_long_partial_prefills=1, long_prefill_token_threshold=0, max_num_seqs=None, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, use_tqdm_on_load=True, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', scheduler_cls='vllm.core.scheduler.Scheduler', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', worker_extension_cls='', generation_config='auto', override_generation_config=None, enable_sleep_mode=False, calculate_kv_scales=False, additional_config=None, enable_reasoning=False, reasoning_parser=None, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False)
INFO 03-11 09:21:04 [api_server.py:209] Started engine process with PID 76
INFO 03-11 09:21:07 [__init__.py:256] Automatically detected platform cuda.
INFO 03-11 09:21:11 [config.py:576] This model supports multiple tasks: {'embed', 'reward', 'classify', 'score', 'generate'}. Defaulting to 'generate'.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 992, in <module>
    uvloop.run(run_server(args))
  File "/opt/venv/lib/python3.12/site-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/root/.local/share/uv/python/cpython-3.12.9-linux-aarch64-gnu/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/root/.local/share/uv/python/cpython-3.12.9-linux-aarch64-gnu/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/opt/venv/lib/python3.12/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 947, in run_server
    async with build_async_engine_client(args) as engine_client:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/uv/python/cpython-3.12.9-linux-aarch64-gnu/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 139, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/uv/python/cpython-3.12.9-linux-aarch64-gnu/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 220, in build_async_engine_client_from_engine_args
    engine_config = engine_args.create_engine_config()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/engine/arg_utils.py", line 1204, in create_engine_config
    model_config = self.create_model_config()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/engine/arg_utils.py", line 1130, in create_model_config
    return ModelConfig(
           ^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/config.py", line 418, in __init__
    self._verify_quantization()
  File "/opt/venv/lib/python3.12/site-packages/vllm/config.py", line 629, in _verify_quantization
    method = get_quantization_config(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/vllm/model_executor/layers/quantization/__init__.py", line 81, in get_quantization_config
    from vllm.model_executor.layers.quantization.quark.quark import QuarkConfig
  File "/opt/venv/lib/python3.12/site-packages/vllm/model_executor/layers/quantization/quark/quark.py", line 9, in <module>
    from vllm.model_executor.layers.fused_moe import FusedMoE
  File "/opt/venv/lib/python3.12/site-packages/vllm/model_executor/layers/fused_moe/__init__.py", line 6, in <module>
    from vllm.model_executor.layers.fused_moe.layer import (
  File "/opt/venv/lib/python3.12/site-packages/vllm/model_executor/layers/fused_moe/layer.py", line 25, in <module>
    from .fused_moe import fused_experts
  File "/opt/venv/lib/python3.12/site-packages/vllm/model_executor/layers/fused_moe/fused_moe.py", line 9, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by YangGuangzhaoJJJacky** [comment]
same issue! same Describing

**Comment by samos123** [comment]
Facing the same when trying to build gh200 image for vllm 0.8.1. Did any of you figure out a workaround?

**Comment by samos123** [comment]
I was able to get it to work by building triton 3.2.x from source.

Working image for GH200 for vllm 0.8.1:
```
substratusai/vllm-gh200:v0.8.1
```

Example docker run:
```
docker run --runtime nvidia --gpus all \
    -v ~/.cache/huggingface:/root/.cache/huggingface \
    -p 8000:8000 \
    --ipc=host -e VLLM_WORKER_MULTIPROC_METHOD=spawn \
    substratusai/vllm-gh200:v0.8.1 \
    --model Qwen/Qwen2.5-Coder-32B-Instruct
```

Code changes made on top of v0.8.1 are here: https://github.com/substratusai/vllm/tree/v0.8.1-gh200

I will try to make a PR if main still has this issue too.

**Comment by cg3dland** [comment]
@samos123 may I think you made some changes on the vllm code?

I pull the code with command 'git clone https://github.com/substratusai/vllm', and checkout the branch v0.8.1-gh200 with command 'git checkout v0.8.1-gh200', but when I try to install the vllm from source of v0.8.1-gh200 with command 'pip install -e .', I get following error:

Obtaining file:///nvme/vllm-gh200
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/nvme/miniforge3/envs/vllm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
        File "/nvme/miniforge3/envs/vllm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
        File "/nvme/miniforge3/envs/vllm/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 157, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-8zz_ry0q/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 483, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-8zz_ry0q/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-8zz_ry0q/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-8zz_ry0q/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 14, in <module>
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


But the torch 2.5.1 has been installed ! ! !

What wrong did I make?

Thanks,
George

**Comment by samos123** [comment]
Yeah I did make changes to torch related code since I ran this: `python3 use_existing_torch.py`.

Note my image seems to be having an issue with flash-infer not being installed. Still working on that.

**Comment by samos123** [comment]
I ended up changing the approach and got 0.8.2 docker image working instead: https://github.com/vllm-project/vllm/issues/10459#issuecomment-2759853357

**Comment by johnnynunez** [comment]
Solved:
```bash
pip3 install xgrammar vllm --index-url https://pypi.jetson-ai-lab.dev/sbsa/cu128/
```
