### ISSUE TITLE
[Bug]: deploy deepseek-r1-awq on 16 x 4090 48G, layer_kv_cache = torch.zeros(kv_cache_shape, [rank0]: RuntimeError: CUDA error: invalid argument

### ISSUE THREAD

**Issue by developer-hq** [vllm-project/vllm#15014]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
PyTorch version: 2.6.0+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.2
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.11.0-19-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.4.131
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 4090
GPU 1: NVIDIA GeForce RTX 4090
GPU 2: NVIDIA GeForce RTX 4090
GPU 3: NVIDIA GeForce RTX 4090
GPU 4: NVIDIA GeForce RTX 4090
GPU 5: NVIDIA GeForce RTX 4090
GPU 6: NVIDIA GeForce RTX 4090
GPU 7: NVIDIA GeForce RTX 4090

Nvidia driver version: 565.57.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        43 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               192
On-line CPU(s) list:                  0-191
Vendor ID:                            AuthenticAMD
BIOS Vendor ID:                       Advanced Micro Devices, Inc.
Model name:                           AMD EPYC 7K62 48-Core Processor
BIOS Model name:                      AMD EPYC 7K62 48-Core Processor                
CPU family:                           23
Model:                                49
Thread(s) per core:                   2
Core(s) per socket:                   48
Socket(s):                            2
Stepping:                             0
Frequency boost:                      enabled
CPU max MHz:                          2600.0000
CPU min MHz:                          1500.0000
BogoMIPS:                             5199.99
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
Virtualization:                       AMD-V
L1d cache:                            3 MiB (96 instances)
L1i cache:                            3 MiB (96 instances)
L2 cache:                             48 MiB (96 instances)
L3 cache:                             384 MiB (24 instances)
NUMA node(s):                         2
NUMA node0 CPU(s):                    0-47,96-143
NUMA node1 CPU(s):                    48-95,144-191
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec rstack overflow:   Mitigation; Safe RET
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cudnn-frontend==1.3.0
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-cusparselt-cu12==0.6.2
[pip3] nvidia-dali-cuda120==1.37.1
[pip3] nvidia-nccl-cu12==2.26.2
[pip3] nvidia-nvimgcodec-cu12==0.2.0.7
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] nvidia-pyindex==1.0.9
[pip3] onnx==1.16.0
[pip3] optree==0.14.1
[pip3] pynvml==11.4.1
[pip3] pytorch-quantization==2.1.2
[pip3] pytorch-triton==3.0.0+989adb9a2
[pip3] pyzmq==26.0.3
[pip3] torch==2.6.0
[pip3] torchaudio==2.6.0
[pip3] torchvision==0.21.0
[pip3] transformers==4.49.0
[pip3] triton==3.2.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.8.0rc3.dev5+g5eeabc2a
vLLM Build Flags:
CUDA Archs: 5.2 6.0 6.1 7.0 7.2 7.5 8.0 8.6 8.7 9.0+PTX; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NODE    NODE    NODE    SYS     SYS     SYS     SYS     0-47,96-143     0               N/A
GPU1    NODE     X      NODE    NODE    SYS     SYS     SYS     SYS     0-47,96-143     0               N/A
GPU2    NODE    NODE     X      NODE    SYS     SYS     SYS     SYS     0-47,96-143     0               N/A
GPU3    NODE    NODE    NODE     X      SYS     SYS     SYS     SYS     0-47,96-143     0               N/A
GPU4    SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    48-95,144-191   1               N/A
GPU5    SYS     SYS     SYS     SYS     NODE     X      NODE    NODE    48-95,144-191   1               N/A
GPU6    SYS     SYS     SYS     SYS     NODE    NODE     X      NODE    48-95,144-191   1               N/A
GPU7    SYS     SYS     SYS     SYS     NODE    NODE    NODE     X      48-95,144-191   1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NVIDIA_VISIBLE_DEVICES=all
CUBLAS_VERSION=12.4.5.8
NVIDIA_REQUIRE_CUDA=cuda>=9.0
CUDA_CACHE_DISABLE=1
TORCH_CUDA_ARCH_LIST=5.2 6.0 6.1 7.0 7.2 7.5 8.0 8.6 8.7 9.0+PTX
NCCL_VERSION=2.21.5
NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
NVIDIA_PRODUCT_NAME=PyTorch
CUDA_VERSION=12.4.1.003
PYTORCH_VERSION=2.4.0a0+07cecf4
PYTORCH_BUILD_NUMBER=0
CUDNN_VERSION=9.1.0.70
PYTORCH_HOME=/opt/pytorch/pytorch
LD_LIBRARY_PATH=/usr/local/lib/python3.10/dist-packages/cv2/../../lib64:/usr/local/lib/python3.10/dist-packages/torch/lib:/usr/local/lib/python3.10/dist-packages/torch_tensorrt/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
NVIDIA_BUILD_ID=91431255
CUDA_DRIVER_VERSION=550.54.15
PYTORCH_BUILD_VERSION=2.4.0a0+07cecf4
CUDA_HOME=/usr/local/cuda
CUDA_HOME=/usr/local/cuda
CUDA_MODULE_LOADING=LAZY
NVIDIA_REQUIRE_JETPACK_HOST_MOUNTS=
NVIDIA_PYTORCH_VERSION=24.05
TORCH_ALLOW_TF32_CUBLAS_OVERRIDE=1
NCCL_CUMEM_ENABLE=0
TORCHINDUCTOR_COMPILE_THREADS=1
```

</details>

### 🐛 Describe the bug

(RayWorkerWrapper pid=12430, ip=192.168.1.3) INFO 03-18 08:32:44 [worker.py:267] model weights take 22.34GiB; non_torch_memory takes 0.24GiB; PyTorch activation peak memory takes 0.37GiB; the rest of the memory reserved for KV Cache is 23.02GiB. [repeated 7x across cluster]
ERROR 03-18 08:32:47 [worker_base.py:620] Error executing method 'initialize_cache'. This might cause deadlock in distributed execution.
ERROR 03-18 08:32:47 [worker_base.py:620] Traceback (most recent call last):
ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 612, in execute_method
ERROR 03-18 08:32:47 [worker_base.py:620]     return run_method(self, method, args, kwargs)
ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 2216, in run_method
ERROR 03-18 08:32:47 [worker_base.py:620]     return func(*args, **kwargs)
ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 307, in initialize_cache
ERROR 03-18 08:32:47 [worker_base.py:620]     self._init_cache_engine()
ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 312, in _init_cache_engine
ERROR 03-18 08:32:47 [worker_base.py:620]     self.cache_engine = [
ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 313, in <listcomp>
ERROR 03-18 08:32:47 [worker_base.py:620]     CacheEngine(self.cache_config, self.model_config,
ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/cache_engine.py", line 66, in __init__
ERROR 03-18 08:32:47 [worker_base.py:620]     self.cpu_cache = self._allocate_kv_cache(self.num_cpu_blocks, "cpu")
ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/cache_engine.py", line 83, in _allocate_kv_cache
ERROR 03-18 08:32:47 [worker_base.py:620]     layer_kv_cache = torch.zeros(kv_cache_shape,
ERROR 03-18 08:32:47 [worker_base.py:620] RuntimeError: CUDA error: invalid argument
ERROR 03-18 08:32:47 [worker_base.py:620] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
ERROR 03-18 08:32:47 [worker_base.py:620] 
[rank0]: Traceback (most recent call last):
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 1054, in <module>
[rank0]:     uvloop.run(run_server(args))
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/uvloop/__init__.py", line 82, in run
[rank0]:     return loop.run_until_complete(wrapper())
[rank0]:   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/uvloop/__init__.py", line 61, in wrapper
[rank0]:     return await main
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 1007, in run_server
[rank0]:     async with build_async_engine_client(args) as engine_client:
[rank0]:   File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
[rank0]:     return await anext(self.gen)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 139, in build_async_engine_client
[rank0]:     async with build_async_engine_client_from_engine_args(
[rank0]:   File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
[rank0]:     return await anext(self.gen)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/entrypoints/openai/api_server.py", line 187, in build_async_engine_client_from_engine_args
[rank0]:     engine_client = AsyncLLMEngine.from_vllm_config(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 651, in from_vllm_config
[rank0]:     return cls(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 606, in __init__
[rank0]:     self.engine = self._engine_class(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/async_llm_engine.py", line 267, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 283, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/llm_engine.py", line 445, in _initialize_kv_caches
[rank0]:     self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 122, in initialize_cache
[rank0]:     self.collective_rpc("initialize_cache",
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 316, in collective_rpc
[rank0]:     return self._run_workers(method, *args, **(kwargs or {}))
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/ray_distributed_executor.py", line 514, in _run_workers
[rank0]:     self.driver_worker.execute_method(sent_method, *args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 621, in execute_method
[rank0]:     raise e
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 612, in execute_method
[rank0]:     return run_method(self, method, args, kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 2216, in run_method
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 307, in initialize_cache
[rank0]:     self._init_cache_engine()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 312, in _init_cache_engine
[rank0]:     self.cache_engine = [
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 313, in <listcomp>
[rank0]:     CacheEngine(self.cache_config, self.model_config,
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/cache_engine.py", line 66, in __init__
[rank0]:     self.cpu_cache = self._allocate_kv_cache(self.num_cpu_blocks, "cpu")
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/cache_engine.py", line 83, in _allocate_kv_cache
[rank0]:     layer_kv_cache = torch.zeros(kv_cache_shape,
[rank0]: RuntimeError: CUDA error: invalid argument
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620] Error executing method 'initialize_cache'. This might cause deadlock in distributed execution.
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620] Traceback (most recent call last):
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 612, in execute_method
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620]     return run_method(self, method, args, kwargs)
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 2216, in run_method
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620]     return func(*args, **kwargs)
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 307, in initialize_cache
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620]     self._init_cache_engine()
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 312, in _init_cache_engine
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620]     self.cache_engine = [
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 313, in <listcomp>
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620]     CacheEngine(self.cache_config, self.model_config,
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/cache_engine.py", line 66, in __init__
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620]     self.cpu_cache = self._allocate_kv_cache(self.num_cpu_blocks, "cpu")
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/cache_engine.py", line 83, in _allocate_kv_cache
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620]     layer_kv_cache = torch.zeros(kv_cache_shape,
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620] RuntimeError: CUDA error: invalid argument
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(RayWorkerWrapper pid=33749) ERROR 03-18 08:32:47 [worker_base.py:620] 
(RayWorkerWrapper pid=33753) INFO 03-18 08:32:46 [utils.py:104] Hidden layers were unevenly partitioned: 31,30 [repeated 14x across cluster]
(RayWorkerWrapper pid=33753) INFO 03-18 08:32:46 [utils.py:106] This can be manually overridden using the VLLM_PP_LAYER_PARTITION environment variable [repeated 14x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620] Error executing method 'initialize_cache'. This might cause deadlock in distributed execution. [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620] Traceback (most recent call last): [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker_base.py", line 612, in execute_method [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]     return run_method(self, method, args, kwargs) [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 2216, in run_method [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]     return func(*args, **kwargs) [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 307, in initialize_cache [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]     self._init_cache_engine() [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 312, in _init_cache_engine [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]     self.cache_engine = [ [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py", line 313, in <listcomp> [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]     CacheEngine(self.cache_config, self.model_config, [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/cache_engine.py", line 66, in __init__ [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]     self.cpu_cache = self._allocate_kv_cache(self.num_cpu_blocks, "cpu") [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]   File "/usr/local/lib/python3.10/dist-packages/vllm/worker/cache_engine.py", line 83, in _allocate_kv_cache [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]     layer_kv_cache = torch.zeros(kv_cache_shape, [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620] RuntimeError: CUDA error: invalid argument [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620] For debugging consider passing CUDA_LAUNCH_BLOCKING=1 [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. [repeated 4x across cluster]
(RayWorkerWrapper pid=33753) ERROR 03-18 08:32:47 [worker_base.py:620]  [repeated 4x across cluster]
INFO 03-18 08:32:48 [ray_distributed_executor.py:127] Shutting down Ray distributed executor. If you see error log from logging.cc regarding SIGTERM received, please ignore because this is the expected termination process in Ray.
INFO 03-18 08:32:48 [ray_distributed_executor.py:127] Shutting down Ray distributed executor. If you see error log from logging.cc regarding SIGTERM received, please ignore because this is the expected termination process in Ray.
[rank0]:[W318 08:32:48.660406600 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

run command
python -m vllm.entrypoints.openai.api_server \
    --max-model-len 32768 \
    --trust-remote-code \
    --tensor-parallel-size 8 \
    --pipeline-parallel-size 2 \
    --quantization moe_wna16 \
    --gpu-memory-utilization 0.97 \
    --calculate-kv-scales \
    --served-model-name deepseek-reasoner \
    --model /mnt
    --host 0.0.0.0 \
    --port 18001 \

I have also tried these args:
dtype=float16
pp=2,tp=8
tp=16

With command
VLLM_WORKER_MULTIPROC_METHOD=spawn vllm serve /mnt \
    --host 0.0.0.0 \
    --port 19001 \
    --max-model-len 16384 \
    --max-num-batched-tokens 16384 \
    --trust-remote-code \
    --tensor-parallel-size 16 \
    --gpu-memory-utilization 0.97 \
    --dtype float16 \
    --enable-reasoning \
    --reasoning-parser deepseek_r1 \
    --served-model-name deepseek-reasoner  \
    --enforce-eager

can serve the model, but collapse when curl /v1/chat/completions api

There is also a missing config:
WARNING 03-18 08:31:51 [fused_moe.py:876] Using default MoE config. Performance might be sub-optimal! Config file not found at /usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=256,N=256,device_name=NVIDIA_GeForce_RTX_4090,dtype=int4_w4a16.json

For environment, official docker with vllm=0.7.3 also cannot work

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by CharlesRiggins** [comment]
Same here. Did you solve it?

**Comment by developer-hq** [comment]
I tried with docker and ray cluster. This way sometimes works for me. I also failed with sglang. If you can solve it with other ways, it will be very thankful to let me know

发自我的iPhone


------------------ Original ------------------
From: Charles Riggins ***@***.***&gt;
Date: Fri,Apr 25,2025 0:18 AM
To: vllm-project/vllm ***@***.***&gt;
Cc: developer-hq ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [vllm-project/vllm] [Bug]: deploy deepseek-r1-awq on 16 x 409048G, layer_kv_cache = torch.zeros(kv_cache_shape, [rank0]: RuntimeError: CUDAerror: invalid argument (Issue #15014)



 CharlesRiggins left a comment (vllm-project/vllm#15014)
 
Same here. Did you solve it?
