### ISSUE TITLE
[Usage]:

### ISSUE THREAD

**Issue by rainays** [vllm-project/vllm#15469]
### Your current environment

**env**
torch  2.5.1+cu118
vllm 0.7.2
cuda 12

**termial**
CUDA_VISIBLE_DEVICES=0,1 VLLM_USE_V1=1 VLLM_WORKER_MULTIPROC_METHOD=spawn vllm serve /home/work/anyujie/Qwen/Qwen2.5-VL-3B-Instruct --gpu-memory-utilization 0.9 --swap-space 16 --max-model-len 4096 --tensor-parallel-size 2 --port 8091 --disable-custom-all-reduce

**error**
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374] WorkerProc hit an exception: %s
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374] Traceback (most recent call last):
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/executor/multiproc_executor.py", line 370, in worker_busy_loop
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     output = func(*args, **kwargs)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/worker/gpu_worker.py", line 223, in compile_or_warm_up_model
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     self.model_runner.capture_model()
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/worker/gpu_model_runner.py", line 1036, in capture_model
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     self._dummy_run(num_tokens)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return func(*args, **kwargs)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/worker/gpu_model_runner.py", line 894, in _dummy_run
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     hidden_states = model(
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return self._call_impl(*args, **kwargs)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return forward_call(*args, **kwargs)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 1095, in forward
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     hidden_states = self.language_model.model(
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/compilation/decorators.py", line 245, in __call__
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     model_output = self.forward(*args, **kwargs)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/model_executor/models/qwen2.py", line 327, in forward
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     def forward(
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return self._call_impl(*args, **kwargs)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return forward_call(*args, **kwargs)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 632, in _fn
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return fn(*args, **kwargs)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/fx/graph_module.py", line 784, in call_wrapped
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return self._wrapped_call(self, *args, **kwargs)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/fx/graph_module.py", line 361, in __call__
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     raise e
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/fx/graph_module.py", line 348, in __call__
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return self._call_impl(*args, **kwargs)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return forward_call(*args, **kwargs)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "<eval_with_key>.74", line 267, in forward
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     submod_2 = self.submod_2(getitem_3, s0, l_self_modules_layers_modules_0_modules_self_attn_modules_o_proj_parameters_weight_, l_inputs_embeds_, l_self_modules_layers_modules_0_modules_post_attention_layernorm_parameters_weight_, l_self_modules_layers_modules_0_modules_mlp_modules_gate_up_proj_parameters_weight_, l_self_modules_layers_modules_0_modules_mlp_modules_down_proj_parameters_weight_, l_self_modules_layers_modules_1_modules_input_layernorm_parameters_weight_, l_self_modules_layers_modules_1_modules_self_attn_modules_qkv_proj_parameters_weight_, l_self_modules_layers_modules_1_modules_self_attn_modules_qkv_proj_parameters_bias_, l_self_modules_layers_modules_0_modules_self_attn_modules_rotary_emb_buffers_cos_sin_cache_, l_positions_, s2);  getitem_3 = l_self_modules_layers_modules_0_modules_self_attn_modules_o_proj_parameters_weight_ = l_inputs_embeds_ = l_self_modules_layers_modules_0_modules_post_attention_layernorm_parameters_weight_ = l_self_modules_layers_modules_0_modules_mlp_modules_gate_up_proj_parameters_weight_ = l_self_modules_layers_modules_0_modules_mlp_modules_down_proj_parameters_weight_ = l_self_modules_layers_modules_1_modules_input_layernorm_parameters_weight_ = l_self_modules_layers_modules_1_modules_self_attn_modules_qkv_proj_parameters_weight_ = l_self_modules_layers_modules_1_modules_self_attn_modules_qkv_proj_parameters_bias_ = None
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/compilation/backends.py", line 842, in __call__
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     output = entry.runnable(*args)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/compilation/backends.py", line 239, in compiled_graph
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     graph_output = inductor_compiled_graph(list_args)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 1478, in __call__
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return self.current_callable(inputs)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/.cache/vllm/torch_compile_cache/41bb4c971c/rank_1/inductor_cache/jv/cjvnew4xe4km4tkfgn5lbxq3essp3z2p2h2aepjsb27xbv4qr7om.py", line 488, in call
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     buf1 = torch.ops.vllm.all_reduce.default(buf0, 'tp:0')
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/_ops.py", line 716, in __call__
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return self._op(*args, **kwargs)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/distributed/parallel_state.py", line 111, in all_reduce
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return group._all_reduce_out_place(tensor)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/distributed/parallel_state.py", line 370, in _all_reduce_out_place
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     out = pynccl_comm.all_reduce(input_)
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/distributed/device_communicators/pynccl.py", line 126, in all_reduce
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     self.nccl.ncclAllReduce(buffer_type(in_tensor.data_ptr()),
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 290, in ncclAllReduce
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     self.NCCL_CHECK(self._funcs["ncclAllReduce"](sendbuff, recvbuff, count,
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 256, in NCCL_CHECK
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374]     raise RuntimeError(f"NCCL error: {error_str}")
(VllmWorker rank=1 pid=12231) ERROR 03-25 21:13:53 multiproc_executor.py:374] RuntimeError: NCCL error: invalid usage (run with NCCL_DEBUG=WARN for details)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374] WorkerProc hit an exception: %s
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374] Traceback (most recent call last):
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/executor/multiproc_executor.py", line 370, in worker_busy_loop
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     output = func(*args, **kwargs)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/worker/gpu_worker.py", line 223, in compile_or_warm_up_model
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     self.model_runner.capture_model()
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/worker/gpu_model_runner.py", line 1036, in capture_model
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     self._dummy_run(num_tokens)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return func(*args, **kwargs)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/worker/gpu_model_runner.py", line 894, in _dummy_run
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     hidden_states = model(
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return self._call_impl(*args, **kwargs)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return forward_call(*args, **kwargs)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 1095, in forward
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     hidden_states = self.language_model.model(
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/compilation/decorators.py", line 245, in __call__
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     model_output = self.forward(*args, **kwargs)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/model_executor/models/qwen2.py", line 327, in forward
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     def forward(
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return self._call_impl(*args, **kwargs)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return forward_call(*args, **kwargs)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 632, in _fn
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return fn(*args, **kwargs)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/fx/graph_module.py", line 784, in call_wrapped
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return self._wrapped_call(self, *args, **kwargs)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/fx/graph_module.py", line 361, in __call__
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     raise e
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/fx/graph_module.py", line 348, in __call__
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return self._call_impl(*args, **kwargs)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return forward_call(*args, **kwargs)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "<eval_with_key>.74", line 267, in forward
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     submod_2 = self.submod_2(getitem_3, s0, l_self_modules_layers_modules_0_modules_self_attn_modules_o_proj_parameters_weight_, l_inputs_embeds_, l_self_modules_layers_modules_0_modules_post_attention_layernorm_parameters_weight_, l_self_modules_layers_modules_0_modules_mlp_modules_gate_up_proj_parameters_weight_, l_self_modules_layers_modules_0_modules_mlp_modules_down_proj_parameters_weight_, l_self_modules_layers_modules_1_modules_input_layernorm_parameters_weight_, l_self_modules_layers_modules_1_modules_self_attn_modules_qkv_proj_parameters_weight_, l_self_modules_layers_modules_1_modules_self_attn_modules_qkv_proj_parameters_bias_, l_self_modules_layers_modules_0_modules_self_attn_modules_rotary_emb_buffers_cos_sin_cache_, l_positions_, s2);  getitem_3 = l_self_modules_layers_modules_0_modules_self_attn_modules_o_proj_parameters_weight_ = l_inputs_embeds_ = l_self_modules_layers_modules_0_modules_post_attention_layernorm_parameters_weight_ = l_self_modules_layers_modules_0_modules_mlp_modules_gate_up_proj_parameters_weight_ = l_self_modules_layers_modules_0_modules_mlp_modules_down_proj_parameters_weight_ = l_self_modules_layers_modules_1_modules_input_layernorm_parameters_weight_ = l_self_modules_layers_modules_1_modules_self_attn_modules_qkv_proj_parameters_weight_ = l_self_modules_layers_modules_1_modules_self_attn_modules_qkv_proj_parameters_bias_ = None
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/compilation/backends.py", line 842, in __call__
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     output = entry.runnable(*args)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/compilation/backends.py", line 239, in compiled_graph
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     graph_output = inductor_compiled_graph(list_args)
ERROR 03-25 21:13:53 core.py:210] EngineCore hit an exception: Traceback (most recent call last):
ERROR 03-25 21:13:53 core.py:210]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/engine/core.py", line 202, in run_engine_core
ERROR 03-25 21:13:53 core.py:210]     engine_core = EngineCoreProc(*args, **kwargs)
ERROR 03-25 21:13:53 core.py:210]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/engine/core.py", line 156, in __init__
ERROR 03-25 21:13:53 core.py:210]     super().__init__(vllm_config, executor_class)
ERROR 03-25 21:13:53 core.py:210]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/engine/core.py", line 54, in __init__
ERROR 03-25 21:13:53 core.py:210]     num_gpu_blocks, num_cpu_blocks = self._initialize_kv_caches(
ERROR 03-25 21:13:53 core.py:210]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/engine/core.py", line 88, in _initialize_kv_caches
ERROR 03-25 21:13:53 core.py:210]     self.model_executor.initialize(kv_cache_config)
ERROR 03-25 21:13:53 core.py:210]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/executor/abstract.py", line 58, in initialize
ERROR 03-25 21:13:53 core.py:210]     self.collective_rpc("compile_or_warm_up_model")
ERROR 03-25 21:13:53 core.py:210]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/executor/multiproc_executor.py", line 133, in collective_rpc
ERROR 03-25 21:13:53 core.py:210]     raise e
ERROR 03-25 21:13:53 core.py:210]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/v1/executor/multiproc_executor.py", line 122, in collective_rpc
ERROR 03-25 21:13:53 core.py:210]     raise result
ERROR 03-25 21:13:53 core.py:210] RuntimeError: NCCL error: invalid usage (run with NCCL_DEBUG=WARN for details)
ERROR 03-25 21:13:53 core.py:210]
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/_inductor/codecache.py", line 1478, in __call__
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return self.current_callable(inputs)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/.cache/vllm/torch_compile_cache/41bb4c971c/rank_0/inductor_cache/5z/c5zvmuadomaodz6l6kchh3vaaemvj67qljc2mko5nflojgly6442.py", line 488, in call
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     buf1 = torch.ops.vllm.all_reduce.default(buf0, 'tp:0')
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/torch/_ops.py", line 716, in __call__
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return self._op(*args, **kwargs)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/distributed/parallel_state.py", line 111, in all_reduce
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     return group._all_reduce_out_place(tensor)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/distributed/parallel_state.py", line 370, in _all_reduce_out_place
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     out = pynccl_comm.all_reduce(input_)
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/distributed/device_communicators/pynccl.py", line 126, in all_reduce
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     self.nccl.ncclAllReduce(buffer_type(in_tensor.data_ptr()),
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 290, in ncclAllReduce
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     self.NCCL_CHECK(self._funcs["ncclAllReduce"](sendbuff, recvbuff, count,
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]   File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 256, in NCCL_CHECK
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374]     raise RuntimeError(f"NCCL error: {error_str}")
(VllmWorker rank=0 pid=12191) ERROR 03-25 21:13:53 multiproc_executor.py:374] RuntimeError: NCCL error: invalid usage (run with NCCL_DEBUG=WARN for details)
CRITICAL 03-25 21:13:53 core_client.py:158] Got fatal signal from worker processes, shutting down. See stack trace above for root cause issue.
deploy.sh: line 17: 11440 Killed                  CUDA_VISIBLE_DEVICES=0,1 VLLM_USE_V1=1 VLLM_WORKER_MULTIPROC_METHOD=spawn vllm serve /home/work/anyujie/Qwen/Qwen2.5-VL-3B-Instruct --gpu-memory-utilization 0.9 --swap-space 16 --max-model-len 4096 --tensor-parallel-size 2 --port 8091 --disable-custom-all-reduce

### How would you like to use vllm

I want to run inference of a [specific model](put link here). I don't know how to integrate it with vllm.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
Can you run `collect_env.py` and show the output?

**Comment by rainays** [comment]
> Can you try running `nvidia-smi topo -m` to show the GPU topology?

	GPU0	GPU1	NIC0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	SYS	SYS	0-63,128-191	0		N/A
GPU1	SYS	 X 	SYS	64-127,192-255	1		N/A
NIC0	SYS	SYS	 X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_bond_0

![Image](https://github.com/user-attachments/assets/a99035d7-a759-4760-9826-2a59f345a823)

**Comment by rainays** [comment]
> Hmm [@youkaichao](https://github.com/youkaichao) any idea?

sorry，i met new problem
i changed my cuda nvvc--version from 12.0 to 11.8，so it can successfully run，but when i use openai with logprob, it will throw new err
**this is my request script**
response = client.chat.completions.create(
                model=model_name,
                messages=[{
                    'role':
                    'user',
                    'content': [{
                        'type': 'text',
                        'text': query,
                    }, {
                        'type': 'image_url',
                        'image_url': {
                            'url':
                            encoded_image_str,
                        },
                    }],
                }],
                temperature=0.7,
                top_p=1, 
                timeout=200,
                max_tokens=3072,
                top_logprobs=5,
                logprobs=True
                # stream=True
                )
**error**
Traceback (most recent call last):
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/fastapi/routing.py", line 297, in app
    raw_response = await run_endpoint_function(
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/fastapi/routing.py", line 210, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/entrypoints/utils.py", line 56, in wrapper
    return handler_task.result()
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/entrypoints/openai/api_server.py", line 392, in create_chat_completion
    generator = await handler.create_chat_completion(request, raw_request)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/entrypoints/openai/serving_chat.py", line 263, in create_chat_completion
    return await self.chat_completion_full_generator(
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/entrypoints/openai/serving_chat.py", line 700, in chat_completion_full_generator
    assert out_logprobs is not None, "Did not output logprobs"

**if i logprobs=false it will work , but i very need this parameter**

**Comment by DarkLight1337** [comment]
Try running it on V0 Engine using `VLLM_USE_V1=0`. I think logprobs aren't supported on V1 in v0.7.2.

**Comment by rainays** [comment]
> VLLM_USE_V1=0

when i use VLLM_USE_V1=0
**it occured:** 😭
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/work/anyujie/py39/lib/python3.9/multiprocessing/process.py", line 318, in _bootstrap
    util._exit_function()
  File "/home/work/anyujie/py39/lib/python3.9/multiprocessing/util.py", line 357, in _exit_function
    p.join()
  File "/home/work/anyujie/py39/lib/python3.9/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/work/anyujie/py39/lib/python3.9/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/work/anyujie/py39/lib/python3.9/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/home/work/anyujie/py39/lib/python3.9/site-packages/vllm/engine/multiprocessing/engine.py", line 374, in signal_handler
    raise KeyboardInterrupt("MQLLMEngine terminated")
KeyboardInterrupt: MQLLMEngine terminated

**Comment by DarkLight1337** [comment]
Can you pass `--disable-frontend-multiprocessing` to get a better error message?

**Comment by rainays** [comment]
> Can you pass `--disable-frontend-multiprocessing` to get a better error message?

oh just moment，i  change gpu-memory-utilization from 0.9 to 0.85, it works! maybe two a10  Memory limit
thanks very much!
Your timely reply solved many of my problems! I expressed my sincere thanks again. I hope vllm team can get better and better😊

**Comment by rainays** [comment]
> Can you pass `--disable-frontend-multiprocessing` to get a better error message?

oh just moment，i change gpu-memory-utilization from 0.9 to 0.85, it works! maybe two a10 Memory limit
thanks very much!
but 
![Image](https://github.com/user-attachments/assets/9dd55cc2-34ce-4bef-8958-3498d6302ecc)
log_prob will be 0 sometimes 
we make it extract signboard name

**Comment by DarkLight1337** [comment]
I think you may need to set `top_p` to increase the number of candidates.

**Comment by rainays** [comment]
> I think you may need to decrease `top_p` to increase the number of candidates.

{
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.05,
  "temperature": 0.1,
  "top_k": 1,
  "top_p": 0.001,
  "transformers_version": "4.49.0.dev0"
}
our top_p was 0.001

**Comment by DarkLight1337** [comment]
Oops I meant `min_p`. IN that case it shouldn't be a problem.

**Comment by DarkLight1337** [comment]
@njhill any idea why this occurs?

**Comment by rainays** [comment]
> min_p

i used use  vllm0.7.3 and cuda nvcc version=12.0 and VLLM_USE_V1=1 to request 
the sam request
 vllm0.7.3 and cuda nvcc version=12.0 and VLLM_USE_V1=1
Choice(finish_reason='stop', index=0, logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='éĩĳ', bytes=[195, 169, 196, 169, 196, 179], logprob=-0.004274992737919092, top_logprobs=[TopLogprob(token='éĩĳ', bytes=[195, 169, 196, 169, 196, 179], logprob=-0.004274992737919092)]), ChatCompletionTokenLogprob(token='åĪ©', bytes=[195, 165, 196, 170, 194, 169], logprob=-4.3987260141875595e-05, top_logprobs=[TopLogprob(token='åĪ©', bytes=[195, 165, 196, 170, 194, 169], logprob=-4.3987260141875595e-05)]), ChatCompletionTokenLogprob(token='èĩª', bytes=[195, 168, 196, 169, 194, 170], logprob=-0.0018780466634780169, top_logprobs=[TopLogprob(token='èĩª', bytes=[195, 168, 196, 169, 194, 170], logprob=-0.0018780466634780169)]), ChatCompletionTokenLogprob(token='éĢī', bytes=[195, 169, 196, 162, 196, 171], logprob=-3.576278118089249e-07, top_logprobs=[TopLogprob(token='éĢī', bytes=[195, 169, 196, 162, 196, 171], logprob=-3.576278118089249e-07)]), ChatCompletionTokenLogprob(token='åºĹ', bytes=[195, 165, 194, 186, 196, 185], logprob=-2.992108420585282e-05, top_logprobs=[TopLogprob(token='åºĹ', bytes=[195, 165, 194, 186, 196, 185], logprob=-2.992108420585282e-05)]), ChatCompletionTokenLogprob(token='<|im_end|>', bytes=[60, 124, 105, 109, 95, 101, 110, 100, 124, 62], logprob=-0.0008253029081970453, top_logprobs=[TopLogprob(token='<|im_end|>', bytes=[60, 124, 105, 109, 95, 101, 110, 100, 124, 62], logprob=-0.0008253029081970453)])], refusal=None), message=ChatCompletionMessage(content='金利自选店', refusal=None, role='assistant', audio=None, function_call=None, tool_calls=[], reasoning_content=None), stop_reason=None)

and now vllm0.7.32and cuda nvcc version=11.8 and VLLM_USE_V1=0
Choice(finish_reason='stop', index=0, logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='金', bytes=[233, 135, 145], logprob=0.0, top_logprobs=[TopLogprob(token='金', bytes=[233, 135, 145], logprob=0.0)]), ChatCompletionTokenLogprob(token='利', bytes=[229, 136, 169], logprob=0.0, top_logprobs=[TopLogprob(token='利', bytes=[229, 136, 169], logprob=0.0)]), ChatCompletionTokenLogprob(token='自', bytes=[232, 135, 170], logprob=0.0, top_logprobs=[TopLogprob(token='自', bytes=[232, 135, 170], logprob=0.0)]), ChatCompletionTokenLogprob(token='选', bytes=[233, 128, 137], logprob=0.0, top_logprobs=[TopLogprob(token='选', bytes=[233, 128, 137], logprob=0.0)]), ChatCompletionTokenLogprob(token='店', bytes=[229, 186, 151], logprob=0.0, top_logprobs=[TopLogprob(token='店', bytes=[229, 186, 151], logprob=0.0)]), ChatCompletionTokenLogprob(token='', bytes=[], logprob=0.0, top_logprobs=[TopLogprob(token='', bytes=[], logprob=0.0)])], refusal=None), message=ChatCompletionMessage(content='金利自选店', refusal=None, role='assistant', audio=None, function_call=None, tool_calls=[], reasoning_content=None), stop_reason=None)
it changed to 0.0

**Comment by rainays** [comment]
> > min_p
> 
> i used use vllm0.7.3 and cuda nvcc version=12.0 and VLLM_USE_V1=1 to request the sam request **vllm0.7.3 and cuda nvcc version=12.0 and VLLM_USE_V1=1** Choice(finish_reason='stop', index=0, logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='éĩĳ', bytes=[195, 169, 196, 169, 196, 179], logprob=-0.004274992737919092, top_logprobs=[TopLogprob(token='éĩĳ', bytes=[195, 169, 196, 169, 196, 179], logprob=-0.004274992737919092)]), ChatCompletionTokenLogprob(token='åĪ©', bytes=[195, 165, 196, 170, 194, 169], logprob=-4.3987260141875595e-05, top_logprobs=[TopLogprob(token='åĪ©', bytes=[195, 165, 196, 170, 194, 169], logprob=-4.3987260141875595e-05)]), ChatCompletionTokenLogprob(token='èĩª', bytes=[195, 168, 196, 169, 194, 170], logprob=-0.0018780466634780169, top_logprobs=[TopLogprob(token='èĩª', bytes=[195, 168, 196, 169, 194, 170], logprob=-0.0018780466634780169)]), ChatCompletionTokenLogprob(token='éĢī', bytes=[195, 169, 196, 162, 196, 171], logprob=-3.576278118089249e-07, top_logprobs=[TopLogprob(token='éĢī', bytes=[195, 169, 196, 162, 196, 171], logprob=-3.576278118089249e-07)]), ChatCompletionTokenLogprob(token='åºĹ', bytes=[195, 165, 194, 186, 196, 185], logprob=-2.992108420585282e-05, top_logprobs=[TopLogprob(token='åºĹ', bytes=[195, 165, 194, 186, 196, 185], logprob=-2.992108420585282e-05)]), ChatCompletionTokenLogprob(token='<|im_end|>', bytes=[60, 124, 105, 109, 95, 101, 110, 100, 124, 62], logprob=-0.0008253029081970453, top_logprobs=[TopLogprob(token='<|im_end|>', bytes=[60, 124, 105, 109, 95, 101, 110, 100, 124, 62], logprob=-0.0008253029081970453)])], refusal=None), message=ChatCompletionMessage(content='金利自选店', refusal=None, role='assistant', audio=None, function_call=None, tool_calls=[], reasoning_content=None), stop_reason=None)
> 
> **and now vllm0.7.32and cuda nvcc version=11.8 and VLLM_USE_V1=0** Choice(finish_reason='stop', index=0, logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='金', bytes=[233, 135, 145], logprob=0.0, top_logprobs=[TopLogprob(token='金', bytes=[233, 135, 145], logprob=0.0)]), ChatCompletionTokenLogprob(token='利', bytes=[229, 136, 169], logprob=0.0, top_logprobs=[TopLogprob(token='利', bytes=[229, 136, 169], logprob=0.0)]), ChatCompletionTokenLogprob(token='自', bytes=[232, 135, 170], logprob=0.0, top_logprobs=[TopLogprob(token='自', bytes=[232, 135, 170], logprob=0.0)]), ChatCompletionTokenLogprob(token='选', bytes=[233, 128, 137], logprob=0.0, top_logprobs=[TopLogprob(token='选', bytes=[233, 128, 137], logprob=0.0)]), ChatCompletionTokenLogprob(token='店', bytes=[229, 186, 151], logprob=0.0, top_logprobs=[TopLogprob(token='店', bytes=[229, 186, 151], logprob=0.0)]), ChatCompletionTokenLogprob(token='', bytes=[], logprob=0.0, top_logprobs=[TopLogprob(token='', bytes=[], logprob=0.0)])], refusal=None), message=ChatCompletionMessage(content='金利自选店', refusal=None, role='assistant', audio=None, function_call=None, tool_calls=[], reasoning_content=None), stop_reason=None) it changed to 0.0

oh, i also changed gpu-memory-utilization, gpu-memory-utilization will influence logroob?

**Comment by njhill** [comment]
@rainays The sampling params you're using don't look like they make much sense. Rather than setting `k=1`, you should probably set temperature=0 for greedy decoding. Also please update to the latest vLLM release 0.8.2.

**Comment by rainays** [comment]
> [@rainays](https://github.com/rainays) The sampling params you're using don't look like they make much sense. Rather than setting `k=1`, you should probably set temperature=0 for greedy decoding. Also please update to the latest vLLM release 0.8.2.

thanks so so much! i tred change temperature=0 and it works🎉😊
but i cant update vllm to 0.8.2 because my linux is centos，due to the company's basic service, we can only deployed services in batches on some centos7 machines，so if we use vllm>=0.7.3, it will give me a error "**Failed to import from vllm._C with ImportError("/lib64/libc.so.6: version `GLIBC_2.25' not found)**" becasue centos7  ldd --version is 2.17， any better idea can make us update to latest vllm smoothly in this old centos linux kernel 🥺

**Comment by DarkLight1337** [comment]
You can try https://stackoverflow.com/questions/48453497/anaconda-libstdc-so-6-version-glibcxx-3-4-20-not-found

**Comment by rainays** [comment]
> You can try https://stackoverflow.com/questions/48453497/anaconda-libstdc-so-6-version-glibcxx-3-4-20-not-found

thanks! i have solved glibc problem, this issue can close. sincerely hope vllm better and better!!

**Comment by DarkLight1337** [comment]
You're welcome! Next time please give a better title to the issue so it's easier to identify.

**Comment by rainays** [comment]
> You're welcome! Next time please give a better title to the issue so it's easier to identify.

sorry I have changed title of this issue! thanks very much for your replys for this issue🥺
