### ISSUE TITLE
[Performance]: Qwen2.5VL preprocessing extremely slow with large image, leading low gpu usage

### ISSUE THREAD

**Issue by tenacioustommy** [vllm-project/vllm#15869]
### Your current environment (if you think it is necessary)

```text
The output of `python collect_env.py`
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by tenacioustommy** [comment]
> You can try setting `max_pixels` for the HF image processor. This can be achieved in vLLM via the `--mm-processor-kwargs` option

But i have already limit the max_pixels under 256*256 in the messages

**Comment by DarkLight1337** [comment]
Can you show how you sent the request to the online server?

**Comment by DarkLight1337** [comment]
Another thing you can try is to set `--limit-mm-per-prompt image=X,video=0` (where X is the number of images you want to support) to disable video input if you don't plan on using the model for video inference.

**Comment by tenacioustommy** [comment]
I use engine mode by llm.generate and this is my input , i just input all inputs as one batch into one request
   # processor = AutoProcessor.from_pretrained(model_path, use_fast=True)
    # prompt = processor.apply_chat_template(
    #     messages,
    #     tokenize=False,
    #     add_generation_prompt=True,
    # )
    # image_inputs, video_inputs = process_vision_info(messages)
    # # inputs_ids = processor(
    # #     text=[prompt],
    # #     images=image_inputs,
    # #     videos=video_inputs,
    # #     padding=True,
    # #     return_tensors="pt",
    # # )
    # mm_data = {}
    # if image_inputs is not None:
    #     mm_data["image"] = image_inputs
    # if video_inputs is not None:
    #     mm_data["video"] = video_inputs

    # llm_inputs = {
    #     "prompt": prompt,
    #     "multi_modal_data": mm_data,
    # }

**Comment by tenacioustommy** [comment]
What i really care is why the gpu usage is not 100 percent all the time but usually 0, while the cpu usage is only 10 percent as well, and i use py-stack to see what happened, and it shows it stuck at preprocessing

**Comment by tenacioustommy** [comment]
> Another thing you can try is to set `--limit-mm-per-prompt image=X,video=0` (where X is the number of images you want to support) to disable video input if you don't plan on using the model for video inference. This should make model startup significantly faster. Separately, you can also use `qwen-vl-utils` to preprocess the image on client side before sending it to vLLM.

What i really care is why the gpu usage is not 100 percent all the time but usually 0, while the cpu usage is only 10 percent as well, and i use py-stack to see what happened, and it shows it stuck at preprocessing

**Comment by DarkLight1337** [comment]
The HF processor (`Qwen2VLImageProcessor`) is really slow, this has been reported many times already. You can try switching to `Qwen2VLImageProcessorFast` by modifying the model config locally to speed it up, but keep in mind that the results may slightly differ from the original one. cc @Isotr0py

**Comment by Isotr0py** [comment]
> image_inputs, video_inputs = process_vision_info(messages)

Seems that you are using `qwen_vl_utils` to preprocess images, can you try using native hf_processor? I suspect it's a bug related to `qwen_vl_utils`, because I noticed their `torchvision` backend can be very slow on some device before.

**Comment by HeLan-Mounta1N** [comment]
I encountered this issue before as well. I resolved it by upgrading vllm from 0.83 to 0.84.

**Comment by tenacioustommy** [comment]
> I encountered this issue before as well. I resolved it by upgrading vllm from 0.83 to 0.84.

Thanks! let me have a try

**Comment by Cydia2018** [comment]
> > I encountered this issue before as well. I resolved it by upgrading vllm from 0.83 to 0.84.
> 
> Thanks! let me have a try

@tenacioustommy May I ask whether you have already resolved this issue?

**Comment by tenacioustommy** [comment]
> > > I encountered this issue before as well. I resolved it by upgrading vllm from 0.83 to 0.84.
> > 
> > Thanks! let me have a try
> 
> @tenacioustommy May I ask whether you have already resolved this issue?
yes I have solved it
