### ISSUE TITLE
[Bug]: CPU offload not working for vllm serve

### ISSUE THREAD

**Issue by hamaadtahiir** [vllm-project/vllm#15877]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
INFO 04-01 15:38:55 [__init__.py:239] Automatically detected platform cuda.
Collecting environment information...
/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils. Support for replacing an already imported distutils is deprecated. In the future, this condition will fail. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
  warnings.warn(
PyTorch version: 2.6.0+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 24.04.2 LTS (x86_64)
GCC version: (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.39

Python version: 3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.11.0-21-generic-x86_64-with-glibc2.39
Is CUDA available: True
CUDA runtime version: 12.8.93
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 570.124.04
cuDNN version: Probably one of the following:
/usr/local/cuda-12.8/targets/x86_64-linux/lib/libcudnn.so.9.8.0
/usr/local/cuda-12.8/targets/x86_64-linux/lib/libcudnn_adv.so.9.8.0
/usr/local/cuda-12.8/targets/x86_64-linux/lib/libcudnn_cnn.so.9.8.0
/usr/local/cuda-12.8/targets/x86_64-linux/lib/libcudnn_engines_precompiled.so.9.8.0
/usr/local/cuda-12.8/targets/x86_64-linux/lib/libcudnn_engines_runtime_compiled.so.9.8.0
/usr/local/cuda-12.8/targets/x86_64-linux/lib/libcudnn_graph.so.9.8.0
/usr/local/cuda-12.8/targets/x86_64-linux/lib/libcudnn_heuristic.so.9.8.0
/usr/local/cuda-12.8/targets/x86_64-linux/lib/libcudnn_ops.so.9.8.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        43 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               32
On-line CPU(s) list:                  0-31
Vendor ID:                            AuthenticAMD
Model name:                           AMD Ryzen 9 3950X 16-Core Processor
CPU family:                           23
Model:                                113
Thread(s) per core:                   2
Core(s) per socket:                   16
Socket(s):                            1
Stepping:                             0
Frequency boost:                      enabled
CPU(s) scaling MHz:                   53%
CPU max MHz:                          4762.0000
CPU min MHz:                          550.0000
BogoMIPS:                             7000.77
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip rdpid overflow_recov succor smca sev sev_es
L1d cache:                            512 KiB (16 instances)
L1i cache:                            512 KiB (16 instances)
L2 cache:                             8 MiB (16 instances)
L3 cache:                             64 MiB (4 instances)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-31
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec rstack overflow:   Mitigation; Safe RET
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-cusparselt-cu12==0.6.2
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] pyzmq==26.3.0
[pip3] torch==2.6.0
[pip3] torchaudio==2.6.0
[pip3] torchvision==0.21.0
[pip3] transformers==4.49.0.dev0
[pip3] triton==3.2.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
[conda] nvidia-cusparselt-cu12    0.6.2                    pypi_0    pypi
[conda] nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
[conda] pyzmq                     26.3.0                   pypi_0    pypi
[conda] torch                     2.6.0                    pypi_0    pypi
[conda] torchaudio                2.6.0                    pypi_0    pypi
[conda] torchvision               0.21.0                   pypi_0    pypi
[conda] transformers              4.49.0.dev0              pypi_0    pypi
[conda] triton                    3.2.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.8.2
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	0-31	0		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

LD_LIBRARY_PATH=/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/cv2/../../lib64:/usr/local/cuda-12.8/lib64
NCCL_CUMEM_ENABLE=0
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY
```

</details>

### 🐛 Describe the bug

I am running the following command to serve the qwen 2.5 vl 32b awq model:

vllm serve Qwen/Qwen2.5-VL-32B-Instruct-AWQ --quantization awq --port 8000 --host 0.0.0.0 --dtype float16 --max-model-len 16384 --gpu-memory-utilization 0.98 --cpu-offload-gb 5

And I am getting the following error:

```
INFO 04-01 15:35:35 [__init__.py:239] Automatically detected platform cuda.
INFO 04-01 15:35:36 [api_server.py:981] vLLM API server version 0.8.2
INFO 04-01 15:35:36 [api_server.py:982] args: Namespace(subparser='serve', model_tag='Qwen/Qwen2.5-VL-32B-Instruct-AWQ', config='', host='0.0.0.0', port=8000, uvicorn_log_level='info', disable_uvicorn_access_log=False, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, enable_ssl_refresh=False, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='Qwen/Qwen2.5-VL-32B-Instruct-AWQ', task='auto', tokenizer=None, hf_config_path=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='float16', kv_cache_dtype='auto', max_model_len=16384, guided_decoding_backend='xgrammar', logits_processor_pattern=None, model_impl='auto', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=1, enable_expert_parallel=False, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=None, swap_space=4, cpu_offload_gb=5.0, gpu_memory_utilization=0.98, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_partial_prefills=1, max_long_partial_prefills=1, long_prefill_token_threshold=0, max_num_seqs=None, max_logprobs=20, disable_log_stats=False, quantization='awq', rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, use_tqdm_on_load=True, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_config=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', scheduler_cls='vllm.core.scheduler.Scheduler', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', worker_extension_cls='', generation_config='auto', override_generation_config=None, enable_sleep_mode=False, calculate_kv_scales=False, additional_config=None, enable_reasoning=False, reasoning_parser=None, disable_cascade_attn=False, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, enable_server_load_tracking=False, dispatch_function=<function ServeSubcommand.cmd at 0x7d92b856e9e0>)
WARNING 04-01 15:35:37 [config.py:2614] Casting torch.bfloat16 to torch.float16.
INFO 04-01 15:35:42 [config.py:585] This model supports multiple tasks: {'score', 'classify', 'embed', 'generate', 'reward'}. Defaulting to 'generate'.
INFO 04-01 15:35:43 [awq_marlin.py:118] Detected that the model can run with awq_marlin, however you specified quantization=awq explicitly, so forcing awq. Use quantization=awq_marlin for faster inference
WARNING 04-01 15:35:43 [config.py:664] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
WARNING 04-01 15:35:43 [arg_utils.py:1854] --cpu-offload-gb is not supported by the V1 Engine. Falling back to V0. 
INFO 04-01 15:35:43 [api_server.py:241] Started engine process with PID 3814
INFO 04-01 15:35:46 [__init__.py:239] Automatically detected platform cuda.
INFO 04-01 15:35:47 [llm_engine.py:241] Initializing a V0 LLM engine (v0.8.2) with config: model='Qwen/Qwen2.5-VL-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-VL-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=16384, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=Qwen/Qwen2.5-VL-32B-Instruct-AWQ, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=True, 
INFO 04-01 15:35:49 [cuda.py:291] Using Flash Attention backend.
INFO 04-01 15:35:55 [parallel_state.py:954] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0
INFO 04-01 15:35:55 [model_runner.py:1110] Starting to load model Qwen/Qwen2.5-VL-32B-Instruct-AWQ...
INFO 04-01 15:35:55 [config.py:3243] cudagraph sizes specified by model runner [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256] is overridden by config [256, 128, 2, 1, 4, 136, 8, 144, 16, 152, 24, 160, 32, 168, 40, 176, 48, 184, 56, 192, 64, 200, 72, 208, 80, 216, 88, 120, 224, 96, 232, 104, 240, 112, 248]
INFO 04-01 15:36:02 [weight_utils.py:265] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/6 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  17% Completed | 1/6 [00:04<00:21,  4.31s/it]
Loading safetensors checkpoint shards:  33% Completed | 2/6 [00:08<00:16,  4.02s/it]
Loading safetensors checkpoint shards:  50% Completed | 3/6 [00:11<00:11,  3.82s/it]
Loading safetensors checkpoint shards:  67% Completed | 4/6 [00:15<00:07,  3.80s/it]
Loading safetensors checkpoint shards:  83% Completed | 5/6 [00:19<00:03,  3.71s/it]
Loading safetensors checkpoint shards: 100% Completed | 6/6 [00:20<00:00,  3.10s/it]
Loading safetensors checkpoint shards: 100% Completed | 6/6 [00:20<00:00,  3.49s/it]

INFO 04-01 15:36:24 [loader.py:447] Loading weights took 21.04 seconds
INFO 04-01 15:36:26 [model_runner.py:1146] Model loading took 14.3771 GB and 29.674582 seconds
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
WARNING 04-01 15:36:28 [model_runner.py:1296] Computed max_num_seqs (min(256, 16384 // 32768)) to be less than 1. Setting it to the minimum value of 1.
WARNING 04-01 15:36:37 [profiling.py:222] The sequence length used for profiling (max_num_batched_tokens / max_num_seqs = 16384) is too short to hold the multi-modal embeddings in the worst case (32768 tokens in total, out of which {'image': 16384, 'video': 16384} are reserved for multi-modal embeddings). This may cause certain multi-modal inputs to fail during inference, even when the input text is short. To avoid this, you should increase `max_model_len`, reduce `max_num_seqs`, and/or reduce `mm_counts`.
INFO 04-01 15:36:55 [worker.py:267] Memory profiling takes 28.40 seconds
INFO 04-01 15:36:55 [worker.py:267] the current vLLM instance can use total_gpu_memory (23.56GiB) x gpu_memory_utilization (0.98) = 23.09GiB
INFO 04-01 15:36:55 [worker.py:267] model weights take 14.38GiB; non_torch_memory takes 0.10GiB; PyTorch activation peak memory takes 3.67GiB; the rest of the memory reserved for KV Cache is 4.95GiB.
INFO 04-01 15:36:55 [executor_base.py:111] # cuda blocks: 1266, # CPU blocks: 1024
INFO 04-01 15:36:55 [executor_base.py:116] Maximum concurrency for 16384 tokens per request: 1.24x
ERROR 04-01 15:37:00 [engine.py:448] CUDA error: invalid argument
ERROR 04-01 15:37:00 [engine.py:448] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
ERROR 04-01 15:37:00 [engine.py:448] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
ERROR 04-01 15:37:00 [engine.py:448] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
ERROR 04-01 15:37:00 [engine.py:448] Traceback (most recent call last):
ERROR 04-01 15:37:00 [engine.py:448]   File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/engine/multiprocessing/engine.py", line 436, in run_mp_engine
ERROR 04-01 15:37:00 [engine.py:448]     engine = MQLLMEngine.from_vllm_config(
ERROR 04-01 15:37:00 [engine.py:448]   File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/engine/multiprocessing/engine.py", line 128, in from_vllm_config
ERROR 04-01 15:37:00 [engine.py:448]     return cls(
ERROR 04-01 15:37:00 [engine.py:448]   File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/engine/multiprocessing/engine.py", line 82, in __init__
ERROR 04-01 15:37:00 [engine.py:448]     self.engine = LLMEngine(*args, **kwargs)
ERROR 04-01 15:37:00 [engine.py:448]   File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 283, in __init__
ERROR 04-01 15:37:00 [engine.py:448]     self._initialize_kv_caches()
ERROR 04-01 15:37:00 [engine.py:448]   File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 445, in _initialize_kv_caches
ERROR 04-01 15:37:00 [engine.py:448]     self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
ERROR 04-01 15:37:00 [engine.py:448]   File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 122, in initialize_cache
ERROR 04-01 15:37:00 [engine.py:448]     self.collective_rpc("initialize_cache",
ERROR 04-01 15:37:00 [engine.py:448]   File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
ERROR 04-01 15:37:00 [engine.py:448]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 04-01 15:37:00 [engine.py:448]   File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/utils.py", line 2255, in run_method
ERROR 04-01 15:37:00 [engine.py:448]     return func(*args, **kwargs)
ERROR 04-01 15:37:00 [engine.py:448]   File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/worker/worker.py", line 307, in initialize_cache
ERROR 04-01 15:37:00 [engine.py:448]     self._init_cache_engine()
ERROR 04-01 15:37:00 [engine.py:448]   File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/worker/worker.py", line 312, in _init_cache_engine
ERROR 04-01 15:37:00 [engine.py:448]     self.cache_engine = [
ERROR 04-01 15:37:00 [engine.py:448]   File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/worker/worker.py", line 313, in <listcomp>
ERROR 04-01 15:37:00 [engine.py:448]     CacheEngine(self.cache_config, self.model_config,
ERROR 04-01 15:37:00 [engine.py:448]   File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/worker/cache_engine.py", line 66, in __init__
ERROR 04-01 15:37:00 [engine.py:448]     self.cpu_cache = self._allocate_kv_cache(self.num_cpu_blocks, "cpu")
ERROR 04-01 15:37:00 [engine.py:448]   File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/worker/cache_engine.py", line 83, in _allocate_kv_cache
ERROR 04-01 15:37:00 [engine.py:448]     layer_kv_cache = torch.zeros(kv_cache_shape,
ERROR 04-01 15:37:00 [engine.py:448] RuntimeError: CUDA error: invalid argument
ERROR 04-01 15:37:00 [engine.py:448] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
ERROR 04-01 15:37:00 [engine.py:448] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
ERROR 04-01 15:37:00 [engine.py:448] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
ERROR 04-01 15:37:00 [engine.py:448] 
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/engine/multiprocessing/engine.py", line 450, in run_mp_engine
    raise e
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/engine/multiprocessing/engine.py", line 436, in run_mp_engine
    engine = MQLLMEngine.from_vllm_config(
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/engine/multiprocessing/engine.py", line 128, in from_vllm_config
    return cls(
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/engine/multiprocessing/engine.py", line 82, in __init__
    self.engine = LLMEngine(*args, **kwargs)
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 283, in __init__
    self._initialize_kv_caches()
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 445, in _initialize_kv_caches
    self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 122, in initialize_cache
    self.collective_rpc("initialize_cache",
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/utils.py", line 2255, in run_method
    return func(*args, **kwargs)
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/worker/worker.py", line 307, in initialize_cache
    self._init_cache_engine()
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/worker/worker.py", line 312, in _init_cache_engine
    self.cache_engine = [
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/worker/worker.py", line 313, in <listcomp>
    CacheEngine(self.cache_config, self.model_config,
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/worker/cache_engine.py", line 66, in __init__
    self.cpu_cache = self._allocate_kv_cache(self.num_cpu_blocks, "cpu")
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/worker/cache_engine.py", line 83, in _allocate_kv_cache
    layer_kv_cache = torch.zeros(kv_cache_shape,
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]:[W401 15:37:01.452682490 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
Traceback (most recent call last):
  File "/home/aipc/anaconda3/envs/vlm2/bin/vllm", line 8, in <module>
    sys.exit(main())
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/entrypoints/cli/main.py", line 75, in main
    args.dispatch_function(args)
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/entrypoints/cli/serve.py", line 33, in cmd
    uvloop.run(run_server(args))
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/uvloop/__init__.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 1016, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 141, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 264, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.

```

I am getting the same error for other models supported by vllm if I try to use cpu offload command with vllm serve. Detailed system specs are:

AMD Ryzen 9 3950 cpu
16GB RAM
1 x RTX 3090 24GB VRAM

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by jeejeelee** [comment]
Yes, or you can refer to [docs](https://docs.vllm.ai/en/latest/getting_started/installation/gpu.html#pre-built-wheels) to install the latest code.

**Comment by hamaadtahiir** [comment]
OK, done that. Now when I run the following command:

vllm serve Qwen/Qwen2.5-VL-32B-Instruct-AWQ --quantization awq --port 8000 --host 0.0.0.0 --dtype float16 --max-model-len 16384 --gpu-memory-utilization 0.98 --cpu-offload-gb 7

Same issue happens:

```
INFO 04-02 12:25:51 [__init__.py:239] Automatically detected platform cuda.
INFO 04-02 12:25:52 [api_server.py:1031] vLLM API server version 0.8.3.dev183+ga79cc68b
INFO 04-02 12:25:52 [api_server.py:1032] args: Namespace(subparser='serve', model_tag='Qwen/Qwen2.5-VL-32B-Instruct-AWQ', config='', host='0.0.0.0', port=8000, uvicorn_log_level='info', disable_uvicorn_access_log=False, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, enable_ssl_refresh=False, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='Qwen/Qwen2.5-VL-32B-Instruct-AWQ', task='auto', tokenizer=None, hf_config_path=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='float16', kv_cache_dtype='auto', max_model_len=16384, guided_decoding_backend='xgrammar', logits_processor_pattern=None, model_impl='auto', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=1, data_parallel_size=1, enable_expert_parallel=False, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, prefix_caching_hash_algo='builtin', disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=None, swap_space=4, cpu_offload_gb=7.0, gpu_memory_utilization=0.98, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_partial_prefills=1, max_long_partial_prefills=1, long_prefill_token_threshold=0, max_num_seqs=None, max_logprobs=20, disable_log_stats=False, quantization='awq', rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, use_tqdm_on_load=True, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_config=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', scheduler_cls='vllm.core.scheduler.Scheduler', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', worker_extension_cls='', generation_config='auto', override_generation_config=None, enable_sleep_mode=False, calculate_kv_scales=False, additional_config=None, enable_reasoning=False, reasoning_parser=None, disable_cascade_attn=False, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, enable_server_load_tracking=False, dispatch_function=<function ServeSubcommand.cmd at 0x7faff4f4cb80>)
WARNING 04-02 12:25:54 [config.py:2678] Casting torch.bfloat16 to torch.float16.
INFO 04-02 12:25:59 [config.py:598] This model supports multiple tasks: {'embed', 'generate', 'reward', 'classify', 'score'}. Defaulting to 'generate'.
INFO 04-02 12:26:00 [awq_marlin.py:118] Detected that the model can run with awq_marlin, however you specified quantization=awq explicitly, so forcing awq. Use quantization=awq_marlin for faster inference
WARNING 04-02 12:26:00 [config.py:677] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 04-02 12:26:00 [config.py:1758] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 04-02 12:26:04 [__init__.py:239] Automatically detected platform cuda.
INFO 04-02 12:26:05 [core.py:61] Initializing a V1 LLM engine (v0.8.3.dev183+ga79cc68b) with config: model='Qwen/Qwen2.5-VL-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-VL-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=16384, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=Qwen/Qwen2.5-VL-32B-Instruct-AWQ, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"level":3,"custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":512}
WARNING 04-02 12:26:06 [utils.py:2413] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x70cf5dd09660>
INFO 04-02 12:26:06 [parallel_state.py:954] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0
INFO 04-02 12:26:06 [cuda.py:221] Using Flash Attention backend on V1 engine.
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
INFO 04-02 12:26:08 [gpu_model_runner.py:1198] Starting to load model Qwen/Qwen2.5-VL-32B-Instruct-AWQ...
INFO 04-02 12:26:08 [config.py:3308] cudagraph sizes specified by model runner [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 264, 272, 280, 288, 296, 304, 312, 320, 328, 336, 344, 352, 360, 368, 376, 384, 392, 400, 408, 416, 424, 432, 440, 448, 456, 464, 472, 480, 488, 496, 504, 512] is overridden by config [512, 384, 256, 128, 4, 2, 1, 392, 264, 136, 8, 400, 272, 144, 16, 408, 280, 152, 24, 416, 288, 160, 32, 424, 296, 168, 40, 432, 304, 176, 48, 440, 312, 184, 56, 448, 320, 192, 64, 456, 328, 200, 72, 464, 336, 208, 80, 472, 344, 216, 88, 120, 480, 352, 248, 224, 96, 488, 504, 360, 232, 104, 496, 368, 240, 112, 376]
WARNING 04-02 12:26:08 [config.py:3759] `torch.compile` is turned on, but the model Qwen/Qwen2.5-VL-32B-Instruct-AWQ does not support it. Please open an issue on GitHub if you want it to be supported.
WARNING 04-02 12:26:08 [config.py:3759] `torch.compile` is turned on, but the model Qwen/Qwen2.5-VL-32B-Instruct-AWQ does not support it. Please open an issue on GitHub if you want it to be supported.
ERROR 04-02 12:26:09 [core.py:380] EngineCore hit an exception: Traceback (most recent call last):
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/v1/engine/core.py", line 368, in run_engine_core
ERROR 04-02 12:26:09 [core.py:380]     engine_core = EngineCoreProc(*args, **kwargs)
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/v1/engine/core.py", line 309, in __init__
ERROR 04-02 12:26:09 [core.py:380]     super().__init__(vllm_config, executor_class, log_stats)
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/v1/engine/core.py", line 67, in __init__
ERROR 04-02 12:26:09 [core.py:380]     self.model_executor = executor_class(vllm_config)
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/executor/executor_base.py", line 52, in __init__
ERROR 04-02 12:26:09 [core.py:380]     self._init_executor()
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/executor/uniproc_executor.py", line 47, in _init_executor
ERROR 04-02 12:26:09 [core.py:380]     self.collective_rpc("load_model")
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
ERROR 04-02 12:26:09 [core.py:380]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/utils.py", line 2347, in run_method
ERROR 04-02 12:26:09 [core.py:380]     return func(*args, **kwargs)
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/v1/worker/gpu_worker.py", line 136, in load_model
ERROR 04-02 12:26:09 [core.py:380]     self.model_runner.load_model()
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/v1/worker/gpu_model_runner.py", line 1201, in load_model
ERROR 04-02 12:26:09 [core.py:380]     self.model = get_model(vllm_config=self.vllm_config)
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/model_executor/model_loader/__init__.py", line 14, in get_model
ERROR 04-02 12:26:09 [core.py:380]     return loader.load_model(vllm_config=vllm_config)
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/model_executor/model_loader/loader.py", line 441, in load_model
ERROR 04-02 12:26:09 [core.py:380]     model = _initialize_model(vllm_config=vllm_config)
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/model_executor/model_loader/loader.py", line 127, in _initialize_model
ERROR 04-02 12:26:09 [core.py:380]     return model_class(vllm_config=vllm_config, prefix=prefix)
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/model_executor/models/qwen2_5_vl.py", line 802, in __init__
ERROR 04-02 12:26:09 [core.py:380]     self.language_model = init_vllm_registered_model(
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/model_executor/models/utils.py", line 286, in init_vllm_registered_model
ERROR 04-02 12:26:09 [core.py:380]     return _initialize_model(vllm_config=vllm_config, prefix=prefix)
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/model_executor/model_loader/loader.py", line 127, in _initialize_model
ERROR 04-02 12:26:09 [core.py:380]     return model_class(vllm_config=vllm_config, prefix=prefix)
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/model_executor/models/qwen2.py", line 431, in __init__
ERROR 04-02 12:26:09 [core.py:380]     self.model = Qwen2Model(vllm_config=vllm_config,
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/compilation/decorators.py", line 151, in __init__
ERROR 04-02 12:26:09 [core.py:380]     old_init(self, vllm_config=vllm_config, prefix=prefix, **kwargs)
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/model_executor/models/qwen2.py", line 300, in __init__
ERROR 04-02 12:26:09 [core.py:380]     self.start_layer, self.end_layer, self.layers = make_layers(
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/model_executor/models/utils.py", line 609, in make_layers
ERROR 04-02 12:26:09 [core.py:380]     [PPMissingLayer() for _ in range(start_layer)] + [
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/model_executor/models/utils.py", line 610, in <listcomp>
ERROR 04-02 12:26:09 [core.py:380]     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/model_executor/models/utils.py", line 556, in maybe_offload_to_cpu
ERROR 04-02 12:26:09 [core.py:380]     cpu_data = torch.empty_strided(size=p.data.size(),
ERROR 04-02 12:26:09 [core.py:380]   File "/home/aipc/anaconda3/envs/vlm2/lib/python3.10/site-packages/torch/utils/_device.py", line 104, in __torch_function__
ERROR 04-02 12:26:09 [core.py:380]     return func(*args, **kwargs)
ERROR 04-02 12:26:09 [core.py:380] RuntimeError: CUDA error: invalid argument
ERROR 04-02 12:26:09 [core.py:380] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
ERROR 04-02 12:26:09 [core.py:380] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
ERROR 04-02 12:26:09 [core.py:380] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
ERROR 04-02 12:26:09 [core.py:380] 
ERROR 04-02 12:26:09 [core.py:380] 
CRITICAL 04-02 12:26:09 [core_client.py:343] Got fatal signal from worker processes, shutting down. See stack trace above for root cause issue.
Killed

```

However, when I try with '--cpu-offload-gb 5', I get the following error:

```
INFO 04-02 12:33:23 [__init__.py:239] Automatically detected platform cuda.
INFO 04-02 12:33:24 [api_server.py:1031] vLLM API server version 0.8.3.dev183+ga79cc68b
INFO 04-02 12:33:24 [api_server.py:1032] args: Namespace(subparser='serve', model_tag='Qwen/Qwen2.5-VL-32B-Instruct-AWQ', config='', host='0.0.0.0', port=8000, uvicorn_log_level='info', disable_uvicorn_access_log=False, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, enable_ssl_refresh=False, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='Qwen/Qwen2.5-VL-32B-Instruct-AWQ', task='auto', tokenizer=None, hf_config_path=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='float16', kv_cache_dtype='auto', max_model_len=16384, guided_decoding_backend='xgrammar', logits_processor_pattern=None, model_impl='auto', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=1, data_parallel_size=1, enable_expert_parallel=False, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, prefix_caching_hash_algo='builtin', disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=None, swap_space=4, cpu_offload_gb=5.0, gpu_memory_utilization=0.98, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_partial_prefills=1, max_long_partial_prefills=1, long_prefill_token_threshold=0, max_num_seqs=None, max_logprobs=20, disable_log_stats=False, quantization='awq', rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, use_tqdm_on_load=True, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_config=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', scheduler_cls='vllm.core.scheduler.Scheduler', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', worker_extension_cls='', generation_config='auto', override_generation_config=None, enable_sleep_mode=False, calculate_kv_scales=False, additional_config=None, enable_reasoning=False, reasoning_parser=None, disable_cascade_attn=False, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, enable_server_load_tracking=False, dispatch_function=<function ServeSubcommand.cmd at 0x7d3769f04dc0>)
WARNING 04-02 12:33:30 [config.py:2678] Casting torch.bfloat16 to torch.float16.
INFO 04-02 12:33:36 [config.py:598] This model supports multiple tasks: {'generate', 'embed', 'score', 'reward', 'classify'}. Defaulting to 'generate'.
INFO 04-02 12:33:37 [awq_marlin.py:118] Detected that the model can run with awq_marlin, however you specified quantization=awq explicitly, so forcing awq. Use quantization=awq_marlin for faster inference
WARNING 04-02 12:33:37 [config.py:677] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 04-02 12:33:37 [config.py:1758] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 04-02 12:33:41 [__init__.py:239] Automatically detected platform cuda.
INFO 04-02 12:33:42 [core.py:61] Initializing a V1 LLM engine (v0.8.3.dev183+ga79cc68b) with config: model='Qwen/Qwen2.5-VL-32B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2.5-VL-32B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=16384, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=Qwen/Qwen2.5-VL-32B-Instruct-AWQ, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"level":3,"custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":512}
WARNING 04-02 12:33:43 [utils.py:2413] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x770c36dd56f0>
INFO 04-02 12:33:43 [parallel_state.py:954] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0
INFO 04-02 12:33:43 [cuda.py:221] Using Flash Attention backend on V1 engine.
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
INFO 04-02 12:33:45 [gpu_model_runner.py:1198] Starting to load model Qwen/Qwen2.5-VL-32B-Instruct-AWQ...
INFO 04-02 12:33:45 [config.py:3308] cudagraph sizes specified by model runner [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 264, 272, 280, 288, 296, 304, 312, 320, 328, 336, 344, 352, 360, 368, 376, 384, 392, 400, 408, 416, 424, 432, 440, 448, 456, 464, 472, 480, 488, 496, 504, 512] is overridden by config [512, 384, 256, 128, 4, 2, 1, 392, 264, 136, 8, 400, 272, 144, 16, 408, 280, 152, 24, 416, 288, 160, 32, 424, 296, 168, 40, 432, 304, 176, 48, 440, 312, 184, 56, 448, 320, 192, 64, 456, 328, 200, 72, 464, 336, 208, 80, 472, 344, 216, 88, 120, 480, 352, 248, 224, 96, 488, 504, 360, 232, 104, 496, 368, 240, 112, 376]
WARNING 04-02 12:33:52 [topk_topp_sampler.py:69] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
INFO 04-02 12:33:53 [weight_utils.py:265] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/6 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  17% Completed | 1/6 [00:04<00:23,  4.69s/it]
Loading safetensors checkpoint shards:  33% Completed | 2/6 [00:09<00:20,  5.04s/it]
Loading safetensors checkpoint shards:  50% Completed | 3/6 [00:14<00:14,  4.82s/it]
Loading safetensors checkpoint shards:  67% Completed | 4/6 [00:17<00:08,  4.20s/it]
Loading safetensors checkpoint shards:  83% Completed | 5/6 [00:22<00:04,  4.45s/it]
Loading safetensors checkpoint shards: 100% Completed | 6/6 [00:24<00:00,  3.48s/it]
Loading safetensors checkpoint shards: 100% Completed | 6/6 [00:24<00:00,  4.05s/it]

INFO 04-02 12:34:18 [loader.py:447] Loading weights took 24.37 seconds
INFO 04-02 12:34:20 [gpu_model_runner.py:1210] Model loading took 14.3780 GiB and 33.483237 seconds
INFO 04-02 12:34:20 [gpu_model_runner.py:1479] Encoder cache will be initialized with a budget of 16384 tokens, and profiled with 1 image items of the maximum feature size.
INFO 04-02 12:34:54 [backends.py:416] Using cache directory: /home/aipc/.cache/vllm/torch_compile_cache/597035cbc9/rank_0_0 for vLLM's torch.compile
INFO 04-02 12:34:54 [backends.py:426] Dynamo bytecode transform time: 12.50 s
INFO 04-02 12:34:55 [backends.py:115] Directly load the compiled graph for shape None from the cache
INFO 04-02 12:35:06 [monitor.py:33] torch.compile takes 12.50 s in total
ERROR 04-02 12:35:10 [core.py:380] EngineCore hit an exception: Traceback (most recent call last):
ERROR 04-02 12:35:10 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/v1/engine/core.py", line 368, in run_engine_core
ERROR 04-02 12:35:10 [core.py:380]     engine_core = EngineCoreProc(*args, **kwargs)
ERROR 04-02 12:35:10 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/v1/engine/core.py", line 309, in __init__
ERROR 04-02 12:35:10 [core.py:380]     super().__init__(vllm_config, executor_class, log_stats)
ERROR 04-02 12:35:10 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/v1/engine/core.py", line 71, in __init__
ERROR 04-02 12:35:10 [core.py:380]     self._initialize_kv_caches(vllm_config)
ERROR 04-02 12:35:10 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/v1/engine/core.py", line 136, in _initialize_kv_caches
ERROR 04-02 12:35:10 [core.py:380]     kv_cache_configs = [
ERROR 04-02 12:35:10 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/v1/engine/core.py", line 137, in <listcomp>
ERROR 04-02 12:35:10 [core.py:380]     get_kv_cache_config(vllm_config, kv_cache_spec_one_worker,
ERROR 04-02 12:35:10 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/v1/core/kv_cache_utils.py", line 643, in get_kv_cache_config
ERROR 04-02 12:35:10 [core.py:380]     check_enough_kv_cache_memory(vllm_config, kv_cache_spec, available_memory)
ERROR 04-02 12:35:10 [core.py:380]   File "/home/aipc/Desktop/vllm/vllm/v1/core/kv_cache_utils.py", line 490, in check_enough_kv_cache_memory
ERROR 04-02 12:35:10 [core.py:380]     raise ValueError(
ERROR 04-02 12:35:10 [core.py:380] ValueError: To serve at least one request with the models's max seq len (16384), (4.00 GiB KV cache is needed, which is larger than the available KV cache memory (2.12 GiB). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.
ERROR 04-02 12:35:10 [core.py:380] 
CRITICAL 04-02 12:35:10 [core_client.py:343] Got fatal signal from worker processes, shutting down. See stack trace above for root cause issue.
Killed

```

**Comment by Likeux** [comment]
I have the same issue. It seems to be because you are trying to offload a quantized model. Seems like its currently not supported but I could find any info on it.

**Comment by CharlesRiggins** [comment]
Same here. It's not about the quantized model. I use a non-quantized model, and it gets the same error.

**Comment by penghb2025** [comment]
I met with a similar failure when I run test on T4 GPU. In that case, I found it uses the PagedAttention in attention/ops/paged_attn.py. It returns the kv_cache_shape seems to be unexpected to the rest of the code. So I modified that code to return `(2, num_blocks, block_size, num_kv_heads, head_size)`. This works for me.

**Comment by Likeux** [comment]
> I met with a similar failure when I run test on T4 GPU. In that case, I found it uses the PagedAttention in attention/ops/paged_attn.py. It returns the kv_cache_shape seems to be unexpected to the rest of the code. So I modified that code to return `(2, num_blocks, block_size, num_kv_heads, head_size)`. This works for me.

I just tested this on an AWQ model and it worked for me as well. Amazing, thank you 👍
