### ISSUE TITLE
[Bug]: Can't serve mistral3.1-AWQ on 24G GPU

### ISSUE THREAD

**Issue by hahmad2008** [vllm-project/vllm#16128]
### Your current environment

vllm `0.8.1`

### 🐛 Describe the bug

Can I serve mistral3.1-awq (`OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym  `)model on A10 GPU (24G)? 

I get OOM for the following command:
1. command
```
HF_TOKEN=XX VLLM_USE_V1=0 vllm serve OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym  --dtype half  \
--tensor-parallel-size 1  --max-model-len 4096 --gpu-memory-utilization 0.95   --distributed-executor-backend mp \  
--served-model-name mistral --tokenizer-mode mistral --config-format mistral --load_format mistral  \
--hf-config-path mistralai/Mistral-Small-3.1-24B-Instruct-2503   --tokenizer mistralai/Mistral-Small-3.1-24B-Instruct-2503  
```

 1.1. error:
  ```
  torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 320.00 MiB. GPU 0 has a total capacity of 21.99 GiB of which 19.38 MiB is free. Including non-PyTorch memory, this process has 21.96 GiB memory in use. Of the allocated memory 21.67 GiB is allocated by PyTorch, and 5.59 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
  ```

I tried to pass awq to the quantization argument `--quantization awq`, but I get this error:
 
```
 quant_config = get_quant_config(model_config, load_config)
  File "/lib/python3.9/site-packages/vllm/model_executor/model_loader/weight_utils.py", line 196, in get_quant_config
    raise ValueError(
ValueError: Cannot find the config file for awq
```

**Do I miss anything here?**

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by hahmad2008** [comment]
@DarkLight1337 could you please check this one? 🙏

**Comment by DarkLight1337** [comment]
Are you sure the model is in Mistral format?

**Comment by hahmad2008** [comment]
@DarkLight1337 should it be a mistral as it is a quantized version from mistral instruct `mistralai/Mistral-Small-3.1-24B-Instruct-2503 `?

**Comment by DarkLight1337** [comment]
The original repo supports both HF (`model-*-of-*.safetensors`) weights and Mistral (`consolidated.safetensors`) weights. You should check which one you're supposed to use/

**Comment by hahmad2008** [comment]
If i didn't pass the `hf-config-path `I get this error:
```
File " /lib/python3.9/site-packages/vllm/transformers_utils/config.py", line 623, in load_params_config
    assert isinstance(config_dict, dict)
AssertionError

```
that's why I pass it. what is the best practice here to do if i need to serve [OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym](https://huggingface.co/OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym)  model?

**Comment by DarkLight1337** [comment]
You can try removing the options related to `--config-format` and `--load-format`

**Comment by hahmad2008** [comment]
Shouldn't we use them for mistral3.1 mode as we i did the base mistral3.1 model?

remove them and encountered this error: `ValueError: Mistral3ForConditionalGeneration has no vLLM implementation and the Transformers implementation is not compatible with vLLM. Try setting VLLM_USE_V1=0..`

**Comment by hahmad2008** [comment]
@DarkLight1337 previously I used this command to serve the base model on A100 (80G) or 4xA10 GPUs(each with 24G)

```
 VLLM_USE_V1=0 vllm serve mistralai/Mistral-Small-3.1-24B-Base-2503  --tensor-parallel-size 1  \
--max-model-len 32000 --gpu-memory-utilization 0.90   --distributed-executor-backend mp  \
--served-model-name mistral --tokenizer-mode mistral --config-format mistral --load_format mistral
```

And now the first command in this issue should work, but I have a OOM, so my question can I serve mistral3.1-AWQ on A10(24G)? and should I pass anything related to quantization?

**Comment by DarkLight1337** [comment]
The latest version of vLLM should support HF format of Mistral3 model, can you update vLLM?

**Comment by hahmad2008** [comment]
@DarkLight1337 I tried this without mistral mode as you mentioned and still I get OOM, does it mean we can't load it on A10(24G) GPU?

```
HF_TOKEN=XXX VLLM_USE_V1=0 vllm serve OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym \
--tensor-parallel-size 1  --max-model-len 4096 --gpu-memory-utilization 0.95   --distributed-executor-backend mp \
--hf-config-path mistralai/Mistral-Small-3.1-24B-Instruct-2503   --tokenizer mistralai/Mistral-Small-3.1-24B-Instruct-2503  \
 --served-model-name mistral  --dtype half  
```

**Comment by DarkLight1337** [comment]
`--config-format`/`--load-format`/`--tokenizer-mode` are to load the model in Mistral format. Seems that the quantized repo uses the HF formatted weights.

Why are you setting `--dtype half` if you're already using quantized model?

**Comment by hmellor** [comment]
`--dtype half` will mean you need 48GB for model weights, which is double the 24GB you have.

**Comment by hahmad2008** [comment]
@hmellor the base model when i load it on 4A10, it took 44.5G to the model weights to be loaded on the GPU. What about the awq mode `OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym`? isn't it a smaller than the original? should fit on 24G, right? do i miss anything here in the command?

- command:
```
HF_TOKEN=XX  VLLM_USE_V1=0 vllm serve OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym \
--tensor-parallel-size 1  --max-model-len 128 --gpu-memory-utilization 0.95   --distributed-executor-backend ray \
--hf-config-path mistralai/Mistral-Small-3.1-24B-Instruct-2503   --tokenizer mistralai/Mistral-Small-3.1-24B-Instruct-2503  \
 --served-model-name mistral  
```

- error:

```
INFO 04-07 09:02:48 [llm_engine.py:242] Initializing a V0 LLM engine (v0.8.3) with config: model='OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym', speculative_config=None, tokenizer='mistralai/Mistral-Small-3.1-24B-Instruct-2503', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=128, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=mistral, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=True, 
lib/python3.9/site-packages/vllm/transformers_utils/tokenizer_group/tokenizer_group.py:25: FutureWarning: It is strongly recommended to run mistral models with `--tokenizer-mode "mistral"` to ensure correct encoding and decoding.
  self.tokenizer = get_tokenizer(self.tokenizer_id, **tokenizer_config)
WARNING 04-07 09:02:49 [multiproc_worker_utils.py:306] Reducing Torch parallelism from 8 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 04-07 09:02:50 [cuda.py:292] Using Flash Attention backend.
INFO 04-07 09:02:51 [parallel_state.py:957] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0
INFO 04-07 09:02:51 [model_runner.py:1110] Starting to load model OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym...
INFO 04-07 09:02:52 [config.py:3334] cudagraph sizes specified by model runner [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256] is overridden by config [256, 128, 2, 1, 4, 136, 8, 144, 16, 152, 24, 160, 32, 168, 40, 176, 48, 184, 56, 192, 64, 200, 72, 208, 80, 216, 88, 120, 224, 96, 232, 104, 240, 112, 248]
ERROR 04-07 09:02:53 [engine.py:448] CUDA out of memory. Tried to allocate 320.00 MiB. GPU 0 has a total capacity of 21.99 GiB of which 231.38 MiB is free. Including non-PyTorch memory, this process has 21.75 GiB memory in use. Of the allocated memory 21.46 GiB is allocated by PyTorch, and 12.54 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
ERROR 04-07 09:02:53 [engine.py:448] Traceback (most recent call last):
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/engine/multiprocessing/engine.py", line 436, in run_mp_engine
ERROR 04-07 09:02:53 [engine.py:448]     engine = MQLLMEngine.from_vllm_config(
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/engine/multiprocessing/engine.py", line 128, in from_vllm_config
ERROR 04-07 09:02:53 [engine.py:448]     return cls(
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/engine/multiprocessing/engine.py", line 82, in __init__
ERROR 04-07 09:02:53 [engine.py:448]     self.engine = LLMEngine(*args, **kwargs)
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 281, in __init__
ERROR 04-07 09:02:53 [engine.py:448]     self.model_executor = executor_class(vllm_config=vllm_config, )
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/executor/executor_base.py", line 286, in __init__
ERROR 04-07 09:02:53 [engine.py:448]     super().__init__(*args, **kwargs)
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/executor/executor_base.py", line 52, in __init__
ERROR 04-07 09:02:53 [engine.py:448]     self._init_executor()
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/executor/mp_distributed_executor.py", line 125, in _init_executor
ERROR 04-07 09:02:53 [engine.py:448]     self._run_workers("load_model",
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/executor/mp_distributed_executor.py", line 185, in _run_workers
ERROR 04-07 09:02:53 [engine.py:448]     driver_worker_output = run_method(self.driver_worker, sent_method,
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/utils.py", line 2347, in run_method
ERROR 04-07 09:02:53 [engine.py:448]     return func(*args, **kwargs)
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/worker/worker.py", line 183, in load_model
ERROR 04-07 09:02:53 [engine.py:448]     self.model_runner.load_model()
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/worker/model_runner.py", line 1113, in load_model
ERROR 04-07 09:02:53 [engine.py:448]     self.model = get_model(vllm_config=self.vllm_config)
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/model_loader/__init__.py", line 14, in get_model
ERROR 04-07 09:02:53 [engine.py:448]     return loader.load_model(vllm_config=vllm_config)
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/model_loader/loader.py", line 441, in load_model
ERROR 04-07 09:02:53 [engine.py:448]     model = _initialize_model(vllm_config=vllm_config)
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/model_loader/loader.py", line 127, in _initialize_model
ERROR 04-07 09:02:53 [engine.py:448]     return model_class(vllm_config=vllm_config, prefix=prefix)
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/models/mistral3.py", line 470, in __init__
ERROR 04-07 09:02:53 [engine.py:448]     self.language_model = init_vllm_registered_model(
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/models/utils.py", line 286, in init_vllm_registered_model
ERROR 04-07 09:02:53 [engine.py:448]     return _initialize_model(vllm_config=vllm_config, prefix=prefix)
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/model_loader/loader.py", line 127, in _initialize_model
ERROR 04-07 09:02:53 [engine.py:448]     return model_class(vllm_config=vllm_config, prefix=prefix)
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 486, in __init__
ERROR 04-07 09:02:53 [engine.py:448]     self.model = self._init_model(vllm_config=vllm_config,
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 527, in _init_model
ERROR 04-07 09:02:53 [engine.py:448]     return LlamaModel(vllm_config=vllm_config,
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/compilation/decorators.py", line 151, in __init__
ERROR 04-07 09:02:53 [engine.py:448]     old_init(self, vllm_config=vllm_config, prefix=prefix, **kwargs)
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 321, in __init__
ERROR 04-07 09:02:53 [engine.py:448]     self.start_layer, self.end_layer, self.layers = make_layers(
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/models/utils.py", line 609, in make_layers
ERROR 04-07 09:02:53 [engine.py:448]     [PPMissingLayer() for _ in range(start_layer)] + [
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/models/utils.py", line 610, in <listcomp>
ERROR 04-07 09:02:53 [engine.py:448]     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 323, in <lambda>
ERROR 04-07 09:02:53 [engine.py:448]     lambda prefix: layer_type(config=config,
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 254, in __init__
ERROR 04-07 09:02:53 [engine.py:448]     self.mlp = LlamaMLP(
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 78, in __init__
ERROR 04-07 09:02:53 [engine.py:448]     self.down_proj = RowParallelLinear(
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/layers/linear.py", line 1169, in __init__
ERROR 04-07 09:02:53 [engine.py:448]     self.quant_method.create_weights(
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/vllm/model_executor/layers/linear.py", line 178, in create_weights
ERROR 04-07 09:02:53 [engine.py:448]     weight = Parameter(torch.empty(sum(output_partition_sizes),
ERROR 04-07 09:02:53 [engine.py:448]   File "lib/python3.9/site-packages/torch/utils/_device.py", line 104, in __torch_function__
ERROR 04-07 09:02:53 [engine.py:448]     return func(*args, **kwargs)
ERROR 04-07 09:02:53 [engine.py:448] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 320.00 MiB. GPU 0 has a total capacity of 21.99 GiB of which 231.38 MiB is free. Including non-PyTorch memory, this process has 21.75 GiB memory in use. Of the allocated memory 21.46 GiB is allocated by PyTorch, and 12.54 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

```
 
cc: @DarkLight1337

**Comment by hmellor** [comment]
```
VLLM_USE_V1=0 vllm serve OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym \
  --tensor-parallel-size 1  \
  --max-model-len 128 \
  --gpu-memory-utilization 0.95 \
  --distributed-executor-backend ray \
  --hf-config-path mistralai/Mistral-Small-3.1-24B-Instruct-2503  \
  --tokenizer mistralai/Mistral-Small-3.1-24B-Instruct-2503  \
  --served-model-name mistral 
```

- `--tensor-parallel-size 1` - not necessary when not using TP
- `--distributed-executor-backend ray` - not necessary when not distributed
- `--hf-config-path mistralai/Mistral-Small-3.1-24B-Instruct-2503` - not necessary*
- `--tokenizer mistralai/Mistral-Small-3.1-24B-Instruct-2503` - not necessary

*the `config.json` for [mistralai/Mistral-Small-3.1-24B-Base-2503](https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Base-2503/blob/main/config.json) is not the same as the config for [OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym](https://huggingface.co/OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym/blob/main/config.json). It does not contain the quantisation config, so the model isn't being loaded with quantisation.

---

On the HF side, do you have a new enough version of Transformers? Mistral 3.1 support was added in v4.50.0.

**Comment by hahmad2008** [comment]
How to load it in quantization form using vllm command? for transformers i used the same version that the latest vllm used. version `'4.51.0'`

**Comment by hmellor** [comment]
> How to load it in quantization form using vllm command?

```
VLLM_USE_V1=0 vllm serve OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym \
  --max-model-len 128 \
  --gpu-memory-utilization 0.95 \
  --served-model-name mistral 
```

**Comment by hahmad2008** [comment]
@hmellor Thanks it can be loaded on 24G GPU. Actually I was using these params `--hf-config-path ` while i am using vllm version 0.8.1 as I have this error: 
```
  File " /lib/python3.9/site-packages/vllm/transformers_utils/config.py", line 623, in load_params_config
    assert isinstance(config_dict, dict)
AssertionError
```

However this error disappeared when I use vllm  `v0.8.3`

Please, do you have any explanation?

**Comment by DarkLight1337** [comment]
Support for HF format Mistral3 was only released in vLLM v0.8.3

**Comment by hahmad2008** [comment]
@DarkLight1337 for now I don't have to use these options `--config-format`,-`-load-format`, `--tokenizer-mode`? even for the instruct base model? and then it should use the tokenizer as is not the mistral one as before when I use these options? 
Also what is the chat template here? does it the same as the one built in Mistral tokenizer?

**Comment by DarkLight1337** [comment]
Yes. You don't have to use those options for HF format. Everything can be loaded in HF transformers now. Please open an issue on HF repo if the chat template doesn't work.

**Comment by hahmad2008** [comment]
@DarkLight1337 @hmellor  the model wight takes `Model loading took 14.1373 GiB ` but I can't load the model with 4k context length! I have OOM. why? Llama3.1-8b has the same model weight when loading 14G but I could serve it with up to 14k context length on 24G GPU.

**Comment by DarkLight1337** [comment]
Do keep in mind that you need VRAM not just for the model weights, but also for the forward pass and sampler. What is the `max_num_seqs` that you have set?

**Comment by hahmad2008** [comment]
The default, I didn't pass anything for this argument.

**Comment by DarkLight1337** [comment]
Can you try setting it to a small value like `--max-num-seqs 2`?

**Comment by hahmad2008** [comment]
@DarkLight1337 still have OOM

```
$ vllm serve OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym \
--tensor-parallel-size 1  --max-model-len 4096 --gpu-memory-utilization 0.95   --distributed-executor-backend ray  --dtype float16  --max-num-seqs 2



INFO 04-07 09:53:02 [__init__.py:239] Automatically detected platform cuda.
INFO 04-07 09:53:06 [api_server.py:1034] vLLM API server version 0.8.3
INFO 04-07 09:53:06 [api_server.py:1035] args: Namespace(subparser='serve', model_tag='OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym', config='', host=None, port=8000, uvicorn_log_level='info', disable_uvicorn_access_log=False, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, enable_ssl_refresh=False, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym', task='auto', tokenizer=None, hf_config_path=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='float16', kv_cache_dtype='auto', max_model_len=4096, guided_decoding_backend='xgrammar', logits_processor_pattern=None, model_impl='auto', distributed_executor_backend='ray', pipeline_parallel_size=1, tensor_parallel_size=1, data_parallel_size=1, enable_expert_parallel=False, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, prefix_caching_hash_algo='builtin', disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=None, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.95, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_partial_prefills=1, max_long_partial_prefills=1, long_prefill_token_threshold=0, max_num_seqs=2, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, use_tqdm_on_load=True, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_config=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', scheduler_cls='vllm.core.scheduler.Scheduler', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', worker_extension_cls='', generation_config='auto', override_generation_config=None, enable_sleep_mode=False, calculate_kv_scales=False, additional_config=None, enable_reasoning=False, reasoning_parser=None, disable_cascade_attn=False, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, enable_server_load_tracking=False, dispatch_function=<function ServeSubcommand.cmd at 0x7feb592868b0>)
INFO 04-07 09:53:17 [config.py:600] This model supports multiple tasks: {'reward', 'classify', 'score', 'embed', 'generate'}. Defaulting to 'generate'.
WARNING 04-07 09:53:25 [config.py:679] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 04-07 09:53:30 [config.py:1780] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 04-07 09:53:35 [__init__.py:239] Automatically detected platform cuda.
INFO 04-07 09:53:40 [core.py:61] Initializing a V1 LLM engine (v0.8.3) with config: model='OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym', speculative_config=None, tokenizer='OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=awq, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"level":3,"custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":512}
2025-04-07 09:53:43,347 INFO worker.py:1841 -- Started a local Ray instance.
INFO 04-07 09:53:44 [ray_utils.py:335] No current placement group found. Creating a new placement group.
INFO 04-07 09:53:44 [ray_distributed_executor.py:176] use_ray_spmd_worker: True
(pid=64829) INFO 04-07 09:53:48 [__init__.py:239] Automatically detected platform cuda.
INFO 04-07 09:53:53 [ray_distributed_executor.py:352] non_carry_over_env_vars from config: set()
INFO 04-07 09:53:53 [ray_distributed_executor.py:354] Copying the following environment variables to workers: ['VLLM_USE_RAY_SPMD_WORKER', 'VLLM_USE_RAY_COMPILED_DAG', 'VLLM_WORKER_MULTIPROC_METHOD', 'VLLM_USE_V1']
INFO 04-07 09:53:53 [ray_distributed_executor.py:357] If certain env vars should NOT be copied to workers, add them to /home/ubuntu/.config/vllm/ray_non_carry_over_env_vars.json file
(RayWorkerWrapper pid=64829) WARNING 04-07 09:53:56 [utils.py:2413] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7f44aa184fa0>
(RayWorkerWrapper pid=64829) INFO 04-07 09:53:59 [parallel_state.py:957] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0
(RayWorkerWrapper pid=64829) INFO 04-07 09:53:59 [cuda.py:221] Using Flash Attention backend on V1 engine.
(RayWorkerWrapper pid=64829) INFO 04-07 09:54:01 [gpu_model_runner.py:1258] Starting to load model OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym...
(RayWorkerWrapper pid=64829) INFO 04-07 09:54:01 [config.py:3334] cudagraph sizes specified by model runner [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 264, 272, 280, 288, 296, 304, 312, 320, 328, 336, 344, 352, 360, 368, 376, 384, 392, 400, 408, 416, 424, 432, 440, 448, 456, 464, 472, 480, 488, 496, 504, 512] is overridden by config [512, 384, 256, 128, 4, 2, 1, 392, 264, 136, 8, 400, 272, 144, 16, 408, 280, 152, 24, 416, 288, 160, 32, 424, 296, 168, 40, 432, 304, 176, 48, 440, 312, 184, 56, 448, 320, 192, 64, 456, 328, 200, 72, 464, 336, 208, 80, 472, 344, 216, 88, 120, 480, 352, 248, 224, 96, 488, 504, 360, 232, 104, 496, 368, 240, 112, 376]
(RayWorkerWrapper pid=64829) WARNING 04-07 09:54:01 [topk_topp_sampler.py:69] FlashInfer is not available. Falling back to the PyTorch-native implementation of top-p & top-k sampling. For the best performance, please install FlashInfer.
(RayWorkerWrapper pid=64829) INFO 04-07 09:54:02 [weight_utils.py:265] Using model weights format ['*.safetensors']
(RayWorkerWrapper pid=64829) INFO 04-07 09:54:02 [weight_utils.py:281] Time spent downloading weights for OPEA/Mistral-Small-3.1-24B-Instruct-2503-int4-AutoRound-awq-sym: 0.549679 seconds
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:00<00:01,  1.75it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:01<00:01,  1.26it/s]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:04<00:01,  1.58s/it]
(RayWorkerWrapper pid=64829) INFO 04-07 09:54:08 [loader.py:447] Loading weights took 5.70 seconds
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.58s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:05<00:00,  1.41s/it]
(RayWorkerWrapper pid=64829) 
(RayWorkerWrapper pid=64829) INFO 04-07 09:54:08 [gpu_model_runner.py:1273] Model loading took 14.1373 GiB and 7.327854 seconds
(RayWorkerWrapper pid=64829) INFO 04-07 09:54:09 [gpu_model_runner.py:1542] Encoder cache will be initialized with a budget of 3080 tokens, and profiled with 1 image items of the maximum feature size.
(RayWorkerWrapper pid=64829) INFO 04-07 09:54:22 [backends.py:416] Using cache directory: /home/ubuntu/.cache/vllm/torch_compile_cache/56dbe1f063/rank_0_0 for vLLM's torch.compile
(RayWorkerWrapper pid=64829) INFO 04-07 09:54:22 [backends.py:426] Dynamo bytecode transform time: 10.01 s
(RayWorkerWrapper pid=64829) huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
(RayWorkerWrapper pid=64829) To disable this warning, you can either:
(RayWorkerWrapper pid=64829)    - Avoid using `tokenizers` before the fork if possible
(RayWorkerWrapper pid=64829)    - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
(RayWorkerWrapper pid=64829) huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
(RayWorkerWrapper pid=64829) To disable this warning, you can either:
(RayWorkerWrapper pid=64829)    - Avoid using `tokenizers` before the fork if possible
(RayWorkerWrapper pid=64829)    - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
(RayWorkerWrapper pid=64829) INFO 04-07 09:54:23 [backends.py:115] Directly load the compiled graph for shape None from the cache
(RayWorkerWrapper pid=64829) INFO 04-07 09:54:36 [monitor.py:33] torch.compile takes 10.01 s in total
INFO 04-07 09:54:39 [kv_cache_utils.py:578] GPU KV cache size: 35,392 tokens
INFO 04-07 09:54:39 [kv_cache_utils.py:581] Maximum concurrency for 4,096 tokens per request: 8.64x
ERROR 04-07 09:54:52 [core.py:390] EngineCore hit an exception: Traceback (most recent call last):
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/v1/engine/core.py", line 378, in run_engine_core
ERROR 04-07 09:54:52 [core.py:390]     engine_core = EngineCoreProc(*args, **kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/v1/engine/core.py", line 319, in __init__
ERROR 04-07 09:54:52 [core.py:390]     super().__init__(vllm_config, executor_class, log_stats)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/v1/engine/core.py", line 71, in __init__
ERROR 04-07 09:54:52 [core.py:390]     self._initialize_kv_caches(vllm_config)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/v1/engine/core.py", line 159, in _initialize_kv_caches
ERROR 04-07 09:54:52 [core.py:390]     self.model_executor.initialize_from_config(kv_cache_configs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/v1/executor/abstract.py", line 63, in initialize_from_config
ERROR 04-07 09:54:52 [core.py:390]     self.collective_rpc("compile_or_warm_up_model")
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/executor/executor_base.py", line 331, in collective_rpc
ERROR 04-07 09:54:52 [core.py:390]     return self._run_workers(method, *args, **(kwargs or {}))
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/executor/ray_distributed_executor.py", line 521, in _run_workers
ERROR 04-07 09:54:52 [core.py:390]     ray_worker_outputs = ray.get(ray_worker_outputs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
ERROR 04-07 09:54:52 [core.py:390]     return fn(*args, **kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
ERROR 04-07 09:54:52 [core.py:390]     return func(*args, **kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/ray/_private/worker.py", line 2771, in get
ERROR 04-07 09:54:52 [core.py:390]     values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/ray/_private/worker.py", line 919, in get_objects
ERROR 04-07 09:54:52 [core.py:390]     raise value.as_instanceof_cause()
ERROR 04-07 09:54:52 [core.py:390] ray.exceptions.RayTaskError(OutOfMemoryError): ray::RayWorkerWrapper.execute_method() (pid=64829, ip=10.5.8.112, actor_id=5d571e13d3d1d9f384ad757f01000000, repr=<vllm.executor.ray_utils.RayWorkerWrapper object at 0x7f44aa193be0>)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/worker/worker_base.py", line 621, in execute_method
ERROR 04-07 09:54:52 [core.py:390]     raise e
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/worker/worker_base.py", line 612, in execute_method
ERROR 04-07 09:54:52 [core.py:390]     return run_method(self, method, args, kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/utils.py", line 2347, in run_method
ERROR 04-07 09:54:52 [core.py:390]     return func(*args, **kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/v1/worker/gpu_worker.py", line 216, in compile_or_warm_up_model
ERROR 04-07 09:54:52 [core.py:390]     self.model_runner.capture_model()
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/v1/worker/gpu_model_runner.py", line 1600, in capture_model
ERROR 04-07 09:54:52 [core.py:390]     self._dummy_run(num_tokens)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 04-07 09:54:52 [core.py:390]     return func(*args, **kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/v1/worker/gpu_model_runner.py", line 1423, in _dummy_run
ERROR 04-07 09:54:52 [core.py:390]     hidden_states = model(
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
ERROR 04-07 09:54:52 [core.py:390]     return self._call_impl(*args, **kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
ERROR 04-07 09:54:52 [core.py:390]     return forward_call(*args, **kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/model_executor/models/mistral3.py", line 634, in forward
ERROR 04-07 09:54:52 [core.py:390]     hidden_states = self.language_model.model(input_ids,
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/compilation/decorators.py", line 245, in __call__
ERROR 04-07 09:54:52 [core.py:390]     model_output = self.forward(*args, **kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/model_executor/models/llama.py", line 341, in forward
ERROR 04-07 09:54:52 [core.py:390]     def forward(
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
ERROR 04-07 09:54:52 [core.py:390]     return self._call_impl(*args, **kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
ERROR 04-07 09:54:52 [core.py:390]     return forward_call(*args, **kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 745, in _fn
ERROR 04-07 09:54:52 [core.py:390]     return fn(*args, **kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/torch/fx/graph_module.py", line 822, in call_wrapped
ERROR 04-07 09:54:52 [core.py:390]     return self._wrapped_call(self, *args, **kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/torch/fx/graph_module.py", line 400, in __call__
ERROR 04-07 09:54:52 [core.py:390]     raise e
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/torch/fx/graph_module.py", line 387, in __call__
ERROR 04-07 09:54:52 [core.py:390]     return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
ERROR 04-07 09:54:52 [core.py:390]     return self._call_impl(*args, **kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
ERROR 04-07 09:54:52 [core.py:390]     return forward_call(*args, **kwargs)
ERROR 04-07 09:54:52 [core.py:390]   File "<eval_with_key>.82", line 582, in forward
ERROR 04-07 09:54:52 [core.py:390]     submod_4 = self.submod_4(getitem_7, s0, l_self_modules_layers_modules_1_modules_self_attn_modules_o_proj_parameters_qweight_, l_self_modules_layers_modules_1_modules_self_attn_modules_o_proj_parameters_scales_, l_self_modules_layers_modules_1_modules_self_attn_modules_o_proj_parameters_qzeros_, getitem_8, l_self_modules_layers_modules_1_modules_post_attention_layernorm_parameters_weight_, l_self_modules_layers_modules_1_modules_mlp_modules_gate_up_proj_parameters_qweight_, l_self_modules_layers_modules_1_modules_mlp_modules_gate_up_proj_parameters_scales_, l_self_modules_layers_modules_1_modules_mlp_modules_gate_up_proj_parameters_qzeros_, l_self_modules_layers_modules_1_modules_mlp_modules_down_proj_parameters_qweight_, l_self_modules_layers_modules_1_modules_mlp_modules_down_proj_parameters_scales_, l_self_modules_layers_modules_1_modules_mlp_modules_down_proj_parameters_qzeros_, l_self_modules_layers_modules_2_modules_input_layernorm_parameters_weight_, l_self_modules_layers_modules_2_modules_self_attn_modules_qkv_proj_parameters_qweight_, l_self_modules_layers_modules_2_modules_self_attn_modules_qkv_proj_parameters_scales_, l_self_modules_layers_modules_2_modules_self_attn_modules_qkv_proj_parameters_qzeros_, l_positions_, l_self_modules_layers_modules_0_modules_self_attn_modules_rotary_emb_buffers_cos_sin_cache_);  getitem_7 = l_self_modules_layers_modules_1_modules_self_attn_modules_o_proj_parameters_qweight_ = l_self_modules_layers_modules_1_modules_self_attn_modules_o_proj_parameters_scales_ = l_self_modules_layers_modules_1_modules_self_attn_modules_o_proj_parameters_qzeros_ = getitem_8 = l_self_modules_layers_modules_1_modules_post_attention_layernorm_parameters_weight_ = l_self_modules_layers_modules_1_modules_mlp_modules_gate_up_proj_parameters_qweight_ = l_self_modules_layers_modules_1_modules_mlp_modules_gate_up_proj_parameters_scales_ = l_self_modules_layers_modules_1_modules_mlp_modules_gate_up_proj_parameters_qzeros_ = l_self_modules_layers_modules_1_modules_mlp_modules_down_proj_parameters_qweight_ = l_self_modules_layers_modules_1_modules_mlp_modules_down_proj_parameters_scales_ = l_self_modules_layers_modules_1_modules_mlp_modules_down_proj_parameters_qzeros_ = l_self_modules_layers_modules_2_modules_input_layernorm_parameters_weight_ = l_self_modules_layers_modules_2_modules_self_attn_modules_qkv_proj_parameters_qweight_ = l_self_modules_layers_modules_2_modules_self_attn_modules_qkv_proj_parameters_scales_ = l_self_modules_layers_modules_2_modules_self_attn_modules_qkv_proj_parameters_qzeros_ = None
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/compilation/backends.py", line 649, in __call__
ERROR 04-07 09:54:52 [core.py:390]     return entry.runnable(*args)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/vllm/compilation/compiler_interface.py", line 357, in compiled_graph
ERROR 04-07 09:54:52 [core.py:390]     graph_output = inductor_compiled_graph(list_args)
ERROR 04-07 09:54:52 [core.py:390]   File "/lib/python3.9/site-packages/torch/_inductor/output_code.py", line 466, in __call__
ERROR 04-07 09:54:52 [core.py:390]     return self.current_callable(inputs)
ERROR 04-07 09:54:52 [core.py:390]   File "/home/ubuntu/.cache/vllm/torch_compile_cache/56dbe1f063/rank_0_0/inductor_cache/nm/cnmqd3soq4fu56ilve7gq4jx5uejd6tjsbowrpjeubqrowl6hfqw.py", line 477, in call
ERROR 04-07 09:54:52 [core.py:390]     buf7 = empty_strided_cuda((s0, 65536), (65536, 1), torch.float16)
ERROR 04-07 09:54:52 [core.py:390] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB. GPU 0 has a total capacity of 21.99 GiB of which 33.38 MiB is free. Including non-PyTorch memory, this process has 21.95 GiB memory in use. Of the allocated memory 20.98 GiB is allocated by PyTorch, with 777.00 MiB allocated in private pools (e.g., CUDA Graphs), and 131.91 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
ERROR 04-07 09:54:52 [core.py:390] 
INFO 04-07 09:54:52 [ray_distributed_executor.py:127] Shutting down Ray distributed executor. If you see error log from logging.cc regarding SIGTERM received, please ignore because this is the expected termination process in Ray.
CRITICAL 04-07 09:54:52 [core_client.py:361] Got fatal signal from worker processes, shutting down. See stack trace above for root cause issue.
Killed
```

**Comment by hahmad2008** [comment]
@DarkLight1337 I could serve 4k when I set use` VLLM_USE_V1=0 ` however what is the diff between v0 and v1? why v1 takes memory more than v0?

**Comment by alew3** [comment]
Is Mistral3.1 quantized AWQ working with vLLM?

**Comment by joboosij** [comment]
This Mistral model is really tricky. The original Mistral model works fine, but once it's quantized (in HF format), it becomes a complete mess. In the case of vLLM, it's known for being lenient with Qwen but notorious for its aversion to the GGUF quantization type. When it's needed for work, vLLM becomes a real headache.

**Comment by DarkLight1337** [comment]
cc @Isotr0py maybe you can help with this?

**Comment by Isotr0py** [comment]
@joboosij Can you provide the model you are trying to run?
