### ISSUE TITLE
[Performance]:

### ISSUE THREAD

**Issue by fangbaolei** [vllm-project/vllm#16342]
### Proposal to improve performance

When running the vllm Docker container with version v0.8.3, a CUDA out of memory error occurs, while version v0.6.3 runs without issues on an A100 80GB GPU. The error message indicates that the GPU runs out of memory during the warm-up phase, specifically when handling 1024 dummy requests. The model in question is Qwen2.5-14B-Instruct-AWQ, and the Docker command used is as follows:

  docker run --rm \
  --name Qwen2.5-14B-Instruct-AWQ \
  --runtime nvidia \
  --gpus all \
  -v /ai/model/model/:/models \
  -p 8000:8000 \
  --ipc=host \
  vllm/vllm-openai:v0.8.3 \
  --served-model-name Qwen2.5-14B-Instruct-AWQ \
  --max-model-len 4096 \
  --trust-remote-code \
  --gpu-memory-utilization 0.99 \
  --model /models/Qwen2.5-14B-Instruct-AWQ

The performance of version 0.8.3 is not as good as that of version 0.6.3.
reuslt as below：
 vllm version        mdoel                           ttfs                   throughput       GPU Utilization     
vllm 0.8.3      Qwen2.5-7B-Instruct	   0.062856206	        91.79787982	      0.85-0.92
vllm 0.6.3      Qwen2.5-7B-Instruct     0.045440826	103.2321574	      0.94

env use：

![Image](https://github.com/user-attachments/assets/7427f96d-d173-45d6-9977-6604c19cd8c5)

### Your current environment (if you think it is necessary)

```text
The output of `python collect_env.py`
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by fangbaolei** [comment]
![Image](https://github.com/user-attachments/assets/8f478cf5-5f06-420c-90bd-403cafd42690)

**Comment by DarkLight1337** [comment]
It may be due to CUDA graph capture, can you try `--enforce-eager` to disable it?

**Comment by fangbaolei** [comment]
i sloved the first problem by pip install flashinfer-python==0.2.2 and --enforce-eager,but performance of version 0.8.3 still not as good as that of version 0.6.3.

**Comment by DarkLight1337** [comment]
If you use `--enforce-eager` then the performance may drop a bit since CUDA graph is supposed to speed up inference. Can you try other ways of reducing memory? For example, set `--max-num-seqs 256` to use the old V0 default

**Comment by Xerxes-cn** [comment]
The performance of version 0.8.3 is not as good as that of version 0.6.3.  Any progress? I have the same problem. @DarkLight1337

**Comment by DarkLight1337** [comment]
Could you elaborate? How did you run vLLM in these two versions and how did you measure the performance?

**Comment by Xerxes-cn** [comment]
> Could you elaborate? How did you run vLLM in these two versions and how did you measure the performance?

I downloaded vllm-openai:v0.8.3 and vllm-openai:v0.6.3 from the official 
start server 
0.6.3:   python3 -m vllm.entrypoints.openai.api_server  --host 0.0.0.0 --port 30001 --dtype float16 --distributed-executor-backend mp --trust-remote-code --tensor-parallel-size 1 --enable-chunked-prefill=False --model /path/to/model/qwen2-7b/

0.8.3: python3 -m vllm.entrypoints.openai.api_server  --host 0.0.0.0 --port 30001 --dtype float16 --distributed-executor-backend mp --trust-remote-code --tensor-parallel-size 1 --enable-chunked-prefill=False --model /path/to/model/qwen2-7b/ --no-enable-prefix-caching

I tested 44 concurrency , input 3600-3000, output 500-300, The data was sampled using a normal distribution

result:
0.6.3: 
![Image](https://github.com/user-attachments/assets/77290de3-775a-427d-aa81-c29e793c2474)

0.8.3:
![Image](https://github.com/user-attachments/assets/e4c31fd0-3fe9-4773-912d-e8bdc4bdce25)

It can be seen that whether it is TPOT, TTFT or TPS. they are worse than 0.6.3.

I use a private testing tool. The principle is equivalent to
```shell
python benchmark_serving.py  --dataset-path / --port 30001 --dataset-name random --ignore-eos  --num-prompts 440 --max-concurrency 44 --random-output-len 500 --random-input-len 3600--random-range-ratio 0.8 --trust-remote-code --model /path/to/model/qwen2-7b/
```
@DarkLight1337

**Comment by DarkLight1337** [comment]
Why did you disable prefix caching in 0.8.3?

**Comment by Xerxes-cn** [comment]
This is the data of version 0.8.3 V0. It looks the same as 0.6.3.
start cmd: VLLM_USE_V1=0 python3 -m vllm.entrypoints.openai.api_server  --host 0.0.0.0 --port 30001 --dtype float16 --distributed-executor-backend mp --trust-remote-code --tensor-parallel-size 1 --enable-chunked-prefill=False --model /path/to/model/qwen2-7b/
![Image](https://github.com/user-attachments/assets/e0029c84-6a8d-4e82-9092-7c10a4d9ed8f)

**Comment by Xerxes-cn** [comment]
> Why did you disable prefix caching in 0.8.3?
On the one hand, the data samples I used were highly repetitive, and on the other hand, our online hit rate was also very low, 5-10%. It is difficult to reproduce the data of a specified hit rate, so we tested it by turning off prefix_cache by default. @DarkLight1337

**Comment by DarkLight1337** [comment]
Ok, so is the issue solved now that prefix caching is enabled again?

**Comment by fangbaolei** [comment]
Since I only have an RTX 4090 24G device at hand, I have reproduced the previous issue (where version 0.8.5 performs worse than 0.6.3) on this device, and I am not using the --enforce-eager mode.  Test cmd as below：
  docker run --rm \
  --name Qwen2-7B-Instruct-awq \
  --runtime nvidia \
  --gpus all \
  -v /ai/zhiyi/models/:/models \
  -p 8000:8000 \
  --ipc=host \
  vllm-image:0.6.3.post1 \
  --served-model-name Qwen2-7B-Instruct-awq \
  --max-model-len 4096 \
  --trust-remote-code \
  --gpu-memory-utilization 0.85 --max-num-seqs 256 \
  --model /models/Qwen2-7B-Instruct-awq
test result:
![Image](https://github.com/user-attachments/assets/9d9e0844-137e-46c6-a503-27723eb43f20)

The table data shows that the GPU utilization for version 0.8.5 is lower then 0.6.3.

**Comment by fangbaolei** [comment]
> Is the command the same in both versions?

yes

**Comment by DarkLight1337** [comment]
cc @robertgshaw2-redhat
