### ISSUE TITLE
[Bug]: Cannot load  Qwen2.5-VL

### ISSUE THREAD

**Issue by furkanc** [vllm-project/vllm#16429]
We had loaded Qwen2.5-VL successfully nearly 20 days ago. We cannot load Qwen2.5-VL model, after restarting the environment. 

We suspect that V1 update broke something.

<details>

```text
Collecting environment information...
/opt/conda/lib/python3.11/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
PyTorch version: 2.5.1+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1061-gke-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB

Nvidia driver version: 535.161.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      46 bits physical, 48 bits virtual
CPU(s):                             48
On-line CPU(s) list:                0-47
Thread(s) per core:                 2
Core(s) per socket:                 24
Socket(s):                          1
NUMA node(s):                       1
Vendor ID:                          GenuineIntel
CPU family:                         6
Model:                              85
Model name:                         Intel(R) Xeon(R) CPU @ 2.20GHz
Stepping:                           7
CPU MHz:                            2200.180
BogoMIPS:                           4400.36
Hypervisor vendor:                  KVM
Virtualization type:                full
L1d cache:                          768 KiB
L1i cache:                          768 KiB
L2 cache:                           24 MiB
L3 cache:                           38.5 MiB
NUMA node0 CPU(s):                  0-47
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Retbleed:             Mitigation; Enhanced IBRS
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI Syscall hardening, KVM SW loop
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat avx512_vnni md_clear arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-cusparselt-cu12==0.6.2
[pip3] nvidia-ml-py==12.570.86
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] pyzmq==25.1.2
[pip3] torch==2.5.1
[pip3] torchaudio==2.5.1
[pip3] torchvision==0.20.1
[pip3] transformers==4.51.2
[pip3] triton==3.1.0
[conda] cuda-cccl                 12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-command-line-tools   12.1.0                        0    nvidia/label/cuda-12.1.0
[conda] cuda-compiler             12.1.0                        0    nvidia/label/cuda-12.1.0
[conda] cuda-cudart               12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-cudart-dev           12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-cudart-static        12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-cuobjdump            12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-cupti                12.1.62                       0    nvidia/label/cuda-12.1.0
[conda] cuda-cupti-static         12.1.62                       0    nvidia/label/cuda-12.1.0
[conda] cuda-cuxxfilt             12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-documentation        12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-driver-dev           12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-gdb                  12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-libraries            12.1.0                        0    nvidia/label/cuda-12.1.0
[conda] cuda-libraries-dev        12.1.0                        0    nvidia/label/cuda-12.1.0
[conda] cuda-libraries-static     12.1.0                        0    nvidia/label/cuda-12.1.0
[conda] cuda-nsight               12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-nsight-compute       12.1.0                        0    nvidia/label/cuda-12.1.0
[conda] cuda-nvcc                 12.1.66                       0    nvidia/label/cuda-12.1.0
[conda] cuda-nvdisasm             12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-nvml-dev             12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-nvprof               12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-nvprune              12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-nvrtc                12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-nvrtc-dev            12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-nvrtc-static         12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-nvtx                 12.1.66                       0    nvidia/label/cuda-12.1.0
[conda] cuda-nvvp                 12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-opencl               12.1.56                       0    nvidia/label/cuda-12.1.0
[conda] cuda-opencl-dev           12.1.56                       0    nvidia/label/cuda-12.1.0
[conda] cuda-profiler-api         12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-sanitizer-api        12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] cuda-toolkit              12.1.0                        0    nvidia/label/cuda-12.1.0
[conda] cuda-tools                12.1.0                        0    nvidia/label/cuda-12.1.0
[conda] cuda-visual-tools         12.1.0                        0    nvidia/label/cuda-12.1.0
[conda] gds-tools                 1.6.0.25                      0    nvidia/label/cuda-12.1.0
[conda] libcublas                 12.1.0.26                     0    nvidia/label/cuda-12.1.0
[conda] libcublas-dev             12.1.0.26                     0    nvidia/label/cuda-12.1.0
[conda] libcublas-static          12.1.0.26                     0    nvidia/label/cuda-12.1.0
[conda] libcufft                  11.0.2.4                      0    nvidia/label/cuda-12.1.0
[conda] libcufft-dev              11.0.2.4                      0    nvidia/label/cuda-12.1.0
[conda] libcufft-static           11.0.2.4                      0    nvidia/label/cuda-12.1.0
[conda] libcufile                 1.6.0.25                      0    nvidia/label/cuda-12.1.0
[conda] libcufile-dev             1.6.0.25                      0    nvidia/label/cuda-12.1.0
[conda] libcufile-static          1.6.0.25                      0    nvidia/label/cuda-12.1.0
[conda] libcurand                 10.3.2.56                     0    nvidia/label/cuda-12.1.0
[conda] libcurand-dev             10.3.2.56                     0    nvidia/label/cuda-12.1.0
[conda] libcurand-static          10.3.2.56                     0    nvidia/label/cuda-12.1.0
[conda] libcusolver               11.4.4.55                     0    nvidia/label/cuda-12.1.0
[conda] libcusolver-dev           11.4.4.55                     0    nvidia/label/cuda-12.1.0
[conda] libcusolver-static        11.4.4.55                     0    nvidia/label/cuda-12.1.0
[conda] libcusparse               12.0.2.55                     0    nvidia/label/cuda-12.1.0
[conda] libcusparse-dev           12.0.2.55                     0    nvidia/label/cuda-12.1.0
[conda] libcusparse-static        12.0.2.55                     0    nvidia/label/cuda-12.1.0
[conda] libnpp                    12.0.2.50                     0    nvidia/label/cuda-12.1.0
[conda] libnpp-dev                12.0.2.50                     0    nvidia/label/cuda-12.1.0
[conda] libnpp-static             12.0.2.50                     0    nvidia/label/cuda-12.1.0
[conda] libnvjitlink              12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] libnvjitlink-dev          12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] libnvjpeg                 12.1.0.39                     0    nvidia/label/cuda-12.1.0
[conda] libnvjpeg-dev             12.1.0.39                     0    nvidia/label/cuda-12.1.0
[conda] libnvjpeg-static          12.1.0.39                     0    nvidia/label/cuda-12.1.0
[conda] libnvvm-samples           12.1.55                       0    nvidia/label/cuda-12.1.0
[conda] nsight-compute            2023.1.0.15                   0    nvidia/label/cuda-12.1.0
[conda] numpy                     1.26.2                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
[conda] nvidia-cusparselt-cu12    0.6.2                    pypi_0    pypi
[conda] nvidia-ml-py              12.570.86                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
[conda] pyzmq                     25.1.2                   pypi_0    pypi
[conda] torch                     2.5.1                    pypi_0    pypi
[conda] torchaudio                2.5.1                    pypi_0    pypi
[conda] torchvision               0.20.1                   pypi_0    pypi
[conda] transformers              4.51.2                   pypi_0    pypi
[conda] triton                    3.1.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.7.3
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV12    NV12    NV12    0-47    0               N/A
GPU1    NV12     X      NV12    NV12    0-47    0               N/A
GPU2    NV12    NV12     X      NV12    0-47    0               N/A
GPU3    NV12    NV12    NV12     X      0-47    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NVIDIA_VISIBLE_DEVICES=all
NVIDIA_REQUIRE_CUDA=cuda>=12.1
NVIDIA_DRIVER_CAPABILITIES=compute,utility
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
NCCL_CUMEM_ENABLE=0
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY
```
</details>

### 🐛 Describe the bug

```python
import logging
import os
from typing import Dict, Optional

from fastapi import FastAPI
from starlette.requests import Request
from starlette.responses import StreamingResponse, JSONResponse
from vllm.engine.arg_utils import AsyncEngineArgs
from vllm.engine.async_llm_engine import AsyncLLMEngine
from vllm.entrypoints.chat_utils import load_chat_template
from vllm.entrypoints.openai.cli_args import make_arg_parser
from vllm.entrypoints.openai.protocol import (
    ChatCompletionRequest,
    ChatCompletionResponse,
    ErrorResponse,
)
from vllm.entrypoints.openai.serving_chat import OpenAIServingChat
from vllm.entrypoints.openai.serving_models import (BaseModelPath,
                                                    OpenAIServingModels)
from vllm.utils import FlexibleArgumentParser

logger = logging.getLogger("ray.serve")

app = FastAPI()

os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"
os.environ["VLLM_USE_V1"] = "0"

class VLLMDeployment:
    def __init__(
            self,
            engine_args: AsyncEngineArgs,
            response_role: str,
            chat_template: Optional[str] = None,
    ):
        logger.info(f"Starting with engine args: {engine_args}")
        self.openai_serving_chat = None
        self.engine_args = engine_args
        self.response_role = response_role
        self.chat_template = chat_template
        self.engine = AsyncLLMEngine.from_engine_args(engine_args)

    async def create_chat_completion(
            self, request: ChatCompletionRequest, raw_request: Request
    ):
        """OpenAI-compatible HTTP endpoint.

        API reference:
            - https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html
        """
        if not self.openai_serving_chat:
            model_config = await self.engine.get_model_config()
            if self.engine_args.served_model_name is not None:
                served_model_names = OpenAIServingModels(self.engine_args.served_model_name)
            else:
                served_model_names = [self.engine_args.model]

            base_model_paths = [
                BaseModelPath(name=name, model_path=self.engine_args.model)
                for name in served_model_names
            ]

            resolved_chat_template = load_chat_template(self.chat_template)
            logger.info("Using supplied chat template:\n%s", resolved_chat_template)

            openai_serving_models = OpenAIServingModels(
                engine_client=self.engine,
                model_config=model_config,
                base_model_paths=base_model_paths
            )
            self.openai_serving_chat = OpenAIServingChat(
                self.engine,
                model_config,
                models=openai_serving_models,
                response_role=self.response_role,
                request_logger=None,
                chat_template=self.chat_template,
                chat_template_content_format="auto")

        logger.info(f"Request: {request}")
        generator = await self.openai_serving_chat.create_chat_completion(
            request, raw_request
        )
        if isinstance(generator, ErrorResponse):
            return JSONResponse(
                content=generator.model_dump(), status_code=generator.code
            )
        if request.stream:
            return StreamingResponse(content=generator, media_type="text/event-stream")
        else:
            assert isinstance(generator, ChatCompletionResponse)
            return JSONResponse(content=generator.model_dump())


def parse_vllm_args(cli_args: Dict[str, str]):
    """Parses vLLM args based on CLI inputs.

    Currently uses argparse because vLLM doesn't expose Python models for all of the
    config options we want to support.
    """
    parser = FlexibleArgumentParser(description="vLLM CLI")
    parser = make_arg_parser(parser)
    arg_strings = []
    for key, value in cli_args.items():
        arg_strings.extend([f"--{key}", str(value)])
    logger.info(arg_strings)
    parsed_args = parser.parse_args(args=arg_strings)
    return parsed_args


def build_app(cli_args: Dict[str, str]):
    """Builds the Serve app based on CLI arguments.

    See https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#command-line-arguments-for-the-server
    for the complete set of arguments.

    Supported engine arguments: https://docs.vllm.ai/en/latest/models/engine_args.html.
    """  # noqa: E501
    parsed_args = parse_vllm_args(cli_args)
    engine_args = AsyncEngineArgs.from_cli_args(parsed_args)
    engine_args.worker_use_ray = False
    engine_args.trust_remote_code = True
    engine_args.enforce_eager = True
    engine_args.tensor_parallel_size = 4
    engine_args.dtype="bfloat16"
    engine_args.model="Qwen/Qwen2.5-VL-72B-Instruct"

    return VLLMDeployment(
        engine_args,
        parsed_args.response_role,
        parsed_args.chat_template,
    )


def get_vllm_env_vars(prefix="VLLM_") -> Dict[str, str]:
    """Extracts vLLM-related environment variables dynamically."""
    vllm_args = {}
    for key, value in os.environ.items():
        if key.startswith(prefix):
            cli_key = key[len(prefix):].lower().replace("_", "-")
            vllm_args[cli_key] = value
    return vllm_args


model = build_app(get_vllm_env_vars())

```

We use versions below. (We have tried also with latest version.)
```text
vllm==0.7.3
transformers==4.49.0
```

We're getting error like below

```text
KeyError                                  Traceback (most recent call last)
Cell In[1], line 147
    143             vllm_args[cli_key] = value
    144     return vllm_args
--> 147 model = build_app(get_vllm_env_vars())

Cell In[1], line 128, in build_app(cli_args)
    125 engine_args.dtype="bfloat16"
    126 engine_args.model="Qwen/Qwen2.5-VL-72B-Instruct"
--> 128 return VLLMDeployment(
    129     engine_args,
    130     parsed_args.response_role,
    131     parsed_args.chat_template,
    132 )

Cell In[1], line 41, in VLLMDeployment.__init__(self, engine_args, response_role, chat_template)
     39 self.response_role = response_role
     40 self.chat_template = chat_template
---> 41 self.engine = AsyncLLMEngine.from_engine_args(engine_args)

File /opt/conda/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py:644, in AsyncLLMEngine.from_engine_args(cls, engine_args, engine_config, start_engine_loop, usage_context, stat_loggers)
    641 executor_class = cls._get_executor_cls(engine_config)
    643 # Create the async LLM engine.
--> 644 engine = cls(
    645     vllm_config=engine_config,
    646     executor_class=executor_class,
    647     log_requests=not engine_args.disable_log_requests,
    648     log_stats=not engine_args.disable_log_stats,
    649     start_engine_loop=start_engine_loop,
    650     usage_context=usage_context,
    651     stat_loggers=stat_loggers,
    652 )
    653 return engine

File /opt/conda/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py:594, in AsyncLLMEngine.__init__(self, log_requests, start_engine_loop, *args, **kwargs)
    588 def __init__(self,
    589              *args,
    590              log_requests: bool = True,
    591              start_engine_loop: bool = True,
    592              **kwargs) -> None:
    593     self.log_requests = log_requests
--> 594     self.engine = self._engine_class(*args, **kwargs)
    596     # This ensures quick processing of request outputs
    597     # so the append to asyncio queues is not delayed,
    598     # especially for multi-step.
    599     self.use_process_request_outputs_callback = (
    600         self.engine.model_config.use_async_output_proc)

File /opt/conda/lib/python3.11/site-packages/vllm/engine/async_llm_engine.py:267, in _AsyncLLMEngine.__init__(self, *args, **kwargs)
    266 def __init__(self, *args, **kwargs):
--> 267     super().__init__(*args, **kwargs)

File /opt/conda/lib/python3.11/site-packages/vllm/engine/llm_engine.py:276, in LLMEngine.__init__(self, vllm_config, executor_class, log_stats, usage_context, stat_loggers, input_registry, mm_registry, use_cached_outputs)
    273 self.model_executor = executor_class(vllm_config=vllm_config, )
    275 if self.model_config.runner_type != "pooling":
--> 276     self._initialize_kv_caches()
    278 # If usage stat is enabled, collect relevant info.
    279 if is_usage_stats_enabled():

File /opt/conda/lib/python3.11/site-packages/vllm/engine/llm_engine.py:421, in LLMEngine._initialize_kv_caches(self)
    414 """Initialize the KV cache in the worker(s).
    415 
    416 The workers will determine the number of blocks in both the GPU cache
    417 and the swap CPU cache.
    418 """
    419 start = time.time()
    420 num_gpu_blocks, num_cpu_blocks = (
--> 421     self.model_executor.determine_num_available_blocks())
    423 if self.cache_config.num_gpu_blocks_override is not None:
    424     num_gpu_blocks_override = self.cache_config.num_gpu_blocks_override

File /opt/conda/lib/python3.11/site-packages/vllm/executor/executor_base.py:102, in ExecutorBase.determine_num_available_blocks(self)
     89 def determine_num_available_blocks(self) -> Tuple[int, int]:
     90     """Determine the number of available blocks for the GPU KV cache and
     91     swappable CPU KV cache.
     92 
   (...)
    100     appended to.
    101     """
--> 102     results = self.collective_rpc("determine_num_available_blocks")
    103     a = min([r[0] for r in results])
    104     b = min([r[1] for r in results])

File /opt/conda/lib/python3.11/site-packages/vllm/executor/executor_base.py:316, in DistributedExecutorBase.collective_rpc(self, method, timeout, args, kwargs)
    311 def collective_rpc(self,
    312                    method: Union[str, Callable],
    313                    timeout: Optional[float] = None,
    314                    args: Tuple = (),
    315                    kwargs: Optional[Dict] = None) -> List[Any]:
--> 316     return self._run_workers(method, *args, **(kwargs or {}))

File /opt/conda/lib/python3.11/site-packages/vllm/executor/mp_distributed_executor.py:185, in MultiprocessingDistributedExecutor._run_workers(***failed resolving arguments***)
    179 # Start all remote workers first.
    180 worker_outputs = [
    181     worker.execute_method(sent_method, *args, **kwargs)
    182     for worker in self.workers
    183 ]
--> 185 driver_worker_output = run_method(self.driver_worker, sent_method,
    186                                   args, kwargs)
    188 # Get the results of the workers.
    189 return [driver_worker_output
    190         ] + [output.get() for output in worker_outputs]

File /opt/conda/lib/python3.11/site-packages/vllm/utils.py:2196, in run_method(obj, method, args, kwargs)
   2194 else:
   2195     func = partial(method, obj)  # type: ignore
-> 2196 return func(*args, **kwargs)

File /opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py:116, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    113 @functools.wraps(func)
    114 def decorate_context(*args, **kwargs):
    115     with ctx_factory():
--> 116         return func(*args, **kwargs)

File /opt/conda/lib/python3.11/site-packages/vllm/worker/worker.py:229, in Worker.determine_num_available_blocks(self)
    224 # Execute a forward pass with dummy inputs to profile the memory usage
    225 # of the model.
    226 with memory_profiling(
    227         self.baseline_snapshot,
    228         weights_memory=self.model_runner.model_memory_usage) as result:
--> 229     self.model_runner.profile_run()
    231 self._assert_memory_footprint_increased_during_profiling()
    233 memory_for_current_instance = total_gpu_memory * \
    234     self.cache_config.gpu_memory_utilization

File /opt/conda/lib/python3.11/site-packages/torch/utils/_contextlib.py:116, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    113 @functools.wraps(func)
    114 def decorate_context(*args, **kwargs):
    115     with ctx_factory():
--> 116         return func(*args, **kwargs)

File /opt/conda/lib/python3.11/site-packages/vllm/worker/model_runner.py:1235, in GPUModelRunnerBase.profile_run(self)
   1232 max_num_batched_tokens = \
   1233     self.scheduler_config.max_num_batched_tokens
   1234 max_num_seqs = self.scheduler_config.max_num_seqs
-> 1235 self._dummy_run(max_num_batched_tokens, max_num_seqs)

File /opt/conda/lib/python3.11/site-packages/vllm/worker/model_runner.py:1300, in GPUModelRunnerBase._dummy_run(self, max_num_batched_tokens, max_num_seqs)
   1295 seq_len = (max_num_batched_tokens // max_num_seqs +
   1296            (group_id < max_num_batched_tokens % max_num_seqs))
   1297 batch_size += seq_len
   1299 dummy_data = self.input_registry \
-> 1300     .dummy_data_for_profiling(self.model_config,
   1301                             seq_len,
   1302                             self.mm_registry)
   1304 seq = SequenceGroupMetadata(
   1305     request_id=str(group_id),
   1306     is_prompt=True,
   (...)
   1314     multi_modal_placeholders,
   1315 )
   1316 seqs.append(seq)

File /opt/conda/lib/python3.11/site-packages/vllm/inputs/registry.py:336, in InputRegistry.dummy_data_for_profiling(self, model_config, seq_len, mm_registry, is_encoder_data)
    334     processor = mm_registry.create_processor(model_config, tokenizer)
    335     profiler = MultiModalProfiler(processor)
--> 336     dummy_data = profiler.get_dummy_data(
    337         seq_len, is_encoder_data=is_encoder_data)
    338 else:
    339     model_cls, _ = get_model_architecture(model_config)

File /opt/conda/lib/python3.11/site-packages/vllm/multimodal/profiling.py:168, in MultiModalProfiler.get_dummy_data(self, seq_len, is_encoder_data)
    161 if mm_counts.keys() != mm_max_tokens_per_item.keys():
    162     raise AssertionError(
    163         "The keys returned by `get_supported_mm_limits`"
    164         f"({set(mm_counts.keys())}) should be the same as those "
    165         "returned by `get_mm_max_tokens_per_item` "
    166         f"({set(mm_max_tokens_per_item.keys())})")
--> 168 mm_inputs = self._get_dummy_mm_inputs(seq_len, mm_counts)
    169 prompt_token_ids = mm_inputs["prompt_token_ids"]
    170 placeholders_by_modality = mm_inputs["mm_placeholders"]

File /opt/conda/lib/python3.11/site-packages/vllm/multimodal/profiling.py:141, in MultiModalProfiler._get_dummy_mm_inputs(self, seq_len, mm_counts)
    137 factory = self.dummy_inputs
    138 processor_inputs = factory.get_dummy_processor_inputs(
    139     seq_len, mm_counts)
--> 141 return self.processor.apply(
    142     prompt=processor_inputs.prompt_text,
    143     mm_data=processor_inputs.mm_data,
    144     hf_processor_mm_kwargs=processor_inputs.hf_processor_mm_kwargs,
    145 )

File /opt/conda/lib/python3.11/site-packages/vllm/multimodal/processing.py:1245, in BaseMultiModalProcessor.apply(self, prompt, mm_data, hf_processor_mm_kwargs)
   1233     mm_hashes = None
   1235 (
   1236     prompt_ids,
   1237     mm_kwargs,
   (...)
   1242     hf_processor_mm_kwargs,
   1243 )
-> 1245 unbound_prompt_repls = self._get_prompt_replacements(
   1246     mm_items,
   1247     hf_processor_mm_kwargs,
   1248     mm_kwargs,
   1249 )
   1250 mm_prompt_repls = self._bind_and_group_repls(unbound_prompt_repls)
   1252 mm_item_counts = mm_items.get_all_counts()

File /opt/conda/lib/python3.11/site-packages/vllm/model_executor/models/qwen2_vl.py:1004, in Qwen2VLMultiModalProcessor._get_prompt_replacements(self, mm_items, hf_processor_mm_kwargs, out_mm_kwargs)
   1000 tokenizer = self.info.get_tokenizer()
   1001 vocab = tokenizer.get_vocab()
   1003 placeholder = {
-> 1004     "image": vocab[hf_processor.image_token],
   1005     "video": vocab[hf_processor.video_token],
   1006 }
   1008 merge_length = image_processor.merge_size**2
   1010 def get_replacement_qwen2vl(item_idx: int, modality: str):

KeyError: '<|image_pad|>'
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
I see you are still on vLLM 0.7.3. V1 should not be enabled by default in that version.

**Comment by DarkLight1337** [comment]
Also, I suggest re-downloading the model repo from HF Hub in case their tokenizer definition had to be updated

**Comment by furkanc** [comment]
Hello @DarkLight1337 , I've also tried it with `vllm==0.8.4`. Same error occurs.

 ```text
:job_id:01000000
:actor_name:ServeReplica:default:VLLMDeployment
INFO 04-15 15:17:51 [__init__.py:239] Automatically detected platform cuda.
INFO 04-15 15:18:00 [config.py:689] This model supports multiple tasks: {'generate', 'score', 'embed', 'classify', 'reward'}. Defaulting to 'generate'.
INFO 04-15 15:18:00 [arg_utils.py:1742] Engine in background thread is experimental on VLLM_USE_V1=1. Falling back to V0 Engine.
WARNING 04-15 15:18:00 [arg_utils.py:1603] The model has a long context length (128000). This may causeOOM during the initial memory profiling phase, or result in low performance due to small KV cache size. Consider setting --max-model-len to a smaller value.
INFO 04-15 15:18:00 [config.py:1713] Defaulting to use ray for distributed inference
INFO 04-15 15:18:00 [llm_engine.py:243] Initializing a V0 LLM engine (v0.8.4) with config: model='Qwen/Qwen2.5-VL-72B-Instruct', speculative_config=None, tokenizer='facebook/opt-125m', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=128000, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=2, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=Qwen/Qwen2.5-VL-72B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=False, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=False, 
INFO 04-15 15:18:05 [ray_utils.py:288] Ray is already initialized. Skipping Ray initialization.
INFO 04-15 15:18:05 [ray_utils.py:335] No current placement group found. Creating a new placement group.
INFO 04-15 15:18:06 [ray_distributed_executor.py:176] use_ray_spmd_worker: False
INFO 04-15 15:19:44 [ray_distributed_executor.py:352] non_carry_over_env_vars from config: set()
INFO 04-15 15:19:44 [ray_distributed_executor.py:354] Copying the following environment variables to workers: ['LD_LIBRARY_PATH', 'VLLM_USE_V1']
INFO 04-15 15:19:44 [ray_distributed_executor.py:357] If certain env vars should NOT be copied to workers, add them to /home/ray/.config/vllm/ray_non_carry_over_env_vars.json file
INFO 04-15 15:19:45 [cuda.py:292] Using Flash Attention backend.
INFO 04-15 15:19:46 [utils.py:993] Found nccl from library libnccl.so.2
INFO 04-15 15:19:46 [pynccl.py:69] vLLM is using nccl==2.21.5
INFO 04-15 15:19:46 [parallel_state.py:959] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 0
INFO 04-15 15:19:46 [model_runner.py:1110] Starting to load model Qwen/Qwen2.5-VL-72B-Instruct...
WARNING 04-15 15:19:46 [vision.py:93] Current `vllm-flash-attn` has a bug inside vision module, so we use xformers backend instead. You can run `pip install flash-attn` to use flash-attention backend.
INFO 04-15 15:19:52 [config.py:3466] cudagraph sizes specified by model runner [] is overridden by config []
INFO 04-15 15:19:53 [weight_utils.py:265] Using model weights format ['*.safetensors']
INFO 04-15 15:25:43 [weight_utils.py:281] Time spent downloading weights for Qwen/Qwen2.5-VL-72B-Instruct: 350.149512 seconds
INFO 04-15 15:25:55 [loader.py:458] Loading weights took 11.96 seconds
INFO 04-15 15:25:55 [model_runner.py:1146] Model loading took 69.1485 GiB and 369.142241 seconds
ERROR 04-15 15:27:16 [worker_base.py:620] Error executing method 'determine_num_available_blocks'. This might cause deadlock in distributed execution.
ERROR 04-15 15:27:16 [worker_base.py:620] Traceback (most recent call last):
ERROR 04-15 15:27:16 [worker_base.py:620]   File "/tmp/ray/session_2025-04-15_15-14-22_733980_1/runtime_resources/pip/362d854cecff8242af64cd73202a008c457624f4/virtualenv/lib/python3.11/site-packages/vllm/worker/worker_base.py", line 612, in execute_method
ERROR 04-15 15:27:16 [worker_base.py:620]     return run_method(self, method, args, kwargs)
ERROR 04-15 15:27:16 [worker_base.py:620]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-15 15:27:16 [worker_base.py:620]   File "/tmp/ray/session_2025-04-15_15-14-22_733980_1/runtime_resources/pip/362d854cecff8242af64cd73202a008c457624f4/virtualenv/lib/python3.11/site-packages/vllm/utils.py", line 2378, in run_method
ERROR 04-15 15:27:16 [worker_base.py:620]     return func(*args, **kwargs)
ERROR 04-15 15:27:16 [worker_base.py:620]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 04-15 15:27:16 [worker_base.py:620]   File "/tmp/ray/session_2025-04-15_15-14-22_733980_1/runtime_resources/pip/362d854cecff8242af64cd73202a008c457624f4/virtualenv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 04-15 15:27:16 [worker_base.py:620]     return func(*args, **kwargs)
ERROR 04-15 15:27:16 [worker_base.py:620]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 04-15 15:27:16 [worker_base.py:620]   File "/tmp/ray/session_2025-04-15_15-14-22_733980_1/runtime_resources/pip/362d854cecff8242af64cd73202a008c457624f4/virtualenv/lib/python3.11/site-packages/vllm/worker/worker.py", line 229, in determine_num_available_blocks
ERROR 04-15 15:27:16 [worker_base.py:620]     self.model_runner.profile_run()
ERROR 04-15 15:27:16 [worker_base.py:620]   File "/tmp/ray/session_2025-04-15_15-14-22_733980_1/runtime_resources/pip/362d854cecff8242af64cd73202a008c457624f4/virtualenv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 04-15 15:27:16 [worker_base.py:620]     return func(*args, **kwargs)
ERROR 04-15 15:27:16 [worker_base.py:620]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 04-15 15:27:16 [worker_base.py:620]   File "/tmp/ray/session_2025-04-15_15-14-22_733980_1/runtime_resources/pip/362d854cecff8242af64cd73202a008c457624f4/virtualenv/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1243, in profile_run
ERROR 04-15 15:27:16 [worker_base.py:620]     self._dummy_run(max_num_batched_tokens, max_num_seqs)
ERROR 04-15 15:27:16 [worker_base.py:620]   File "/tmp/ray/session_2025-04-15_15-14-22_733980_1/runtime_resources/pip/362d854cecff8242af64cd73202a008c457624f4/virtualenv/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 1302, in _dummy_run
ERROR 04-15 15:27:16 [worker_base.py:620]     max_mm_tokens = self.mm_registry.get_max_multimodal_tokens(
ERROR 04-15 15:27:16 [worker_base.py:620]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-15 15:27:16 [worker_base.py:620]   File "/tmp/ray/session_2025-04-15_15-14-22_733980_1/runtime_resources/pip/362d854cecff8242af64cd73202a008c457624f4/virtualenv/lib/python3.11/site-packages/vllm/multimodal/registry.py", line 332, in get_max_multimodal_tokens
ERROR 04-15 15:27:16 [worker_base.py:620]     return sum(self.get_max_tokens_by_modality(model_config).values())
ERROR 04-15 15:27:16 [worker_base.py:620]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-15 15:27:16 [worker_base.py:620]   File "/tmp/ray/session_2025-04-15_15-14-22_733980_1/runtime_resources/pip/362d854cecff8242af64cd73202a008c457624f4/virtualenv/lib/python3.11/site-packages/vllm/multimodal/registry.py", line 319, in get_max_tokens_by_modality
ERROR 04-15 15:27:16 [worker_base.py:620]     self.get_max_tokens_per_item_by_modality(model_config).items()
ERROR 04-15 15:27:16 [worker_base.py:620]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-15 15:27:16 [worker_base.py:620]   File "/tmp/ray/session_2025-04-15_15-14-22_733980_1/runtime_resources/pip/362d854cecff8242af64cd73202a008c457624f4/virtualenv/lib/python3.11/site-packages/vllm/multimodal/registry.py", line 266, in get_max_tokens_per_item_by_modality
ERROR 04-15 15:27:16 [worker_base.py:620]     return profiler.get_mm_max_tokens(
ERROR 04-15 15:27:16 [worker_base.py:620]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-15 15:27:16 [worker_base.py:620]   File "/tmp/ray/session_2025-04-15_15-14-22_733980_1/runtime_resources/pip/362d854cecff8242af64cd73202a008c457624f4/virtualenv/lib/python3.11/site-packages/vllm/multimodal/profiling.py", line 272, in get_mm_max_tokens
ERROR 04-15 15:27:16 [worker_base.py:620]     mm_inputs = self._get_dummy_mm_inputs(seq_len, mm_counts)
ERROR 04-15 15:27:16 [worker_base.py:620]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-15 15:27:16 [worker_base.py:620]   File "/tmp/ray/session_2025-04-15_15-14-22_733980_1/runtime_resources/pip/362d854cecff8242af64cd73202a008c457624f4/virtualenv/lib/python3.11/site-packages/vllm/multimodal/profiling.py", line 179, in _get_dummy_mm_inputs
ERROR 04-15 15:27:16 [worker_base.py:620]     return self.processor.apply(
ERROR 04-15 15:27:16 [worker_base.py:620]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 04-15 15:27:16 [worker_base.py:620]   File "/tmp/ray/session_2025-04-15_15-14-22_733980_1/runtime_resources/pip/362d854cecff8242af64cd73202a008c457624f4/virtualenv/lib/python3.11/site-packages/vllm/multimodal/processing.py", line 1620, in apply
ERROR 04-15 15:27:16 [worker_base.py:620]     unbound_prompt_updates = self._get_prompt_updates(
ERROR 04-15 15:27:16 [worker_base.py:620]                              ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-15 15:27:16 [worker_base.py:620]   File "/tmp/ray/session_2025-04-15_15-14-22_733980_1/runtime_resources/pip/362d854cecff8242af64cd73202a008c457624f4/virtualenv/lib/python3.11/site-packages/vllm/model_executor/models/qwen2_vl.py", line 1037, in _get_prompt_updates
ERROR 04-15 15:27:16 [worker_base.py:620]     "image": vocab[hf_processor.image_token],
ERROR 04-15 15:27:16 [worker_base.py:620]              ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-15 15:27:16 [worker_base.py:620] KeyError: '<|image_pad|>'
```

**Comment by DarkLight1337** [comment]
> Also, I suggest re-downloading the model repo from HF Hub in case their tokenizer config had to be updated with respect to latest transformers release

Have you tried this?

If it doesn't solve the problem, can you print the output of `AutoTokenizer.from_pretrained(model_id)`?

**Comment by furkanc** [comment]
Yes, I have tried restarting ray nodes, removing downloaded models, etc. several times, but it doesn't work. 

Here is the output of `AutoTokenizer.from_pretrained(model_id)`

 ```text
Qwen2TokenizerFast(name_or_path='Qwen/Qwen2.5-VL-72B-Instruct', vocab_size=151643, model_max_length=131072, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'eos_token': '<|im_end|>', 'pad_token': '<|endoftext|>', 'additional_special_tokens': ['<|im_start|>', '<|im_end|>', '<|object_ref_start|>', '<|object_ref_end|>', '<|box_start|>', '<|box_end|>', '<|quad_start|>', '<|quad_end|>', '<|vision_start|>', '<|vision_end|>', '<|vision_pad|>', '<|image_pad|>', '<|video_pad|>']}, clean_up_tokenization_spaces=False, added_tokens_decoder={
        151643: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151644: AddedToken("<|im_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151645: AddedToken("<|im_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151646: AddedToken("<|object_ref_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151647: AddedToken("<|object_ref_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151648: AddedToken("<|box_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151649: AddedToken("<|box_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151650: AddedToken("<|quad_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151651: AddedToken("<|quad_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151652: AddedToken("<|vision_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151653: AddedToken("<|vision_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151654: AddedToken("<|vision_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151655: AddedToken("<|image_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151656: AddedToken("<|video_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151657: AddedToken("<tool_call>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
        151658: AddedToken("</tool_call>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
        151659: AddedToken("<|fim_prefix|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
        151660: AddedToken("<|fim_middle|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
        151661: AddedToken("<|fim_suffix|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
        151662: AddedToken("<|fim_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
        151663: AddedToken("<|repo_name|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
        151664: AddedToken("<|file_sep|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
}
)
 ```

**Comment by DarkLight1337** [comment]
That is quite odd - `<|image_pad|>` is clearly in the tokenizer. Hmm... how about `AutoProcessor.from_pretrained(model_id).tokenizer`?

**Comment by furkanc** [comment]
Output for `AutoProcessor.from_pretrained(model_id)._tokenizer`

 ```text
Tokenizer(version="1.0", truncation=None, padding=None, added_tokens=[{"id":151643, "content":"<|endoftext|>", "single_word":False, "lstrip":False, "rstrip":False, ...}, {"id":151644, "content":"<|im_start|>", "single_word":False, "lstrip":False, "rstrip":False, ...}, {"id":151645, "content":"<|im_end|>", "single_word":False, "lstrip":False, "rstrip":False, ...}, {"id":151646, "content":"<|object_ref_start|>", "single_word":False, "lstrip":False, "rstrip":False, ...}, {"id":151647, "content":"<|object_ref_end|>", "single_word":False, "lstrip":False, "rstrip":False, ...}, ...], normalizer=NFC(), pre_tokenizer=Sequence(pretokenizers=[Split(pattern=Regex("(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\r\n\p{L}\p{N}]?\p{L}+|\p{N}| ?[^\s\p{L}\p{N}]+[\r\n]*|\s*[\r\n]+|\s+..."), behavior=Isolated, invert=False), ByteLevel(add_prefix_space=False, trim_offsets=False, use_regex=False)]), post_processor=ByteLevel(add_prefix_space=False, trim_offsets=False, use_regex=False), decoder=ByteLevel(add_prefix_space=False, trim_offsets=False, use_regex=False), model=BPE(dropout=None, unk_token=None, continuing_subword_prefix="", end_of_word_suffix="", fuse_unk=False, byte_fallback=False, ignore_merges=False, vocab={"!":0, """:1, "#":2, "$":3, "%":4, ...}, merges=[("Ġ", "Ġ"), ("ĠĠ", "ĠĠ"), ("i", "n"), ("Ġ", "t"), ("ĠĠĠĠ", "ĠĠĠĠ"), ...]))
```

**Comment by DarkLight1337** [comment]
Oh, oops I thought only the individual entries are truncated. @furkanc can you see `"<|image_pad|>"` in the processor's tokenizer?

**Comment by furkanc** [comment]
Yes, I can see the`<|image_pad|>` in the processor's tokenizer. See the result below

 ```text
Qwen2TokenizerFast(name_or_path='Qwen/Qwen2.5-VL-72B-Instruct', vocab_size=151643, model_max_length=131072, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'eos_token': '<|im_end|>', 'pad_token': '<|endoftext|>', 'additional_special_tokens': ['<|im_start|>', '<|im_end|>', '<|object_ref_start|>', '<|object_ref_end|>', '<|box_start|>', '<|box_end|>', '<|quad_start|>', '<|quad_end|>', '<|vision_start|>', '<|vision_end|>', '<|vision_pad|>', '<|image_pad|>', '<|video_pad|>']}, clean_up_tokenization_spaces=False, added_tokens_decoder={
        151643: AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151644: AddedToken("<|im_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151645: AddedToken("<|im_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151646: AddedToken("<|object_ref_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151647: AddedToken("<|object_ref_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151648: AddedToken("<|box_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151649: AddedToken("<|box_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151650: AddedToken("<|quad_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151651: AddedToken("<|quad_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151652: AddedToken("<|vision_start|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151653: AddedToken("<|vision_end|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151654: AddedToken("<|vision_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151655: AddedToken("<|image_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151656: AddedToken("<|video_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
        151657: AddedToken("<tool_call>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
        151658: AddedToken("</tool_call>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
        151659: AddedToken("<|fim_prefix|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
        151660: AddedToken("<|fim_middle|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
        151661: AddedToken("<|fim_suffix|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
        151662: AddedToken("<|fim_pad|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
        151663: AddedToken("<|repo_name|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
        151664: AddedToken("<|file_sep|>", rstrip=False, lstrip=False, single_word=False, normalized=False, special=False),
}
)
 ```

**Comment by DarkLight1337** [comment]
In your deployment script, do you get the same issue if you set `VLLM_USE_V1=1` instead of `VLLM_USE_V1=0`?

**Comment by furkanc** [comment]
I think it is trying to use V1 but it says following

`INFO 04-15 15:18:00 [arg_utils.py:1742] Engine in background thread is experimental on VLLM_USE_V1=1. Falling back to V0 Engine.`

**Comment by DarkLight1337** [comment]
I can reproduce this locally. Let me spend some time trying different things to fix it...

**Comment by DarkLight1337** [comment]
Ok I found the problem. You need to set `engine_args.tokenizer`. A better way would be to put the model name in `cli_args` so it's set automatically.

**Comment by furkanc** [comment]
Thanks a lot @DarkLight1337 !  Let me try with the tokenizer also.

**Comment by furkanc** [comment]
Hello @DarkLight1337 , did you try this with `v0.7.3` or `v0.8.4`. Could you please share the parameters ?

**Comment by DarkLight1337** [comment]
I used v0.8.4

**Comment by furkanc** [comment]
Ahh, yes it's solved with `tensor-parallel-size`. I've different environments and I had tried on multi-node one with `pipeline-parallel-size` and there is an another issue. Thanks again.

I'm wondering how, in version 0.7.3, an existing deployment stopped working after a restart even though I didn’t make any changes. I saw some feature flags related to V1—do these affect the logic in V0 as well?

**Comment by DarkLight1337** [comment]
There have been some changes related to how the processor's tokenizer was loaded in recent code. It's applicable to both V0 and V1.

**Comment by DarkLight1337** [comment]
cc @LucasWilkinson maybe we need to add a `.contiguous` call?

**Comment by furkanc** [comment]
Hello, Do you have any updates on this ?  Because of this we cannot serve our deployments on clusters that we have to use --pipeline-parallel-size

**Comment by DarkLight1337** [comment]
Can you try https://github.com/vllm-project/vllm/pull/16907?
