### ISSUE TITLE
[Bug]: Severe OOM in 0.8.3 （ok in 0.7.2）

### ISSUE THREAD

**Issue by aabbccddwasd** [vllm-project/vllm#16551]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
INFO 04-13 18:08:28 [__init__.py:239] Automatically detected platform cuda.
Collecting environment information...
PyTorch version: 2.6.0+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.12.8 | packaged by Anaconda, Inc. | (main, Dec 11 2024, 16:31:09) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-136-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.4.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti
GPU 3: NVIDIA GeForce RTX 2080 Ti
GPU 4: NVIDIA GeForce RTX 2080 Ti
GPU 5: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 550.144.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        46 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               56
On-line CPU(s) list:                  0-55
Vendor ID:                            GenuineIntel
Model name:                           Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
CPU family:                           6
Model:                                79
Thread(s) per core:                   2
Core(s) per socket:                   14
Socket(s):                            2
Stepping:                             1
CPU max MHz:                          3300.0000
CPU min MHz:                          1200.0000
BogoMIPS:                             4799.99
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
Virtualization:                       VT-x
L1d cache:                            896 KiB (28 instances)
L1i cache:                            896 KiB (28 instances)
L2 cache:                             7 MiB (28 instances)
L3 cache:                             70 MiB (2 instances)
NUMA node(s):                         2
NUMA node0 CPU(s):                    0-13,28-41
NUMA node1 CPU(s):                    14-27,42-55
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          KVM: Mitigation: VMX disabled
Vulnerability L1tf:                   Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:                    Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:               Mitigation; PTI
Vulnerability Mmio stale data:        Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP conditional; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Mitigation; Clear CPU buffers; SMT vulnerable

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-cusparselt-cu12==0.6.2
[pip3] nvidia-ml-py==12.570.86
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] onnxruntime==1.20.1
[pip3] pyzmq==26.2.0
[pip3] rapidocr-onnxruntime==1.3.24
[pip3] torch==2.6.0
[pip3] torchaudio==2.6.0
[pip3] torchvision==0.21.0
[pip3] transformers==4.51.2
[pip3] triton==3.2.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
[conda] nvidia-ml-py              12.570.86                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
[conda] pyzmq                     26.2.0                   pypi_0    pypi
[conda] torch                     2.6.0                    pypi_0    pypi
[conda] torchaudio                2.6.0                    pypi_0    pypi
[conda] torchvision               0.21.0                   pypi_0    pypi
[conda] transformers              4.51.2                   pypi_0    pypi
[conda] triton                    3.2.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.8.3
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV2	SYS	SYS	SYS	SYS	0-13,28-41	0		N/A
GPU1	NV2	 X 	SYS	SYS	SYS	SYS	0-13,28-41	0		N/A
GPU2	SYS	SYS	 X 	NV2	PHB	PHB	14-27,42-55	1		N/A
GPU3	SYS	SYS	NV2	 X 	PHB	PHB	14-27,42-55	1		N/A
GPU4	SYS	SYS	PHB	PHB	 X 	NV2	14-27,42-55	1		N/A
GPU5	SYS	SYS	PHB	PHB	NV2	 X 	14-27,42-55	1		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

LD_LIBRARY_PATH=:/usr/local/cuda-12.4/lib64
NCCL_CUMEM_ENABLE=0
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY
```

</details>

### 🐛 Describe the bug

I used to serve Qwen-QwQ-32b, Qwen2.5-vl-32b-awq and qwen2.5-vl-7b in vllm 0.7.2，both of them can load successfully. when I upgraded vllm to 0.8.3 I found only QwQ can load successfully and qwen2.5-vl all go OOM.even after I reduced max-model-len, for example for the 7b model, I reduced max-model-len from 26000 to 16384, still OOM. I tried both increase and decrease gpu-memory-utilization, also not working. so I think this is a bug with vllm.

hope will be fixed in 0.8.4 or further, this is really a big bug

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by aabbccddwasd** [comment]
Oh no, when I upgraded vllm to 0.8.3 it also have problem with image processor, and I tried to upgrade my preprocessor_config.json, and when I downgraded vllm to 0.7.2 I found the new config can't be recognized by 0.7.2, so none of qwen2.5vl models can work for me now :(
please fix the OOM bug as early as you can, PLEASE...

**Comment by DarkLight1337** [comment]
You can reduce `--max-num-seqs` parameter. In recent versions it was increased from default 256 to 1024. You can try setting it back to the original value.

**Comment by aabbccddwasd** [comment]
> You can reduce `--max-num-seqs` parameter. In recent versions it was increased from default 256 to 1024. You can try setting it back to the original value.

ok I will try it, so what does this parameter mean? honestly, the doc is too simple that I don't really know how does it affects performance.

**Comment by DarkLight1337** [comment]
It refers to the maximum batch size to pass to the model. So a larger value can improve performance but at the cost of taking up more memory

**Comment by aabbccddwasd** [comment]
> It refers to the maximum batch size to pass to the model. So a larger value can improve performance but at the cost of taking up more memory

so it improves concurrent performance and doesn't affect single request performance right?

**Comment by DarkLight1337** [comment]
Yes

**Comment by aabbccddwasd** [comment]
> GPU0 is relative to the order of GPUs in `CUDA_VISIBLE_DEVICES`.

ok I know it, thanks

**Comment by aabbccddwasd** [comment]
> I see that you set the attention backend to xformers. Is this the case for both versions?

I can't test V1, because 2080ti doesn't support it, but I see someone having same problem in 4 A100s, #16570 , but he succeed
after use v0 engine.

**Comment by erdongchendou** [comment]
vllm serve /path_to_model/Qwen2.5-VL-7B-Instruct --gpu-memory-utilization 0.95 --max-model-len 4096

I can use this command to run Qwen on one 3090 GPU.

**Comment by aabbccddwasd** [comment]
> vllm serve /path_to_model/Qwen2.5-VL-7B-Instruct --gpu-memory-utilization 0.95 --max-model-len 4096
> 
> I can use this command to run Qwen on one 3090 GPU.

but don't you think the context len is too small for this model? I used to run Qwen2.5-VL-7B fp16 with 26000 context len on single 2080ti 22g in 0.7.2....

**Comment by erdongchendou** [comment]
> > vllm serve /path_to_model/Qwen2.5-VL-7B-Instruct --gpu-memory-utilization 0.95 --max-model-len 4096
> > I can use this command to run Qwen on one 3090 GPU.
> 
> but don't you think the context len is too small for this model? I used to run Qwen2.5-VL-7B fp16 with 26000 context len on single 2080ti 22g in 0.7.2....

It doesn't matter. I tried to set max-model-len to 26000 and It didn't OOM.
In my experience, as long as I use this command, it won't OOM.

But If I use this following line to run qwen on more than 1 gpu, it will OOM.

`vllm serve /path_to_qwen/Qwen2.5-VL-7B-Instruct --pipeline-parallel-size 2 --dtype auto --api-key token-abc123 --trust-remote-code --host 0.0.0.0 --max-model-len 4096`

**Comment by aabbccddwasd** [comment]
> > > vllm serve /path_to_model/Qwen2.5-VL-7B-Instruct --gpu-memory-utilization 0.95 --max-model-len 4096
> > > I can use this command to run Qwen on one 3090 GPU.
> > 
> > 
> > but don't you think the context len is too small for this model? I used to run Qwen2.5-VL-7B fp16 with 26000 context len on single 2080ti 22g in 0.7.2....
> 
> It doesn't matter. I tried to set max-model-len to 26000 and It didn't OOM. In my experience, as long as I use this command, it won't OOM.
> 
> But If I use this following line to run qwen on more than 1 gpu, it will OOM.
> 
> `vllm serve /path_to_qwen/Qwen2.5-VL-7B-Instruct --pipeline-parallel-size 2 --dtype auto --api-key token-abc123 --trust-remote-code --host 0.0.0.0 --max-model-len 4096`

emm, still not make sense though, we can't use 2 GPUS to run a model fits in a single GPU, how can it possible, something definitely went wrong.
by the way, in my case, I didn't use any parallelism and it still OOM

**Comment by aabbccddwasd** [comment]
@DarkLight1337 I realized something: only multimodal VLMs goes OOM in 0.8.3, Qwen-QwQ-32B works fine in 0.8.3 with a context length same as it in 0.7.2.

**Comment by aabbccddwasd** [comment]
0.8.4 tested, still not working

**Comment by DarkLight1337** [comment]
It may be because of https://github.com/vllm-project/vllm/issues/16570#issuecomment-2803657113

**Comment by DarkLight1337** [comment]
Please try out the solutions in https://github.com/vllm-project/vllm/pull/16704

**Comment by DarkLight1337** [comment]
The CLI arguments for the online server are basically the same as those of the offline inference engine. The main difference is that you just have to pass the arguments in CLI format instead of as Python objects. See https://docs.vllm.ai/en/latest/serving/engine_args.html

**Comment by DarkLight1337** [comment]
You can pass compilation config in CLI as a dictionary formatted as JSON string

**Comment by aabbccddwasd** [comment]
ok I think I figured out the problems. **it's neither a problem with cuda graph nor with V1 engine** it's about multimodal processor configs. in older versions we don't need to set --mm_processor_kwargs, but in current version we need to set it manually. in my case any max_pixels greater than 1920*1080 will led to OOM, maybe vllm increased the default value of it.

**Comment by aabbccddwasd** [comment]
@DarkLight1337 could you add limit max_pixels in the docs?

**Comment by DarkLight1337** [comment]
Opened https://github.com/vllm-project/vllm/pull/16765
