### ISSUE TITLE
[Bug]: RuntimeError on RTX 5090: "no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by danhnc96** [vllm-project/vllm#16901]
### Describe the bug

When running 

[vLLM.log](https://github.com/user-attachments/files/19829093/vLLM.log)

 with a NVIDIA RTX 5090 GPU, I encountered the following error:

RuntimeError: CUDA error: no kernel image is available for execution on the device

From the logs, it seems that PyTorch does not support the compute capability of the RTX 5090 (sm_120):

### To Reproduce

1. Use RTX 5090 GPU
2. Install vLLM with Docker or system Python environment
3. Launch the vLLM OpenAI API server
4. Engine fails to start due to CUDA kernel compatibility issue

### Environment

- **GPU**: NVIDIA GeForce RTX 5090
- **CUDA Driver Version**: 12.8
- **CUDA Toolkit**: 12.8.93
- **NVIDIA Driver**: 570.124.06
- **PyTorch Version**: 2.x (installed via pip)
- **vLLM Version**: Latest (from PyPI)
- **Python Version**: 3.10
- **OS**: Ubuntu 22.04

### Additional Context

It seems that the RTX 5090 uses a new compute capability (`sm_120`), which is currently not supported in the stable PyTorch build I'm using.

Is there a recommended way to run vLLM with this GPU? Should I:

- Switch to a nightly PyTorch build that supports sm_120?
- Build PyTorch from source with `TORCH_CUDA_ARCH_LIST="12.0"`?
- Wait for official support from PyTorch?

Any guidance or workaround would be greatly appreciated. Thanks!

### How you are installing vllm

```sh
pip install -vvv vllm
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Patrick10203** [comment]
I have the exact same issue with the RTX 5090. I found no solution so far.

**Comment by bi1101** [comment]
You have to build the image yourself

here's the docker that you can try.

clone the vllm repo and place this docker compose right OUTSIDE the repo

```yml
vllm-Qwen3-30B-A3B-AWQ:
    container_name: vllm-Qwen3-30B-A3B-AWQ
    image: vllm-cu128
    build:
      dockerfile: docker/Dockerfile
      context: vllm
      args:
        max_jobs: 16
        RUN_WHEEL_CHECK: "false"
        TORCH_CUDA_ARCH_LIST: "7.0 7.5 8.0 8.6 8.9 9.0+PTX 12.0"
    command: [ "--model", "cognitivecomputations/Qwen3-30B-A3B-AWQ", "--trust-remote-code", "--enable-reasoning", "--reasoning-parser", "deepseek_r1"]
    ports:
      - "8000:8000"
    environment:
      - VLLM_USE_V1=1
      - VLLM_MAX_SIZE_MB=10240
      - VLLM_FLASH_ATTN_VERSION=2
      - VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
      # - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    # runtime: nvidia
    volumes:
      - vllm_cache:/root/.cache
      - model_data:/models
    # ipc: host
    # privileged: true
    # restart: unless-stopped
```

**Comment by alew3** [comment]
@bi1101 after a few hours building, it failed for me when running the model
```vllm-Qwen3-30B-A3B-AWQ  | ERROR 05-08 13:29:08 [core.py:412] RuntimeError: CUDA error: no kernel image is available for execution on the device
vllm-Qwen3-30B-A3B-AWQ  | ERROR 05-08 13:29:08 [core.py:412] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
vllm-Qwen3-30B-A3B-AWQ  | ERROR 05-08 13:29:08 [core.py:412] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
vllm-Qwen3-30B-A3B-AWQ  | ERROR 05-08 13:29:08 [core.py:412] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.```

**Comment by bi1101** [comment]
@alew3 sorry, my mistake, the `torch_cuda_arch_list: "7.0 7.5 8.0 8.6 8.9 9.0+PTX 12.0"` should not be capitalized, the dedault arch does not include compute capability 12.0 architecture for 5090, thus the error you are experiencing

**Comment by cyril23** [comment]
> clone the vllm repo and place this docker compose right OUTSIDE the repo
> To get FP8 models to work on Blackwell
> After building the original image, install triton from souce to the image

This does not work for me unfortunately:

```
git clone https://github.com/vllm-project/vllm
cd vllm/
git checkout tags/v0.9.0 -b mybranch
sudo docker build . --target vllm-openai --tag myvllm-all \
  --file docker/Dockerfile --build-arg max_jobs=4 \
  --build-arg nvcc_threads=1  \
  --build-arg torch_cuda_arch_list="7.0 7.5 8.0 8.6 8.9 9.0+PTX 12.0 12.1" 
  --build-arg RUN_WHEEL_CHECK=false
# takes quite a long time: Building 10139.6s (42/42) FINISHED 

nano Dockerfile_all.fp8
# BEGIN Dockerfile_all.fp8
FROM myvllm-all
RUN pip install --no-cache-dir git+https://github.com/triton-lang/triton
# END Dockerfile_all.fp8

sudo docker build   -f Dockerfile_all.fp8   -t myvllm-all-fp8 .

sudo docker run --runtime nvidia --gpus all \
  -v ~/.cache/huggingface:/root/.cache/huggingface     -p 8000:8000 \
  --env "HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN" \
  --env "TORCH-LOGS=+dynamo"     \
  myvllm-all-fp8 --model RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8     \
  --max-model-len 8k
```

Same errors as usual:

> ```
> INFO 05-18 08:58:46 [default_loader.py:278] Loading weights took 5.17 seconds
> INFO 05-18 08:58:46 [gpu_model_runner.py:1447] Model loading took 8.4890 GiB and 6.184214 seconds
> INFO 05-18 08:58:51 [backends.py:459] Using cache directory: /root/.cache/vllm/torch_compile_cache/d4491b0504/rank_0_0 for vLLM's torch.compile
> INFO 05-18 08:58:51 [backends.py:469] Dynamo bytecode transform time: 4.47 s
> Process EngineCore_0:
> ERROR 05-18 08:58:52 [core.py:489] EngineCore failed to start.
> ERROR 05-18 08:58:52 [core.py:489] Traceback (most recent call last):
> ERROR 05-18 08:58:52 [core.py:489]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 480, in run_engine_core
> ERROR 05-18 08:58:52 [core.py:489]     engine_core = EngineCoreProc(*args, **kwargs)
> [...]
> ERROR 05-18 08:58:52 [core.py:489]   File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 1153, in make_launcher
> ERROR 05-18 08:58:52 [core.py:489]     "launch_enter_hook": binary.__class__.launch_enter_hook,
> ERROR 05-18 08:58:52 [core.py:489]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ERROR 05-18 08:58:52 [core.py:489] torch._inductor.exc.InductorError: AttributeError: type object 'CompiledKernel' has no attribute 'launch_enter_hook'
> ```


System Info:

> - x64 (AMD 9800X3D)
> - 96 GB memory
> - NVIDIA RTX 5090, 32 GB VRAM
> - Host:
>   - Windows 11 24H2
>   - Driver: 576.40 from Mon May 12, 2025
>   - Nvidia CUDA Toolkit 12.9
> - WSL2: `wsl --version -> WSL-Version: 2.4.13.0, Kernelversion: 5.15.167.4-1, WSLg-Version: 1.0.65, MSRDC-Version: 1.2.5716, Direct3D-Version: 1.611.1-81528511, DXCore-Version: 10.0.26100.1-240331-1435.ge-release, Windows-Version: 10.0.26100.3915`
> - Running WSL2 with Ubuntu 24 LTS, freshly installed. The only change to WSL I did is create a file "C:\Users\MYUSER\.wslconfig" with content
> ```
> [wsl2]
> memory=85GB
> ```
> Output of nvidia-smi within Ubuntu 24 WSL:
> ```
> +-----------------------------------------------------------------------------------------+
> | NVIDIA-SMI 575.55.01              Driver Version: 576.40         CUDA Version: 12.9     |
> |-----------------------------------------+------------------------+----------------------+
> | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
> |                                         |                        |               MIG M. |
> |=========================================+========================+======================|
> |   0  NVIDIA GeForce RTX 5090        On  |   00000000:01:00.0  On |                  N/A |
> |  0%   47C    P8             28W /  575W |    1400MiB /  32607MiB |      0%      Default |
> |                                         |                        |                  N/A |
> +-----------------------------------------+------------------------+----------------------+
> 
> +-----------------------------------------------------------------------------------------+
> | Processes:                                                                              |
> |  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
> |        ID   ID                                                               Usage      |
> |=========================================================================================|
> |  No running processes found                                                             |
> +-----------------------------------------------------------------------------------------+
> ```

Are you sure you ran fp8 like that? According to https://github.com/vllm-project/vllm/issues/18153#issuecomment-2888576119

> SM120(5080, 5090) Blackwell support still needs to be added for GEMMS to vLLM. But on the bright side CUTLASS examples and support has released for [80_blackwell_geforce_sparse_gemm](https://github.com/NVIDIA/cutlass/blob/main/examples/80_blackwell_geforce_sparse_gemm) and [79_blackwell_geforce_gemm](https://github.com/NVIDIA/cutlass/blob/main/examples/79_blackwell_geforce_gemm). We would love some community support here.

Will try out https://github.com/vllm-project/vllm/issues/14452#issuecomment-2862553056 now, looks promising: https://github.com/vllm-project/vllm/compare/main...kaln27:vllm:main

**Comment by dingdayu** [comment]
Link:

https://github.com/triton-lang/triton/issues/6805
https://github.com/pytorch/pytorch/pull/153554

**Comment by voipmonitor** [comment]
@cyril23 have you managed to rum vllm with the FP8 models? I'm getting internal errors when loading Qwen/Qwen3-30B-A3B-FP8 

 vllm serve /root/models/Qwen/Qwen3-30B-A3B-FP8/ --enable-reasoning --reasoning-parser deepseek_r1  --max-model-len 8192   --tensor-parallel-size 2  

(VllmWorker rank=0 pid=462124) ERROR 06-04 00:35:04 [multiproc_executor.py:523]   File "/root/vllm-new/vllm/vllm/_custom_ops.py", line 678, in cutlass_scaled_mm
(VllmWorker rank=0 pid=462124) ERROR 06-04 00:35:04 [multiproc_executor.py:523]     torch.ops._C.cutlass_scaled_mm(out, a, b, scale_a, scale_b, bias)
(VllmWorker rank=0 pid=462124) ERROR 06-04 00:35:04 [multiproc_executor.py:523]   File "/root/miniconda3/envs/ktransformers-clean/lib/python3.11/site-packages/torch/_ops.py", line 1208, in __call__
(VllmWorker rank=0 pid=462124) ERROR 06-04 00:35:04 [multiproc_executor.py:523]     return self._op(*args, **(kwargs or {}))
(VllmWorker rank=0 pid=462124) ERROR 06-04 00:35:04 [multiproc_executor.py:523]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorker rank=0 pid=462124) ERROR 06-04 00:35:04 [multiproc_executor.py:523] RuntimeError: Error Internal

**Comment by cyril23** [comment]
> @cyril23 have you managed to rum vllm with the FP8 models

@voipmonitor 
I've successfully tested vLLM with FP8 models on a single RTX 5090. I haven't tried tensor parallelism since I only have one GPU.
- Use my vLLM fork: https://github.com/cyril23/vllm
  - It includes kaln27's SM120 FP8 patch from this pullrequest: https://github.com/vllm-project/vllm/pull/17280 
  - I've merged the latest main branch from https://github.com/vllm-project/vllm into my fork to include recent PyTorch and CUDA updates.
- Full discussion: https://github.com/vllm-project/vllm/issues/16515#issuecomment-2892435704 

```bash
# Clone the repository (includes kaln27's FP8 patch and more recent commits)
git clone https://github.com/cyril23/vllm vllm-kaln27-updated
cd vllm-kaln27-updated/

# Build:
DOCKER_BUILDKIT=1 sudo docker build . \
  --target vllm-openai \
  --tag myvllm-kaln27-updated \
  --file docker/Dockerfile \
  --build-arg max_jobs=4 --build-arg nvcc_threads=1  \
  --build-arg torch_cuda_arch_list="12.0 12.1" \
  --build-arg RUN_WHEEL_CHECK=false

# Run:
export HUGGING_FACE_HUB_TOKEN=YOUR_TOKEN # only needed for private or restricted models
sudo docker run --runtime nvidia --gpus all \
    -v ~/.cache/huggingface:/root/.cache/huggingface \
    -p 8000:8000 \
    --env "HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN" \
    myvllm-kaln27-updated \
    --model RedHatAI/Qwen3-30B-A3B-FP8-dynamic \
    --gpu-memory-utilization 0.9 \
    --enable-prefix-caching \
    --enable-chunked-prefill \
    --enable-reasoning --reasoning-parser deepseek_r1 \
    --max-model-len 8192 \
    --tensor-parallel-size 2

# edit: added tensor parallelism arg. edit: fixed clone command
```

Does that work for you?

By the way, if you’re interested, you can also try NVIDIA's TensorRT-LLM:
- Unlike kaln27’s vLLM PR (which only enables basic FP8 inference), TensorRT-LLM v0.19.0 adds working kernels for FP8 K/V caching on Blackwell (SM 120) GPUs like the RTX 5090.
- In high‐QPS scenarios, TensorRT-LLM can achieve even higher FP8 throughput than vLLM (even without FP8 K/V cache). This might be because kaln27's FP8 implementation in vLLM still has some room for optimization.
- Full instructions are here: https://github.com/NVIDIA/TensorRT-LLM/issues/4275#issuecomment-2941155249

**Comment by voipmonitor** [comment]
> > [@cyril23](https://github.com/cyril23) have you managed to rum vllm with the FP8 models
> 
> [@voipmonitor](https://github.com/voipmonitor) I've successfully tested vLLM with FP8 models on a single RTX 5090. I haven't tried tensor parallelism since I only have one GPU.
> 


Thank you. I have tried your branch and now I'm able to run FP8 model RedHatAI/Qwen3-30B-A3B-FP8-dynamic though I'm not able to run Qwen/Qwen3-30B-A3B-FP8 - have you tried the Qwen3-30B-A3B-FP8 ? It fails with RuntimeError: Currently, block scaled fp8 gemm is not implemented for Blackwell - it seems like torch does not implement this yet? (or what component it might be? 

```
(VllmWorker rank=0 pid=722847) ERROR 06-05 14:28:26 [multiproc_executor.py:522]     torch.ops._C.cutlass_scaled_mm(out, a, b, scale_a, scale_b, bias)
(VllmWorker rank=0 pid=722847) ERROR 06-05 14:28:26 [multiproc_executor.py:522]   File "/root/miniconda3/envs/vllm-clean2/lib/python3.11/site-packages/torch/_ops.py", line 1208, in __call__
(VllmWorker rank=0 pid=722847) ERROR 06-05 14:28:26 [multiproc_executor.py:522]     return self._op(*args, **(kwargs or {}))
(VllmWorker rank=0 pid=722847) ERROR 06-05 14:28:26 [multiproc_executor.py:522]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorker rank=0 pid=722847) ERROR 06-05 14:28:26 [multiproc_executor.py:522] RuntimeError: Currently, block scaled fp8 gemm is not implemented for Blackwell
```


Regarding the tensor parallelism - I have just tested that if I install vllm and pytorch "pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128" and compile vllm directly on the host (ubuntu 24 lts) with Cuda compilation tools, release 12.8, V12.8.93  - it does not crash. I will try to figure out what differs in all the docker images which crashes the parallelism

I'm also curious why when compiling vllm it can use all my 36 cores when nvidia compiler starts while on the docker image it can compile only with 4 parallel tasks (which takes ages) and I have tried almost everything in the docker - injecting -j 36 to the ninja and setting all kind of parameters which should do it - this is annoying when building docker images with vllm 

TensorRT-LLM - not yet. I'm new to all of this progressing slowly - but I will try it. 

I have also tried Ktransformer with hybrid CPU/GPU configuration and the recent AMX implementation getting interesting results

**Comment by cyril23** [comment]
> though I'm not able to run Qwen/Qwen3-30B-A3B-FP8 - have you tried the Qwen3-30B-A3B-FP8 ? It fails with RuntimeError: Currently, block scaled fp8 gemm is not implemented for Blackwell - it seems like torch does not implement this yet?+

Yes, it fails with the same message for me. The message comes directly from kaln27's Pullrequest which I've integrated into my branch. See https://github.com/vllm-project/vllm/pull/17280/files - [this part](https://github.com/user-attachments/assets/804f8f7e-7f22-449f-bf31-e157f47b512c). This type is just not implemented yet.

> Regarding the tensor parallelism - I have just tested that if I install vllm and pytorch "pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128" and compile vllm directly on the host (ubuntu 24 lts) with Cuda compilation tools, release 12.8, V12.8.93 - it does not crash.

The current vLLM Dockerfile uses pytorch stable (for non-arm architecture). So apparently pytorch 2.7.0 is too old and still contains some bugs for RTX Blackwell? But good to know you can at least work-around it for the moment [like that](https://docs.vllm.ai/en/latest/getting_started/installation/gpu.html#use-an-existing-pytorch-installation).

**Comment by voipmonitor** [comment]
> 
> The current vLLM Dockerfile uses pytorch stable (for non-arm architecture). So apparently pytorch 2.7.0 is too old and still contains some bugs for RTX Blackwell? But good to know you can at least work-around it for the moment [like that]

I have just run this command in your docker image: 

`pip install --pre --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
`

and the problem with crashing is gone. 

If you are curious if the tensor parallel brings any spee improvement for a model which fits entirely into one of the 5090 - here is the results (it does not provide any token / second imrovement. But for models which does not fit into the RAM the torch parallel makes sense. 




```
VLLM_ATTENTION_BACKEND=FLASHINFER vllm serve /root/models/RedHatAI/Qwen3-30B-A3B-FP8-dynamic/ --served-model-name  "RedHatAI/Qwen3-30B-A3B-FP8-dynamic" --enable-prefix-caching --enable-chunked-prefill   --max-model-len 20000   --tensor-parallel-size 2 --port 8001


tensor-parallel = 1

(vllm-clean2) root@testserver:~/vllm-clean/flashinfer# VLLM_ATTENTION_BACKEND=FLASHINFER vllm serve /root/models/RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8/ --served-model-name  "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8" --enable-prefix-caching --enable-chunked-prefill   --max-model-len 20000   --tensor-parallel-size 1 --port 8001                


docker run -it --network host -e HF_TOKEN=$HF_TOKEN inference_benchmarker inference-benchmarker   --tokenizer-name "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8"  --url http://localhost:8001/v1   --max-vus 800      --duration 120s         --warmup 30s    --benchmark-kind rate   --rates 1.0     --rates 5.0     --rates 10.0   --prompt-options "num_tokens=200,max_tokens=220,min_tokens=180,variance=10"   --decode-options "num_tokens=200,max_tokens=220,min_tokens=180,variance=10"



VLLM_ATTENTION_BACKEND=FLASHINFER vllm serve /root/models/RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8/ --served-model-name  "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8"    --max-model-len 8k   --tensor-parallel-size 1 --port 8001

┌─────────────────┬────────────────────────────────────────────────────────────────┐━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
│ Parameter       │ Value                                                          │
├─────────────────┼────────────────────────────────────────────────────────────────┤
│ Max VUs         │ 800                                                            │
│ Duration        │ 120                                                            │
│ Warmup Duration │ 30                                                             │
│ Benchmark Kind  │ Rate                                                           │
│ Rates           │ [1.0, 5.0, 10.0]                                               │
│ Num Rates       │ 10                                                             │
│ Prompt Options  │ num_tokens=Some(200),min_tokens=180,max_tokens=220,variance=10 │
│ Decode Options  │ num_tokens=Some(200),min_tokens=180,max_tokens=220,variance=10 │
│ Tokenizer       │ RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8                        │
│ Extra Metadata  │ N/A                                                            │
└─────────────────┴────────────────────────────────────────────────────────────────┘


┌─────────────────────┬────────────┬───────────────────┬────────────┬───────────┬────────────────────┬────────────┬─────────────────────┬─────────────────────────────┬──────────────────────────────┐
│ Benchmark           │ QPS        │ E2E Latency (avg) │ TTFT (avg) │ ITL (avg) │ Throughput         │ Error Rate │ Successful Requests │ Prompt tokens per req (avg) │ Decoded tokens per req (avg) │
├─────────────────────┼────────────┼───────────────────┼────────────┼───────────┼────────────────────┼────────────┼─────────────────────┼─────────────────────────────┼──────────────────────────────┤
│ warmup              │ 0.37 req/s │ 2.73 sec          │ 27.33 ms   │ 15.39 ms  │ 64.60 tokens/sec   │ 0.00%      │ 10/10               │ 200.00                      │ 176.40                       │
│ constant@1.00req/s  │ 0.98 req/s │ 2.90 sec          │ 35.67 ms   │ 15.37 ms  │ 182.57 tokens/sec  │ 0.00%      │ 116/116             │ 200.00                      │ 185.73                       │
│ constant@5.00req/s  │ 4.92 req/s │ 2.89 sec          │ 36.15 ms   │ 15.79 ms  │ 890.18 tokens/sec  │ 0.00%      │ 585/585             │ 200.00                      │ 181.09                       │
│ constant@10.00req/s │ 9.81 req/s │ 3.05 sec          │ 38.14 ms   │ 16.24 ms  │ 1817.21 tokens/sec │ 0.00%      │ 1171/1171           │ 200.00                      │ 185.16                       │
└─────────────────────┴────────────┴───────────────────┴────────────┴───────────┴────────────────────┴────────────┴─────────────────────┴─────────────────────────────┴──────────────────────────────┘


tensor-parallel-size 2

(vllm-clean2) root@testserver:~/vllm-clean/flashinfer# VLLM_ATTENTION_BACKEND=FLASHINFER vllm serve /root/models/RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8/ --served-model-name  "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8" --enable-prefix-caching --enable-chunked-prefill   --max-model-len 20000   --tensor-parallel-size 2 --port 8001  

┌─────────────────┬────────────────────────────────────────────────────────────────┐━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
│ Parameter       │ Value                                                          │
├─────────────────┼────────────────────────────────────────────────────────────────┤
│ Max VUs         │ 800                                                            │
│ Duration        │ 120                                                            │
│ Warmup Duration │ 30                                                             │
│ Benchmark Kind  │ Rate                                                           │
│ Rates           │ [1.0, 5.0, 10.0]                                               │
│ Num Rates       │ 10                                                             │
│ Prompt Options  │ num_tokens=Some(200),min_tokens=180,max_tokens=220,variance=10 │
│ Decode Options  │ num_tokens=Some(200),min_tokens=180,max_tokens=220,variance=10 │
│ Tokenizer       │ RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8                        │
│ Extra Metadata  │ N/A                                                            │
└─────────────────┴────────────────────────────────────────────────────────────────┘


┌─────────────────────┬────────────┬───────────────────┬────────────┬───────────┬────────────────────┬────────────┬─────────────────────┬─────────────────────────────┬──────────────────────────────┐
│ Benchmark           │ QPS        │ E2E Latency (avg) │ TTFT (avg) │ ITL (avg) │ Throughput         │ Error Rate │ Successful Requests │ Prompt tokens per req (avg) │ Decoded tokens per req (avg) │
├─────────────────────┼────────────┼───────────────────┼────────────┼───────────┼────────────────────┼────────────┼─────────────────────┼─────────────────────────────┼──────────────────────────────┤
│ warmup              │ 0.53 req/s │ 1.88 sec          │ 53.88 ms   │ 9.98 ms   │ 97.79 tokens/sec   │ 0.00%      │ 16/16               │ 200.00                      │ 183.88                       │
│ constant@1.00req/s  │ 0.99 req/s │ 1.92 sec          │ 34.21 ms   │ 9.98 ms   │ 186.80 tokens/sec  │ 0.00%      │ 118/118             │ 200.00                      │ 188.13                       │
│ constant@5.00req/s  │ 4.92 req/s │ 1.99 sec          │ 33.09 ms   │ 10.88 ms  │ 883.43 tokens/sec  │ 0.00%      │ 588/588             │ 200.00                      │ 179.63                       │
│ constant@10.00req/s │ 9.83 req/s │ 2.21 sec          │ 35.84 ms   │ 12.10 ms  │ 1763.52 tokens/sec │ 0.00%      │ 1175/1175           │ 200.00                      │ 179.43                       │
└─────────────────────┴────────────┴───────────────────┴────────────┴───────────┴────────────────────┴────────────┴─────────────────────┴─────────────────────────────┴──────────────────────────────┘
```

**Comment by cyril23** [comment]
> If you are curious if the tensor parallel brings any spee improvement for a model which fits entirely into one of the 5090 - here is the results (it does not provide any token / second imrovement.

Thanks for the insights! At least there is an E2E latency drop going from TP1 to TP2, even at 1-10 QPS. 

When testing high QPS scenarios you should get over 5000 tokens/sec on 1 GPU:

> ```
> # TP 1 on 1x RTX 5090:
> sudo docker run --runtime nvidia --gpus all -v ~/.cache/huggingface:/root/.cache/huggingface -p 8000:8000 --env "HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN" myvllm-kaln27-updated --max-model-len 1024 --model RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8 --disable-log-requests --enable-chunked-prefill --max_num_batched_tokens 2048 --gpu_memory_utilization 0.9
> sudo docker run --network host -e HF_TOKEN=$HUGGING_FACE_HUB_TOKEN -v ~/inference-benchmarker-results:/opt/inference-benchmarker/results inference_benchmarker_latest inference-benchmarker --no-console --url http://localhost:8000/v1 --max-vus 800 --duration 120s --warmup 30s --benchmark-kind rate --rates 1.0 --rates 10.0 --rates 30.0 --rates 100.0 --prompt-options "num_tokens=200,max_tokens=220,min_tokens=180,variance=10" --decode-options "num_tokens=200,max_tokens=220,min_tokens=180,variance=10" --model-name "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8" --tokenizer-name "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8"
> ┌─────────────────┬────────────────────────────────────────────────────────────────┐
> │ Parameter       │ Value                                                          │
> ├─────────────────┼────────────────────────────────────────────────────────────────┤
> │ Max VUs         │ 800                                                            │
> │ Duration        │ 120                                                            │
> │ Warmup Duration │ 30                                                             │
> │ Benchmark Kind  │ Rate                                                           │
> │ Rates           │ [1.0, 10.0, 30.0, 100.0]                                       │
> │ Num Rates       │ 10                                                             │
> │ Prompt Options  │ num_tokens=Some(200),min_tokens=180,max_tokens=220,variance=10 │
> │ Decode Options  │ num_tokens=Some(200),min_tokens=180,max_tokens=220,variance=10 │
> │ Tokenizer       │ RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8                        │
> │ Extra Metadata  │ N/A                                                            │
> └─────────────────┴────────────────────────────────────────────────────────────────┘
> ┌──────────────────────┬─────────────┬───────────────────┬─────────────┬───────────┬────────────────────┬────────────┬─────────────────────┬─────────────────────────────┬──────────────────────────────┐
> │ Benchmark            │ QPS         │ E2E Latency (avg) │ TTFT (avg)  │ ITL (avg) │ Throughput         │ Error Rate │ Successful Requests │ Prompt tokens per req (avg) │ Decoded tokens per req (avg) │
> ├──────────────────────┼─────────────┼───────────────────┼─────────────┼───────────┼────────────────────┼────────────┼─────────────────────┼─────────────────────────────┼──────────────────────────────┤
> │ warmup               │ 0.35 req/s  │ 2.88 sec          │ 145.81 ms   │ 15.37 ms  │ 62.03 tokens/sec   │ 0.00%      │ 11/11               │ 200.00                      │ 178.91                       │
> │ constant@1.00req/s   │ 0.98 req/s  │ 2.94 sec          │ 30.88 ms    │ 15.66 ms  │ 183.31 tokens/sec  │ 0.00%      │ 116/116             │ 200.00                      │ 186.60                       │
> │ constant@10.00req/s  │ 9.93 req/s  │ 3.02 sec          │ 34.41 ms    │ 16.67 ms  │ 1776.31 tokens/sec │ 0.00%      │ 1171/1171           │ 200.00                      │ 178.84                       │
> │ constant@30.00req/s  │ 27.57 req/s │ 9.03 sec          │ 761.31 ms   │ 46.01 ms  │ 4959.31 tokens/sec │ 0.00%      │ 3297/3297           │ 200.00                      │ 179.87                       │
> │ constant@100.00req/s │ 29.45 req/s │ 23.12 sec         │ 14937.02 ms │ 46.45 ms  │ 5249.54 tokens/sec │ 0.00%      │ 3525/3525           │ 200.00                      │ 178.25                       │
> └──────────────────────┴─────────────┴───────────────────┴─────────────┴───────────┴────────────────────┴────────────┴─────────────────────┴─────────────────────────────┴──────────────────────────────┘
> ```
> 

According to https://www.determined.ai/blog/tp#intermediate these might be the reasons for the throughput not improving in your tests:
> The disadvantage of Tensor Parallelism is that it generally reduces GPU efficiency, for two primary reasons:
> - The communications between GPUs need to be completed before the model can move forward, which can seriously hamper efficiency. Nobody likes waiting around.
> - Modern GPUs often achieve higher throughput when performing larger matrix-multiplies (see the plot below), but Tensor Parallelism unfortunately reduces the size of the matrix-multiplies.

There are many vllm issues about it, e.g. https://github.com/vllm-project/vllm/issues/689#issuecomment-2036419216
> The cost of inter-GPU communication outweighs the parallelisation of the compute for smaller models

This is an interesting read too: https://rocm.blogs.amd.com/artificial-intelligence/LLM_Inference/README.html - The blog talks about ROCm performance of an AMD MI300X gpu with 192 GB HBM3 but the principles might still apply to RTX 5090 CUDA performance:
> Having larger HBM memory is helpful to serve certain LLMs on a single GPU, e.g. <=70B, to avoid the communication overhead with TP > 1. AMD recommends serving LLMs in 8 instances of TP=1 to maximize the throughput if the latency constraints can be met. This method has been adopted by AMD in MLPerf benchmark. Avoid running small LLMs <=30B on multiple GPUs ( TP>1 mode) where AllReduce overhead can dominate.

So maybe models in the 11-14B range at FP16 (or even bigger models at FP8?) might show more E2E latency drops and throughput gains when going TP1 to TP2, even if the models still fit on 1 GPU. But probably only at higher QPS.

According to https://www.deepspeed.ai/tutorials/automatic-tensor-parallelism/#t5-11b-inference-performance-comparison you still might see a throughput improvement for 2 GPUs with tensor parallelism when you try out higher QPS like 32, 64, 128. At least they did it with "deepseed" instead of vllm, using the good old 2020 Google T5 11B model.

**Comment by hxssgaa** [comment]
> > [@cyril23](https://github.com/cyril23) have you managed to rum vllm with the FP8 models
> 
> [@voipmonitor](https://github.com/voipmonitor) I've successfully tested vLLM with FP8 models on a single RTX 5090. I haven't tried tensor parallelism since I only have one GPU.
> 
> * Use my vLLM fork: https://github.com/cyril23/vllm
>   
>   * It includes kaln27's SM120 FP8 patch from this pullrequest: [[NVIDIA] Support Cutlass w8a8 for Blackwell Geforce GPUs (sm120) #17280](https://github.com/vllm-project/vllm/pull/17280)
>   * I've merged the latest main branch from https://github.com/vllm-project/vllm into my fork to include recent PyTorch and CUDA updates.
> * Full discussion: [[Installation]: Dual 5090's (sm120, cu128) Issues Running vLLM #16515 (comment)](https://github.com/vllm-project/vllm/issues/16515#issuecomment-2892435704)
> 
> # Clone the repository (includes kaln27's FP8 patch and more recent commits)
> git clone https://github.com/cyril23/vllm vllm-kaln27-updated
> cd vllm-kaln27-updated/
> 
> # Build:
> DOCKER_BUILDKIT=1 sudo docker build . \
>   --target vllm-openai \
>   --tag myvllm-kaln27-updated \
>   --file docker/Dockerfile \
>   --build-arg max_jobs=4 --build-arg nvcc_threads=1  \
>   --build-arg torch_cuda_arch_list="12.0 12.1" \
>   --build-arg RUN_WHEEL_CHECK=false
> 
> # Run:
> export HUGGING_FACE_HUB_TOKEN=YOUR_TOKEN # only needed for private or restricted models
> sudo docker run --runtime nvidia --gpus all \
>     -v ~/.cache/huggingface:/root/.cache/huggingface \
>     -p 8000:8000 \
>     --env "HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN" \
>     myvllm-kaln27-updated \
>     --model RedHatAI/Qwen3-30B-A3B-FP8-dynamic \
>     --gpu-memory-utilization 0.9 \
>     --enable-prefix-caching \
>     --enable-chunked-prefill \
>     --enable-reasoning --reasoning-parser deepseek_r1 \
>     --max-model-len 8192 \
>     --tensor-parallel-size 2
> 
> # edit: added tensor parallelism arg. edit: fixed clone command
> Does that work for you?
> 
> By the way, if you’re interested, you can also try NVIDIA's TensorRT-LLM:
> 
> * Unlike kaln27’s vLLM PR (which only enables basic FP8 inference), TensorRT-LLM v0.19.0 adds working kernels for FP8 K/V caching on Blackwell (SM 120) GPUs like the RTX 5090.
> * In high‐QPS scenarios, TensorRT-LLM can achieve even higher FP8 throughput than vLLM (even without FP8 K/V cache). This might be because kaln27's FP8 implementation in vLLM still has some room for optimization.
> * Full instructions are here: [tensorrt-llm 0.19.0 requires torch<=2.7.0a0,>=2.6.0 (and therefore does not install the current 2.7.0 but the old 2.6.0 which makes it Blackwell incompatible) NVIDIA/TensorRT-LLM#4275 (comment)](https://github.com/NVIDIA/TensorRT-LLM/issues/4275#issuecomment-2941155249)

getting error when running Qwen3-14B-FP8 with a single RTX 5090:
```
ERROR 06-07 21:48:09 [core.py:489] RuntimeError: Currently, block scaled fp8 gemm is not implemented for Blackwell
```

**Comment by cyril23** [comment]
> getting error when running Qwen3-14B-FP8 with a single RTX 5090:
> 
> ERROR 06-07 21:48:09 [core.py:489] RuntimeError: Currently, block scaled fp8 gemm is not implemented for Blackwell

- please be so kind and reformat your [comment](https://github.com/vllm-project/vllm/issues/16901#issuecomment-2953551652) and don't full quote but just quote the part needed.
- Just read https://github.com/vllm-project/vllm/issues/16901#issuecomment-2944828957 carefully. You can run `RedHatAI/Qwen3-30B-A3B-FP8-dynamic` with the current kaln27 patch but not `Qwen/Qwen3-30B-A3B-FP8` because it is a different quant type. See https://github.com/vllm-project/vllm/issues/16901#issuecomment-2946139323 for details.

**Comment by techcomthanh** [comment]
> You have to build the image yourself
> 
> here's the docker that you can try.
> 
> clone the vllm repo and place this docker compose right OUTSIDE the repo
> 
> vllm-Qwen3-30B-A3B-AWQ:
>     container_name: vllm-Qwen3-30B-A3B-AWQ
>     image: vllm-cu128
>     build:
>       dockerfile: docker/Dockerfile
>       context: vllm
>       args:
>         max_jobs: 16
>         RUN_WHEEL_CHECK: "false"
>         nvcc_threads: 16
>         torch_cuda_arch_list: "7.0 7.5 8.0 8.6 8.9 9.0+PTX 12.0" # Should not be capitalized
>     command: [ "--model", "cognitivecomputations/Qwen3-30B-A3B-AWQ", "--trust-remote-code", "--enable-reasoning", "--reasoning-parser", "deepseek_r1"]
>     ports:
>       - "8000:8000"
>     environment:
>       - VLLM_USE_V1=1
>       - VLLM_MAX_SIZE_MB=10240
>       - VLLM_FLASH_ATTN_VERSION=2
>       - VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
>       # - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
>     deploy:
>       resources:
>         reservations:
>           devices:
>             - driver: nvidia
>               device_ids: ['0']
>               capabilities: [gpu]
>     # runtime: nvidia
>     volumes:
>       - vllm_cache:/root/.cache
>       - model_data:/models
>     # ipc: host
>     # privileged: true
>     # restart: unless-stopped
> To get FP8 models to work on Blackwell
> 
> After building the original image, install triton from souce to the image
> 
> FROM vllm-cu128
> # Install Triton from source.
> RUN pip install git+https://github.com/triton-lang/triton

@bi1101 Hello could you please explain more how to do this:
```
> After building the original image, install triton from souce to the image
> 
> FROM vllm-cu128
> # Install Triton from source.
> RUN pip install git+https://github.com/triton-lang/triton
```
I tried to include those lines to `docker/Dockerfile`. After around 6 hours, it created a vllm-cu128 image. I tried to run "docker compose up" with given docker-compose.yaml above then it returned:

```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running prestart hook #0: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object file: no such file or directory: unknown
``` 
I also tried to run `ocker run --runtime nvidia --gpus all -p 8000:8000 --ipc=host vllm-cu128 --model deepseek-ai/DeepSeek-R1-Distill-Qwen-14B` then it returned:
```
INFO 06-12 23:36:21 [__init__.py:244] Automatically detected platform cuda.
INFO 06-12 23:36:26 [api_server.py:1287] vLLM API server version 0.9.1rc2.dev12+g9368cc90b.d20250612
INFO 06-12 23:36:26 [cli_args.py:309] non-default args: {'model': 'deepseek-ai/DeepSeek-R1-Distill-Qwen-14B'}
INFO 06-12 23:36:37 [config.py:823] This model supports multiple tasks: {'generate', 'score', 'reward', 'embed', 'classify'}. Defaulting to 'generate'.
INFO 06-12 23:36:38 [config.py:2195] Chunked prefill is enabled with max_num_batched_tokens=2048.
WARNING 06-12 23:36:47 [env_override.py:17] NCCL_CUMEM_ENABLE is set to 0, skipping override. This may increase memory overhead with cudagraph+allreduce: https://github.com/NVIDIA/nccl/issues/1234
INFO 06-12 23:36:49 [__init__.py:244] Automatically detected platform cuda.
INFO 06-12 23:36:52 [core.py:455] Waiting for init message from front-end.
INFO 06-12 23:36:52 [core.py:70] Initializing a V1 LLM engine (v0.9.1rc2.dev12+g9368cc90b.d20250612) with config: model='deepseek-ai/DeepSeek-R1-Distill-Qwen-14B', speculative_config=None, tokenizer='deepseek-ai/DeepSeek-R1-Distill-Qwen-14B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=16384, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=deepseek-ai/DeepSeek-R1-Distill-Qwen-14B, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
WARNING 06-12 23:36:53 [utils.py:2737] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x72cb0f0154c0>
Process EngineCore_0:
ERROR 06-12 23:36:53 [core.py:515] EngineCore failed to start.
ERROR 06-12 23:36:53 [core.py:515] Traceback (most recent call last):
ERROR 06-12 23:36:53 [core.py:515]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 506, in run_engine_core
ERROR 06-12 23:36:53 [core.py:515]     engine_core = EngineCoreProc(*args, **kwargs)
ERROR 06-12 23:36:53 [core.py:515]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-12 23:36:53 [core.py:515]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 390, in __init__
ERROR 06-12 23:36:53 [core.py:515]     super().__init__(vllm_config, executor_class, log_stats,
ERROR 06-12 23:36:53 [core.py:515]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 76, in __init__
ERROR 06-12 23:36:53 [core.py:515]     self.model_executor = executor_class(vllm_config)
ERROR 06-12 23:36:53 [core.py:515]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-12 23:36:53 [core.py:515]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 53, in __init__
ERROR 06-12 23:36:53 [core.py:515]     self._init_executor()
ERROR 06-12 23:36:53 [core.py:515]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 47, in _init_executor
ERROR 06-12 23:36:53 [core.py:515]     self.collective_rpc("init_device")
ERROR 06-12 23:36:53 [core.py:515]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 57, in collective_rpc
ERROR 06-12 23:36:53 [core.py:515]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 06-12 23:36:53 [core.py:515]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-12 23:36:53 [core.py:515]   File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 2671, in run_method
ERROR 06-12 23:36:53 [core.py:515]     return func(*args, **kwargs)
ERROR 06-12 23:36:53 [core.py:515]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 06-12 23:36:53 [core.py:515]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 606, in init_device
ERROR 06-12 23:36:53 [core.py:515]     self.worker.init_device()  # type: ignore
ERROR 06-12 23:36:53 [core.py:515]     ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-12 23:36:53 [core.py:515]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 128, in init_device
ERROR 06-12 23:36:53 [core.py:515]     torch.cuda.set_device(self.device)
ERROR 06-12 23:36:53 [core.py:515]   File "/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py", line 529, in set_device
ERROR 06-12 23:36:53 [core.py:515]     torch._C._cuda_setDevice(device)
ERROR 06-12 23:36:53 [core.py:515]   File "/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py", line 372, in _lazy_init
ERROR 06-12 23:36:53 [core.py:515]     torch._C._cuda_init()
ERROR 06-12 23:36:53 [core.py:515] RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 519, in run_engine_core
    raise e
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 506, in run_engine_core
    engine_core = EngineCoreProc(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 390, in __init__
    super().__init__(vllm_config, executor_class, log_stats,
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 76, in __init__
    self.model_executor = executor_class(vllm_config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 53, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 47, in _init_executor
    self.collective_rpc("init_device")
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 57, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 2671, in run_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 606, in init_device
    self.worker.init_device()  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 128, in init_device
    torch.cuda.set_device(self.device)
  File "/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py", line 529, in set_device
    torch._C._cuda_setDevice(device)
  File "/usr/local/lib/python3.12/dist-packages/torch/cuda/__init__.py", line 372, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 1387, in <module>
    uvloop.run(run_server(args))
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 1323, in run_server
    await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 1343, in run_server_worker
    async with build_async_engine_client(args, client_config) as engine_client:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 155, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 191, in build_async_engine_client_from_engine_args
    async_llm = AsyncLLM.from_vllm_config(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 162, in from_vllm_config
    return cls(
           ^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 124, in __init__
    self.engine_core = EngineCoreClient.make_async_mp_client(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 93, in make_async_mp_client
    return AsyncMPClient(vllm_config, executor_class, log_stats,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 716, in __init__
    super().__init__(
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 422, in __init__
    self._init_engines_direct(vllm_config, local_only,
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 491, in _init_engines_direct
    self._wait_for_engine_startup(handshake_socket, input_address,
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 511, in _wait_for_engine_startup
    wait_for_engine_startup(
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/utils.py", line 494, in wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}

```

**Comment by bi1101** [comment]
@techcomthanh 
You should build 2 images
1. Just build the dockerfile from source (do not modify it). Remember to add torch_cuda_arch_list 12.0 to the build args (12.0 is the arch of 5090, that is the reason for no kernel image is available, in the lastest docker file, this hasn't been added, Black well sm100 (B100 B200, etc)  might has been added, but not sm120 (5090)
2. Create a separate Dockerfile for fp8 like I mentioned above to build on top of the vllm-12.8 image, you will want to build this to a different image name like vllm-12.8-triton to avoid overwriting the vllm-12.8 image. 

Note: The FP8 worked for Qwen 3 fp8 at the time I posted the comment, but since then I have settled on AWQ so I haven't touched the FP8, so that may have changed, according to some of the comments above, they reported Fp8 is not yet supported and did not work. You may want to experiment with V0 & V1 and different vllm args to get Fp8 working, I recall I used V0 for Fp8 but I do not remember for sure.

**Comment by techcomthanh** [comment]
> [@techcomthanh](https://github.com/techcomthanh) You should build 2 images
> 
> 1. Just build the dockerfile from source (do not modify it). Remember to add torch_cuda_arch_list 12.0 to the build args (12.0 is the arch of 5090, that is the reason for no kernel image is available, in the lastest docker file, this hasn't been added, Black well sm100 (B100 B200, etc)  might has been added, but not sm120 (5090)
> 2. Create a separate Dockerfile for fp8 like I mentioned above to build on top of the vllm-12.8 image, you will want to build this to a different image name like vllm-12.8-triton to avoid overwriting the vllm-12.8 image.
> 
> Note: The FP8 worked for Qwen 3 fp8 at the time I posted the comment, but since then I have settled on AWQ so I haven't touched the FP8, so that may have changed, according to some of the comments above, they reported Fp8 is not yet supported and did not work. You may want to experiment with V0 & V1 and different vllm args to get Fp8 working, I recall I used V0 for Fp8 but I do not remember for sure.

@bi1101 so for first step (1), I just need create docker-compose.yaml as you suggested. Should I keep only 12.0 `        torch_cuda_arch_list: "12.0" ` for faster build time?
For second Dockerfile, Do I just need to includes your two lines only, right?

Thanks so much bro

**Comment by bi1101** [comment]
@techcomthanh yes, I found no real difference when removing other arch and I have multiple cards so I leave the other archs in the build arg, you can remove them if you want.

Try testing the FP8 in the fisrt image before building the second one. I saw that vllm changed some pytorch triton deps in the dockerfile since the time I posted so the triton issue may have been solved already.

**Comment by techcomthanh** [comment]
> [@techcomthanh](https://github.com/techcomthanh) yes, I found no real difference when removing other arch and I have multiple cards so I leave the other archs in the build arg, you can remove them if you want.
> 
> Try testing the FP8 in the fisrt image before building the second one. I saw that vllm changed some pytorch triton deps in the dockerfile since the time I posted so the triton issue may have been solved already.

Thankyou, I will try then update here later

**Comment by 3chh** [comment]
> > [@cyril23](https://github.com/cyril23) have you managed to rum vllm with the FP8 models
> 
> [@voipmonitor](https://github.com/voipmonitor) I've successfully tested vLLM with FP8 models on a single RTX 5090. I haven't tried tensor parallelism since I only have one GPU.
> 
> * Use my vLLM fork: https://github.com/cyril23/vllm
>   
>   * It includes kaln27's SM120 FP8 patch from this pullrequest: [[NVIDIA] Support Cutlass w8a8 for Blackwell Geforce GPUs (sm120) #17280](https://github.com/vllm-project/vllm/pull/17280)
>   * I've merged the latest main branch from https://github.com/vllm-project/vllm into my fork to include recent PyTorch and CUDA updates.
> * Full discussion: [[Installation]: Dual 5090's (sm120, cu128) Issues Running vLLM #16515 (comment)](https://github.com/vllm-project/vllm/issues/16515#issuecomment-2892435704)
> 
> # Clone the repository (includes kaln27's FP8 patch and more recent commits)
> git clone https://github.com/cyril23/vllm vllm-kaln27-updated
> cd vllm-kaln27-updated/
> 
> # Build:
> DOCKER_BUILDKIT=1 sudo docker build . \
>   --target vllm-openai \
>   --tag myvllm-kaln27-updated \
>   --file docker/Dockerfile \
>   --build-arg max_jobs=4 --build-arg nvcc_threads=1  \
>   --build-arg torch_cuda_arch_list="12.0 12.1" \
>   --build-arg RUN_WHEEL_CHECK=false
> 
> # Run:
> export HUGGING_FACE_HUB_TOKEN=YOUR_TOKEN # only needed for private or restricted models
> sudo docker run --runtime nvidia --gpus all \
>     -v ~/.cache/huggingface:/root/.cache/huggingface \
>     -p 8000:8000 \
>     --env "HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN" \
>     myvllm-kaln27-updated \
>     --model RedHatAI/Qwen3-30B-A3B-FP8-dynamic \
>     --gpu-memory-utilization 0.9 \
>     --enable-prefix-caching \
>     --enable-chunked-prefill \
>     --enable-reasoning --reasoning-parser deepseek_r1 \
>     --max-model-len 8192 \
>     --tensor-parallel-size 2
> 
> # edit: added tensor parallelism arg. edit: fixed clone command
> Does that work for you?
> 
> By the way, if you’re interested, you can also try NVIDIA's TensorRT-LLM:
> 
> * Unlike kaln27’s vLLM PR (which only enables basic FP8 inference), TensorRT-LLM v0.19.0 adds working kernels for FP8 K/V caching on Blackwell (SM 120) GPUs like the RTX 5090.
> * In high‐QPS scenarios, TensorRT-LLM can achieve even higher FP8 throughput than vLLM (even without FP8 K/V cache). This might be because kaln27's FP8 implementation in vLLM still has some room for optimization.
> * Full instructions are here: [tensorrt-llm 0.19.0 requires torch<=2.7.0a0,>=2.6.0 (and therefore does not install the current 2.7.0 but the old 2.6.0 which makes it Blackwell incompatible) NVIDIA/TensorRT-LLM#4275 (comment)](https://github.com/NVIDIA/TensorRT-LLM/issues/4275#issuecomment-2941155249)

hi cyril23, i follow what you suggested and met this message:
WARNING 06-13 17:43:55 [utils.py:2664] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7df0f4d29430>
so when i run container it can't init cachekv: 
raise ValueError("No available memory for the cache blocks. "
ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.
Can u help me with this.

**Comment by voipmonitor** [comment]
@cyril23 I have tested kaln27 and TensorRT-LLM FP8 model and I'm getting almost exact same performance on two rtx 5090 - I will retest and compare results with 1x 5090 variant to exclude pcie bottleneck. But it seems both vllm and TensorRT-LLM provides nearly same speed.

**Comment by cyril23** [comment]
@voipmonitor Don’t forget to post some numbers. We all love numbers

@3chh Read the error output, it says you don’t have enough GPU memory. Try to load a smaller model, smaller quant, less max model length etc or try slightly increasing gpu memory utilization as suggested by the error message.

**Comment by voipmonitor** [comment]
> [@voipmonitor](https://github.com/voipmonitor) Don’t forget to post some numbers. We all love numbers
> 
yes, I'm still in the "research" phase tyring all the frameworks and combinations. I will post numbers soon

**Comment by 3chh** [comment]
> [@3chh](https://github.com/3chh) Read the error output, it says you don’t have enough GPU memory. Try to load a smaller model, smaller quant, less max model length etc or try slightly increasing gpu memory utilization as suggested by the error message.

thanhks @cyril23 i found exactly problems i encounter  here, bcs my GPU just have ~1GiB left after load LLM model and new vLLM using V1 Engine not support offload kv_cache to cpu so its show up a OOM error. I just back to use V0 Engine and it worked.
https://github.com/vllm-project/vllm/issues/15228

**Comment by bely66** [comment]
Hi everyone

Anyone found solution, i'm facing issues running lora + bnb 4 quantization

could this be related to the supported arch on v0.9.1

**Comment by voipmonitor** [comment]
> Hi everyone
> 
> Anyone found solution, i'm facing issues running lora + bnb 4 quantization
> 
> could this be related to the supported arch on v0.9.1

I have built vllm docker for the sm_120 arch which you can try - the docker image is uploaded to the docker hub - voipmonitor/inference-vllm:25.05

in case you want to build it on your machine - here is the Dockerfile I'm using (not all things inside are maybe correct, use on your own risk) 

please note that I'm using patched branch with FP8 support on blackwell. If you do not need FP8 you can change the git to the main branch 

```# syntax=docker/dockerfile:1

# Base image as specified
FROM nvcr.io/nvidia/pytorch:25.05-py3

# --- Build Arguments ---
# Use --build-arg to set this. Examples:
# Hopper (H100/H200): CUDA_ARCHS="9.0"
# Ampere (A100):      CUDA_ARCHS="8.0;8.6;8.9"
# Ada Lovelace (4090): CUDA_ARCHS="8.9" (compiles as Ampere, runs on Ada)
ARG CUDA_ARCHS="12.0"
# Corresponding format for cmake/make (e.g., "90" for Hopper, "86" for A100)
ARG CMAKE_CUDA_ARCHS="120-real"

# Set shell to bash for commands like $(nproc)
SHELL ["/bin/bash", "-c"]

# --- Environment Variables for Compilation ---
# This block corresponds to your 'export' commands.
ENV \
    # Core PyTorch Components
    USE_CUDA=1 \
    USE_CUDNN=1 \
    USE_MKLDNN=1 \
    USE_XNNPACK=1 \
    USE_DISTRIBUTED=1 \
    USE_NCCL=1 \
    USE_SYSTEM_NCCL=1 \
    \
    # Inductor + AOT stack
    USE_INDUCTOR=1 \
    USE_AOT_RUNTIME=1 \
    USE_TRITON=1 \
    USE_FUNCTORCH=1 \
    TORCHINDUCTOR_DEV=1 \
    \
    # Misc Build Flags
    BUILD_CAFFE2=0 \
    BUILD_TEST=0 \
    USE_FLASH_ATTENTION=1 \
    USE_TENSORRT=0 \
    \
    # Build Metadata & Options
    PYTORCH_BUILD_NUMBER=1 \
    MAX_JOBS=$(nproc) \
    FLASHINFER_ENABLE_AOT=1 \
    CCACHE_DIR=/root/.ccache \
    \
    # --- CRITICAL: Set CUDA Architectures from ARG ---
    TORCH_CUDA_ARCH_LIST="${CUDA_ARCHS}" \
    FLASH_ATTN_CUDA_ARCHS="${CMAKE_CUDA_ARCHS}"

# Set working directory for all our builds
WORKDIR /workspace

RUN pip install --upgrade "packaging>=24.2"

# Install essential build dependencies
# git, cmake, and ninja-build are usually in the base image, but we ensure they are present.
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    cmake \
    ninja-build \
    ccache \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Install build-time and runtime dependencies in fewer layers
RUN pip install --no-cache-dir \
    triton \
    "numpy<2.3" \
    aiohttp protobuf click rich starlette distro httpx jiter pydantic \
    safetensors uvloop uvicorn python-multipart accelerate msgpack llvmlite

# ------------------------------------------------------------------------------
# 1. Compile and Install PyTorch
# ------------------------------------------------------------------------------
#RUN git clone --recursive https://github.com/pytorch/pytorch.git
#WORKDIR /workspace/pytorch

#RUN pip install --no-cache-dir -r requirements.txt

# Build PyTorch. Using --mount for ccache to speed up rebuilds.
# Note: Changed 'install install' to the standard 'install'.
#RUN --mount=type=cache,target=/root/.ccache \
#    MAX_JOBS=$(nproc) CMAKE_BUILD_PARALLEL_LEVEL=$(nproc) python setup.py --verbose install

# ------------------------------------------------------------------------------
# 2. Compile and Install FlashInfer
# ------------------------------------------------------------------------------
WORKDIR /workspace
RUN git clone --recursive https://github.com/flashinfer-ai/flashinfer.git
WORKDIR /workspace/flashinfer

# Build FlashInfer using CMake and Ninja
#RUN  python3 -m flashinfer.aot --out-dir=/root/.cache/flashinfer --f16-dtype bfloat16  --f8-dtype float8_e4m3fn
#RUN  python3 -m flashinfer.aot --out-dir=/root/.cache/flashinfer
RUN --mount=type=cache,target=/root/.ccache \
    mkdir -p build && \
    cd build && \
    cmake .. -DCMAKE_CUDA_ARCHITECTURES="${CMAKE_CUDA_ARCHS}" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -GNinja && \
    ninja -j$(nproc)

# Install FlashInfer via pip in editable mode
RUN pip install -e . --no-build-isolation --no-deps --verbose

# ------------------------------------------------------------------------------
# 3. Compile and Install bitsandbytes
# ------------------------------------------------------------------------------
WORKDIR /workspace
RUN git clone https://github.com/bitsandbytes-foundation/bitsandbytes.git
WORKDIR /workspace/bitsandbytes

# Build bitsandbytes
RUN --mount=type=cache,target=/root/.ccache \
    cmake . -DCOMPUTE_CAPABILITY=${CMAKE_CUDA_ARCHS} -DCOMPUTE_BACKEND=cuda -DCMAKE_BUILD_TYPE=Release && \
    make -j$(nproc)

# Install bitsandbytes via pip in editable mode
RUN --mount=type=cache,target=/root/.ccache \
    pip install -e . --no-build-isolation --no-deps --verbose

WORKDIR /workspace

# Set vLLM-specific environment variables
ENV USE_CUDNN=1 \
    USE_CUSPARSELT=1 \
    NCCL_CUMEM_ENABLE=1

# Clone your specified vLLM fork
RUN git clone https://github.com/cyril23/vllm vllm-kaln27-updated/
WORKDIR /workspace/vllm-kaln27-updated/

# vLLM build process
RUN python use_existing_torch.py
RUN pip install --no-cache-dir -r requirements/build.txt
RUN pip install --no-cache-dir -r requirements/common.txt
RUN pip install --no-cache-dir setuptools_scm

# Build vLLM in development mode. Using --mount for ccache.
RUN --mount=type=cache,target=/root/.ccache \
    #MAX_JOBS=$(nproc) CMAKE_BUILD_PARALLEL_LEVEL=$(nproc) python setup.py --verbose develop
    MAX_JOBS=$(nproc) CMAKE_BUILD_PARALLEL_LEVEL=$(nproc)  pip install . --no-deps --no-build-isolation --verbose

# ------------------------------------------------------------------------------
# Finalization
# ------------------------------------------------------------------------------
# Clean up build directories to reduce final image size
#RUN rm -rf /workspace

# Set the final working directory
WORKDIR /
```

**Comment by cyril23** [comment]
by the way if anyone builds vLLM based on the current main branch of https://github.com/vllm-project/vllm with `--build-arg torch_cuda_arch_list='12.0'`  and is wondering why it does not work anymore (in contrast to vLLM builds before 11th June), check out https://github.com/vllm-project/vllm/issues/19810

**Comment by mgoin** [comment]
This will be resolved in the next release! We landed support for SM120 in the wheel and docker image https://github.com/vllm-project/vllm/pull/19794
