### ISSUE TITLE
[Bug]: unable automatically set CUDA_VISIBLE_DEVICES correctly for v0 engine data parallel

### ISSUE THREAD

**Issue by izhuhaoran** [vllm-project/vllm#16978]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.6.0+cu124
Is debug build: False
CUDA used to build PyTorch: 12.4
ROCM used to build PyTorch: N/A

OS: Ubuntu 24.04.1 LTS (x86_64)
GCC version: (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Clang version: Could not collect
CMake version: version 3.31.4
Libc version: glibc-2.39

Python version: 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0] (64-bit runtime)
Python platform: Linux-5.10.134-008.16.kangaroo.al8.x86_64-x86_64-with-glibc2.39
Is CUDA available: True
CUDA runtime version: 12.8.61
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H20
GPU 1: NVIDIA H20
GPU 2: NVIDIA H20
GPU 3: NVIDIA H20

Nvidia driver version: 550.54.15
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          80
On-line CPU(s) list:             0-79
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Processor
CPU family:                      6
Model:                           143
Thread(s) per core:              1
Core(s) per socket:              80
Socket(s):                       1
Stepping:                        8
BogoMIPS:                        5200.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx_vnni avx512_bf16 wbnoinvd avx512vbmi umip pku waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid cldemote movdiri movdir64b fsrm md_clear serialize tsxldtrk amx_bf16 avx512_fp16 amx_tile amx_int8 arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       1.9 MiB (40 instances)
L1i cache:                       1.3 MiB (40 instances)
L2 cache:                        80 MiB (40 instances)
L3 cache:                        97.5 MiB (1 instance)
NUMA node(s):                    1
NUMA node0 CPU(s):               0-79
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled, PBRSB-eIBRS: Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==2.2.4
[pip3] nvidia-cublas-cu12==12.4.5.8
[pip3] nvidia-cuda-cupti-cu12==12.4.127
[pip3] nvidia-cuda-nvrtc-cu12==12.4.127
[pip3] nvidia-cuda-runtime-cu12==12.4.127
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.2.1.3
[pip3] nvidia-curand-cu12==10.3.5.147
[pip3] nvidia-cusolver-cu12==11.6.1.9
[pip3] nvidia-cusparse-cu12==12.3.1.170
[pip3] nvidia-cusparselt-cu12==0.6.2
[pip3] nvidia-nccl-cu12==2.21.5
[pip3] nvidia-nvjitlink-cu12==12.4.127
[pip3] nvidia-nvtx-cu12==12.4.127
[pip3] pyzmq==26.4.0
[pip3] torch==2.6.0
[pip3] torchao==0.10.0
[pip3] torchdiffeq==0.2.5
[pip3] transformers==4.51.3
[pip3] triton==3.2.0
[pip3] x-transformers==2.2.11
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.1.dev5924+g4c41278.d20250422 (git sha: 4c41278.d20250422
vLLM Build Flags:
CUDA Archs: 7.5 8.0 8.6 9.0 10.0 12.0+PTX; ROCm: Disabled; Neuron: Disabled
GPU Topology:
	GPU0	GPU1	GPU2	GPU3	NIC0	NIC1	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV18	NV18	NV18	PHB	PHB	0-79	0		N/A
GPU1	NV18	 X 	NV18	NV18	PHB	PHB	0-79	0		N/A
GPU2	NV18	NV18	 X 	NV18	PHB	PHB	0-79	0		N/A
GPU3	NV18	NV18	NV18	 X 	PHB	PHB	0-79	0		N/A
NIC0	PHB	PHB	PHB	PHB	 X 	PHB				
NIC1	PHB	PHB	PHB	PHB	PHB	 X 				

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1

NVIDIA_VISIBLE_DEVICES=all
CUBLAS_VERSION=12.8.3.14
NVIDIA_REQUIRE_CUDA=cuda>=9.0
CUDA_CACHE_DISABLE=1
TORCH_CUDA_ARCH_LIST=7.5 8.0 8.6 9.0 10.0 12.0+PTX
NCCL_VERSION=2.25.1
NCCL_NVLS_ENABLE=0
NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
TORCH_NCCL_USE_COMM_NONBLOCKING=0
NCCL_DEBUG=WARN
NVIDIA_PRODUCT_NAME=PyTorch
CUDA_VERSION=12.8.0.038
PYTORCH_VERSION=2.6.0a0+ecf3bae
PYTORCH_BUILD_NUMBER=0
NCCL_DEBUG_FILE=/mnt/workspace/zhr/test/test.log
CUDNN_FRONTEND_VERSION=1.9.0
CUDNN_VERSION=9.7.0.66
PYTORCH_HOME=/opt/pytorch/pytorch
LD_LIBRARY_PATH=/usr/local/lib/python3.12/dist-packages/torch/lib:/usr/local/lib/python3.12/dist-packages/torch_tensorrt/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
NVIDIA_BUILD_ID=134983853
CUDA_DRIVER_VERSION=570.86.10
PYTORCH_BUILD_VERSION=2.6.0a0+ecf3bae
CUDA_HOME=/usr/local/cuda
CUDA_HOME=/usr/local/cuda
VLLM_LOGGING_LEVEL=INFO
CUDA_MODULE_LOADING=LAZY
NVIDIA_REQUIRE_JETPACK_HOST_MOUNTS=
NVIDIA_PYTORCH_VERSION=25.01
TORCH_ALLOW_TF32_CUBLAS_OVERRIDE=1
VLLM_USE_V1=0
NCCL_CUMEM_ENABLE=0
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
```

</details>

### 🐛 Describe the bug

I am testing data parallelism using the latest version of vLLM with the `data_parallel.py` example script (`https://github.com/vllm-project/vllm/blob/main/examples/offline_inference/data_parallel.py`). My setup includes:

- **dp-size=2**, **tp-size=2**, **enable_expert_parallel=False** (other parameters are default).
- Single node with **4x H20 GPUs**.

When using the **v1 engine** (`VLLM_USE_V1=1`), vLLM works as expected without issues. 

However, when switching to the **v0 engine** (`export VLLM_USE_V1=0`), I encounter the following error:

#### Error output with `export VLLM_LOGGING_LEVEL=DEBUG`:

```
DEBUG 04-22 18:36:47 [__init__.py:28] No plugins for group vllm.platform_plugins found.
DEBUG 04-22 18:36:47 [__init__.py:34] Checking if TPU platform is available.
DEBUG 04-22 18:36:47 [__init__.py:44] TPU platform is not available because: No module named 'libtpu'
DEBUG 04-22 18:36:47 [__init__.py:101] Checking if ROCm platform is available.
DEBUG 04-22 18:36:47 [__init__.py:115] ROCm platform is not available because: No module named 'amdsmi'
DEBUG 04-22 18:36:47 [__init__.py:123] Checking if HPU platform is available.
DEBUG 04-22 18:36:47 [__init__.py:130] HPU platform is not available because habana_frameworks is not found.
DEBUG 04-22 18:36:47 [__init__.py:141] Checking if XPU platform is available.
DEBUG 04-22 18:36:47 [__init__.py:151] XPU platform is not available because: No module named 'intel_extension_for_pytorch'
DEBUG 04-22 18:36:47 [__init__.py:159] Checking if CPU platform is available.
DEBUG 04-22 18:36:47 [__init__.py:173] CPU platform is not available because: No package metadata was found for vllm
DEBUG 04-22 18:36:47 [__init__.py:181] Checking if Neuron platform is available.
DEBUG 04-22 18:36:47 [__init__.py:188] Neuron platform is not available because: No module named 'transformers_neuronx'
INFO 04-22 18:36:47 [__init__.py:240] Automatically detected platform cuda.
DP rank 0 needs to process 4 prompts
INFO 04-22 18:36:53 [llm.py:198] Initializing LLM from vllm official.
DP rank 1 needs to process 4 prompts
INFO 04-22 18:36:53 [llm.py:198] Initializing LLM from vllm official.
DEBUG 04-22 18:36:53 [__init__.py:28] No plugins for group vllm.general_plugins found.
DEBUG 04-22 18:36:53 [__init__.py:28] No plugins for group vllm.general_plugins found.
INFO 04-22 18:37:12 [config.py:713] This model supports multiple tasks: {'generate', 'score', 'embed', 'classify', 'reward'}. Defaulting to 'generate'.
INFO 04-22 18:37:12 [config.py:1760] Defaulting to use mp for distributed inference
WARNING 04-22 18:37:12 [cuda.py:96] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
INFO 04-22 18:37:12 [llm_engine.py:243] Initializing a V0 LLM engine (v0.1.dev5924+g4c41278.d20250422) with config: model='/mnt/data/nas/tao/models/qwen2.5-42ba6b-instruct', speculative_config=None, tokenizer='/mnt/data/nas/tao/models/qwen2.5-42ba6b-instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=/mnt/data/nas/tao/models/qwen2.5-42ba6b-instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=False, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=False, 
INFO 04-22 18:37:12 [config.py:713] This model supports multiple tasks: {'generate', 'score', 'embed', 'classify', 'reward'}. Defaulting to 'generate'.
INFO 04-22 18:37:12 [config.py:1760] Defaulting to use mp for distributed inference
WARNING 04-22 18:37:12 [cuda.py:96] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
INFO 04-22 18:37:12 [llm_engine.py:243] Initializing a V0 LLM engine (v0.1.dev5924+g4c41278.d20250422) with config: model='/mnt/data/nas/tao/models/qwen2.5-42ba6b-instruct', speculative_config=None, tokenizer='/mnt/data/nas/tao/models/qwen2.5-42ba6b-instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=/mnt/data/nas/tao/models/qwen2.5-42ba6b-instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=False, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=False, 
WARNING 04-22 18:37:13 [multiproc_worker_utils.py:306] Reducing Torch parallelism from 80 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
(VllmWorkerProcess pid=490282) INFO 04-22 18:37:13 [multiproc_worker_utils.py:225] Worker ready; awaiting tasks
WARNING 04-22 18:37:13 [multiproc_worker_utils.py:306] Reducing Torch parallelism from 80 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
(VllmWorkerProcess pid=490286) INFO 04-22 18:37:13 [multiproc_worker_utils.py:225] Worker ready; awaiting tasks
INFO 04-22 18:37:17 [cuda.py:292] Using Flash Attention backend.
INFO 04-22 18:37:17 [cuda.py:292] Using Flash Attention backend.
DEBUG 04-22 18:37:17 [config.py:4031] enabled custom ops: Counter()
DEBUG 04-22 18:37:17 [config.py:4031] enabled custom ops: Counter()
DEBUG 04-22 18:37:17 [config.py:4033] disabled custom ops: Counter()
DEBUG 04-22 18:37:17 [config.py:4033] disabled custom ops: Counter()
(VllmWorkerProcess pid=490282) INFO 04-22 18:37:17 [cuda.py:292] Using Flash Attention backend.
(VllmWorkerProcess pid=490282) DEBUG 04-22 18:37:17 [config.py:4031] enabled custom ops: Counter()
(VllmWorkerProcess pid=490282) DEBUG 04-22 18:37:17 [config.py:4033] disabled custom ops: Counter()
(VllmWorkerProcess pid=490286) INFO 04-22 18:37:17 [cuda.py:292] Using Flash Attention backend.
(VllmWorkerProcess pid=490286) DEBUG 04-22 18:37:17 [config.py:4031] enabled custom ops: Counter()
(VllmWorkerProcess pid=490286) DEBUG 04-22 18:37:17 [config.py:4033] disabled custom ops: Counter()
DEBUG 04-22 18:37:18 [parallel_state.py:809] world_size=2 rank=0 local_rank=0 distributed_init_method=tcp://172.16.2.28:39847 backend=nccl
INFO 04-22 18:37:18 [parallel_state.py:825] Adjusting world_size=4 rank=0 distributed_init_method=tcp://127.0.0.1:33761 for DP
DEBUG 04-22 18:37:18 [parallel_state.py:809] world_size=2 rank=0 local_rank=0 distributed_init_method=tcp://172.16.2.28:54899 backend=nccl
INFO 04-22 18:37:18 [parallel_state.py:825] Adjusting world_size=4 rank=2 distributed_init_method=tcp://127.0.0.1:33761 for DP
[rank2]:[W422 18:37:18.243015733 ProcessGroupGloo.cpp:727] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
(VllmWorkerProcess pid=490286) DEBUG 04-22 18:37:19 [parallel_state.py:809] world_size=2 rank=1 local_rank=1 distributed_init_method=tcp://172.16.2.28:54899 backend=nccl
(VllmWorkerProcess pid=490286) INFO 04-22 18:37:19 [parallel_state.py:825] Adjusting world_size=4 rank=3 distributed_init_method=tcp://127.0.0.1:33761 for DP
(VllmWorkerProcess pid=490282) DEBUG 04-22 18:37:19 [parallel_state.py:809] world_size=2 rank=1 local_rank=1 distributed_init_method=tcp://172.16.2.28:39847 backend=nccl
(VllmWorkerProcess pid=490282) INFO 04-22 18:37:19 [parallel_state.py:825] Adjusting world_size=4 rank=1 distributed_init_method=tcp://127.0.0.1:33761 for DP
[rank1]:[W422 18:37:19.630434010 ProcessGroupGloo.cpp:727] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
[rank0]:[W422 18:37:19.634208266 ProcessGroupGloo.cpp:727] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
[rank3]:[W422 18:37:19.678597507 ProcessGroupGloo.cpp:727] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
(VllmWorkerProcess pid=490282) INFO 04-22 18:37:19 [utils.py:1043] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=490286) INFO 04-22 18:37:19 [utils.py:1043] Found nccl from library libnccl.so.2
INFO 04-22 18:37:19 [utils.py:1043] Found nccl from library libnccl.so.2
INFO 04-22 18:37:19 [utils.py:1043] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=490282) INFO 04-22 18:37:19 [pynccl.py:69] vLLM is using nccl==2.21.5
INFO 04-22 18:37:19 [pynccl.py:69] vLLM is using nccl==2.21.5
INFO 04-22 18:37:19 [pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=490286) INFO 04-22 18:37:19 [pynccl.py:69] vLLM is using nccl==2.21.5
NCCL version 2.21.5+cuda12.4
NCCL version 2.21.5+cuda12.4
INFO 04-22 18:37:20 [custom_all_reduce_utils.py:244] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
(VllmWorkerProcess pid=490286) INFO 04-22 18:37:20 [custom_all_reduce_utils.py:244] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
INFO 04-22 18:37:20 [custom_all_reduce_utils.py:244] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
(VllmWorkerProcess pid=490282) INFO 04-22 18:37:20 [custom_all_reduce_utils.py:244] reading GPU P2P access cache from /root/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
DEBUG 04-22 18:37:20 [shm_broadcast.py:221] Binding to ipc:///tmp/f066f45b-2151-468b-9538-aed981e93fd5
DEBUG 04-22 18:37:20 [shm_broadcast.py:221] Binding to ipc:///tmp/edb84537-7a54-4b36-96bf-170891992f31
INFO 04-22 18:37:20 [shm_broadcast.py:266] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_dc41c30f'), local_subscribe_addr='ipc:///tmp/f066f45b-2151-468b-9538-aed981e93fd5', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 04-22 18:37:20 [shm_broadcast.py:266] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_5e499ca8'), local_subscribe_addr='ipc:///tmp/edb84537-7a54-4b36-96bf-170891992f31', remote_subscribe_addr=None, remote_addr_ipv6=False)
(VllmWorkerProcess pid=490286) DEBUG 04-22 18:37:20 [shm_broadcast.py:290] Connecting to ipc:///tmp/f066f45b-2151-468b-9538-aed981e93fd5
(VllmWorkerProcess pid=490282) DEBUG 04-22 18:37:20 [shm_broadcast.py:290] Connecting to ipc:///tmp/edb84537-7a54-4b36-96bf-170891992f31
(VllmWorkerProcess pid=490282) INFO 04-22 18:37:20 [utils.py:1043] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=490282) INFO 04-22 18:37:20 [pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=490286) INFO 04-22 18:37:20 [utils.py:1043] Found nccl from library libnccl.so.2
INFO 04-22 18:37:20 [utils.py:1043] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=490286) INFO 04-22 18:37:20 [pynccl.py:69] vLLM is using nccl==2.21.5
INFO 04-22 18:37:20 [pynccl.py:69] vLLM is using nccl==2.21.5
INFO 04-22 18:37:20 [utils.py:1043] Found nccl from library libnccl.so.2
INFO 04-22 18:37:20 [pynccl.py:69] vLLM is using nccl==2.21.5
NCCL version 2.21.5+cuda12.4
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238] Exception in worker VllmWorkerProcess while processing method init_device.
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238] Traceback (most recent call last):
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/executor/multiproc_worker_utils.py", line 232, in _run_worker_process
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     output = run_method(worker, method, args, kwargs)
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/utils.py", line 2428, in run_method
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/worker/worker_base.py", line 604, in init_device
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     self.worker.init_device()  # type: ignore
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     ^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/worker/worker.py", line 166, in init_device
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     init_worker_distributed_environment(self.vllm_config, self.rank,
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/worker/worker.py", line 507, in init_worker_distributed_environment
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     ensure_model_parallel_initialized(parallel_config.tensor_parallel_size,
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 964, in ensure_model_parallel_initialized
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     initialize_model_parallel(tensor_model_parallel_size,
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238] Exception in worker VllmWorkerProcess while processing method init_device.
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 941, in initialize_model_parallel
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     _DP = init_model_parallel_group(group_ranks,
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238] Traceback (most recent call last):
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/executor/multiproc_worker_utils.py", line 232, in _run_worker_process
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 730, in init_model_parallel_group
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     output = run_method(worker, method, args, kwargs)
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     return GroupCoordinator(
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/utils.py", line 2428, in run_method
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 206, in __init__
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     self.device_communicator = device_comm_cls(
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]                                ^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/worker/worker_base.py", line 604, in init_device
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/cuda_communicator.py", line 39, in __init__
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     self.worker.init_device()  # type: ignore
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     self.pynccl_comm = PyNcclCommunicator(
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     ^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]                        ^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/pynccl.py", line 99, in __init__
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/worker/worker.py", line 166, in init_device
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     init_worker_distributed_environment(self.vllm_config, self.rank,
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/worker/worker.py", line 507, in init_worker_distributed_environment
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/pynccl_wrapper.py", line 277, in ncclCommInitRank
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     ensure_model_parallel_initialized(parallel_config.tensor_parallel_size,
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 964, in ensure_model_parallel_initialized
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/pynccl_wrapper.py", line 256, in NCCL_CHECK
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     initialize_model_parallel(tensor_model_parallel_size,
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     raise RuntimeError(f"NCCL error: {error_str}")
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 941, in initialize_model_parallel
(VllmWorkerProcess pid=490286) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238] RuntimeError: NCCL error: invalid usage (run with NCCL_DEBUG=WARN for details)
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     _DP = init_model_parallel_group(group_ranks,
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 730, in init_model_parallel_group
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     return GroupCoordinator(
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 206, in __init__
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     self.device_communicator = device_comm_cls(
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]                                ^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/cuda_communicator.py", line 39, in __init__
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     self.pynccl_comm = PyNcclCommunicator(
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]                        ^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/pynccl.py", line 99, in __init__
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/pynccl_wrapper.py", line 277, in ncclCommInitRank
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]   File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/pynccl_wrapper.py", line 256, in NCCL_CHECK
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238]     raise RuntimeError(f"NCCL error: {error_str}")
(VllmWorkerProcess pid=490282) ERROR 04-22 18:37:20 [multiproc_worker_utils.py:238] RuntimeError: NCCL error: invalid usage (run with NCCL_DEBUG=WARN for details)
Process Process-2:
ERROR 04-22 18:37:21 [multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 490286 died, exit code: -15
INFO 04-22 18:37:21 [multiproc_worker_utils.py:124] Killing local vLLM worker processes
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/workspace/zhr/test/test_data_parallel_official.py", line 119, in main
    llm = LLM(model=model,
          ^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/utils.py", line 1149, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/entrypoints/llm.py", line 249, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/engine/llm_engine.py", line 522, in from_engine_args
    return engine_cls.from_vllm_config(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/engine/llm_engine.py", line 498, in from_vllm_config
    return cls(
           ^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/engine/llm_engine.py", line 282, in __init__
    self.model_executor = executor_class(vllm_config=vllm_config, )
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/executor/executor_base.py", line 286, in __init__
    super().__init__(*args, **kwargs)
  File "/mnt/workspace/zhr/vllm_official/vllm/executor/executor_base.py", line 52, in __init__
    self._init_executor()
  File "/mnt/workspace/zhr/vllm_official/vllm/executor/mp_distributed_executor.py", line 124, in _init_executor
    self._run_workers("init_device")
  File "/mnt/workspace/zhr/vllm_official/vllm/executor/mp_distributed_executor.py", line 185, in _run_workers
    driver_worker_output = run_method(self.driver_worker, sent_method,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/utils.py", line 2428, in run_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/worker/worker_base.py", line 604, in init_device
    self.worker.init_device()  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/worker/worker.py", line 166, in init_device
    init_worker_distributed_environment(self.vllm_config, self.rank,
  File "/mnt/workspace/zhr/vllm_official/vllm/worker/worker.py", line 507, in init_worker_distributed_environment
    ensure_model_parallel_initialized(parallel_config.tensor_parallel_size,
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 964, in ensure_model_parallel_initialized
    initialize_model_parallel(tensor_model_parallel_size,
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 941, in initialize_model_parallel
    _DP = init_model_parallel_group(group_ranks,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 730, in init_model_parallel_group
    return GroupCoordinator(
           ^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 206, in __init__
    self.device_communicator = device_comm_cls(
                               ^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/cuda_communicator.py", line 39, in __init__
    self.pynccl_comm = PyNcclCommunicator(
                       ^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/pynccl.py", line 99, in __init__
    self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/pynccl_wrapper.py", line 277, in ncclCommInitRank
    self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/pynccl_wrapper.py", line 256, in NCCL_CHECK
    raise RuntimeError(f"NCCL error: {error_str}")
RuntimeError: NCCL error: invalid usage (run with NCCL_DEBUG=WARN for details)
INFO 04-22 18:37:21 [multiproc_worker_utils.py:124] Killing local vLLM worker processes
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/workspace/zhr/test/test_data_parallel_official.py", line 119, in main
    llm = LLM(model=model,
          ^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/utils.py", line 1149, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/entrypoints/llm.py", line 249, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/engine/llm_engine.py", line 522, in from_engine_args
    return engine_cls.from_vllm_config(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/engine/llm_engine.py", line 498, in from_vllm_config
    return cls(
           ^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/engine/llm_engine.py", line 282, in __init__
    self.model_executor = executor_class(vllm_config=vllm_config, )
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/executor/executor_base.py", line 286, in __init__
    super().__init__(*args, **kwargs)
  File "/mnt/workspace/zhr/vllm_official/vllm/executor/executor_base.py", line 52, in __init__
    self._init_executor()
  File "/mnt/workspace/zhr/vllm_official/vllm/executor/mp_distributed_executor.py", line 124, in _init_executor
    self._run_workers("init_device")
  File "/mnt/workspace/zhr/vllm_official/vllm/executor/mp_distributed_executor.py", line 185, in _run_workers
    driver_worker_output = run_method(self.driver_worker, sent_method,
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/utils.py", line 2428, in run_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/worker/worker_base.py", line 604, in init_device
    self.worker.init_device()  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/worker/worker.py", line 166, in init_device
    init_worker_distributed_environment(self.vllm_config, self.rank,
  File "/mnt/workspace/zhr/vllm_official/vllm/worker/worker.py", line 507, in init_worker_distributed_environment
    ensure_model_parallel_initialized(parallel_config.tensor_parallel_size,
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 964, in ensure_model_parallel_initialized
    initialize_model_parallel(tensor_model_parallel_size,
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 941, in initialize_model_parallel
    _DP = init_model_parallel_group(group_ranks,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 730, in init_model_parallel_group
    return GroupCoordinator(
           ^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/parallel_state.py", line 206, in __init__
    self.device_communicator = device_comm_cls(
                               ^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/cuda_communicator.py", line 39, in __init__
    self.pynccl_comm = PyNcclCommunicator(
                       ^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/pynccl.py", line 99, in __init__
    self.comm: ncclComm_t = self.nccl.ncclCommInitRank(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/pynccl_wrapper.py", line 277, in ncclCommInitRank
    self.NCCL_CHECK(self._funcs["ncclCommInitRank"](ctypes.byref(comm),
  File "/mnt/workspace/zhr/vllm_official/vllm/distributed/device_communicators/pynccl_wrapper.py", line 256, in NCCL_CHECK
    raise RuntimeError(f"NCCL error: {error_str}")
RuntimeError: NCCL error: invalid usage (run with NCCL_DEBUG=WARN for details)
/usr/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/usr/lib/python3.12/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

```

Then, I set NCCL_DEBUG=WARN, get nccl log:

```
init.cc:943 NCCL WARN Duplicate GPU detected: rank 0 and rank 1 both on CUDA device 10
```

#### Observations:

- This issue persists when changing `dp-size` (e.g., `dp-size=4`, `tp-size=1`), indicating a problem with GPU assignment across DP ranks.
- The `data_parallel.py` script claims to automatically set `CUDA_VISIBLE_DEVICES` for each DP rank, but this does not seem to work correctly in the v0 engine.

It appears that the **v0 engine** fails to properly configure `CUDA_VISIBLE_DEVICES` for data parallelism, leading to multiple ranks being assigned to the same GPU. 

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by izhuhaoran** [comment]
The [docs example](https://docs.vllm.ai/en/latest/getting_started/examples/data_parallel.html) mention that `CUDA_VISIBLE_DEVICES` is automatically set, but seems only for the v1 engine. For the v0 engine, users seem to need to manually configure it for each rank to avoid issues. Should this be clarified in the documentation?
@youkaichao @DarkLight1337

**Comment by DarkLight1337** [comment]
From my understanding, data parallelism is only implemented for V1.

**Comment by izhuhaoran** [comment]
> From my understanding, data parallelism is only implemented for V1.

Really? I set `VLLM_USE_V1=0` and manually configured `CUDA_VISIBLE_DEVICES` for each DP rank, and it worked as expected.

**Comment by yjk-66** [comment]
> > From my understanding, data parallelism is only implemented for V1.
> 
> Really? I set `VLLM_USE_V1=0` and manually configured `CUDA_VISIBLE_DEVICES` for each DP rank, and it worked as expected.

i also try to run dp in v0 engine, i manually configured `CUDA_VISIBLE_DEVICES` for each DP rank in examples/offline_inference/data_parallel.py like:

![Image](https://github.com/user-attachments/assets/f6708262-6df5-453c-9ed2-a9b5639925a8)

but get another bug like:
```DEBUG 05-14 19:55:14 [llm_engine.py:1520] Stopping remote worker execution loop.
Processed prompts: 100%|██████████████████████████████████████████████| 200/200 [00:34<00:00,  5.82it/s, est. speed input: 37.84 toks/s, output: 93.15 toks/s]
DP rank 0, Prompt: 'Hello, my name is', Generated text: " Alex. I'm 13 years old and I'm from New York."
DP rank 0, Prompt: 'The president of the United States is', Generated text: ' the head of state and government of the United States. The president leads the executive'
DP rank 0, Prompt: 'The capital of France is', Generated text: ' Paris. Paris is located in the northern part of France. The Eiffel'
DP rank 0, Prompt: 'The future of AI is', Generated text: " bright, but it's also a bit concerning. How can we ensure that AI"
DP rank 0, Prompt: 'Hello, my name is', Generated text: " John. I'm 13 years old and I'm from New York."
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yjk/vllm-new/dp-test/data_parallel.py", line 108, in main
    outputs = llm.generate(prompts, sampling_params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 1131, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/llm.py", line 473, in generate
    outputs = self._run_engine(use_tqdm=use_tqdm)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/llm.py", line 1401, in _run_engine
    step_outputs = self.llm_engine.step()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 1435, in step
    outputs = self.model_executor.execute_model(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 147, in execute_model
    output = self.collective_rpc("execute_model",
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 2347, in run_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker_base.py", line 420, in execute_model
    output = self.model_runner.execute_model(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1768, in execute_model
    with set_forward_context(model_input.attn_metadata,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/forward_context.py", line 89, in set_forward_context
    dist.all_reduce(num_tokens_tensor, group=get_dp_group().cpu_group)
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/distributed/distributed_c10d.py", line 2811, in all_reduce
    work.wait()
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [172.17.0.16]:41862
```

how did you manually configured that make it worked as expected?

**Comment by mollon650** [comment]
@yjk-66 have u solved the problem? @izhuhaoran can u provide your code how to set the env？ i have the same problem

**Comment by yjk-66** [comment]
> [@yjk-66](https://github.com/yjk-66) have u solved the problem? [@izhuhaoran](https://github.com/izhuhaoran) can u provide your code how to set the env？ i have the same problem

https://github.com/vllm-project/vllm/issues/17685#issuecomment-2855779042 
if you only have to run the dp offline demo in v0 engine, try this

**Comment by mollon650** [comment]
@yjk-66 i not only run dp offline, i also need all gather tensor between ranks, so differnet dp finish in different time but set_forward_context has the code         dist.all_reduce(num_tokens_tensor, group=get_dp_group().cpu_group)
,so if one process exit,it has the error RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [172.17.0.16]:41862, do you solved it? i try v1 version of vllm ,it not has the problem, is the schedule of v1 version    is better than v0?

**Comment by yjk-66** [comment]
https://github.com/vllm-project/vllm/issues/18702#issue-3090485917
see the similar issue i asked. maybe get_dp_group only scheduled in v1 code, im not sure. you need to check the code.
