### ISSUE TITLE
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by phatjkk** [vllm-project/vllm#1716]
My code work well yesterday but now it is not working today since the latest update (v.0.2.2)!
My code:
```python
from langchain.llms import VLLM
llm = VLLM(
    model=GENERATE_MODEL_NAME,
    trust_remote_code=True,  # mandatory for hf models
    max_new_tokens=max_new_tokens,
    top_k=10,
    top_p=0.95,
    temperature=0.8,
    # dtype="half",
    vllm_kwargs={"quantization": "awq"}
)
```
The error:
```
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/langchain/llms/vllm.py](https://localhost:8080/#) in validate_environment(cls, values)
     79             from vllm import LLM as VLLModel
     80         except ImportError:
---> 81             raise ImportError(
     82                 "Could not import vllm python package. "
     83                 "Please install it with `pip install vllm`."

ImportError: Could not import vllm python package. Please install it with `pip install vllm`.
```
I tried 'pip install vllm' many time but not fixed. I run on my Google Colab T4.
Anyone has the same issue?

**Comment by WoosukKwon** [comment]
Hi @phatjkk, could you try the CUDA-11.8 version of vLLM?
```
pip install https://github.com/vllm-project/vllm/releases/download/v0.2.2/vllm-0.2.2+cu118-cp310-cp310-manylinux1_x86_64.whl
```
vLLM v0.2.2 depends on PyTorch 2.1 and CUDA 12.1. This might cause error if you environment does not support CUDA 12.1.

**Comment by phatjkk** [comment]
Thank you for respond!
I tried install the latest version of cudatoolkit on nvidia website:
https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_network
And my code is working now, here is the code help me:
```
!wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
!sudo dpkg -i cuda-keyring_1.1-1_all.deb
!sudo apt-get update
!sudo apt-get -y install cuda-toolkit-12-3
```
If anyone has the same error you can try this!

**Comment by zhaozhaoxia** [comment]
Can it support CUDA11.6??  And How to build? please give me a  link
