### ISSUE TITLE
NCCL error

### ISSUE THREAD

**Issue by maxmelichov** [vllm-project/vllm#1726]
I'm trying to load model into LLM(model="meta-llama/Llama-2-7b-chat-hf") and I'm getting the error below

```
DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:219, invalid argument, NCCL version 2.14.3
ncclInvalidArgument: Invalid value for an argument.
Last error:
Invalid config blocking attribute value -2147483648
```

**Comment by WoosukKwon** [comment]
Hi @maxmelichov, in my experience, the error happened when using old version of pytorch. Please make sure to use `torch2.1.0+cu121` by running `pip install --upgrade torch`.

**Comment by insunkang** [comment]
same issue in cuda 11.8 , torch2.1.0+cu118

**Comment by Cucunnber** [comment]
same issue in cuda 12.1, torch 2.1.1 + cu121, did u solve it ?

**Comment by insunkang** [comment]
i solved it using cuda 11.8 nvidia driver 525.125.06. and then i got some error with xformers.  beacause the version of xformers didn't match with cuda 11.8. so i got cu118 version for xformers.

**Comment by sanfuyee** [comment]
occur the same problem

**Comment by NintendoLink** [comment]
same error.
torch                         2.1.1
torchaudio                    2.1.1
torchvision                   0.16.1

**Comment by jxh4945777** [comment]
same issue

**Comment by ywglf** [comment]
pip list | grep nccl
to check if you have two versions， you should remove the unnecessary one

**Comment by jxh4945777** [comment]
> pip list | grep nccl to check if you have two versions， you should remove the unnecessary one

THX, solved

**Comment by noelEOS** [comment]
> pip list | grep nccl to check if you have two versions， you should remove the unnecessary one

This solved it for me as well. Thanks!

**Comment by BeastyZ** [comment]
> pip list | grep nccl to check if you have two versions， you should remove the unnecessary one

It works for me, too. Thanks!

**Comment by goswamig** [comment]
```
pip install --upgrade torch
```

solved the issue for me.

torch                     2.1.2
torchaudio                2.1.2
torchvision               0.16.2

**Comment by iseesaw** [comment]
> pip list | grep nccl to check if you have two versions， you should remove the unnecessary one

Thx, I love you!

**Comment by songkq** [comment]
Same error in env. Could you please give some advice?
```
CUDA_VISIBLE_DEVICES="5,7" python3 -m vllm.entrypoints.openai.api_server --model Qwen1.5-72B-Chat-GPTQ-Int4 --port 21002 --gpu-memory-utilization 0.98 --tensor-parallel-size 2

nvidia-nccl-cu12==2.18.1
torch==2.1.2+cu121
vllm==0.3.0
```



```
File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 217, in <module>
    engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 623, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 319, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 364, in _init_engine
    return engine_class(*args, **kwargs)
  File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 109, in __init__
    self._init_workers_ray(placement_group)
  File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 271, in _init_workers_ray
    self._run_workers("init_model")
  File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 983, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/worker/worker.py", line 84, in init_model
    init_distributed_environment(self.parallel_config, self.rank,
  File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/worker/worker.py", line 253, in init_distributed_environment
    torch.distributed.all_reduce(torch.zeros(1).cuda())
  File "/workspace/envs/collie/lib/python3.10/site-packages/torch-2.1.2-py3.10-linux-x86_64.egg/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/torch-2.1.2-py3.10-linux-x86_64.egg/torch/distributed/distributed_c10d.py", line 2050, in all_reduce
    work = group.allreduce([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:219, invalid argument, NCCL version 2.16.5
ncclInvalidArgument: Invalid value for an argument.
```

**Comment by jinfengfeng** [comment]
I got the same issue. Have you solved it?

**Comment by songkq** [comment]
> @songkq I got the same issue. Have you solved it?

Not yet.


@WoosukKwon Could you please give some advice for this issue?

**Comment by songkq** [comment]
> Same error in env. Could you please give some advice?
> 
> ```
> CUDA_VISIBLE_DEVICES="5,7" python3 -m vllm.entrypoints.openai.api_server --model Qwen1.5-72B-Chat-GPTQ-Int4 --port 21002 --gpu-memory-utilization 0.98 --tensor-parallel-size 2
> 
> nvidia-nccl-cu12==2.18.1
> torch==2.1.2+cu121
> vllm==0.3.0 or 0.3.1
> ```
> 
> ```
> File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 217, in <module>
>     engine = AsyncLLMEngine.from_engine_args(engine_args)
>   File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 623, in from_engine_args
>     engine = cls(parallel_config.worker_use_ray,
>   File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 319, in __init__
>     self.engine = self._init_engine(*args, **kwargs)
>   File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 364, in _init_engine
>     return engine_class(*args, **kwargs)
>   File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 109, in __init__
>     self._init_workers_ray(placement_group)
>   File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 271, in _init_workers_ray
>     self._run_workers("init_model")
>   File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 983, in _run_workers
>     driver_worker_output = getattr(self.driver_worker,
>   File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/worker/worker.py", line 84, in init_model
>     init_distributed_environment(self.parallel_config, self.rank,
>   File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/vllm/worker/worker.py", line 253, in init_distributed_environment
>     torch.distributed.all_reduce(torch.zeros(1).cuda())
>   File "/workspace/envs/collie/lib/python3.10/site-packages/torch-2.1.2-py3.10-linux-x86_64.egg/torch/distributed/c10d_logger.py", line 47, in wrapper
>     return func(*args, **kwargs)
>   File "/workspace/miniconda3/envs/collie/lib/python3.10/site-packages/torch-2.1.2-py3.10-linux-x86_64.egg/torch/distributed/distributed_c10d.py", line 2050, in all_reduce
>     work = group.allreduce([tensor], opts)
> torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.hpp:219, invalid argument, NCCL version 2.16.5
> ncclInvalidArgument: Invalid value for an argument.
> ```

@jinfengfeng  Solved by upgrading to vllm==0.3.2

**Comment by AlexYoung757** [comment]
@songkq maybe you should retry install nccl. url:https://developer.nvidia.com/nccl/nccl-legacy-downloads
（1）update nccl mirrors
sudo dpkg -i nccl-local-repo-xxx.deb
（2）install nccl
sudo apt install libnccl2=2.18.1-1+cuda12.1 libnccl-dev=2.18.1-1+cuda12.1
（3）add nccl environment
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu

**Comment by timbmg** [comment]
> pip list | grep nccl to check if you have two versions， you should remove the unnecessary one

Thanks for the suggestion @ywglf. `pip list | grep nccl` shows me an nvidia and vllm nccl. which one is unnecessary in this case?

```text
pip list | grep nccl
nvidia-nccl-cu12          2.19.3
vllm-nccl-cu12            2.18.1.0.4.0
```

**Comment by AlexYoung757** [comment]
> > pip list | grep nccl to check if you have two versions， you should remove the unnecessary one
> 
> Thanks for the suggestion @ywglf. `pip list | grep nccl` shows me an nvidia and vllm nccl. which one is unnecessary in this case?
> 
> ```
> pip list | grep nccl
> nvidia-nccl-cu12          2.19.3
> vllm-nccl-cu12            2.18.1.0.4.0
> ```

only nvidia-nccl is necessary

**Comment by ruifengma** [comment]
> > > pip list | grep nccl to check if you have two versions， you should remove the unnecessary one
> > 
> > 
> > Thanks for the suggestion @ywglf. `pip list | grep nccl` shows me an nvidia and vllm nccl. which one is unnecessary in this case?
> > ```
> > pip list | grep nccl
> > nvidia-nccl-cu12          2.19.3
> > vllm-nccl-cu12            2.18.1.0.4.0
> > ```
> 
> only nvidia-nccl is necessary

what's vllm-nccl-cu12 for?

**Comment by hmellor** [comment]
`vllm-nccl-cu12` was a workaround to pin the NCCL version when we upgraded to PyTorch 2.2.

NCCL 2.19 (which was the new default with PyTorch 2.2) was using much more memory than NCCL 2.18 so we pinned NCCL and proceeded with the PyTorch 2.2 upgrade.

A newer workaround has since been found so `vllm-nccl-cu12` is no longer necessary.

You can read:
- from this comment onwards to learn about the PyTorch 2.2 upgrade https://github.com/vllm-project/vllm/pull/2804#issuecomment-2037712597
- this issue to learn about the issue with NCCL https://github.com/NVIDIA/nccl/issues/1234
- this PR where the workaround was replaced with a new workaround which meant we can use the latest NCCL again https://github.com/vllm-project/vllm/pull/5091

**Comment by phoenix-zmh** [comment]
you may have two nccl package, one is vllm_nccl, other is nvidia-nccl. Because vllm_nccl is default and it's not good. So, you can set nvidia-nccl as default, eg:
export VLLM_NCCL_SO_PATH=/root/miniconda3/envs/[your env name]/lib/[your python]/site-packages/nvidia/nccl/lib/libnccl.so.2

**Comment by daje0601** [comment]
For me, I solved the issue by setting `export NCCL_P2P_DISABLE=1`
