### ISSUE TITLE
Qwen3 OOM v0.8.5

### ISSUE THREAD

**Issue by cpwan** [vllm-project/vllm#17469]
**vLLM**: v0.8.5
**Model**: Qwen/Qwen3-30B-A3B
**Hardware**: A10*4, 96GB VRAM

Gives OOM, even i set max-model-len to 1024, with max-num-seq =1

Works with enforce-eager. Gives 20 token per seconds.

Works fine with SGLang 0.4.6.post1, gives 60 token per seconds.

<details>
  <summary>logs</summary>
  
```
qwen3-1  | INFO 04-29 00:57:42 [__init__.py:239] Automatically detected platform cuda.
qwen3-1  | INFO 04-29 00:57:50 [api_server.py:1043] vLLM API server version 0.8.5
qwen3-1  | INFO 04-29 00:57:50 [api_server.py:1044] args: Namespace(host=None, port=8000, uvicorn_log_level='info', disable_uvicorn_access_log=False, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key='sk-secret', lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, enable_ssl_refresh=False, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='Qwen/Qwen3-30B-A3B', task='auto', tokenizer=None, hf_config_path=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, allowed_local_media_path=None, load_format='auto', download_dir=None, model_loader_extra_config={}, use_tqdm_on_load=True, config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', max_model_len=8192, guided_decoding_backend='auto', reasoning_parser=None, logits_processor_pattern=None, model_impl='auto', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=4, data_parallel_size=1, enable_expert_parallel=False, max_parallel_loading_workers=None, ray_workers_use_nsight=False, disable_custom_all_reduce=False, block_size=None, gpu_memory_utilization=0.9, swap_space=4, kv_cache_dtype='auto', num_gpu_blocks_override=None, enable_prefix_caching=None, prefix_caching_hash_algo='builtin', cpu_offload_gb=0, calculate_kv_scales=False, disable_sliding_window=False, use_v2_block_manager=True, seed=None, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_token=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config={}, limit_mm_per_prompt={}, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=None, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=None, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', speculative_config=None, ignore_patterns=[], served_model_name=None, qlora_adapter_name_or_path=None, show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, max_num_batched_tokens=None, max_num_seqs=64, max_num_partial_prefills=1, max_long_partial_prefills=1, long_prefill_token_threshold=0, num_lookahead_slots=0, scheduler_delay_factor=0.0, preemption_mode=None, num_scheduler_steps=1, multi_step_stream_outputs=True, scheduling_policy='fcfs', enable_chunked_prefill=None, disable_chunked_mm_input=False, scheduler_cls='vllm.core.scheduler.Scheduler', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', worker_extension_cls='', generation_config='auto', override_generation_config=None, enable_sleep_mode=False, additional_config=None, enable_reasoning=False, disable_cascade_attn=False, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, enable_server_load_tracking=False)
qwen3-1  | INFO 04-29 00:58:00 [config.py:717] This model supports multiple tasks: {'generate', 'classify', 'embed', 'score', 'reward'}. Defaulting to 'generate'.
qwen3-1  | INFO 04-29 00:58:01 [config.py:1770] Defaulting to use mp for distributed inference
qwen3-1  | INFO 04-29 00:58:01 [config.py:2003] Chunked prefill is enabled with max_num_batched_tokens=2048.
qwen3-1  | INFO 04-29 00:58:07 [__init__.py:239] Automatically detected platform cuda.
qwen3-1  | INFO 04-29 00:58:10 [core.py:58] Initializing a V1 LLM engine (v0.8.5) with config: model='Qwen/Qwen3-30B-A3B', speculative_config=None, tokenizer='Qwen/Qwen3-30B-A3B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='auto', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=Qwen/Qwen3-30B-A3B, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"level":3,"custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":512}
qwen3-1  | WARNING 04-29 00:58:10 [multiproc_worker_utils.py:306] Reducing Torch parallelism from 24 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
qwen3-1  | INFO 04-29 00:58:10 [shm_broadcast.py:266] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1, 2, 3], buffer_handle=(4, 10485760, 10, 'psm_00050c59'), local_subscribe_addr='ipc:///tmp/48ef9229-a171-45ae-9528-eff23807c2cd', remote_subscribe_addr=None, remote_addr_ipv6=False)
qwen3-1  | INFO 04-29 00:58:14 [__init__.py:239] Automatically detected platform cuda.
qwen3-1  | INFO 04-29 00:58:14 [__init__.py:239] Automatically detected platform cuda.
qwen3-1  | INFO 04-29 00:58:14 [__init__.py:239] Automatically detected platform cuda.
qwen3-1  | INFO 04-29 00:58:14 [__init__.py:239] Automatically detected platform cuda.
qwen3-1  | WARNING 04-29 00:58:19 [utils.py:2522] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7fa1d4edf740>
qwen3-1  | WARNING 04-29 00:58:19 [utils.py:2522] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7fed8a34d8e0>
qwen3-1  | WARNING 04-29 00:58:19 [utils.py:2522] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7fef3bf9f470>
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 00:58:19 [shm_broadcast.py:266] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_e2d147db'), local_subscribe_addr='ipc:///tmp/00d5e6a3-8ea8-46e5-a707-3e899932b09c', remote_subscribe_addr=None, remote_addr_ipv6=False)
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 00:58:19 [shm_broadcast.py:266] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_7bfd0441'), local_subscribe_addr='ipc:///tmp/ce06e2d4-7ad0-4c0c-8aac-495426086826', remote_subscribe_addr=None, remote_addr_ipv6=False)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 00:58:19 [shm_broadcast.py:266] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_58f60516'), local_subscribe_addr='ipc:///tmp/370530fd-a341-43cd-8f1b-a5d04c639836', remote_subscribe_addr=None, remote_addr_ipv6=False)
qwen3-1  | WARNING 04-29 00:58:19 [utils.py:2522] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7f72c0ff0230>
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 00:58:19 [shm_broadcast.py:266] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_a5ec45d6'), local_subscribe_addr='ipc:///tmp/dccddf7d-b44d-4f23-9a23-51ce8ef80739', remote_subscribe_addr=None, remote_addr_ipv6=False)
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 00:58:20 [utils.py:1055] Found nccl from library libnccl.so.2
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 00:58:20 [pynccl.py:69] vLLM is using nccl==2.21.5
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 00:58:20 [utils.py:1055] Found nccl from library libnccl.so.2
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 00:58:20 [pynccl.py:69] vLLM is using nccl==2.21.5
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 00:58:20 [utils.py:1055] Found nccl from library libnccl.so.2
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 00:58:20 [pynccl.py:69] vLLM is using nccl==2.21.5
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 00:58:20 [utils.py:1055] Found nccl from library libnccl.so.2
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 00:58:20 [pynccl.py:69] vLLM is using nccl==2.21.5
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m WARNING 04-29 00:58:21 [custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m WARNING 04-29 00:58:21 [custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m WARNING 04-29 00:58:21 [custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m WARNING 04-29 00:58:21 [custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 00:58:21 [shm_broadcast.py:266] vLLM message queue communication handle: Handle(local_reader_ranks=[1, 2, 3], buffer_handle=(3, 4194304, 6, 'psm_d0f9f695'), local_subscribe_addr='ipc:///tmp/22358ed2-dec6-4e1b-812d-bb6df0196376', remote_subscribe_addr=None, remote_addr_ipv6=False)
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 00:58:21 [parallel_state.py:1004] rank 0 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 0
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 00:58:21 [cuda.py:221] Using Flash Attention backend on V1 engine.
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 00:58:21 [topk_topp_sampler.py:59] Using FlashInfer for top-p & top-k sampling.
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 00:58:21 [parallel_state.py:1004] rank 2 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 2
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 00:58:21 [parallel_state.py:1004] rank 1 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 1
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 00:58:21 [cuda.py:221] Using Flash Attention backend on V1 engine.
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 00:58:21 [cuda.py:221] Using Flash Attention backend on V1 engine.
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 00:58:21 [parallel_state.py:1004] rank 3 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 3
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 00:58:21 [topk_topp_sampler.py:59] Using FlashInfer for top-p & top-k sampling.
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 00:58:21 [topk_topp_sampler.py:59] Using FlashInfer for top-p & top-k sampling.
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 00:58:21 [cuda.py:221] Using Flash Attention backend on V1 engine.
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 00:58:21 [topk_topp_sampler.py:59] Using FlashInfer for top-p & top-k sampling.
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 00:58:21 [gpu_model_runner.py:1329] Starting to load model Qwen/Qwen3-30B-A3B...
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 00:58:21 [gpu_model_runner.py:1329] Starting to load model Qwen/Qwen3-30B-A3B...
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 00:58:21 [gpu_model_runner.py:1329] Starting to load model Qwen/Qwen3-30B-A3B...
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 00:58:21 [gpu_model_runner.py:1329] Starting to load model Qwen/Qwen3-30B-A3B...
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 00:58:22 [weight_utils.py:265] Using model weights format ['*.safetensors', '*.bin']
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 00:58:22 [weight_utils.py:265] Using model weights format ['*.safetensors', '*.bin']
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 00:58:22 [weight_utils.py:265] Using model weights format ['*.safetensors', '*.bin']
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 00:58:22 [weight_utils.py:265] Using model weights format ['*.safetensors', '*.bin']
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:   0% Completed | 0/16 [00:00<?, ?it/s]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:   6% Completed | 1/16 [00:37<09:23, 37.54s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:  12% Completed | 2/16 [00:59<06:33, 28.13s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:  19% Completed | 3/16 [01:37<07:08, 32.97s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:  25% Completed | 4/16 [02:15<06:56, 34.71s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:  31% Completed | 5/16 [02:54<06:38, 36.22s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:  38% Completed | 6/16 [03:32<06:08, 36.80s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:  44% Completed | 7/16 [04:09<05:33, 37.05s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:  50% Completed | 8/16 [04:48<05:00, 37.55s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:  56% Completed | 9/16 [05:26<04:24, 37.72s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:  62% Completed | 10/16 [06:04<03:47, 38.00s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:  69% Completed | 11/16 [06:43<03:10, 38.16s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:  75% Completed | 12/16 [07:21<02:32, 38.21s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:  81% Completed | 13/16 [07:59<01:54, 38.03s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:  88% Completed | 14/16 [08:06<00:57, 28.57s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards:  94% Completed | 15/16 [08:44<00:31, 31.60s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards: 100% Completed | 16/16 [09:18<00:00, 32.19s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
Loading safetensors checkpoint shards: 100% Completed | 16/16 [09:18<00:00, 34.89s/it]
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m 
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 01:07:40 [loader.py:458] Loading weights took 558.37 seconds
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 01:07:40 [loader.py:458] Loading weights took 558.63 seconds
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 01:07:40 [loader.py:458] Loading weights took 558.63 seconds
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 01:07:40 [loader.py:458] Loading weights took 558.57 seconds
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 01:07:41 [gpu_model_runner.py:1347] Model loading took 14.2474 GiB and 558.868858 seconds
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 01:07:41 [gpu_model_runner.py:1347] Model loading took 14.2474 GiB and 559.045517 seconds
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 01:07:41 [gpu_model_runner.py:1347] Model loading took 14.2474 GiB and 559.043662 seconds
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 01:07:41 [gpu_model_runner.py:1347] Model loading took 14.2474 GiB and 559.041898 seconds
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 01:08:02 [backends.py:420] Using cache directory: /root/.cache/vllm/torch_compile_cache/5477567bed/rank_1_0 for vLLM's torch.compile
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 01:08:02 [backends.py:420] Using cache directory: /root/.cache/vllm/torch_compile_cache/5477567bed/rank_2_0 for vLLM's torch.compile
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 01:08:02 [backends.py:420] Using cache directory: /root/.cache/vllm/torch_compile_cache/5477567bed/rank_3_0 for vLLM's torch.compile
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 01:08:02 [backends.py:420] Using cache directory: /root/.cache/vllm/torch_compile_cache/5477567bed/rank_0_0 for vLLM's torch.compile
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 01:08:02 [backends.py:430] Dynamo bytecode transform time: 21.06 s
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 01:08:02 [backends.py:430] Dynamo bytecode transform time: 21.05 s
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 01:08:02 [backends.py:430] Dynamo bytecode transform time: 21.06 s
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 01:08:02 [backends.py:430] Dynamo bytecode transform time: 21.05 s
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 01:08:11 [backends.py:136] Cache the graph of shape None for later use
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 01:08:11 [backends.py:136] Cache the graph of shape None for later use
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 01:08:11 [backends.py:136] Cache the graph of shape None for later use
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 01:08:11 [backends.py:136] Cache the graph of shape None for later use
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 01:09:00 [backends.py:148] Compiling a graph for general shape takes 56.80 s
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 01:09:01 [backends.py:148] Compiling a graph for general shape takes 57.65 s
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 01:09:02 [backends.py:148] Compiling a graph for general shape takes 58.92 s
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 01:09:02 [backends.py:148] Compiling a graph for general shape takes 59.09 s
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m WARNING 04-29 01:09:06 [fused_moe.py:668] Using default MoE config. Performance might be sub-optimal! Config file not found at /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=128,N=192,device_name=NVIDIA_A10.json
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m WARNING 04-29 01:09:06 [fused_moe.py:668] Using default MoE config. Performance might be sub-optimal! Config file not found at /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=128,N=192,device_name=NVIDIA_A10.json
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m WARNING 04-29 01:09:06 [fused_moe.py:668] Using default MoE config. Performance might be sub-optimal! Config file not found at /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=128,N=192,device_name=NVIDIA_A10.json
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m WARNING 04-29 01:09:06 [fused_moe.py:668] Using default MoE config. Performance might be sub-optimal! Config file not found at /usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/configs/E=128,N=192,device_name=NVIDIA_A10.json
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m INFO 04-29 01:09:47 [monitor.py:33] torch.compile takes 80.14 s in total
qwen3-1  | [1;36m(VllmWorker rank=2 pid=107)[0;0m INFO 04-29 01:09:47 [monitor.py:33] torch.compile takes 77.85 s in total
qwen3-1  | [1;36m(VllmWorker rank=0 pid=105)[0;0m INFO 04-29 01:09:47 [monitor.py:33] torch.compile takes 78.70 s in total
qwen3-1  | [1;36m(VllmWorker rank=3 pid=108)[0;0m INFO 04-29 01:09:47 [monitor.py:33] torch.compile takes 79.98 s in total
qwen3-1  | INFO 04-29 01:09:49 [kv_cache_utils.py:634] GPU KV cache size: 198,784 tokens
qwen3-1  | INFO 04-29 01:09:49 [kv_cache_utils.py:637] Maximum concurrency for 8,192 tokens per request: 24.27x
qwen3-1  | INFO 04-29 01:09:49 [kv_cache_utils.py:634] GPU KV cache size: 198,784 tokens
qwen3-1  | INFO 04-29 01:09:49 [kv_cache_utils.py:637] Maximum concurrency for 8,192 tokens per request: 24.27x
qwen3-1  | INFO 04-29 01:09:49 [kv_cache_utils.py:634] GPU KV cache size: 198,784 tokens
qwen3-1  | INFO 04-29 01:09:49 [kv_cache_utils.py:637] Maximum concurrency for 8,192 tokens per request: 24.27x
qwen3-1  | INFO 04-29 01:09:49 [kv_cache_utils.py:634] GPU KV cache size: 198,784 tokens
qwen3-1  | INFO 04-29 01:09:49 [kv_cache_utils.py:637] Maximum concurrency for 8,192 tokens per request: 24.27x
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470] WorkerProc hit an exception.
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470] Traceback (most recent call last):
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 465, in worker_busy_loop
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     output = func(*args, **kwargs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]              ^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_worker.py", line 242, in compile_or_warm_up_model
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     self.model_runner.capture_model()
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 1678, in capture_model
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     self._dummy_run(num_tokens)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return func(*args, **kwargs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 1497, in _dummy_run
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     outputs = model(
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]               ^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return self._call_impl(*args, **kwargs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return forward_call(*args, **kwargs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen3_moe.py", line 509, in forward
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     hidden_states = self.model(input_ids, positions, intermediate_tensors,
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/vllm/compilation/decorators.py", line 245, in __call__
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     model_output = self.forward(*args, **kwargs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/qwen3_moe.py", line 350, in forward
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     def forward(
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return self._call_impl(*args, **kwargs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return forward_call(*args, **kwargs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py", line 745, in _fn
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return fn(*args, **kwargs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/fx/graph_module.py", line 822, in call_wrapped
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return self._wrapped_call(self, *args, **kwargs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/fx/graph_module.py", line 400, in __call__
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     raise e
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/fx/graph_module.py", line 387, in __call__
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return self._call_impl(*args, **kwargs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return forward_call(*args, **kwargs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "<eval_with_key>.98", line 449, in forward
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     submod_2 = self.submod_2(getitem_3, s0, l_self_modules_layers_modules_0_modules_self_attn_modules_o_proj_parameters_weight_, getitem_4, l_self_modules_layers_modules_0_modules_post_attention_layernorm_parameters_weight_, l_self_modules_layers_modules_0_modules_mlp_modules_gate_parameters_weight_, l_self_modules_layers_modules_0_modules_mlp_modules_experts_parameters_w13_weight_, l_self_modules_layers_modules_0_modules_mlp_modules_experts_parameters_w2_weight_, l_self_modules_layers_modules_1_modules_input_layernorm_parameters_weight_, l_self_modules_layers_modules_1_modules_self_attn_modules_qkv_proj_parameters_weight_, l_self_modules_layers_modules_1_modules_self_attn_modules_q_norm_parameters_weight_, l_self_modules_layers_modules_1_modules_self_attn_modules_k_norm_parameters_weight_, l_positions_, l_self_modules_layers_modules_0_modules_self_attn_modules_rotary_emb_buffers_cos_sin_cache_);  getitem_3 = l_self_modules_layers_modules_0_modules_self_attn_modules_o_proj_parameters_weight_ = getitem_4 = l_self_modules_layers_modules_0_modules_post_attention_layernorm_parameters_weight_ = l_self_modules_layers_modules_0_modules_mlp_modules_gate_parameters_weight_ = l_self_modules_layers_modules_0_modules_mlp_modules_experts_parameters_w13_weight_ = l_self_modules_layers_modules_0_modules_mlp_modules_experts_parameters_w2_weight_ = l_self_modules_layers_modules_1_modules_input_layernorm_parameters_weight_ = l_self_modules_layers_modules_1_modules_self_attn_modules_qkv_proj_parameters_weight_ = l_self_modules_layers_modules_1_modules_self_attn_modules_q_norm_parameters_weight_ = l_self_modules_layers_modules_1_modules_self_attn_modules_k_norm_parameters_weight_ = None
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/vllm/compilation/backends.py", line 653, in __call__
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return entry.runnable(*args)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/_dynamo/eval_frame.py", line 745, in _fn
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return fn(*args, **kwargs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/aot_autograd.py", line 1184, in forward
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return compiled_fn(full_args)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 323, in runtime_wrapper
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     all_outs = call_func_at_runtime_with_args(
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/_aot_autograd/utils.py", line 126, in call_func_at_runtime_with_args
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     out = normalize_as_list(f(args))
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]                             ^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 672, in inner_fn
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     outs = compiled_fn(args)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 490, in wrapper
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return compiled_fn(runtime_args)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/output_code.py", line 466, in __call__
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return self.current_callable(inputs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/_inductor/utils.py", line 2128, in run
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return model(new_inputs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/root/.cache/vllm/torch_compile_cache/5477567bed/rank_1_0/inductor_cache/5x/c5xqlf36yrrwuc3hzszl5bgdec6wpaa5dackr5bj6hs27gla47b3.py", line 634, in call
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     torch.ops.vllm.inplace_fused_experts.default(buf7, arg6_1, arg7_1, buf15, buf1, 'silu', False, False, False, False, False, False, 128)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/torch/_ops.py", line 723, in __call__
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     return self._op(*args, **kwargs)
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]            ^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/fused_moe.py", line 986, in inplace_fused_experts
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     fused_experts_impl(hidden_states, w1, w2, topk_weights, topk_ids, True,
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/layers/fused_moe/fused_moe.py", line 1295, in fused_experts_impl
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]     cache13 = torch.empty(M * top_k_num * max(N, K),
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
qwen3-1  | [1;36m(VllmWorker rank=1 pid=106)[0;0m ERROR 04-29 01:10:12 [multiproc_executor.py:470] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 1 has a total capacity of 21.99 GiB of which 5.44 MiB is free. Including non-PyTorch memory, this process has 0 bytes memory in use. Of the allocated memory 18.91 GiB is allocated by PyTorch, with 31.88 MiB allocated in private pools (e.g., CUDA Graphs), and 128.44 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```
  
</details>

_Originally posted by @cpwan in https://github.com/vllm-project/vllm/issues/17327#issuecomment-2840716496_

**Comment by FanYaning** [comment]
try to ruduce `gpu_memory_utilization`  

as  gpu_memory_utilization=0.85

**Comment by cpwan** [comment]
Problem solved after updating to nvidia driver 550. Same config with nth changed.

**Comment by cpwan** [comment]
https://github.com/ray-project/llmperf
550 in, 150 out, running at most 128 requests

![Image](https://github.com/user-attachments/assets/196ee36b-784b-42f5-af42-59eb15874ca0)
