### ISSUE TITLE
[Bug]: torch.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by Eirx-po** [vllm-project/vllm#17835]
### Your current environment

<details>

conda list
# packages in environment at /home/conti/.conda/envs/myenv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
aiohappyeyeballs          2.6.1                    pypi_0    pypi
aiohttp                   3.11.18                  pypi_0    pypi
aiosignal                 1.3.2                    pypi_0    pypi
airportsdata              20250224                 pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
anyio                     4.9.0                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
attrs                     25.3.0                   pypi_0    pypi
blake3                    1.0.4                    pypi_0    pypi
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2025.2.25            h06a4308_0  
cachetools                5.5.2                    pypi_0    pypi
certifi                   2025.4.26                pypi_0    pypi
charset-normalizer        3.4.1                    pypi_0    pypi
click                     8.1.8                    pypi_0    pypi
cloudpickle               3.1.1                    pypi_0    pypi
compressed-tensors        0.9.3                    pypi_0    pypi
cupy-cuda12x              13.4.1                   pypi_0    pypi
deprecated                1.2.18                   pypi_0    pypi
depyf                     0.18.0                   pypi_0    pypi
dill                      0.4.0                    pypi_0    pypi
diskcache                 5.6.3                    pypi_0    pypi
distro                    1.9.0                    pypi_0    pypi
dnspython                 2.7.0                    pypi_0    pypi
einops                    0.8.1                    pypi_0    pypi
email-validator           2.2.0                    pypi_0    pypi
expat                     2.7.1                h6a678d5_0  
fastapi                   0.115.12                 pypi_0    pypi
fastapi-cli               0.0.7                    pypi_0    pypi
fastrlock                 0.8.3                    pypi_0    pypi
filelock                  3.18.0                   pypi_0    pypi
frozenlist                1.6.0                    pypi_0    pypi
fsspec                    2025.3.2                 pypi_0    pypi
gguf                      0.16.2                   pypi_0    pypi
googleapis-common-protos  1.70.0                   pypi_0    pypi
grpcio                    1.71.0                   pypi_0    pypi
h11                       0.16.0                   pypi_0    pypi
hf-xet                    1.1.0                    pypi_0    pypi
httpcore                  1.0.9                    pypi_0    pypi
httptools                 0.6.4                    pypi_0    pypi
httpx                     0.28.1                   pypi_0    pypi
huggingface-hub           0.30.2                   pypi_0    pypi
idna                      3.10                     pypi_0    pypi
importlib-metadata        8.0.0                    pypi_0    pypi
interegular               0.3.3                    pypi_0    pypi
jinja2                    3.1.6                    pypi_0    pypi
jiter                     0.9.0                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2025.4.1                 pypi_0    pypi
lark                      1.2.2                    pypi_0    pypi
ld_impl_linux-64          2.40                 h12ee557_0  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
llguidance                0.7.19                   pypi_0    pypi
llvmlite                  0.44.0                   pypi_0    pypi
lm-format-enforcer        0.10.11                  pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                3.0.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mistral-common            1.5.4                    pypi_0    pypi
modelscope                1.25.0                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.1.0                    pypi_0    pypi
msgspec                   0.19.0                   pypi_0    pypi
multidict                 6.4.3                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.4.2                    pypi_0    pypi
ninja                     1.11.1.4                 pypi_0    pypi
numba                     0.61.2                   pypi_0    pypi
numpy                     2.2.5                    pypi_0    pypi
nvidia-cublas-cu12        12.4.5.8                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.4.127                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.4.127                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.4.127                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.2.1.3                 pypi_0    pypi
nvidia-cufile-cu12        1.11.1.6                 pypi_0    pypi
nvidia-curand-cu12        10.3.5.147               pypi_0    pypi
nvidia-cusolver-cu12      11.6.1.9                 pypi_0    pypi
nvidia-cusparse-cu12      12.3.1.170               pypi_0    pypi
nvidia-cusparselt-cu12    0.6.2                    pypi_0    pypi
nvidia-nccl-cu12          2.21.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
nvidia-nvtx-cu12          12.4.127                 pypi_0    pypi
openai                    1.76.2                   pypi_0    pypi
opencv-python-headless    4.11.0.86                pypi_0    pypi
openssl                   3.0.16               h5eee18b_0  
opentelemetry-api         1.26.0                   pypi_0    pypi
opentelemetry-exporter-otlp 1.26.0                   pypi_0    pypi
opentelemetry-exporter-otlp-proto-common 1.26.0                   pypi_0    pypi
opentelemetry-exporter-otlp-proto-grpc 1.26.0                   pypi_0    pypi
opentelemetry-exporter-otlp-proto-http 1.26.0                   pypi_0    pypi
opentelemetry-proto       1.26.0                   pypi_0    pypi
opentelemetry-sdk         1.26.0                   pypi_0    pypi
opentelemetry-semantic-conventions 0.47b0                   pypi_0    pypi
opentelemetry-semantic-conventions-ai 0.4.3                    pypi_0    pypi
outlines                  0.1.11                   pypi_0    pypi
outlines-core             0.1.26                   pypi_0    pypi
packaging                 25.0                     pypi_0    pypi
partial-json-parser       0.2.1.1.post5            pypi_0    pypi
pillow                    11.2.1                   pypi_0    pypi
pip                       25.0            py312h06a4308_0  
prometheus-client         0.21.1                   pypi_0    pypi
prometheus-fastapi-instrumentator 7.1.0                    pypi_0    pypi
propcache                 0.3.1                    pypi_0    pypi
protobuf                  4.25.7                   pypi_0    pypi
psutil                    7.0.0                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pycountry                 24.6.1                   pypi_0    pypi
pydantic                  2.11.4                   pypi_0    pypi
pydantic-core             2.33.2                   pypi_0    pypi
pygments                  2.19.1                   pypi_0    pypi
python                    3.12.9               h5148396_0  
python-dotenv             1.1.0                    pypi_0    pypi
python-json-logger        3.3.0                    pypi_0    pypi
python-multipart          0.0.20                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
pyzmq                     26.4.0                   pypi_0    pypi
ray                       2.45.0                   pypi_0    pypi
readline                  8.2                  h5eee18b_0  
referencing               0.36.2                   pypi_0    pypi
regex                     2024.11.6                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rich                      14.0.0                   pypi_0    pypi
rich-toolkit              0.14.4                   pypi_0    pypi
rpds-py                   0.24.0                   pypi_0    pypi
safetensors               0.5.3                    pypi_0    pypi
scipy                     1.15.2                   pypi_0    pypi
sentencepiece             0.2.0                    pypi_0    pypi
setuptools                75.8.0          py312h06a4308_0  
shellingham               1.5.4                    pypi_0    pypi
six                       1.17.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
starlette                 0.46.2                   pypi_0    pypi
sympy                     1.13.1                   pypi_0    pypi
tiktoken                  0.9.0                    pypi_0    pypi
tk                        8.6.14               h39e8969_0  
tokenizers                0.21.1                   pypi_0    pypi
torch                     2.6.0                    pypi_0    pypi
torchaudio                2.6.0                    pypi_0    pypi
torchvision               0.21.0                   pypi_0    pypi
tqdm                      4.67.1                   pypi_0    pypi
transformers              4.51.3                   pypi_0    pypi
triton                    3.2.0                    pypi_0    pypi
typer                     0.15.3                   pypi_0    pypi
typing-extensions         4.13.2                   pypi_0    pypi
typing-inspection         0.4.0                    pypi_0    pypi
tzdata                    2025a                h04d1e81_0  
urllib3                   2.4.0                    pypi_0    pypi
uvicorn                   0.34.2                   pypi_0    pypi
uvloop                    0.21.0                   pypi_0    pypi
vllm                      0.8.5.post1              pypi_0    pypi
watchfiles                1.0.5                    pypi_0    pypi
websockets                15.0.1                   pypi_0    pypi
wheel                     0.45.1          py312h06a4308_0  
wrapt                     1.17.2                   pypi_0    pypi
xformers                  0.0.29.post2             pypi_0    pypi
xgrammar                  0.1.18                   pypi_0    pypi
xz                        5.6.4                h5eee18b_1  
yarl                      1.20.0                   pypi_0    pypi
zipp                      3.21.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1  ``

vllm serve /mnt/AI/models/vllm/  --dtype auto --gpu_memory_utilization 0.9 --tensor-parallel-size 2 --trust-remote-code --port 8002

(VllmWorker rank=1 pid=194255) ERROR 05-08 14:46:12 [multiproc_executor.py:435] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 270.00 MiB. GPU 1 has a total capacity of 21.98 GiB of which 156.94 MiB is free. Including non-PyTorch memory, this process has 21.80 GiB memory in use. Of the allocated memory 21.42 GiB is allocated by PyTorch, and 24.12 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

nvidia-smi
Thu May  8 14:59:52 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.163.01             Driver Version: 550.163.01     CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A10                     Off |   00000000:3B:00.0 Off |                    0 |
|  0%   43C    P0             58W /  150W |     257MiB /  23028MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A10                     Off |   00000000:D8:00.0 Off |                    0 |
|  0%   31C    P8              9W /  150W |      17MiB /  23028MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      2287      G   /usr/lib/xorg/Xorg                              4MiB |
|    0   N/A  N/A      3346    C+G   ...libexec/gnome-remote-desktop-daemon        229MiB |
|    1   N/A  N/A      2287      G   /usr/lib/xorg/Xorg                              4MiB |
+-----------------------------------------------------------------------------------------+

</details>

貌似是 troch 吧正在使用的显存值 赋给了可用显存值，导致无法分配现存报错。

### 🐛 Describe the bug

torch.OutOfMemoryError: CUDA out of memory 

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Eirx-po** [comment]
vllm serve /mnt/AI/models/vllm/  --dtype auto --gpu_memory_utilization 0.5 --tensor-parallel-size 2 --trust-remote-code --port 8002 --enforce-eager --disable-frontend-multiprocessing --disable-custom-all-reduce --max_num_batched_tokens 2048 --max-num-seqs 16
This's my command now  but still have this issue: 

error:           ^^^^^^^^^^^^^^^^^^^^^
(VllmWorker rank=1 pid=567343) ERROR 05-09 09:07:03 [multiproc_executor.py:435] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 270.00 MiB. GPU 1 has a total capacity of 21.98 GiB of which 147.62 MiB is free. Process 267753 has 18.78 GiB memory in use. Including non-PyTorch memory, this process has 3.03 GiB memory in use. Of the allocated memory 2.66 GiB is allocated by PyTorch, and 20.84 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)


I think it's the mismatch the free RAM and used RAM...

**Comment by magicsong** [comment]
what is your model

**Comment by Eirx-po** [comment]
Deepseek R1-32B

**Comment by magicsong** [comment]
> Deepseek R1-32B

The 32B model needs 90GB+ VRAM. With your two 24GB cards (48GB total), you’d need almost double that. 😊

**Comment by Double680** [comment]
The same issue ...
I am trying to deploy a 16B model (Kimi-VL-A3B-Thinking) on one A800 80GB, yet it returned "CUDA out of memory"

```
LLM(
    model=model_path, # local_dir to Kimi-VL-A3B-Thinking from modelscope
    trust_remote_code=True,
    tensor_parallel_size=1
    gpu_memory_utilization=0.9,
    disable_mm_preprocessor_cache=True,
    limit_mm_per_prompt={"image": 2}
)
```

The error information is 
```
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 289.53 GiB. GPU 0 has a total capacity of 79.32 GiB of which 31.52 GiB is free. Process 2054080 has 47.80 GiB memory in use. Of the allocated memory 47.13 GiB is allocated by PyTorch, and 179.14 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management
```

Python Version: 3.11.11
PyTorch Version: 2.6.0
vllm Version: 0.8.5.post1

**Comment by Double680** [comment]
It's my problem... I re-install the package `flash-attn` and it works...
Anyway, thanks for your reply.

**Comment by Eirx-po** [comment]
So 32B models request for 96G~~ but ollama just request for 24G VRAM...
So what models you suggest?

**Comment by magicsong** [comment]
> So 32B models request for 96G~~ but ollama just request for 24G VRAM... So what models you suggest?

Ollama will offload part of the inference process to the CPU, but this will significantly reduce QPS. I would recommend using an 8B model

**Comment by Eirx-po** [comment]
OK thanks, I tried downgrade to vllm 0.8.3 with DeepSeek-R1-Distill-Llama-8B, it works.
thank you very much!

**Comment by nizuzihengui99** [comment]
why  my previous vllm version 0.7.2 and limit_mm_per_prompt '{"image": 20, "video": 2}' is ok ,but now vllm version 0.8.5.post1 the Same parameters limit_mm_per_prompt '{"image": 20, "video": 2}' but error CUDA out of memory . other parameters  no changes

**Comment by Ericoool9614** [comment]
> why my previous vllm version 0.7.2 and limit_mm_per_prompt '{"image": 20, "video": 2}' is ok ,but now vllm version 0.8.5.post1 the Same parameters limit_mm_per_prompt '{"image": 20, "video": 2}' but error CUDA out of memory . other parameters no changes

similar problem. I can run 2 Qwen2vl2b processes with gpu_memory_utilization=0.35 and vllm==0.6.1, while with the vllm==0.8.5, there is error CUDA out of memory, I have to set gpu_memory_utilization=0.55 and can only run 1 process.
