### ISSUE TITLE
CUDA OOM on Multi GPU but works on single GPU, multiple models

### ISSUE THREAD

**Issue by d4munche3z** [vllm-project/vllm#1792]
I attempted to run a number of models through two GPU and got OOM however this was successful with single GPU. Initially I thought my model was too large when running a 34B version and scaled down to 6.7B however it did not work with 6.7B either. But testing the 6.7B with single GPU worked so I am assuming this is an issue with the distributed compute with multiple GPU rather than an actual memory constraint. 

Models tested: 
TheBloke/deepseek-coder-6.7B-instruct-AWQ
TheBloke/deepseek-coder-33B-instruct-AWQ
TheBloke/Phind-CodeLlama-34B-v2-AWQ

python -m vllm.entrypoints.openai.api_server --model TheBloke/deepseek-coder-6.7B-instruct-AWQ --served-model-name gpt-3.5-turbo-16k-0613 --tensor-parallel-size 2 --max-model-len 16384 --quantization awq --dtype half --load-format safetensors --tokenizer-mode auto --trust-remote-code & npx localtunnel --port 8000
[6] 11724
your url is: https://heavy-bags-hide.loca.lt
INFO 11-26 14:01:26 api_server.py:638] args: Namespace(host=None, port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name='gpt-3.5-turbo-16k-0613', model='TheBloke/deepseek-coder-6.7B-instruct-AWQ', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='safetensors', dtype='half', max_model_len=16384, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization='awq', engine_use_ray=False, disable_log_requests=False, max_log_len=None)
WARNING 11-26 14:01:26 config.py:140] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
2023-11-26 14:01:27,757	INFO worker.py:1673 -- Started a local Ray instance.
INFO 11-26 14:01:28 llm_engine.py:72] Initializing an LLM engine with config: model='TheBloke/deepseek-coder-6.7B-instruct-AWQ', tokenizer='TheBloke/deepseek-coder-6.7B-instruct-AWQ', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=16384, download_dir=None, load_format=safetensors, tensor_parallel_size=2, quantization=awq, seed=0)
Traceback (most recent call last):
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/munche3z/miniconda3/envs/devteam/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, r

**Comment by viktor-ferenczi** [comment]
Which vLLM version? On what two GPUs?

**Comment by d4munche3z** [comment]
I haven't tried without AWQ but since the model was quantized with that would it still be compatible if I am not selecting that for quantization? I am on 0.2.2 on two rtx 3090.

**Comment by d4munche3z** [comment]
I ran without AWQ quantization and it works. However, I was under the impression that the --tensor-parallel-size would partition  the model between the two gpus however both gpu is utilizing the same amount of memory roughly 18gb, while when I had been running on a single GPU (with AWQ) it was running at 14.5gb. My expectation is that the ram utilization should be half on two devices. 

Would you be able to give me insight on this? 

Also, is AWQ quantization not implemented on multigpu? 

![image](https://github.com/vllm-project/vllm/assets/64295671/533c030c-60bf-4bfe-881e-1f406091c301)


python -m vllm.entrypoints.openai.api_server --model TheBloke/deepseek-coder-6.7B-instruct-AWQ --served-model-name gpt-3.5-turbo-16k-0613 --tensor-parallel-size 2 --max-model-len 16384 --dtype half --load-format safetensors --tokenizer-mode auto --trust-remote-code & npx localtunnel --port 8000
[2] 3381
your url is: https://slimy-horses-visit.loca.lt
INFO 11-27 23:44:55 api_server.py:638] args: Namespace(host=None, port=8000, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], served_model_name='gpt-3.5-turbo-16k-0613', model='TheBloke/deepseek-coder-6.7B-instruct-AWQ', tokenizer=None, revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='safetensors', dtype='half', max_model_len=16384, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, block_size=16, seed=0, swap_space=4, gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, max_paddings=256, disable_log_stats=False, quantization=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
WARNING 11-27 23:44:55 config.py:140] awq quantization is not fully optimized yet. The speed can be slower than non-quantized models.
2023-11-27 23:44:58,266	INFO worker.py:1673 -- Started a local Ray instance.
INFO 11-27 23:44:58 llm_engine.py:72] Initializing an LLM engine with config: model='TheBloke/deepseek-coder-6.7B-instruct-AWQ', tokenizer='TheBloke/deepseek-coder-6.7B-instruct-AWQ', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=16384, download_dir=None, load_format=safetensors, tensor_parallel_size=2, quantization=awq, seed=0)
INFO 11-27 23:45:12 llm_engine.py:207] # GPU blocks: 3824, # CPU blocks: 1024
INFO:     Started server process [3381]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

**Comment by leocnj** [comment]
From your log, it seems that AWQ has been used although it was not called in the Python command line.
```
INFO 11-27 23:44:58 llm_engine.py:72] Initializing an LLM engine with config: model='TheBloke/deepseek-coder-6.7B-instruct-AWQ', tokenizer='TheBloke/deepseek-coder-6.7B-instruct-AWQ', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=16384, download_dir=None, load_format=safetensors, tensor_parallel_size=2, quantization=awq, seed=0)
```

**Comment by viktor-ferenczi** [comment]
Engine arguments from log (wrapped for readability):
```
args: Namespace(host='0.0.0.0', port=8000, allow_credentials=False, allowed_origins=['*'], 
allowed_methods=['*'], allowed_headers=['*'], served_model_name='model', 
model='/home/viktor/models/TheBloke/deepseek-coder-33B-instruct-AWQ', tokenizer=None, 
revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, 
download_dir=None, load_format='safetensors', dtype='half', max_model_len=16384, 
worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, 
max_parallel_loading_workers=None, block_size=16, seed=0, swap_space=4, 
gpu_memory_utilization=0.9, max_num_batched_tokens=None, max_num_seqs=256, 
max_paddings=256, disable_log_stats=False, quantization=None, engine_use_ray=False, 
disable_log_requests=True, max_log_len=None)
```

**Comment by viktor-ferenczi** [comment]
Passing `--max-num-seqs=1` fixes the OOM. 

Getting 41 t/s for single stream, 217 t/s in total while running 32 generations in parallel (async client).

VRAM usage:
```
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:0B:00.0 Off |                  Off |
| 30%   36C    P2              77W / 350W |  16676MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        On  | 00000000:0C:00.0 Off |                  Off |
| 30%   40C    P2              85W / 350W |  16676MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by viktor-ferenczi** [comment]
VRAM usage on each of the GPUs according to various values of the `--max-num-seqs` option:

```csv
max-num-seqs,VRAM1 [MB],VRAM1 [MB]
1,16676,16676
2,18248,18288
4,21192,21192
8,19136,19136
16,22370,22368
```

**Remarks**
- VRAM reported by `nvidia-smi` after test run.
- I have not tried non-power-of-2 values.

As far as I understand vLLM will use up the remaining free VRAM as KV-cache eventually, which is normal.

Generation speed was around 41 tokens/second for each sequence processed. Processing them in parallel results in significantly higher throughput. Your optimal value will depend on the average number of parallel requests you can feed into vLLM and how much your workload benefits from the KV-cache. Experiment with it and find your best value.

**Comment by viktor-ferenczi** [comment]
A bit off-topic, but I compared it to llama-cpp running the same test against the `server` binary with 32 slots and the 8-bit GGUF model. It was using ~21GB VRAM on both GPUs, which is about the same as vLLM.

Model: `TheBloke/deepseek-coder-33B-instruct-GGUF/deepseek-coder-33b-instruct.Q8_0.gguf`

Result: `Generated 8631 tokens in 147.7s (58.4 tokens/s)`

It returned less than 100 tokens for some of the sequences, that's okay.

vLLM is faster in this case, as expected. But vLLM was running with the 4-bit AWQ model above, while llama.cpp could keep up this performance with the 8-bit quantized model, which has higher quality in theory. So there is a performance-quality trade-off here at similar VRAM requirements.

**Comment by d4munche3z** [comment]
Thank you for the unexpectedly detailed response, this had solved my problem and also provided me very good insight on working with these models!
