### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by SunixLiu** [vllm-project/vllm#188]
I successfully installed vLLM in WSL2, when I was trying to run the sample code, I got error info like this:

```
from vllm import LLM, SamplingParams

prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
llm = LLM(model="/mnt/d/github/text-generation-webui/models/facebook_opt-125m")

outputs = llm.generate(prompts, sampling_params)

# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```

INFO 06-21 21:40:02 llm_engine.py:59] Initializing an LLM engine with config: model='/mnt/d/github/text-generation-webui/models/facebook_opt-125m', dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
INFO 06-21 21:40:12 llm_engine.py:128] # GPU blocks: 37375, # CPU blocks: 7281
Traceback (most recent call last):
  File "/mnt/d/01Projects/vllm/prac_1.py", line 11, in <module>
    llm = LLM(model="/mnt/d/github/text-generation-webui/models/facebook_opt-125m")
  File "/mnt/d/github/vllm/vllm/entrypoints/llm.py", line 55, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/mnt/d/github/vllm/vllm/engine/llm_engine.py", line 145, in from_engine_args
    engine = cls(*engine_configs, distributed_init_method, devices,
  File "/mnt/d/github/vllm/vllm/engine/llm_engine.py", line 102, in __init__
    self._init_cache()
  File "/mnt/d/github/vllm/vllm/engine/llm_engine.py", line 134, in _init_cache
    self._run_workers("init_cache_engine", cache_config=self.cache_config)
  File "/mnt/d/github/vllm/vllm/engine/llm_engine.py", line 307, in _run_workers
    output = executor(*args, **kwargs)
  File "/mnt/d/github/vllm/vllm/worker/worker.py", line 126, in init_cache_engine
    self.cache_engine = CacheEngine(
  File "/mnt/d/github/vllm/vllm/worker/cache_engine.py", line 41, in __init__
    self.cpu_cache = self.allocate_cpu_cache()
  File "/mnt/d/github/vllm/vllm/worker/cache_engine.py", line 89, in allocate_cpu_cache
    key_blocks = torch.empty(
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Python: 3.10.11
GPU: RTX 3090 24G
Linux: WSL2, Ubuntu 20.04.6 LTS
Can anyone help to answer this?

**Comment by zhuohan123** [comment]
The OPT-125M is very small and this cannot happen. While I cannot reproduce the exact error on my side, when you initialize the LLM class, can you try to add the following argument: `gpu_memory_utilization=0.98`? The default utilization upper bound is 0.90.

**Comment by SunixLiu** [comment]
I added two lines:
```
import os
os.environ ['CUDA_LAUNCH_BLOCKING'] ='1'
```

and this `gpu_memory_utilization=0.50` .

but it seems the error info is the same:

INFO 06-21 22:53:33 llm_engine.py:59] Initializing an LLM engine with config: model='/mnt/d/github/text-generation-webui/models/facebook_opt-125m', dtype=torch.float16, use_dummy_weights=False, download_dir=None, use_np_weights=False, tensor_parallel_size=1, seed=0)
INFO 06-21 22:53:41 llm_engine.py:128] # GPU blocks: 19899, # CPU blocks: 7281
Traceback (most recent call last):
  File "/mnt/d/01Projects/vllm/prac_1.py", line 14, in <module>
    llm = LLM(model="/mnt/d/github/text-generation-webui/models/facebook_opt-125m",gpu_memory_utilization=0.50)
  File "/mnt/d/github/vllm/vllm/entrypoints/llm.py", line 55, in __init__
    self.llm_engine = LLMEngine.from_engine_args(engine_args)
  File "/mnt/d/github/vllm/vllm/engine/llm_engine.py", line 145, in from_engine_args
    engine = cls(*engine_configs, distributed_init_method, devices,
  File "/mnt/d/github/vllm/vllm/engine/llm_engine.py", line 102, in __init__
    self._init_cache()
  File "/mnt/d/github/vllm/vllm/engine/llm_engine.py", line 134, in _init_cache
    self._run_workers("init_cache_engine", cache_config=self.cache_config)
  File "/mnt/d/github/vllm/vllm/engine/llm_engine.py", line 307, in _run_workers
    output = executor(*args, **kwargs)
  File "/mnt/d/github/vllm/vllm/worker/worker.py", line 126, in init_cache_engine
    self.cache_engine = CacheEngine(
  File "/mnt/d/github/vllm/vllm/worker/cache_engine.py", line 41, in __init__
    self.cpu_cache = self.allocate_cpu_cache()
  File "/mnt/d/github/vllm/vllm/worker/cache_engine.py", line 89, in allocate_cpu_cache
    key_blocks = torch.empty(
RuntimeError: CUDA error: out of memory
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by zhuohan123** [comment]
Just to make sure it's not the model's issue, can you run `facebook/opt-125m` model?

**Comment by dcruiz01** [comment]
I'm running into the same issue. I'm on Ubuntu WSL2, CUDA 11.8, and RTX 2080Ti, which should easily be able to accommodate opt-125m. I've tried other small models, such as cerebras/Cerebras-GPT-111M and distilgpt2, but those give different errors (probably due to architecture incompatibility?).

I've confirmed I can run opt-125m via standard transformers library...any other ideas what might be causing the issue @zhuohan123  @WoosukKwon ?

**Comment by SunixLiu** [comment]
> Just to make sure it's not the model's issue, can you run `facebook/opt-125m` model?

Yes, I can use text-generation-webui to load `facebook/opt-125m` and get it work.

**Comment by AlpinDale** [comment]
Currently having this issue as well. The `CUDA_VISIBLE_DEVICES` environment variable has no effect either, and it only loads the models to GPU 0. I'm running on A100s but still get OOM with 125m OPT. There's something fatally wrong with this repo.

**Comment by WoosukKwon** [comment]
@dcruiz01 @SunixLiu @AlpinDale vLLM is designed to take almost all of your GPU memory. Could you double-check your GPU is not used by other processes when using vLLM?

**Comment by AlpinDale** [comment]
> @dcruiz01 @SunixLiu @AlpinDale vLLM is designed to take almost all of your GPU memory. Could you double-check your GPU is not used by other processes when using vLLM?

Thanks, I think I understand now. A *somewhat* related question - how is multi-GPU handled? If I load a bigger model, will it split across the available GPUs? Also, if I want more memory to accommodate more users on a single, smaller model, can I have the process use multiple GPUs at once?

**Comment by WoosukKwon** [comment]
@AlpinDale Good question. You can use the `tensor_parallel_size` argument for multi-GPU inference.
First, initialize your Ray cluster by executing
```bash
$ ray start --head
```

Then, use the `tensor_parallel_size` argument in the LLM class:
```python
llm = LLM(model=<your model>, tensor_parallel_size=2)  # Inference with 2 GPUs 
```

**Comment by SunixLiu** [comment]
> @dcruiz01 @SunixLiu @AlpinDale vLLM is designed to take almost all of your GPU memory. Could you double-check your GPU is not used by other processes when using vLLM?

I'm pretty sure there's no other process was using my GPU, and here's the screenshot, you can find a burst in both GPU 3D and VRAM, that happended when the code was trying to load the model.
<img width="559" alt="image" src="https://github.com/vllm-project/vllm/assets/34759356/83b75c96-a32b-4630-b772-f3565b16f462">

**Comment by dcruiz01** [comment]
I'm seeing the same as @SunixLiu. Nothing else is happening on my GPU. Running the code at the top of this issue spikes the GPU and then crashes.

**Comment by dcruiz01** [comment]
Any new developments here? @zhuohan123

**Comment by zhuohan123** [comment]
@SunixLiu @dcruiz01 We believe this is actually a bug. We are not sure whether this is caused by WSL or vLLM. We don't have a Windows environment with GPUs. How about we set up a 30-min meeting to pair-debug on your environments? Please check your emails.

**Comment by zhuohan123** [comment]
Just pair-debugged with @SunixLiu and we successfully locate the issue. As a temporary fix, please comment out `pin_memory=True` in vLLM code when allocating CPU cache:

https://github.com/vllm-project/vllm/blob/4026a049d3ad510bea8e177bf71722bd510fbb46/vllm/worker/cache_engine.py#L89-L97

It seems like `pin_memory` does not work properly on WSL. After commenting out this, vLLM should work properly.

**Comment by SunixLiu** [comment]
Thank you @zhuohan123 for helping this.
Issue closed.

**Comment by dcruiz01** [comment]
> Just pair-debugged with @SunixLiu and we successfully locate the issue. As a temporary fix, please comment out `pin_memory=True` in vLLM code when allocating CPU cache:
> 
> https://github.com/vllm-project/vllm/blob/4026a049d3ad510bea8e177bf71722bd510fbb46/vllm/worker/cache_engine.py#L89-L97
> 
> `pin_memory` has a limit in WSL ([official doc](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#known-limitations-for-linux-cuda-applications)) and the limit [seems to be 2GB](https://www.reddit.com/r/StableDiffusion/comments/y2fca2/does_your_wsl_linux_allow_you_to_pin_more_than/). After commenting out this, vLLM should work properly.

Hey thank you so much for getting to the bottom of this! Never saw an email, but I'm glad you were able to figure it out with @SunixLiu. Looking forward to testing out the fix.

**Comment by lucasjinreal** [comment]
Got OOM too as well, on 32GB v100 and using 7B llama model, it shouldn't OOM, why?

**Comment by FarziBuilder** [comment]
> ```python
> , tensor_parallel_size=2
> ```

I don't understand how will i do that? do u want me to fork vLLM, change the source code and then re-run?

**Comment by FarziBuilder** [comment]
> Just pair-debugged with @SunixLiu and we successfully locate the issue. As a temporary fix, please comment out `pin_memory=True` in vLLM code when allocating CPU cache:
> 
> https://github.com/vllm-project/vllm/blob/4026a049d3ad510bea8e177bf71722bd510fbb46/vllm/worker/cache_engine.py#L89-L97
> 
> `pin_memory` has a limit in WSL ([official doc](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#known-limitations-for-linux-cuda-applications)) and the limit [seems to be 2GB](https://www.reddit.com/r/StableDiffusion/comments/y2fca2/does_your_wsl_linux_allow_you_to_pin_more_than/). After commenting out this, vLLM should work properly.

@zhuohan123 i don't understand how to do that. Do u want us to fork vLLM, change the source code and then re-run.

Or is there any simpler way?

**Comment by allanwakes** [comment]
I run into the same error, I tried to run Baichuan2-7B-Chat-4bits alone, and it worked.
But with vllm, it went to oom.
No WSL, RTX 3060, 12G

**Comment by flexchar** [comment]
@allanwakes @prashantskit have you come across a solution?

I'm seeing same with Mistral 7B on RTX 3090 24GB

**Comment by nosolosoft** [comment]
Mistral 7b on RTX4060 16GB fails. With ollama for example it doesn't

**Comment by flexchar** [comment]
After setting `--max-model-len 8192` the OOM went away. @nosolosoft, what if you try using `--max-model-len 4096`? I also use an AWQ quant with `--quantization awq` parameter. Works amazing!

**Comment by gordicaleksa** [comment]
I'm hitting this same issue on Ubuntu, 48GB of VRAM (2xRTX3090), using OPT-125M model.

I'm comfortably using large ML systems on my rig in general.

the pin memory hack works for ubuntu as well, I've just set it to False as a tmp workaround.

**Comment by gordicaleksa** [comment]
Ok, I've done some debugging, this function is literally designed to allocate GPU memory as max as possible (up to what's set in the `gpu_memory_utilization`). What's the reasoning behind this design decision?

![image](https://github.com/vllm-project/vllm/assets/29271842/9a842775-5fcc-4835-b492-6c0c262e22ea)

**Comment by mendhak** [comment]
With Mistral as well on Ubuntu, I'm getting the CUDA out of memory error, and playing with `--gpu-memory-utilization` doesn't seem to make a difference. 

```bash
python -u -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --model mistralai/Mistral-7B-v0.1 --dtype half --gpu-memory-utilization 0.8  --max-model-len 4096
```

results in:

> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 224.00 MiB (GPU 0; 10.73 GiB total capacity; 9.85 GiB already allocated; 46.44 MiB free; 9.86 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.

I tried to follow the AWQ advice above and this works:

```bash
python -u -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --model TheBloke/Mistral-7B-OpenOrca-AWQ --dtype half --gpu-memory-utilization 0.7  --max-model-len 4096 --quantization awq
```

(Ubuntu 22.04, RTX 2080 Ti, 32GB RAM)

But I'm not sure how to get the original Mistral running. Anything I'm missing?

**Comment by tongyx361** [comment]
In my case (pure Linux with A100(80GB)),
decreasing swap_space (perhaps under the corresponding value of GPU memory * gpu_memory_utilization) helps.

**Comment by yiakwy-xpu-ml-framework-team** [comment]
> Ok, I've done some debugging, this function is literally designed to allocate GPU memory as max as possible (up to what's set in the `gpu_memory_utilization`). What's the reasoning behind this design decision?
> 
> Edit: I know see that this is by design, you occupy all available GPU memory in case new instances are spawned? So then it must be some other bug. I stepped into the code and OPT-125M by itself only occupied a small amount of memory until this GPU allocation happened. I'll limit the `gpu_memory_utilization` as a tmp workaround.
> 
> ![image](https://private-user-images.githubusercontent.com/29271842/280799090-9a842775-5fcc-4835-b492-6c0c262e22ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyODQzNjcsIm5iZiI6MTcxNDI4NDA2NywicGF0aCI6Ii8yOTI3MTg0Mi8yODA3OTkwOTAtOWE4NDI3NzUtNWZjYy00ODM1LWI0OTItNmMwYzI2MmUyMmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA2MDEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNjc3Zjc4NGFiN2RmZjdmODRlZWRmMWU0OWYxZTYxNzBhY2ZiYzJmMjRjODdiZWUzNjg4MzBjNzZlODUxMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sXmFoTEH0ty-KjpbO4LhhS85k-N1V6RThuMMuE_TD4I)

Note in the latest code, vllm allocating blocks with pin_memory. The problems that also try utilize all the memory, so when you load a small model like lllama 7b with A100, it will go out of memory by default. Hope this message helps.

**Comment by yiakwy-xpu-ml-framework-team** [comment]
您好，邮箱主人会认真阅读！谢谢关注/

**Comment by piotrmasior** [comment]
```
[rank0]:   File "/home/pmasior/miniconda3/envs/vllm2/lib/python3.10/site-packages/vllm/worker/cache_engine.py", line 64, in _allocate_kv_cache
[rank0]:     torch.empty(kv_cache_shape,
[rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.70 GiB. GPU 
```
![image](https://github.com/vllm-project/vllm/assets/1107041/0e752ce9-89e0-4a6b-86f7-5674f29c7bed)
1,7gb my ass :D

same issue as @LGLG42 

not working on python 3.9 nor 3.10
```
nvidia-smi
Sat May 25 23:52:09 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0  On |                  Off |
|  0%   58C    P8              21W / 450W |   2539MiB / 24564MiB |      7%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by piotrmasior** [comment]
this works:
```
python -m vllm.entrypoints.openai.api_server --model facebook/opt-125m --gpu-memory-utilization 0.8
```
but memory being reserved... is funny
![image](https://github.com/vllm-project/vllm/assets/1107041/10cd68ef-a4e4-4fc0-8f8b-601c8d8775d5)

**Comment by piotrmasior** [comment]
I do not know if it will help someone, but it looks like you need to fine tune manually --gpu-memory-utilization
for instance that works:
```
python -m vllm.entrypoints.openai.api_server --model facebook/opt-125m --gpu-memory-utilization 0.05
```
but 0.04 throws:
```
ValueError: The model's max seq len (2048) is larger than the maximum number of tokens that can be stored in KV cache (1344). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.
```

so in my case manipulating both parameters manually set you up...

cheers

**Comment by Daya-Jin** [comment]
lower the gpu-memory-utilization works for me(8*A800 80GB). 

python -m vllm.entrypoints.openai.api_server --model /Qwen-7B-Chat --dtype bfloat16 --api-key token-abc123 --trust-remote-code --gpu-memory-utilization 0.3 --max-model-len 4096

**Comment by nate-walter** [comment]
I’m from the future, December of the year 2024. And I’m still getting this CUDA Out of Memory error. I’m using 5 RTX 3090s with 24 GB each. When I a small model that loads easily in my other work flows I’m running into this error. I’ve tried decreasing gpu-memory-allocation and using awq but still getting the error

**Comment by ccll** [comment]
Same here, with 2 RTX 3090s (24GB) loading Qwen1.5 7B model.
No matter what I tried to tune, gpu_memory_utilization, awq, enforce_eager, max_model_len, ...... nothing works.
The model itself took 14.3919 GB, then vLLM tries to grab more memory until it reached the limit set by gpu_memory_utilization, then throws a torch.cuda.OutOfMemoryError.

**Comment by hieuhthh** [comment]
Anyways to use only the model itself without extra more memory. I want to use vLLM but need to minimize the gpu mem as much as possible. Thank you!

**Comment by morningcafe** [comment]
same error here :-1:

**Comment by satheshshiva** [comment]
Same error running vllm on a docker container. My setup runs 8B models just fine. But goes OOM with just 125M on vllm :(

**Comment by TiddlyWiddly** [comment]
Same error running docker and 2x3090s with nothing else running.

**Comment by Ironieser** [comment]
same

**Comment by trminhnam** [comment]
Same error on serving [mistralai/Mistral-7B-Instruct-v0.3](https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.3) on a server with two RTX 4090 24GB

**Comment by arichiardi** [comment]
Same here, are you all running using podman/docker?

**Comment by lingxiao216** [comment]
Hi, there, 

I use this command for `unsloth/DeepSeek-R1-Distill-Qwen-32B-bnb-4bit`
vllm serve unsloth/DeepSeek-R1-Distill-Qwen-32B-bnb-4bit --enable-reasoning --reasoning-parser deepseek_r1 --quantization bitsandbytes --load-format bitsandbytes --enable-chunked-prefill --max_model_len 6704
that's OK with RTX 4090 24GB.

**Comment by twright8** [comment]
Any update on this? constant OOM

[rank0]: Traceback (most recent call last):
[rank0]:   File "/usr/lib/python3.10/code.py", line 90, in runcode
[rank0]:     exec(code, self.locals)
[rank0]:   File "<input>", line 1, in <module>
[rank0]:   File "/home/tom/Documents/PycharmProjects/TI_RAG/venv/lib/python3.10/site-packages/aphrodite/endpoints/llm.py", line 180, in __init__
[rank0]:     self.llm_engine = AphroditeEngine.from_engine_args(engine_args)
[rank0]:   File "/home/tom/Documents/PycharmProjects/TI_RAG/venv/lib/python3.10/site-packages/aphrodite/engine/aphrodite_engine.py", line 521, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/home/tom/Documents/PycharmProjects/TI_RAG/venv/lib/python3.10/site-packages/aphrodite/engine/aphrodite_engine.py", line 347, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/home/tom/Documents/PycharmProjects/TI_RAG/venv/lib/python3.10/site-packages/aphrodite/engine/aphrodite_engine.py", line 448, in _initialize_kv_caches
[rank0]:     self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/home/tom/Documents/PycharmProjects/TI_RAG/venv/lib/python3.10/site-packages/aphrodite/executor/gpu_executor.py", line 126, in initialize_cache
[rank0]:     self.driver_worker.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/home/tom/Documents/PycharmProjects/TI_RAG/venv/lib/python3.10/site-packages/aphrodite/worker/worker.py", line 269, in initialize_cache
[rank0]:     self._init_cache_engine()
[rank0]:   File "/home/tom/Documents/PycharmProjects/TI_RAG/venv/lib/python3.10/site-packages/aphrodite/worker/worker.py", line 274, in _init_cache_engine
[rank0]:     self.cache_engine = [
[rank0]:   File "/home/tom/Documents/PycharmProjects/TI_RAG/venv/lib/python3.10/site-packages/aphrodite/worker/worker.py", line 275, in <listcomp>
[rank0]:     CacheEngine(self.cache_config, self.model_config,
[rank0]:   File "/home/tom/Documents/PycharmProjects/TI_RAG/venv/lib/python3.10/site-packages/aphrodite/worker/cache_engine.py", line 65, in __init__
[rank0]:     self.cpu_cache = self._allocate_kv_cache(self.num_cpu_blocks, "cpu")
[rank0]:   File "/home/tom/Documents/PycharmProjects/TI_RAG/venv/lib/python3.10/site-packages/aphrodite/worker/cache_engine.py", line 82, in _allocate_kv_cache
[rank0]:     torch.zeros(kv_cache_shape,
[rank0]: RuntimeError: CUDA error: invalid argument
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by zhzLuke96** [comment]
any update this issues? same issues i hit

**Comment by fedeotto** [comment]
Just getting the same issue here! :(

**Comment by Rtsmjy** [comment]
Got same issue when running `vllm serve "agentica-org/DeepCoder-14B-Preview"`.

**Comment by mgutierrezc** [comment]
Same issue with `peiyi9979/math-shepherd-mistral-7b-prm`

**Comment by GabrielXie** [comment]
Trying to use the parameters' enforce agent 'and' gpu memory tilization ', as well as a quantization model, may potentially solve the problem

**Comment by lthomas122** [comment]
I was getting a similar issue with unsloth's llama3.2 11B Vision B2B on an A10G, the following parameters got it working for me after multiple failed attempts: 
```
--quantization bitsandbytes     --enforce-eager     --max_num_seqs 16  --max-model-len 6074    --model unsloth/Llama-3.2-11B-Vision-unsloth-bnb-4bit 
```

**Comment by Daqiangzhi** [comment]
I ran into the same issue. I have an RTX 4090D 24GB graphics card. When I use the vllm framework from LLaMA-Factory to run the Qwen3-14B model, it works fine. But when I write a script on my own to call the vllm library for inference, I get an OOM error... ToT

**Comment by zhzLuke96** [comment]
Hi, actually I resolved this issue about a month ago and managed to pinpoint the root cause. While it may not necessarily apply to your specific environment, I think it's worth sharing my findings:

1. First of all, this issue is not related to the GPU — it's caused by the CPU, and it's tightly coupled with the WSL kernel.

   * It's very counterintuitive that a CUDA error would be unrelated to the GPU, but in fact, if it's due to insufficient VRAM, the CUDA error will clearly indicate how much VRAM allocation failed. So, if the CUDA error doesn’t include VRAM-related details, it's most likely a CPU-side issue.

2. The root cause lies somewhere in the WSL kernel’s virtualization layer, which imposes a cap on `pin_memory`.

   * I tried to locate exactly where this limit comes from, but couldn’t pinpoint it... It’s quite a complex issue and may depend on the hardware, software, kernel version, or build environment — because all of this is built on top of WSL’s virtual PCIe layer.

3. I was only able to identify the issue with `pin_memory`, but I strongly suspect there are still other problems lurking beneath. To be honest, very few people are fine-tuning large models on WSL, so we might be treading new ground here 😂

In short, the workaround is to disable all usage of `pin_memory`, fall back to slower memory, or switch `device="cpu"` to `device="cuda"`, effectively avoiding the low-level logic in the virtualization layer that interacts with `pin_memory`.

You can find a more detailed debug log and discussion in the issue I opened on the Unsloth repo:
[https://github.com/unslothai/unsloth/issues/1744](https://github.com/unslothai/unsloth/issues/1744)
