### ISSUE TITLE
[Bug]: Multi-node data parallel cannot recognize IPv6 host address

### ISSUE THREAD

**Issue by SparkJiao** [vllm-project/vllm#18986]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
INFO 05-31 17:48:16 [__init__.py:247] No platform detected, vLLM is running on UnspecifiedPlatform
WARNING 05-31 17:48:18 [_custom_ops.py:21] Failed to import from vllm._C with ImportError('/lib/x86_64-linux-gnu/libcuda.so.1: file too short')
Collecting environment information...
==============================
        System Info
==============================
OS                           : Debian GNU/Linux 12 (bookworm) (x86_64)
GCC version                  : (Debian 12.2.0-14) 12.2.0
Clang version                : Could not collect
CMake version                : version 3.25.1
Libc version                 : glibc-2.36

==============================
       PyTorch Info
==============================
PyTorch version              : 2.7.0+cu126
Is debug build               : False
CUDA used to build PyTorch   : 12.6
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0] (64-bit runtime)
Python platform              : Linux-5.4.143.bsk.8-amd64-x86_64-with-glibc2.36

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : False
CUDA runtime version         : 12.4.131
CUDA_MODULE_LOADING set to   : N/A
GPU models and configuration: Head node so not available GPU nodes
Nvidia driver version        : Could not collect
cuDNN version                : Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.4.0
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          128
On-line CPU(s) list:             0-127
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8336C CPU @ 2.30GHz
CPU family:                      6
Model:                           106
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
Stepping:                        6
CPU(s) scaling MHz:              86%
CPU max MHz:                     3500.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4600.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid md_clear pconfig flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       3 MiB (64 instances)
L1i cache:                       2 MiB (64 instances)
L2 cache:                        80 MiB (64 instances)
L3 cache:                        108 MiB (2 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-15,64-79
NUMA node1 CPU(s):               16-31,80-95
NUMA node2 CPU(s):               32-47,96-111
NUMA node3 CPU(s):               48-63,112-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

==============================
Versions of relevant libraries
==============================
[pip3] flashinfer-python==0.2.3+cu124torch2.5
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.6.4.1
[pip3] nvidia-cuda-cupti-cu12==12.6.80
[pip3] nvidia-cuda-nvrtc-cu12==12.6.77
[pip3] nvidia-cuda-runtime-cu12==12.6.77
[pip3] nvidia-cudnn-cu12==9.5.1.17
[pip3] nvidia-cufft-cu12==11.3.0.4
[pip3] nvidia-cufile-cu12==1.11.1.6
[pip3] nvidia-curand-cu12==10.3.7.77
[pip3] nvidia-cusolver-cu12==11.7.1.2
[pip3] nvidia-cusparse-cu12==12.5.4.2
[pip3] nvidia-cusparselt-cu12==0.6.3
[pip3] nvidia-ml-py==11.495.46
[pip3] nvidia-modelopt==0.27.1
[pip3] nvidia-modelopt-core==0.27.1
[pip3] nvidia-nccl-cu12==2.26.2
[pip3] nvidia-nvjitlink-cu12==12.6.85
[pip3] nvidia-nvtx-cu12==12.6.77
[pip3] nvidia-resiliency-ext==0.3.0
[pip3] pynvml==12.0.0
[pip3] pyzmq==26.2.1
[pip3] torch==2.7.0
[pip3] torchao==0.10.0
[pip3] torchaudio==2.7.0
[pip3] torchdata==0.11.0
[pip3] torchprofile==0.0.4
[pip3] torchvision==0.22.0
[pip3] transformers==4.51.1
[pip3] triton==3.3.0
[conda] flashinfer-python         0.2.3+cu124torch2.5          pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.6.4.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.6.80                  pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.6.77                  pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.6.77                  pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.5.1.17                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.3.0.4                 pypi_0    pypi
[conda] nvidia-cufile-cu12        1.11.1.6                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.7.77                pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.7.1.2                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.5.4.2                 pypi_0    pypi
[conda] nvidia-cusparselt-cu12    0.6.3                    pypi_0    pypi
[conda] nvidia-ml-py              11.495.46                pypi_0    pypi
[conda] nvidia-modelopt           0.27.1                   pypi_0    pypi
[conda] nvidia-modelopt-core      0.27.1                   pypi_0    pypi
[conda] nvidia-nccl-cu12          2.26.2                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.6.85                  pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.6.77                  pypi_0    pypi
[conda] nvidia-resiliency-ext     0.3.0                    pypi_0    pypi
[conda] pynvml                    12.0.0                   pypi_0    pypi
[conda] pyzmq                     26.2.1                   pypi_0    pypi
[conda] torch                     2.7.0                    pypi_0    pypi
[conda] torchao                   0.10.0                   pypi_0    pypi
[conda] torchaudio                2.7.0                    pypi_0    pypi
[conda] torchdata                 0.11.0                   pypi_0    pypi
[conda] torchprofile              0.0.4                    pypi_0    pypi
[conda] torchvision               0.22.0                   pypi_0    pypi
[conda] transformers              4.51.1                   pypi_0    pypi
[conda] triton                    3.3.0                    pypi_0    pypi

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
Neuron SDK Version           : N/A
vLLM Version                 : 0.9.0.1
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
  Head node so no available GPUs.

==============================
     Environment Variables
==============================
NVIDIA_VISIBLE_DEVICES=none
NVIDIA_REQUIRE_CUDA=cuda>=12.2 brand=tesla,driver>=450,driver<451 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=510,driver<511 brand=unknown,driver>=510,driver<511 brand=nvidia,driver>=510,driver<511 brand=nvidiartx,driver>=510,driver<511 brand=geforce,driver>=510,driver<511 brand=geforcertx,driver>=510,driver<511 brand=quadro,driver>=510,driver<511 brand=quadrortx,driver>=510,driver<511 brand=titan,driver>=510,driver<511 brand=titanrtx,driver>=510,driver<511 brand=tesla,driver>=515,driver<516 brand=unknown,driver>=515,driver<516 brand=nvidia,driver>=515,driver<516 brand=nvidiartx,driver>=515,driver<516 brand=geforce,driver>=515,driver<516 brand=geforcertx,driver>=515,driver<516 brand=quadro,driver>=515,driver<516 brand=quadrortx,driver>=515,driver<516 brand=titan,driver>=515,driver<516 brand=titanrtx,driver>=515,driver<516 brand=tesla,driver>=525,driver<526 brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526 brand=nvidiartx,driver>=525,driver<526 brand=geforce,driver>=525,driver<526 brand=geforcertx,driver>=525,driver<526 brand=quadro,driver>=525,driver<526 brand=quadrortx,driver>=525,driver<526 brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526
NVIDIA_DRIVER_CAPABILITIES=compute,utility
LD_LIBRARY_PATH=/opt/tiger/native_libhdfs/lib/native:/opt/tiger/jdk/jdk8u265-b01/jre/lib/amd64/server:/opt/tiger/yarn_deploy/hadoop/lib/native:/opt/tiger/yarn_deploy/hadoop/lib/native/ufs:/opt/tiger/yarn_deploy/hadoop/lib/native:/opt/tiger/yarn_deploy/hadoop_current/lib/native:/opt/tiger/yarn_deploy/hadoop_current/lzo/lib
CUDA_HOME=/usr/local/cuda
CUDA_HOME=/usr/local/cuda
NCCL_CUMEM_ENABLE=0
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
```

</details>

### 🐛 Describe the bug

I'm try deploy Qwen2.5-32B-Instruct across 2 A100-80G nodes by using the following command:

```
export VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
export VLLM_USE_V1="1"

#export VLLM_HOST_IP=$(hostname -I | awk '{print $1}')
#export HOST_IP=$(hostname -I | awk '{print $1}')
IFS=',' read -ra HOSTS <<< "$NODE_WORKER_HOSTS"
echo "${HOSTS[0]}"

cd /data/models

addr="${HOSTS[0]}"

if [[ $addr =~ ^\[(.+)\]:([0-9]+)$ ]]; then
  ip="${BASH_REMATCH[1]}"
  port="${BASH_REMATCH[2]}"
else
  echo "输入格式不对，无法解析：$addr" >&2
  exit 1
fi

dp_address="tcp://[${ip}]:${port}"   # <-- exactly one pair of brackets here

echo "GPU‐node IP   = ${ip}"
echo "GPU‐node PORT = ${port}"
echo "DP_ADDRESS    = ${dp_address}"

# 公共参数
BASE_OPTS=(
    Qwen2.5-32B-Instruct
    --host "::"
    --port 8000
    --served-model-name qwen2.5-32b
    --tensor-parallel-size 8
    --max-num-seqs 256
    --rope-scaling '{"rope_type":"yarn","factor":4.0,"original_max_position_embeddings":32768}'
    --max-model-len 131072
    --data-parallel-size 2
    --data-parallel-size-local 1
    --data-parallel-address "${NODE_WORKER_0_HOST}"
    --data-parallel-rpc-port "${NODE_WORKER_0_PORT}"
)
#     
echo "${BASE_OPTS[@]}"

if [ "${NODE_ID}" -eq 0 ]; then
    vllm serve "${BASE_OPTS[@]}"
else
    vllm serve "${BASE_OPTS[@]}" \
        --data-parallel-start-rank "${NODE_ID}" \
        --headless
fi
```

The resulted command is like this (on first node):
```
vllm serve Qwen2.5-32B-Instruct --host :: --port 8000 --served-model-name qwen2.5-32b --tensor-parallel-size 8 --max-num-seqs 256 --rope-scaling '{"rope_type":"yarn","factor":4.0,"original_max_position_embeddings":32768}' --max-model-len 131072 --data-parallel-size 2 --data-parallel-size-local 1 --data-parallel-address 2605:340:cd51:a00:2a6:1aa4:9970:acec --data-parallel-rpc-port 9662
```

Afterwards, I will receive the following error:
```
INFO 05-31 17:36:07 [__init__.py:243] Automatically detected platform cuda.
INFO 05-31 17:36:15 [__init__.py:31] Available plugins for group vllm.general_plugins:
INFO 05-31 17:36:15 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
INFO 05-31 17:36:15 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 05-31 17:36:18 [api_server.py:1289] vLLM API server version 0.9.0.1
INFO 05-31 17:36:18 [cli_args.py:300] non-default args: {'host': '::', 'rope_scaling': {'rope_type': 'yarn', 'factor': 4.0, 'original_max_position_embeddings': 32768}, 'max_model_len': 131072, 'served_model_name': ['qwen2.5-32b'], 'tensor_parallel_size': 8, 'data_parallel_size': 2, 'data_parallel_size_local': 1, 'data_parallel_address': '2605:340:cd51:a00:2a6:1aa4:9970:acec', 'data_parallel_rpc_port': 9662, 'max_num_seqs': 256}
INFO 05-31 17:36:18 [config.py:520] Overriding HF config with {'rope_scaling': {'rope_type': 'yarn', 'factor': 4.0, 'original_max_position_embeddings': 32768}}
INFO 05-31 17:36:39 [config.py:793] This model supports multiple tasks: {'generate', 'classify', 'embed', 'score', 'reward'}. Defaulting to 'generate'.
INFO 05-31 17:36:39 [config.py:1875] Defaulting to use mp for distributed inference
INFO 05-31 17:36:39 [config.py:2118] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 05-31 17:36:39 [cuda.py:156] Data Parallel: Forcing enforce eager to be True since DP is currently not supported with CUDA Graphs.
INFO 05-31 17:36:52 [__init__.py:243] Automatically detected platform cuda.
[1;36m(EngineCore_0 pid=12588)[0;0m INFO 05-31 17:37:00 [core.py:438] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=12588)[0;0m WARNING 05-31 17:37:00 [cuda.py:87] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
[1;36m(EngineCore_0 pid=12588)[0;0m INFO 05-31 17:37:01 [__init__.py:31] Available plugins for group vllm.general_plugins:
[1;36m(EngineCore_0 pid=12588)[0;0m INFO 05-31 17:37:01 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
[1;36m(EngineCore_0 pid=12588)[0;0m INFO 05-31 17:37:01 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
[1;36m(EngineCore_0 pid=12588)[0;0m INFO 05-31 17:37:01 [core.py:65] Initializing a V1 LLM engine (v0.9.0.1) with config: model='Qwen2.5-32B-Instruct', speculative_config=None, tokenizer='Qwen2.5-32B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=auto, tensor_parallel_size=8, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=qwen2.5-32b, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=False, pooler_config=None, compilation_config={"level": 3, "custom_ops": ["none"], "splitting_ops": ["vllm.unified_attention", "vllm.unified_attention_with_output"], "use_inductor": false, "compile_sizes": [], "inductor_compile_config": {"enable_auto_functionalized_v2": false}, "cudagraph_num_of_warmups": 1, "cudagraph_capture_sizes": [512, 504, 496, 488, 480, 472, 464, 456, 448, 440, 432, 424, 416, 408, 400, 392, 384, 376, 368, 360, 352, 344, 336, 328, 320, 312, 304, 296, 288, 280, 272, 264, 256, 248, 240, 232, 224, 216, 208, 200, 192, 184, 176, 168, 160, 152, 144, 136, 128, 120, 112, 104, 96, 88, 80, 72, 64, 56, 48, 40, 32, 24, 16, 8, 4, 2, 1], "max_capture_size": 512}
[1;36m(EngineCore_0 pid=12588)[0;0m INFO 05-31 17:37:01 [shm_broadcast.py:250] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1, 2, 3, 4, 5, 6, 7], buffer_handle=(8, 10485760, 10, 'psm_7dce1134'), local_subscribe_addr='ipc:///tmp/f73120d8-bfd3-440a-bff0-4d777cc55edd', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 05-31 17:37:13 [__init__.py:243] Automatically detected platform cuda.
INFO 05-31 17:37:13 [__init__.py:243] Automatically detected platform cuda.
INFO 05-31 17:37:14 [__init__.py:243] Automatically detected platform cuda.
INFO 05-31 17:37:14 [__init__.py:243] Automatically detected platform cuda.
INFO 05-31 17:37:14 [__init__.py:243] Automatically detected platform cuda.
INFO 05-31 17:37:14 [__init__.py:243] Automatically detected platform cuda.
INFO 05-31 17:37:14 [__init__.py:243] Automatically detected platform cuda.
INFO 05-31 17:37:15 [__init__.py:243] Automatically detected platform cuda.
INFO 05-31 17:37:21 [__init__.py:31] Available plugins for group vllm.general_plugins:
INFO 05-31 17:37:21 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
INFO 05-31 17:37:21 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 05-31 17:37:21 [__init__.py:31] Available plugins for group vllm.general_plugins:
INFO 05-31 17:37:21 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
INFO 05-31 17:37:21 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 05-31 17:37:21 [__init__.py:31] Available plugins for group vllm.general_plugins:
INFO 05-31 17:37:21 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
INFO 05-31 17:37:21 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 05-31 17:37:21 [__init__.py:31] Available plugins for group vllm.general_plugins:
INFO 05-31 17:37:21 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
INFO 05-31 17:37:21 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 05-31 17:37:22 [__init__.py:31] Available plugins for group vllm.general_plugins:
INFO 05-31 17:37:22 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
INFO 05-31 17:37:22 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 05-31 17:37:22 [__init__.py:31] Available plugins for group vllm.general_plugins:
INFO 05-31 17:37:22 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
INFO 05-31 17:37:22 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 05-31 17:37:22 [__init__.py:31] Available plugins for group vllm.general_plugins:
INFO 05-31 17:37:22 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
INFO 05-31 17:37:22 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
WARNING 05-31 17:37:22 [utils.py:2671] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7fa2d7bad420>
WARNING 05-31 17:37:22 [utils.py:2671] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7f9dfffa9450>
WARNING 05-31 17:37:22 [utils.py:2671] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7fa5e5bbd270>
WARNING 05-31 17:37:22 [utils.py:2671] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7fbf23bcd3f0>
[1;36m(VllmWorker rank=2 pid=12972)[0;0m INFO 05-31 17:37:22 [shm_broadcast.py:250] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_f21bb634'), local_subscribe_addr='ipc:///tmp/1df113b8-edc3-45fd-b006-7e714c407861', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(VllmWorker rank=3 pid=12977)[0;0m INFO 05-31 17:37:22 [shm_broadcast.py:250] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_d3e24d64'), local_subscribe_addr='ipc:///tmp/ff1acdde-b2b5-4947-858b-caccb6ecd2fa', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(VllmWorker rank=0 pid=12968)[0;0m INFO 05-31 17:37:22 [shm_broadcast.py:250] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_51257ce6'), local_subscribe_addr='ipc:///tmp/6ad86fd1-c12c-46ae-8558-e6caa06526d0', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(VllmWorker rank=1 pid=12971)[0;0m INFO 05-31 17:37:22 [shm_broadcast.py:250] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_8c57d0cf'), local_subscribe_addr='ipc:///tmp/26fa8c1e-6a42-493c-8893-bf7a071d2eee', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 05-31 17:37:23 [__init__.py:31] Available plugins for group vllm.general_plugins:
INFO 05-31 17:37:23 [__init__.py:33] - lora_filesystem_resolver -> vllm.plugins.lora_resolvers.filesystem_resolver:register_filesystem_resolver
INFO 05-31 17:37:23 [__init__.py:36] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
WARNING 05-31 17:37:23 [utils.py:2671] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7faae22e9480>
[1;36m(VllmWorker rank=4 pid=12978)[0;0m INFO 05-31 17:37:23 [shm_broadcast.py:250] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_ac7798aa'), local_subscribe_addr='ipc:///tmp/41298a75-9062-465e-ac00-8534fcfe1bc8', remote_subscribe_addr=None, remote_addr_ipv6=False)
WARNING 05-31 17:37:23 [utils.py:2671] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7fbefddc5360>
[1;36m(VllmWorker rank=6 pid=12996)[0;0m INFO 05-31 17:37:23 [shm_broadcast.py:250] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_da23e077'), local_subscribe_addr='ipc:///tmp/9c523ea2-53d2-49ec-8a8f-c8d1d582a33d', remote_subscribe_addr=None, remote_addr_ipv6=False)
WARNING 05-31 17:37:23 [utils.py:2671] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7f586dd19330>
[1;36m(VllmWorker rank=5 pid=12979)[0;0m INFO 05-31 17:37:23 [shm_broadcast.py:250] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_8a7362e2'), local_subscribe_addr='ipc:///tmp/c200ddfc-87b4-4fe3-92be-f9cce67afa82', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(VllmWorker rank=0 pid=12968)[0;0m INFO 05-31 17:37:23 [parallel_state.py:933] Adjusting world_size=16 rank=0 distributed_init_method=tcp://2605:340:cd51:a00:2a6:1aa4:9970:acec:53280 for DP
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487] WorkerProc failed to start.
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487] Traceback (most recent call last):
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 461, in worker_main
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]     worker = WorkerProc(*args, **kwargs)
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 357, in __init__
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]     self.worker.init_device()
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 604, in init_device
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]     self.worker.init_device()  # type: ignore
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/vllm/v1/worker/gpu_worker.py", line 137, in init_device
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]     init_worker_distributed_environment(self.vllm_config, self.rank,
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/vllm/v1/worker/gpu_worker.py", line 347, in init_worker_distributed_environment
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]     init_distributed_environment(parallel_config.world_size, rank,
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 941, in init_distributed_environment
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]     torch.distributed.init_process_group(
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 81, in wrapper
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]     return func(*args, **kwargs)
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 95, in wrapper
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]     func_return = func(*args, **kwargs)
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1710, in init_process_group
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]     store, rank, world_size = next(rendezvous_iterator)
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/torch/distributed/rendezvous.py", line 216, in _tcp_rendezvous_handler
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]     if not result.port:
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/urllib/parse.py", line 186, in port
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487]     raise ValueError(f"Port could not be cast to integer value as {port!r}")
[1;36m(VllmWorker rank=0 pid=12968)[0;0m ERROR 05-31 17:37:23 [multiproc_executor.py:487] ValueError: Port could not be cast to integer value as '340:cd51:a00:2a6:1aa4:9970:acec:53280'
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500] EngineCore failed to start.
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 489, in run_engine_core
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500]     engine_core = DPEngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 690, in __init__
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500]     super().__init__(vllm_config, on_head_node, input_address,
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 390, in __init__
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 71, in __init__
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 52, in __init__
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500]     self._init_executor()
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 93, in _init_executor
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500]     self.workers = WorkerProc.wait_for_ready(unready_workers)
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500]   File "/mlx/users/jiaofangkai/miniconda3/envs/verl/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 422, in wait_for_ready
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500]     raise e from None
[1;36m(EngineCore_0 pid=12588)[0;0m ERROR 05-31 17:37:25 [core.py:500] Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by lengrongfu** [comment]
i will to check.

**Comment by SparkJiao** [comment]
I have tries your patch, and it works for me. Thank you very much!
