### ISSUE TITLE
[Bug]: Unable to get vLLM working with RTX 5090

### ISSUE THREAD

**Issue by scottgl9** [vllm-project/vllm#18995]
### Your current environment

I've tried nightly builds, building from source, and docker containers, but I am always seeing the same error:

```
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

I am able to reproduce the issue by running the following container on Ubuntu 24.04:
```
docker run --rm \
    --gpus all \
    -v "${HOME}/.cache/huggingface:/root/.cache/huggingface" \
    -p 8000:8000 \
    -e VLLM_USE_FLASH_ATTN=0 \
    --ipc=host \
    vllm/vllm-openai:latest \
    --model "${MODEL_NAME}"
```
Where ${MODEL_NAME} for example could be Qwen/Qwen3-4B-AWQ.

nvidia-smi output:
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.133.20             Driver Version: 570.133.20     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5090        Off |   00000000:01:00.0 Off |                  N/A |
|  0%   35C    P8             12W /  575W |      15MiB /  32607MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            1553      G   /usr/lib/xorg/Xorg                        4MiB |
+-----------------------------------------------------------------------------------------+
```

### 🐛 Describe the bug

I am able to reproduce the bug from the following simple example:
```
curl -X POST http://localhost:8000/v1/chat/completions   -H "Content-Type: application/json"   -d '{
        "model": "Qwen/Qwen3-4B-AWQ",
        "messages": [
          { "role": "system", "content": "You are a helpful assistant." },
          { "role": "user",   "content": "Tell me a joke." }
        ],
        "max_tokens": 50,
        "temperature": 0.7
      }'
```

FYI ollama works fine as a backend with the 5090, but I want the improved performance and tool calling ability which comes with vllm (OpenAI compatibility). If needed, I can provide the full debug output. I've tried with and without the VLLM_USE_FLASH_ATTN environment variable.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by scottgl9** [comment]
Error output:

[vllm_error_output.log](https://github.com/user-attachments/files/20535838/vllm_error_output.log)

**Comment by Rezzemy** [comment]
having the same issue as you at #18916

**Comment by afinkSyntactix** [comment]
Same Error on RTX 6000 Pro 96 Blackwell
tried some of the old hints on how to get blackwell running and the current nightly vllm (-pre ) built with and withoud docker without success

**Comment by Rezzemy** [comment]
> Same Error on RTX 6000 Pro 96 Blackwell tried some of the old hints on how to get blackwell running and the current nightly vllm (-pre ) built with and withoud docker without success

I have a dockerfile that seems to fix this issue in #18916

**Comment by anyiz** [comment]
I just posted a bug with the same issue you encountered with my 5090D graphics card

**Comment by andreasNfink** [comment]
@Rezzemy , thanks I didnt try your dockerfile as i did not want to wait so long without control, but i build the package from git (pytorch + vllm ) manually  and now it works, so manual compile from latest code works, the nightly docker image does not. maybe that helps

**Comment by humorist6** [comment]
same error, but on 5060ti

**Comment by Charmnut** [comment]
Same Error on 5090

**Comment by Leon-Sander** [comment]
`CUDA error: no kernel image is available for execution on the device` error with rtx 5090 using the vllm/vllm-openai:v0.9.0.1

**Comment by NINE9-9-9** [comment]
same error on 5090

**Comment by ChachAloha** [comment]
same error

**Comment by To0nyZ** [comment]
vllm0.9.1相同的错误

**Comment by linsmalldragon** [comment]
same error

**Comment by shuttie** [comment]
Blackwell support is only available in CUDA 12.8+, but official VLLM wheels are built with 12.6. If you build vllm from source with the latest CUDA, then it works quite well on my 2x 5090.

**Comment by mgoin** [comment]
This will be resolved in the next release! We landed support for SM120 in the wheel and docker image https://github.com/vllm-project/vllm/pull/19794
