### ISSUE TITLE
[Bug]: Dual a6000 pros not working. Arch 120.

### ISSUE THREAD

**Issue by vladrad** [vllm-project/vllm#19025]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Collecting environment information...
==============================
        System Info
==============================
OS                           : Ubuntu 22.04.5 LTS (x86_64)
GCC version                  : (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version                : Could not collect
CMake version                : version 3.22.1
Libc version                 : glibc-2.35

==============================
       PyTorch Info
==============================
PyTorch version              : 2.7.0+cu128
Is debug build               : False
CUDA used to build PyTorch   : 12.8
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (64-bit runtime)
Python platform              : Linux-6.5.0-45-generic-x86_64-with-glibc2.35

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : Could not collect
CUDA_MODULE_LOADING set to   : LAZY
GPU models and configuration : 
GPU 0: NVIDIA RTX PRO 6000 Blackwell Workstation Edition
GPU 1: NVIDIA RTX PRO 6000 Blackwell Workstation Edition

Nvidia driver version        : 575.51.03
cuDNN version                : Could not collect
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      39 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             32
On-line CPU(s) list:                0-31
Vendor ID:                          GenuineIntel
Model name:                         13th Gen Intel(R) Core(TM) i9-13900KF
CPU family:                         6
Model:                              183
Thread(s) per core:                 2
Core(s) per socket:                 24
Socket(s):                          1
Stepping:                           1
CPU max MHz:                        5800.0000
CPU min MHz:                        800.0000
BogoMIPS:                           5990.40
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req hfi vnmi umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                     VT-x
L1d cache:                          896 KiB (24 instances)
L1i cache:                          1.3 MiB (24 instances)
L2 cache:                           32 MiB (12 instances)
L3 cache:                           36 MiB (1 instance)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-31
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI BHI_DIS_S
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

==============================
Versions of relevant libraries
==============================
[pip3] numpy==2.1.2
[pip3] nvidia-cublas-cu12==12.8.3.14
[pip3] nvidia-cuda-cupti-cu12==12.8.57
[pip3] nvidia-cuda-nvrtc-cu12==12.8.61
[pip3] nvidia-cuda-runtime-cu12==12.8.57
[pip3] nvidia-cudnn-cu12==9.7.1.26
[pip3] nvidia-cufft-cu12==11.3.3.41
[pip3] nvidia-cufile-cu12==1.13.0.11
[pip3] nvidia-curand-cu12==10.3.9.55
[pip3] nvidia-cusolver-cu12==11.7.2.55
[pip3] nvidia-cusparse-cu12==12.5.7.53
[pip3] nvidia-cusparselt-cu12==0.6.3
[pip3] nvidia-nccl-cu12==2.26.2
[pip3] nvidia-nvjitlink-cu12==12.8.61
[pip3] nvidia-nvtx-cu12==12.8.55
[pip3] pytorch-triton==3.3.1+gitc8757738
[pip3] pyzmq==26.4.0
[pip3] torch==2.7.0+cu128
[pip3] torchaudio==2.7.0+cu128
[pip3] torchvision==0.22.0+cu128
[pip3] transformers==4.52.4
[pip3] triton==3.3.0
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
Neuron SDK Version           : N/A
vLLM Version                 : 0.9.0.1
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
        GPU0    GPU1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PHB     0-31    0               N/A
GPU1    PHB      X      0-31    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

==============================
     Environment Variables
==============================
LD_LIBRARY_PATH=/usr/local/cuda/lib64:
CUDA_HOME=/usr/local/cuda
CUDA_HOME=/usr/local/cuda
NCCL_CUMEM_ENABLE=0
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY
```

</details>

### 🐛 Describe the bug

When running any model in with -tp 2 I get illegal memory access issues. 

I have tried a mixture of every possible combination:
-kernel version
-cuda version 12.8+12.9
-different drivers
-nccl versions
-compiled from source for all combinations and tried docker.
-works in windows WSL but not ubuntu 22.04

I understand a lot of people have been experiencing similar issues but I can't tell if its the same error.

Just to be sure I have gone out and rented two a6000 pros on runpod.io. I used their 12.8 template and got the same error there... so I assume it's not my hardware since it does not work with enterprise grade infra.

I cannot pin point this bug and initially thought that nccl is to blame. 

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by lengrongfu** [comment]
@vladrad can you provide running error info and running command?

**Comment by vladrad** [comment]
Hi yes!

```
vllm serve Qwen/Qwen3-8B -tp 2
```

Pretty much any model that can be split via `-tp`. I mostly tried 8B because I can test really fast. I tried all versions including nightly. I tried the official release from run pod... they all seem to have this issue. Let me know what else I can do or help out with.

**Comment by lengrongfu** [comment]
If use one A6000 device can running success?

**Comment by vladrad** [comment]
it boots up with one device but doing a request against it crashes it with the same error as above

**Comment by lengrongfu** [comment]
Ok, i will to check, because i only one A6000 device 😄

**Comment by lengrongfu** [comment]
![Image](https://github.com/user-attachments/assets/26b02bb9-69a4-4b5b-9413-3013b49f5d96)

![Image](https://github.com/user-attachments/assets/2a103a99-9823-4f0c-b9e7-8b6d66c80880)

![Image](https://github.com/user-attachments/assets/98df0723-e5ca-429a-b190-9a0352e42a92)

I use single A6000 device test is ok in vllm 0.8.4 version.

**Comment by vladrad** [comment]
Ah @lengrongfu thank you for giving it a shot. I think looking through all the issues I see people being successful with the older hardware.

I have a a6000 pro 96gb which was released about 2 weeks ago. It works ok in windows but vllm in ubuntu does not work even for single mode cards. This is arch 120.

**Comment by sarmiena** [comment]
> Ah [@lengrongfu](https://github.com/lengrongfu) thank you for giving it a shot. I think looking through all the issues I see people being successful with the older hardware.
> 
> I have a a6000 pro 96gb which was released about 2 weeks ago. It works ok in windows but vllm in ubuntu does not work even for single mode cards. This is arch 120.

There's an A6000 Pro with 96GB ram released 2 weeks ago? Or do you mean the RTX PRO 6000 96GB Blackwell? 

But yeah, I'm struggling with RTX PRO 6000 as well

**Comment by lengrongfu** [comment]
https://github.com/vllm-project/vllm/issues/18995 look like this issue.

**Comment by vladrad** [comment]
yeah that RTX PRO 6000 Blackwell. @lengrongfu ill try out the docker file in there and see if anything works.

**Comment by vladrad** [comment]
the image on #18995 allowed me to load  with -tp 2. im not sure what Nvidia did but their image seems to have something... I am getting around 66 t/s full context with qwen 235 awq.

**Comment by lengrongfu** [comment]
How did you do it? @vladrad

**Comment by vladrad** [comment]
@lengrongfu https://github.com/vllm-project/vllm/issues/18916#issuecomment-2936843240

I used the docker image in this comment from Nvidia. It works

**Comment by lengrongfu** [comment]
It may be a problem with FLASHINFER,

**Comment by vladrad** [comment]
Oh when running the docker image `docker run --rm -it --gpus=all --shm-size=1g` make sure you pass --shm-size otherwise it wont work.

it could be a issue with flashinfer... its one of the few things I did not get to try and look into

**Comment by RodriMora** [comment]
I had a problem with 2x5090. I see your env has `nvidia-nccl-cu12==2.26.2`

You need `nvidia-nccl-cu12==2.26.5` or `nvidia-nccl-cu12==2.27.3` for -tp >1 GPU to work

**Comment by vladrad** [comment]
I’ll give it a shot again

**Comment by sniper35** [comment]
> I had a problem with 2x5090. I see your env has `nvidia-nccl-cu12==2.26.2`
> 
> You need `nvidia-nccl-cu12==2.26.5` or `nvidia-nccl-cu12==2.27.3` for -tp >1 GPU to work

+1, This works for me

**Comment by lengrongfu** [comment]
This version is torch deepend https://github.com/pytorch/pytorch, wait release new version after I will update this version.

**Comment by RodriMora** [comment]
> This version is torch deepend https://github.com/pytorch/pytorch, wait release new version after I will update this version.

seems like pytorch has already updated the version to nvidia-nccl-cu12==2.27.3
https://github.com/pytorch/pytorch/blob/f45f483884ef524f2d8260dcf2b2ba2c203eab2f/.github/workflows/generated-linux-binary-manywheel-main.yml#L64

**Comment by lengrongfu** [comment]
> > This version is torch deepend https://github.com/pytorch/pytorch, wait release new version after I will update this version.
> 
> seems like pytorch has already updated the version to nvidia-nccl-cu12==2.27.3 https://github.com/pytorch/pytorch/blob/f45f483884ef524f2d8260dcf2b2ba2c203eab2f/.github/workflows/generated-linux-binary-manywheel-main.yml#L64

yes, but not release new version, latest 2.7.1 version than is 2.27.2 https://github.com/pytorch/pytorch/blob/v2.7.1/.github/workflows/generated-linux-binary-manywheel-main.yml

**Comment by mgoin** [comment]
This will be resolved in the next release! We landed support for SM120 in the wheel and docker image https://github.com/vllm-project/vllm/pull/19794

**Comment by gau-nernst** [comment]
@mgoin Awesome that vLLM pre-built wheels have sm120 support now! Can we pin torch to 2.7.1 instead? torch 2.7.0 ships with trition 3.3.0, which does not have sm120 support -> all torch.compile() features will break. torch 2.7.1 ships triton 3.3.1, which solves the issue for sm120.

**Comment by cyysky** [comment]
> I had a problem with 2x5090. I see your env has `nvidia-nccl-cu12==2.26.2`
> 
> You need `nvidia-nccl-cu12==2.26.5` or `nvidia-nccl-cu12==2.27.3` for -tp >1 GPU to work

+1 nvidia-nccl-cu12==2.27.3 works for me too 

pip install nvidia-nccl-cu12==2.27.3 --extra-index-url https://pypi.nvidia.com
