### ISSUE TITLE
[Bug]: RTX50xx GPU is not supported for running W8A8 FP8 quant models!

### ISSUE THREAD

**Issue by ziyye** [vllm-project/vllm#19605]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
INFO 06-13 16:55:15 [__init__.py:244] Automatically detected platform cuda.
Collecting environment information...
/data/liaojuncheng/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/torch/cuda/__init__.py:287: UserWarning: 
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
==============================
        System Info
==============================
OS                           : Ubuntu 22.04.5 LTS (x86_64)
GCC version                  : (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version                : Could not collect
CMake version                : Could not collect
Libc version                 : glibc-2.35

==============================
       PyTorch Info
==============================
PyTorch version              : 2.7.0+cu126
Is debug build               : False
CUDA used to build PyTorch   : 12.6
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.11 | packaged by Anaconda, Inc. | (main, Jun  5 2025, 13:09:17) [GCC 11.2.0] (64-bit runtime)
Python platform              : Linux-5.15.0-138-generic-x86_64-with-glibc2.35

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : 12.8.93
CUDA_MODULE_LOADING set to   : LAZY
GPU models and configuration : GPU 0: NVIDIA GeForce RTX 5070 Ti
Nvidia driver version        : 570.124.06
cuDNN version                : Could not collect
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        39 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               8
On-line CPU(s) list:                  0-7
Vendor ID:                            GenuineIntel
Model name:                           Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
CPU family:                           6
Model:                                158
Thread(s) per core:                   1
Core(s) per socket:                   8
Socket(s):                            1
Stepping:                             12
CPU max MHz:                          4900.0000
CPU min MHz:                          800.0000
BogoMIPS:                             7200.00
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
Virtualization:                       VT-x
L1d cache:                            256 KiB (8 instances)
L1i cache:                            256 KiB (8 instances)
L2 cache:                             2 MiB (8 instances)
L3 cache:                             12 MiB (1 instance)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-7
Vulnerability Gather data sampling:   Mitigation; Microcode
Vulnerability Itlb multihit:          KVM: Mitigation: VMX disabled
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Mitigation; IBRS
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; IBRS; IBPB conditional; STIBP disabled; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Mitigation; Microcode
Vulnerability Tsx async abort:        Mitigation; TSX disabled

==============================
Versions of relevant libraries
==============================
[pip3] numpy==2.2.6
[pip3] nvidia-cublas-cu12==12.6.4.1
[pip3] nvidia-cuda-cupti-cu12==12.6.80
[pip3] nvidia-cuda-nvrtc-cu12==12.6.77
[pip3] nvidia-cuda-runtime-cu12==12.6.77
[pip3] nvidia-cudnn-cu12==9.5.1.17
[pip3] nvidia-cufft-cu12==11.3.0.4
[pip3] nvidia-cufile-cu12==1.11.1.6
[pip3] nvidia-curand-cu12==10.3.7.77
[pip3] nvidia-cusolver-cu12==11.7.1.2
[pip3] nvidia-cusparse-cu12==12.5.4.2
[pip3] nvidia-cusparselt-cu12==0.6.3
[pip3] nvidia-nccl-cu12==2.26.2
[pip3] nvidia-nvjitlink-cu12==12.6.85
[pip3] nvidia-nvtx-cu12==12.6.77
[pip3] pyzmq==26.4.0
[pip3] torch==2.7.0
[pip3] torchaudio==2.7.0
[pip3] torchvision==0.22.0
[pip3] transformers==4.52.4
[pip3] triton==3.3.0
[conda] numpy                     2.2.6                    pypi_0    pypi
[conda] nvidia-cublas-cu12        12.6.4.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.6.80                  pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.6.77                  pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.6.77                  pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.5.1.17                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.3.0.4                 pypi_0    pypi
[conda] nvidia-cufile-cu12        1.11.1.6                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.7.77                pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.7.1.2                 pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.5.4.2                 pypi_0    pypi
[conda] nvidia-cusparselt-cu12    0.6.3                    pypi_0    pypi
[conda] nvidia-nccl-cu12          2.26.2                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.6.85                  pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.6.77                  pypi_0    pypi
[conda] pyzmq                     26.4.0                   pypi_0    pypi
[conda] torch                     2.7.0                    pypi_0    pypi
[conda] torchaudio                2.7.0                    pypi_0    pypi
[conda] torchvision               0.22.0                   pypi_0    pypi
[conda] transformers              4.52.4                   pypi_0    pypi
[conda] triton                    3.3.0                    pypi_0    pypi

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
Neuron SDK Version           : N/A
vLLM Version                 : 0.9.1
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
        GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      0-7     0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

==============================
     Environment Variables
==============================
NCCL_CUMEM_ENABLE=0
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY
```

</details>

### 🐛 Describe the bug

On RTX5070 GPU, a W8A8 FP8 quant model is not supported, as `sm_120` architecture is not supported by vLLM yet.

Running `vllm serve Llama-3.2-3B-Instruct-FP8-dynamic` got error:

<details>
<summary>Error stack trace</summary>

```text
INFO 06-13 16:49:51 [__init__.py:244] Automatically detected platform cuda.
INFO 06-13 16:49:56 [api_server.py:1287] vLLM API server version 0.9.1
INFO 06-13 16:49:57 [cli_args.py:309] non-default args: {'model': '/mnt/pai-storage-12/models/Llama-3.2-3B-Instruct-FP8-dynamic'}
INFO 06-13 16:50:03 [config.py:823] This model supports multiple tasks: {'classify', 'embed', 'reward', 'generate', 'score'}. Defaulting to 'generate'.
INFO 06-13 16:50:04 [config.py:2195] Chunked prefill is enabled with max_num_batched_tokens=2048.
WARNING 06-13 16:50:06 [env_override.py:17] NCCL_CUMEM_ENABLE is set to 0, skipping override. This may increase memory overhead with cudagraph+allreduce: https://github.com/NVIDIA/nccl/issues/1234
INFO 06-13 16:50:08 [__init__.py:244] Automatically detected platform cuda.
INFO 06-13 16:50:11 [core.py:455] Waiting for init message from front-end.
INFO 06-13 16:50:11 [core.py:70] Initializing a V1 LLM engine (v0.9.1) with config: model='/mnt/pai-storage-12/models/Llama-3.2-3B-Instruct-FP8-dynamic', speculative_config=None, tokenizer='/mnt/pai-storage-12/models/Llama-3.2-3B-Instruct-FP8-dynamic', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=compressed-tensors, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/mnt/pai-storage-12/models/Llama-3.2-3B-Instruct-FP8-dynamic, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/torch/cuda/__init__.py:287: UserWarning: 
NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
WARNING 06-13 16:50:12 [utils.py:2737] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7fe8c3d62930>
INFO 06-13 16:50:12 [parallel_state.py:1065] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
INFO 06-13 16:50:12 [topk_topp_sampler.py:49] Using FlashInfer for top-p & top-k sampling.
ERROR 06-13 16:50:12 [core.py:515] EngineCore failed to start.
ERROR 06-13 16:50:12 [core.py:515] Traceback (most recent call last):
ERROR 06-13 16:50:12 [core.py:515]   File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 506, in run_engine_core
ERROR 06-13 16:50:12 [core.py:515]     engine_core = EngineCoreProc(*args, **kwargs)
ERROR 06-13 16:50:12 [core.py:515]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-13 16:50:12 [core.py:515]   File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 390, in __init__
ERROR 06-13 16:50:12 [core.py:515]     super().__init__(vllm_config, executor_class, log_stats,
ERROR 06-13 16:50:12 [core.py:515]   File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 76, in __init__
ERROR 06-13 16:50:12 [core.py:515]     self.model_executor = executor_class(vllm_config)
ERROR 06-13 16:50:12 [core.py:515]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-13 16:50:12 [core.py:515]   File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 53, in __init__
ERROR 06-13 16:50:12 [core.py:515]     self._init_executor()
ERROR 06-13 16:50:12 [core.py:515]   File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 47, in _init_executor
ERROR 06-13 16:50:12 [core.py:515]     self.collective_rpc("init_device")
ERROR 06-13 16:50:12 [core.py:515]   File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 57, in collective_rpc
ERROR 06-13 16:50:12 [core.py:515]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 06-13 16:50:12 [core.py:515]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-13 16:50:12 [core.py:515]   File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/utils.py", line 2671, in run_method
ERROR 06-13 16:50:12 [core.py:515]     return func(*args, **kwargs)
ERROR 06-13 16:50:12 [core.py:515]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 06-13 16:50:12 [core.py:515]   File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 606, in init_device
ERROR 06-13 16:50:12 [core.py:515]     self.worker.init_device()  # type: ignore
ERROR 06-13 16:50:12 [core.py:515]     ^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 06-13 16:50:12 [core.py:515]   File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 160, in init_device
ERROR 06-13 16:50:12 [core.py:515]     self.model_runner: GPUModelRunner = GPUModelRunner(
ERROR 06-13 16:50:12 [core.py:515]                                         ^^^^^^^^^^^^^^^
ERROR 06-13 16:50:12 [core.py:515]   File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 185, in __init__
ERROR 06-13 16:50:12 [core.py:515]     self.input_batch = InputBatch(
ERROR 06-13 16:50:12 [core.py:515]                        ^^^^^^^^^^^
ERROR 06-13 16:50:12 [core.py:515]   File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/worker/gpu_input_batch.py", line 102, in __init__
ERROR 06-13 16:50:12 [core.py:515]     self.block_table = MultiGroupBlockTable(
ERROR 06-13 16:50:12 [core.py:515]                        ^^^^^^^^^^^^^^^^^^^^^
ERROR 06-13 16:50:12 [core.py:515]   File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/worker/block_table.py", line 110, in __init__
ERROR 06-13 16:50:12 [core.py:515]     BlockTable(max_num_reqs, cdiv(max_model_len, block_size),
ERROR 06-13 16:50:12 [core.py:515]   File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/worker/block_table.py", line 29, in __init__
ERROR 06-13 16:50:12 [core.py:515]     self.block_table = torch.zeros(
ERROR 06-13 16:50:12 [core.py:515]                        ^^^^^^^^^^^^
ERROR 06-13 16:50:12 [core.py:515] RuntimeError: CUDA error: no kernel image is available for execution on the device
ERROR 06-13 16:50:12 [core.py:515] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
ERROR 06-13 16:50:12 [core.py:515] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
ERROR 06-13 16:50:12 [core.py:515] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
ERROR 06-13 16:50:12 [core.py:515] 
Process EngineCore_0:
Traceback (most recent call last):
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 519, in run_engine_core
    raise e
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 506, in run_engine_core
    engine_core = EngineCoreProc(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 390, in __init__
    super().__init__(vllm_config, executor_class, log_stats,
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 76, in __init__
    self.model_executor = executor_class(vllm_config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 53, in __init__
    self._init_executor()
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 47, in _init_executor
    self.collective_rpc("init_device")
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/executor/uniproc_executor.py", line 57, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/utils.py", line 2671, in run_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 606, in init_device
    self.worker.init_device()  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 160, in init_device
    self.model_runner: GPUModelRunner = GPUModelRunner(
                                        ^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 185, in __init__
    self.input_batch = InputBatch(
                       ^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/worker/gpu_input_batch.py", line 102, in __init__
    self.block_table = MultiGroupBlockTable(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/worker/block_table.py", line 110, in __init__
    BlockTable(max_num_reqs, cdiv(max_model_len, block_size),
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/worker/block_table.py", line 29, in __init__
    self.block_table = torch.zeros(
                       ^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank0]:[W613 16:50:13.749090346 ProcessGroupNCCL.cpp:1476] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
Traceback (most recent call last):
  File "/data/bode/miniconda3/envs/vllm_9.0/bin/vllm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/entrypoints/cli/main.py", line 59, in main
    args.dispatch_function(args)
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/entrypoints/cli/serve.py", line 58, in cmd
    uvloop.run(run_server(args))
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1323, in run_server
    await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1343, in run_server_worker
    async with build_async_engine_client(args, client_config) as engine_client:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 155, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 191, in build_async_engine_client_from_engine_args
    async_llm = AsyncLLM.from_vllm_config(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 162, in from_vllm_config
    return cls(
           ^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 124, in __init__
    self.engine_core = EngineCoreClient.make_async_mp_client(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 93, in make_async_mp_client
    return AsyncMPClient(vllm_config, executor_class, log_stats,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 716, in __init__
    super().__init__(
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 422, in __init__
    self._init_engines_direct(vllm_config, local_only,
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 491, in _init_engines_direct
    self._wait_for_engine_startup(handshake_socket, input_address,
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 511, in _wait_for_engine_startup
    wait_for_engine_startup(
  File "/data/bode/miniconda3/envs/vllm_9.0/lib/python3.12/site-packages/vllm/v1/utils.py", line 494, in wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
```

</details>

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by l137295** [comment]
Excuse me, my friend, my 5060TI also reports an error：
RuntimeError: CUDA error: no kernel image is available for execution on the device
2025-06-12 20:49:44 CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
2025-06-12 20:49:44 For debugging consider passing CUDA_LAUNCH_BLOCKING=1
2025-06-12 20:49:44 Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

**Comment by Salomonmejia1** [comment]
Use this tutorial to run it in a docker container. It worked for me. 

https://github.com/vllm-project/vllm/issues/14452

**Comment by ziyye** [comment]
This PR works for me, with this PR, the FP8 W8A8 quantized model can run on 5070Ti GPU.

https://github.com/vllm-project/vllm/pull/17280

**Comment by ziyye** [comment]
Tested on 5070Ti, both methods (https://github.com/vllm-project/vllm/issues/14452 and https://github.com/vllm-project/vllm/pull/17280) work.
