### ISSUE TITLE
[Bug]: VLLM doesn't work on 5090s

### ISSUE THREAD

**Issue by povgeek** [vllm-project/vllm#20533]
### Your current environment

I'm sorry if this is duplicating information or bugs out there, but I'm having a hard time figuring out if VLLM has been updated to work with 5090s or now. I've been trying to get OCRFlux working on my 5090 for three days now and keep going through hurdle after hurdle.

I see posts that claim the 5090 now works, but that doesn't match my experience. I also see posts that show a long roadmap of fixes, which implies a long road to things being supported.

### 🐛 Describe the bug

CUDA Errors, several hour attempts to build locally that just fail, misery, etc.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by hetian127** [comment]
You can build vLLM from source.It works for me.

1，
pip3 install -U --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
2，
git clone https://github.com/vllm-project/vllm.git
cd vllm
python use_existing_torch.py
pip install -r requirements/build.txt
pip install --no-build-isolation -e .

**Comment by DaBossCoda** [comment]
can't get it to work either with 0.9.2

**Comment by alew3** [comment]
You can build a custom docker with Blackwell support

``` bash
git clone https://github.com/vllm-project/vllm.git
cd vllm
DOCKER_BUILDKIT=1 sudo docker build . --target vllm-openai \
  --tag myvllm --file docker/Dockerfile \
  --build-arg max_jobs=4 \
  --build-arg nvcc_threads=1 \
  --build-arg torch_cuda_arch_list="12.0 12.1" \
  --build-arg RUN_WHEEL_CHECK=false
```

**Comment by fscdc** [comment]
@hetian127 's way works for me, but CUDA should be a high version (12.8.1 for me). Hi @DaBossCoda , maybe u can try one more time
