### ISSUE TITLE
[Usage]: vLLM Server Launch Freezes at Using NCCL on B200

### ISSUE THREAD

**Issue by kimbochen** [vllm-project/vllm#20862]
### Your current environment

```text
==============================
        System Info
==============================
OS                           : Ubuntu 22.04.5 LTS (x86_64)
GCC version                  : (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version                : Could not collect
CMake version                : version 4.0.2
Libc version                 : glibc-2.35

==============================
       PyTorch Info
==============================
PyTorch version              : 2.7.0+cu128
Is debug build               : False
CUDA used to build PyTorch   : 12.8
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.11 (main, Jun  4 2025, 08:56:18) [GCC 11.4.0] (64-bit runtime)
Python platform              : Linux-5.15.0-143-generic-x86_64-with-glibc2.35

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : 12.8.93
CUDA_MODULE_LOADING set to   : LAZY
GPU models and configuration :
GPU 0: NVIDIA B200
GPU 1: NVIDIA B200
GPU 2: NVIDIA B200
GPU 3: NVIDIA B200
GPU 4: NVIDIA B200
GPU 5: NVIDIA B200
GPU 6: NVIDIA B200
GPU 7: NVIDIA B200

Nvidia driver version        : 575.57.08
cuDNN version                : Could not collect
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        52 bits physical, 57 bits virtual
Byte Order:                           Little Endian
CPU(s):                               224
On-line CPU(s) list:                  0-223
Vendor ID:                            GenuineIntel
Model name:                           INTEL(R) XEON(R) PLATINUM 8570
CPU family:                           6
Model:                                207
Thread(s) per core:                   2
Core(s) per socket:                   56
Socket(s):                            2
Stepping:                             2
BogoMIPS:                             4200.00
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm arat pln pts avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
Virtualization:                       VT-x
L1d cache:                            5.3 MiB (112 instances)
L1i cache:                            3.5 MiB (112 instances)
L2 cache:                             224 MiB (112 instances)
L3 cache:                             600 MiB (2 instances)
NUMA node(s):                         4
NUMA node0 CPU(s):                    0-27,112-139
NUMA node1 CPU(s):                    28-55,140-167
NUMA node2 CPU(s):                    56-83,168-195
NUMA node3 CPU(s):                    84-111,196-223
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI BHI_DIS_S
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

==============================
Versions of relevant libraries
==============================
[pip3] numpy==2.2.6
[pip3] nvidia-cublas-cu12==12.8.3.14
[pip3] nvidia-cuda-cupti-cu12==12.8.57
[pip3] nvidia-cuda-nvrtc-cu12==12.8.61
[pip3] nvidia-cuda-runtime-cu12==12.8.57
[pip3] nvidia-cudnn-cu12==9.7.1.26
[pip3] nvidia-cufft-cu12==11.3.3.41
[pip3] nvidia-cufile-cu12==1.13.0.11
[pip3] nvidia-curand-cu12==10.3.9.55
[pip3] nvidia-cusolver-cu12==11.7.2.55
[pip3] nvidia-cusparse-cu12==12.5.7.53
[pip3] nvidia-cusparselt-cu12==0.6.3
[pip3] nvidia-nccl-cu12==2.26.2
[pip3] nvidia-nvjitlink-cu12==12.8.61
[pip3] nvidia-nvtx-cu12==12.8.55
[pip3] pyzmq==26.4.0
[pip3] torch==2.7.0+cu128
[pip3] torchaudio==2.7.0+cu128
[pip3] torchvision==0.22.0+cu128
[pip3] transformers==4.52.4
[pip3] triton==3.3.0
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
Neuron SDK Version           : N/A
vLLM Version                 : 0.9.1
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6    NIC7    NIC8    NIC9    NIC10   NIC11CPU Affinity     NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NV18    NV18    NV18    NV18    NV18    NV18    PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS  0-27,112-139     0               N/A
GPU1    NV18     X      NV18    NV18    NV18    NV18    NV18    NV18    NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS  0-27,112-139     0               N/A
GPU2    NV18    NV18     X      NV18    NV18    NV18    NV18    NV18    SYS     SYS     SYS     SYS     PIX     NODE    SYS     SYS     SYS     SYS     SYS     SYS  28-55,140-167    1               N/A
GPU3    NV18    NV18    NV18     X      NV18    NV18    NV18    NV18    SYS     SYS     SYS     SYS     NODE    PIX     SYS     SYS     SYS     SYS     SYS     SYS  28-55,140-167    1               N/A
GPU4    NV18    NV18    NV18    NV18     X      NV18    NV18    NV18    SYS     SYS     SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    SYS     SYS  56-83,168-195    2               N/A
GPU5    NV18    NV18    NV18    NV18    NV18     X      NV18    NV18    SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX     SYS     SYS  56-83,168-195    2               N/A
GPU6    NV18    NV18    NV18    NV18    NV18    NV18     X      NV18    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     PIX     NODE 84-111,196-223   3               N/A
GPU7    NV18    NV18    NV18    NV18    NV18    NV18    NV18     X      SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     NODE    PIX  84-111,196-223   3               N/A
NIC0    PIX     NODE    SYS     SYS     SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS
NIC1    NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     NODE     X      PIX     NODE    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS
NIC2    NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     NODE    PIX      X      NODE    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS
NIC3    NODE    PIX     SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE     X      SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS
NIC4    SYS     SYS     PIX     NODE    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      NODE    SYS     SYS     SYS     SYS     SYS     SYS
NIC5    SYS     SYS     NODE    PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     NODE     X      SYS     SYS     SYS     SYS     SYS     SYS
NIC6    SYS     SYS     SYS     SYS     PIX     NODE    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    SYS     SYS
NIC7    SYS     SYS     SYS     SYS     NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     NODE     X      PIX     NODE    SYS     SYS
NIC8    SYS     SYS     SYS     SYS     NODE    NODE    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     NODE    PIX      X      NODE    SYS     SYS
NIC9    SYS     SYS     SYS     SYS     NODE    PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE     X      SYS     SYS
NIC10   SYS     SYS     SYS     SYS     SYS     SYS     PIX     NODE    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      NODE
NIC11   SYS     SYS     SYS     SYS     SYS     SYS     NODE    PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     NODE     X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_4
  NIC1: mlx5_5
  NIC2: mlx5_6
  NIC3: mlx5_7
  NIC4: mlx5_8
  NIC5: mlx5_9
  NIC6: mlx5_10
  NIC7: mlx5_11
  NIC8: mlx5_12
  NIC9: mlx5_13
  NIC10: mlx5_14
  NIC11: mlx5_15

==============================
     Environment Variables
==============================
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_REQUIRE_CUDA=cuda>=12.8 brand=unknown,driver>=470,driver<471 brand=grid,driver>=470,driver<471 brand=tesla,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=vapps,driver>=470,driver<471 brand=vpc,driver>=470,driver<471 brand=vcs,driver>=470,driver<471 brand=vws,driver>=470,driver<471 brand=cloudgaming,driver>=470,driver<471 brand=unknown,driver>=535,driver<536 brand=grid,driver>=535,driver<536 brand=tesla,driver>=535,driver<536 brand=nvidia,driver>=535,driver<536 brand=quadro,driver>=535,driver<536 brand=quadrortx,driver>=535,driver<536 brand=nvidiartx,driver>=535,driver<536 brand=vapps,driver>=535,driver<536 brand=vpc,driver>=535,driver<536 brand=vcs,driver>=535,driver<536 brand=vws,driver>=535,driver<536 brand=cloudgaming,driver>=535,driver<536 brand=unknown,driver>=550,driver<551 brand=grid,driver>=550,driver<551 brand=tesla,driver>=550,driver<551 brand=nvidia,driver>=550,driver<551 brand=quadro,driver>=550,driver<551 brand=quadrortx,driver>=550,driver<551 brand=nvidiartx,driver>=550,driver<551 brand=vapps,driver>=550,driver<551 brand=vpc,driver>=550,driver<551 brand=vcs,driver>=550,driver<551 brand=vws,driver>=550,driver<551 brand=cloudgaming,driver>=550,driver<551 brand=unknown,driver>=560,driver<561 brand=grid,driver>=560,driver<561 brand=tesla,driver>=560,driver<561 brand=nvidia,driver>=560,driver<561 brand=quadro,driver>=560,driver<561 brand=quadrortx,driver>=560,driver<561 brand=nvidiartx,driver>=560,driver<561 brand=vapps,driver>=560,driver<561 brand=vpc,driver>=560,driver<561 brand=vcs,driver>=560,driver<561 brand=vws,driver>=560,driver<561 brand=cloudgaming,driver>=560,driver<561 brand=unknown,driver>=565,driver<566 brand=grid,driver>=565,driver<566 brand=tesla,driver>=565,driver<566 brand=nvidia,driver>=565,driver<566 brand=quadro,driver>=565,driver<566 brand=quadrortx,driver>=565,driver<566 brand=nvidiartx,driver>=565,driver<566 brand=vapps,driver>=565,driver<566 brand=vpc,driver>=565,driver<566 brand=vcs,driver>=565,driver<566 brand=vws,driver>=565,driver<566 brand=cloudgaming,driver>=565,driver<566
NCCL_VERSION=2.25.1-1
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NVIDIA_PRODUCT_NAME=CUDA
VLLM_USAGE_SOURCE=production-docker-image
CUDA_VERSION=12.8.1
LD_LIBRARY_PATH=/usr/local/cuda/lib64
NCCL_CUMEM_ENABLE=0
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY
```

### How would you like to use vllm

I want to run vLLM on a B200 node with tensor parallel, but the server launch gets stuck at using NCCL.
TP=1 works, but TP=2 and TP=4 doesn't work.
I have also had the same issue on v0.9.2.

```
INFO 07-12 13:11:37 [__init__.py:244] Automatically detected platform cuda.
INFO 07-12 13:11:42 [api_server.py:1287] vLLM API server version 0.9.1
INFO 07-12 13:11:42 [cli_args.py:309] non-default args: {'port': 8888, 'model': 'nvidia/Llama-3.1-70B-Instruct-FP8', 'dtype': 'bfloat16', 'max_model_len': 3072, 'quantization': 'modelopt', 'max_seq_len_to_capture': 3072, 'distributed_executor_backend': 'mp', 'tensor_parallel_size': 2, 'max_num_seqs': 32, 'disable_log_requests': True}
INFO 07-12 13:11:52 [config.py:823] This model supports multiple tasks: {'score', 'embed', 'reward', 'classify', 'generate'}. Defaulting to 'generate'.
INFO 07-12 13:11:52 [config.py:2195] Chunked prefill is enabled with max_num_batched_tokens=8192.
WARNING 07-12 13:11:53 [modelopt.py:49] Detected ModelOpt fp8 checkpoint. Please note that the format is experimental and could change.
WARNING 07-12 13:11:56 [env_override.py:17] NCCL_CUMEM_ENABLE is set to 0, skipping override. This may increase memory overhead with cudagraph+allreduce: https://github.com/NVIDIA/nccl/issues/1234
INFO 07-12 13:11:58 [__init__.py:244] Automatically detected platform cuda.
INFO 07-12 13:12:01 [core.py:455] Waiting for init message from front-end.
INFO 07-12 13:12:01 [core.py:70] Initializing a V1 LLM engine (v0.9.1) with config: model='nvidia/Llama-3.1-70B-Instruct-FP8', speculative_config=None, tokenizer='nvidia/Llama-3.1-70B-Instruct-FP8', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=3072, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=modelopt, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=nvidia/Llama-3.1-70B-Instruct-FP8, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["none"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
WARNING 07-12 13:12:01 [multiproc_worker_utils.py:307] Reducing Torch parallelism from 112 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 07-12 13:12:01 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1], buffer_handle=(2, 16777216, 10, 'psm_46083f38'), local_subscribe_addr='ipc:///tmp/a1ebfe5d-3fd2-4429-8bb9-f3c0fbbf2bd7', remote_subscribe_addr=None, remote_addr_ipv6=False)
WARNING 07-12 13:12:03 [env_override.py:17] NCCL_CUMEM_ENABLE is set to 0, skipping override. This may increase memory overhead with cudagraph+allreduce: https://github.com/NVIDIA/nccl/issues/1234
WARNING 07-12 13:12:03 [env_override.py:17] NCCL_CUMEM_ENABLE is set to 0, skipping override. This may increase memory overhead with cudagraph+allreduce: https://github.com/NVIDIA/nccl/issues/1234
INFO 07-12 13:12:05 [__init__.py:244] Automatically detected platform cuda.
INFO 07-12 13:12:05 [__init__.py:244] Automatically detected platform cuda.
WARNING 07-12 13:12:15 [utils.py:2737] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7f6959fefda0>
WARNING 07-12 13:12:15 [utils.py:2737] Methods determine_num_available_blocks,device_config,get_cache_block_size_bytes,initialize_cache not implemented in <vllm.v1.worker.gpu_worker.Worker object at 0x7faee13994c0>
(VllmWorker rank=0 pid=227) INFO 07-12 13:12:15 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_c920beec'), local_subscribe_addr='ipc:///tmp/da1301a2-5de4-4c8a-bc47-676af0172428', remote_subscribe_addr=None, remote_addr_ipv6=False)
(VllmWorker rank=1 pid=228) INFO 07-12 13:12:15 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_81be1106'), local_subscribe_addr='ipc:///tmp/a612604e-47d9-4e10-acc3-bd052dec4645', remote_subscribe_addr=None, remote_addr_ipv6=False)
(VllmWorker rank=1 pid=228) INFO 07-12 13:12:16 [utils.py:1126] Found nccl from library libnccl.so.2
(VllmWorker rank=1 pid=228) INFO 07-12 13:12:16 [pynccl.py:70] vLLM is using nccl==2.26.2
(VllmWorker rank=0 pid=227) INFO 07-12 13:12:16 [utils.py:1126] Found nccl from library libnccl.so.2
(VllmWorker rank=0 pid=227) INFO 07-12 13:12:16 [pynccl.py:70] vLLM is using nccl==2.26.2
```

Here is the command:
```bash
docker run --rm --network bmk-net --name bmk-server --runtime nvidia --gpus all --ipc host --privileged --ulimit memlock=-1 --ulimit stack=67108864 vllm/vllm-openai:v0.9.1 --model nvidia/Llama-3.1-70B-Instruct-FP8 --port 8888 --tensor-parallel-size 2 --distributed-executor-backend mp --dtype bfloat16 --quantization modelopt --max-num-seqs 32 --max-model-len 3072 --max-seq-len-to-capture 3072 --disable-log-requests
```

I'm not sure if I installed my software properly, so here's the list for reference:
```
1. NVIDIA kernel module version:
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  575.57.08  Release Build  (dvs-builder@U22-I3-H04-01-5)  Sat May 24 07:03:13 UTC 2025
GCC version:  gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)

2. User-space NVML driver version (nvidia-smi):
575.57.08
575.57.08
575.57.08
575.57.08
575.57.08
575.57.08
575.57.08
575.57.08

3. NVIDIA Fabric Manager package version:
ii  nvidia-fabricmanager-575               575.57.08-1                                  amd64        Fabric Manager for NVSwitch based systems.

4. Fabric Manager CLI version:
Fabric Manager version is : 575.57.08

5. NVLink Subnet Manager (nvlsm) version:
-------------------------------------------------
OpenSM 2025.03.1.1_7ed131d_929989e_ae214d2
Command Line Arguments:

6. NVLink-5 support library (libnvsdm) version:
ii  libnvsdm-575                           575.57.08-1                                  amd64        NVIDIA NVSDM provides library to retrieve telemetry from QM switches

7. NVLink-5 package version:
ii  nvlink5-575                            575.57.08-1                                  amd64        NVIDIA NVLink5 575

8. NVIDIA IMEX package version:
ii  nvidia-imex-575                        575.57.08-1                                  amd64        Imex process is a privileged/system client of RM and will facilitate the mapping of GPU memory(over NVLink) between GPUs via the memory import and export mechanisms.

9. NVIDIA Container Toolkit runtime version:
NVIDIA Container Runtime version 1.17.8
commit: f202b80a9b9d0db00d9b1d73c0128c8962c55f4d
spec: 1.2.1

runc version 1.2.5
commit: v1.2.5-0-g59923ef
spec: 1.2.0
go: go1.23.7
libseccomp: 2.5.3

10. Docker registered runtimes (should list 'nvidia'):
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc

11. CUDA Toolkit version (nvcc):
Cuda compilation tools, release 12.8, V12.8.93

12. NCCL APT packages installed:
ii  libnccl-dev                            2.27.5-1+cuda12.9                            amd64        NVIDIA Collective Communication Library (NCCL) Development Files
ii  libnccl2                               2.27.5-1+cuda12.9                            amd64        NVIDIA Collective Communication Library (NCCL) Runtime
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by simon-mo** [comment]
I ran into this once before and it worked on a second try. While I’m still trying to figure out why, can you try setting VLLM_SKIP_P2P_CHECK=1?

**Comment by robertgshaw2-redhat** [comment]
you need to give the container some shared memory for nccl

**Comment by functionstackx** [comment]
trying rn. will update if doing docker shm-size=16G works

**Comment by functionstackx** [comment]
@robertgshaw2-redhat thanks for taking a look at the issue.

from trying set with docker shm-size, it still seems like the issue is happening. I am trying with the latest `v0.9.2` image too.

## command
```bash
~$ docker run --rm --network bmk-net --name bmk-server --runtime nvidia --gpus all --ipc host --privileged --ulimit memlock=-1 --ulimit stack=67108864 --shm-size=16G vllm/vllm-openai:v0.9.2 --model nvidia/Llama-3.1-70B-Instruct-FP8 --port 8888 --tensor-parallel-size 2 --dtype auto --quantization modelopt --max-num-seqs 32 --max-model-len 3072 --max-seq-len-to-capture 3072 --disable-log-requests
```

## logs
```bash
sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
WARNING 07-12 16:19:07 [multiproc_worker_utils.py:307] Reducing Torch parallelism from 112 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 07-12 16:19:07 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1], buffer_handle=(2, 16777216, 10, 'psm_875f0461'), local_subscribe_addr='ipc:///tmp/ec949a17-d5b0-43f5-9e10-37cbd4d6e1be', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 07-12 16:19:11 [__init__.py:244] Automatically detected platform cuda.
INFO 07-12 16:19:11 [__init__.py:244] Automatically detected platform cuda.
(VllmWorker rank=1 pid=407) INFO 07-12 16:19:20 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_1273adb3'), local_subscribe_addr='ipc:///tmp/8e4796ed-6ddb-4f17-8a6c-fd36fd7f9ff0', remote_subscribe_addr=None, remote_addr_ipv6=False)
(VllmWorker rank=0 pid=406) INFO 07-12 16:19:20 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_d9f1f477'), local_subscribe_addr='ipc:///tmp/0472dded-21a7-44af-8ad7-22879ba3dc23', remote_subscribe_addr=None, remote_addr_ipv6=False)
(VllmWorker rank=1 pid=407) INFO 07-12 16:19:21 [__init__.py:1152] Found nccl from library libnccl.so.2
(VllmWorker rank=1 pid=407) INFO 07-12 16:19:21 [pynccl.py:70] vLLM is using nccl==2.26.2
(VllmWorker rank=0 pid=406) INFO 07-12 16:19:21 [__init__.py:1152] Found nccl from library libnccl.so.2
(VllmWorker rank=0 pid=406) INFO 07-12 16:19:21 [pynccl.py:70] vLLM is using nccl==2.26.2
```

**Comment by functionstackx** [comment]
hi @simon-mo ,

Thanks for taking the time on your weekend to take a look at this issue.

I tried with your suggested flag `VLLM_SKIP_P2P_CHECK=1` on 0.9.2 but unfortunately it still needs to freeze.

We only have 1 b200 node atm so unable to check if this is an issue with my b200 specifically

```bash
 docker run --rm --network bmk-net --name bmk-server --runtime nvidia --gpus all --ipc host --privileged --ulimit memlock=-1 --ulimit stack=67108864 --shm-size=16G -e VLLM_SKIP_P2P_CHECK=1 vllm/vllm-openai:v0.9.2 --model nvidia/Llama-3.1-70B-Instruct-FP8 --port 8888 --tensor-parallel-size 2 --dtype auto --quantization modelopt --max-num-seqs 32 --max-model-len 3072 --max-seq-len-to-capture 3072 --disable-log-requests
INFO 07-12 16:25:51 [__init__.py:244] Automatically detected platform cuda.
INFO 07-12 16:25:56 [api_server.py:1395] vLLM API server version 0.9.2
INFO 07-12 16:25:56 [cli_args.py:325] non-default args: {'port': 8888, 'model': 'nvidia/Llama-3.1-70B-Instruct-FP8', 'max_model_len': 3072, 'quantization': 'modelopt', 'max_seq_len_to_capture': 3072, 'tensor_parallel_size': 2, 'max_num_seqs': 32, 'disable_log_requests': True}
INFO 07-12 16:26:02 [config.py:841] This model supports multiple tasks: {'classify', 'embed', 'reward', 'generate'}. Defaulting to 'generate'.
INFO 07-12 16:26:02 [config.py:1472] Using max model len 3072
INFO 07-12 16:26:03 [config.py:2285] Chunked prefill is enabled with max_num_batched_tokens=8192.
WARNING 07-12 16:26:04 [modelopt.py:49] Detected ModelOpt fp8 checkpoint. Please note that the format is experimental and could change.
INFO 07-12 16:26:09 [__init__.py:244] Automatically detected platform cuda.
INFO 07-12 16:26:11 [core.py:526] Waiting for init message from front-end.
INFO 07-12 16:26:11 [core.py:69] Initializing a V1 LLM engine (v0.9.2) with config: model='nvidia/Llama-3.1-70B-Instruct-FP8', speculative_config=None, tokenizer='nvidia/Llama-3.1-70B-Instruct-FP8', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=3072, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=modelopt, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=nvidia/Llama-3.1-70B-Instruct-FP8, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":512,"local_cache_dir":null}
WARNING 07-12 16:26:11 [multiproc_worker_utils.py:307] Reducing Torch parallelism from 112 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 07-12 16:26:11 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0, 1], buffer_handle=(2, 16777216, 10, 'psm_b1f306c6'), local_subscribe_addr='ipc:///tmp/646c6f7d-4f2f-4042-a2a6-3fa86e2e2b40', remote_subscribe_addr=None, remote_addr_ipv6=False)
INFO 07-12 16:26:16 [__init__.py:244] Automatically detected platform cuda.
INFO 07-12 16:26:16 [__init__.py:244] Automatically detected platform cuda.
(VllmWorker rank=1 pid=407) INFO 07-12 16:26:25 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_c03e0ec8'), local_subscribe_addr='ipc:///tmp/9095920b-3505-4796-834a-ab3d3784272a', remote_subscribe_addr=None, remote_addr_ipv6=False)
(VllmWorker rank=0 pid=406) INFO 07-12 16:26:25 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[0], buffer_handle=(1, 10485760, 10, 'psm_24da798a'), local_subscribe_addr='ipc:///tmp/52335bd8-59f5-49b2-a285-bc03e56bd71a', remote_subscribe_addr=None, remote_addr_ipv6=False)
(VllmWorker rank=1 pid=407) INFO 07-12 16:26:25 [__init__.py:1152] Found nccl from library libnccl.so.2
(VllmWorker rank=1 pid=407) INFO 07-12 16:26:25 [pynccl.py:70] vLLM is using nccl==2.26.2
(VllmWorker rank=0 pid=406) INFO 07-12 16:26:25 [__init__.py:1152] Found nccl from library libnccl.so.2
(VllmWorker rank=0 pid=406) INFO 07-12 16:26:25 [pynccl.py:70] vLLM is using nccl==2.26.2
```

**Comment by functionstackx** [comment]
i just checked that `nccl-tests` works so probably isn't the node issue, but doesn't rule it out completely as there could be some race condition.

```bash
#                                                              out-of-place                       in-place          
#       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
#        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
           8             2     float     sum      -1    46.61    0.00    0.00      0    45.67    0.00    0.00      0
          16             4     float     sum      -1    46.14    0.00    0.00      0    45.76    0.00    0.00      0
          32             8     float     sum      -1    98.79    0.00    0.00      0    47.25    0.00    0.00      0
          64            16     float     sum      -1    47.24    0.00    0.00      0    47.12    0.00    0.00      0
         128            32     float     sum      -1    47.47    0.00    0.00      0    47.06    0.00    0.00      0
         256            64     float     sum      -1    47.23    0.01    0.01      0    47.17    0.01    0.01      0
         512           128     float     sum      -1    47.21    0.01    0.02      0    47.07    0.01    0.02      0
        1024           256     float     sum      -1    47.11    0.02    0.04      0    47.22    0.02    0.04      0
        2048           512     float     sum      -1    47.71    0.04    0.08      0    47.20    0.04    0.08      0
        4096          1024     float     sum      -1    47.56    0.09    0.15      0    47.35    0.09    0.15      0
        8192          2048     float     sum      -1    47.43    0.17    0.30      0    47.41    0.17    0.30      0
       16384          4096     float     sum      -1    47.57    0.34    0.60      0    47.39    0.35    0.60      0
       32768          8192     float     sum      -1    46.80    0.70    1.23      0    47.40    0.69    1.21      0
       65536         16384     float     sum      -1    47.67    1.37    2.41      0    47.74    1.37    2.40      0
      131072         32768     float     sum      -1    48.86    2.68    4.69      0    48.85    2.68    4.70      0
      262144         65536     float     sum      -1    50.86    5.15    9.02      0    50.74    5.17    9.04      0
      524288        131072     float     sum      -1    53.94    9.72   17.01      0    54.19    9.68   16.93      0
     1048576        262144     float     sum      -1    60.18   17.42   30.49      0    60.48   17.34   30.34      0
     2097152        524288     float     sum      -1    60.75   34.52   60.41      0    60.25   34.81   60.91      0
     4194304       1048576     float     sum      -1    58.56   71.63  125.35      0    58.23   72.03  126.05      0
     8388608       2097152     float     sum      -1    79.82  105.09  183.91      0    79.41  105.64  184.87      0
    16777216       4194304     float     sum      -1    110.8  151.46  265.05      0    108.8  154.22  269.89      0
    33554432       8388608     float     sum      -1    174.2  192.57  336.99      0    172.7  194.31  340.03      0
    67108864      16777216     float     sum      -1    283.4  236.81  414.43      0    283.3  236.90  414.58      0
   134217728      33554432     float     sum      -1    402.8  333.20  583.10      0    401.5  334.28  584.99      0
   268435456      67108864     float     sum      -1    728.0  368.71  645.25      0    728.7  368.38  644.67      0
   536870912     134217728     float     sum      -1   1359.3  394.96  691.17      0   1357.2  395.56  692.23      0
  1073741824     268435456     float     sum      -1   2620.1  409.81  717.17      0   2622.3  409.46  716.56      0
  2147483648     536870912     float     sum      -1   4605.2  466.31  816.05      0   4607.0  466.14  815.74      0
  4294967296    1073741824     float     sum      -1   9057.0  474.22  829.88      0   9062.9  473.91  829.34      0
  8589934592    2147483648     float     sum      -1    18135  473.66  828.91      0    18120  474.06  829.60      0
 17179869184    4294967296     float     sum      -1    36088  476.06  833.10      0    36079  476.17  833.29      0
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 231.334 
#
```

**Comment by functionstackx** [comment]
on bare metal, [stas's all reduce script](https://github.com/stas00/ml-engineering/blob/master/network/benchmarks/all_reduce_bench.py) works fine too, but inside the vllm container, it freezes.

## docker start command
```bash
docker run -it --rm   --network bmk-net   --name bmk-server   --runtime nvidia   --gpus all   --ipc host   --privileged   --ulimit memlock=-1   --ulimit stack=67108864   --shm-size=16G   -e VLLM_SKIP_P2P_CHECK=1   --entrypoint bash   vllm/vllm-openai:v0.9.2
```

## run command
```
python3 -u -m torch.distributed.run --nproc_per_node=8 --standalone all_reduce_bench.py
```

## nccl & torch version on bare metal
```bash
ubuntu@node:~$ pip list | grep torch
torch                    2.7.1+cu128
torchaudio               2.7.1+cu128
torchvision              0.22.1+cu128
ubuntu@node:~$ pip list | grep nccl
nvidia-nccl-cu12         2.26.2
```

## nccl version inside the command
```bash
root@e8f90d23d052:/vllm-workspace# apt list --installed | grep nccl

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libnccl-dev/unknown,now 2.25.1-1+cuda12.8 amd64 [installed,upgradable to: 2.27.5-1+cuda12.9]
libnccl2/unknown,now 2.25.1-1+cuda12.8 amd64 [installed,upgradable to: 2.27.5-1+cuda12.9]

root@e8f90d23d052:/vllm-workspace# pip list | grep nccl
nvidia-nccl-cu12                  2.26.2
```

## bare metal logs
```bash

| payload |    busbw   |    algbw   |
| ------: | ---------: | ---------: |
|   32KiB |   0.51GBps |   0.29GBps |
|   64KiB |   1.07GBps |   0.61GBps |
|  128KiB |   4.10GBps |   2.34GBps |
|  256KiB |   8.08GBps |   4.62GBps |
|  512KiB |  15.02GBps |   8.58GBps |
|    1MiB |  30.72GBps |  17.55GBps |
|    2MiB |  58.60GBps |  33.49GBps |
|    4MiB |  56.47GBps |  32.27GBps |
|    8MiB | 101.54GBps |  58.02GBps |
|   16MiB | 236.82GBps | 135.32GBps |
|   32MiB | 334.81GBps | 191.32GBps |
|   64MiB | 401.64GBps | 229.51GBps |
|  128MiB | 566.54GBps | 323.74GBps |
|  256MiB | 652.18GBps | 372.67GBps |
|  512MiB | 708.29GBps | 404.74GBps |
|    1GiB | 749.21GBps | 428.12GBps |
|    2GiB | 810.95GBps | 463.40GBps |
|    4GiB | 824.21GBps | 470.98GBps |
|    8GiB | 832.79GBps | 475.88GBps |
|   16GiB | 836.97GBps | 478.27GBps |
```

**Comment by functionstackx** [comment]
i tried on the NGC container and the stas all reduce script works. seems like the issue is the vllm image for blackwell

`nvcr.io/nvidia/pytorch:25.06-py3`

```bash
docker run -it --rm   --network bmk-net   --name bmk-server   --runtime nvidia   --gpus all   --ipc host   --privileged   --ulimit memlock=-1   --ulimit stack=67108864   --shm-size=16G   -e VLLM_SKIP_P2P_CHECK=1   --entrypoint bash   nvcr.io/nvidia/pytorch:25.06-py3
```

**Comment by functionstackx** [comment]
from using `py-spy top`, it seems like it is stuck in 

```bash
ncclCommInitRank (vllm/distributed/device_communicators/pynccl_wrapper.py)
```

<img width="1412" height="593" alt="Image" src="https://github.com/user-attachments/assets/b92c3337-912d-4e4e-ad15-5b09f69eecd8" />

**Comment by functionstackx** [comment]
it seems like it is stuck on this line https://github.com/vllm-project/vllm/blob/f45a33288624f30e3ab3d1f5c3c4499e86c5bb7d/vllm/distributed/device_communicators/pynccl.py#L100

<img width="1711" height="511" alt="Image" src="https://github.com/user-attachments/assets/1f0e5924-25b9-48bf-af5a-a94696da30a5" />

**Comment by functionstackx** [comment]
hmm, this is really flaky

 seems like for 75% of the time, it is stuck on `ncclCommInitRank` forever and it doesnt unfreeze

the other 25% of the time, `ncclCommInitRank` takes 10 mins

**Comment by functionstackx** [comment]
from using `sudo perf top --sort=comm,dso -p <pid>`, it is stuck on `libnvidia-ptxjitcompiler.so.575.57.08`

which according to the [nvidia "docs"](https://download.nvidia.com/XFree86/Linux-x86_64///575.57.08/README/installedcomponents.html), it is the jit compiler that compiles the kernel in ptx virtual isa into gpu machine code (i.e. acutal isa)

not sure where in `ncclCommInitRank` even requires ptx to sass translation as it seems like all host side api calls and no device side code https://github.com/NVIDIA/nccl/blob/f44ac759fee12ecb3cc6891e9e739a000f66fd70/src/init.cc#L1720-L1736


```bash
Samples: 351K of event 'cycles', 4000 Hz, Event count (approx.): 33352449377 lost: 0/0 drop: 0/0
Overhead  Command          Shared Object
  95.99%  python3          libnvidia-ptxjitcompiler.so.575.57.08
   2.72%  python3          libc.so.6
   0.98%  python3          [kernel]
   0.26%  python3          libcuda.so.575.57.08
   0.02%  python3          libm.so.6
   0.01%  pt_nccl_watchdg  [kernel]
   0.01%  cuda-EvtHandlr   [kernel]
   0.00%  pt_nccl_heartbt  [kernel]
   0.00%  python3          libstdc++.so.6.0.30
   0.00%  python3          libtorch_cpu.so
   0.00%  pt_nccl_watchdg  libstdc++.so.6.0.30
   0.00%  pt_nccl_watchdg  libtorch_cuda.so
   0.00%  cuda-EvtHandlr   libcuda.so.575.57.08
   0.00%  pt_nccl_watchdg  libc.so.6
   0.00%  pt_nccl_watchdg  [vdso]
   0.00%  python3          libquadmath-96973f99-934c22de.so.0.0.0
   0.00%  python3          [vdso]
```

**Comment by functionstackx** [comment]
from using `strace` it seems like spends 10-30 minutes converting all device kernels in NCCL lib from ptx to sass when calling `ncclCommInitRank`

`sudo strace -p <PID>`

not sure when it is so slow

```bash
kdir("/root/.nv/ComputeCache/1", 0700) = -1 EEXIST (File exists)
mkdir("/root/.nv/ComputeCache/1/0", 0700) = -1 EEXIST (File exists)
mkdir("/root/.nv/ComputeCache/1/0/", 0700) = -1 EEXIST (File exists)
openat(AT_FDCWD, "/root/.nv/ComputeCache/1/0/90b4d95b7832ba", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 164
newfstatat(164, "", {st_mode=S_IFREG|0644, st_size=0, ...}, AT_EMPTY_PATH) = 0
write(164, "A\0\0\0\3359\37\0\0\0\0\0\230\201\33\0\0\0\0\0T\317\323\27\232\235\367vMay "..., 4096) = 4096
write(164, "103, 110, 101, 100, 32, 99, 104,"..., 2039808) = 2039808
write(164, "r5579+1064], %rd3805;\n\n$L__BB7_9"..., 4096) = 4096
write(164, "_AllReduce_SumPostDiv_u32_RING_L"..., 1798144) = 1798144
write(164, "\0\10\0\0\0\0\0\0\0\30\0\0\0\0\0\0\0007\5\0\0\4\0\0\0@\0\0\0\0\0\0"..., 2961) = 2961
close(164)                              = 0
lseek(163, 688, SEEK_SET)               = 688
```

**Comment by functionstackx** [comment]
temp fix seems to be mount the sass cache path in the docker container in the host machine too `-v ./computecache:/root/.nv/ComputeCache`, `ncclCommInitRank` takes less than a minute now when it gets the cache hit.

in terms of permanent fix, i am not too sure since i am not familar with when it would take 10 minutes to convert the entire nccl device library kernels from ptx to sass. 

@kedarpotdar-nv can u look into this too and why ptx to sass compilation takes 10-30 minutes

**Comment by functionstackx** [comment]
The issue seems to be that whatever nccl package vllm is calling isn't precompiled with the Blackwell arch so it has to live generation the blackwell sass from the ptx in the shared lib

https://developer.nvidia.com/blog/cuda-pro-tip-understand-fat-binaries-jit-caching/

**Comment by functionstackx** [comment]
could be wrong but from looking at the git blame like before `nccl>=2.27.5`, nccl packages was only built with `sm90` (i.e. hopper, and not with blackwell). tho after `2.27.5`, the nccl packages is built with `sm100` (i.e. blackwell) too

Blackwell NCCL support was added in `2.25.1` but it only did blackwell aot gen for cuda 13 which isn't publicly accessible yet

in https://github.com/pytorch/pytorch/pull/157108 , upstream torch updated to `nccl==2.27.51`


## Link to Git Blame on 2.27.5
https://github.com/NVIDIA/nccl/blame/7c12c627c62ef4e5a2485777a8d9dce58f3f562f/makefiles/common.mk#L46

## Git blame prev 2.27.5
https://github.com/NVIDIA/nccl/blame/72d2432094d6ae36abd6e511c3a16a2d052dbf94/makefiles/common.mk#L42-L52

## Git blame 2.25.1
https://github.com/NVIDIA/nccl/commit/80f6bda4378b99d99e82b4d76a633791cc45fef0#diff-45a9034a0c75cbfbbb34e853a43f6513c1d4c933eccf6adca705abe234fc1113R42-R49

**Comment by youkaichao** [comment]
@functionstackx are you using the system nccl? I checked the nccl version installed from https://pypi.org/project/nvidia-nccl-cu12/ , using `cuobjdump`, and it seems both 2.26.2 and 2.27 has cubin (sass) for sm100 architecture.

**Comment by functionstackx** [comment]
@youkaichao I believe it is using the pypi nccl, but it triggers a compile to sass everytime

**Comment by MattTheCuber** [comment]
I believe I am getting the same error on my 2x Pro 6000s (RHEL 9.5) when running `docker run -d --gpus '"device=0,2"' -v /opt/tools/huggingface/cache:/root/.cache/huggingface -p 7007:8000 --ipc host vllm/vllm-openai:latest --model Qwen/Qwen3-32B --tensor-parallel-size 2 --enable-auto-tool-choice --tool-call-parser hermes`

**Comment by MattTheCuber** [comment]
Might also be related to #14449

**Comment by ptrblck** [comment]
This is a known issue with the `nvidia-nccl-cu12==2.26.2` pip wheels which are used in our PyTorch 2.7.x release.
As a workaround you can install PyTorch as before and replace the NCCL wheel via:
```python
# install PyTorch e.g. via pip install torch
pip uninstall nvidia-nccl-cu12
pip install nvidia-nccl-cu12==2.26.2.post1
```
This will use the same `2.26.2` release with the missing Blackwell architectures. You can also use our PyTorch nightly binaries, which use a newer NCCL version or you could also wait for the upcoming PyTorch 2.8.0 release.

**Comment by MattTheCuber** [comment]
To expand on @ptrblck's comment. If you want to apply this to the Docker method, you can follow these steps:

1. Create a `Dockerfile` with the following content:
    ```Dockerfile
    FROM vllm/vllm-openai:latest
    RUN python3 -m pip uninstall nvidia-nccl-cu12 -y && python3 -m pip install nvidia-nccl-cu12==2.26.2.post1
    ```
2. Run `docker build -t vllm-openai-nccl .`
3. Run your `docker run ...` command with `-e NCCL_P2P_DISABLE=1` and switch the container image from `vllm/vllm-openai:latest` to `vllm-openai-nccl`. For example:
    ```
    docker run --gpus all -e NCCL_P2P_DISABLE=1 --ipc host vllm-openai-nccl --model Qwen/Qwen3-Coder-30B-A3B-Instruct --tensor-parallel-size 4
    ```

**Comment by coffee-overflow** [comment]
> To expand on [@ptrblck](https://github.com/ptrblck)'s comment. If you want to apply this to the Docker method, you can follow these steps:
> 
> 1. Create a `Dockerfile` with the following content:
>    FROM vllm/vllm-openai:latest
>    RUN python3 -m pip uninstall nvidia-nccl-cu12 -y && python3 -m pip install nvidia-nccl-cu12==2.26.2.post1
> 2. Run `docker build -t vllm-openai-nccl .`
> 3. Run your `docker run ...` command with `-e NCCL_P2P_DISABLE=1` and switch the container image from `vllm/vllm-openai:latest` to `vllm-openai-nccl`. For example:
>    ```
>    docker run --gpus all -e NCCL_P2P_DISABLE=1 --ipc host vllm-openai-nccl --model Qwen/Qwen3-Coder-30B-A3B-Instruct --tensor-parallel-size 4
>    ```

Despite attempting a workaround to slice models across two L40s (48GB) GPUs, it didn't work. 

While vllm/vllm-openai:v0.8.5 image operates successfully, vllm/vllm-openai:v0.10.1 does not. Additionally, I attempted upgrading torch to version 2.8, but it seems that vLLM v0.10.1 is not compatible with this version. 

Does anyone have any other suggestions? 

Thanks in advance.

The helm chart values.yaml is as follows:

```
servingEngineSpec:
  enableEngine: true
  command: ["python3", "-m", "vllm.entrypoints.openai.api_server", "--host=0.0.0.0", "--port=8000"]
  modelSpec:
    - name: "qwen-7b"
      modelURL: /data/Qwen2.5-7B-Instruct
      repository: docker.io/vllm/vllm-openai
      tag: v0.10.1
      imagePullPolicy: IfNotPresent
      replicaCount: 1
      requestCPU: 2
      requestMemory: "4Gi"
      limitCPU: 6
      limitMemory: "8Gi"
      requestGPU: 2         
      limitGPU: 2            
      pvcStorage: "40Gi"
      pvcAccessMode:
        - ReadWriteOnce
      storageClass: longhorn
      vllmConfig:
        gpuMemoryUtilization: 0.8
        tensorParallelSize: 2
        maxNumSeqs: 16       
        maxModelLen: 8192     
        shmSize: "30Gi"
      env:
        - name: HF_HUB_OFFLINE
          value: "1"
        - name: TRANSFORMERS_OFFLINE
          value: "1"
        - name: HUGGINGFACE_HUB_CACHE
          value: "/data"
        - name: NCCL_IB_DISABLE
          value: "1"
        - name: NCCL_DEBUG
          value: "INFO"
        - name: NCCL_DEBUG_SUBSYS
          value: "ALL"
        - name: NCCL_ASYNC_ERROR_HANDLING
          value: "1"
        - name: NCCL_P2P_DISABLE
          value: "1"        
      nodeSelectorTerms:
        - matchExpressions:
            - key: nvidia.com/gpu.product
              operator: "In"
              values:
                - "NVIDIA-L40S-48Q"
                
hostIPC: true
hostNetwork: true

```

**Comment by shahizat** [comment]
Hello, I have the same issue with nccl==2.28.9 on the B200.

```
(APIServer pid=363862) INFO 07-31 05:49:24 [api_utils.py:345]
(APIServer pid=363862) INFO 07-31 05:49:24 [api_utils.py:345]        █     █     █▄   ▄█
(APIServer pid=363862) INFO 07-31 05:49:24 [api_utils.py:345]  ▄▄ ▄█ █     █     █ ▀▄▀ █  version 0.26.0
(APIServer pid=363862) INFO 07-31 05:49:24 [api_utils.py:345]   █▄█▀ █     █     █     █  model   nvidia/Qwen3.6-35B-A3B-NVFP4
(APIServer pid=363862) INFO 07-31 05:49:24 [api_utils.py:345]    ▀▀  ▀▀▀▀▀ ▀▀▀▀▀ ▀     ▀
(APIServer pid=363862) INFO 07-31 05:49:24 [api_utils.py:345]
(APIServer pid=363862) INFO 07-31 05:49:24 [api_utils.py:273] non-default args: {'model_tag': 'nvidia/Qwen3.6-35B-A3B-NVFP4', 'model': 'nvidia/Qwen3.6-35B-A3B-NVFP4', 'max_model_len': 262144, 'quantization': 'modelopt', 'reasoning_parser': 'qwen3', 'tensor_parallel_size': 4}
(APIServer pid=363862) INFO 07-31 05:49:26 [model.py:623] Resolved architecture: Qwen3_5MoeForConditionalGeneration
(APIServer pid=363862) INFO 07-31 05:49:26 [model.py:1788] Using max model len 262144
(APIServer pid=363862) INFO 07-31 05:49:27 [scheduler.py:252] Chunked prefill is enabled with max_num_batched_tokens=8192.
(APIServer pid=363862) WARNING 07-31 05:49:27 [modelopt.py:385] Detected ModelOpt fp8 checkpoint (quant_algo=FP8). Please note that the format is experimental and could change.
(APIServer pid=363862) WARNING 07-31 05:49:27 [modelopt.py:1034] Detected ModelOpt NVFP4 checkpoint (quant_algo=NVFP4). Please note that the format is experimental and could change in future.
(APIServer pid=363862) WARNING 07-31 05:49:27 [modelopt.py:1034] Detected ModelOpt NVFP4 checkpoint (quant_algo=W4A16_NVFP4). Please note that the format is experimental and could change in future.
(APIServer pid=363862) WARNING 07-31 05:49:27 [modelopt.py:1707] Detected ModelOpt MXFP8 checkpoint. Please note that the format is experimental and could change in future.
(APIServer pid=363862) INFO 07-31 05:49:27 [vllm.py:1109] Asynchronous scheduling is enabled.
(APIServer pid=363862) INFO 07-31 05:49:27 [kernel.py:295] Final IR op priority after setting platform defaults: IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native'])
(APIServer pid=363862) [transformers] The `use_fast` parameter is deprecated and will be removed in a future version. Use `backend="torchvision"` instead of `use_fast=True`, or `backend="pil"` instead of `use_fast=False`.
(EngineCore pid=364151) INFO 07-31 05:50:05 [core.py:116] Initializing a V1 LLM engine (v0.26.0) with config: model='nvidia/Qwen3.6-35B-A3B-NVFP4', speculative_config=None, tokenizer='nvidia/Qwen3.6-35B-A3B-NVFP4', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=262144, download_dir=None, load_format=auto, tensor_parallel_size=4, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=False, quantization=modelopt_mixed, quantization_config=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='qwen3', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False, jit_monitor_mode='warn', jit_monitor_verbose=False), seed=0, served_model_name=nvidia/Qwen3.6-35B-A3B-NVFP4, enable_prefix_caching=False, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'ir_enable_torch_wrap': True, 'splitting_ops': ['vllm::unified_attention_with_output', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::qwen_gdn_attention_core', 'vllm::gdn_attention_core_xpu', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::deepseek_v4_attention', 'vllm::hpc_rope_norm_forward', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update'], 'compile_mm_encoder': False, 'cudagraph_mm_encoder': False, 'encoder_cudagraph_token_budgets': [], 'encoder_cudagraph_max_vision_items_per_batch': 0, 'encoder_cudagraph_max_frames_per_batch': None, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'size_asserts': False, 'alignment_asserts': False, 'scalar_asserts': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False, 'enable_qk_norm_rope_fusion': False, 'fuse_rope_kvcache_cat_mla': False, 'fuse_act_padding': False, 'fuse_qk_norm_rope_kvcache': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': False, 'static_all_moe_layers': []}, kernel_config=KernelConfig(ir_op_priority=IrOpPriorityConfig(rms_norm=['native'], fused_add_rms_norm=['native']), enable_flashinfer_autotune=True, enable_cutedsl_warmup=True, enable_bf16x3_router_gemm=False, moe_backend='auto', linear_backend='auto')
(EngineCore pid=364151) WARNING 07-31 05:50:05 [multiproc_executor.py:1070] Reducing Torch parallelism from 48 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
(EngineCore pid=364151) INFO 07-31 05:50:05 [multiproc_executor.py:140] DP group leader: node_rank=0, node_rank_within_dp=0, master_addr=127.0.0.1, mq_connect_ip=131.226.222.6 (local), world_size=4, local_world_size=4
(Worker pid=364356) INFO 07-31 05:50:22 [parallel_state.py:1615] world_size=4 rank=3 local_rank=3 distributed_init_method=tcp://127.0.0.1:40135 backend=nccl
(Worker pid=364354) INFO 07-31 05:50:22 [parallel_state.py:1615] world_size=4 rank=1 local_rank=1 distributed_init_method=tcp://127.0.0.1:40135 backend=nccl
(Worker pid=364353) INFO 07-31 05:50:23 [parallel_state.py:1615] world_size=4 rank=0 local_rank=0 distributed_init_method=tcp://127.0.0.1:40135 backend=nccl
(Worker pid=364355) INFO 07-31 05:50:23 [parallel_state.py:1615] world_size=4 rank=2 local_rank=2 distributed_init_method=tcp://127.0.0.1:40135 backend=nccl
(Worker pid=364353) INFO 07-31 05:50:25 [pynccl.py:113] vLLM is using nccl==2.28.9

```
