### ISSUE TITLE
[Bug]: w8a8 quantization not supporting sm120

### ISSUE THREAD

**Issue by sarmiena** [vllm-project/vllm#21097]
### Your current environment

<details>
<summary>Collect env</summary>

```text
oot@1ed942223b03:/vllm-workspace# python3 collect_env.py 
Collecting environment information...
==============================
        System Info
==============================
OS                           : Ubuntu 22.04.5 LTS (x86_64)
GCC version                  : (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version                : Could not collect
CMake version                : version 4.0.3
Libc version                 : glibc-2.35

==============================
       PyTorch Info
==============================
PyTorch version              : 2.7.1+cu128
Is debug build               : False
CUDA used to build PyTorch   : 12.8
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.11 (main, Jun  4 2025, 08:56:18) [GCC 11.4.0] (64-bit runtime)
Python platform              : Linux-6.8.0-63-generic-x86_64-with-glibc2.35

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : 12.8.93
CUDA_MODULE_LOADING set to   : LAZY
GPU models and configuration : 
GPU 0: NVIDIA RTX PRO 6000 Blackwell Workstation Edition
GPU 1: NVIDIA RTX PRO 6000 Blackwell Workstation Edition

Nvidia driver version        : 575.57.08
cuDNN version                : Could not collect
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        52 bits physical, 57 bits virtual
Byte Order:                           Little Endian
CPU(s):                               64
On-line CPU(s) list:                  0-63
Vendor ID:                            AuthenticAMD
Model name:                           AMD EPYC 9355P 32-Core Processor
CPU family:                           26
Model:                                2
Thread(s) per core:                   2
Core(s) per socket:                   32
Socket(s):                            1
Stepping:                             1
Frequency boost:                      enabled
CPU max MHz:                          4413.2319
CPU min MHz:                          1500.0000
BogoMIPS:                             7100.24
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp ibrs_enhanced vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local user_shstk avx_vnni avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin cppc amd_ibpb_ret arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif x2avic v_spec_ctrl vnmi avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid bus_lock_detect movdiri movdir64b overflow_recov succor smca fsrm avx512_vp2intersect flush_l1d debug_swap
Virtualization:                       AMD-V
L1d cache:                            1.5 MiB (32 instances)
L1i cache:                            1 MiB (32 instances)
L2 cache:                             32 MiB (32 instances)
L3 cache:                             256 MiB (8 instances)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-63
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

==============================
Versions of relevant libraries
==============================
[pip3] flashinfer-python==0.2.6.post1+cu128torch2.7
[pip3] numpy==2.2.6
[pip3] nvidia-cublas-cu12==12.8.3.14
[pip3] nvidia-cuda-cupti-cu12==12.8.57
[pip3] nvidia-cuda-nvrtc-cu12==12.8.61
[pip3] nvidia-cuda-runtime-cu12==12.8.57
[pip3] nvidia-cudnn-cu12==9.7.1.26
[pip3] nvidia-cufft-cu12==11.3.3.41
[pip3] nvidia-cufile-cu12==1.13.0.11
[pip3] nvidia-curand-cu12==10.3.9.55
[pip3] nvidia-cusolver-cu12==11.7.2.55
[pip3] nvidia-cusparse-cu12==12.5.7.53
[pip3] nvidia-cusparselt-cu12==0.6.3
[pip3] nvidia-nccl-cu12==2.26.2
[pip3] nvidia-nvjitlink-cu12==12.8.61
[pip3] nvidia-nvtx-cu12==12.8.55
[pip3] pyzmq==27.0.0
[pip3] torch==2.7.1+cu128
[pip3] torchvision==0.22.1
[pip3] transformers==4.53.2
[pip3] triton==3.3.1
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
Neuron SDK Version           : N/A
vLLM Version                 : 0.9.3.dev0+ga5dd03c1e.d20250717 (git sha: a5dd03c1e, date: 20250717)
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
  	GPU0	GPU1	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NODE	0-63	0		N/A
GPU1	NODE	 X 	0-63	0		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

==============================
     Environment Variables
==============================
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_REQUIRE_CUDA=cuda>=12.8 brand=unknown,driver>=470,driver<471 brand=grid,driver>=470,driver<471 brand=tesla,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=vapps,driver>=470,driver<471 brand=vpc,driver>=470,driver<471 brand=vcs,driver>=470,driver<471 brand=vws,driver>=470,driver<471 brand=cloudgaming,driver>=470,driver<471 brand=unknown,driver>=535,driver<536 brand=grid,driver>=535,driver<536 brand=tesla,driver>=535,driver<536 brand=nvidia,driver>=535,driver<536 brand=quadro,driver>=535,driver<536 brand=quadrortx,driver>=535,driver<536 brand=nvidiartx,driver>=535,driver<536 brand=vapps,driver>=535,driver<536 brand=vpc,driver>=535,driver<536 brand=vcs,driver>=535,driver<536 brand=vws,driver>=535,driver<536 brand=cloudgaming,driver>=535,driver<536 brand=unknown,driver>=550,driver<551 brand=grid,driver>=550,driver<551 brand=tesla,driver>=550,driver<551 brand=nvidia,driver>=550,driver<551 brand=quadro,driver>=550,driver<551 brand=quadrortx,driver>=550,driver<551 brand=nvidiartx,driver>=550,driver<551 brand=vapps,driver>=550,driver<551 brand=vpc,driver>=550,driver<551 brand=vcs,driver>=550,driver<551 brand=vws,driver>=550,driver<551 brand=cloudgaming,driver>=550,driver<551 brand=unknown,driver>=560,driver<561 brand=grid,driver>=560,driver<561 brand=tesla,driver>=560,driver<561 brand=nvidia,driver>=560,driver<561 brand=quadro,driver>=560,driver<561 brand=quadrortx,driver>=560,driver<561 brand=nvidiartx,driver>=560,driver<561 brand=vapps,driver>=560,driver<561 brand=vpc,driver>=560,driver<561 brand=vcs,driver>=560,driver<561 brand=vws,driver>=560,driver<561 brand=cloudgaming,driver>=560,driver<561 brand=unknown,driver>=565,driver<566 brand=grid,driver>=565,driver<566 brand=tesla,driver>=565,driver<566 brand=nvidia,driver>=565,driver<566 brand=quadro,driver>=565,driver<566 brand=quadrortx,driver>=565,driver<566 brand=nvidiartx,driver>=565,driver<566 brand=vapps,driver>=565,driver<566 brand=vpc,driver>=565,driver<566 brand=vcs,driver>=565,driver<566 brand=vws,driver>=565,driver<566 brand=cloudgaming,driver>=565,driver<566
NCCL_VERSION=2.25.1-1
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NVIDIA_PRODUCT_NAME=CUDA
VLLM_USAGE_SOURCE=production-docker-image
CUDA_VERSION=12.8.1
LD_LIBRARY_PATH=/usr/local/cuda/lib64
NCCL_CUMEM_ENABLE=0
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY
```

</details>

### 🐛 Describe the bug

According to #17280 and https://docs.vllm.ai/en/stable/features/quantization/int8.html#3-applying-quantization we should be able to use w8a8 fp8 with sm120

Used official docker image via ```docker pull vllm/vllm-openai:v0.9.2```

Started docker container via ```docker run -e HF_TOKEN --gpus all --rm -it --entrypoint bash -v ./models:/models -v ./scripts:/scripts vllm/vllm-openai:v0.9.2```

once inside I followed https://docs.vllm.ai/en/stable/features/quantization/int8.html#3-applying-quantization to quantize the example model and got ```CUDA error: no kernel image is available for execution on the device```

Wasn't #17280 supposed to fix this?

```
((venv) ) root@f8f14b925638:/scripts# python3 quantize.rb 
INFO 07-17 00:03:09 [__init__.py:244] Automatically detected platform cuda.
/scripts/venv/lib/python3.12/site-packages/torch/cuda/__init__.py:287: UserWarning: 
NVIDIA RTX PRO 6000 Blackwell Workstation Edition with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA RTX PRO 6000 Blackwell Workstation Edition GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
/scripts/venv/lib/python3.12/site-packages/llmcompressor/pytorch/__init__.py:19: UserWarning: torch.compile is not supported by llmcompressor for torch 2.0.x
  warnings.warn(
config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 654/654 [00:00<00:00, 6.44MB/s]
model.safetensors.index.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23.9k/23.9k [00:00<00:00, 14.6MB/s]
model-00004-of-00004.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.17G/1.17G [02:35<00:00, 7.49MB/s]
model-00002-of-00004.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.00G/5.00G [03:08<00:00, 26.6MB/s]
model-00003-of-00004.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.92G/4.92G [03:09<00:00, 26.0MB/s]
model-00001-of-00004.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4.98G/4.98G [03:09<00:00, 26.3MB/s]
Fetching 4 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [03:09<00:00, 47.35s/it]
/scripts/venv/lib/python3.12/site-packages/torch/cuda/__init__.py:287: UserWarning: █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 4.71G/4.92G [03:07<00:02, 72.4MB/s]
NVIDIA RTX PRO 6000 Blackwell Workstation Edition with CUDA capability sm_120 is not compatible with the current PyTorch installation.████████████████████████████████████████████████████████████████████████████████████| 4.92G/4.92G [03:09<00:00, 105MB/s]
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA RTX PRO 6000 Blackwell Workstation Edition GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  3.31it/s]
generation_config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 187/187 [00:00<00:00, 1.50MB/s]
tokenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 51.0k/51.0k [00:00<00:00, 9.80MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.09M/9.09M [00:00<00:00, 22.1MB/s]
special_tokens_map.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 73.0/73.0 [00:00<00:00, 617kB/s]
README.md: 3.90kB [00:00, 34.4MB/s]
data/train_sft-00000-of-00003-a3ecf92756(…): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 244M/244M [00:06<00:00, 40.3MB/s]
data/train_sft-00001-of-00003-0a1804bcb6(…): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 244M/244M [00:07<00:00, 33.4MB/s]
data/train_sft-00002-of-00003-ee46ed25cf(…): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 244M/244M [00:06<00:00, 39.8MB/s]
data/test_sft-00000-of-00001-f7dfac4afe5(…): 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 81.2M/81.2M [00:02<00:00, 37.2MB/s]
data/train_gen-00000-of-00003-a6c9fb894b(…): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 244M/244M [00:04<00:00, 51.3MB/s]
data/train_gen-00001-of-00003-d6a0402e41(…): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 243M/243M [00:04<00:00, 52.4MB/s]
data/train_gen-00002-of-00003-c0db75b92a(…): 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 243M/243M [00:04<00:00, 52.0MB/s]
data/test_gen-00000-of-00001-3d4cd830914(…): 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80.4M/80.4M [00:02<00:00, 37.0MB/s]
Generating train_sft split: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 207865/207865 [00:03<00:00, 53111.06 examples/s]
Generating test_sft split: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 23110/23110 [00:00<00:00, 56786.44 examples/s]
Generating train_gen split: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 256032/256032 [00:03<00:00, 69294.90 examples/s]
Generating test_gen split: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28304/28304 [00:00<00:00, 69388.24 examples/s]
Map: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:00<00:00, 9604.13 examples/s]
Map:  34%|█████████████████████████████████████████████████████████████████████▍                                                                                                                                    | 176/512 [00:00<00:00, 868.67 examples/s]Map: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 512/512 [00:00<00:00, 797.70 examples/s]
/scripts/quantize.rb:46: DeprecationWarning: `from llmcompressor.transformers import oneshot` is deprecated, please use `from llmcompressor import oneshot`.
  oneshot(
2025-07-17T00:07:16.476912-0700 | reset | INFO - Compression lifecycle reset
2025-07-17T00:07:16.478344-0700 | from_modifiers | INFO - Creating recipe from modifiers
2025-07-17T00:07:16.492020-0700 | _infer_mappings_from_model | INFO - No SmoothQuantModifier.mappings provided, inferring from model...
Traceback (most recent call last):
  File "/scripts/quantize.rb", line 46, in <module>
    oneshot(
  File "/scripts/venv/lib/python3.12/site-packages/compressed_tensors/utils/helpers.py", line 193, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/scripts/venv/lib/python3.12/site-packages/llmcompressor/transformers/finetune/text_generation.py", line 33, in oneshot
    oneshot(**kwargs)
  File "/scripts/venv/lib/python3.12/site-packages/llmcompressor/entrypoints/oneshot.py", line 311, in oneshot
    one_shot()
  File "/scripts/venv/lib/python3.12/site-packages/llmcompressor/entrypoints/oneshot.py", line 149, in __call__
    self.apply_recipe_modifiers(
  File "/scripts/venv/lib/python3.12/site-packages/llmcompressor/entrypoints/oneshot.py", line 181, in apply_recipe_modifiers
    session.initialize(
  File "/scripts/venv/lib/python3.12/site-packages/llmcompressor/core/session.py", line 118, in initialize
    mod_data = self._lifecycle.initialize(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scripts/venv/lib/python3.12/site-packages/llmcompressor/core/lifecycle.py", line 102, in initialize
    data = mod.initialize(state=self.state, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scripts/venv/lib/python3.12/site-packages/llmcompressor/modifiers/stage.py", line 67, in initialize
    modifier.initialize(state, **kwargs)
  File "/scripts/venv/lib/python3.12/site-packages/llmcompressor/modifiers/modifier.py", line 76, in initialize
    self.initialized_ = self.on_initialize(state=state, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scripts/venv/lib/python3.12/site-packages/llmcompressor/modifiers/quantization/gptq/base.py", line 169, in on_initialize
    QuantizationMixin.initialize_quantization(self, state.model)
  File "/scripts/venv/lib/python3.12/site-packages/llmcompressor/modifiers/quantization/quantization/mixin.py", line 128, in initialize_quantization
    apply_quantization_config(model, config)
  File "/scripts/venv/lib/python3.12/site-packages/compressed_tensors/quantization/lifecycle/apply.py", line 199, in apply_quantization_config
    apply_quantization_status(model, config.quantization_status)
  File "/scripts/venv/lib/python3.12/site-packages/compressed_tensors/quantization/lifecycle/apply.py", line 261, in apply_quantization_status
    model.apply(
  File "/scripts/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1044, in apply
    module.apply(fn)
  File "/scripts/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1044, in apply
    module.apply(fn)
  File "/scripts/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1044, in apply
    module.apply(fn)
  [Previous line repeated 2 more times]
  File "/scripts/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1045, in apply
    fn(self)
  File "/scripts/venv/lib/python3.12/site-packages/compressed_tensors/quantization/lifecycle/apply.py", line 262, in <lambda>
    lambda module: initialize_module_for_quantization(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scripts/venv/lib/python3.12/site-packages/compressed_tensors/quantization/lifecycle/initialize.py", line 104, in initialize_module_for_quantization
    _initialize_scale_zero_point(
  File "/scripts/venv/lib/python3.12/site-packages/compressed_tensors/quantization/lifecycle/initialize.py", line 207, in _initialize_scale_zero_point
    torch.zeros(expected_shape, device=device, dtype=zp_dtype),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by zou3519** [comment]
> CUDA error: no kernel image is available for execution on the device

I think we fixed this issue, @sarmiena could you try again and see if it went away?

**Comment by sarmiena** [comment]
@zou3519 on master or v0.10.0?

**Comment by zou3519** [comment]
https://github.com/vllm-project/vllm/pull/20853 this is the PR I am thinking of, it should be included in v0.10.0

**Comment by sarmiena** [comment]
@zou3519 i'm using container vllm/vllm-openai:v0.10.0

```
NVIDIA RTX PRO 6000 Blackwell Workstation Edition with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
/scripts/quantize.py:35: DeprecationWarning: `from llmcompressor.transformers import oneshot` is deprecated, please use `from llmcompressor import oneshot`.
  oneshot(
2025-08-11T14:54:50.297574-0700 | reset | INFO - Compression lifecycle reset
2025-08-11T14:54:50.298581-0700 | from_modifiers | INFO - Creating recipe from modifiers
2025-08-11T14:54:50.310529-0700 | _infer_mappings_from_model | INFO - No SmoothQuantModifier.mappings provided, inferring from model...
Traceback (most recent call last):
  File "/scripts/quantize.py", line 35, in <module>
    oneshot(
  File "/vllm-workspace/venv/lib/python3.12/site-packages/compressed_tensors/utils/helpers.py", line 193, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/vllm-workspace/venv/lib/python3.12/site-packages/llmcompressor/transformers/finetune/text_generation.py", line 33, in oneshot
    oneshot(**kwargs)
  File "/vllm-workspace/venv/lib/python3.12/site-packages/llmcompressor/entrypoints/oneshot.py", line 311, in oneshot
    one_shot()
  File "/vllm-workspace/venv/lib/python3.12/site-packages/llmcompressor/entrypoints/oneshot.py", line 149, in __call__
    self.apply_recipe_modifiers(
  File "/vllm-workspace/venv/lib/python3.12/site-packages/llmcompressor/entrypoints/oneshot.py", line 181, in apply_recipe_modifiers
    session.initialize(
  File "/vllm-workspace/venv/lib/python3.12/site-packages/llmcompressor/core/session.py", line 118, in initialize
    mod_data = self._lifecycle.initialize(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vllm-workspace/venv/lib/python3.12/site-packages/llmcompressor/core/lifecycle.py", line 102, in initialize
    data = mod.initialize(state=self.state, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vllm-workspace/venv/lib/python3.12/site-packages/llmcompressor/modifiers/stage.py", line 67, in initialize
    modifier.initialize(state, **kwargs)
  File "/vllm-workspace/venv/lib/python3.12/site-packages/llmcompressor/modifiers/modifier.py", line 76, in initialize
    self.initialized_ = self.on_initialize(state=state, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vllm-workspace/venv/lib/python3.12/site-packages/llmcompressor/modifiers/quantization/gptq/base.py", line 169, in on_initialize
    QuantizationMixin.initialize_quantization(self, state.model)
  File "/vllm-workspace/venv/lib/python3.12/site-packages/llmcompressor/modifiers/quantization/quantization/mixin.py", line 128, in initialize_quantization
    apply_quantization_config(model, config)
  File "/vllm-workspace/venv/lib/python3.12/site-packages/compressed_tensors/quantization/lifecycle/apply.py", line 199, in apply_quantization_config
    apply_quantization_status(model, config.quantization_status)
  File "/vllm-workspace/venv/lib/python3.12/site-packages/compressed_tensors/quantization/lifecycle/apply.py", line 261, in apply_quantization_status
    model.apply(
  File "/vllm-workspace/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1044, in apply
    module.apply(fn)
  File "/vllm-workspace/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1044, in apply
    module.apply(fn)
  File "/vllm-workspace/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1044, in apply
    module.apply(fn)
  [Previous line repeated 2 more times]
  File "/vllm-workspace/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1045, in apply
    fn(self)
  File "/vllm-workspace/venv/lib/python3.12/site-packages/compressed_tensors/quantization/lifecycle/apply.py", line 262, in <lambda>
    lambda module: initialize_module_for_quantization(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vllm-workspace/venv/lib/python3.12/site-packages/compressed_tensors/quantization/lifecycle/initialize.py", line 104, in initialize_module_for_quantization
    _initialize_scale_zero_point(
  File "/vllm-workspace/venv/lib/python3.12/site-packages/compressed_tensors/quantization/lifecycle/initialize.py", line 207, in _initialize_scale_zero_point
    torch.zeros(expected_shape, device=device, dtype=zp_dtype),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

```

This is the script I used once I got into the container:

```
from transformers import AutoTokenizer, AutoModelForCausalLM
from llmcompressor.transformers import oneshot
from llmcompressor.modifiers.quantization import GPTQModifier
from llmcompressor.modifiers.smoothquant import SmoothQuantModifier
from datasets import load_dataset

MODEL_ID = "meta-llama/Meta-Llama-3-8B-Instruct"
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID, device_map="auto", torch_dtype="auto",
)
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

NUM_CALIBRATION_SAMPLES = 512
MAX_SEQUENCE_LENGTH = 2048

# Load and preprocess the dataset
ds = load_dataset("HuggingFaceH4/ultrachat_200k", split="train_sft")
ds = ds.shuffle(seed=42).select(range(NUM_CALIBRATION_SAMPLES))

def preprocess(example):
    return {"text": tokenizer.apply_chat_template(example["messages"], tokenize=False)}
ds = ds.map(preprocess)

def tokenize(sample):
    return tokenizer(sample["text"], padding=False, max_length=MAX_SEQUENCE_LENGTH, truncation=True, add_special_tokens=False)
ds = ds.map(tokenize, remove_columns=ds.column_names)

# Configure the quantization algorithms
recipe = [
    SmoothQuantModifier(smoothing_strength=0.8),
    GPTQModifier(targets="Linear", scheme="W8A8", ignore=["lm_head"]),
]

# Apply quantization
oneshot(
    model=model,
    dataset=ds,
    recipe=recipe,
    max_seq_length=MAX_SEQUENCE_LENGTH,
    num_calibration_samples=NUM_CALIBRATION_SAMPLES,
)

# Save the compressed model: Meta-Llama-3-8B-Instruct-W8A8-Dynamic-Per-Token
SAVE_DIR = MODEL_ID.split("/")[1] + "-W8A8-Dynamic-Per-Token"
model.save_pretrained(SAVE_DIR, save_compressed=True)
tokenizer.save_pretrained(SAVE_DIR)
```
