### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory

### ISSUE THREAD

**Issue by DenisStefanAndrei** [vllm-project/vllm#2140]
I am running this code example from hugging face's TheBloke/zephyr-7B-beta-AWQ 

```
from vllm import LLM, SamplingParams
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:512"
prompts = [
    "Tell me about AI",
   # "Write a story about llamas",
   # "What is 291 - 150?",
   # "How much wood would a woodchuck chuck if a woodchuck could chuck wood?",
]
prompt_template=f'''<|system|>
</s>
<|user|>
{prompts}</s>
<|assistant|>
'''

prompts = [prompt_template.format(prompt=prompt) for prompt in prompts]

sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

llm = LLM(model="TheBloke/zephyr-7B-beta-AWQ", quantization="awq", dtype="auto", gpu_memory_utilization=0.5)

outputs = llm.generate(prompts, sampling_params)

# Print the outputs.
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```

Unfortunately I get this error 

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 GiB. GPU 0 has a total capacty of 14.58 GiB of which 9.93 GiB is free. Including non-PyTorch memory, this process has 4.64 GiB memory in use. Of the allocated memory 4.38 GiB is allocated by PyTorch, and 755.50 KiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I am using a **Nvidia T4 - 16Gb memory** 
This the output from nvidia-smi before running the script
![image](https://github.com/vllm-project/vllm/assets/93513013/558073e1-5b32-4fda-8c41-ea4b6bb0585d)

and this is the output from nvitop command
![image](https://github.com/vllm-project/vllm/assets/93513013/ea18c038-f8c0-4a01-b2eb-be926a038dc0)

I understand the process allocates 4.64 GB for the process. Why do I receive out of memory error? 

Thank you anticipated for any help!

**Comment by esmeetu** [comment]
Is it not because you set 'gpu_memory_utilization' to 0.5?
Increase it.

**Comment by DenisStefanAndrei** [comment]
Same error without 'gpu_memory_utilization'

**Comment by esmeetu** [comment]
> Same error without 'gpu_memory_utilization'

why setting this in your code:
```
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:512"
```
Could you try commenting out this?

**Comment by DenisStefanAndrei** [comment]
It is to avoid memory fragmentation comming from torch, if I comment it I will have more unallocated space coming from torch. Same error

**Comment by WoosukKwon** [comment]
> Tried to allocate 14.00 GiB.

This part of the warning message is very weird. We shouldn't allocate that big tensor for that GPU.

@DenisStefanAndrei Which version of vLLM are you using?

**Comment by DenisStefanAndrei** [comment]
I use version 0.2.5

**Comment by lasseedfast** [comment]
Running the same code and vllm version 0.2.5 I get a similar error:
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.50 GiB. GPU 0 has a total capacty of 23.69 GiB of which 3.09 GiB is free. Including non-PyTorch memory, this process has 20.57 GiB memory in use. Of the allocated memory 20.13 GiB is allocated by PyTorch, and 755.50 KiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

Running nvidia-smi just before:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:01:00.0 Off |                  N/A |
| 30%   29C    P8              24W / 350W |     28MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090        Off | 00000000:04:00.0 Off |                  N/A |
| 30%   26C    P8              20W / 350W |     12MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA GeForce RTX 3090        Off | 00000000:05:00.0 Off |                  N/A |
| 30%   24C    P8              17W / 350W |     12MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A       737      G   /usr/lib/xorg/Xorg                            9MiB |
|    0   N/A  N/A       885      G   /usr/bin/gnome-shell                          8MiB |
|    1   N/A  N/A       737      G   /usr/lib/xorg/Xorg                            4MiB |
|    2   N/A  N/A       737      G   /usr/lib/xorg/Xorg                            4MiB |
+---------------------------------------------------------------------------------------+
```

Seems like something is happening that takes up 20+ memory on the GPU (RTX 3090) but I don't know how to check that in real time.   
When I set `tensor_parallel_size=2` it works but I get this warning:
```
WARNING 12-17 10:21:30 config.py:308] Possibly too large swap space. 8.00 GiB out of the 15.51 GiB total CPU memory is allocated for the swap space.
INFO 12-17 10:23:05 llm_engine.py:222] # GPU blocks: 2937, # CPU blocks: 4096
``

**Comment by dachengai** [comment]
A100 80G  set gpu_memory_utilization=0.5    run llm error like: 

2023-12-18 05:06:01 | INFO | stdout | vllm engine args: AsyncEngineArgs(model='/app/models/Baichuan2-13B-Chat', tokenizer='/app/models/Baichuan2-13B-Chat', tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='half', seed=0, max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, block_size=16, swap_space=4, gpu_memory_utilization=0.5, max_num_batched_tokens=None, max_num_seqs=32, max_paddings=256, disable_log_stats=False, revision=None, tokenizer_revision=None, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
WARNING 12-18 05:06:01 config.py:467] Casting torch.bfloat16 to torch.float16.
INFO 12-18 05:06:01 llm_engine.py:73] Initializing an LLM engine with config: model='/app/models/Baichuan2-13B-Chat', tokenizer='/app/models/Baichuan2-13B-Chat', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, enforce_eager=False, seed=0)
WARNING 12-18 05:06:02 tokenizer.py:62] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 12-18 05:06:35 llm_engine.py:223] # GPU blocks: 0, # CPU blocks: 327
2023-12-18 05:06:35 | ERROR | stderr | Traceback (most recent call last):
2023-12-18 05:06:35 | ERROR | stderr |   File "orionchat/serve/vllm_worker.py", line 279, in <module>
2023-12-18 05:06:35 | ERROR | stderr |     engine = AsyncLLMEngine.from_engine_args(engine_args)
2023-12-18 05:06:35 | ERROR | stderr |   File "/app/vllm/vllm/engine/async_llm_engine.py", line 496, in from_engine_args
2023-12-18 05:06:35 | ERROR | stderr |     engine = cls(parallel_config.worker_use_ray,
2023-12-18 05:06:35 | ERROR | stderr |   File "/app/vllm/vllm/engine/async_llm_engine.py", line 269, in __init__
2023-12-18 05:06:35 | ERROR | stderr |     self.engine = self._init_engine(*args, **kwargs)
2023-12-18 05:06:35 | ERROR | stderr |   File "/app/vllm/vllm/engine/async_llm_engine.py", line 314, in _init_engine
2023-12-18 05:06:35 | ERROR | stderr |     return engine_class(*args, **kwargs)
2023-12-18 05:06:35 | ERROR | stderr |   File "/app/vllm/vllm/engine/llm_engine.py", line 113, in __init__
2023-12-18 05:06:35 | ERROR | stderr |     self._init_cache()
2023-12-18 05:06:35 | ERROR | stderr |   File "/app/vllm/vllm/engine/llm_engine.py", line 227, in _init_cache
2023-12-18 05:06:35 | ERROR | stderr |     raise ValueError("No available memory for the cache blocks. "
2023-12-18 05:06:35 | ERROR | stderr | ValueError: No available memory for the cache blocks. Try increasing `gpu_memory_utilization` when initializing the engine.

**Comment by DenisStefanAndrei** [comment]
Any more ideas on how to solve this, please? I am stuck and I see I am not the only one with this problem

**Comment by esmeetu** [comment]
> Any more ideas on how to solve this, please? I am stuck and I see I am not the only one with this problem

This is indeed a problem for me after my experiment.
And there is workaround which i think might works. For v0.2.6, you had better to add `--enforce-eager` args to save memory. and increase `gpu_memory_utilization` to >0.95. If not working, descreasing model context length by add `--max-model-len 4096`.

**Comment by dachengai** [comment]
Any more ideas on how to solve this, please?

**Comment by dachengai** [comment]
> > Any more ideas on how to solve this, please? I am stuck and I see I am not the only one with this problem
> 
> Hey, @DenisStefanAndrei. This is indeed a problem for me after my experiment. And there is workaround which i think might works. For v0.2.6, you had better to add `--enforce-eager` args to save memory. and increase `gpu_memory_utilization` to >0.95. If not working, descreasing model context length by add `--max-model-len 4096`.

not work

**Comment by dachengai** [comment]
first time run vllm on RTX3090 2G  to  print torch.cuda.mem_get_info(): 

023-12-21 13:14:39 | INFO | stdout | total_gpu_memory: 25438126080  free_gpu_memory: 819003392


free_gpu_memory 819003392 ?????
 

use torch to print directly:  

Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.cuda.mem_get_info())
(25162743808, 25438126080)
>>>

**Comment by mrasputin** [comment]
same here

**Comment by DenisStefanAndrei** [comment]
setting max_model_len to 512 did the job for me.

**Comment by dachengai** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.04 GiB. GPU 0 has a total capacty of 23.69 GiB of which 963.88 MiB is free. Process 16803 has 254.00 MiB memory in use. Process 17811 has 22.48 GiB memory in use. Of the allocated memory 20.95 GiB is allocated by PyTorch, and 1.06 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by PhaneendraGunda** [comment]
> > Any more ideas on how to solve this, please? I am stuck and I see I am not the only one with this problem
> 
> Hey, @DenisStefanAndrei. This is indeed a problem for me after my experiment. And there is workaround which i think might works. For v0.2.6, you had better to add `--enforce-eager` args to save memory. and increase `gpu_memory_utilization` to >0.95. If not working, descreasing model context length by add `--max-model-len 4096`.

it's working for me with the  `--enforce-eager` arg

**Comment by lx1229** [comment]
> > > Any more ideas on how to solve this, please? I am stuck and I see I am not the only one with this problem
> > 
> > 
> > Hey, @DenisStefanAndrei. This is indeed a problem for me after my experiment. And there is workaround which i think might works. For v0.2.6, you had better to add `--enforce-eager` args to save memory. and increase `gpu_memory_utilization` to >0.95. If not working, descreasing model context length by add `--max-model-len 4096`.
> 
> it's working for me with the `--enforce-eager` arg

This works for my situation! That is amazing!

**Comment by robocanic** [comment]
I got the same problem. I used 2080Ti which has 22GB memory for run vllm as a server for qwen2-7b-instruct: `python -m vllm.entrypoints.openai.api_server --model /home/jovyan/qwen/Qwen2-7B-Instruct  --served-model-name Qwen2-7B-Instruct --max-model-len=512 --dtype=float --enforce-eager`, and I had tried to adjust the `--max-model-len` , `--enforce-eager` or `gpu_memory_utilization `, but didn't work. The error is like below:
![image](https://github.com/vllm-project/vllm/assets/79916872/6b6979d5-dcb0-448e-af46-994fc9aed150)
errors: 
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 518.00 MiB. GPU 0 has a total capacty of 21.67 GiB of which 4.06 MiB is free. Process 2417585 has 21.65 GiB memory in use. Of the allocated memory 21.32 GiB is allocated by PyTorch, and 1018.00 KiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

versions: vllm==0.4.0.post1(also tried 0.4.3 0.5.0), pytorch==2.1.2, transformers==4.39.3
I think 22GB is enough  for the model of 7B-size, but I have no idea ，what has gone wrong？Can anybody help me with this？

**Comment by mars-ch** [comment]
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.04 GiB. GPU 0 has a total capacty of 23.69 GiB of which 963.88 MiB is free. Process 16803 has 254.00 MiB memory in use. Process 17811 has 22.48 GiB memory in use. Of the allocated memory 20.95 GiB is allocated by PyTorch, and 1.06 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Hi, I wonder how you fix this problem?

**Comment by robocanic** [comment]
> > torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.04 GiB. GPU 0 has a total capacty of 23.69 GiB of which 963.88 MiB is free. Process 16803 has 254.00 MiB memory in use. Process 17811 has 22.48 GiB memory in use. Of the allocated memory 20.95 GiB is allocated by PyTorch, and 1.06 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 
> Hi, I wonder how you fix this problem?
Currently unresolved🙃

**Comment by robocanic** [comment]
I tried fastapi + transformers to do the similar thing and it works fine. The memory usage is about 15G/22G as below:

![image](https://github.com/vllm-project/vllm/assets/79916872/ee6f494d-1ab4-48ee-9b46-eae924a48a71)
So I think there are indeed some problems with my current usage with vllm

**Comment by adolfo-ab** [comment]
I have the same problem. Trying to run a sample code locally:
`import torch
from vllm import LLM

prompts = ["Hello, my name is", "The capital of France is"]
llm = LLM(model="Mistral-7B-v0.1", gpu_memory_utilization=1, enforce_eager=True, max_seq_len_to_capture=512)
outputs = llm.generate(prompts)

print(outputs)
`

And I got this error:

`INFO 06-15 12:17:55 llm_engine.py:161] Initializing an LLM engine (v0.5.0.post1) with config: model='Mistral-7B-v0.1', speculative_config=None, tokenizer='Mistral-7B-v0.1', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=Mistral-7B-v0.1)
INFO 06-15 12:17:55 selector.py:150] Cannot use FlashAttention-2 backend due to sliding window.
INFO 06-15 12:17:55 selector.py:51] Using XFormers backend.
INFO 06-15 12:17:56 selector.py:150] Cannot use FlashAttention-2 backend due to sliding window.
INFO 06-15 12:17:56 selector.py:51] Using XFormers backend.
INFO 06-15 12:17:57 model_runner.py:160] Loading model weights took 13.4966 GB
[rank0]: Traceback (most recent call last):
[rank0]:   File "...", line 7, in <module>
[rank0]:     llm = LLM(model="Mistral-7B-v0.1", device=device, gpu_memory_utilization=0.6)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/.../.conda/envs/poc-llm/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 144, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 363, in from_engine_args
[rank0]:     engine = cls(
[rank0]:              ^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 236, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/vllm/engine/llm_engine.py", line 313, in _initialize_kv_caches
[rank0]:     self.model_executor.determine_num_available_blocks())
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/vllm/executor/gpu_executor.py", line 75, in determine_num_available_blocks
[rank0]:     return self.driver_worker.determine_num_available_blocks()
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/vllm/worker/worker.py", line 162, in determine_num_available_blocks
[rank0]:     self.model_runner.profile_run()
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 844, in profile_run
[rank0]:     self.execute_model(seqs, kv_caches)
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 749, in execute_model
[rank0]:     hidden_states = model_executable(
[rank0]:                     ^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 371, in forward
[rank0]:     hidden_states = self.model(input_ids, positions, kv_caches,
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 288, in forward
[rank0]:     hidden_states, residual = layer(
[rank0]:                               ^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 227, in forward
[rank0]:     hidden_states = self.self_attn(
[rank0]:                     ^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 161, in forward
[rank0]:     attn_output = self.attn(q, k, v, kv_cache, attn_metadata)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/vllm/attention/layer.py", line 89, in forward
[rank0]:     return self.impl.forward(query, key, value, kv_cache, attn_metadata,
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/user/.conda/envs/poc-llm/lib/python3.11/site-packages/vllm/attention/backends/xformers.py", line 279, in forward
[rank0]:     output = torch.empty_like(query)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB. GPU 

Process finished with exit code 1`

Although I can run the same model locally using ollama with no problem. When running the code I see no increase in GPU usage with nvidia-smi, and using torch I verified that my code could see my GPU --when creating a simple tensor I see an increase in GPU usage, but not when trying to use vLLM.

**Comment by Qubitium** [comment]
@adolfo-ab Please increase memory config to `0.9` (this is percentage of memory allocated to vllm). Righ tnow you have `0.6` or 60% which is not enough for the model and kv cache. If it works with 0.9 or 0.95, gradually tweak down the value until you find the sweet spot.

```
llm = LLM(model="Mistral-7B-v0.1", device=device, gpu_memory_utilization=0.6)
```

**Comment by adolfo-ab** [comment]
@Qubitium Thanks for your answer. I tried values between 1 and 0.5 and got the same error. It's weird because I can run the same model (and bigger ones) with both ollama and the Transformers library with no issue.

**Comment by Qubitium** [comment]
@adolfo-ab This should not happen and stacktrace should be different now. There is now enough vram to bypass your first OOM.  Also vllm is not optimized for desktop but for server usage. As such, vllm will maximize memory usage to maximize batch and throughput. Think of it this way, ollama and transformer will also oom if memory is optimized for max batching.

**Comment by Jungle0430** [comment]
> @Qubitium Thanks for your answer. I tried values between 1 and 0.5 and got the same error. It's weird because I can run the same model (and bigger ones) with both ollama and the Transformers library with no issue.

You can try setting gpu_memory_utilization to less than 0.5. For my situation, gpu_memory_utilization=0.4 and max_model_len=1024 worked well. Just adjust these two parameters manually!

**Comment by kamillle** [comment]
https://github.com/vllm-project/vllm/issues/2140#issuecomment-2165168290
Same.
I used NVIDIA L4 which has 23GB memory running vllm as a server for qwen2-7b-instruct. qwen2-7b as well :(

**Comment by 1suancaiyu** [comment]
> I got the same problem. I used 2080Ti which has 22GB memory running vllm as a server for qwen2-7b-instruct: `python -m vllm.entrypoints.openai.api_server --model /home/jovyan/qwen/Qwen2-7B-Instruct --served-model-name Qwen2-7B-Instruct --max-model-len=512 --dtype=float --enforce-eager`, and I had tried to adjust the `--max-model-len` , `--enforce-eager` or `gpu_memory_utilization `, but didn't work. The error is like below: ![image](https://private-user-images.githubusercontent.com/79916872/339309781-6b6979d5-dcb0-448e-af46-994fc9aed150.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MTM4NzcsIm5iZiI6MTcyMDUxMzU3NywicGF0aCI6Ii83OTkxNjg3Mi8zMzkzMDk3ODEtNmI2OTc5ZDUtZGNiMC00NDhlLWFmNDYtOTk0ZmM5YWVkMTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA4MjYxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MjRkMTcxYzY2NTA4NzE5YWE4YTlmOGUwYzkzMzRjZjZkYzI0ZTJkNWU1OGMxMTUxZmY1OGJmMjE2ODI1OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GDmR6lfw1INR17MM71TrXLOMyWHpjgnIcqR9PHmm04Y) errors:
> 
> > torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 518.00 MiB. GPU 0 has a total capacty of 21.67 GiB of which 4.06 MiB is free. Process 2417585 has 21.65 GiB memory in use. Of the allocated memory 21.32 GiB is allocated by PyTorch, and 1018.00 KiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> 
> versions: vllm==0.4.0.post1(also tried 0.4.3 0.5.0), pytorch==2.1.2, transformers==4.39.3，python==3.10.7, cuda 12.1 I think 22GB is enough for the model of 7B-size, but I have no idea ，what has gone wrong？Can anybody help me with this？

Have you resolved now ? I meat the same error.

**Comment by youkaichao** [comment]
The original post uses `--dtype=float` , each number takes 4 bytes, so 7B model will use 28GM memory.

**Comment by robocanic** [comment]
> The original post uses `--dtype=float` , each number takes 4 bytes, so 7B model will use 28GM memory.

I've also tried RTX3090  which has 24GB of memory to do inference for 7B-size model using vLLM, it worked fine and the memory usage is about 15GB. So I think the memory is not the key problem.

**Comment by 1suancaiyu** [comment]
python -m vllm.entrypoints.openai.api_server --model ./Qwen2-7B-Instruct-GPTQ-Int4/ --served-model-name Qwen2-7B-Instruct-Int4 --gpu-memory-utilization=0.38 --port 3020

My GPU: A800, CUDA 11.8, Qwen2-7B-Instruct-GPTQ-Int4, VLLM_VERSION=0.4.0

That's my command, I add --gpu-memory-utilization to solve this error.

**Comment by TRONBFFL** [comment]
If I use  vllm 0.2.1.post1   I do not get the error. But if I use anything else I do. Using on an A10

**Comment by wiluen** [comment]
decrease the --gpu-memory-utilization . if it is 0.5, the memory will be 40G*0.5=20G, that is ok.

**Comment by TRONBFFL** [comment]
I have vllm==0.5.3.post1 running consistently with a 7B model on an A10 GPU. 

these are my args

self.model_args = AsyncEngineArgs(
            model=model_metadata["repo_id"],
            trust_remote_code=True,
            tensor_parallel_size=model_metadata["tensor_parallel"],
            dtype="auto",
            enforce_eager=True,
            gpu_memory_utilization=1,
            tokenizer_mode="auto",
