### ISSUE TITLE
[Bug]: Tensor parallelism on sm_120 (rtx 5090) is broken on latest docker (0.9.2)?

### ISSUE THREAD

**Issue by andrenatal** [vllm-project/vllm#21491]
### Your current environment

docker run -d --runtime nvidia --gpus all  -v ~/.cache/huggingface:/root/.cache/huggingface     --env "HUGGING_FACE_HUB_TOKEN=xxxx"     -p 8002:8000     --ipc=host     vllm/vllm-openai:latest --model openai/whisper-large-v3  --gpu_memory_utilization 0.90 --tensor-parallel-size 2

### 🐛 Describe the bug

Apparently, when I start a container with tensor-parallelism (2) using the aforementioned combination, the server gets stuck on some call related to nccl. My log below is using whisper, but also tried with llms to no avail. I can load a model individually on each gpu without tensor-paralellism, though.

```
INFO 07-23 19:51:14 [__init__.py:244] Automatically detected platform cuda.
INFO 07-23 19:51:18 [api_server.py:1395] vLLM API server version 0.9.2
INFO 07-23 19:51:18 [cli_args.py:325] non-default args: {'model': 'openai/whisper-large-v3', 'tensor_parallel_size': 2}
INFO 07-23 19:51:25 [config.py:841] This model supports multiple tasks: {'embed', 'reward', 'classify', 'transcription', 'generate'}. Defaulting to 'transcription'.
INFO 07-23 19:51:25 [config.py:1472] Using max model len 448
WARNING 07-23 19:51:25 [arg_utils.py:1735] ['WhisperForConditionalGeneration'] is not supported by the V1 Engine. Falling back to V0.
INFO 07-23 19:51:26 [api_server.py:268] Started engine process with PID 92
INFO 07-23 19:51:30 [__init__.py:244] Automatically detected platform cuda.
INFO 07-23 19:51:32 [llm_engine.py:230] Initializing a V0 LLM engine (v0.9.2) with config: model='openai/whisper-large-v3', speculative_config=None, tokenizer='openai/whisper-large-v3', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=448, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=openai/whisper-large-v3, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":[],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":256,"local_cache_dir":null}, use_cached_outputs=True,
WARNING 07-23 19:51:32 [multiproc_worker_utils.py:307] Reducing Torch parallelism from 10 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 07-23 19:51:33 [cuda.py:363] Using Flash Attention backend.
INFO 07-23 19:51:36 [__init__.py:244] Automatically detected platform cuda.
(VllmWorkerProcess pid=137) INFO 07-23 19:51:38 [multiproc_worker_utils.py:226] Worker ready; awaiting tasks
(VllmWorkerProcess pid=137) INFO 07-23 19:51:38 [cuda.py:363] Using Flash Attention backend.
(VllmWorkerProcess pid=137) INFO 07-23 19:51:39 [__init__.py:1152] Found nccl from library libnccl.so.2
INFO 07-23 19:51:39 [__init__.py:1152] Found nccl from library libnccl.so.2
INFO 07-23 19:51:39 [pynccl.py:70] vLLM is using nccl==2.26.2
(VllmWorkerProcess pid=137) INFO 07-23 19:51:39 [pynccl.py:70] vLLM is using nccl==2.26.2
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by RagnarokChan** [comment]
Updating NCCL to the 2.27 version series will resolve the issue.

**Comment by andrenatal** [comment]
In the host? I did it already, and it didn't work.

**Comment by RagnarokChan** [comment]
After building vLLM in a conda virtual environment , I resolved the TP=2 issue by updating NCCL to version 2.27.5/2.27.6 using pip install. Additionally, for Docker images I built, I also updated the NCCL version via pip install in the Dockerfile. You can verify the NCCL version in the vLLM startup logs . My setup uses two RTX5090D GPUs .

**Comment by andrenatal** [comment]
I tried this. I added `nvidia-nccl-cu12==2.27.6` to an already working Dockerfile, which is represented below:

```
FROM vllm/vllm-openai:v0.9.2

# e.g. install the `audio` optional dependencies
# NOTE: Make sure the version of vLLM matches the base image!
RUN uv pip install --system vllm[audio]==0.9.2 transformers==4.52.4 nvidia-nccl-cu12==2.27.6
```

but that, yields me the following conflicts:

```
[+] Building 1.6s (5/5) FINISHED                                                                                                                                                                                                                                                   docker:rootless
 => [internal] load build definition from Dockerfile.audio                                                                                                                                                                                                                                    0.0s
 => => transferring dockerfile: 279B                                                                                                                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/vllm/vllm-openai:v0.9.2                                                                                                                                                                                                                            0.3s
 => [internal] load .dockerignore                                                                                                                                                                                                                                                             0.0s
 => => transferring context: 387B                                                                                                                                                                                                                                                             0.0s
 => CACHED [1/2] FROM docker.io/vllm/vllm-openai:v0.9.2@sha256:37cd5bd18d220a0f4c70401ce1d4a0cc588fbfe03cc210579428f2c47e6eac33                                                                                                                                                               0.0s
 => ERROR [2/2] RUN uv pip install --system vllm[audio]==0.9.2 transformers==4.52.4 nvidia-nccl-cu12==2.27.6                                                                                                                                                                                  1.0s
------
 > [2/2] RUN uv pip install --system vllm[audio]==0.9.2 transformers==4.52.4 nvidia-nccl-cu12==2.27.6:
0.271 Using Python 3.12.11 environment at: /usr
0.766   × No solution found when resolving dependencies:
0.766   ╰─▶ Because torch==2.7.0 depends on nvidia-nccl-cu12{platform_machine ==
0.766       'x86_64' and sys_platform == 'linux'}==2.26.2 and only the following
0.766       versions of torch are available:
0.766           torch<=2.7.0
0.766           torch>2.7.0+cu128
0.766       we can conclude that torch==2.7.0 depends on nvidia-nccl-cu12==2.26.2.
0.766       And because vllm==0.9.2 depends on torch==2.7.0, we can conclude that
0.766       vllm==0.9.2 depends on nvidia-nccl-cu12==2.26.2.
0.766       And because you require vllm[audio]==0.9.2 and nvidia-nccl-cu12==2.27.6,
0.766       we can conclude that your requirements are unsatisfiable.
------
Dockerfile.audio:5
--------------------
   3 |     # e.g. install the `audio` optional dependencies
   4 |     # NOTE: Make sure the version of vLLM matches the base image!
   5 | >>> RUN uv pip install --system vllm[audio]==0.9.2 transformers==4.52.4 nvidia-nccl-cu12==2.27.6
   6 |
--------------------
ERROR: failed to solve: process "/bin/bash -c uv pip install --system vllm[audio]==0.9.2 transformers==4.52.4 nvidia-nccl-cu12==2.27.6" did not complete successfully: exit code: 1
```

Was `nvidia-nccl-cu12==2.27.6` the package you installed?

**Comment by RagnarokChan** [comment]
Yes, but I had Cursor assist with the Docker portion. After upgrading via conda build, it no longer gets stuck at NCCL 2.26. You also need to add - SHM_SIZE=32G to the configuration; otherwise, it will throw an error.

**Comment by SecurityNeo** [comment]
just upgrade nccl to 2.27.6: `pip install nvidia-nccl-cu12==2.27.6`,it works for me
