### ISSUE TITLE
[Bug]: CUDA error: invalid device ordinal when using tensor parallel + data parallel with data-parallel-backend ray

### ISSUE THREAD

**Issue by luhansh** [vllm-project/vllm#22677]
### Your current environment

vLLM v0.10.0

### 🐛 Describe the bug

I am using [data parallel](https://docs.vllm.ai/en/latest/serving/data_parallel_deployment.html) and ray as backend.
Command
```
vllm serve $MODEL --tensor-parallel-size 1 --data-parallel-size 4 --data-parallel-size-local 1 \
                  --data-parallel-backend=ray
```
works well for me, so that I can run a 4 DP workers server using 4 nodes(each worker uses 1 GPU on its corresponding node)

But when I run the below command to leverage 4 GPUs for each worker
```
vllm serve $MODEL --tensor-parallel-size 4 --data-parallel-size 4 --data-parallel-size-local 1 \
                  --data-parallel-backend=ray
```
I got 
```
(DPEngineCoreActor pid=3551736) Exception raised in creation task: The actor died because of an error raised in its creation task, ray::DPEngineCoreActor.init() (pid=3551736, ip=10.0.2.109, actor_id=7b9995853ad2be757c1825e501000000, repr=<vllm.v1.engine.core.DPEngineCoreActor object at 0x7f916f5331a0>)
(DPEngineCoreActor pid=3551736)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(DPEngineCoreActor pid=3551736)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 1089, in init
(DPEngineCoreActor pid=3551736)     super().init(vllm_config, local_client, "", executor_class,
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 881, in init
(DPEngineCoreActor pid=3551736)     super().init(vllm_config, local_client, handshake_address,
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 441, in init
(DPEngineCoreActor pid=3551736)     super().init(vllm_config, executor_class, log_stats,
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 77, in init
(DPEngineCoreActor pid=3551736)     self.model_executor = executor_class(vllm_config)
(DPEngineCoreActor pid=3551736)                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 263, in init
(DPEngineCoreActor pid=3551736)     super().init(*args, **kwargs)
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/executor/executor_base.py", line 53, in init
(DPEngineCoreActor pid=3551736)     self._init_executor()
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/v1/executor/ray_distributed_executor.py", line 47, in _init_executor
(DPEngineCoreActor pid=3551736)     super()._init_executor()
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/executor/ray_distributed_executor.py", line 107, in _init_executor
(DPEngineCoreActor pid=3551736)     self._init_workers_ray(placement_group)
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/executor/ray_distributed_executor.py", line 377, in _init_workers_ray
(DPEngineCoreActor pid=3551736)     self._run_workers("init_device")
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/executor/ray_distributed_executor.py", line 503, in _run_workers
(DPEngineCoreActor pid=3551736)     ray_worker_outputs = ray.get(ray_worker_outputs)
(DPEngineCoreActor pid=3551736)                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(DPEngineCoreActor pid=3551736)            ^^^^^^^^^^^^^^^^^^^
(DPEngineCoreActor pid=3551736)            ^^^^^^^^^^^^^^^^^^^^^
(DPEngineCoreActor pid=3551736)                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(DPEngineCoreActor pid=3551736) ray.exceptions.RayTaskError(RuntimeError): ray::RayWorkerWrapper.execute_method() (pid=3552728, ip=10.0.2.109, actor_id=6c7ffac2a3a175ebca647ff201000000, repr=<vllm.executor.ray_utils.RayWorkerWrapper object at 0x7fce6b50e120>)
(DPEngineCoreActor pid=3551736)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(DPEngineCoreActor pid=3551736)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 620, in execute_method
(DPEngineCoreActor pid=3551736)     raise e
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 611, in execute_method
(DPEngineCoreActor pid=3551736)     return run_method(self, method, args, kwargs)
(DPEngineCoreActor pid=3551736)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/utils/init.py", line 2985, in run_method
(DPEngineCoreActor pid=3551736)     return func(*args, **kwargs)
(DPEngineCoreActor pid=3551736)            ^^^^^^^^^^^^^^^^^^^^^
(DPEngineCoreActor pid=3551736)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/worker/worker_base.py", line 603, in init_device
(DPEngineCoreActor pid=3551736)     self.worker.init_device()  # type: ignore
(DPEngineCoreActor pid=3551736)     ^^^^^^^^^^^^^^^^^^^^^^^^^
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 156, in init_device
(DPEngineCoreActor pid=3551736)     current_platform.set_device(self.device)
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/vllm/platforms/cuda.py", line 80, in set_device
(DPEngineCoreActor pid=3551736)     torch.cuda.set_device(device)
(DPEngineCoreActor pid=3551736)   File "/workplace/luhansh/AGIModelLens-new/src/AGIModelLens/.venv/lib/python3.12/site-packages/torch/cuda/init.py", line 530, in set_device
(DPEngineCoreActor pid=3551736)     torch._C._cuda_setDevice(device)
(DPEngineCoreActor pid=3551736) RuntimeError: CUDA error: invalid device ordinal
```

The same error applies to a local run, I can not use more than 1 GPU for each DP worker using ray backend.
Is this a bug or just this functionality is not enabled? 

Besides, I am not sure if multi-nodes for a single DP worker is supported.
How can I leverage the current multi-nodes solution with the DP solution? Or I can only implement external load balancing for multiple multi-nodes vLLM server?
Thanks!

**Comment by luhansh** [comment]
It seems that every bundle only has 1 GPU.

**Comment by luhansh** [comment]
May I ask why the GPU count in each bundle is 1? Should this be the number of tensor parallel size?
https://github.com/vllm-project/vllm/blob/main/vllm/v1/engine/utils.py#L327
cc: @njhill @ruisearch42 

Thank you so much!

**Comment by ruisearch42** [comment]
> Besides, I am not sure if multi-nodes for a single DP worker is supported.

Hi @luhansh , this is not supported right now but we will do in future:
https://github.com/vllm-project/vllm/blob/main/vllm/v1/engine/utils.py#L317

> How can I leverage the current multi-nodes solution with the DP solution? 

Can you say more what exactly you were trying to achieve?

**Comment by ruisearch42** [comment]
> May I ask why the GPU count in each bundle is 1? Should this be the number of tensor parallel size?
> https://github.com/vllm-project/vllm/blob/main/vllm/v1/engine/utils.py#L327

It actually multiplies the world_size (=TP x PP) here: https://github.com/vllm-project/vllm/blob/main/vllm/v1/engine/utils.py#L329

**Comment by ruisearch42** [comment]
I tried the TP>1 on a single node and it worked fine:
```
vllm serve ibm-research/PowerMoE-3b --tensor-parallel-size 2 --data-parallel-size 2 --data-parallel-size-local 2 --data-parallel-backend=ray
```
I will try on multi-node later on. @luhansh In the mean time, could you add more details about your setup? How many GPUs are there on a node for you?

**Comment by luhansh** [comment]
Hi @ruisearch42 , thank you so much for you reply!

I think you are right, I also tried
```
vllm serve ibm-research/PowerMoE-3b --tensor-parallel-size 2 --data-parallel-size 2 --data-parallel-size-local 2 --data-parallel-backend=ray
```
and this works for me.

Seems this issue only happens on our model:

```
vllm serve our_model --tensor-parallel-size 2 --data-parallel-size 2 --data-parallel-size-local 2 --data-parallel-backend ray
```

Got the above `RuntimeError: CUDA error: invalid device ordinal` error
```
vllm serve our_model --tensor-parallel-size 2 --data-parallel-size 2 --data-parallel-size-local 2
```
works well without ray backend

I am running on a g5.12xlarge(4 GPUs). I am looking into this issue.
