### ISSUE TITLE
[Bug]: torch.AcceleratorError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by sleepwalker2017** [vllm-project/vllm#24430]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Collecting environment information...                                                                                                                  
==============================                                                                                                                         
        System Info                                                                                                                                    
==============================                                                                                                                         
OS                           : Ubuntu 22.04.4 LTS (x86_64)
GCC version                  : (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0                                                                                   
Clang version                : Could not collect                                                                                                       
CMake version                : version 3.30.2                                                                                                          
Libc version                 : glibc-2.35              
                                                                                                                                                       
==============================                                             
       PyTorch Info                                                        
==============================                                                                                                                         
PyTorch version              : 2.8.0+cu128                                                                                                             
Is debug build               : False                                                                                                                   
CUDA used to build PyTorch   : 12.8                                                                                                                    
ROCM used to build PyTorch   : N/A                                                                                                                     
                                                                                                                                                       
==============================                                                                                                                         
      Python Environment                                                                                                                               
==============================                                                                                                                         
Python version               : 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] (64-bit runtime)                                                     
Python platform              : Linux-5.4.210.bsk.6-amd64-x86_64-with-glibc2.35                                                                         
                                                                                                                                                       
==============================                                                                                                                         
       CUDA / GPU Info                                                     
==============================                                                                                                                         
Is CUDA available            : True                                        
CUDA runtime version         : Could not collect                                                                                                       
CUDA_MODULE_LOADING set to   : LAZY                                                                                                                    
GPU models and configuration : GPU 0: NVIDIA L20                                                                                                       
Nvidia driver version        : 535.161.08                                                                                                              
cuDNN version                : Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.4.0
HIP runtime version          : N/A                                                                                                                     
MIOpen runtime version       : N/A                                         
Is XNNPACK available         : True 
                                                                           
==============================                                             
          CPU Info                                                         
==============================                                             
Architecture:                    x86_64                                    
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          180                                       
On-line CPU(s) list:             0-179                                     
Vendor ID:                       GenuineIntel                              
Model name:                      Intel(R) Xeon(R) Platinum 8457C           
CPU family:                      6                                         
Model:                           143                                                                                                                   
Thread(s) per core:              2                                                                                                                     
Core(s) per socket:              45                                                                                                                    
Socket(s):                       2                                         
Stepping:                        8
BogoMIPS:                        5200.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdp
e1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadli
ne_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adju
st bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetb
v1 xsaves avx512_bf16 wbnoinvd arat avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpi
d cldemote movdiri movdir64b md_clear arch_capabilities
Hypervisor vendor:               KVM
Virtualization type:             full 
L1d cache:                       4.2 MiB (90 instances)
L1i cache:                       2.8 MiB (90 instances)
L2 cache:                        180 MiB (90 instances)
L3 cache:                        195 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-89 
NUMA node1 CPU(s):               90-179
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected   
Vulnerability Tsx async abort:   Mitigation; TSX disabled
==============================                                             
Versions of relevant libraries      
==============================                                             
[pip3] flashinfer==0.1.6+cu124torch2.4                                     
[pip3] mypy==1.15.0                                                        
[pip3] mypy-extensions==1.0.0                                              
[pip3] numpy==1.26.4                                                       
[pip3] nvidia-cublas-cu12==12.8.4.1                                        
[pip3] nvidia-cuda-cupti-cu12==12.8.90                            
[pip3] nvidia-cuda-nvrtc-cu12==12.8.93        
[pip3] nvidia-cuda-runtime-cu12==12.8.90                                   
[pip3] nvidia-cudnn-cu12==9.10.2.21                                        
[pip3] nvidia-cudnn-frontend==1.6.0                                        
[pip3] nvidia-cufft-cu12==11.3.3.83                                        
[pip3] nvidia-cufile-cu12==1.13.1.3                                        
[pip3] nvidia-curand-cu12==10.3.9.90                                                                                                                   
[pip3] nvidia-cusolver-cu12==11.7.3.90                                                                                                                 
[pip3] nvidia-cusparse-cu12==12.5.8.93                                                                                                                 
[pip3] nvidia-cusparselt-cu12==0.7.1                                       
[pip3] nvidia-dali-cuda120==1.41.0
[pip3] nvidia-ml-py==11.495.46                                             
[pip3] nvidia-modelopt==0.15.1                                                                                                                         
[pip3] nvidia-nccl-cu12==2.27.3                                                                                                                        
[pip3] nvidia-nvimgcodec-cu12==0.3.0.5                                                                                                                 
[pip3] nvidia-nvjitlink-cu12==12.8.93                                                                                                                  
[pip3] nvidia-nvtx-cu12==12.8.90                                                                                                                       
[pip3] nvidia-pyindex==1.0.9                                               
[pip3] onnx==1.16.2                 
[pip3] optree==0.12.1                                                      
[pip3] pynvml==11.5.3                                                      
[pip3] pytorch-triton==3.0.0+dedb7bdf3                 
[pip3] pyzmq==26.2.0                                                       
[pip3] torch==2.8.0                                                        
[pip3] torch_tensorrt==2.5.0a0    
[pip3] torchao==0.9.0                                                      
[pip3] torchaudio==2.8.0                                                   
[pip3] torchvision==0.23.0                                                 
[pip3] transformers==4.56.1                                                
[pip3] triton==3.4.0                                                       
[conda] Could not collect                     
                                                                           
==============================                                             
         vLLM Info                                                         
==============================                                             
ROCM Version                 : Could not collect                                                                                                       
vLLM Version                 : 0.10.2rc2.dev148+gf4962a6d5 (git sha: f4962a6d5)                                                                        
vLLM Build Flags:                                                                                                                                      
  CUDA Archs: Not Set; ROCm: Disabled                                      
GPU Topology:                     
        GPU0    NIC0    CPU Affinity    NUMA Affinity   GPU NUMA ID        
GPU0     X      SYS     92-177  1               N/A                                                                                                    
NIC0    SYS      X                                                                                                                                     
                                                                                                                                                       
Legend:                                                                                                                                                
                                                                                                                                                       
  X    = Self                                                              
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge                
  NV#  = Connection traversing a bonded set of # NVLinks                   
                                     
NIC Legend:                                                                
                                                                           
  NIC0: mlx5_0                                                             
                                                                           
==============================                                             
     Environment Variables                                                 
==============================                                             
PYTORCH_NVML_BASED_CUDA_CHECK=1                                                                                                                        
TORCHINDUCTOR_COMPILE_THREADS=1                                                                                                                        
CUDA_MODULE_LOADING=LAZY 
```

</details>


### 🐛 Describe the bug

I try to deploy `Qwen2VLForConditionalGeneration` using vllm, both tried 0.10.0 and nightly version, all failed on some machine. I run it on 10 L20 instances, 4 of them failed to start.

The model is [Qwen2-VL-2B-Instruct](https://huggingface.co/Qwen/Qwen2-VL-2B-Instruct)

My cmd is 
```
vllm serve /opt/models/mm_embedding_2b --trust-remote-code --swap-space 16 --disable-log-requests --port 9491 --host :: --dtype bfloat16 --limit-mm-per-prompt '{"image":1,"video":1}' --task embed --tensor-parallel-size 1 --max-model-len 4096 --override-pooler-config '{"pooling_type":"LAST","normalize":false}' --chat-template /opt/models/mm_embedding_2b/embedding_template.jinja2 --enforce-eager
```

The error is 

```
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]     self.model_executor = executor_class(vllm_config)                                     
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/executor_base.py", line 54, 
in __init__                                                                                                                                            
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]     self._init_executor()                                                                 
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/uniproc_executor.py", line 4
9, in _init_executor                                                                                                                                   
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]     self.collective_rpc("load_model")                                                     
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]   File "/usr/local/lib/python3.10/dist-packages/vllm/executor/uniproc_executor.py", line 5
8, in collective_rpc                                                                                                                                   
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]     answer = run_method(self.driver_worker, method, args, kwargs)                         
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]   File "/usr/local/lib/python3.10/dist-packages/vllm/utils/__init__.py", line 3045, in run
_method                                                                                                                                                
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]     return func(*args, **kwargs)                                                          
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]   File "/usr/local/lib/python3.10/dist-packages/vllm/v1/worker/gpu_worker.py", line 213, i
n load_model                                                                                                                                           
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]     self.model_runner.load_model(eep_scale_up=eep_scale_up)                               
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]   File "/usr/local/lib/python3.10/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 
2207, in load_model                                                                                                                                    
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]     with DeviceMemoryProfiler() as m:                                                     
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]   File "/usr/local/lib/python3.10/dist-packages/vllm/utils/__init__.py", line 1206, in __e
xit__                                                                                                                                                  
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]     self.final_memory = self.current_memory_usage()                                       
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]   File "/usr/local/lib/python3.10/dist-packages/vllm/utils/__init__.py", line 1198, in cur
rent_memory_usage                                                                                                                                      
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]     return current_platform.get_current_memory_usage(self.device)                         
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]   File "/usr/local/lib/python3.10/dist-packages/vllm/platforms/cuda.py", line 201, in get_
current_memory_usage                                                                                                                                   
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]     torch.cuda.empty_cache()                                                              
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]   File "/usr/local/lib/python3.10/dist-packages/torch/cuda/memory.py", line 224, in empty_
cache                                                                                                                                                  
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718]     torch._C._cuda_emptyCache()                                                           
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718] torch.AcceleratorError: CUDA error: an illegal memory access was encountered              
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktr
ace below might be incorrect.
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(EngineCore_0 pid=713790) ERROR 09-08 09:02:44 [core.py:718] 
```



### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by akaihaoshuai** [comment]
same error in use qwen3-next-80b-a3b-thinking

**Comment by imaben** [comment]
same error in use qwen3-next-80b-a3b

**Comment by zeroorhero** [comment]
> same error in use qwen3-next-80b-a3b

resolved ?

**Comment by Celdrick** [comment]
+1
since v0.10.2,but v0.10.1.1 still works on similar runtime and similar command

when --tensor-parallel-size is set to 1 for using one GPU,it has been resolved,but it appears set to 2 for using multiple GPUs

**Comment by jiangwu300** [comment]
Nope, it's quite random. Happens sometimes only. Still waiting for official response/fix from the vllm team

**Comment by DBMing** [comment]
> Nope, it's quite random. Happens sometimes only. Still waiting for official response/fix from the vllm team

When you encounter the above problem, is it accompanied by the error message "Error: Failed to initialize the TMA descriptor 700"?

**Comment by jiangwu300** [comment]
Anyone tried 0.13.0? Seems a lot more stable from my testing so far. Wondering how others are perceiving it.

**Comment by lost-person** [comment]
+1

**Comment by haifzhu** [comment]
+1 , same issue on v0.10.1.1

**Comment by HojaMuerta** [comment]
same as 0.16.0nightly for qwen3.5 series

**Comment by ccm1990** [comment]
+1
the same issue
output of collect_env.py:

==============================
        System Info
==============================
OS                           : Ubuntu 22.04.5 LTS (x86_64)
GCC version                  : (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0
Clang version                : Could not collect
CMake version                : version 3.22.1
Libc version                 : glibc-2.35

==============================
       PyTorch Info
==============================
PyTorch version              : 2.10.0+cu130
Is debug build               : False
CUDA used to build PyTorch   : 13.0
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0] (64-bit runtime)
Python platform              : Linux-5.15.0-142-generic-x86_64-with-glibc2.35

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : 13.0.48
CUDA_MODULE_LOADING set to   : 
GPU models and configuration : 
GPU 0: NVIDIA H20
GPU 1: NVIDIA H20
GPU 2: NVIDIA H20
GPU 3: NVIDIA H20

Nvidia driver version        : 580.126.20
cuDNN version                : Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.12.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.12.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.12.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.12.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.12.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.12.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.12.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.12.0
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        52 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               64
On-line CPU(s) list:                  0-63
Vendor ID:                            AuthenticAMD
Model name:                           AMD EPYC 9K84 96-Core Processor
CPU family:                           25
Model:                                17
Thread(s) per core:                   2
Core(s) per socket:                   32
Socket(s):                            1
Stepping:                             0
BogoMIPS:                             5200.46
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core invpcid_single ibpb vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 avx512_bf16 clzero xsaveerptr wbnoinvd arat avx512vbmi umip avx512_vbmi2 vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm
Hypervisor vendor:                    KVM
Virtualization type:                  full
L1d cache:                            1 MiB (32 instances)
L1i cache:                            1 MiB (32 instances)
L2 cache:                             32 MiB (32 instances)
L3 cache:                             128 MiB (4 instances)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-63
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Mitigation; safe RET, no microcode
Vulnerability Spec store bypass:      Vulnerable
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; STIBP disabled; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

==============================
Versions of relevant libraries
==============================
[pip3] flashinfer-python==0.6.4
[pip3] numpy==2.0.2
[pip3] nvidia-cublas==13.1.0.3
[pip3] nvidia-cublas-cu12==12.8.4.1
[pip3] nvidia-cuda-cupti==13.0.85
[pip3] nvidia-cuda-cupti-cu12==12.8.90
[pip3] nvidia-cuda-nvrtc==13.0.88
[pip3] nvidia-cuda-nvrtc-cu12==12.8.93
[pip3] nvidia-cuda-runtime==13.0.96
[pip3] nvidia-cuda-runtime-cu12==12.8.90
[pip3] nvidia-cudnn-cu12==9.10.2.21
[pip3] nvidia-cudnn-cu13==9.15.1.9
[pip3] nvidia-cudnn-frontend==1.18.0
[pip3] nvidia-cufft==12.0.0.61
[pip3] nvidia-cufft-cu12==11.3.3.83
[pip3] nvidia-cufile==1.15.1.6
[pip3] nvidia-cufile-cu12==1.13.1.3
[pip3] nvidia-curand==10.4.0.35
[pip3] nvidia-curand-cu12==10.3.9.90
[pip3] nvidia-cusolver==12.0.4.66
[pip3] nvidia-cusolver-cu12==11.7.3.90
[pip3] nvidia-cusparse==12.6.3.3
[pip3] nvidia-cusparse-cu12==12.5.8.93
[pip3] nvidia-cusparselt-cu13==0.8.0
[pip3] nvidia-cutlass-dsl==4.4.1
[pip3] nvidia-cutlass-dsl-libs-base==4.4.1
[pip3] nvidia-ml-py==13.590.48
[pip3] nvidia-modelopt==0.41.0
[pip3] nvidia-nccl-cu13==2.28.9
[pip3] nvidia-nvjitlink==13.0.88
[pip3] nvidia-nvjitlink-cu12==12.8.93
[pip3] nvidia-nvshmem-cu12==3.4.5
[pip3] nvidia-nvshmem-cu13==3.4.5
[pip3] nvidia-nvtx==13.0.85
[pip3] nvidia-nvtx-cu12==12.8.90
[pip3] onnx==1.18.0
[pip3] onnx-graphsurgeon==0.5.8
[pip3] optree==0.19.0
[pip3] pyzmq==27.1.0
[pip3] torch==2.10.0+cu130
[pip3] torch-c-dlpack-ext==0.1.5
[pip3] torchaudio==2.10.0+cu130
[pip3] torchvision==0.25.0+cu130
[pip3] transformers==4.57.6
[pip3] triton==3.6.0
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
vLLM Version                 : 0.17.0
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled
GPU Topology:
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NV18    NV18    0-63    0               N/A
GPU1    NV18     X      NV18    NV18    0-63    0               N/A
GPU2    NV18    NV18     X      NV18    0-63    0               N/A
GPU3    NV18    NV18    NV18     X      0-63    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

==============================
     Environment Variables
==============================
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_REQUIRE_CUDA=cuda>=13.0 brand=unknown,driver>=535,driver<536 brand=grid,driver>=535,driver<536 brand=tesla,driver>=535,driver<536 brand=nvidia,driver>=535,driver<536 brand=quadro,driver>=535,driver<536 brand=quadrortx,driver>=535,driver<536 brand=nvidiartx,driver>=535,driver<536 brand=vapps,driver>=535,driver<536 brand=vpc,driver>=535,driver<536 brand=vcs,driver>=535,driver<536 brand=vws,driver>=535,driver<536 brand=cloudgaming,driver>=535,driver<536 brand=unknown,driver>=550,driver<551 brand=grid,driver>=550,driver<551 brand=tesla,driver>=550,driver<551 brand=nvidia,driver>=550,driver<551 brand=quadro,driver>=550,driver<551 brand=quadrortx,driver>=550,driver<551 brand=nvidiartx,driver>=550,driver<551 brand=vapps,driver>=550,driver<551 brand=vpc,driver>=550,driver<551 brand=vcs,driver>=550,driver<551 brand=vws,driver>=550,driver<551 brand=cloudgaming,driver>=550,driver<551 brand=unknown,driver>=565,driver<566 brand=grid,driver>=565,driver<566 brand=tesla,driver>=565,driver<566 brand=nvidia,driver>=565,driver<566 brand=quadro,driver>=565,driver<566 brand=quadrortx,driver>=565,driver<566 brand=nvidiartx,driver>=565,driver<566 brand=vapps,driver>=565,driver<566 brand=vpc,driver>=565,driver<566 brand=vcs,driver>=565,driver<566 brand=vws,driver>=565,driver<566 brand=cloudgaming,driver>=565,driver<566 brand=unknown,driver>=570,driver<571 brand=grid,driver>=570,driver<571 brand=tesla,driver>=570,driver<571 brand=nvidia,driver>=570,driver<571 brand=quadro,driver>=570,driver<571 brand=quadrortx,driver>=570,driver<571 brand=nvidiartx,driver>=570,driver<571 brand=vapps,driver>=570,driver<571 brand=vpc,driver>=570,driver<571 brand=vcs,driver>=570,driver<571 brand=vws,driver>=570,driver<571 brand=cloudgaming,driver>=570,driver<571 brand=unknown,driver>=575,driver<576 brand=grid,driver>=575,driver<576 brand=tesla,driver>=575,driver<576 brand=nvidia,driver>=575,driver<576 brand=quadro,driver>=575,driver<576 brand=quadrortx,driver>=575,driver<576 brand=nvidiartx,driver>=575,driver<576 brand=vapps,driver>=575,driver<576 brand=vpc,driver>=575,driver<576 brand=vcs,driver>=575,driver<576 brand=vws,driver>=575,driver<576 brand=cloudgaming,driver>=575,driver<576
NCCL_VERSION=2.27.7-1
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NVIDIA_PRODUCT_NAME=CUDA
CUDA_VERSION=13.0.0
VLLM_ALLOW_RUNTIME_LORA_UPDATING=True
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_root

**Comment by VinyehShaw** [comment]
set `vllm_enable_sleep_mode=False` worked for me
