### ISSUE TITLE
vLLM Distributed Inference stuck when using multi -GPU

### ISSUE THREAD

**Issue by RathoreShubh** [vllm-project/vllm#2466]
I am trying to run inferece server on multi GPU using this on (4 * NVIDIA GeForce RTX 3090) server. 

**python -u -m vllm.entrypoints.api_server      --host 0.0.0.0        --model mistralai/Mistral-7B-Instruct-v0.2        --tensor-parallel-size 4**

while this works fine when using --tensor-parallel-size =1 , but on using tensor-parallel-size >1 it stuck on strat up. 

Thanks
<img width="1114" alt="Screenshot 2024-01-17 at 5 44 11 PM" src="https://github.com/vllm-project/vllm/assets/6662738/d2c163dd-3fc0-4ed2-af15-fcd3874ca765">

**Comment by QuantNymph** [comment]
this is happening to me too, on 2 * 3090

**Comment by s-natsubori** [comment]
try these parameters
`--gpu-memory-utilization 0.7~0.9`
`--max-model-len 8192`

**Comment by Double-bear** [comment]
> try these parameters `--gpu-memory-utilization 0.7~0.9` `--max-model-len 8192`

hello, I have tried the method you provided, but it has no effect.

**Comment by QuantNymph** [comment]
No effect here either

**Comment by BilalKHA95** [comment]
Did you found a solution i Ve the same issue ?

**Comment by shubham-bnxt** [comment]
@BilalKHA95 try this

**export NCCL_P2P_DISABLE=1**

this woked for me

**Comment by Palmik** [comment]
> export NCCL_P2P_DISABLE=1

This also solved this issue for me.

**Comment by emersonium** [comment]
> > @BilalKHA95 try this
> > **export NCCL_P2P_DISABLE=1**
> > this woked for me
> 
> Thank's !!! it's working now, this env variable + update cuda tooltik to 12.3

Hi!
 does this result in higher tokens/second for you ? (for a small model like: -model mistralai/Mistral-7B-Instruct-v0.2 --tensor-parallel-size 4)  ? thanks!

**Comment by SuperBruceJia** [comment]
This didn't work for me:
```
export NCCL_P2P_DISABLE=1
```

Is there any solutions?

Thank you guys very much in advance!

Best regards,

Shuyue
June 9th, 2024

**Comment by DarkLight1337** [comment]
We have added [documentation](https://docs.vllm.ai/en/stable/getting_started/debugging.html) for this situation in #5430. Please take a look.
