### ISSUE TITLE
[Bug]: Qwen3-VL-4B-Instruct vllm推理报错

### ISSUE THREAD

**Issue by Angx9006** [vllm-project/vllm#27103]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Your output of `python collect_env.py` here
Collecting environment information...
==============================
        System Info
==============================
OS                           : Ubuntu 22.04.5 LTS (x86_64)
GCC version                  : (conda-forge gcc 12.4.0-2) 12.4.0
Clang version                : Could not collect
CMake version                : Could not collect
Libc version                 : glibc-2.35

==============================
       PyTorch Info
==============================
PyTorch version              : 2.8.0+cu128
Is debug build               : False
CUDA used to build PyTorch   : 12.8
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.10.18 (main, Jun  5 2025, 13:14:17) [GCC 11.2.0] (64-bit runtime)
Python platform              : Linux-5.15.0-91-generic-x86_64-with-glibc2.35

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : 12.8.61
CUDA_MODULE_LOADING set to   : LAZY
GPU models and configuration : 
GPU 0: NVIDIA H20
GPU 1: NVIDIA H20
GPU 2: NVIDIA H20
GPU 3: NVIDIA H20
GPU 4: NVIDIA H20
GPU 5: NVIDIA H20
GPU 6: NVIDIA H20
GPU 7: NVIDIA H20

Nvidia driver version        : 550.144.03
cuDNN version                : Probably one of the following:
/usr/local/cuda-12.4/targets/x86_64-linux/lib/libcudnn.so.8.9.7
/usr/local/cuda-12.4/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.9.7
/usr/local/cuda-12.4/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.9.7
/usr/local/cuda-12.4/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.9.7
/usr/local/cuda-12.4/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.9.7
/usr/local/cuda-12.4/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.9.7
/usr/local/cuda-12.4/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.9.7
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      52 bits physical, 57 bits virtual
Byte Order:                         Little Endian
CPU(s):                             192
On-line CPU(s) list:                0-191
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Xeon(R) Platinum 8457C
CPU family:                         6
Model:                              143
Thread(s) per core:                 2
Core(s) per socket:                 48
Socket(s):                          2
Stepping:                           8
CPU max MHz:                        3800.0000
CPU min MHz:                        800.0000
BogoMIPS:                           5200.00
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
Virtualization:                     VT-x
L1d cache:                          4.5 MiB (96 instances)
L1i cache:                          3 MiB (96 instances)
L2 cache:                           192 MiB (96 instances)
L3 cache:                           195 MiB (2 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0-47,96-143
NUMA node1 CPU(s):                  48-95,144-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

==============================
Versions of relevant libraries
==============================
[pip3] numpy==2.2.6
[pip3] nvidia-cublas-cu12==12.8.4.1
[pip3] nvidia-cuda-cupti-cu12==12.8.90
[pip3] nvidia-cuda-nvrtc-cu12==12.8.93
[pip3] nvidia-cuda-runtime-cu12==12.8.90
[pip3] nvidia-cudnn-cu12==9.10.2.21
[pip3] nvidia-cufft-cu12==11.3.3.83
[pip3] nvidia-cufile-cu12==1.13.1.3
[pip3] nvidia-curand-cu12==10.3.9.90
[pip3] nvidia-cusolver-cu12==11.7.3.90
[pip3] nvidia-cusparse-cu12==12.5.8.93
[pip3] nvidia-cusparselt-cu12==0.7.1
[pip3] nvidia-nccl-cu12==2.27.3
[pip3] nvidia-nvjitlink-cu12==12.8.93
[pip3] nvidia-nvtx-cu12==12.8.90
[pip3] pyzmq==27.1.0
[pip3] torch==2.8.0
[pip3] torchaudio==2.8.0
[pip3] torchvision==0.23.0
[pip3] transformers==4.57.1
[pip3] triton==3.4.0
[conda] numpy                     2.2.6                    pypi_0    pypi
[conda] nvidia-cublas-cu12        12.8.4.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.8.90                  pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.8.93                  pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.8.90                  pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.10.2.21                pypi_0    pypi
[conda] nvidia-cufft-cu12         11.3.3.83                pypi_0    pypi
[conda] nvidia-cufile-cu12        1.13.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.9.90                pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.7.3.90                pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.5.8.93                pypi_0    pypi
[conda] nvidia-cusparselt-cu12    0.7.1                    pypi_0    pypi
[conda] nvidia-nccl-cu12          2.27.3                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.8.93                  pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.8.90                  pypi_0    pypi
[conda] pyzmq                     27.1.0                   pypi_0    pypi
[conda] torch                     2.8.0                    pypi_0    pypi
[conda] torchaudio                2.8.0                    pypi_0    pypi
[conda] torchvision               0.23.0                   pypi_0    pypi
[conda] transformers              4.57.1                   pypi_0    pypi
[conda] triton                    3.4.0                    pypi_0    pypi

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
vLLM Version                 : 0.11.0
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled
GPU Topology:
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    NIC4      NIC5    NIC6    NIC7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NV18    NV18    NV18    NV18    NV18    NV18    PIX     NODE    NODE    NODE    SYS       SYS     SYS     SYS     0-47,96-143     0               N/A
GPU1    NV18     X      NV18    NV18    NV18    NV18    NV18    NV18    NODE    PIX     NODE    NODE    SYS       SYS     SYS     SYS     0-47,96-143     0               N/A
GPU2    NV18    NV18     X      NV18    NV18    NV18    NV18    NV18    NODE    NODE    PIX     NODE    SYS       SYS     SYS     SYS     0-47,96-143     0               N/A
GPU3    NV18    NV18    NV18     X      NV18    NV18    NV18    NV18    NODE    NODE    NODE    PIX     SYS       SYS     SYS     SYS     0-47,96-143     0               N/A
GPU4    NV18    NV18    NV18    NV18     X      NV18    NV18    NV18    SYS     SYS     SYS     SYS     PIX       NODE    NODE    NODE    48-95,144-191   1               N/A
GPU5    NV18    NV18    NV18    NV18    NV18     X      NV18    NV18    SYS     SYS     SYS     SYS     NODE      PIX     NODE    NODE    48-95,144-191   1               N/A
GPU6    NV18    NV18    NV18    NV18    NV18    NV18     X      NV18    SYS     SYS     SYS     SYS     NODE      NODE    PIX     NODE    48-95,144-191   1               N/A
GPU7    NV18    NV18    NV18    NV18    NV18    NV18    NV18     X      SYS     SYS     SYS     SYS     NODE      NODE    NODE    PIX     48-95,144-191   1               N/A
NIC0    PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    SYS       SYS     SYS     SYS
NIC1    NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     NODE     X      NODE    NODE    SYS       SYS     SYS     SYS
NIC2    NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE    NODE     X      NODE    SYS       SYS     SYS     SYS
NIC3    NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     NODE    NODE    NODE     X      SYS       SYS     SYS     SYS
NIC4    SYS     SYS     SYS     SYS     PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS      X        NODE    NODE    NODE
NIC5    SYS     SYS     SYS     SYS     NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     NODE       X      NODE    NODE
NIC6    SYS     SYS     SYS     SYS     NODE    NODE    PIX     NODE    SYS     SYS     SYS     SYS     NODE      NODE     X      NODE
NIC7    SYS     SYS     SYS     SYS     NODE    NODE    NODE    PIX     SYS     SYS     SYS     SYS     NODE      NODE    NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_1
  NIC1: mlx5_2
  NIC2: mlx5_3
  NIC3: mlx5_4
  NIC4: mlx5_5
  NIC5: mlx5_6
  NIC6: mlx5_7
  NIC7: mlx5_8

==============================
     Environment Variables
==============================
LD_LIBRARY_PATH=/usr/local/cuda-12.8/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib64/:/usr/local/cuda-12.8/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/nvidia/lib64/:
CUDA_HOME=/usr/local/cuda-12.8
CUDA_HOME=/usr/local/cuda-12.8
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
CUDA_MODULE_LOADING=LAZY

```

</details>

### 🐛 Describe the bug

推理脚本：
DISABLE_VERSION_CHECK=1 CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python tools/vllm_infer.py \
    --model_name_or_path /data/flux/zhanghang/weights/pretrained/Qwen3-VL-4B-Instruct \
    --template qwen3_vl_nothink \
    --pipeline_parallel_size 1 \
    --dataset caption_image16_test_250821 \
    --image_max_pixels 262144 \
    --save_dir runs/caption/1017

报错完整：
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/worker/gpu_worker.py", line 263, in determine_available_memory
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     self.model_runner.profile_run()
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/worker/gpu_model_runner.py", line 3361, in profile_run
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     self.model.get_multimodal_embeddings(
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 1381, in get_multimodal_embeddings
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     video_embeddings = self._process_video_input(multimodal_input)
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 1335, in _process_video_input
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     video_embeds = self.visual(pixel_values_videos,
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 517, in forward
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     hidden_states = blk(hidden_states,
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 200, in forward
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     x = x + self.attn(self.norm1(x),
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 369, in forward
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     output = flash_attn_varlen_func(q,
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/vllm_flash_attn/flash_attn_interface.py", line 233, in flash_attn_varlen_func
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     out, softmax_lse = torch.ops._vllm_fa2_C.varlen_fwd(
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/_ops.py", line 1243, in __call__
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._op(*args, **kwargs)
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671] torch.AcceleratorError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(Worker_TP0 pid=288155) ERROR 10-17 13:05:09 [multiproc_executor.py:671] 
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671] WorkerProc hit an exception.
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/worker/gpu_worker.py", line 263, in determine_available_memory
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     self.model_runner.profile_run()
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/worker/gpu_model_runner.py", line 3361, in profile_run
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     self.model.get_multimodal_embeddings(
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 1381, in get_multimodal_embeddings
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     video_embeddings = self._process_video_input(multimodal_input)
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 1335, in _process_video_input
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     video_embeds = self.visual(pixel_values_videos,
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 517, in forward
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     hidden_states = blk(hidden_states,
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 200, in forward
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     x = x + self.attn(self.norm1(x),
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 369, in forward
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     output = flash_attn_varlen_func(q,
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/vllm_flash_attn/flash_attn_interface.py", line 233, in flash_attn_varlen_func
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     out, softmax_lse = torch.ops._vllm_fa2_C.varlen_fwd(
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/_ops.py", line 1243, in __call__
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._op(*args, **kwargs)
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671] torch.AcceleratorError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(Worker_TP4 pid=288159) ERROR 10-17 13:05:09 [multiproc_executor.py:671] 
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671] WorkerProc hit an exception.
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/worker/gpu_worker.py", line 263, in determine_available_memory
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     self.model_runner.profile_run()
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/worker/gpu_model_runner.py", line 3361, in profile_run
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     self.model.get_multimodal_embeddings(
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 1381, in get_multimodal_embeddings
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     video_embeddings = self._process_video_input(multimodal_input)
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 1335, in _process_video_input
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     video_embeds = self.visual(pixel_values_videos,
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 517, in forward
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     hidden_states = blk(hidden_states,
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 200, in forward
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     x = x + self.attn(self.norm1(x),
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 369, in forward
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     output = flash_attn_varlen_func(q,
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/vllm_flash_attn/flash_attn_interface.py", line 233, in flash_attn_varlen_func
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     out, softmax_lse = torch.ops._vllm_fa2_C.varlen_fwd(
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/_ops.py", line 1243, in __call__
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._op(*args, **kwargs)
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671] torch.AcceleratorError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(Worker_TP1 pid=288156) ERROR 10-17 13:05:09 [multiproc_executor.py:671] 
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671] WorkerProc hit an exception.
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671] WorkerProc hit an exception.
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/worker/gpu_worker.py", line 263, in determine_available_memory
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     self.model_runner.profile_run()
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/worker/gpu_model_runner.py", line 3361, in profile_run
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     self.model.get_multimodal_embeddings(
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 1381, in get_multimodal_embeddings
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     video_embeddings = self._process_video_input(multimodal_input)
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 1335, in _process_video_input
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/worker/gpu_worker.py", line 263, in determine_available_memory
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     video_embeds = self.visual(pixel_values_videos,
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     self.model_runner.profile_run()
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/worker/gpu_model_runner.py", line 3361, in profile_run
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     self.model.get_multimodal_embeddings(
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 1381, in get_multimodal_embeddings
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     video_embeddings = self._process_video_input(multimodal_input)
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 517, in forward
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 1335, in _process_video_input
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     hidden_states = blk(hidden_states,
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     video_embeds = self.visual(pixel_values_videos,
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 200, in forward
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 517, in forward
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     x = x + self.attn(self.norm1(x),
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     hidden_states = blk(hidden_states,
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 369, in forward
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen3_vl.py", line 200, in forward
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     output = flash_attn_varlen_func(q,
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     x = x + self.attn(self.norm1(x),
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/vllm_flash_attn/flash_attn_interface.py", line 233, in flash_attn_varlen_func
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1773, in _wrapped_call_impl
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     out, softmax_lse = torch.ops._vllm_fa2_C.varlen_fwd(
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/_ops.py", line 1243, in __call__
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1784, in _call_impl
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._op(*args, **kwargs)
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671] torch.AcceleratorError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2_5_vl.py", line 369, in forward
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     output = flash_attn_varlen_func(q,
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/vllm_flash_attn/flash_attn_interface.py", line 233, in flash_attn_varlen_func
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     out, softmax_lse = torch.ops._vllm_fa2_C.varlen_fwd(
(Worker_TP6 pid=288161) ERROR 10-17 13:05:09 [multiproc_executor.py:671] 
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/torch/_ops.py", line 1243, in __call__
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671]     return self._op(*args, **kwargs)
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671] torch.AcceleratorError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(Worker_TP5 pid=288160) ERROR 10-17 13:05:09 [multiproc_executor.py:671] 
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708] EngineCore failed to start.
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708] Traceback (most recent call last):
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 699, in run_engine_core
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708]     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 498, in __init__
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708]     super().__init__(vllm_config, executor_class, log_stats,
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 92, in __init__
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708]     self._initialize_kv_caches(vllm_config)
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 190, in _initialize_kv_caches
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708]     self.model_executor.determine_available_memory())
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/executor/abstract.py", line 85, in determine_available_memory
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708]     return self.collective_rpc("determine_available_memory")
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 264, in collective_rpc
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708]     result = get_response(w, dequeue_timeout,
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 248, in get_response
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708]     raise RuntimeError(
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708] RuntimeError: Worker failed with error 'CUDA error: the provided PTX was compiled with an unsupported toolchain.
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708] For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:09 [core.py:708] ', please check the stack trace above for the root cause
(EngineCore_DP0 pid=287973) ERROR 10-17 13:05:10 [multiproc_executor.py:154] Worker proc VllmWorker-0 died unexpectedly, shutting down executor.
(EngineCore_DP0 pid=287973) Process EngineCore_DP0:
(EngineCore_DP0 pid=287973) Traceback (most recent call last):
(EngineCore_DP0 pid=287973)   File "/root/miniconda3/envs/vllm/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=287973)     self.run()
(EngineCore_DP0 pid=287973)   File "/root/miniconda3/envs/vllm/lib/python3.10/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=287973)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=287973)   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 712, in run_engine_core
(EngineCore_DP0 pid=287973)     raise e
(EngineCore_DP0 pid=287973)   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 699, in run_engine_core
(EngineCore_DP0 pid=287973)     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=287973)   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 498, in __init__
(EngineCore_DP0 pid=287973)     super().__init__(vllm_config, executor_class, log_stats,
(EngineCore_DP0 pid=287973)   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 92, in __init__
(EngineCore_DP0 pid=287973)     self._initialize_kv_caches(vllm_config)
(EngineCore_DP0 pid=287973)   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 190, in _initialize_kv_caches
(EngineCore_DP0 pid=287973)     self.model_executor.determine_available_memory())
(EngineCore_DP0 pid=287973)   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/executor/abstract.py", line 85, in determine_available_memory
(EngineCore_DP0 pid=287973)     return self.collective_rpc("determine_available_memory")
(EngineCore_DP0 pid=287973)   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 264, in collective_rpc
(EngineCore_DP0 pid=287973)     result = get_response(w, dequeue_timeout,
(EngineCore_DP0 pid=287973)   File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/executor/multiproc_executor.py", line 248, in get_response
(EngineCore_DP0 pid=287973)     raise RuntimeError(
(EngineCore_DP0 pid=287973) RuntimeError: Worker failed with error 'CUDA error: the provided PTX was compiled with an unsupported toolchain.
(EngineCore_DP0 pid=287973) CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
(EngineCore_DP0 pid=287973) For debugging consider passing CUDA_LAUNCH_BLOCKING=1
(EngineCore_DP0 pid=287973) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(EngineCore_DP0 pid=287973) ', please check the stack trace above for the root cause
Traceback (most recent call last):
  File "/data/flux/zhanghang/factory/llamafactory/tools/vllm_infer.py", line 208, in <module>
    fire.Fire(vllm_infer)
  File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/data/flux/zhanghang/factory/llamafactory/tools/vllm_infer.py", line 119, in vllm_infer
    llm = LLM(**engine_args)
  File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 297, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/llm_engine.py", line 177, in from_engine_args
    return cls(vllm_config=vllm_config,
  File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/llm_engine.py", line 114, in __init__
    self.engine_core = EngineCoreClient.make_client(
  File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/core_client.py", line 80, in make_client
    return SyncMPClient(vllm_config, executor_class, log_stats)
  File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/core_client.py", line 602, in __init__
    super().__init__(
  File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/core_client.py", line 448, in __init__
    with launch_core_engines(vllm_config, executor_class,
  File "/root/miniconda3/envs/vllm/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/utils.py", line 732, in launch_core_engines
    wait_for_engine_startup(
  File "/root/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/v1/engine/utils.py", line 785, in wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}

核心报错：
torch.AcceleratorError: CUDA error: the provided PTX was compiled with an unsupported toolchain.

其他信息：
在A800机器上可以推理，在H20机器上推理报错

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Yimi81** [comment]
+1 h800

**Comment by mingzeG** [comment]
Same issue. I changed the VLLM_ATTENTION_BACKEND setting to FLASHINFER and installed flashinfer-python==0.3.1 with pip to avoid the problem above.

**Comment by dogehhh** [comment]
> export VLLM_ATTENTION_BACKEND=FLASHINFER

Thank you! This works for me!

**Comment by mingzeG** [comment]
Try to update your flash_attn to 2.8.3

在 2025-10-21 16:40:56，Angx ***@***.***> 写道：
Angx9006 left a comment (vllm-project/vllm#27103)
Same issue. I changed the VLLM_ATTENTION_BACKEND setting to FLASHINFER and installed flashinfer-python==0.3.1 with pip to avoid the problem above.
Not work for me.
 New error "RuntimeError: Qwen3-VL does not support _Backend.FLASHINFER backend now."

**Comment by XueTianci** [comment]
Hi, I’m trying to run vLLM with VLLM_ATTENTION_BACKEND=FLASHINFER (Qwen3-VL-4B-Instruct).
After installing flashinfer-python==0.3.1 and flash_attn==2.8.3,  I encountered the following issue:

`.../torch/include/c10/util/floating_point_utils.h(15): error: identifier "_castu32_f32" is undefined
.../torch/include/c10/util/floating_point_utils.h(27): error: identifier "_castf32_u32" is undefined
`

> Traceback (most recent call last):
>   File "<ENV_PATH>/site-packages/vllm/v1/worker/gpu_model_runner.py", line 3217, in _dummy_sampler_run
>     sampler_output = self.sampler(logits=logits, ...
>   File "<ENV_PATH>/site-packages/vllm/v1/sample/sampler.py", line 180, in sample
>     random_sampled, processed_logprobs = self.topk_topp_sampler(
>   File "<ENV_PATH>/site-packages/vllm/v1/sample/ops/topk_topp_sampler.py", line 289, in flashinfer_sample
>     next_token_ids = flashinfer.sampling.top_k_top_p_sampling_from_logits(
>   File "<ENV_PATH>/site-packages/flashinfer/sampling.py", line 1300, in top_k_mask_logits
>     return get_sampling_module().top_k_mask_logits(
>   File "<ENV_PATH>/site-packages/flashinfer/jit/core.py", line 160, in build_and_load
>     self.build(verbose, need_lock=False)
>   File "<ENV_PATH>/site-packages/flashinfer/jit/cpp_ext.py", line 270, in run_ninja
>     raise RuntimeError(msg) from e
> 
> RuntimeError: Ninja build failed. Ninja output:
> ninja: Entering directory `<CACHE_DIR>/flashinfer/90/cached_ops'
> [1/4] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile \
> -ccbin /apps/spack/.../intel-oneapi-compilers/.../linux/bin/intel64/icc \
> -DTORCH_EXTENSION_NAME=sampling -DTORCH_API_INCLUDE_EXTENSION_H \
> -gencode=arch=compute_90a,code=sm_90a -O3 -std=c++17 --threads=1 -use_fast_math \
> -c <ENV_PATH>/site-packages/flashinfer/data/csrc/flashinfer_sampling_ops.cu \
> -o sampling/flashinfer_sampling_ops.cuda.o
> icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated...
> <ENV_PATH>/site-packages/torch/include/c10/util/floating_point_utils.h(15): error: identifier "_castu32_f32" is undefined
> <ENV_PATH>/site-packages/torch/include/c10/util/floating_point_utils.h(27): error: identifier "_castf32_u32" is undefined
> FAILED: [code=2] sampling/flashinfer_sampling_ops.cuda.o
> 
> [2/4] /usr/local/cuda/bin/nvcc ... -ccbin .../icc ... \
> -c <ENV_PATH>/site-packages/flashinfer/data/csrc/renorm.cu -o sampling/renorm.cuda.o
> ... (same `_castu32_f32` / `_castf32_u32` errors) ...
> 
> [3/4] /usr/local/cuda/bin/nvcc ... -ccbin .../icc ... \
> -c <ENV_PATH>/site-packages/flashinfer/data/csrc/sampling.cu -o sampling/sampling.cuda.o
> ... (same errors) ...
> 
> ninja: build stopped: subcommand failed.
> [rank]: W ... TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.


I searched both the vLLM and flashinfer issues but couldn’t find anything related to this problem.
Are there any other possible solutions?

**Comment by pspdada** [comment]
I encountered the same issue! The 8B model of Qwen3-VL starts up normally, but the 4B model does not. Do you have any good solutions?

**Comment by gerayking** [comment]
same problem.
