### ISSUE TITLE
[Bug]: Multinode inference request with Ray and vLLM crashes - regression from vLLM v0.7.3

### ISSUE THREAD

**Issue by ysimeonovatnvidia** [vllm-project/vllm#29373]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Collecting environment information...
==============================
        System Info
==============================
OS                           : Ubuntu 22.04.5 LTS (x86_64)
GCC version                  : (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version                : Could not collect
CMake version                : version 4.1.3
Libc version                 : glibc-2.35

==============================
       PyTorch Info
==============================
PyTorch version              : 2.9.0+cu129
Is debug build               : False
CUDA used to build PyTorch   : 12.9
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0] (64-bit runtime)
Python platform              : Linux-6.11.0-1016-nvidia-x86_64-with-glibc2.35

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : 12.9.86
CUDA_MODULE_LOADING set to   : 
GPU models and configuration : 
GPU 0: NVIDIA H200
GPU 1: NVIDIA H200
GPU 2: NVIDIA H200
GPU 3: NVIDIA H200
GPU 4: NVIDIA H200
GPU 5: NVIDIA H200
GPU 6: NVIDIA H200
GPU 7: NVIDIA H200

Nvidia driver version        : 570.195.03
cuDNN version                : Could not collect
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        48 bits physical, 57 bits virtual
Byte Order:                           Little Endian
CPU(s):                               128
On-line CPU(s) list:                  0-127
Vendor ID:                            GenuineIntel
Model name:                           Intel(R) Xeon(R) Platinum 8468
CPU family:                           6
Model:                                143
Thread(s) per core:                   2
Core(s) per socket:                   32
Socket(s):                            2
Stepping:                             8
BogoMIPS:                             4200.00
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq dtes64 ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx_vnni avx512_bf16 wbnoinvd arat avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b fsrm md_clear serialize tsxldtrk amx_bf16 avx512_fp16 amx_tile amx_int8 arch_capabilities
Hypervisor vendor:                    KVM
Virtualization type:                  full
L1d cache:                            4 MiB (128 instances)
L1i cache:                            4 MiB (128 instances)
L2 cache:                             256 MiB (64 instances)
L3 cache:                             32 MiB (2 instances)
NUMA node(s):                         2
NUMA node0 CPU(s):                    0-63
NUMA node1 CPU(s):                    64-127
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Unknown: No mitigations
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI SW loop, KVM SW loop
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Mitigation; TSX disabled

==============================
Versions of relevant libraries
==============================
[pip3] flashinfer-python==0.5.2
[pip3] numpy==2.2.0
[pip3] nvidia-cublas-cu12==12.9.1.4
[pip3] nvidia-cuda-cupti-cu12==12.9.79
[pip3] nvidia-cuda-nvrtc-cu12==12.9.86
[pip3] nvidia-cuda-runtime-cu12==12.9.79
[pip3] nvidia-cudnn-cu12==9.10.2.21
[pip3] nvidia-cudnn-frontend==1.16.0
[pip3] nvidia-cufft-cu12==11.4.1.4
[pip3] nvidia-cufile-cu12==1.14.1.1
[pip3] nvidia-curand-cu12==10.3.10.19
[pip3] nvidia-cusolver-cu12==11.7.5.82
[pip3] nvidia-cusparse-cu12==12.5.10.65
[pip3] nvidia-cusparselt-cu12==0.7.1
[pip3] nvidia-cutlass-dsl==4.2.1
[pip3] nvidia-ml-py==13.580.82
[pip3] nvidia-nccl-cu12==2.27.5
[pip3] nvidia-nvjitlink-cu12==12.9.86
[pip3] nvidia-nvshmem-cu12==3.3.20
[pip3] nvidia-nvtx-cu12==12.9.79
[pip3] pyzmq==27.1.0
[pip3] torch==2.9.0+cu129
[pip3] torchaudio==2.9.0+cu129
[pip3] torchvision==0.24.0+cu129
[pip3] transformers==4.57.1
[pip3] triton==3.5.0
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
vLLM Version                 : 0.11.2
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled
GPU Topology:
  	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	NIC0	NIC1	NIC2	NIC3	NIC4	NIC5	NIC6	NIC7	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV18	NV18	NV18	NV18	NV18	NV18	NV18	SYS	SYS	SYS	SYS	PIX	PHB	PHB	PHB	0-63	0		N/A
GPU1	NV18	 X 	NV18	NV18	NV18	NV18	NV18	NV18	SYS	SYS	SYS	SYS	PHB	PIX	PHB	PHB	0-63	0		N/A
GPU2	NV18	NV18	 X 	NV18	NV18	NV18	NV18	NV18	SYS	SYS	SYS	SYS	PHB	PHB	PIX	PHB	0-63	0		N/A
GPU3	NV18	NV18	NV18	 X 	NV18	NV18	NV18	NV18	SYS	SYS	SYS	SYS	PHB	PHB	PHB	PIX	0-63	0		N/A
GPU4	NV18	NV18	NV18	NV18	 X 	NV18	NV18	NV18	PIX	PHB	PHB	PHB	SYS	SYS	SYS	SYS	64-127	1		N/A
GPU5	NV18	NV18	NV18	NV18	NV18	 X 	NV18	NV18	PHB	PIX	PHB	PHB	SYS	SYS	SYS	SYS	64-127	1		N/A
GPU6	NV18	NV18	NV18	NV18	NV18	NV18	 X 	NV18	PHB	PHB	PIX	PHB	SYS	SYS	SYS	SYS	64-127	1		N/A
GPU7	NV18	NV18	NV18	NV18	NV18	NV18	NV18	 X 	PHB	PHB	PHB	PIX	SYS	SYS	SYS	SYS	64-127	1		N/A
NIC0	SYS	SYS	SYS	SYS	PIX	PHB	PHB	PHB	 X 	PHB	PHB	PHB	SYS	SYS	SYS	SYS				
NIC1	SYS	SYS	SYS	SYS	PHB	PIX	PHB	PHB	PHB	 X 	PHB	PHB	SYS	SYS	SYS	SYS				
NIC2	SYS	SYS	SYS	SYS	PHB	PHB	PIX	PHB	PHB	PHB	 X 	PHB	SYS	SYS	SYS	SYS				
NIC3	SYS	SYS	SYS	SYS	PHB	PHB	PHB	PIX	PHB	PHB	PHB	 X 	SYS	SYS	SYS	SYS				
NIC4	PIX	PHB	PHB	PHB	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	 X 	PHB	PHB	PHB				
NIC5	PHB	PIX	PHB	PHB	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PHB	 X 	PHB	PHB				
NIC6	PHB	PHB	PIX	PHB	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PHB	PHB	 X 	PHB				
NIC7	PHB	PHB	PHB	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PHB	PHB	PHB	 X 				

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
  NIC4: mlx5_4
  NIC5: mlx5_5
  NIC6: mlx5_6
  NIC7: mlx5_7

==============================
     Environment Variables
==============================
NVIDIA_VISIBLE_DEVICES=GPU-e7f2aa60-a339-8c7f-df7d-0203ec316148,GPU-15f09c08-0bfc-b600-12ae-44c3382245ca,GPU-e79578ff-d5eb-2080-e96b-e3312bdea557,GPU-0d49f7ca-b241-e148-6d70-75890bcb770f,GPU-b23a942c-3692-0245-54ee-40735c8f5454,GPU-8c853c4e-3ede-3ce0-17cd-2338d9dd1588,GPU-e7163a97-3822-9eea-3fde-1db054d01c48,GPU-dd5719e7-6f02-f2d4-f167-771c8fade3d4
NVIDIA_REQUIRE_CUDA=cuda>=12.9 brand=unknown,driver>=535,driver<536 brand=grid,driver>=535,driver<536 brand=tesla,driver>=535,driver<536 brand=nvidia,driver>=535,driver<536 brand=quadro,driver>=535,driver<536 brand=quadrortx,driver>=535,driver<536 brand=nvidiartx,driver>=535,driver<536 brand=vapps,driver>=535,driver<536 brand=vpc,driver>=535,driver<536 brand=vcs,driver>=535,driver<536 brand=vws,driver>=535,driver<536 brand=cloudgaming,driver>=535,driver<536 brand=unknown,driver>=550,driver<551 brand=grid,driver>=550,driver<551 brand=tesla,driver>=550,driver<551 brand=nvidia,driver>=550,driver<551 brand=quadro,driver>=550,driver<551 brand=quadrortx,driver>=550,driver<551 brand=nvidiartx,driver>=550,driver<551 brand=vapps,driver>=550,driver<551 brand=vpc,driver>=550,driver<551 brand=vcs,driver>=550,driver<551 brand=vws,driver>=550,driver<551 brand=cloudgaming,driver>=550,driver<551 brand=unknown,driver>=560,driver<561 brand=grid,driver>=560,driver<561 brand=tesla,driver>=560,driver<561 brand=nvidia,driver>=560,driver<561 brand=quadro,driver>=560,driver<561 brand=quadrortx,driver>=560,driver<561 brand=nvidiartx,driver>=560,driver<561 brand=vapps,driver>=560,driver<561 brand=vpc,driver>=560,driver<561 brand=vcs,driver>=560,driver<561 brand=vws,driver>=560,driver<561 brand=cloudgaming,driver>=560,driver<561 brand=unknown,driver>=565,driver<566 brand=grid,driver>=565,driver<566 brand=tesla,driver>=565,driver<566 brand=nvidia,driver>=565,driver<566 brand=quadro,driver>=565,driver<566 brand=quadrortx,driver>=565,driver<566 brand=nvidiartx,driver>=565,driver<566 brand=vapps,driver>=565,driver<566 brand=vpc,driver>=565,driver<566 brand=vcs,driver>=565,driver<566 brand=vws,driver>=565,driver<566 brand=cloudgaming,driver>=565,driver<566 brand=unknown,driver>=570,driver<571 brand=grid,driver>=570,driver<571 brand=tesla,driver>=570,driver<571 brand=nvidia,driver>=570,driver<571 brand=quadro,driver>=570,driver<571 brand=quadrortx,driver>=570,driver<571 brand=nvidiartx,driver>=570,driver<571 brand=vapps,driver>=570,driver<571 brand=vpc,driver>=570,driver<571 brand=vcs,driver>=570,driver<571 brand=vws,driver>=570,driver<571 brand=cloudgaming,driver>=570,driver<571
NCCL_VERSION=2.27.3-1
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NCCL_DEBUG=WARN
NVIDIA_PRODUCT_NAME=CUDA
NVIDIA_MOFED=enabled
VLLM_USAGE_SOURCE=production-docker-image
CUDA_VERSION=12.9.1
LD_LIBRARY_PATH=/usr/local/nvidia/lib64:/usr/local/cuda/lib64
CUDA_HOME=/usr/local/cuda
CUDA_HOME=/usr/local/cuda
VLLM_HOST_IP=10.0.39.33
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1

[deepseek_multinode.log](https://github.com/user-attachments/files/23738153/deepseek_multinode.log)

```

</details>

### 🐛 Describe the bug

```
vllm serve /model --tensor-parallel-size 8 --pipeline-parallel-size 2 --distributed-executor-backend ray --dtype bfloat16 --gpu-memory-utilization 0.9 --trust-remote-code --served-model-name deepseek-ai/DeepSeek-R1
```
vLLM loads and warms up cleanly, but the first inference hangs until a Ray compiled-DAG channel times out after 300s and the Raylet dies (RayChannelTimeoutError → ChannelError: Channel closed in deepseek_multinode.log). That points to Ray’s compiled-graph path hanging/crashing rather than an NCCL collective failing.
```
(APIServer pid=37667) INFO 11-24 16:09:24 [launcher.py:46] Route: /ping, Methods: POST
(APIServer pid=37667) INFO 11-24 16:09:24 [launcher.py:46] Route: /invocations, Methods: POST
(APIServer pid=37667) INFO 11-24 16:09:24 [launcher.py:46] Route: /metrics, Methods: GET
(APIServer pid=37667) INFO:     Started server process [37667]
(APIServer pid=37667) INFO:     Waiting for application startup.
(APIServer pid=37667) INFO:     Application startup complete.
(APIServer pid=37667) INFO:     10.2.21.131:56994 - "GET /v1/models HTTP/1.1" 200 OK
(APIServer pid=37667) INFO 11-24 16:09:47 [chat_utils.py:557] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
(EngineCore_DP0 pid=37804) INFO 11-24 16:09:48 [ray_executor.py:538] RAY_CGRAPH_get_timeout is set to 300
(EngineCore_DP0 pid=37804) INFO 11-24 16:09:48 [ray_executor.py:542] VLLM_USE_RAY_COMPILED_DAG_CHANNEL_TYPE = auto
(EngineCore_DP0 pid=37804) INFO 11-24 16:09:48 [ray_executor.py:546] VLLM_USE_RAY_COMPILED_DAG_OVERLAP_COMM = False
(EngineCore_DP0 pid=37804) INFO 11-24 16:09:48 [ray_executor.py:605] Using RayPPCommunicator (which wraps vLLM _PP GroupCoordinator) for Ray Compiled Graph communication.
(EngineCore_DP0 pid=37804) 2025-11-24 16:09:48,096	INFO torch_tensor_accelerator_channel.py:807 -- Creating communicator group 1389844d-f9e8-4e13-80e8-634f1ac0cefd on actors: [Actor(RayWorkerWrapper, 1e301752790d2b5ea7fab2ba01000000), Actor(RayWorkerWrapper, 321bb37fee2721fe7495a98701000000), Actor(RayWorkerWrapper, 3c6ca94490de6015c325aa1c01000000), Actor(RayWorkerWrapper, 2acc03f878ffd221f8f0201801000000), Actor(RayWorkerWrapper, 4d833b8ae5903b301d1fd02b01000000), Actor(RayWorkerWrapper, 21caf2927c23d9dfdeafd0f401000000), Actor(RayWorkerWrapper, 49fbad2af1b4e4db2c2f8b8401000000), Actor(RayWorkerWrapper, b6ba8a1c11de0c2601ac3eae01000000), Actor(RayWorkerWrapper, 8354a1efe8537e2ce6aa7a3901000000), Actor(RayWorkerWrapper, 6ead1cbc4a5f057f1a42d29d01000000), Actor(RayWorkerWrapper, a110e63c8fac222b5d0ee39201000000), Actor(RayWorkerWrapper, 95b9c9b8ae7afff9d205d71701000000), Actor(RayWorkerWrapper, 194a06f5fe9d34d417567f6601000000), Actor(RayWorkerWrapper, 2aa11967c4216061b493bb9b01000000), Actor(RayWorkerWrapper, 805e5250e679fde5f55642fd01000000), Actor(RayWorkerWrapper, 7d39becec18c4f619b564fe801000000)]
(EngineCore_DP0 pid=37804) 2025-11-24 16:09:48,291	INFO torch_tensor_accelerator_channel.py:833 -- Communicator group initialized.

(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [dump_input.py:72] Dumping input data for V1 LLM engine (v0.11.2) with config: model='/model', speculative_config=None, tokenizer='/model', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=163840, download_dir=None, load_format=auto, tensor_parallel_size=8, pipeline_parallel_size=2, data_parallel_size=1, disable_custom_all_reduce=False, quantization=fp8, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=deepseek-ai/DeepSeek-R1, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none', '+quant_fp8', '+quant_fp8'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer'], 'compile_mm_encoder': False, 'use_inductor': None, 'compile_sizes': [], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_cudagraph_capture_size': 512, 'local_cache_dir': None}, 
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [dump_input.py:79] Dumping scheduler output for model execution: SchedulerOutput(scheduled_new_reqs=[NewRequestData(req_id=chatcmpl-ff7e20e1b1284820a2009ddc53cd4757,prompt_token_ids_len=20,mm_features=[],sampling_params=SamplingParams(n=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.7, top_p=0.95, top_k=0, min_p=0.0, seed=None, stop=[], stop_token_ids=[], bad_words=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=100, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None, structured_outputs=None, extra_args=None),block_ids=([1],),num_computed_tokens=0,lora_request=None,prompt_embeds_shape=None)], scheduled_cached_reqs=CachedRequestData(req_ids=[], resumed_req_ids=[], new_token_ids=[], all_token_ids={}, new_block_ids=[], num_computed_tokens=[], num_output_tokens=[]), num_scheduled_tokens={chatcmpl-ff7e20e1b1284820a2009ddc53cd4757: 20}, total_num_scheduled_tokens=20, scheduled_spec_decode_tokens={}, scheduled_encoder_inputs={}, num_common_prefix_blocks=[1], finished_req_ids=[], free_encoder_mm_hashes=[], pending_structured_output_tokens=false, kv_connector_metadata=null, ec_connector_metadata=null)
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [dump_input.py:81] Dumping scheduler stats: SchedulerStats(num_running_reqs=1, num_waiting_reqs=0, step_counter=0, current_wave=0, kv_cache_usage=2.670512204239195e-05, prefix_cache_stats=PrefixCacheStats(reset=False, requests=1, queries=20, hits=0, preempted_requests=0, preempted_queries=0, preempted_hits=0), connector_prefix_cache_stats=None, spec_decoding_stats=None, kv_connector_stats=None, waiting_lora_adapters={}, running_lora_adapters={})
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844] EngineCore encountered a fatal error.
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844] Traceback (most recent call last):
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/ray/dag/compiled_dag_node.py", line 2525, in _execute_until
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     result = self._dag_output_fetcher.read(timeout)
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/ray/experimental/channel/common.py", line 312, in read
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     outputs = self._read_list(timeout)
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]               ^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/ray/experimental/channel/common.py", line 403, in _read_list
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     raise e
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/ray/experimental/channel/common.py", line 385, in _read_list
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     result = c.read(min(remaining_timeout, iteration_timeout))
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/ray/experimental/channel/shared_memory_channel.py", line 776, in read
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     return self._channel_dict[self._resolve_actor_id()].read(timeout)
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/ray/experimental/channel/shared_memory_channel.py", line 480, in read
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     ret = self._worker.get_objects(
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]           ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py", line 998, in get_objects
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     ] = self.core_worker.get_objects(
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "python/ray/_raylet.pyx", line 3141, in ray._raylet.CoreWorker.get_objects
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "python/ray/includes/common.pxi", line 120, in ray._raylet.check_status
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844] ray.exceptions.RayChannelTimeoutError: System error: Timed out waiting for object available to read. ObjectID: 00c8a0c70956419879521afbc4959f4d8925cea00100000002e1f505
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844] 
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844] The above exception was the direct cause of the following exception:
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844] 
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844] Traceback (most recent call last):
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 835, in run_engine_core
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     engine_core.run_busy_loop()
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 862, in run_busy_loop
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     self._process_engine_step()
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 891, in _process_engine_step
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     outputs, model_executed = self.step_fn()
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]                               ^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 437, in step_with_batch_queue
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     model_output = future.result()
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]                    ^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/ray_utils.py", line 150, in result
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     outputs = ray.get(self.ref_or_refs, timeout=timeout)
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     return fn(*args, **kwargs)
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]            ^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     return func(*args, **kwargs)
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py", line 2934, in get
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     return object_refs.get(timeout=timeout)
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/ray/experimental/compiled_dag_ref.py", line 115, in get
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     self._dag._execute_until(
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]   File "/usr/local/lib/python3.12/dist-packages/ray/dag/compiled_dag_node.py", line 2535, in _execute_until
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844]     raise RayChannelTimeoutError(
(EngineCore_DP0 pid=37804) ERROR 11-24 16:14:48 [core.py:844] ray.exceptions.RayChannelTimeoutError: System error: If the execution is expected to take a long time, increase RAY_CGRAPH_get_timeout which is currently 300 seconds. Otherwise, this may indicate that the execution is hanging.
(EngineCore_DP0 pid=37804) INFO 11-24 16:14:48 [ray_executor.py:121] Shutting down Ray distributed executor. If you see error log from logging.cc regarding SIGTERM received, please ignore because this is the expected termination process in Ray.
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,855	INFO compiled_dag_node.py:2167 -- Tearing down compiled DAG
(APIServer pid=37667) ERROR 11-24 16:14:48 [async_llm.py:525] AsyncLLM output_handler failed.
(APIServer pid=37667) ERROR 11-24 16:14:48 [async_llm.py:525] Traceback (most recent call last):
(APIServer pid=37667) ERROR 11-24 16:14:48 [async_llm.py:525]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 477, in output_handler
(APIServer pid=37667) ERROR 11-24 16:14:48 [async_llm.py:525]     outputs = await engine_core.get_output_async()
(APIServer pid=37667) ERROR 11-24 16:14:48 [async_llm.py:525]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=37667) ERROR 11-24 16:14:48 [async_llm.py:525]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 883, in get_output_async
(APIServer pid=37667) ERROR 11-24 16:14:48 [async_llm.py:525]     raise self._format_exception(outputs) from None
(APIServer pid=37667) ERROR 11-24 16:14:48 [async_llm.py:525] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,855	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 805e5250e679fde5f55642fd01000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,855	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 7d39becec18c4f619b564fe801000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,855	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 194a06f5fe9d34d417567f6601000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,855	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 3c6ca94490de6015c325aa1c01000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,855	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 4d833b8ae5903b301d1fd02b01000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,855	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 6ead1cbc4a5f057f1a42d29d01000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,855	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, a110e63c8fac222b5d0ee39201000000)
(APIServer pid=37667) INFO:     10.2.21.131:38066 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,855	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 321bb37fee2721fe7495a98701000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,855	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 8354a1efe8537e2ce6aa7a3901000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,856	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 49fbad2af1b4e4db2c2f8b8401000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,856	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 21caf2927c23d9dfdeafd0f401000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,856	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, b6ba8a1c11de0c2601ac3eae01000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,856	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 95b9c9b8ae7afff9d205d71701000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,856	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 2aa11967c4216061b493bb9b01000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,856	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 1e301752790d2b5ea7fab2ba01000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,856	INFO compiled_dag_node.py:2172 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 2acc03f878ffd221f8f0201801000000)
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,872	INFO compiled_dag_node.py:2194 -- Waiting for worker tasks to exit
(EngineCore_DP0 pid=37804) 2025-11-24 16:14:48,872	INFO compiled_dag_node.py:2197 -- Teardown complete
(EngineCore_DP0 pid=37804) Process EngineCore_DP0:
(EngineCore_DP0 pid=37804) Traceback (most recent call last):
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/ray/dag/compiled_dag_node.py", line 2525, in _execute_until
(EngineCore_DP0 pid=37804)     result = self._dag_output_fetcher.read(timeout)
(EngineCore_DP0 pid=37804)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/ray/experimental/channel/common.py", line 312, in read
(EngineCore_DP0 pid=37804)     outputs = self._read_list(timeout)
(EngineCore_DP0 pid=37804)               ^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/ray/experimental/channel/common.py", line 403, in _read_list
(EngineCore_DP0 pid=37804)     raise e
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/ray/experimental/channel/common.py", line 385, in _read_list
(EngineCore_DP0 pid=37804)     result = c.read(min(remaining_timeout, iteration_timeout))
(EngineCore_DP0 pid=37804)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/ray/experimental/channel/shared_memory_channel.py", line 776, in read
(EngineCore_DP0 pid=37804)     return self._channel_dict[self._resolve_actor_id()].read(timeout)
(EngineCore_DP0 pid=37804)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/ray/experimental/channel/shared_memory_channel.py", line 480, in read
(EngineCore_DP0 pid=37804)     ret = self._worker.get_objects(
(EngineCore_DP0 pid=37804)           ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py", line 998, in get_objects
(EngineCore_DP0 pid=37804)     ] = self.core_worker.get_objects(
(EngineCore_DP0 pid=37804)         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804)   File "python/ray/_raylet.pyx", line 3141, in ray._raylet.CoreWorker.get_objects
(EngineCore_DP0 pid=37804)   File "python/ray/includes/common.pxi", line 120, in ray._raylet.check_status
(EngineCore_DP0 pid=37804) ray.exceptions.RayChannelTimeoutError: System error: Timed out waiting for object available to read. ObjectID: 00c8a0c70956419879521afbc4959f4d8925cea00100000002e1f505
(EngineCore_DP0 pid=37804) 
(EngineCore_DP0 pid=37804) The above exception was the direct cause of the following exception:
(EngineCore_DP0 pid=37804) 
(EngineCore_DP0 pid=37804) Traceback (most recent call last):
(EngineCore_DP0 pid=37804)   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=37804)     self.run()
(EngineCore_DP0 pid=37804)   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=37804)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 846, in run_engine_core
(EngineCore_DP0 pid=37804)     raise e
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 835, in run_engine_core
(EngineCore_DP0 pid=37804)     engine_core.run_busy_loop()
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 862, in run_busy_loop
(EngineCore_DP0 pid=37804)     self._process_engine_step()
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 891, in _process_engine_step
(EngineCore_DP0 pid=37804)     outputs, model_executed = self.step_fn()
(EngineCore_DP0 pid=37804)                               ^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 437, in step_with_batch_queue
(EngineCore_DP0 pid=37804)     model_output = future.result()
(EngineCore_DP0 pid=37804)                    ^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/ray_utils.py", line 150, in result
(EngineCore_DP0 pid=37804)     outputs = ray.get(self.ref_or_refs, timeout=timeout)
(EngineCore_DP0 pid=37804)               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
(EngineCore_DP0 pid=37804)     return fn(*args, **kwargs)
(EngineCore_DP0 pid=37804)            ^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
(EngineCore_DP0 pid=37804)     return func(*args, **kwargs)
(EngineCore_DP0 pid=37804)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py", line 2934, in get
(EngineCore_DP0 pid=37804)     return object_refs.get(timeout=timeout)
(EngineCore_DP0 pid=37804)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/ray/experimental/compiled_dag_ref.py", line 115, in get
(EngineCore_DP0 pid=37804)     self._dag._execute_until(
(EngineCore_DP0 pid=37804)   File "/usr/local/lib/python3.12/dist-packages/ray/dag/compiled_dag_node.py", line 2535, in _execute_until
(EngineCore_DP0 pid=37804)     raise RayChannelTimeoutError(
(EngineCore_DP0 pid=37804) ray.exceptions.RayChannelTimeoutError: System error: If the execution is expected to take a long time, increase RAY_CGRAPH_get_timeout which is currently 300 seconds. Otherwise, this may indicate that the execution is hanging.
(EngineCore_DP0 pid=37804) (raylet) Raylet is terminated. Termination is unexpected. Possible reasons include: (1) SIGKILL by the user or system OOM killer, (2) Invalid memory access from Raylet causing SIGSEGV or SIGBUS, (3) Other termination signals. Last 20 lines of the Raylet logs:
(EngineCore_DP0 pid=37804)     - bytes errored: 0
(EngineCore_DP0 pid=37804)     
(EngineCore_DP0 pid=37804)     [2025-11-24 16:14:48,882 C 37444 37444] (raylet) experimental_mutable_object_provider.cc:154:  An unexpected system state has occurred. You have likely discovered a bug in Ray. Please report this issue at https://github.com/ray-project/ray/issues and we'll work with you to fix it. Check failed: object_manager_->WriteAcquire(info.local_object_id, total_data_size, nullptr, total_metadata_size, info.num_readers, object_backing_store) Status not OK: ChannelError: Channel closed. 
(EngineCore_DP0 pid=37804)     *** StackTrace Information ***
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xef0aca) [0x5d9928c5daca] ray::operator<<()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xef30e9) [0x5d9928c600e9] ray::RayLog::~RayLog()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x3e037a) [0x5d992814d37a] ray::core::experimental::MutableObjectProvider::HandlePushMutableObject()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x2a4e8f) [0x5d9928011e8f] ray::raylet::NodeManager::HandlePushMutableObject()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x30e24f) [0x5d992807b24f] ray::rpc::ServerCallImpl<>::HandleRequestImpl()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x7f1668) [0x5d992855e668] EventTracker::RecordExecution()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x7e9377) [0x5d9928556377] std::_Function_handler<>::_M_invoke()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x7ea31b) [0x5d992855731b] boost::asio::detail::executor_op<>::do_complete()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xebc47b) [0x5d9928c2947b] boost::asio::detail::scheduler::do_run_one()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xebea09) [0x5d9928c2ba09] boost::asio::detail::scheduler::run()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xebef22) [0x5d9928c2bf22] boost::asio::io_context::run()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x21a557) [0x5d9927f87557] main
(EngineCore_DP0 pid=37804)     /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x77f524e20d90]
(EngineCore_DP0 pid=37804)     /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x77f524e20e40] __libc_start_main
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x23d997) [0x5d9927faa997]
(EngineCore_DP0 pid=37804)     
(EngineCore_DP0 pid=37804) 
(EngineCore_DP0 pid=37804) (RayWorkerWrapper pid=31550, ip=10.2.21.131) INFO 11-24 16:09:23 [custom_all_reduce.py:216] Registering 600 cuda graph addresses [repeated 15x across cluster]
(EngineCore_DP0 pid=37804) (RayWorkerWrapper pid=31547, ip=10.2.21.131) INFO 11-24 16:09:23 [gpu_model_runner.py:4244] Graph capturing finished in 18 secs, took -0.32 GiB
(EngineCore_DP0 pid=37804) (raylet) [2025-11-24 16:14:48,882 C 37444 37444] (raylet) experimental_mutable_object_provider.cc:154:  An unexpected system state has occurred. You have likely discovered a bug in Ray. Please report this issue at https://github.com/ray-project/ray/issues and we'll work with you to fix it. Check failed: object_manager_->WriteAcquire(info.local_object_id, total_data_size, nullptr, total_metadata_size, info.num_readers, object_backing_store) Status not OK: ChannelError: Channel closed. 
(EngineCore_DP0 pid=37804) (raylet) *** StackTrace Information ***
(EngineCore_DP0 pid=37804) (raylet) /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xef0aca) [0x5d9928c5daca] ray::operator<<()
(EngineCore_DP0 pid=37804) (raylet) /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xef30e9) [0x5d9928c600e9] ray::RayLog::~RayLog()
(EngineCore_DP0 pid=37804) (raylet) /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x3e037a) [0x5d992814d37a] ray::core::experimental::MutableObjectProvider::HandlePushMutableObject()
(EngineCore_DP0 pid=37804) (raylet) /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x2a4e8f) [0x5d9928011e8f] ray::raylet::NodeManager::HandlePushMutableObject()
(EngineCore_DP0 pid=37804) (raylet) /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x30e24f) [0x5d992807b24f] ray::rpc::ServerCallImpl<>::HandleRequestImpl()
(EngineCore_DP0 pid=37804) (raylet) /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x7f1668) [0x5d992855e668] EventTracker::RecordExecution()
(EngineCore_DP0 pid=37804) (raylet) /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x7e9377) [0x5d9928556377] std::_Function_handler<>::_M_invoke()
(EngineCore_DP0 pid=37804) (raylet) /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x7ea31b) [0x5d992855731b] boost::asio::detail::executor_op<>::do_complete()
(EngineCore_DP0 pid=37804) (raylet) /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xebc47b) [0x5d9928c2947b] boost::asio::detail::scheduler::do_run_one()
(EngineCore_DP0 pid=37804) (raylet) /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xebea09) [0x5d9928c2ba09] boost::asio::detail::scheduler::run()
(EngineCore_DP0 pid=37804) (raylet) /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xebef22) [0x5d9928c2bf22] boost::asio::io_context::run()
(EngineCore_DP0 pid=37804) (raylet) /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x21a557) [0x5d9927f87557] main
(EngineCore_DP0 pid=37804) (raylet) /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x77f524e20d90]
(EngineCore_DP0 pid=37804) (raylet) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x77f524e20e40] __libc_start_main
(EngineCore_DP0 pid=37804) (raylet) /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x23d997) [0x5d9927faa997]
(EngineCore_DP0 pid=37804) (raylet) 
(EngineCore_DP0 pid=37804) (raylet) Raylet is terminated. Termination is unexpected. Possible reasons include: (1) SIGKILL by the user or system OOM killer, (2) Invalid memory access from Raylet causing SIGSEGV or SIGBUS, (3) Other termination signals. Last 20 lines of the Raylet logs:
(EngineCore_DP0 pid=37804)     - bytes errored: 0
(EngineCore_DP0 pid=37804)     
(EngineCore_DP0 pid=37804)     [2025-11-24 16:14:48,882 C 37444 37444] (raylet) experimental_mutable_object_provider.cc:154:  An unexpected system state has occurred. You have likely discovered a bug in Ray. Please report this issue at https://github.com/ray-project/ray/issues and we'll work with you to fix it. Check failed: object_manager_->WriteAcquire(info.local_object_id, total_data_size, nullptr, total_metadata_size, info.num_readers, object_backing_store) Status not OK: ChannelError: Channel closed. 
(EngineCore_DP0 pid=37804)     *** StackTrace Information ***
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xef0aca) [0x5d9928c5daca] ray::operator<<()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xef30e9) [0x5d9928c600e9] ray::RayLog::~RayLog()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x3e037a) [0x5d992814d37a] ray::core::experimental::MutableObjectProvider::HandlePushMutableObject()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x2a4e8f) [0x5d9928011e8f] ray::raylet::NodeManager::HandlePushMutableObject()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x30e24f) [0x5d992807b24f] ray::rpc::ServerCallImpl<>::HandleRequestImpl()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x7f1668) [0x5d992855e668] EventTracker::RecordExecution()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x7e9377) [0x5d9928556377] std::_Function_handler<>::_M_invoke()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x7ea31b) [0x5d992855731b] boost::asio::detail::executor_op<>::do_complete()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xebc47b) [0x5d9928c2947b] boost::asio::detail::scheduler::do_run_one()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xebea09) [0x5d9928c2ba09] boost::asio::detail::scheduler::run()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0xebef22) [0x5d9928c2bf22] boost::asio::io_context::run()
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x21a557) [0x5d9927f87557] main
(EngineCore_DP0 pid=37804)     /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x77f524e20d90]
(EngineCore_DP0 pid=37804)     /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x77f524e20e40] __libc_start_main
(EngineCore_DP0 pid=37804)     /usr/local/lib/python3.12/dist-packages/ray/core/src/ray/raylet/raylet(+0x23d997) [0x5d9927faa997]
(EngineCore_DP0 pid=37804)     
(EngineCore_DP0 pid=37804) 
(APIServer pid=37667) INFO:     Shutting down
(APIServer pid=37667) INFO:     Waiting for application shutdown.
(APIServer pid=37667) INFO:     Application shutdown complete.
(APIServer pid=37667) INFO:     Finished server process [37667]
root@ds-gpu-node-1-6fd4846fbc-zzd88:/vllm-workspace# 
```
The same deployment but with vLLM v0.7.3 works without issues.
In addition, the model loads across the 16 GPUs (2 nodes x 8 GPUs) but I see the following warning: 
```
(EngineCore_DP0 pid=37804) WARNING 11-24 15:56:41 [ray_utils.py:331] Tensor parallel size (16) exceeds available GPUs (8). This may result in Ray placement group allocation failures. Consider reducing tensor_parallel_size to 8 or less, or ensure your Ray cluster has 16 GPUs available.

```
Even Ray shows 16:
```
root@ds-gpu-node-2-5ff46cd9b5-pjhd4:/vllm-workspace# ray --version
ray, version 2.51.1
root@ds-gpu-node-2-5ff46cd9b5-pjhd4:/vllm-workspace# ray status   
======== Autoscaler status: 2025-11-24 16:44:05.468566 ========
Node status
---------------------------------------------------------------
Active:
 1 node_b4934412308c56c8d5d82fce102744e64a499987af6c30827fa32c53
 1 node_0bbe15e6fc9a1e1a7f83926c773d8fa513497d01a01fbf058fa95e8d
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Total Usage:
 0.0/32.0 CPU
 16.0/16.0 GPU (16.0 used of 16.0 reserved in placement groups)
 0B/386.20GiB memory
 0B/121.60GiB object_store_memory

From request_resources:
 (none)
Pending Demands:
 (no resource demands)
root@ds-gpu-node-2-5ff46cd9b5-pjhd4:/vllm-workspace#
```

I see the same behaviour in AWS EKS with EFA and BareMetal Kubernetes cluster with Infiniband. 

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by umi-soft** [comment]
> Thanks! It is with what is packaged with the vllm/vllm-openai:v0.11.2 container image! I also tried with several earlier versions, and it is the same. The only container image that works for me is llm/vllm-openai:v0.7.3

same problem with the vllm/vllm-openai:v0.11.2，I have 4 servers, each with 2 T4 files, deployed on Qwen3-32B，TP 4 and PP2

@DarkLight1337 @njhill @mgoin

**Comment by ruisearch42** [comment]
Hi @ysimeonovatnvidia , RayChannelTimeoutError indicates there is hanging, and one of the common causes was multi-node network was not properly set up.

Ray Compiled Graph uses NCCL underneath, you can turn on NCCL_DEBUG to see if there is anything suspicious.

**Comment by tensorsofthewall** [comment]
+1. I reported this issue a while back (https://github.com/vllm-project/vllm/issues/26899). Adding the `VLLM_USE_RAY_COMPILED_DAG_CHANNEL_TYPE=shm` environment variable allows the model to run, but eventually vllm will crash. The maximum time I was able to serve the model was ~46 hours.

**Comment by alesspalma** [comment]
any updates on this @colldata79 ? @ving666 @victrgao

**Comment by SiriusPaul** [comment]
相同的问题，使用ray部署qwen2.5-7B训练时出现
