### ISSUE TITLE
[Bug]: Error occurred when I run an simple command: "TORCH_USE_CUDA_DSA=1 LMCACHE_CHUNK_SIZE=8 vllm serve /home/nbw/model/Qwen2-0.5B/  --port 8000 --kv-transfer-config '{"kv_connector":"LMCacheConnectorV1", "kv_role":"kv_both"}'"

### ISSUE THREAD

**Issue by niebowen666** [vllm-project/vllm#30031]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
(vllm-128) root@dpss170-NF5280:/home/nbw# python collect_env.py
Collecting environment information...
==============================
        System Info
==============================
OS                           : Ubuntu 24.04.3 LTS (x86_64)
GCC version                  : (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Clang version                : 18.1.3 (1ubuntu1)
CMake version                : version 3.28.3
Libc version                 : glibc-2.39

==============================
       PyTorch Info
==============================
PyTorch version              : 2.9.0+cu128
Is debug build               : False
CUDA used to build PyTorch   : 12.8
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.9 | packaged by Anaconda, Inc. | (main, Feb  6 2025, 18:56:27) [GCC 11.2.0] (64-bit runtime)
Python platform              : Linux-6.9.0-x86_64-with-glibc2.39

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : 12.8.93
CUDA_MODULE_LOADING set to   :
GPU models and configuration : GPU 0: NVIDIA L20
Nvidia driver version        : 570.124.06
cuDNN version                : Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.16.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.16.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.16.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.16.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.16.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.16.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.16.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.16.0
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        52 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               288
On-line CPU(s) list:                  0-287
Vendor ID:                            GenuineIntel
BIOS Vendor ID:                       Intel(R) Corporation
Model name:                           Intel(R) Xeon(R) 6766E
BIOS Model name:                      Intel(R) Xeon(R) 6766E  CPU @ 1.9GHz
BIOS CPU family:                      179
CPU family:                           6
Model:                                175
Thread(s) per core:                   1
Core(s) per socket:                   144
Socket(s):                            2
Stepping:                             3
CPU(s) scaling MHz:                   30%
CPU max MHz:                          2700.0000
CPU min MHz:                          800.0000
BogoMIPS:                             3800.00
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect user_shstk avx_vnni lam wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req vnmi umip pku ospke waitpkg gfni vaes vpclmulqdq tme rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize pconfig arch_lbr ibt flush_l1d arch_capabilities
Virtualization:                       VT-x
L1d cache:                            9 MiB (288 instances)
L1i cache:                            18 MiB (288 instances)
L2 cache:                             288 MiB (72 instances)
L3 cache:                             216 MiB (2 instances)
NUMA node(s):                         2
NUMA node0 CPU(s):                    0-143
NUMA node1 CPU(s):                    144-287
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS Not affected; BHI BHI_DIS_S
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

==============================
Versions of relevant libraries
==============================
[pip3] flashinfer-python==0.5.3
[pip3] numpy==2.2.0
[pip3] nvidia-cublas-cu12==12.8.4.1
[pip3] nvidia-cuda-cupti-cu12==12.8.90
[pip3] nvidia-cuda-nvrtc-cu12==12.8.93
[pip3] nvidia-cuda-runtime-cu12==12.8.90
[pip3] nvidia-cudnn-cu12==9.10.2.21
[pip3] nvidia-cudnn-frontend==1.16.0
[pip3] nvidia-cufft-cu12==11.3.3.83
[pip3] nvidia-cufile-cu12==1.13.1.3
[pip3] nvidia-curand-cu12==10.3.9.90
[pip3] nvidia-cusolver-cu12==11.7.3.90
[pip3] nvidia-cusparse-cu12==12.5.8.93
[pip3] nvidia-cusparselt-cu12==0.7.1
[pip3] nvidia-cutlass-dsl==4.3.1
[pip3] nvidia-ml-py==13.580.82
[pip3] nvidia-nccl-cu12==2.27.5
[pip3] nvidia-nvjitlink-cu12==12.8.93
[pip3] nvidia-nvshmem-cu12==3.3.20
[pip3] nvidia-nvtx-cu12==12.8.90
[pip3] pyzmq==27.1.0
[pip3] torch==2.9.0+cu128
[pip3] torchaudio==2.9.0+cu128
[pip3] torchvision==0.24.0+cu128
[pip3] transformers==4.57.3
[pip3] triton==3.5.0
[conda] flashinfer-python         0.5.3                    pypi_0    pypi
[conda] numpy                     2.2.0                    pypi_0    pypi
[conda] nvidia-cublas-cu12        12.8.4.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.8.90                  pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.8.93                  pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.8.90                  pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.10.2.21                pypi_0    pypi
[conda] nvidia-cudnn-frontend     1.16.0                   pypi_0    pypi
[conda] nvidia-cufft-cu12         11.3.3.83                pypi_0    pypi
[conda] nvidia-cufile-cu12        1.13.1.3                 pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.9.90                pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.7.3.90                pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.5.8.93                pypi_0    pypi
[conda] nvidia-cusparselt-cu12    0.7.1                    pypi_0    pypi
[conda] nvidia-cutlass-dsl        4.3.1                    pypi_0    pypi
[conda] nvidia-ml-py              13.580.82                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.27.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.8.93                  pypi_0    pypi
[conda] nvidia-nvshmem-cu12       3.3.20                   pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.8.90                  pypi_0    pypi
[conda] pyzmq                     27.1.0                   pypi_0    pypi
[conda] torch                     2.9.0+cu128              pypi_0    pypi
[conda] torchaudio                2.9.0+cu128              pypi_0    pypi
[conda] torchvision               0.24.0+cu128             pypi_0    pypi
[conda] transformers              4.57.3                   pypi_0    pypi
[conda] triton                    3.5.0                    pypi_0    pypi

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
vLLM Version                 : 0.12.0
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled
GPU Topology:
        GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      144-287 1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

==============================
     Environment Variables
==============================
VLLM_WORKER_MULTIPROC_METHOD=spawn
CUDA_LAUNCH_BLOCKING=1
TORCHDYNAMO_DISABLE=1
TORCH_USE_CUDA_DSA=1
LD_LIBRARY_PATH=/usr/local/cuda-12.8/lib64:
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1

```

</details>

### 🐛 Describe the bug

The error is shown as below:
```
(APIServer pid=6908) INFO 12-04 23:05:25 [api_server.py:1772] vLLM API server version 0.12.0
(APIServer pid=6908) INFO 12-04 23:05:25 [utils.py:253] non-default args: {'model_tag': '/home/nbw/model/Qwen2-0.5B/', 'model': '/home/nbw/model/Qwen2-0.5B/', 'kv_transfer_config': KVTransferConfig(kv_connector='LMCacheConnectorV1', engine_id='823fba11-9ea2-4f1f-902e-9825b65f3377', kv_buffer_device='cuda', kv_buffer_size=1000000000.0, kv_role='kv_both', kv_rank=None, kv_parallel_size=1, kv_ip='127.0.0.1', kv_port=14579, kv_connector_extra_config={}, kv_connector_module_path=None, enable_permute_local_kv=False)}
(APIServer pid=6908) INFO 12-04 23:05:25 [model.py:637] Resolved architecture: Qwen2ForCausalLM
(APIServer pid=6908) INFO 12-04 23:05:25 [model.py:1750] Using max model len 32768
(APIServer pid=6908) INFO 12-04 23:05:25 [scheduler.py:228] Chunked prefill is enabled with max_num_batched_tokens=2048.
(APIServer pid=6908) WARNING 12-04 23:05:25 [vllm.py:896] Turning off hybrid kv cache manager because `--kv-transfer-config` is set. This will reduce the performance of vLLM on LLMs with sliding window attention or Mamba attention. If you are a developer of kv connector, please consider supporting hybrid kv cache manager for your connector by making sure your connector is a subclass of `SupportsHMA` defined in kv_connector/v1/base.py.
(EngineCore_DP0 pid=7130) INFO 12-04 23:05:33 [core.py:93] Initializing a V1 LLM engine (v0.12.0) with config: model='/home/nbw/model/Qwen2-0.5B/', speculative_config=None, tokenizer='/home/nbw/model/Qwen2-0.5B/', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01), seed=0, served_model_name=/home/nbw/model/Qwen2-0.5B/, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer'], 'compile_mm_encoder': False, 'compile_sizes': [], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>}, 'local_cache_dir': None}
(EngineCore_DP0 pid=7130) INFO 12-04 23:05:35 [parallel_state.py:1200] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://109.105.118.170:53521 backend=nccl
(EngineCore_DP0 pid=7130) INFO 12-04 23:05:35 [parallel_state.py:1408] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0
(EngineCore_DP0 pid=7130) INFO 12-04 23:05:36 [gpu_model_runner.py:3467] Starting to load model /home/nbw/model/Qwen2-0.5B/...
(EngineCore_DP0 pid=7130) INFO 12-04 23:05:37 [cuda.py:411] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION']
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:02<00:00,  2.22s/it]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:02<00:00,  2.22s/it]
(EngineCore_DP0 pid=7130)
(EngineCore_DP0 pid=7130) INFO 12-04 23:05:39 [default_loader.py:308] Loading weights took 2.24 seconds
(EngineCore_DP0 pid=7130) INFO 12-04 23:05:40 [gpu_model_runner.py:3549] Model loading took 0.9271 GiB memory and 2.815654 seconds
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843] EngineCore failed to start.
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843] Traceback (most recent call last):
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 834, in run_engine_core
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 610, in __init__
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]     super().__init__(
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 109, in __init__
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]     num_gpu_blocks, num_cpu_blocks, kv_cache_config = self._initialize_kv_caches(
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 235, in _initialize_kv_caches
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]     available_gpu_memory = self.model_executor.determine_available_memory()
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/executor/abstract.py", line 126, in determine_available_memory
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]     return self.collective_rpc("determine_available_memory")
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/executor/uniproc_executor.py", line 75, in collective_rpc
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]     result = run_method(self.driver_worker, method, args, kwargs)
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/serial_utils.py", line 479, in run_method
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]     return func(*args, **kwargs)
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]     return func(*args, **kwargs)
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 324, in determine_available_memory
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]     self.model_runner.profile_run()
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 4364, in profile_run
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]     output = self._dummy_sampler_run(last_hidden_states)
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]     return func(*args, **kwargs)
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 4136, in _dummy_sampler_run
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]     temperature=dummy_tensors(0.5),
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]                 ^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 4133, in <lambda>
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]     dummy_tensors = lambda v: torch.full((num_reqs,), v, device=self.device)
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843] torch.AcceleratorError: CUDA error: unknown error
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843] Search for `cudaErrorUnknown' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(EngineCore_DP0 pid=7130) ERROR 12-04 23:05:42 [core.py:843]
(EngineCore_DP0 pid=7130) Process EngineCore_DP0:
(EngineCore_DP0 pid=7130) Traceback (most recent call last):
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=7130)     self.run()
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=7130)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 847, in run_engine_core
(EngineCore_DP0 pid=7130)     raise e
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 834, in run_engine_core
(EngineCore_DP0 pid=7130)     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=7130)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 610, in __init__
(EngineCore_DP0 pid=7130)     super().__init__(
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 109, in __init__
(EngineCore_DP0 pid=7130)     num_gpu_blocks, num_cpu_blocks, kv_cache_config = self._initialize_kv_caches(
(EngineCore_DP0 pid=7130)                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 235, in _initialize_kv_caches
(EngineCore_DP0 pid=7130)     available_gpu_memory = self.model_executor.determine_available_memory()
(EngineCore_DP0 pid=7130)                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/executor/abstract.py", line 126, in determine_available_memory
(EngineCore_DP0 pid=7130)     return self.collective_rpc("determine_available_memory")
(EngineCore_DP0 pid=7130)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/executor/uniproc_executor.py", line 75, in collective_rpc
(EngineCore_DP0 pid=7130)     result = run_method(self.driver_worker, method, args, kwargs)
(EngineCore_DP0 pid=7130)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/serial_utils.py", line 479, in run_method
(EngineCore_DP0 pid=7130)     return func(*args, **kwargs)
(EngineCore_DP0 pid=7130)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(EngineCore_DP0 pid=7130)     return func(*args, **kwargs)
(EngineCore_DP0 pid=7130)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 324, in determine_available_memory
(EngineCore_DP0 pid=7130)     self.model_runner.profile_run()
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 4364, in profile_run
(EngineCore_DP0 pid=7130)     output = self._dummy_sampler_run(last_hidden_states)
(EngineCore_DP0 pid=7130)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(EngineCore_DP0 pid=7130)     return func(*args, **kwargs)
(EngineCore_DP0 pid=7130)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 4136, in _dummy_sampler_run
(EngineCore_DP0 pid=7130)     temperature=dummy_tensors(0.5),
(EngineCore_DP0 pid=7130)                 ^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 4133, in <lambda>
(EngineCore_DP0 pid=7130)     dummy_tensors = lambda v: torch.full((num_reqs,), v, device=self.device)
(EngineCore_DP0 pid=7130)                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=7130) torch.AcceleratorError: CUDA error: unknown error
(EngineCore_DP0 pid=7130) Search for `cudaErrorUnknown' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
(EngineCore_DP0 pid=7130) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
(EngineCore_DP0 pid=7130)
[rank0]:[W1204 23:05:43.959614557 ProcessGroupNCCL.cpp:1524] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
(APIServer pid=6908) Traceback (most recent call last):
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/bin/vllm", line 7, in <module>
(APIServer pid=6908)     sys.exit(main())
(APIServer pid=6908)              ^^^^^^
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/entrypoints/cli/main.py", line 73, in main
(APIServer pid=6908)     args.dispatch_function(args)
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/entrypoints/cli/serve.py", line 60, in cmd
(APIServer pid=6908)     uvloop.run(run_server(args))
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/uvloop/__init__.py", line 96, in run
(APIServer pid=6908)     return __asyncio.run(
(APIServer pid=6908)            ^^^^^^^^^^^^^^
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/asyncio/runners.py", line 195, in run
(APIServer pid=6908)     return runner.run(main)
(APIServer pid=6908)            ^^^^^^^^^^^^^^^^
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/asyncio/runners.py", line 118, in run
(APIServer pid=6908)     return self._loop.run_until_complete(task)
(APIServer pid=6908)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=6908)   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/uvloop/__init__.py", line 48, in wrapper
(APIServer pid=6908)     return await main
(APIServer pid=6908)            ^^^^^^^^^^
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1819, in run_server
(APIServer pid=6908)     await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 1838, in run_server_worker
(APIServer pid=6908)     async with build_async_engine_client(
(APIServer pid=6908)                ^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/contextlib.py", line 210, in __aenter__
(APIServer pid=6908)     return await anext(self.gen)
(APIServer pid=6908)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 183, in build_async_engine_client
(APIServer pid=6908)     async with build_async_engine_client_from_engine_args(
(APIServer pid=6908)                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/contextlib.py", line 210, in __aenter__
(APIServer pid=6908)     return await anext(self.gen)
(APIServer pid=6908)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/entrypoints/openai/api_server.py", line 224, in build_async_engine_client_from_engine_args
(APIServer pid=6908)     async_llm = AsyncLLM.from_vllm_config(
(APIServer pid=6908)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 223, in from_vllm_config
(APIServer pid=6908)     return cls(
(APIServer pid=6908)            ^^^^
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 134, in __init__
(APIServer pid=6908)     self.engine_core = EngineCoreClient.make_async_mp_client(
(APIServer pid=6908)                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 121, in make_async_mp_client
(APIServer pid=6908)     return AsyncMPClient(*client_args)
(APIServer pid=6908)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 810, in __init__
(APIServer pid=6908)     super().__init__(
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 471, in __init__
(APIServer pid=6908)     with launch_core_engines(vllm_config, executor_class, log_stats) as (
(APIServer pid=6908)          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/contextlib.py", line 144, in __exit__
(APIServer pid=6908)     next(self.gen)
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/utils.py", line 903, in launch_core_engines
(APIServer pid=6908)     wait_for_engine_startup(
(APIServer pid=6908)   File "/root/anaconda3/envs/vllm-128/lib/python3.12/site-packages/vllm/v1/engine/utils.py", line 960, in wait_for_engine_startup
(APIServer pid=6908)     raise RuntimeError(
(APIServer pid=6908) RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
```

Besides, my config is shown as below:
**My NVIDIA Driver version:**
```
(vllm-128) root@dpss170-NF5280:~# nvidia-smi
Thu Dec  4 23:22:19 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.124.06             Driver Version: 570.124.06     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L20                     Off |   00000000:C6:00.0 Off |                    0 |
| N/A   37C    P8             27W /  350W |      14MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            3972      G   /usr/lib/xorg/Xorg                        4MiB |
+-----------------------------------------------------------------------------------------+
```

**My CUDA version:**
```
(vllm-128) root@dpss170-NF5280:~# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Fri_Feb_21_20:23:50_PST_2025
Cuda compilation tools, release 12.8, V12.8.93
Build cuda_12.8.r12.8/compiler.35583870_0
```

**My cudnn version:**
```
(vllm-128) root@dpss170-NF5280:~# cat /usr/include/x86_64-linux-gnu/cudnn_version.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 9
#define CUDNN_MINOR 16
#define CUDNN_PATCHLEVEL 0
--
#define CUDNN_VERSION (CUDNN_MAJOR * 10000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

/* cannot use constexpr here since this is a C-only file */

```

**the conda env is:**
```
(vllm-128) root@dpss170-NF5280:~# conda list
# packages in environment at /root/anaconda3/envs/vllm-128:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
aiofile                   3.9.0                    pypi_0    pypi
aiofiles                  25.1.0                   pypi_0    pypi
aiohappyeyeballs          2.6.1                    pypi_0    pypi
aiohttp                   3.13.2                   pypi_0    pypi
aiosignal                 1.4.0                    pypi_0    pypi
airportsdata              20250909                 pypi_0    pypi
annotated-doc             0.0.4                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
anthropic                 0.71.0                   pypi_0    pypi
anyio                     4.12.0                   pypi_0    pypi
apache-tvm-ffi            0.1.4                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
attrs                     25.4.0                   pypi_0    pypi
awscrt                    0.29.2                   pypi_0    pypi
blake3                    1.0.8                    pypi_0    pypi
bzip2                     1.0.8                h5eee18b_6
ca-certificates           2025.12.2            h06a4308_0
cachetools                6.2.2                    pypi_0    pypi
caio                      0.9.24                   pypi_0    pypi
cbor2                     5.7.1                    pypi_0    pypi
certifi                   2025.11.12               pypi_0    pypi
charset-normalizer        3.4.4                    pypi_0    pypi
click                     8.2.1                    pypi_0    pypi
cloudpickle               3.1.2                    pypi_0    pypi
compressed-tensors        0.12.2                   pypi_0    pypi
cuda-bindings             13.0.3                   pypi_0    pypi
cuda-pathfinder           1.3.2                    pypi_0    pypi
cuda-python               13.0.3                   pypi_0    pypi
cufile-python             0.2.0                    pypi_0    pypi
cupy-cuda12x              13.6.0                   pypi_0    pypi
depyf                     0.20.0                   pypi_0    pypi
dill                      0.4.0                    pypi_0    pypi
diskcache                 5.6.3                    pypi_0    pypi
distro                    1.9.0                    pypi_0    pypi
dnspython                 2.8.0                    pypi_0    pypi
docstring-parser          0.17.0                   pypi_0    pypi
einops                    0.8.1                    pypi_0    pypi
email-validator           2.3.0                    pypi_0    pypi
expat                     2.7.3                h3385a95_0
fastapi                   0.123.5                  pypi_0    pypi
fastapi-cli               0.0.16                   pypi_0    pypi
fastapi-cloud-cli         0.5.2                    pypi_0    pypi
fastar                    0.8.0                    pypi_0    pypi
fastrlock                 0.8.3                    pypi_0    pypi
filelock                  3.19.1                   pypi_0    pypi
flashinfer-python         0.5.3                    pypi_0    pypi
frozenlist                1.8.0                    pypi_0    pypi
fsspec                    2025.9.0                 pypi_0    pypi
gguf                      0.17.1                   pypi_0    pypi
googleapis-common-protos  1.72.0                   pypi_0    pypi
grpcio                    1.76.0                   pypi_0    pypi
h11                       0.16.0                   pypi_0    pypi
hf-xet                    1.2.0                    pypi_0    pypi
httpcore                  1.0.9                    pypi_0    pypi
httptools                 0.7.1                    pypi_0    pypi
httpx                     0.28.1                   pypi_0    pypi
huggingface-hub           0.36.0                   pypi_0    pypi
idna                      3.11                     pypi_0    pypi
importlib-metadata        8.7.0                    pypi_0    pypi
infinistore               0.2.35                   pypi_0    pypi
interegular               0.3.3                    pypi_0    pypi
jinja2                    3.1.6                    pypi_0    pypi
jiter                     0.12.0                   pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
jsonschema                4.25.1                   pypi_0    pypi
jsonschema-specifications 2025.9.1                 pypi_0    pypi
lark                      1.2.2                    pypi_0    pypi
ld_impl_linux-64          2.44                 h153f514_2
libffi                    3.4.4                h6a678d5_1
libgcc                    15.2.0               h69a1729_7
libgcc-ng                 15.2.0               h166f726_7
libgomp                   15.2.0               h4751f2c_7
libstdcxx                 15.2.0               h39759b7_7
libstdcxx-ng              15.2.0               hc03a8fd_7
libuuid                   1.41.5               h5eee18b_0
libxcb                    1.17.0               h9b100fa_0
libzlib                   1.3.1                hb25bd0a_0
llguidance                1.3.0                    pypi_0    pypi
llvmlite                  0.44.0                   pypi_0    pypi
lm-format-enforcer        0.11.3                   pypi_0    pypi
lmcache                   0.3.10                   pypi_0    pypi
loguru                    0.7.3                    pypi_0    pypi
markdown-it-py            4.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mistral-common            1.8.6                    pypi_0    pypi
model-hosting-container-standards 0.1.9                    pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.1.2                    pypi_0    pypi
msgspec                   0.20.0                   pypi_0    pypi
multidict                 6.7.0                    pypi_0    pypi
ncurses                   6.5                  h7934f7d_0
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.5                      pypi_0    pypi
ninja                     1.13.0                   pypi_0    pypi
nixl                      0.8.0                    pypi_0    pypi
nixl-cu12                 0.8.0                    pypi_0    pypi
numba                     0.61.2                   pypi_0    pypi
numpy                     2.2.0                    pypi_0    pypi
nvidia-cublas-cu12        12.8.4.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.8.90                  pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.8.93                  pypi_0    pypi
nvidia-cuda-runtime-cu12  12.8.90                  pypi_0    pypi
nvidia-cudnn-cu12         9.10.2.21                pypi_0    pypi
nvidia-cudnn-frontend     1.16.0                   pypi_0    pypi
nvidia-cufft-cu12         11.3.3.83                pypi_0    pypi
nvidia-cufile-cu12        1.13.1.3                 pypi_0    pypi
nvidia-curand-cu12        10.3.9.90                pypi_0    pypi
nvidia-cusolver-cu12      11.7.3.90                pypi_0    pypi
nvidia-cusparse-cu12      12.5.8.93                pypi_0    pypi
nvidia-cusparselt-cu12    0.7.1                    pypi_0    pypi
nvidia-cutlass-dsl        4.3.1                    pypi_0    pypi
nvidia-ml-py              13.580.82                pypi_0    pypi
nvidia-nccl-cu12          2.27.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.8.93                  pypi_0    pypi
nvidia-nvshmem-cu12       3.3.20                   pypi_0    pypi
nvidia-nvtx-cu12          12.8.90                  pypi_0    pypi
nvtx                      0.2.14                   pypi_0    pypi
openai                    2.8.1                    pypi_0    pypi
openai-harmony            0.0.8                    pypi_0    pypi
opencv-python-headless    4.12.0.88                pypi_0    pypi
openssl                   3.0.18               hd6dcaed_0
opentelemetry-api         1.38.0                   pypi_0    pypi
opentelemetry-exporter-otlp 1.38.0                   pypi_0    pypi
opentelemetry-exporter-otlp-proto-common 1.38.0                   pypi_0    pypi
opentelemetry-exporter-otlp-proto-grpc 1.38.0                   pypi_0    pypi
opentelemetry-exporter-otlp-proto-http 1.38.0                   pypi_0    pypi
opentelemetry-proto       1.38.0                   pypi_0    pypi
opentelemetry-sdk         1.38.0                   pypi_0    pypi
opentelemetry-semantic-conventions 0.59b0                   pypi_0    pypi
opentelemetry-semantic-conventions-ai 0.4.13                   pypi_0    pypi
outlines                  0.1.11                   pypi_0    pypi
outlines-core             0.2.11                   pypi_0    pypi
packaging                 25.0                     pypi_0    pypi
partial-json-parser       0.2.1.1.post7            pypi_0    pypi
pillow                    11.3.0                   pypi_0    pypi
pip                       25.3               pyhc872135_0
prometheus-client         0.23.1                   pypi_0    pypi
prometheus-fastapi-instrumentator 7.1.0                    pypi_0    pypi
propcache                 0.4.1                    pypi_0    pypi
protobuf                  6.33.1                   pypi_0    pypi
psutil                    7.1.3                    pypi_0    pypi
pthread-stubs             0.3                  h0ce48e5_1
py-cpuinfo                9.0.0                    pypi_0    pypi
pybase64                  1.4.2                    pypi_0    pypi
pybind11                  3.0.1                    pypi_0    pypi
pycountry                 24.6.1                   pypi_0    pypi
pydantic                  2.12.5                   pypi_0    pypi
pydantic-core             2.41.5                   pypi_0    pypi
pydantic-extra-types      2.10.6                   pypi_0    pypi
pygments                  2.19.2                   pypi_0    pypi
python                    3.12.9               h5148396_0
python-dotenv             1.2.1                    pypi_0    pypi
python-json-logger        4.0.0                    pypi_0    pypi
python-multipart          0.0.20                   pypi_0    pypi
pyyaml                    6.0.3                    pypi_0    pypi
pyzmq                     27.1.0                   pypi_0    pypi
ray                       2.52.1                   pypi_0    pypi
readline                  8.3                  hc2a1206_0
redis                     7.1.0                    pypi_0    pypi
referencing               0.37.0                   pypi_0    pypi
regex                     2025.11.3                pypi_0    pypi
requests                  2.32.5                   pypi_0    pypi
rich                      14.2.0                   pypi_0    pypi
rich-toolkit              0.17.0                   pypi_0    pypi
rignore                   0.7.6                    pypi_0    pypi
rpds-py                   0.30.0                   pypi_0    pypi
safetensors               0.7.0                    pypi_0    pypi
scipy                     1.16.3                   pypi_0    pypi
sentencepiece             0.2.1                    pypi_0    pypi
sentry-sdk                2.46.0                   pypi_0    pypi
setproctitle              1.3.7                    pypi_0    pypi
setuptools                79.0.1                   pypi_0    pypi
setuptools-scm            9.2.2                    pypi_0    pypi
shellingham               1.5.4                    pypi_0    pypi
six                       1.17.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
sqlite                    3.51.0               h2a70700_0
starlette                 0.50.0                   pypi_0    pypi
supervisor                4.3.0                    pypi_0    pypi
sympy                     1.14.0                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tiktoken                  0.12.0                   pypi_0    pypi
tk                        8.6.15               h54e0aa7_0
tokenizers                0.22.1                   pypi_0    pypi
torch                     2.9.0+cu128              pypi_0    pypi
torchaudio                2.9.0+cu128              pypi_0    pypi
torchvision               0.24.0+cu128             pypi_0    pypi
tqdm                      4.67.1                   pypi_0    pypi
transformers              4.57.3                   pypi_0    pypi
triton                    3.5.0                    pypi_0    pypi
typer                     0.20.0                   pypi_0    pypi
typing-extensions         4.15.0                   pypi_0    pypi
typing-inspection         0.4.2                    pypi_0    pypi
tzdata                    2025b                h04d1e81_0
urllib3                   2.5.0                    pypi_0    pypi
uvicorn                   0.38.0                   pypi_0    pypi
uvloop                    0.22.1                   pypi_0    pypi
vllm                      0.12.0                   pypi_0    pypi
watchfiles                1.1.1                    pypi_0    pypi
websockets                15.0.1                   pypi_0    pypi
wheel                     0.45.1          py312h06a4308_0
xformers                  0.0.33.post1             pypi_0    pypi
xgrammar                  0.1.27                   pypi_0    pypi
xorg-libx11               1.8.12               h9b100fa_1
xorg-libxau               1.0.12               h9b100fa_0
xorg-libxdmcp             1.1.5                h9b100fa_0
xorg-xorgproto            2024.1               h5eee18b_1
xxhash                    3.5.0                    pypi_0    pypi
xz                        5.6.4                h5eee18b_1
yarl                      1.22.0                   pypi_0    pypi
zipp                      3.23.0                   pypi_0    pypi
zlib                      1.3.1                hb25bd0a_0
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by niebowen666** [comment]
Anybody could help me on this error? Thanks very much!

**Comment by k4rth33k** [comment]
@niebowen666 @Dpsley 
Looks like this issue is fixed already. Couldn't replicate it on stable vLLM.
