### ISSUE TITLE
[Bug]: RuntimeError: bmm_fp8_internal_cublaslt failed when deploying

### ISSUE THREAD

**Issue by Austin-Liang** [vllm-project/vllm#30324]
### Your current environment

==============================
        System Info
==============================
OS                           : Ubuntu 24.04.3 LTS (aarch64)
GCC version                  : (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Clang version                : Could not collect
CMake version                : version 3.28.3
Libc version                 : glibc-2.39

==============================
       PyTorch Info
==============================
PyTorch version              : 2.9.0+cu129
Is debug build               : False
CUDA used to build PyTorch   : 12.9
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.3 (main, Nov  6 2025, 13:44:16) [GCC 13.3.0] (64-bit runtime)
Python platform              : Linux-6.11.0-1016-nvidia-aarch64-with-glibc2.39

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : 13.0.88
CUDA_MODULE_LOADING set to   : 
GPU models and configuration : GPU 0: NVIDIA GB10
Nvidia driver version        : 580.95.05
cuDNN version                : Could not collect
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture：                                aarch64
CPU op-mode(s)：                        64-bit
Byte Order:                           Little Endian
CPU(s):                               20
On-line CPU(s) list:                  0-19
Vendor ID：                        ARM
Model name:                           Cortex-X925
Model：                                1
Thread(s) per core：                      1
Core(s) per socket：                      10
Socket(s):                            1
Stepping：                                r0p1
CPU(s) scaling MHz:                   110%
CPU max MHz:                          4004.0000
CPU min MHz:                          1378.0000
BogoMIPS:                             2000.00
Flags:                                fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm sb paca pacg dcpodp sve2 sveaes svepmull svebitperm svesha3 svesm4 flagm2 frint svei8mm svebf16 i8mm bf16 dgh bti ecv afp wfxt
Model name:                           Cortex-A725
Model：                                1
Thread(s) per core：                      1
Core(s) per socket：                      10
Socket(s):                            1
Stepping：                                r0p1
CPU(s) scaling MHz:                   107%
CPU max MHz:                          2860.0000
CPU min MHz:                          338.0000
BogoMIPS:                             2000.00
Flags:                                fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm sb paca pacg dcpodp sve2 sveaes svepmull svebitperm svesha3 svesm4 flagm2 frint svei8mm svebf16 i8mm bf16 dgh bti ecv afp wfxt
L1d cache：                            1.3 MiB (20 instances)
L1i cache：                            1.3 MiB (20 instances)
L2 cache：                             25 MiB (20 instances)
L3 cache：                             24 MiB (2 instances)
NUMA node(s)：                           1
NUMA node0 CPU(s)：                   0-19
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; __user pointer sanitization
Vulnerability Spectre v2:             Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

==============================
Versions of relevant libraries
==============================
[pip3] flashinfer-python==0.5.3
[pip3] numpy==2.2.6
[pip3] nvidia-cublas-cu12==12.9.1.4
[pip3] nvidia-cuda-cupti-cu12==12.9.79
[pip3] nvidia-cuda-nvrtc-cu12==12.9.86
[pip3] nvidia-cuda-runtime-cu12==12.9.79
[pip3] nvidia-cudnn-cu12==9.10.2.21
[pip3] nvidia-cudnn-frontend==1.16.0
[pip3] nvidia-cufft-cu12==11.4.1.4
[pip3] nvidia-cufile-cu12==1.14.1.1
[pip3] nvidia-curand-cu12==10.3.10.19
[pip3] nvidia-cusolver-cu12==11.7.5.82
[pip3] nvidia-cusparse-cu12==12.5.10.65
[pip3] nvidia-cusparselt-cu12==0.7.1
[pip3] nvidia-cutlass-dsl==4.3.2
[pip3] nvidia-ml-py==13.590.44
[pip3] nvidia-nccl-cu12==2.27.5
[pip3] nvidia-nvjitlink-cu12==12.9.86
[pip3] nvidia-nvshmem-cu12==3.3.20
[pip3] nvidia-nvtx-cu12==12.9.79
[pip3] pyzmq==27.1.0
[pip3] torch==2.9.0+cu129
[pip3] torchaudio==2.9.0
[pip3] torchvision==0.24.0
[pip3] transformers==4.57.3
[pip3] triton==3.5.0
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
vLLM Version                 : 0.12.0
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled
GPU Topology:
  	GPU0	NIC0	NIC1	NIC2	NIC3	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NODE	NODE	NODE	NODE	0-19	0		N/A
NIC0	NODE	 X 	PIX	NODE	NODE				
NIC1	NODE	PIX	 X 	NODE	NODE				
NIC2	NODE	NODE	NODE	 X 	PIX				
NIC3	NODE	NODE	NODE	PIX	 X 				

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: rocep1s0f0
  NIC1: rocep1s0f1
  NIC2: roceP2p1s0f0
  NIC3: roceP2p1s0f1

==============================
     Environment Variables
==============================
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1

### 🐛 Describe the bug

I am attempting to deploy the mistralai/Ministral-3-14B-Instruct-2512 model on an ASUS Ascent GX10 server using vLLM 0.12.0.

The Hugging Face model card (https://huggingface.co/mistralai/Ministral-3-14B-Instruct-2512) recommends using vLLM 0.12.0, and I have explicitly verified that the installed mistral_common package is version 1.8.6.

The error logs are as follows:
(vllm-env) llmTester@gx10-0ea2:~/vllm-env/scripts$ python run_inference.py
INFO 12-09 15:59:21 [utils.py:253] non-default args: {'tokenizer_mode': 'mistral', 'trust_remote_code': True, 'load_format': 'mistral', 'config_format': 'mistral', 'dtype': 'bfloat16', 'seed': None, 'max_model_len': 4096, 'gpu_memory_utilization': 0.94, 'max_num_batched_tokens': 4096, 'max_num_seqs': 1, 'disable_log_stats': True, 'enforce_eager': True, 'model': '/home/llmTester/models/ministral3_14b_instruct'}
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
WARNING 12-09 15:59:21 [arg_utils.py:1175] `seed=None` is equivalent to `seed=0` in V1 Engine. You will no longer be allowed to pass `None` in v0.13.
INFO 12-09 15:59:21 [model.py:637] Resolved architecture: PixtralForConditionalGeneration
INFO 12-09 15:59:21 [model.py:1750] Using max model len 4096
INFO 12-09 15:59:21 [scheduler.py:228] Chunked prefill is enabled with max_num_batched_tokens=4096.
WARNING 12-09 15:59:21 [vllm.py:601] Enforce eager set, overriding optimization level to -O0
INFO 12-09 15:59:21 [vllm.py:707] Cudagraph is disabled under eager mode
[2025-12-09 15:59:22] INFO tekken.py:187: Non special vocabulary size is 130072 with 1000 special tokens.
[2025-12-09 15:59:22] INFO tekken.py:187: Non special vocabulary size is 130072 with 1000 special tokens.
(EngineCore_DP0 pid=12178) INFO 12-09 15:59:22 [core.py:93] Initializing a V1 LLM engine (v0.12.0) with config: model='/home/llmTester/models/ministral3_14b_instruct', speculative_config=None, tokenizer='/home/llmTester/models/ministral3_14b_instruct', skip_tokenizer_init=False, tokenizer_mode=mistral, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=mistral, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=fp8, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01), seed=0, served_model_name=/home/llmTester/models/ministral3_14b_instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'splitting_ops': [], 'compile_mm_encoder': False, 'compile_sizes': [], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': [], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 0, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>}, 'local_cache_dir': None}
(EngineCore_DP0 pid=12178) /home/llmTester/vllm-env/lib/python3.12/site-packages/torch/cuda/__init__.py:283: UserWarning: 
(EngineCore_DP0 pid=12178)     Found GPU0 NVIDIA GB10 which is of cuda capability 12.1.
(EngineCore_DP0 pid=12178)     Minimum and Maximum cuda capability supported by this version of PyTorch is
(EngineCore_DP0 pid=12178)     (8.0) - (12.0)
(EngineCore_DP0 pid=12178)     
(EngineCore_DP0 pid=12178)   warnings.warn(
(EngineCore_DP0 pid=12178) INFO 12-09 15:59:23 [parallel_state.py:1200] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.161.231.186:54477 backend=nccl
(EngineCore_DP0 pid=12178) INFO 12-09 15:59:23 [parallel_state.py:1408] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0
(EngineCore_DP0 pid=12178) INFO 12-09 15:59:24 [gpu_model_runner.py:3467] Starting to load model /home/llmTester/models/ministral3_14b_instruct...
(EngineCore_DP0 pid=12178) WARNING 12-09 15:59:24 [vllm.py:608] Inductor compilation was disabled by user settings,Optimizations settings that are only active duringInductor compilation will be ignored.
(EngineCore_DP0 pid=12178) INFO 12-09 15:59:24 [vllm.py:707] Cudagraph is disabled under eager mode
(EngineCore_DP0 pid=12178) INFO 12-09 15:59:24 [cuda.py:411] Using FLASH_ATTN attention backend out of potential backends: ['FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION']
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [01:24<00:00, 84.36s/it]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [01:24<00:00, 84.36s/it]
(EngineCore_DP0 pid=12178) 
(EngineCore_DP0 pid=12178) INFO 12-09 16:00:50 [default_loader.py:308] Loading weights took 84.86 seconds
(EngineCore_DP0 pid=12178) INFO 12-09 16:00:51 [gpu_model_runner.py:3549] Model loading took 14.7101 GiB memory and 87.063865 seconds
(EngineCore_DP0 pid=12178) INFO 12-09 16:00:51 [gpu_model_runner.py:4306] Encoder cache will be initialized with a budget of 4096 tokens, and profiled with 1 image items of the maximum feature size.
(EngineCore_DP0 pid=12178) WARNING 12-09 16:00:51 [processing.py:1153] PixtralProcessorAdapter did not return `BatchFeature`. Make sure to match the behaviour of `ProcessorMixin` when implementing custom processors.
(EngineCore_DP0 pid=12178) INFO 12-09 16:00:55 [gpu_worker.py:359] Available KV cache memory: 95.43 GiB
(EngineCore_DP0 pid=12178) INFO 12-09 16:00:55 [kv_cache_utils.py:1286] GPU KV cache size: 625,408 tokens
(EngineCore_DP0 pid=12178) INFO 12-09 16:00:55 [kv_cache_utils.py:1291] Maximum concurrency for 4,096 tokens per request: 152.69x
(EngineCore_DP0 pid=12178) 2025-12-09 16:01:03,591 - INFO - autotuner.py:256 - flashinfer.jit: [Autotuner]: Autotuning process starts ...
(EngineCore_DP0 pid=12178) 2025-12-09 16:01:05,084 - INFO - autotuner.py:262 - flashinfer.jit: [Autotuner]: Autotuning process ends
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843] EngineCore failed to start.
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843] Traceback (most recent call last):
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 834, in run_engine_core
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 610, in __init__
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     super().__init__(
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 109, in __init__
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     num_gpu_blocks, num_cpu_blocks, kv_cache_config = self._initialize_kv_caches(
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 251, in _initialize_kv_caches
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     self.model_executor.initialize_from_config(kv_cache_configs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/executor/abstract.py", line 116, in initialize_from_config
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     self.collective_rpc("compile_or_warm_up_model")
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/executor/uniproc_executor.py", line 75, in collective_rpc
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     result = run_method(self.driver_worker, method, args, kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/serial_utils.py", line 479, in run_method
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return func(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 423, in compile_or_warm_up_model
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     kernel_warmup(self)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/warmup/kernel_warmup.py", line 41, in kernel_warmup
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     flashinfer_autotune(worker.model_runner)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/warmup/kernel_warmup.py", line 94, in flashinfer_autotune
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     runner._dummy_run(
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return func(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 4071, in _dummy_run
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     outputs = self.model(
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]               ^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return self._call_impl(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return forward_call(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/models/pixtral.py", line 495, in forward
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     hidden_states = self.language_model.model(
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/compilation/decorators.py", line 360, in __call__
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return self.forward(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 440, in forward
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     hidden_states, residual = layer(positions, hidden_states, residual)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return self._call_impl(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return forward_call(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 346, in forward
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     hidden_states = self.self_attn(positions=positions, hidden_states=hidden_states)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return self._call_impl(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return forward_call(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 242, in forward
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     qkv, _ = self.qkv_proj(hidden_states)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return self._call_impl(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return forward_call(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/layers/linear.py", line 565, in forward
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     output_parallel = self.quant_method.apply(self, input_, bias)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/layers/quantization/fp8.py", line 638, in apply
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return self.fp8_linear.apply(
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/layers/quantization/utils/w8a8_utils.py", line 484, in apply
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return w8a8_scaled_mm_func(
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/layers/quantization/utils/w8a8_utils.py", line 176, in flashinfer_w8a8_scaled_mm
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return flashinfer_scaled_fp8_mm(
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/utils/flashinfer.py", line 489, in flashinfer_scaled_fp8_mm
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     output = bmm_fp8(
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]              ^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/_library/custom_ops.py", line 676, in __call__
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return self._opoverload(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/_ops.py", line 841, in __call__
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return self._op(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/_library/custom_ops.py", line 343, in backend_impl
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     result = self._backend_fns[device_type](*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/_compile.py", line 53, in inner
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return disable_fn(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 1044, in _fn
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return fn(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/_library/custom_ops.py", line 376, in wrapped_fn
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return fn(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/utils/flashinfer.py", line 426, in bmm_fp8
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return bmm_fp8_(A, B, A_scale, B_scale, dtype, None, backend)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/flashinfer/utils.py", line 1164, in wrapper
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return func(*args, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/flashinfer/gemm/gemm_base.py", line 2182, in bmm_fp8
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     fp8_gemm_sm100(A, B, A_scale, B_scale, out, workspace_buffer, backends)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/flashinfer/gemm/gemm_base.py", line 396, in fp8_gemm_sm100
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     runner, tactic = tuner.choose_one(
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]                      ^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/flashinfer/autotuner.py", line 477, in choose_one
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     r(tensors, tactic=-1, do_preparation=True, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/flashinfer/autotuner.py", line 217, in __call__
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     return self.forward(inputs, **kwargs)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/flashinfer/gemm/gemm_base.py", line 120, in forward
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     module.bmm_fp8(
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "python/tvm_ffi/cython/function.pxi", line 923, in tvm_ffi.core.Function.__call__
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "<unknown>", line 0, in __tvm_ffi_bmm_fp8
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/flashinfer/data/csrc/bmm_fp8.cu", line 57, in bmm_fp8(tvm::ffi::TensorView, tvm::ffi::TensorView, tvm::ffi::TensorView, tvm::ffi::TensorView, tvm::ffi::TensorView, tvm::ffi::TensorView, int64_t)::<lambda()>::<lambda()>::<lambda()>::<lambda()>::<lambda()>::<lambda()>
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     TVM_FFI_ICHECK(status == CUBLAS_STATUS_SUCCESS)
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843]     
(EngineCore_DP0 pid=12178) ERROR 12-09 16:01:05 [core.py:843] RuntimeError: Check failed: (status == CUBLAS_STATUS_SUCCESS) is false: bmm_fp8_internal_cublaslt failed: the library was not initialized
(EngineCore_DP0 pid=12178) Process EngineCore_DP0:
(EngineCore_DP0 pid=12178) Traceback (most recent call last):
(EngineCore_DP0 pid=12178)   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=12178)     self.run()
(EngineCore_DP0 pid=12178)   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=12178)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 847, in run_engine_core
(EngineCore_DP0 pid=12178)     raise e
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 834, in run_engine_core
(EngineCore_DP0 pid=12178)     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=12178)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 610, in __init__
(EngineCore_DP0 pid=12178)     super().__init__(
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 109, in __init__
(EngineCore_DP0 pid=12178)     num_gpu_blocks, num_cpu_blocks, kv_cache_config = self._initialize_kv_caches(
(EngineCore_DP0 pid=12178)                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 251, in _initialize_kv_caches
(EngineCore_DP0 pid=12178)     self.model_executor.initialize_from_config(kv_cache_configs)
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/executor/abstract.py", line 116, in initialize_from_config
(EngineCore_DP0 pid=12178)     self.collective_rpc("compile_or_warm_up_model")
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/executor/uniproc_executor.py", line 75, in collective_rpc
(EngineCore_DP0 pid=12178)     result = run_method(self.driver_worker, method, args, kwargs)
(EngineCore_DP0 pid=12178)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/serial_utils.py", line 479, in run_method
(EngineCore_DP0 pid=12178)     return func(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 423, in compile_or_warm_up_model
(EngineCore_DP0 pid=12178)     kernel_warmup(self)
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/warmup/kernel_warmup.py", line 41, in kernel_warmup
(EngineCore_DP0 pid=12178)     flashinfer_autotune(worker.model_runner)
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/warmup/kernel_warmup.py", line 94, in flashinfer_autotune
(EngineCore_DP0 pid=12178)     runner._dummy_run(
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(EngineCore_DP0 pid=12178)     return func(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 4071, in _dummy_run
(EngineCore_DP0 pid=12178)     outputs = self.model(
(EngineCore_DP0 pid=12178)               ^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
(EngineCore_DP0 pid=12178)     return self._call_impl(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
(EngineCore_DP0 pid=12178)     return forward_call(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/models/pixtral.py", line 495, in forward
(EngineCore_DP0 pid=12178)     hidden_states = self.language_model.model(
(EngineCore_DP0 pid=12178)                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/compilation/decorators.py", line 360, in __call__
(EngineCore_DP0 pid=12178)     return self.forward(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 440, in forward
(EngineCore_DP0 pid=12178)     hidden_states, residual = layer(positions, hidden_states, residual)
(EngineCore_DP0 pid=12178)                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
(EngineCore_DP0 pid=12178)     return self._call_impl(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
(EngineCore_DP0 pid=12178)     return forward_call(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 346, in forward
(EngineCore_DP0 pid=12178)     hidden_states = self.self_attn(positions=positions, hidden_states=hidden_states)
(EngineCore_DP0 pid=12178)                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
(EngineCore_DP0 pid=12178)     return self._call_impl(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
(EngineCore_DP0 pid=12178)     return forward_call(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/models/llama.py", line 242, in forward
(EngineCore_DP0 pid=12178)     qkv, _ = self.qkv_proj(hidden_states)
(EngineCore_DP0 pid=12178)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
(EngineCore_DP0 pid=12178)     return self._call_impl(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
(EngineCore_DP0 pid=12178)     return forward_call(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/layers/linear.py", line 565, in forward
(EngineCore_DP0 pid=12178)     output_parallel = self.quant_method.apply(self, input_, bias)
(EngineCore_DP0 pid=12178)                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/layers/quantization/fp8.py", line 638, in apply
(EngineCore_DP0 pid=12178)     return self.fp8_linear.apply(
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/layers/quantization/utils/w8a8_utils.py", line 484, in apply
(EngineCore_DP0 pid=12178)     return w8a8_scaled_mm_func(
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/model_executor/layers/quantization/utils/w8a8_utils.py", line 176, in flashinfer_w8a8_scaled_mm
(EngineCore_DP0 pid=12178)     return flashinfer_scaled_fp8_mm(
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/utils/flashinfer.py", line 489, in flashinfer_scaled_fp8_mm
(EngineCore_DP0 pid=12178)     output = bmm_fp8(
(EngineCore_DP0 pid=12178)              ^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/_library/custom_ops.py", line 676, in __call__
(EngineCore_DP0 pid=12178)     return self._opoverload(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/_ops.py", line 841, in __call__
(EngineCore_DP0 pid=12178)     return self._op(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/_library/custom_ops.py", line 343, in backend_impl
(EngineCore_DP0 pid=12178)     result = self._backend_fns[device_type](*args, **kwargs)
(EngineCore_DP0 pid=12178)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/_compile.py", line 53, in inner
(EngineCore_DP0 pid=12178)     return disable_fn(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 1044, in _fn
(EngineCore_DP0 pid=12178)     return fn(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/torch/_library/custom_ops.py", line 376, in wrapped_fn
(EngineCore_DP0 pid=12178)     return fn(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/utils/flashinfer.py", line 426, in bmm_fp8
(EngineCore_DP0 pid=12178)     return bmm_fp8_(A, B, A_scale, B_scale, dtype, None, backend)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/flashinfer/utils.py", line 1164, in wrapper
(EngineCore_DP0 pid=12178)     return func(*args, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/flashinfer/gemm/gemm_base.py", line 2182, in bmm_fp8
(EngineCore_DP0 pid=12178)     fp8_gemm_sm100(A, B, A_scale, B_scale, out, workspace_buffer, backends)
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/flashinfer/gemm/gemm_base.py", line 396, in fp8_gemm_sm100
(EngineCore_DP0 pid=12178)     runner, tactic = tuner.choose_one(
(EngineCore_DP0 pid=12178)                      ^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/flashinfer/autotuner.py", line 477, in choose_one
(EngineCore_DP0 pid=12178)     r(tensors, tactic=-1, do_preparation=True, **kwargs)
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/flashinfer/autotuner.py", line 217, in __call__
(EngineCore_DP0 pid=12178)     return self.forward(inputs, **kwargs)
(EngineCore_DP0 pid=12178)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/flashinfer/gemm/gemm_base.py", line 120, in forward
(EngineCore_DP0 pid=12178)     module.bmm_fp8(
(EngineCore_DP0 pid=12178)   File "python/tvm_ffi/cython/function.pxi", line 923, in tvm_ffi.core.Function.__call__
(EngineCore_DP0 pid=12178)   File "<unknown>", line 0, in __tvm_ffi_bmm_fp8
(EngineCore_DP0 pid=12178)   File "/home/llmTester/vllm-env/lib/python3.12/site-packages/flashinfer/data/csrc/bmm_fp8.cu", line 57, in bmm_fp8(tvm::ffi::TensorView, tvm::ffi::TensorView, tvm::ffi::TensorView, tvm::ffi::TensorView, tvm::ffi::TensorView, tvm::ffi::TensorView, int64_t)::<lambda()>::<lambda()>::<lambda()>::<lambda()>::<lambda()>::<lambda()>
(EngineCore_DP0 pid=12178)     TVM_FFI_ICHECK(status == CUBLAS_STATUS_SUCCESS)
(EngineCore_DP0 pid=12178)     
(EngineCore_DP0 pid=12178) RuntimeError: Check failed: (status == CUBLAS_STATUS_SUCCESS) is false: bmm_fp8_internal_cublaslt failed: the library was not initialized
Traceback (most recent call last):
  File "/home/llmTester/vllm-env/scripts/run_inference.py", line 17, in <module>
    llm = LLM(
          ^^^^
  File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/entrypoints/llm.py", line 334, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/llm_engine.py", line 183, in from_engine_args
    return cls(
           ^^^^
  File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/llm_engine.py", line 109, in __init__
    self.engine_core = EngineCoreClient.make_client(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 93, in make_client
    return SyncMPClient(vllm_config, executor_class, log_stats)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 642, in __init__
    super().__init__(
  File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 471, in __init__
    with launch_core_engines(vllm_config, executor_class, log_stats) as (
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/utils.py", line 903, in launch_core_engines
    wait_for_engine_startup(
  File "/home/llmTester/vllm-env/lib/python3.12/site-packages/vllm/v1/engine/utils.py", line 960, in wait_for_engine_startup
    raise RuntimeError(
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}

=====================================================================

The main issue seems to be: [**RuntimeError: Check failed: (status == CUBLAS_STATUS_SUCCESS) is false: bmm_fp8_internal_cublaslt failed: the library was not initialized**].

Even though I explicitly set dtype="bfloat16" and quantization=None in my test script to avoid FP8, the system persists in trying to use it.

Here is the Python script I used:
```
from vllm import LLM, SamplingParams

# Load model into vLLM
#llm = LLM(
#    model="/home/llmTester/models/qwen3_30b_thinking",
#    tensor_parallel_size=1,
#    gpu_memory_utilization=0.94,
#    trust_remote_code=True,
#    dtype="auto",
#    enforce_eager=True,
#    disable_custom_all_reduce=True,
#    max_model_len=4096,
#    max_num_seqs=1,
#    max_num_batched_tokens=4096
#)

llm = LLM(
    model="/home/llmTester/models/ministral3_14b_instruct",
    tensor_parallel_size=1,
    gpu_memory_utilization=0.94,
    trust_remote_code=True,
    dtype="bfloat16",
    quantization=None,
    enforce_eager=True,
    tokenizer_mode="mistral",
    config_format="mistral",
    load_format="mistral",
    max_model_len=4096,
    max_num_seqs=1,
    max_num_batched_tokens=4096
)

# Set Params
sampling_params = SamplingParams(
    temperature=0.7,
    top_p=0.9,
    max_tokens=512
)

# Set Prompt
prompts = ["Hey man, give me a quick intro about yourself."]
outputs = llm.generate(prompts, sampling_params)

for output in outputs:
    print(f"Ans: {output.outputs[0].text}")

```

I noticed that vLLM 0.12.0(https://github.com/vllm-project/vllm/releases/tag/v0.12.0) doesn't seem to support CUDA 13.0 yet.

I was able to successfully install vLLM (with cu129) using the command below and deploy the Qwen3-30B-A3B-Thinking-2507 model for testing without any issues:

`pip install vllm --extra-index-url https://download.pytorch.org/whl/cu129`

I'm not sure if this is a bug or simply an environment configuration issue.

Any help would be appreciated. Thanks.

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Austin-Liang** [comment]
Based on my attempts so far, please refer to the vLLM AI Chatbot log below: 
[Chat records](https://app.runllm.com/chat/8981401b-b3c2-462f-a6ae-ee92ce21113d)
My current best guess is that the library failed to initialize because PyTorch does not support the GB10 GPU (sm_121). Therefore, this is likely a version compatibility issue.

**Comment by 0xhaggis** [comment]
I'm using sm_120.

**Comment by LukeKeywalker** [comment]
Looks like the root cause for this error is incompatibility between system CUDA version 13.0, and CUDA version against which PyTorch was compiled (in my case it was 12.8, I see yours is 12.9). Fix steps are:

1. Install your PyTorch's CUDA version alongside the 13.0:

```
sudo ./cuda_12.8.0_*.run --silent --toolkit --toolkitpath=/usr/local/cuda-12.8 --no-opengl-libs --override
```

2. Point VLLM to new CUDA installation. My .zshrc config for vLLM looks now like this:
```
# CUDA stuff
export VLLM_CUDA_HOME=/usr/locali/cuda-12.8
export VLLM_FLASH_ATTN_CUDA_HOME=/usr/local/cuda-12.8
export FLASHINFER_CUDA_HOME=/usr/local/cuda-12.8

export CUDA_HOME=/usr/local/cuda-12.8
export PATH=/usr/local/cuda-12.8/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-12.8/lib64:$LD_LIBRARY_PATH
```

3. Clear `.cache/flashinfer` - this step is important, without it it would still complain about cuBLAS initialization even though it has proper CUDA installed

```
rm -rf ~/.cache/flashinfer
```

That fixed it for me, I hope it helps you too

**Comment by wende04** [comment]
Thank you. It's useful.
