### ISSUE TITLE
[Bug]: CUDA OOM during sampler warmup with DeepSeek-V3.2 (DeepGEMM) on vLLM Nightly (V1 Engine)

### ISSUE THREAD

**Issue by zkf331** [vllm-project/vllm#30637]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Collecting environment information...                                                                                                                    [195/513]
uv is set                                                                                                                                                         
==============================                                                                                                                                    
        System Info                                                                                                                                               
==============================                                                                                                                                    
OS                           : Ubuntu 22.04.5 LTS (x86_64)                                                                                                        
GCC version                  : (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0
Clang version                : Could not collect
CMake version                : version 4.1.0
Libc version                 : glibc-2.35

==============================
       PyTorch Info
==============================
PyTorch version              : 2.9.0+cu128
Is debug build               : False
CUDA used to build PyTorch   : 12.8
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.11 (main, Jun  4 2025, 08:56:18) [GCC 11.4.0] (64-bit runtime)                                                                
Python platform              : Linux-5.4.119-19.0009.56-x86_64-with-glibc2.35                                                                                     
                                                                                                                                                                  
==============================                                                                                                                                    
       CUDA / GPU Info                                                                                                                                            
==============================                                                                                                                                    
Is CUDA available            : True                                                                                                                               
CUDA runtime version         : 12.8.93
CUDA_MODULE_LOADING set to   : 
GPU models and configuration : 
GPU 0: NVIDIA H20-3e
GPU 1: NVIDIA H20-3e
GPU 2: NVIDIA H20-3e
GPU 3: NVIDIA H20-3e
GPU 4: NVIDIA H20-3e
GPU 5: NVIDIA H20-3e
GPU 6: NVIDIA H20-3e
GPU 7: NVIDIA H20-3e
Nvidia driver version        : 535.216.03
cuDNN version                : Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.14.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.14.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.14.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.14.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.14.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.14.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.14.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.14.0
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

=============================                                                                                                                                    
Versions of relevant libraries                                                                                                                                    
==============================                                                                                                                                    
[pip3] flashinfer-python==0.5.3
[pip3] numpy==2.2.6
[pip3] nvidia-cublas-cu12==12.8.4.1
[pip3] nvidia-cuda-cupti-cu12==12.8.90
[pip3] nvidia-cuda-nvrtc-cu12==12.8.93
[pip3] nvidia-cuda-runtime-cu12==12.8.90 
[pip3] nvidia-cudnn-cu12==9.10.2.21
[pip3] nvidia-cudnn-frontend==1.16.0
[pip3] nvidia-cufft-cu12==11.3.3.83
[pip3] nvidia-cufile-cu12==1.13.1.3
[pip3] nvidia-curand-cu12==10.3.9.90
[pip3] nvidia-cusolver-cu12==11.7.3.90
[pip3] nvidia-cusparse-cu12==12.5.8.93
[pip3] nvidia-cusparselt-cu12==0.7.1
[pip3] nvidia-cutlass-dsl==4.3.3
[pip3] nvidia-ml-py==13.590.44
[pip3] nvidia-ml-py==13.590.44
[pip3] nvidia-nccl-cu12==2.27.5
[pip3] nvidia-nvjitlink-cu12==12.8.93
[pip3] nvidia-nvshmem-cu12==3.3.20
[pip3] nvidia-nvtx-cu12==12.8.90
[pip3] pyzmq==27.1.0
[pip3] torch==2.9.0
[pip3] torchaudio==2.9.0
[pip3] torchvision==0.24.0
[pip3] transformers==4.57.3
[pip3] triton==3.5.0
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
vLLM Version                 : 0.13.0rc2.dev118+g29f7d9771 (git sha: 29f7d9771)

==============================                                                                                                                                    
     Environment Variables                                                                                                                                        
==============================
NVIDIA_VISIBLE_DEVICES=GPU-af560c2b-feb8-943d-7bd8-87e81e555abd,GPU-980b870d-61e6-2495-2dde-c665edb1c0b2,GPU-9b4accd9-8d0f-98dd-26d9-2d844d02a5a8,GPU-da7b4aac-e62
b-a0b1-ef42-066ecb7e9348,GPU-f5b4dd4d-d370-b97b-c829-5f66f22e66fb,GPU-685f7a08-2522-494b-2411-7176ea1caac1,GPU-b34af17d-783e-38ee-fe72-1891f821c45c,GPU-5d6f4297-3
639-9c82-dc30-85de0006f70b
NVIDIA_REQUIRE_CUDA=cuda>=12.8 brand=unknown,driver>=470,driver<471 brand=grid,driver>=470,driver<471 brand=tesla,driver>=470,driver<471 brand=nvidia,driver>=470,
driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=vapps,driver>=470,driver<471 br
and=vpc,driver>=470,driver<471 brand=vcs,driver>=470,driver<471 brand=vws,driver>=470,driver<471 brand=cloudgaming,driver>=470,driver<471 brand=unknown,driver>=53
5,driver<536 brand=grid,driver>=535,driver<536 brand=tesla,driver>=535,driver<536 brand=nvidia,driver>=535,driver<536 brand=quadro,driver>=535,driver<536 brand=qu
adrortx,driver>=535,driver<536 brand=nvidiartx,driver>=535,driver<536 brand=vapps,driver>=535,driver<536 brand=vpc,driver>=535,driver<536 brand=vcs,driver>=535,dr
iver<536 brand=vws,driver>=535,driver<536 brand=cloudgaming,driver>=535,driver<536 brand=unknown,driver>=550,driver<551 brand=grid,driver>=550,driver<551 brand=te
sla,driver>=550,driver<551 brand=nvidia,driver>=550,driver<551 brand=quadro,driver>=550,driver<551 brand=quadrortx,driver>=550,driver<551 brand=nvidiartx,driver>=
550,driver<551 brand=vapps,driver>=550,driver<551 brand=vpc,driver>=550,driver<551 brand=vcs,driver>=550,driver<551 brand=vws,driver>=550,driver<551 brand=cloudga
ming,driver>=550,driver<551 brand=unknown,driver>=560,driver<561 brand=grid,driver>=560,driver<561 brand=tesla,driver>=560,driver<561 brand=nvidia,driver>=560,dri
ver<561 brand=quadro,driver>=560,driver<561 brand=quadrortx,driver>=560,driver<561 brand=nvidiartx,driver>=560,driver<561 brand=vapps,driver>=560,driver<561 brand
=vpc,driver>=560,driver<561 brand=vcs,driver>=560,driver<561 brand=vws,driver>=560,driver<561 brand=cloudgaming,driver>=560,driver<561 brand=unknown,driver>=565,d
river<566 brand=grid,driver>=565,driver<566 brand=tesla,driver>=565,driver<566 brand=nvidia,driver>=565,driver<566 brand=quadro,driver>=565,driver<566 brand=quadr
ortx,driver>=565,driver<566 brand=nvidiartx,driver>=565,driver<566 brand=vapps,driver>=565,driver<566 brand=vpc,driver>=565,driver<566 brand=vcs,driver>=565,drive
r<566 brand=vws,driver>=565,driver<566 brand=cloudgaming,driver>=565,driver<566
NCCL_VERSION=2.25.1-1
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NVIDIA_PRODUCT_NAME=CUDA
VLLM_USAGE_SOURCE=production-docker-image
CUDA_VERSION=12.8.1
LD_LIBRARY_PATH=/usr/local/x86_64-linux-gnu:/usr/local/mpi/lib:/usr/local/cuda/lib64
OMP_NUM_THREADS=1
CUDA_HOME=/usr/local/cuda
CUDA_HOME=/usr/local/cuda
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1

```

</details>


### 🐛 Describe the bug

I am trying to serve deepseek-ai/DeepSeek-V3.2 using the latest vLLM nightly build and DeepGEMM. The model loads successfully, and DeepGEMM E8M0 is enabled. However, the server crashes with a CUDA out of memory error during the sampler warmup phase (_dummy_sampler_run), specifically when performing logits.sort.

I followed the instructions in the [DeepSeek-V3.2 recipe](https://github.com/vllm-project/recipes/blob/main/DeepSeek/DeepSeek-V3_2.md#installing-vllm), but it fails on the latest nightly version.

```shell
vllm serve deepseek-ai/DeepSeek-V3.2 \
   --tensor-parallel-size 8 \
   --gpu-memory-utilization 0.85  \
   --tool-call-parser deepseek_v32 \
   --enable-auto-tool-choice \
   --reasoning-parser deepseek_v3
```
Log Output

```txt
(APIServer pid=1594496) INFO 12-14 15:35:25 [api_server.py:1351] vLLM API server version 0.13.0rc2.dev118+g29f7d9771
...
(EngineCore_DP0 pid=1594645) INFO 12-14 15:35:48 [core.py:93] Initializing a V1 LLM engine ...
...
(Worker_TP0 pid=1594712) INFO 12-14 15:37:38 [deep_gemm.py:76] DeepGEMM E8M0 enabled on current platform.
...
(Worker_TP2 pid=1594714) ERROR 12-14 15:40:59 [multiproc_executor.py:824]   File "/home/tione/notebook/zkf/venv/vllm-0.13.0rc1/lib/python3.12/site-packages/vllm/v1/sample/ops/topk_topp_sampler.py", line 258, in apply_top_k_top_p
(Worker_TP2 pid=1594714) ERROR 12-14 15:40:59 [multiproc_executor.py:824]     logits_sort, logits_idx = logits.sort(dim=-1, descending=False)
(Worker_TP2 pid=1594714) ERROR 12-14 15:40:59 [multiproc_executor.py:824]                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP2 pid=1594714) ERROR 12-14 15:40:59 [multiproc_executor.py:824] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1010.00 MiB. GPU 2 has a total capacity of 139.73 GiB of which 693.75 MiB is free. Including non-PyTorch memory, this process has 139.04 GiB memory in use.
...
(Worker_TP2 pid=1594714) ERROR 12-14 15:40:59 [multiproc_executor.py:824] RuntimeError: CUDA out of memory occurred when warming up sampler with 1024 dummy requests. Please try lowering `max_num_seqs` or `gpu_memory_utilization` when initializing the engine.
```

Reproduction Steps
1. Install vllm nightly and deepgemm v2.1.1.post3.
2. Run the vllm serve command with DeepSeek-V3.2 and TP8.
3. Observe crash during initialization (sampler warmup).

Additional Context

- It seems the V1 Engine is being initialized by default (Initializing a V1 LLM engine).
- The GPU memory usage is extremely high (139.04 GiB used out of 139.73 GiB) even before the sampler warmup completes.
- Is gpu-memory-utilization 0.85 too high for the V1 engine overhead with this model?

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by zkf331** [comment]
@mondaylord Here is the setup process that worked for me.

**1. Installing vLLM Nightly**
I used the command below. As you can see from the logs, it successfully pulls the specific dev version (`0.13.0rc2.dev118...`). If you are still seeing `0.12.0`, you might want to check your pip cache or ensure your network can reach the vllm nightly wheel server.

```bash
pip install vllm --extra-index-url https://wheels.vllm.ai/nightly
```

Output log for reference:

```text
Looking in indexes: https://wheels.vllm.ai/nightly
Requirement already satisfied: vllm in /usr/local/lib/python3.12/dist-packages 
Collecting vllm
  Downloading https://wheels.vllm.ai/29f7d9771569f26238d67cf6ea3a8792fb6a7792/vllm-0.13.0rc2.dev118%2Bg29f7d9771-cp38-abi3-manylinux_2_31_x86_64.whl (474.9 MB)
```

**2. Installing DeepGEMM**
For DeepGEMM `v2.1.1.post3`, I encountered issues with standard installation as well. To fix the compilation error, I downloaded the source code locally and installed it using `--no-build-isolation --no-deps`. This forces it to use the existing environment environment libraries.

```bash
# Assuming you have downloaded/cloned the source to this directory
cd ~/DeepGEMM-v2.1.1.post3/
pip install . --no-build-isolation --no-deps
```

**Comment by zkf331** [comment]
I successfully launched the DeepSeek-V3.2 service and ran performance tests using the command below:

```shell
vllm serve deepseek-ai/DeepSeek-V3.2 \
 --gpu-memory-utilization 0.90 --tensor-parallel-size 8 --enable-chunked-prefill \
 --tokenizer-mode deepseek_v32 --max-num-batched-tokens 4096  --max-model-len 131072 \
 --enable-auto-tool-choice --tool-call-parser deepseek_v32 --reasoning-parser deepseek_v3 \
 --trust-remote-code  --max-num-seqs 128
```

**Regarding OOM:** If you encounter OOM issues, I suggest reducing --gpu-memory-utilization or --max-num-batched-tokens. I am currently tuning these two parameters to find the optimal trade-off for performance.

**Benchmark Inconsistency:** However, when using vllm bench serve (command below), I noticed a significant performance discrepancy between the first and second runs. This seems relevant to issue #30853.

```shell
vllm bench serve \
  --model deepseek-ai/DeepSeek-V3.2 \
  --dataset-name random \
  --random-input 2048 \
  --random-output 1024 \
  --request-rate 10 \
  --num-prompt 100  \
  --trust-remote-code
```
