### ISSUE TITLE
[Bug]: After upgrade to 0.11.2, vllm crashs with Qwen3.

### ISSUE THREAD

**Issue by tonyaw** [vllm-project/vllm#31709]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

After upgrade to 0.11.2, vllm may crash sometimes with Qwen3.
Command to start vllm:
```
VLLM_ALLOW_LONG_MAX_MODEL_LEN=1 uv run vllm serve \
        Qwen/Qwen3-32B-FP8 \
        --host 0.0.0.0 --port $port --seed 42 --trust-remote-code \
        --enable-chunked-prefill --enable-prefix-caching \
        --enable-prompt-tokens-details \
        --reasoning-parser deepseek_r1 \
        --gpu-memory-utilization 0.97 \
        --max_num_seqs 100 \
        --enable-auto-tool-choice --tool-call-parser hermes \
        --hf-overrides '{"rope-scaling": {"factor": 4.0, "original_max_position_embeddings": 32768, "rope_type": "yarn"}}' \
        -O3 \
        --quantization fp8 \
        --tensor-parallel-size 1 --max-model-len 87040 >> "$LOG_FILE" 2>&1 &
```

Error logs when it is crashed:
```
/tmp/torchinductor_root/q5/cq5iuvdeguweyk7x36xgxz2jrq5ktxlkxxg3u6legsnlo62zqcrn.py:97: unknown: block: [4,0,0], thread: [0,0,0] Assertion `index out of bounds: 0 <= tmp48 < 40960` failed.
/tmp/torchinductor_root/q5/cq5iuvdeguweyk7x36xgxz2jrq5ktxlkxxg3u6legsnlo62zqcrn.py:97: unknown: block: [4,0,0], thread: [1,0,0] Assertion `index out of bounds: 0 <= tmp48 < 40960` failed.
...
/tmp/torchinductor_root/q5/cq5iuvdeguweyk7x36xgxz2jrq5ktxlkxxg3u6legsnlo62zqcrn.py:53: unknown: block: [3,0,0], thread: [126,0,0] Assertion `index out of bounds: 0 <= tmp16 < 40960` failed.
/tmp/torchinductor_root/q5/cq5iuvdeguweyk7x36xgxz2jrq5ktxlkxxg3u6legsnlo62zqcrn.py:53: unknown: block: [3,0,0], thread: [127,0,0] Assertion `index out of bounds: 0 <= tmp16 < 40960` failed.
...
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [dump_input.py:72] Dumping input data for V1 LLM engine (v0.11.2) with config: model='Qwen/Qwen3-32B-FP8', speculative_config=None, tokenizer='Qwen/Qwen3-32B-FP8', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=87040, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=fp8, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='deepseek_r1', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=42, served_model_name=Qwen/Qwen3-32B-FP8, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '/root/.cache/vllm/torch_compile_cache/86fcff198d', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none', '+quant_fp8', '+quant_fp8'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer'], 'compile_mm_encoder': False, 'use_inductor': None, 'compile_sizes': [], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_cudagraph_capture_size': 200, 'local_cache_dir': '/root/.cache/vllm/torch_compile_cache/86fcff198d/rank_0_0/backbone'},

^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [dump_input.py:79] Dumping scheduler output for model execution: SchedulerOutput(scheduled_new_reqs=[], scheduled_cached_reqs=CachedRequestData(req_ids=['chatcmpl-a3ac53d1-e227-4922-9e26-05665d2d2498'], resumed_req_ids=[], new_token_ids=[], all_token_ids={}, new_block_ids=[[[4167]]], num_computed_tokens=[40960], num_output_tokens=[37610]), num_scheduled_tokens={chatcmpl-a3ac53d1-e227-4922-9e26-05665d2d2498: 1}, total_num_scheduled_tokens=1, scheduled_spec_decode_tokens={}, scheduled_encoder_inputs={}, num_common_prefix_blocks=[2561], finished_req_ids=[], free_encoder_mm_hashes=[], pending_structured_output_tokens=false, kv_connector_metadata=null, ec_connector_metadata=null)
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [dump_input.py:81] Dumping scheduler stats: SchedulerStats(num_running_reqs=1, num_waiting_reqs=0, step_counter=0, current_wave=0, kv_cache_usage=0.2332847513208235, prefix_cache_stats=PrefixCacheStats(reset=False, requests=0, queries=0, hits=0, preempted_requests=0, preempted_queries=0, preempted_hits=0), connector_prefix_cache_stats=None, spec_decoding_stats=None, kv_connector_stats=None, waiting_lora_adapters={}, running_lora_adapters={})

^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844] EngineCore encountered a fatal error.^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844] Traceback (most recent call last):^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 835, in run_engine_core^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]     engine_core.run_busy_loop()^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 862, in run_busy_loop^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]     self._process_engine_step()^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 891, in _process_engine_step^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]     outputs, model_executed = self.step_fn()^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]                               ^^^^^^^^^^^^^^^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 344, in step^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]     model_output = self.model_executor.sample_tokens(grammar_output)^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/executor/uniproc_executor.py", line 107, in sample_tokens^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]     return self.collective_rpc(^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]            ^^^^^^^^^^^^^^^^^^^^^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/executor/uniproc_executor.py", line 75, in collective_rpc^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]     result = run_method(self.driver_worker, method, args, kwargs)^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/serial_utils.py", line 479, in run_method^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]     return func(*args, **kwargs)^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]            ^^^^^^^^^^^^^^^^^^^^^^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]     return func(*args, **kwargs)^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]            ^^^^^^^^^^^^^^^^^^^^^^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 539, in sample_tokens^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]     return self.model_runner.sample_tokens(grammar_output)^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]     return func(*args, **kwargs)^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]            ^^^^^^^^^^^^^^^^^^^^^^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 2990, in sample_tokens^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]     ) = self._bookkeeping_sync(^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]         ^^^^^^^^^^^^^^^^^^^^^^^^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 2484, in _bookkeeping_sync^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]     valid_sampled_token_ids = self._to_list(sampled_token_ids)^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 5101, in _to_list^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]     self.transfer_event.synchronize()^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/torch/cuda/streams.py", line 231, in synchronize^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]     super().synchronize()^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844] torch.AcceleratorError: CUDA error: device-side assert triggered^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844] Search for `cudaErrorAssert' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844] CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844] For debugging consider passing CUDA_LAUNCH_BLOCKING=1^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844] Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.^M
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m ERROR 01-04 04:31:09 [core.py:844]
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [async_llm.py:525] AsyncLLM output_handler failed.^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [async_llm.py:525] Traceback (most recent call last):^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [async_llm.py:525]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 477, in output_handler^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [async_llm.py:525]     outputs = await engine_core.get_output_async()^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [async_llm.py:525]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [async_llm.py:525]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 883, in get_output_async^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [async_llm.py:525]     raise self._format_exception(outputs) from None^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [async_llm.py:525] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278] Error in chat completion stream generator.^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278] Traceback (most recent call last):^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/entrypoints/openai/serving_chat.py", line 611, in chat_completion_stream_generator^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278]     async for res in result_generator:^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 423, in generate^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278]     out = q.get_nowait() or await q.get()^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278]                             ^^^^^^^^^^^^^^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/output_processor.py", line 70, in get^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278]     raise output^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/async_llm.py", line 477, in output_handler^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278]     outputs = await engine_core.get_output_async()^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278]   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/core_client.py", line 883, in get_output_async^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278]     raise self._format_exception(outputs) from None^M
^[[1;36m(APIServer pid=42929)^[[0;0m ERROR 01-04 04:31:09 [serving_chat.py:1278] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m Process EngineCore_DP0:
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m Traceback (most recent call last):
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     self.run()
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     self._target(*self._args, **self._kwargs)
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 846, in run_engine_core
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     raise e
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 835, in run_engine_core
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     engine_core.run_busy_loop()
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 862, in run_busy_loop
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     self._process_engine_step()
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 891, in _process_engine_step
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     outputs, model_executed = self.step_fn()
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m                               ^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/engine/core.py", line 344, in step
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     model_output = self.model_executor.sample_tokens(grammar_output)
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/executor/uniproc_executor.py", line 107, in sample_tokens
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     return self.collective_rpc(
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m            ^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/executor/uniproc_executor.py", line 75, in collective_rpc
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     result = run_method(self.driver_worker, method, args, kwargs)
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/serial_utils.py", line 479, in run_method
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     return func(*args, **kwargs)
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m            ^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     return func(*args, **kwargs)
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m            ^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_worker.py", line 539, in sample_tokens
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     return self.model_runner.sample_tokens(grammar_output)
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     return func(*args, **kwargs)
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m            ^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 2990, in sample_tokens
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     ) = self._bookkeeping_sync(
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m         ^^^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 2484, in _bookkeeping_sync
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     valid_sampled_token_ids = self._to_list(sampled_token_ids)
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/vllm/v1/worker/gpu_model_runner.py", line 5101, in _to_list
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     self.transfer_event.synchronize()
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m   File "/root/vllm-src/.venv/lib/python3.12/site-packages/torch/cuda/streams.py", line 231, in synchronize
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m     super().synchronize()
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m torch.AcceleratorError: CUDA error: device-side assert triggered
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m Search for `cudaErrorAssert' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m For debugging consider passing CUDA_LAUNCH_BLOCKING=1
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
^[[1;36m(EngineCore_DP0 pid=43065)^[[0;0m
[rank0]:[W104 04:31:09.295769924 ProcessGroupNCCL.cpp:1524] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by tonyaw** [comment]
Thanks! I'm trying it to see if I can reproduce this issue with rope_parameters.
May I ask the difference between rope_parameters and rope-scaling?

**Comment by pengjiang80** [comment]
Encountered the same issue, change the "--hf-overrides={"rope_scaling": {"rope_type":"yarn","factor":4.0,"original_max_position_embeddings":32768}}" to "--hf-overrides={"rope_parameters": {"rope_type":"yarn","factor":4.0,"original_max_position_embeddings":32768}}" did the trick. With the rope_scaling setting, vLLM will crash with a prompt longer than the value in config.json.
