### ISSUE TITLE
[Bug]: AttributeError: 'Qwen3VLMoeConfig' object has no attribute 'vocab_size'

### ISSUE THREAD

**Issue by study-overflow** [vllm-project/vllm#33508]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Collecting environment information...
==============================
        System Info
==============================
OS                           : Ubuntu 22.04.4 LTS (x86_64)
GCC version                  : (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version                : Could not collect
CMake version                : version 3.31.4
Libc version                 : glibc-2.35

==============================
       PyTorch Info
==============================
PyTorch version              : 2.9.1+cu128
Is debug build               : False
CUDA used to build PyTorch   : 12.8
ROCM used to build PyTorch   : N/A

==============================
      Python Environment
==============================
Python version               : 3.13.11 | packaged by Anaconda, Inc. | (main, Dec 10 2025, 21:28:48) [GCC 14.3.0] (64-bit runtime)
Python platform              : Linux-5.4.241-1-tlinux4-0017.7-x86_64-with-glibc2.35

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : 12.4.131
CUDA_MODULE_LOADING set to   : 
GPU models and configuration : 
GPU 0: NVIDIA H20
GPU 1: NVIDIA H20
GPU 2: NVIDIA H20
GPU 3: NVIDIA H20
GPU 4: NVIDIA H20
GPU 5: NVIDIA H20
GPU 6: NVIDIA H20
GPU 7: NVIDIA H20

Nvidia driver version        : 535.247.01
cuDNN version                : Could not collect
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          384
On-line CPU(s) list:             0-383
Vendor ID:                       AuthenticAMD
BIOS Vendor ID:                  Advanced Micro Devices, Inc.
Model name:                      AMD EPYC 9K84 96-Core Processor
BIOS Model name:                 AMD EPYC 9K84 96-Core Processor                
CPU family:                      25
Model:                           17
Thread(s) per core:              2
Core(s) per socket:              96
Socket(s):                       2
Stepping:                        1
Frequency boost:                 enabled
CPU max MHz:                     2600.0000
CPU min MHz:                     1500.0000
BogoMIPS:                        5199.85
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid overflow_recov succor smca fsrm flush_l1d
Virtualization:                  AMD-V
L1d cache:                       6 MiB (192 instances)
L1i cache:                       6 MiB (192 instances)
L2 cache:                        192 MiB (192 instances)
L3 cache:                        768 MiB (24 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-95,192-287
NUMA node1 CPU(s):               96-191,288-383
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP always-on, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

==============================
Versions of relevant libraries
==============================
[pip3] flashinfer-python==0.6.1
[pip3] numpy==2.2.6
[pip3] nvidia-cublas-cu12==12.8.4.1
[pip3] nvidia-cuda-cupti-cu12==12.8.90
[pip3] nvidia-cuda-nvrtc-cu12==12.8.93
[pip3] nvidia-cuda-runtime-cu12==12.8.90
[pip3] nvidia-cudnn-cu12==9.10.2.21
[pip3] nvidia-cudnn-frontend==1.18.0
[pip3] nvidia-cufft-cu12==11.3.3.83
[pip3] nvidia-cufile-cu12==1.13.1.3
[pip3] nvidia-curand-cu12==10.3.9.90
[pip3] nvidia-cusolver-cu12==11.7.3.90
[pip3] nvidia-cusparse-cu12==12.5.8.93
[pip3] nvidia-cusparselt-cu12==0.7.1
[pip3] nvidia-cutlass-dsl==4.3.5
[pip3] nvidia-ml-py==13.590.48
[pip3] nvidia-nccl-cu12==2.27.5
[pip3] nvidia-nvjitlink-cu12==12.8.93
[pip3] nvidia-nvshmem-cu12==3.3.20
[pip3] nvidia-nvtx-cu12==12.8.90
[pip3] pyzmq==27.1.0
[pip3] torch==2.9.1
[pip3] torchaudio==2.9.1
[pip3] torchvision==0.24.1
[pip3] transformers==4.57.6
[pip3] triton==3.5.1
[conda] flashinfer-python                    0.6.1            pypi_0              pypi
[conda] numpy                                2.2.6            pypi_0              pypi
[conda] nvidia-cublas-cu12                   12.8.4.1         pypi_0              pypi
[conda] nvidia-cuda-cupti-cu12               12.8.90          pypi_0              pypi
[conda] nvidia-cuda-nvrtc-cu12               12.8.93          pypi_0              pypi
[conda] nvidia-cuda-runtime-cu12             12.8.90          pypi_0              pypi
[conda] nvidia-cudnn-cu12                    9.10.2.21        pypi_0              pypi
[conda] nvidia-cudnn-frontend                1.18.0           pypi_0              pypi
[conda] nvidia-cufft-cu12                    11.3.3.83        pypi_0              pypi
[conda] nvidia-cufile-cu12                   1.13.1.3         pypi_0              pypi
[conda] nvidia-curand-cu12                   10.3.9.90        pypi_0              pypi
[conda] nvidia-cusolver-cu12                 11.7.3.90        pypi_0              pypi
[conda] nvidia-cusparse-cu12                 12.5.8.93        pypi_0              pypi
[conda] nvidia-cusparselt-cu12               0.7.1            pypi_0              pypi
[conda] nvidia-cutlass-dsl                   4.3.5            pypi_0              pypi
[conda] nvidia-ml-py                         13.590.48        pypi_0              pypi
[conda] nvidia-nccl-cu12                     2.27.5           pypi_0              pypi
[conda] nvidia-nvjitlink-cu12                12.8.93          pypi_0              pypi
[conda] nvidia-nvshmem-cu12                  3.3.20           pypi_0              pypi
[conda] nvidia-nvtx-cu12                     12.8.90          pypi_0              pypi
[conda] pyzmq                                27.1.0           pypi_0              pypi
[conda] torch                                2.9.1            pypi_0              pypi
[conda] torchaudio                           2.9.1            pypi_0              pypi
[conda] torchvision                          0.24.1           pypi_0              pypi
[conda] transformers                         4.57.6           pypi_0              pypi
[conda] triton                               3.5.1            pypi_0              pypi

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
vLLM Version                 : 0.15.0
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled
GPU Topology:
  	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	NIC0	NIC1	NIC2	NIC3	NIC4	NIC5	NIC6	NIC7	NIC8	NIC9	NIC10	NIC11	NIC12	NIC13	NIC14	NIC15	NIC16	NIC17	NIC18	NIC19	NIC20	NIC21	NIC22	NIC23	NIC24NIC25	NIC26	NIC27	NIC28	NIC29	NIC30	NIC31	NIC32	NIC33	NIC34	NIC35	NIC36	NIC37	NIC38	NIC39	NIC40	NIC41CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV18	NV18	NV18	NV18	NV18	NV18	NV18	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PIX	NODE	NODE	NODE	SYS	SYS	SYS	SYS	0-95,192-287	0		N/A
GPU1	NV18	 X 	NV18	NV18	NV18	NV18	NV18	NV18	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	NODE	NODE	PHB	PIX	SYS	SYS	SYS	SYS	0-95,192-287	0		N/A
GPU2	NV18	NV18	 X 	NV18	NV18	NV18	NV18	NV18	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	NODE	NODE	PIX	PHB	SYS	SYS	SYS	SYS	0-95,192-287	0		N/A
GPU3	NV18	NV18	NV18	 X 	NV18	NV18	NV18	NV18	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	NODE	PIX	NODE	NODE	SYS	SYS	SYS	SYS	0-95,192-287	0		N/A
GPU4	NV18	NV18	NV18	NV18	 X 	NV18	NV18	NV18	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	NODE	NODE	PIX	NODE	96-191,288-383	1		N/A
GPU5	NV18	NV18	NV18	NV18	NV18	 X 	NV18	NV18	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	NODE	PIX	NODE	NODE	96-191,288-383	1		N/A
GPU6	NV18	NV18	NV18	NV18	NV18	NV18	 X 	NV18	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	PHB	NODE	NODE	PIX	96-191,288-383	1		N/A
GPU7	NV18	NV18	NV18	NV18	NV18	NV18	NV18	 X 	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	PIX	NODE	NODE	PHB	96-191,288-383	1		N/A
NIC0	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC1	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC2	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC3	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC4	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC5	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC6	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC7	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC8	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC9	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC10	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC11	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC12	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC13	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC14	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC15	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC16	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC17	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC18	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC19	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC20	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC21	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC22	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC23	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC24	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC25	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC26	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC27	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC28	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC29	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC30	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC31	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC32	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	PIX	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC33	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	PIX	 X 	SYS	SYS	SYS	SYS	NODE	NODE	NODE	NODE	
NIC34	PIX	NODE	NODE	NODE	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	 X 	NODE	NODE	NODE	SYS	SYS	SYS	SYS	
NIC35	NODE	NODE	NODE	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	NODE	 X 	NODE	NODE	SYS	SYS	SYS	SYS	
NIC36	NODE	PHB	PIX	NODE	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	NODE	NODE	 X 	PHB	SYS	SYS	SYS	SYS	
NIC37	NODE	PIX	PHB	NODE	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	NODE	NODE	PHB	 X 	SYS	SYS	SYS	SYS	
NIC38	SYS	SYS	SYS	SYS	NODE	NODE	PHB	PIX	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	 X 	NODE	NODE	PHB	
NIC39	SYS	SYS	SYS	SYS	NODE	PIX	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	NODE	 X 	NODE	NODE	
NIC40	SYS	SYS	SYS	SYS	PIX	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	NODE	NODE	 X 	NODE	
NIC41	SYS	SYS	SYS	SYS	NODE	NODE	PIX	PHB	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	PHB	NODE	NODE	 X 	

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
  NIC4: mlx5_4
  NIC5: mlx5_5
  NIC6: mlx5_6
  NIC7: mlx5_7
  NIC8: mlx5_8
  NIC9: mlx5_9
  NIC10: mlx5_10
  NIC11: mlx5_11
  NIC12: mlx5_12
  NIC13: mlx5_13
  NIC14: mlx5_14
  NIC15: mlx5_15
  NIC16: mlx5_16
  NIC17: mlx5_17
  NIC18: mlx5_18
  NIC19: mlx5_19
  NIC20: mlx5_20
  NIC21: mlx5_21
  NIC22: mlx5_22
  NIC23: mlx5_23
  NIC24: mlx5_24
  NIC25: mlx5_25
  NIC26: mlx5_26
  NIC27: mlx5_27
  NIC28: mlx5_28
  NIC29: mlx5_29
  NIC30: mlx5_30
  NIC31: mlx5_31
  NIC32: mlx5_32
  NIC33: mlx5_33
  NIC34: mlx5_bond_1
  NIC35: mlx5_bond_2
  NIC36: mlx5_bond_3
  NIC37: mlx5_bond_4
  NIC38: mlx5_bond_5
  NIC39: mlx5_bond_6
  NIC40: mlx5_bond_7
  NIC41: mlx5_bond_8

==============================
     Environment Variables
==============================
NVIDIA_VISIBLE_DEVICES=GPU-d8d9836b-9ddc-dfdc-40b4-2f4a0fd210ad,GPU-db5255d8-b601-64c6-f051-2f14cb9ba9bb,GPU-b2e04582-9c28-9aea-02ae-011285f160f3,GPU-3c806406-ddcd-b2b7-979e-dcb23836eb8c,GPU-eeb3f00c-d366-668d-b454-0e6042e8dc8a,GPU-a0f72703-f32d-314d-d9cf-ab41ab98c6f9,GPU-bb7a4ba1-2b8a-4aad-97ab-7c9b82bacdbb,GPU-b11fca56-ad24-692f-8d17-d0622db8f47b
NVIDIA_REQUIRE_CUDA=cuda>=12.4 brand=tesla,driver>=470,driver<471 brand=unknown,driver>=470,driver<471 brand=nvidia,driver>=470,driver<471 brand=nvidiartx,driver>=470,driver<471 brand=geforce,driver>=470,driver<471 brand=geforcertx,driver>=470,driver<471 brand=quadro,driver>=470,driver<471 brand=quadrortx,driver>=470,driver<471 brand=titan,driver>=470,driver<471 brand=titanrtx,driver>=470,driver<471 brand=tesla,driver>=525,driver<526 brand=unknown,driver>=525,driver<526 brand=nvidia,driver>=525,driver<526 brand=nvidiartx,driver>=525,driver<526 brand=geforce,driver>=525,driver<526 brand=geforcertx,driver>=525,driver<526 brand=quadro,driver>=525,driver<526 brand=quadrortx,driver>=525,driver<526 brand=titan,driver>=525,driver<526 brand=titanrtx,driver>=525,driver<526 brand=tesla,driver>=535,driver<536 brand=unknown,driver>=535,driver<536 brand=nvidia,driver>=535,driver<536 brand=nvidiartx,driver>=535,driver<536 brand=geforce,driver>=535,driver<536 brand=geforcertx,driver>=535,driver<536 brand=quadro,driver>=535,driver<536 brand=quadrortx,driver>=535,driver<536 brand=titan,driver>=535,driver<536 brand=titanrtx,driver>=535,driver<536
NCCL_VERSION=2.21.5-1
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NVIDIA_PRODUCT_NAME=CUDA
CUDA_VERSION=12.4.1
LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
```

</details>

### 🐛 Describe the bug

Hi, thanks for the great work on vLLM.

I am trying to deploy **Qwen/Qwen3-VL-235B-A22B-Instruct** locally following the official recipe:

[https://docs.vllm.ai/projects/recipes/en/latest/Qwen/Qwen3-VL.html](https://docs.vllm.ai/projects/recipes/en/latest/Qwen/Qwen3-VL.html)

However, I encounter an error during startup.

---

### Command

```bash
VLLM_USE_MODELSCOPE=true vllm serve <path/to/Qwen3-VL-235B-A22B-Instruct> \
  --tensor-parallel-size 8
```

---

### Error Message

```text
ERROR 02-01 01:50:11 engine.py:389] AttributeError: 'Qwen3VLMoeConfig' object has no attribute 'vocab_size'
```

---

### Additional Information

I checked the model’s `config.json`, and it **does include** the `vocab_size` field:

```json
"vocab_size": 151936
```

So it seems that `Qwen3VLMoeConfig` does not correctly expose or propagate `vocab_size`, even though it is present in the underlying config.

---

### Question

* Is this a known compatibility issue between vLLM and `Qwen3VLMoeConfig`?
* Is there a recommended workaround or patch?
* Or is this a bug that should be fixed in vLLM?

Any guidance would be appreciated. Thanks!

<details>
<summary>The detailed outputs can be seen here.</summary>

```bash
$ VLLM_USE_MODELSCOPE=true vllm serve /mnt/shaoguan1cephfs/zjangozhang/Qwen3
Modular Diffusers is currently an experimental feature under active development. The API is subject to breaking changes in future releases.
INFO 02-01 01:49:53 __init__.py:186] Automatically detected platform cuda.
INFO 02-01 01:49:54 api_server.py:840] vLLM API server version 0.7.2.dev56+gbf3b79ef
INFO 02-01 01:49:54 api_server.py:841] args: Namespace(subparser='serve', model_tag='/mnt/shaoguan1cephfs/zjangozhang/Qwen3', config='', host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, enable_reasoning=False, reasoning_parser=None, tool_call_parser=None, tool_parser_plugin='', model='/mnt/shaoguan1cephfs/zjangozhang/Qwen3', task='auto', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', max_model_len=None, guided_decoding_backend='xgrammar', logits_processor_pattern=None, model_impl='auto', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=None, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=False, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_disable_mqa_scorer=False, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', generation_config=None, override_generation_config=None, enable_sleep_mode=False, calculate_kv_scales=False, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, dispatch_function=<function serve at 0x7fb6b270e3e0>)
INFO 02-01 01:49:54 api_server.py:206] Started engine process with PID 18482
`torch_dtype` is deprecated! Use `dtype` instead!
Modular Diffusers is currently an experimental feature under active development. The API is subject to breaking changes in future releases.
INFO 02-01 01:49:59 __init__.py:186] Automatically detected platform cuda.
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 02-01 01:50:02 config.py:542] This model supports multiple tasks: {'classify', 'score', 'reward', 'generate', 'embed'}. Defaulting to 'generate'.
WARNING 02-01 01:50:02 arg_utils.py:1135] Chunked prefill is enabled by default for models with max_model_len > 32K. Currently, chunked prefill might not work with some features or models. If you encounter any issues, please disable chunked prefill by setting --enable-chunked-prefill=False.
INFO 02-01 01:50:02 config.py:1557] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 02-01 01:50:09 config.py:542] This model supports multiple tasks: {'classify', 'generate', 'reward', 'score', 'embed'}. Defaulting to 'generate'.
WARNING 02-01 01:50:09 arg_utils.py:1135] Chunked prefill is enabled by default for models with max_model_len > 32K. Currently, chunked prefill might not work with some features or models. If you encounter any issues, please disable chunked prefill by setting --enable-chunked-prefill=False.
INFO 02-01 01:50:09 config.py:1557] Chunked prefill is enabled with max_num_batched_tokens=2048.
INFO 02-01 01:50:09 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.2.dev56+gbf3b79ef) with config: model='/mnt/shaoguan1cephfs/zjangozhang/Qwen3', speculative_config=None, tokenizer='/mnt/shaoguan1cephfs/zjangozhang/Qwen3', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=262144, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/mnt/shaoguan1cephfs/zjangozhang/Qwen3, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=True, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=True, 
INFO 02-01 01:50:10 cuda.py:230] Using Flash Attention backend.
INFO 02-01 01:50:11 model_runner.py:1110] Starting to load model /mnt/shaoguan1cephfs/zjangozhang/Qwen3...
WARNING 02-01 01:50:11 utils.py:69] Qwen3VLMoeForConditionalGeneration has no vLLM implementation, falling back to Transformers implementation. Some features may not be supported and performance may not be optimal.
INFO 02-01 01:50:11 transformers.py:120] Using Transformers backend.
ERROR 02-01 01:50:11 engine.py:389] 'Qwen3VLMoeConfig' object has no attribute 'vocab_size'
ERROR 02-01 01:50:11 engine.py:389] Traceback (most recent call last):
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 380, in run_mp_engine
ERROR 02-01 01:50:11 engine.py:389]     engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
ERROR 02-01 01:50:11 engine.py:389]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 123, in from_engine_args
ERROR 02-01 01:50:11 engine.py:389]     return cls(ipc_path=ipc_path,
ERROR 02-01 01:50:11 engine.py:389]            ^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 75, in __init__
ERROR 02-01 01:50:11 engine.py:389]     self.engine = LLMEngine(*args, **kwargs)
ERROR 02-01 01:50:11 engine.py:389]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 273, in __init__
ERROR 02-01 01:50:11 engine.py:389]     self.model_executor = executor_class(vllm_config=vllm_config, )
ERROR 02-01 01:50:11 engine.py:389]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 51, in __init__
ERROR 02-01 01:50:11 engine.py:389]     self._init_executor()
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 42, in _init_executor
ERROR 02-01 01:50:11 engine.py:389]     self.collective_rpc("load_model")
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 51, in collective_rpc
ERROR 02-01 01:50:11 engine.py:389]     answer = run_method(self.driver_worker, method, args, kwargs)
ERROR 02-01 01:50:11 engine.py:389]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 2220, in run_method
ERROR 02-01 01:50:11 engine.py:389]     return func(*args, **kwargs)
ERROR 02-01 01:50:11 engine.py:389]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker.py", line 183, in load_model
ERROR 02-01 01:50:11 engine.py:389]     self.model_runner.load_model()
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1112, in load_model
ERROR 02-01 01:50:11 engine.py:389]     self.model = get_model(vllm_config=self.vllm_config)
ERROR 02-01 01:50:11 engine.py:389]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/__init__.py", line 14, in get_model
ERROR 02-01 01:50:11 engine.py:389]     return loader.load_model(vllm_config=vllm_config)
ERROR 02-01 01:50:11 engine.py:389]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 383, in load_model
ERROR 02-01 01:50:11 engine.py:389]     model = _initialize_model(vllm_config=vllm_config)
ERROR 02-01 01:50:11 engine.py:389]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 125, in _initialize_model
ERROR 02-01 01:50:11 engine.py:389]     return model_class(vllm_config=vllm_config, prefix=prefix)
ERROR 02-01 01:50:11 engine.py:389]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/transformers.py", line 128, in __init__
ERROR 02-01 01:50:11 engine.py:389]     self.vocab_size = config.vocab_size
ERROR 02-01 01:50:11 engine.py:389]                       ^^^^^^^^^^^^^^^^^
ERROR 02-01 01:50:11 engine.py:389]   File "/usr/local/lib/python3.12/dist-packages/transformers/configuration_utils.py", line 207, in __getattribute__
ERROR 02-01 01:50:11 engine.py:389]     return super().__getattribute__(key)
ERROR 02-01 01:50:11 engine.py:389]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 02-01 01:50:11 engine.py:389] AttributeError: 'Qwen3VLMoeConfig' object has no attribute 'vocab_size'
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 391, in run_mp_engine
    raise e
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 380, in run_mp_engine
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 123, in from_engine_args
    return cls(ipc_path=ipc_path,
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/multiprocessing/engine.py", line 75, in __init__
    self.engine = LLMEngine(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/engine/llm_engine.py", line 273, in __init__
    self.model_executor = executor_class(vllm_config=vllm_config, )
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/executor_base.py", line 51, in __init__
    self._init_executor()
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 42, in _init_executor
    self.collective_rpc("load_model")
  File "/usr/local/lib/python3.12/dist-packages/vllm/executor/uniproc_executor.py", line 51, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/utils.py", line 2220, in run_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/worker.py", line 183, in load_model
    self.model_runner.load_model()
  File "/usr/local/lib/python3.12/dist-packages/vllm/worker/model_runner.py", line 1112, in load_model
    self.model = get_model(vllm_config=self.vllm_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/__init__.py", line 14, in get_model
    return loader.load_model(vllm_config=vllm_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 383, in load_model
    model = _initialize_model(vllm_config=vllm_config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/model_loader/loader.py", line 125, in _initialize_model
    return model_class(vllm_config=vllm_config, prefix=prefix)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/model_executor/models/transformers.py", line 128, in __init__
    self.vocab_size = config.vocab_size
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/transformers/configuration_utils.py", line 207, in __getattribute__
    return super().__getattribute__(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Qwen3VLMoeConfig' object has no attribute 'vocab_size'
[rank0]:[W201 01:50:12.701774995 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
Traceback (most recent call last):
  File "/usr/local/bin/vllm", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/scripts.py", line 204, in main
    args.dispatch_function(args)
  File "/usr/local/lib/python3.12/dist-packages/vllm/scripts.py", line 44, in serve
    uvloop.run(run_server(args))
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 109, in run
    return __asyncio.run(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 875, in run_server
    async with build_async_engine_client(args) as engine_client:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 136, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 230, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.
```
</details>

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by study-overflow** [comment]
Sorry for the confusion. After further investigation, I found that this issue was caused by a dependency mismatch in my environment, which resulted in an incorrect version of vLLM being used. After switching back to the vLLM version specified in the original documentation, the issue was resolved.

Thanks for the help!
