### ISSUE TITLE
How to run multiple mixtral in one machine

### ISSUE THREAD

**Issue by ToheartZhang** [vllm-project/vllm#3406]
I have an 8xA100 GPU machine. I noticed that one Mixtral instance requires at least 2 GPUs. However, when I attempt to run two Mixtral instances on the machine, each allocated 2 GPUs, the second one hangs at `Started a local Ray instance.` Additionally, the terminal reports `fork: retry: Resource temporarily unavailable`. It appears that the two Ray instances are causing a conflict. Is there any solution to resolve this issue?

**Comment by ToheartZhang** [comment]
Thanks for your help. I have specified CUDA_VISIBLE_DEVICES. Besides, multiple vllm process works when each model only needs one GPU, where Ray is not used. So I believe the issue is about setting Ray.

**Comment by ToheartZhang** [comment]
Problem solved by https://github.com/vllm-project/vllm/issues/1058
