### ISSUE TITLE
[Bug]: CUDA error: invalid argument 

### ISSUE THREAD

**Issue by qingjiaozyn** [vllm-project/vllm#3743]
### Your current environment

在A800（80G显存） 2卡机器上启动两个qwen-14B的模型，一张卡上一个模型，第一个模型启动正常，但是在启动第二个模型的时候，vllm版本是0.3.3

### 🐛 Describe the bug
WARNING 03-29 18:28:18 tokenizer.py:64] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 03-29 18:28:50 llm_engine.py:357] # GPU blocks: 3531, # CPU blocks: 327
2024-03-29 18:28:51,319 xinference.core.worker 75 ERROR    Failed to load model merge_qwen_ccb-1-0
Traceback (most recent call last):
  File "/app/xinference/xinference/core/worker.py", line 569, in launch_builtin_model
    await model_ref.load()
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "/app/xinference/xinference/core/model.py", line 239, in load
    self._model.load()
  File "/app/xinference/xinference/model/llm/vllm/core.py", line 147, in load
    self._engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 628, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 321, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 369, in _init_engine
    return engine_class(*args, **kwargs)
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 131, in __init__
    self._init_cache()
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 377, in _init_cache
    self._run_workers("init_cache_engine", cache_config=self.cache_config)
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 1041, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/worker/worker.py", line 150, in init_cache_engine
    self.cache_engine = CacheEngine(self.cache_config, self.model_config,
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/worker/cache_engine.py", line 52, in __init__
    self.cpu_cache = self.allocate_cpu_cache()
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/worker/cache_engine.py", line 106, in allocate_cpu_cache
    key_blocks = torch.empty(
RuntimeError: [address=0.0.0.0:43266, pid=897] CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2024-03-29 18:28:51,875 xinference.api.restful_api 8 ERROR    [address=0.0.0.0:43266, pid=897] CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
Traceback (most recent call last):
  File "/app/xinference/xinference/api/restful_api.py", line 793, in launch_model
    model_uid = await (
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/app/xinference/xinference/core/supervisor.py", line 803, in launch_builtin_model
    await _launch_model()
  File "/app/xinference/xinference/core/supervisor.py", line 767, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/app/xinference/xinference/core/supervisor.py", line 748, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/app/xinference/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/app/xinference/xinference/core/worker.py", line 569, in launch_builtin_model
    await model_ref.load()
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "/app/xinference/xinference/core/model.py", line 239, in load
    self._model.load()
  File "/app/xinference/xinference/model/llm/vllm/core.py", line 147, in load
    self._engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 628, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 321, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 369, in _init_engine
    return engine_class(*args, **kwargs)
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 131, in __init__
    self._init_cache()
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 377, in _init_cache
    self._run_workers("init_cache_engine", cache_config=self.cache_config)
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 1041, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/worker/worker.py", line 150, in init_cache_engine
    self.cache_engine = CacheEngine(self.cache_config, self.model_config,
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/worker/cache_engine.py", line 52, in __init__
    self.cpu_cache = self.allocate_cpu_cache()
  File "/opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/worker/cache_engine.py", line 106, in allocate_cpu_cache
    key_blocks = torch.empty(
RuntimeError: [address=0.0.0.0:43266, pid=897] CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

self._lock None， inspect.iscoroutinefunction(fn) True
inspect.isgenerator(ret) False
“”“”

**Comment by youkaichao** [comment]
Usually this is because some code sets `CUDA_VISIBLE_DEVICES` incorrectly. I would suggest you try to edit /opt/xinference/xinference_venv/lib/python3.10/site-packages/vllm/worker/cache_engine.py", line 106 , and print `torch.cuda.device_count()` and `os.environ["CUDA_VISIBLE_DEVICES"]` to see what's wrong.

In addition, it seems you are using `vllm` through `xinference`, so this might be their problem, too. Things get even more complicated because you want to start two `vllm` engine, which needs careful consideration on `CUDA_VISIBLE_DEVICES`.

**Comment by Novak-22** [comment]
你好，我想问一下你最后解决了吗？ @qingjiaozyn

**Comment by kanishkg** [comment]
https://github.com/vllm-project/vllm/issues/188#issuecomment-1609634702
This solved it for me

**Comment by 2002priyaa** [comment]
@youkaichao 
hello, i am also facing the issue on CUDA ERROR like this,

Error during CUDA Iterative FDK: itk::ERROR: CUDA ERROR: invalid argument

as i am working with rtk::CudaIterativeFDKConeBeamReconstructionFilter my getvolume function code section is given below,

itk::Image<float,3>::Pointer MainWindow::getvolume1(unsigned short *ExtBuffer, float *angles, QList<double> mDetailsD1)
{
    typedef itk::ImportImageFilter<PixelType, 3> ImportFilterType;
    ImportFilterType::Pointer importFilter = ImportFilterType::New();

    ImportFilterType::SizeType size;
    size[0] = 1536;
    size[1] = 1536;
    size[2] = 670;

    ImportFilterType::IndexType start;
    start.Fill(0);

    ImportFilterType::RegionType region;
    region.SetIndex(start);
    region.SetSize(size);

    importFilter->SetRegion(region);
    double spacing[3];
     spacing[0] = 0.278; // along X direction
     spacing[1] = 0.278; // along Y direction
     spacing[2] = 1.0;

    double origin[3];
     origin[0] =-0.5* spacing[0]*(size[0]-1);// X coordinate
     origin[1] = -0.5* spacing[1]*(size[1]-1); // Y coordinate
     origin[2] =-0.5*spacing[2]*size[2]; // Z coordinate


    importFilter->SetOrigin(origin);
    importFilter->SetSpacing(spacing);

    const unsigned int numberOfPixels = size[0] * size[1] * size[2];
     const bool importImageFilterWillOwnTheBuffer = false;
     importFilter->SetImportPointer( ExtBuffer, numberOfPixels,
     importImageFilterWillOwnTheBuffer );
     try{
     importFilter->Update();
     }
     catch(itk::ExceptionObject e){
     throw(e);
     return 0;
     }
    qDebug() << "import filter updated";

     ImageType::Pointer rval = importFilter->GetOutput();
     itk::OrientImageFilter< ImageType, ImageType>::Pointer
    orienter =itk::OrientImageFilter< ImageType,ImageType>::New();
     orienter->SetInput(rval);
     try
     {
     orienter->Update();
     qDebug() << "orienter filter updated";
     }
     catch(itk::ExceptionObject e)
     {
     throw(e);
     return 0;
     }
     orienter->GenerateOutputInformation();
     rval = orienter->GetOutput();

     typedef itk::ChangeInformationImageFilter< ImageType>
     FilterType;
      FilterType::Pointer filter = FilterType::New();
      ImageType::SpacingType pSpacing;
      pSpacing[0] = 0.278;
      pSpacing[1] =0.278;
      pSpacing[2] = 1.0;
      ImageType::PointType pOrigin;
      pOrigin[0] = -0.5* pSpacing[0]*(1536-1);
      pOrigin[1] = -0.5* pSpacing[0]*(1536-1);
      pOrigin[2] = -0.5* pSpacing[2]*670;
      filter->SetOutputOrigin(pOrigin);
      ImageType::DirectionType direction =importFilter->GetOutput()->GetDirection();
      filter->SetOutputDirection(direction);
      filter->SetOutputSpacing(pSpacing);
      filter->ChangeAll();
      filter->SetInput(rval);
      try
      {
      filter->Update();
       qDebug() << "filter updated";
      }
      catch(itk::ExceptionObject e)
      {
      throw(e);
      return 0;
      }

      typedef rtk::ThreeDCircularProjectionGeometry Geometry;
       Geometry::Pointer geo=Geometry::New();
       for (unsigned int i = 0; i < 670; ++i)
          {
          // qDebug() << "geo updated";
              geo->AddProjection(mDetailsD1.at(0),mDetailsD1.at(1),angles[i], mDetailsD1.at(2),mDetailsD1.at(3));
          }
qDebug() << "geo updated";
       try
        {
        geo->Update();
         //qDebug() << "geo updated";
        }
        catch(itk::ExceptionObject e)
        {
        throw(e);
        return 0;
        }

       typedef rtk::ThreeDCircularProjectionGeometryXMLFileWriter
       GeometryWriterType;
        GeometryWriterType::Pointer geometryWriter = GeometryWriterType::New();
        geometryWriter->SetFilename("D:\\iterative recon\\geo_cirs.xml");
        geometryWriter->SetObject(geo);
        geometryWriter->WriteFile();
        try
        {
        geo->Update();
        }
        catch(itk::ExceptionObject e)
        {
        throw(e);
        return 0;
        }

        // Create constant volume source (used by RTK later, not directly used here)
            typedef rtk::ConstantImageSource<volumeType> ConstantSourceType;
            ConstantSourceType::Pointer constVolume = ConstantSourceType::New();
            ConstantSourceType::SizeType volSize = {{512, 512, 512}};
            ConstantSourceType::SpacingType volSpacing;
            ConstantSourceType::PointType volOrigin;

            if (FanSelection == 1)
            {
                volSpacing[0] = 256.0 /(float) 512;
                volSpacing[1] = 256.0 /(float) 512;
                volSpacing[2] = 256.0 /(float) 512;
            }
            else
            {
                volSpacing[0] = 256.0 /(float) 512;
                volSpacing[1] = 256.0 /(float) 512;
                volSpacing[2] = 256.0 /(float) 512;
            }
            

            volOrigin[0] = -0.5 * (volSize[0] - 1) * volSpacing[0];
            volOrigin[1] = -0.5 * (volSize[1] - 1) * volSpacing[1];
            volOrigin[2] = -0.5 * (volSize[2] - 1) * volSpacing[2];

            constVolume->SetOrigin(volOrigin);
            constVolume->SetSpacing(volSpacing);
            constVolume->SetSize(volSize);
            constVolume->SetConstant(0);
            constVolume->Update();
            qDebug() << "constant volume updated";

        typedef
        rtk::BoellaardScatterCorrectionImageFilter<ImageType,ImageType>LagCorrectionImageFilterType1;
         LagCorrectionImageFilterType1::Pointer LagCorrection =LagCorrectionImageFilterType1::New();
         LagCorrection->SetInput(filter->GetOutput());
         LagCorrection->SetScatterToPrimaryRatio(1.2);

         try
         {
         LagCorrection->Update();
          qDebug() << "lagcorrection updated";
         }
         catch(itk::ExceptionObject e)
         {
         throw(e);
         return 0;

         }

         typedef
         rtk::I0EstimationProjectionFilter<ImageType,ImageType,3>IoFilterType;
          IoFilterType::Pointer ioFilter=IoFilterType::New();
          ioFilter->SetInput(LagCorrection->GetOutput());
          try
          {
              ioFilter->Update();
               qDebug() << "io updated";
          }
          catch(itk::ExceptionObject e)
           {
           throw(e);
           return 0;
           }

          typedef
          rtk::LUTbasedVariableI0RawToAttenuationImageFilter<ImageType,volumeType> ConvertFilterType;
           ConvertFilterType::Pointer convert = ConvertFilterType::New();
           convert->SetInput(ioFilter->GetOutput());
           try
           {
           convert->Update();
           qDebug() << "lut updated";
           }
           catch(itk::ExceptionObject e)
           {
           throw(e);
           return 0;
           }

              using DDFOFFFOVType =
              rtk::DisplacedDetectorForOffsetFieldOfViewImageFilter<volumeType>;
              DDFOFFFOVType::Pointer ddf;
              ddf = DDFOFFFOVType::New();
              ddf->SetInput(convert->GetOutput());
              ddf->SetGeometry(geo);

            typedef rtk::ParkerShortScanImageFilter<volumeType> PSSFType;
            PSSFType::Pointer pssf = PSSFType::New();
            pssf->SetInput(ddf->GetOutput());
            pssf->SetGeometry(geo);
            pssf->InPlaceOff();
            try
            {
            pssf->Update();
            qDebug() << "pssf updated";
            }
            catch(itk::ExceptionObject e)
            {
            throw(e);
            return 0;
            }
            std::cout << "Volume spacing: " << constVolume->GetOutput()->GetSpacing() << std::endl;
            std::cout << "Projection spacing: " << pssf->GetOutput()->GetSpacing() << std::endl;



            typedef rtk::CudaIterativeFDKConeBeamReconstructionFilter IterativeFDKType;

            IterativeFDKType::Pointer IterativeFDK = IterativeFDKType::New();

            IterativeFDK->SetInput(0, constVolume->GetOutput());
            IterativeFDK->SetInput(1, pssf->GetOutput());
            IterativeFDK->SetGeometry(geo);
            std::cout << IterativeFDK->GetInput(0)->GetNameOfClass() << std::endl;
            std::cout << IterativeFDK->GetInput(1)->GetNameOfClass() << std::endl;

            IterativeFDK->SetProjectionSubsetSize(1);
            IterativeFDK->SetLambda(1.0f);

            IterativeFDK->SetNumberOfIterations(3);

            IterativeFDK->SetForwardProjectionFilter(0); // Joseph
            IterativeFDK->SetBackProjectionFilter(0);// CudaVoxelBased

            IterativeFDK->SetEnforcePositivity(true);

            IterativeFDK->SetHannCutFrequency(0.3);
            //IterativeFDK->SetTruncationCorrection(1.0);
             IterativeFDK->SetGPUEnabled(true);  // Make sure GPU is enabled (usually default)

            qDebug() <<  "iterativeFDK parameter is set";
            IterativeFDK->UpdateOutputInformation(); // before .Update()

            cudaSetDevice(0);  // Explicitly initialize GPU context
            cudaDeviceSynchronize(); // Ensure previous kernels finished

            try {
                IterativeFDK->Update();
                qDebug() << "CUDA Iterative FDK completed successfully.";
            } catch (itk::ExceptionObject &e) {
                qCritical() << "Error during CUDA Iterative FDK:" << e.GetDescription();
                return nullptr;
            }


             typedef rtk::FieldOfViewImageFilter<volumeType,volumeType>
             FOVFilterType;

             FOVFilterType::Pointer fov=FOVFilterType::New();
             fov->SetInput(0,  IterativeFDK->GetOutput());
             fov->SetProjectionsStack(ddf->GetOutput());
             fov->SetGeometry(geo);
             try
             {
             fov->Update();
             }
             catch(itk::ExceptionObject e)
             {
             throw(e);
             }
what's wrong in this can you please tell me.
