### ISSUE TITLE
[Bug]: cuda graph takes too much memory for qwen 3.5

### ISSUE THREAD

**Issue by ErykCh** [vllm-project/vllm#38486]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
Your output of `python collect_env.py` here
```

</details>

### 🐛 Describe the bug

Hi,

everything is OK with enforce eager:

docker run --runtime nvidia --gpus all -d --name vllm-Qwen35_35B_fp8_v20 --restart unless-stopped -v ~/.cache/huggingface/hub:/models -v ~/.cache/vllm:/root/.cache/vllm -v ~/.cache/huggingface:/root/.cache/huggingface -p 8000:8000 vllm/vllm-openai:v0.18.0 --model Qwen/Qwen3.5-35B-A3B-FP8 --served-model-name llm vllm-local vllm --enforce-eager

but generation speed is very slow: 14.43 tokens per second

int4 version (Qwen/Qwen3.5-35B-A3B-GPTQ-Int4)  gives me: 109.97 tokens per second
but with cuda graph

but I can't remove enforce-eager flag, because of out of memory.

Probably there is problem with cuda graph.

from logs: Model loading took 33.38 GiB memory and 21.582860 seconds

So after loading weight 33 gb of memory of occupied, but I have 44 gb of memory:

from logs: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.03 GiB. GPU 0 has a total capacity of 44.40 GiB of which 858.31 MiB is free.

even when max model length is set to 1024:
docker run --runtime nvidia --gpus all -d --name vllm-Qwen35_35B_fp8_v23 --restart unless-stopped -v ~/.cache/huggingface/hub:/models -v ~/.cache/vllm:/root/.cache/vllm -v ~/.cache/huggingface:/root/.cache/huggingface -p 8000:8000 vllm/vllm-openai:v0.18.0 --model Qwen/Qwen3.5-35B-A3B-FP8 --served-model-name llm vllm-local vllm --max-model-len 1024 --language-model-only

logs:

(EngineCore pid=86) INFO 03-29 18:32:46 [backends.py:371] Cache the graph of compile range (1, 2048) for later use
(EngineCore pid=86) INFO 03-29 18:33:05 [backends.py:387] Compiling a graph for compile range (1, 2048) takes 22.84 s
(EngineCore pid=86) INFO 03-29 18:33:07 [monitor.py:48] torch.compile took 33.00 s in total
(EngineCore pid=86) INFO 03-29 18:34:26 [monitor.py:76] Initial profiling/warmup run took 78.59 s

and than:

(EngineCore pid=86) ERROR 03-29 18:34:32 [core.py:1099]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 6229, in _allocate_kv_cache_tensors
(EngineCore pid=86) ERROR 03-29 18:34:32 [core.py:1099]     tensor = torch.zeros(
(EngineCore pid=86) ERROR 03-29 18:34:32 [core.py:1099]              ^^^^^^^^^^^^
(EngineCore pid=86) ERROR 03-29 18:34:32 [core.py:1099] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.03 GiB. GPU 0 has a total capacity of 44.40 GiB of which 858.31 MiB is free. Process 12865 has 43.56 GiB memory in use. Of the allocated memory 42.94 GiB is allocated by PyTorch, and 101.36 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by ErykCh** [comment]
so what I've achieved till now,

and this configuration is working solution:

docker run --runtime nvidia --gpus all -d --name vllm-Qwen35_35B_fp8_v35 --restart unless-stopped -v ~/.cache/huggingface/hub:/models -v ~/.cache/vllm:/root/.cache/vllm -v ~/.cache/huggingface:/root/.cache/huggingface -e PYTORCH_ALLOC_CONF=expandable_segments:True -e VLLM_LOGGING_LEVEL=INFO -e VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 -p 8000:8000 vllm/vllm-openai:v0.18.0 --model Qwen/Qwen3.5-35B-A3B-FP8 --served-model-name llm vllm-local vllm --max-model-len 50000 --max-num-batched-tokens 50000 --max-num-seqs 1 --max-cudagraph-capture-size 4  --gpu-memory-utilization 0.99 --language-model-only --speculative-config '{"method":"mtp","num_speculative_tokens":3}' --calculate-kv-scales --kv-cache-metrics --cudagraph-metrics --enable-mfu-metrics --enable-logging-iteration-details --enable-flashinfer-autotune --performance-mode interactivity --enable-log-requests


it seems that there is possibility to minimalize memory occupied during cuda graphs calculations

logs:

Model loading took 34.18 GiB memory and 24.658857 seconds
Cache the graph of compile range (1, 50000) for later use
Compiling a graph for compile range (1, 50000) takes 92.12 s
Initial profiling/warmup run took 82.62 s

Overriding num_gpu_blocks=0 with num_gpu_blocks_override=4
Profiling CUDA graph memory: PIECEWISE=1 (largest=4), FULL=1 (largest=4)

 UserWarning: Input tensor shape suggests potential format mismatch: seq_len (4) < num_heads (16). This may indicate the inputs were passed in head-first format [B, H, T, ...] Please verify your input tensor format matches the expected shape [B, T, H, ...].

Estimated CUDA graph memory: 0.06 GiB total
Available KV cache memory: 2.18 GiB
GPU KV cache size: 25,728 tokens
 Maximum concurrency for 50,000 tokens per request: 1.63x

 Graph capturing finished in 2 secs, took 0.03 GiB
CUDA graph pool memory: 0.03 GiB (actual), 0.06 GiB (estimated), difference: 0.04 GiB (128.6%).
init engine (profile, create kv cache, warmup model) took 258.15 seconds



so logs doesn't make any sens

2gb of available memory, space for 25k tokens, accepting 50k tokens of max model length, and this gives 1,63x concurrent requests

but it's now working

so for sure there is a lot of bugs

with not freeing memory after cuda graphs creation and before kv cache
incorect calculations for kv cache size

**Comment by ZJY0516** [comment]
try to set `--max-cudagraph-capture-size` manually

**Comment by samlkrystof** [comment]
I'm seeing the same issue with Qwen3.5-27B-FP8 and Qwen3.5-35B-A3B-FP8 on L40S. Confirmed it's a regression from #30515, profile_cudagraph_memory() OOMs during the profiling step itself, before KV cache is even sized. Works fine on v0.17.1 where this method doesn't exist.                                                                                                                                                
The VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS flag doesn't help because it only controls whether the estimate is applied, not whether the profiling runs.     

I'm working on a fix,  catching torch.OutOfMemoryError in determine_available_memory() and falling back to estimate=0 (v0.17.1 behavior). Will open a PR soon.

**Comment by veropeaky** [comment]
I meet the same question when I use dflash as qwen3.6-35b-a3b's speculative decoding method. Fortunately, A800 has engough VRAM to deploy, which makes it's acessable for me to observe gpu kv cache usage
when I use Dflash, the available kv cache size is 227k, actually, the gpu kv cache usage is 87% under the 32 request with 1.5k prompt and 1k output
I assume that the kv cache allocation is not valid
