### ISSUE TITLE
[Bug]: v0.19.1 Crash with CUDA invalid argument / Segfault when using KV Offloading + EAGLE3 + Expert Parallel (on 8x H20 141GB)

### ISSUE THREAD

**Issue by BenWongCityuCS** [vllm-project/vllm#40259]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
(base) user1@user1:/ssd1/tmp$ python3 collect_env.py
Collecting environment information...
==============================
        System Info
==============================
OS                           : Ubuntu 22.04.4 LTS (x86_64)
GCC version                  : (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0
Clang version                : Could not collect
CMake version                : Could not collect
Libc version                 : glibc-2.35

==============================
       PyTorch Info
==============================
PyTorch version              : 2.9.0+cu128
Is debug build               : False
CUDA used to build PyTorch   : 12.8
ROCM used to build PyTorch   : N/A
XPU used to build PyTorch    : N/A

==============================
      Python Environment
==============================
Python version               : 3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:16:10) [GCC 11.2.0] (64-bit runtime)
Python platform              : Linux-5.15.0-94-generic-x86_64-with-glibc2.35

==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : 12.6.85
CUDA_MODULE_LOADING set to   :
GPU models and configuration :
GPU 0: NVIDIA H20-3e
GPU 1: NVIDIA H20-3e
GPU 2: NVIDIA H20-3e
GPU 3: NVIDIA H20-3e
GPU 4: NVIDIA H20-3e
GPU 5: NVIDIA H20-3e
GPU 6: NVIDIA H20-3e
GPU 7: NVIDIA H20-3e

Nvidia driver version        : 570.86.15
cuDNN version                : Could not collect
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      52 bits physical, 57 bits virtual
Byte Order:                         Little Endian
CPU(s):                             192
On-line CPU(s) list:                0-191
Vendor ID:                          GenuineIntel
Model name:                         INTEL(R) XEON(R) PLATINUM 8558
CPU family:                         6
Model:                              207
Thread(s) per core:                 2
Core(s) per socket:                 48
Socket(s):                          2
Stepping:                           2
CPU max MHz:                        4000.0000
CPU min MHz:                        800.0000
BogoMIPS:                           4200.00
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
Virtualization:                     VT-x
L1d cache:                          4.5 MiB (96 instances)
L1i cache:                          3 MiB (96 instances)
L2 cache:                           192 MiB (96 instances)
L3 cache:                           520 MiB (2 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0-47,96-143
NUMA node1 CPU(s):                  48-95,144-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

==============================
Versions of relevant libraries
==============================
[pip3] flashinfer-python==0.5.3
[pip3] numpy==2.2.6
[pip3] nvidia-cublas-cu12==12.8.4.1
[pip3] nvidia-cuda-cupti-cu12==12.8.90
[pip3] nvidia-cuda-nvrtc-cu12==12.8.93
[pip3] nvidia-cuda-runtime-cu12==12.8.90
[pip3] nvidia-cudnn-cu12==9.10.2.21
[pip3] nvidia-cudnn-frontend==1.16.0
[pip3] nvidia-cufft-cu12==11.3.3.83
[pip3] nvidia-cufile-cu12==1.13.1.3
[pip3] nvidia-curand-cu12==10.3.9.90
[pip3] nvidia-cusolver-cu12==11.7.3.90
[pip3] nvidia-cusparse-cu12==12.5.8.93
[pip3] nvidia-cusparselt-cu12==0.7.1
[pip3] nvidia-cutlass==4.2.0.0
[pip3] nvidia-cutlass-dsl==4.3.2
[pip3] nvidia-ml-py==13.580.82
[pip3] nvidia-nccl-cu12==2.27.5
[pip3] nvidia-nvjitlink-cu12==12.8.93
[pip3] nvidia-nvshmem-cu12==3.3.20
[pip3] nvidia-nvtx-cu12==12.8.90
[pip3] pyzmq==27.1.0
[pip3] torch==2.9.0
[pip3] torchaudio==2.9.0
[pip3] torchvision==0.24.0
[pip3] transformers==4.57.3
[pip3] triton==3.5.0
[conda] cuda-cccl_linux-64                   12.6.77          0                   nvidia
[conda] cuda-command-line-tools              12.6.3           0                   nvidia
[conda] cuda-compiler                        12.6.3           0                   nvidia
[conda] cuda-crt-dev_linux-64                12.6.85          0                   nvidia
[conda] cuda-crt-tools                       12.6.85          0                   nvidia
[conda] cuda-cudart                          12.6.77          0                   nvidia
[conda] cuda-cudart-dev                      12.6.77          0                   nvidia
[conda] cuda-cudart-dev_linux-64             12.6.77          0                   nvidia
[conda] cuda-cudart-static                   12.6.77          0                   nvidia
[conda] cuda-cudart-static_linux-64          12.6.77          0                   nvidia
[conda] cuda-cudart_linux-64                 12.6.77          0                   nvidia
[conda] cuda-cuobjdump                       12.6.77          0                   nvidia
[conda] cuda-cupti                           12.6.80          0                   nvidia
[conda] cuda-cupti-dev                       12.6.80          0                   nvidia
[conda] cuda-cuxxfilt                        12.6.77          0                   nvidia
[conda] cuda-driver-dev                      12.6.77          0                   nvidia
[conda] cuda-driver-dev_linux-64             12.6.77          0                   nvidia
[conda] cuda-gdb                             12.6.77          0                   nvidia
[conda] cuda-libraries                       12.6.3           0                   nvidia
[conda] cuda-libraries-dev                   12.6.3           0                   nvidia
[conda] cuda-nsight                          12.6.77          0                   nvidia
[conda] cuda-nvcc                            12.6.85          0                   nvidia
[conda] cuda-nvcc-dev_linux-64               12.6.85          0                   nvidia
[conda] cuda-nvcc-impl                       12.6.85          0                   nvidia
[conda] cuda-nvcc-tools                      12.6.85          0                   nvidia
[conda] cuda-nvcc_linux-64                   12.6.85          0                   nvidia
[conda] cuda-nvdisasm                        12.6.77          0                   nvidia
[conda] cuda-nvml-dev                        12.6.77          2                   nvidia
[conda] cuda-nvprof                          12.6.80          0                   nvidia
[conda] cuda-nvprune                         12.6.77          0                   nvidia
[conda] cuda-nvrtc                           12.6.85          0                   nvidia
[conda] cuda-nvrtc-dev                       12.6.85          0                   nvidia
[conda] cuda-nvtx                            12.6.77          0                   nvidia
[conda] cuda-nvvm-dev_linux-64               12.6.85          0                   nvidia
[conda] cuda-nvvm-impl                       12.6.85          0                   nvidia
[conda] cuda-nvvm-tools                      12.6.85          0                   nvidia
[conda] cuda-nvvp                            12.6.80          0                   nvidia
[conda] cuda-opencl                          12.6.77          0                   nvidia
[conda] cuda-opencl-dev                      12.6.77          0                   nvidia
[conda] cuda-profiler-api                    12.6.77          0                   nvidia
[conda] cuda-sanitizer-api                   12.6.77          0                   nvidia
[conda] cuda-toolkit                         12.6.3           0                   nvidia
[conda] cuda-tools                           12.6.3           0                   nvidia
[conda] cuda-visual-tools                    12.6.3           0                   nvidia
[conda] flashinfer-python                    0.5.3            pypi_0              pypi
[conda] gds-tools                            1.11.1.6         0                   nvidia
[conda] libcublas                            12.6.4.1         0                   nvidia
[conda] libcublas-dev                        12.6.4.1         0                   nvidia
[conda] libcufft                             11.3.0.4         0                   nvidia
[conda] libcufft-dev                         11.3.0.4         0                   nvidia
[conda] libcufile                            1.11.1.6         0                   nvidia
[conda] libcufile-dev                        1.11.1.6         0                   nvidia
[conda] libcurand                            10.3.7.77        0                   nvidia
[conda] libcurand-dev                        10.3.7.77        0                   nvidia
[conda] libcusolver                          11.7.1.2         0                   nvidia
[conda] libcusolver-dev                      11.7.1.2         0                   nvidia
[conda] libcusparse                          12.5.4.2         0                   nvidia
[conda] libcusparse-dev                      12.5.4.2         0                   nvidia
[conda] libnpp                               12.2.5.30        0                   nvidia
[conda] libnpp-dev                           12.2.5.30        0                   nvidia
[conda] libnvfatbin                          12.6.77          0                   nvidia
[conda] libnvfatbin-dev                      12.6.77          0                   nvidia
[conda] libnvjitlink                         12.6.85          0                   nvidia
[conda] libnvjitlink-dev                     12.6.85          0                   nvidia
[conda] libnvjpeg                            12.3.1.117       0                   nvidia
[conda] libnvjpeg-dev                        12.3.1.117       0                   nvidia
[conda] nsight-compute                       2024.3.2.3       0                   nvidia
[conda] numpy                                2.2.6            pypi_0              pypi
[conda] nvidia-cublas-cu12                   12.8.4.1         pypi_0              pypi
[conda] nvidia-cuda-cupti-cu12               12.8.90          pypi_0              pypi
[conda] nvidia-cuda-nvrtc-cu12               12.8.93          pypi_0              pypi
[conda] nvidia-cuda-runtime-cu12             12.8.90          pypi_0              pypi
[conda] nvidia-cudnn-cu12                    9.10.2.21        pypi_0              pypi
[conda] nvidia-cudnn-frontend                1.16.0           pypi_0              pypi
[conda] nvidia-cufft-cu12                    11.3.3.83        pypi_0              pypi
[conda] nvidia-cufile-cu12                   1.13.1.3         pypi_0              pypi
[conda] nvidia-curand-cu12                   10.3.9.90        pypi_0              pypi
[conda] nvidia-cusolver-cu12                 11.7.3.90        pypi_0              pypi
[conda] nvidia-cusparse-cu12                 12.5.8.93        pypi_0              pypi
[conda] nvidia-cusparselt-cu12               0.7.1            pypi_0              pypi
[conda] nvidia-cutlass                       4.2.0.0          pypi_0              pypi
[conda] nvidia-cutlass-dsl                   4.3.2            pypi_0              pypi
[conda] nvidia-ml-py                         13.580.82        pypi_0              pypi
[conda] nvidia-nccl-cu12                     2.27.5           pypi_0              pypi
[conda] nvidia-nvjitlink-cu12                12.8.93          pypi_0              pypi
[conda] nvidia-nvshmem-cu12                  3.3.20           pypi_0              pypi
[conda] nvidia-nvtx-cu12                     12.8.90          pypi_0              pypi
[conda] pyzmq                                27.1.0           pypi_0              pypi
[conda] torch                                2.9.0            pypi_0              pypi
[conda] torchaudio                           2.9.0            pypi_0              pypi
[conda] torchvision                          0.24.0           pypi_0              pypi
[conda] transformers                         4.57.3           pypi_0              pypi
[conda] triton                               3.5.0            pypi_0              pypi

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
vLLM Version                 : 0.12.0
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled; XPU: Disabled
GPU Topology:
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NV18    NV18    NV18    NV18    NV18    NV18    PIX     NODE    NODE    NODE    SYS     SYS0-47,96-143      0               N/A
GPU1    NV18     X      NV18    NV18    NV18    NV18    NV18    NV18    PIX     NODE    NODE    NODE    SYS     SYS0-47,96-143      0               N/A
GPU2    NV18    NV18     X      NV18    NV18    NV18    NV18    NV18    NODE    NODE    NODE    PIX     SYS     SYS0-47,96-143      0               N/A
GPU3    NV18    NV18    NV18     X      NV18    NV18    NV18    NV18    NODE    NODE    NODE    PIX     SYS     SYS0-47,96-143      0               N/A
GPU4    NV18    NV18    NV18    NV18     X      NV18    NV18    NV18    SYS     SYS     SYS     SYS     PIX     NODE48-95,144-191   1               N/A
GPU5    NV18    NV18    NV18    NV18    NV18     X      NV18    NV18    SYS     SYS     SYS     SYS     PIX     NODE48-95,144-191   1               N/A
GPU6    NV18    NV18    NV18    NV18    NV18    NV18     X      NV18    SYS     SYS     SYS     SYS     NODE    PIX48-95,144-191    1               N/A
GPU7    NV18    NV18    NV18    NV18    NV18    NV18    NV18     X      SYS     SYS     SYS     SYS     NODE    PIX48-95,144-191    1               N/A
NIC0    PIX     PIX     NODE    NODE    SYS     SYS     SYS     SYS      X      NODE    NODE    NODE    SYS     SYS
NIC1    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE     X      PIX     NODE    SYS     SYS
NIC2    NODE    NODE    NODE    NODE    SYS     SYS     SYS     SYS     NODE    PIX      X      NODE    SYS     SYS
NIC3    NODE    NODE    PIX     PIX     SYS     SYS     SYS     SYS     NODE    NODE    NODE     X      SYS     SYS
NIC4    SYS     SYS     SYS     SYS     PIX     PIX     NODE    NODE    SYS     SYS     SYS     SYS      X      NODE
NIC5    SYS     SYS     SYS     SYS     NODE    NODE    PIX     PIX     SYS     SYS     SYS     SYS     NODE     X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
  NIC4: mlx5_4
  NIC5: mlx5_5

==============================
     Environment Variables
==============================
TORCHINDUCTOR_CACHE_DIR=/ssd2/cache/torchinductor/user1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
```

</details>

### Environment
- **vLLM version:** v0.19.1 (docker: `vllm/vllm-openai:v0.19.1`)  
  *Note: Host environment has v0.12.0, but bug is reproduced in v0.19.1 container*
- **Hardware:** 8× NVIDIA H20-3e (141GB) — Total VRAM ~1.1TB
- **CPU:** 2× Intel Xeon Platinum 8558 (192 cores, 2 NUMA nodes)
- **System:** 2TB RAM, Ubuntu 22.04, NVIDIA Driver 570.86.15, CUDA 12.6/12.8
- **Interconnect:** NV18 (18 NVLinks) fully connected mesh
- **Model:** moonshot-ai/Kimi-K2.5 (compressed-tensors, ~72GB)
- **Draft model:** moonshot-ai/Kimi-K2.5-Eagle3 (EAGLE3 speculative decoding)

### Problem Description
When running Kimi-K2.5 with **EAGLE3 speculative decoding** and **Expert Parallel (EP)** enabled, the presence of `--kv-offloading-size` causes a **fatal cascade failure** (segfault → NVLink corruption → distributed crash) once context length exceeds the configured GPU block limit.

**Critical observation:** With 8× H20-3e (1.1TB+ VRAM available after model weights), the system should never need offloading for 32K context. Instead of graceful operation, the configuration triggers memory corruption.

### Reproduction Command
```bash
docker run --rm -it \
    --gpus all \
    -e VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 \
    -p 8000:8000 \
    -v /data:/model_files \
    vllm/vllm-openai:v0.19.1 \
    /model_files/Kimi-K2.5 \
    --tensor-parallel-size 8 \
    --enable-expert-parallel \
    --enable-ep-weight-filter \
    --compilation-config '{"pass_config": {"fuse_allreduce_rms": true}}' \
    --kv-cache-dtype fp8 \
    --speculative-config '{"model": "/model_files/Kimi-K2.5-Eagle3", "method": "eagle3", "num_speculative_tokens": 3}' \
    --gpu-memory-utilization 0.95 \
    --max-num-batched-tokens 16384 \
    --kv-offloading-size 400 \  # <--- Trigger
    --max-num-seqs 25 \
    --enable-chunked-prefill \
    --enable-prefix-caching \
    --host 0.0.0.0 \
    --port 8000 \
    --trust-remote-code
```

### Trigger Condition
Context length exceeding configured block capacity:
- **Block size:** 64 tokens
- **Configured:** 400 blocks (25,600 tokens)
- **Actual request:** 32,768 tokens (512 blocks needed)
- **Available VRAM:** >1TB unused (should not require offloading)

#### 1. Root Cause (Invalid CUDA memory access)
```python
# gpu_model_runner.py:1997
self.num_computed_tokens[req_indices_gpu].to(torch.int64)
# req_indices_gpu contains indices for offloaded CPU blocks
torch.AcceleratorError: CUDA error: invalid argument
```

#### 2. Memory Corruption (Segfault)
```
!!!!!!! Segfault encountered !!!!!!!
cuMemcpyDtoHAsync_v2  # <--- Crashes in swap_blocks
```

#### 3. NVLink Topology Corruption
```
CUDA error: Invalid access of peer GPU memory over nvlink 
or a hardware error
```

#### 4. Distributed System Death
```
TCPStore: Failed to recv, got 0 bytes
Worker proc VllmWorker-2 died unexpectedly
8 workers cascade failure
```

### Workaround
**Remove `--kv-offloading-size` completely.** With 8× H20-3e 141GB, sufficient VRAM exists for 32K+ context without offloading.

### Analysis
The V1 engine `_prepare_inputs` assumes `num_computed_tokens` is contiguous GPU memory, but `OffloadingConnector` marks certain indices for CPU residence. When `req_indices_gpu` includes these offloaded indices, invalid memory access occurs.

**Compounded by:** EAGLE3 (dual KV caches) + EP (8-way tensor parallel) create state inconsistency in the connector metadata.

### System Topology Details
```
GPU Topology: 8× H20-3e, fully connected NV18 (18 NVLinks)
NUMA: 2 nodes, 192 cores (Intel Xeon Platinum 8558)
Affinity: GPUs 0-3 on NUMA 0, GPUs 4-7 on NUMA 1
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by BenWongCityuCS** [comment]
【Root Cause - CUDA Invalid Argument】
File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 1997, in _prepare_inputs
    self.num_computed_tokens[req_indices_gpu].to(torch.int64)
torch.AcceleratorError: CUDA error: invalid argument (cudaErrorInvalidValue)

【Hardware Segfault - NVLink/Peer Memory Access】
# Multiple workers (TP3-TP7) crashed simultaneously
File "<unknown>", line 0, in cuMemcpyDtoHAsync_v2
File "<unknown>", line 0, in cudaMemcpyAsync  
File "<unknown>", line 0, in swap_blocks(at::Tensor&, at::Tensor&, long, at::Tensor const&)
CUDA error: Invalid access of peer GPU memory over nvlink or a hardware error

【Distributed Communication Failure】
File "/pytorch/torch/csrc/distributed/c10d/TCPStore.cpp", line 125
[c10d] recvValue failed on SocketImpl: Failed to recv, got 0 bytes. Connection was likely closed.
Exception raised from recvBytes at /pytorch/torch/csrc/distributed/c10d/Utils.hpp:682

File "/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp", line 1802
Failed to check the "should dump" flag on TCPStore: Broken pipe

【Engine Cascade Failure】
File "/usr/local/lib/python3.12/dist-packages/vllm/v1/executor/multiproc_executor.py", line 273
Worker proc VllmWorker-2 died unexpectedly, shutting down executor.

File "/usr/local/lib/python3.12/dist-packages/vllm/distributed/device_communicators/shm_broadcast.py", line 677, in acquire_read
    raise RuntimeError("cancelled")
RuntimeError: cancelled

File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1110
EngineCore encountered a fatal error.

File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 985
vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue.

**Key Context Information:**

**Trigger Point:** `gpu_model_runner.py:1997` - Invalid GPU index passed when accessing `num_computed_tokens`

**Propagation Chain:** CUDA Error → Segfault (swap_blocks/NVLink) → Worker Death → TCPStore Disconnection → Engine Cascade Failure

**Configuration:** vLLM V1, TP=8, EAGLE3 speculative decoding, FP8 KV Cache, Kimi-K2.5 model

**Impact Scope:** Multiple TP Workers (TP3, TP4, TP5, TP6, TP7) crashed simultaneously, involving NVLink peer memory access

**Comment by orozery** [comment]
Can you check with #39617 ?

**Comment by BenWongCityuCS** [comment]
> Can you check with [#39617](https://github.com/vllm-project/vllm/pull/39617) ?

I haven't been able to test #39617 yet since v0.19.1 doesn't include that commit (and I haven't built from the main branch).
However, during testing, I discovered that my original issue in #40259 might actually be **two separate bugs**:
1. **The KV offloading issue** you mentioned (fixed by #39617) - I still need to verify this
2. **A distinct FP8-related bug** that I just filed as #40435
The new issue (#40435) reproduces **without** any `--kv-offloading-size` parameter, and is specifically triggered by `--kv-cache-dtype fp8` + Expert Parallel + EAGLE3 under concurrent load. Removing `--kv-cache-dtype fp8` (using default) results in 100% success rate (120/120 requests), while with fp8 it crashes in `mla_attention.py:1733`.
Could you help confirm if #40435 is indeed distinct from #39617's fix scope? Thanks!

**Comment by BenWongCityuCS** [comment]
> Can you check with [#39617](https://github.com/vllm-project/vllm/pull/39617) ?

@orozery — following up with a controlled test to isolate the variables:

I pulled the newer `**vllm/vllm-openai:deepseekv4-cu130**` image (published after v0.19.1), which I understand should carry the prior offloading fixes, including #39617.
To rule out the FP8 issue I filed separately in #40435, I **completely removed `--kv-cache-dtype fp8`** from the launch config.

**The crash still reproduces.**

### Clean error this time
```text
RuntimeError: cuMemcpyBatchAsync failed at index 63 with error 1
```
with the backtrace terminating at:
```text
File ".../vllm/v1/kv_offload/worker/cpu_gpu.py", line 232, in transfer_async
    ops.swap_blocks_batch(batch_src, batch_dst, batch_sizes)
```

### Context
The failure happens during `handle_preemptions` while the `OffloadingConnectorMetadata` is attempting to **store** blocks to CPU (`reqs_to_store` is non-empty for one of the running requests). All 8 TP workers hit the same `cuMemcpyBatchAsync` failure and then assert out.

### Implications
- This confirms the FP8 bug (#40435) is **distinct** from the offloading crash.
- **#40259 is NOT resolved** simply by moving past v0.19.1 or dropping FP8.
- If #39617 is already in this image, then the `UniformTypeKVCacheSpecs` sizing fix does **not** cover whatever invalid pointer/size is being fed into the batch memcpy during TP=8 + EAGLE3 preemption swaps.

Let me know if you'd like the full scheduler dump from the failure or if there's a specific commit beyond `deepseekv4-cu130` you'd like me to validate.


docker run --rm -it --name vllm-kimi-k2.6 \
    --gpus all \
    --ipc=host \
    --ulimit memlock=-1 \
    --ulimit stack=67108864 \
    -e VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 \
    -p 8000:8000 \
    -v /model_files:/model_files \
    vllm/vllm-openai:deepseekv4-cu130 \
    /model_files/kimi-k2.6 \
    --tensor-parallel-size 8 \
    --compilation-config '{"pass_config": {"fuse_allreduce_rms": true}}' \
    --speculative-config '{"model": "/model_files/kimi-k2.6-eagle3", "method": "eagle3", "num_speculative_tokens": 3}' \
    --gpu-memory-utilization 0.90 \
    --max-num-batched-tokens 16384 \
    --mm-encoder-tp-mode data \
    --mm-processor-cache-type shm \
    --mm-processor-cache-gb 128 \
    --kv-offloading-size 200 \
    --max-num-seqs 25 \
    --enable-chunked-prefill \
    --enable-prefix-caching \
    --host 0.0.0.0 \
    --port 8000 \
    --enable-auto-tool-choice \
    --trust-remote-code \
    --tool-call-parser kimi_k2 \
    --reasoning-parser kimi_k2 \
    --disable-hybrid-kv-cache-manager

**Comment by ywang96** [comment]
Can you give a try to https://github.com/vllm-project/vllm/pull/37160? (aka set `export VLLM_USE_SIMPLE_KV_OFFLOAD=1`)

**Comment by orozery** [comment]
> I pulled the newer `**vllm/vllm-openai:deepseekv4-cu130**` image (published after v0.19.1), which I understand should carry the prior offloading fixes, including [#39617](https://github.com/vllm-project/vllm/pull/39617).

I tried to understand the vllm version for this image.
```
$ docker run --rm --entrypoint python3 vllm/vllm-openai:deepseekv4-cu130 -c "import vllm; print(vllm.__version__)"
0.1.dev15833+g62d441ee8
```

Can't find this commit hash in vllm repo.

Anyhow, I manually checked the file that was fixed in #39617 but it is not fixed.

In other words, `vllm/vllm-openai:deepseekv4-cu130` does not contain the #39617 fix.

**Comment by BenWongCityuCS** [comment]
> > I pulled the newer `**vllm/vllm-openai:deepseekv4-cu130**` image (published after v0.19.1), which I understand should carry the prior offloading fixes, including [#39617](https://github.com/vllm-project/vllm/pull/39617).
> 
> I tried to understand the vllm version for this image.
> 
> ```
> $ docker run --rm --entrypoint python3 vllm/vllm-openai:deepseekv4-cu130 -c "import vllm; print(vllm.__version__)"
> 0.1.dev15833+g62d441ee8
> ```
> 
> Can't find this commit hash in vllm repo.
> 
> Anyhow, I manually checked the file that was fixed in [#39617](https://github.com/vllm-project/vllm/pull/39617) but it is not fixed.
> 
> In other words, `vllm/vllm-openai:deepseekv4-cu130` does not contain the [#39617](https://github.com/vllm-project/vllm/pull/39617) fix.

@orozery Sorry for the trouble, and thanks for catching that!

I’ll verify first whether the fix from #39617 is actually present in the cu129-nightly-8cd174fa358326d5cc4195446be2ebcd65c481ce image by checking the relevant file directly. I’ll update my findings here once I’ve confirmed it, instead of jumping to conclusions again.

**Comment by BenWongCityuCS** [comment]
> > I pulled the newer `**vllm/vllm-openai:deepseekv4-cu130**` image (published after v0.19.1), which I understand should carry the prior offloading fixes, including [#39617](https://github.com/vllm-project/vllm/pull/39617).
> 
> I tried to understand the vllm version for this image.
> 
> ```
> $ docker run --rm --entrypoint python3 vllm/vllm-openai:deepseekv4-cu130 -c "import vllm; print(vllm.__version__)"
> 0.1.dev15833+g62d441ee8
> ```
> 
> Can't find this commit hash in vllm repo.
> 
> Anyhow, I manually checked the file that was fixed in [#39617](https://github.com/vllm-project/vllm/pull/39617) but it is not fixed.
> 
> In other words, `vllm/vllm-openai:deepseekv4-cu130` does not contain the [#39617](https://github.com/vllm-project/vllm/pull/39617) fix.

@orozery You were right. I switched to the newer `cu129-nightly-8cd174fa358326d5cc4195446be2ebcd65c481ce` image and re-ran the exact same offloading config. The crashes are gone and all requests completed successfully.

**Serve command:**
```bash
docker run --rm -it \
    --gpus all \
    -e VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 \
    -p 8000:8000 \
    -v /ssd1:/model_files \
    vllm/vllm-openai:cu129-nightly-8cd174fa358326d5cc4195446be2ebcd65c481ce \
    /model_files/Kimi-K2.5 \
    --tensor-parallel-size 8 \
    --enable-expert-parallel \
    --enable-ep-weight-filter \
    --compilation-config '{"pass_config": {"fuse_allreduce_rms": true}}' \
    --kv-cache-dtype fp8 \
    --speculative-config '{"model": "/model_files/Kimi-K2.5-Eagle3", "method": "eagle3", "num_speculative_tokens": 3}' \
    --gpu-memory-utilization 0.95 \
    --max-num-batched-tokens 16384 \
    --kv-offloading-size 400 \
    --max-num-seqs 25 \
    --enable-chunked-prefill \
    --enable-prefix-caching \
    --host 0.0.0.0 \
    --port 8000 \
    --trust-remote-code \
    --disable-hybrid-kv-cache-manager
```

**Benchmark commands & results:**
```bash
# Test 1: random, 120 prompts, 20 req/s, max-concurrency 20
vllm bench serve --host localhost --port 8000 --endpoint /v1/chat/completions --model /model_files/Kimi-K2.5 --tokenizer /ssd1/Kimi-K2.5 --backend openai-chat --dataset-name random --num-prompts 120 --request-rate 20 --max-concurrency 20 --trust-remote-code
→ Successful requests: 120 / 120

# Test 2: random, 5 prompts, 64k input / 512 output, single seq
vllm bench serve --host localhost --port 8000 --endpoint /v1/chat/completions --model /model_files/Kimi-K2.5 --tokenizer /ssd1/Kimi-K2.5 --backend openai-chat --dataset-name random --num-prompts 5 --request-rate 1 --max-concurrency 1 --trust-remote-code --random-input 64000 --random-output 512
→ Successful requests: 5 / 5

# Test 3: sharegpt, 120 prompts, 20 req/s, max-concurrency 20
vllm bench serve --host localhost --port 8000 --endpoint /v1/chat/completions --model /model_files/Kimi-K2.5 --tokenizer /ssd1/Kimi-K2.5 --backend openai-chat --dataset-name sharegpt --dataset-path ./ShareGPT_V3_unfiltered_cleaned_split.json --num-prompts 120 --request-rate 20 --max-concurrency 20 --trust-remote-code
→ Successful requests: 120 / 120
```

**Comment by BenWongCityuCS** [comment]
> Can you give a try to [#37160](https://github.com/vllm-project/vllm/pull/37160)? (aka set `export VLLM_USE_SIMPLE_KV_OFFLOAD=1`)

@ywang96 I also tested `#37160` with `export VLLM_USE_SIMPLE_KV_OFFLOAD=1` on the same `cu129-nightly-8cd174fa358326d5cc4195446be2ebcd65c481ce` image. It runs clean as well — no crashes and all requests succeeded.

**Serve command:**
```bash
docker run --rm -it \
    --gpus all \
    -e VLLM_USE_SIMPLE_KV_OFFLOAD=1 \
    -e VLLM_MEMORY_PROFILER_ESTIMATE_CUDAGRAPHS=1 \
    -p 8000:8000 \
    -v /ssd1:/model_files \
    vllm/vllm-openai:cu129-nightly-8cd174fa358326d5cc4195446be2ebcd65c481ce \
    /model_files/Kimi-K2.5 \
    --tensor-parallel-size 8 \
    --enable-expert-parallel \
    --enable-ep-weight-filter \
    --compilation-config '{"pass_config": {"fuse_allreduce_rms": true}}' \
    --kv-cache-dtype fp8 \
    --speculative-config '{"model": "/model_files/Kimi-K2.5-Eagle3", "method": "eagle3", "num_speculative_tokens": 3}' \
    --gpu-memory-utilization 0.95 \
    --max-num-batched-tokens 16384 \
    --kv-offloading-size 400 \
    --max-num-seqs 25 \
    --enable-chunked-prefill \
    --enable-prefix-caching \
    --host 0.0.0.0 \
    --port 8000 \
    --trust-remote-code \
    --disable-hybrid-kv-cache-manager
```

**Benchmark commands & results:**
```bash
# Test 1: random, 120 prompts, 20 req/s, max-concurrency 20
vllm bench serve --host localhost --port 8000 --endpoint /v1/chat/completions --model /model_files/Kimi-K2.5 --tokenizer /ssd1/Kimi-K2.5 --backend openai-chat --dataset-name random --num-prompts 120 --request-rate 20 --max-concurrency 20 --trust-remote-code
→ Successful requests: 120 / 120

# Test 2: random, 5 prompts, 64k input / 512 output, single seq
vllm bench serve --host localhost --port 8000 --endpoint /v1/chat/completions --model /model_files/Kimi-K2.5 --tokenizer /ssd1/Kimi-K2.5 --backend openai-chat --dataset-name random --num-prompts 5 --request-rate 1 --max-concurrency 1 --trust-remote-code --random-input 64000 --random-output 512
→ Successful requests: 5 / 5

# Test 3: sharegpt, 120 prompts, 20 req/s, max-concurrency 20
vllm bench serve --host localhost --port 8000 --endpoint /v1/chat/completions --model /model_files/Kimi-K2.5 --tokenizer /ssd1/Kimi-K2.5 --backend openai-chat --dataset-name sharegpt --dataset-path ./ShareGPT_V3_unfiltered_cleaned_split.json --num-prompts 120 --request-rate 20 --max-concurrency 20 --trust-remote-code
→ Successful requests: 120 / 120
```

**Comment by BenWongCityuCS** [comment]
> > I pulled the newer `**vllm/vllm-openai:deepseekv4-cu130**` image (published after v0.19.1), which I understand should carry the prior offloading fixes, including [#39617](https://github.com/vllm-project/vllm/pull/39617).
> 
> I tried to understand the vllm version for this image.
> 
> ```
> $ docker run --rm --entrypoint python3 vllm/vllm-openai:deepseekv4-cu130 -c "import vllm; print(vllm.__version__)"
> 0.1.dev15833+g62d441ee8
> ```
> 
> Can't find this commit hash in vllm repo.
> 
> Anyhow, I manually checked the file that was fixed in [#39617](https://github.com/vllm-project/vllm/pull/39617) but it is not fixed.
> 
> In other words, `vllm/vllm-openai:deepseekv4-cu130` does not contain the [#39617](https://github.com/vllm-project/vllm/pull/39617) fix.

 @orozery — following up with a **new, distinct failure**. After confirming the original `CUDA error: invalid argument` / `cuMemcpyBatchAsync` segfault from #40259 is resolved by the `cu129-nightly-8cd174fa358326d5cc4195446be2ebcd65c481ce` image, I hit a different crash under a new configuration. It reproduces 100% of the time.

**Serve Command**

```bash
docker run --rm -it --name vllm-kimi-k2.6 \
  --gpus '"device=0,1,2,3,4,5,6,7"' \
  --ipc=host \
  --ulimit memlock=-1 \
  --ulimit stack=67108864 \
  -v /model_files:/models \
  -p 8000:8000 \
  vllm/vllm-openai:cu129-nightly-8cd174fa358326d5cc4195446be2ebcd65c481ce \
  --model /models/kimi-k2.6 \
  --compilation_config.pass_config.fuse_allreduce_rms true \
  --served-model-name /model_files/h20/Kimi-K2.5 \
  --max-num-seqs 25 \
  --max-num-batched-tokens 8192 \
  --enable-chunked-prefill \
  --enable-prefix-caching \
  --host 0.0.0.0 \
  --port 8000 \
  --trust-remote-code \
  --tensor-parallel-size 8 \
  --tool-call-parser kimi_k2 \
  --reasoning-parser kimi_k2 \
  --enable-auto-tool-choice \
  --mm-encoder-tp-mode data \
  --mm-processor-cache-type shm \
  --mm-processor-cache-gb 128 \
  --decode-context-parallel-size 8 \      # <--- Trigger
   --gpu-memory-utilization 0.9472 \
  --disable-hybrid-kv-cache-manager \
  --safetensors-load-strategy=prefetch \
  --kv-offloading-size 800
```

**Benchmark Command**

```bash
vllm bench serve \
  --host localhost \
  --port 8000 \
  --endpoint /v1/chat/completions \
  --model /model_files/h20/Kimi-K2.5 \
  --tokenizer /model_files/kimi-k2.6 \
  --backend openai-chat \
  --dataset-name random \
  --num-prompts 120 \
  --request-rate 20 \
  --max-concurrency 20 \
  --save-result \
  --result-dir "./log/" \
  --trust-remote-code
```

**Complete Error Log**

```
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138] EngineCore encountered a fatal error.
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138] Traceback (most recent call last):
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1129, in run_engine_core
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]     engine_core.run_busy_loop()
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1170, in run_busy_loop
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]     self._process_engine_step()
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1209, in _process_engine_step
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]     outputs, model_executed = self.step_fn()
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]                               ^^^^^^^^^^^^^^
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 471, in step_with_batch_queue
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]     scheduler_output = self.scheduler.schedule()
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]                        ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/core/sched/scheduler.py", line 619, in schedule
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]     self.connector.get_num_new_matched_tokens(
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/distributed/kv_transfer/kv_connector/v1/offloading_connector.py", line 118, in get_num_new_matched_tokens
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]     return self.connector_scheduler.get_num_new_matched_tokens(
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]   File "/usr/local/lib/python3.12/dist-packages/vllm/distributed/kv_transfer/kv_connector/v1/offloading/scheduler.py", line 240, in get_num_new_matched_tokens
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]     assert len(offload_keys) >= num_blocks
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=1160) ERROR 04-27 07:07:07 [core.py:1138] AssertionError
(APIServer pid=1) ERROR 04-27 07:07:07 [async_llm.py:699] AsyncLLM output_handler failed.
(APIServer pid=1) ERROR 04-27 07:07:07 [async_llm.py:699] Traceback (most recent call last):
(APIServer pid=1) ERROR 04-27 07:07:07 [async_llm.py:699]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 655, in output_handler
(APIServer pid=1) ERROR 04-27 07:07:07 [async_llm.py:699]     outputs = await engine_core.get_output_async()
(APIServer pid=1) ERROR 04-27 07:07:07 [async_llm.py:699]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=1) ERROR 04-27 07:07:07 [async_llm.py:699]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 998, in get_output_async
(APIServer pid=1) ERROR 04-27 07:07:07 [async_llm.py:699]     raise self._format_exception(outputs) from None
(APIServer pid=1) ERROR 04-27 07:07:07 [async_llm.py:699] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
(Worker_TP0_DCP0 pid=1359) INFO 04-27 07:07:07 [multiproc_executor.py:775] Parent process exited, terminating worker queues
(Worker_TP4_DCP4 pid=1363) INFO 04-27 07:07:07 [multiproc_executor.py:872] WorkerProc shutting down.
(Worker_TP6_DCP6 pid=1365) INFO 04-27 07:07:07 [multiproc_executor.py:872] WorkerProc shutting down.
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267] Error in chat completion stream generator.
(Worker_TP5_DCP5 pid=1364) INFO 04-27 07:07:07 [multiproc_executor.py:872] WorkerProc shutting down.
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267] Traceback (most recent call last):
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267]   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/chat_completion/serving.py", line 635, in chat_completion_stream_generator
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267]     async for res in result_generator:
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 574, in generate
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267]     out = q.get_nowait() or await q.get()
(Worker_TP2_DCP2 pid=1361) INFO 04-27 07:07:07 [multiproc_executor.py:872] WorkerProc shutting down.
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267]                             ^^^^^^^^^^^^^
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/output_processor.py", line 85, in get
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267]     raise output
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 655, in output_handler
(Worker_TP3_DCP3 pid=1362) INFO 04-27 07:07:07 [multiproc_executor.py:872] WorkerProc shutting down.
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267]     outputs = await engine_core.get_output_async()
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267]   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 998, in get_output_async
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267]     raise self._format_exception(outputs) from None
(Worker_TP0_DCP0 pid=1359) INFO 04-27 07:07:07 [multiproc_executor.py:872] WorkerProc shutting down.
(APIServer pid=1) ERROR 04-27 07:07:07 [serving.py:1267] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
(Worker_TP1_DCP1 pid=1360) INFO 04-27 07:07:07 [multiproc_executor.py:872] WorkerProc shutting down.
(Worker_TP7_DCP7 pid=1366) INFO 04-27 07:07:07 [multiproc_executor.py:872] WorkerProc shutting down.
(APIServer pid=1) INFO:     172.30.255.1:58942 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
```

**Benchmark Result**

```
============ Serving Benchmark Result ============
Successful requests:                     0
Failed requests:                         120
Maximum request concurrency:             20
Request rate configured (RPS):           20.00
Benchmark duration (s):                  6.01
Total input tokens:                      0
Total generated tokens:                  0
Request throughput (req/s):              0.00
Output token throughput (tok/s):         0.00
Peak output token throughput (tok/s):    0.00
Peak concurrent requests:                0.00
Total Token throughput (tok/s):          0.00
---------------Time to First Token----------------
Mean TTFT (ms):                          0.00
Median TTFT (ms):                        0.00
P99 TTFT (ms):                           0.00
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          0.00
Median TPOT (ms):                        0.00
P99 TPOT (ms):                           0.00
---------------Inter-token Latency----------------
Mean ITL (ms):                           0.00
Median ITL (ms):                         0.00
P99 ITL (ms):                            0.00
==================================================
```

This is a distinct failure from the previous `CUDA error: invalid argument` / `cuMemcpyBatchAsync` segfault. The earlier issue is fixed in this nightly image, but the `AssertionError` in `offloading/scheduler.py:240` above is new and happens immediately on the first request batch.

**Comment by orozery** [comment]
> --decode-context-parallel-size 8 \      # <--- Trigger

Thanks @BenWongCityuCS ! This is really helpful input!

We never actually tested the offloading connector with DCP/PCP enabled.
The specific assertion error you're seeing is due to a mismatch in the block size used for hashing prompt tokens.
I made a small fix to overcome it here:
https://github.com/orozery/vllm/commit/3ff936e26ec48b71641f04ae18ea0f5d09493a7e
Is there a way you can patch it and re-try?

I'm not really familiar with DCP/PCP to tell if there is a bigger gap that would prevent using both features (offloading + DCP) together.
cc @robertgshaw2-redhat @NickLucche do you guys have any experience with DCP/PCP?

**Comment by BenWongCityuCS** [comment]
> > --decode-context-parallel-size 8 \      # <--- Trigger
> 
> Thanks [@BenWongCityuCS](https://github.com/BenWongCityuCS) ! This is really helpful input!
> 
> We never actually tested the offloading connector with DCP/PCP enabled. The specific assertion error you're seeing is due to a mismatch in the block size used for hashing prompt tokens. I made a small fix to overcome it here: [orozery@3ff936e](https://github.com/orozery/vllm/commit/3ff936e26ec48b71641f04ae18ea0f5d09493a7e) Is there a way you can patch it and re-try?
> 
> I'm not really familiar with DCP/PCP to tell if there is a bigger gap that would prevent using both features (offloading + DCP) together. cc [@robertgshaw2-redhat](https://github.com/robertgshaw2-redhat) [@NickLucche](https://github.com/NickLucche) do you guys have any experience with DCP/PCP?

We are currently running kimi k2.6 DCP (decode-context-parallel-size=8) on 8× H20(141 GB) in production with v0.19.1. It effectively solved our previous death spiral: long-context + high concurrency → KV Cache thrashing/eviction → Chunked Prefill recomputation → Decode starvation → TPOT/ITL explosion. With DCP, our effective KV Cache capacity jumped from ~3× 256K to ~25× 256K contexts, and eviction basically disappeared. We do observe a 10–20% throughput/latency penalty with DCP enabled, but that is a very acceptable trade-off to finally kill the death spiral.

That said, while our GPU eviction is under control, we still have ~1.5 TB of host DRAM sitting mostly idle. Our goal with --kv-offloading-size is specifically to extend the prefix caching space into host memory, not to expand concurrent context capacity. We want to retain more historical prefix blocks that would otherwise be dropped from GPU KV cache, thereby pushing our prefix cache hit rate even higher and avoiding cold-start prefill on shared prompts.

This is where we hit the assert len(offload_keys) >= num_blocks failure when combining DCP with the offloading connector.

I have final exams coming up in the next few days, so I will pull the latest nightly image and try your patch (orozery@3ff936e) as soon as I'm free to verify if it unblocks this prefix-caching-offloading use case.

Given your comment that you haven't tested the offloading connector with DCP/PCP, should we treat DCP + KV Offloading as an unsupported combo for now, or is this a path you plan to harden? We’d be glad to validate this and share results. Just wanted to check if there are any known architectural limitations between DCP and offloading that we should keep in mind before diving deeper?

**Comment by orozery** [comment]
> Given your comment that you haven't tested the offloading connector with DCP/PCP, should we treat DCP + KV Offloading as an unsupported combo for now, or is this a path you plan to harden? We’d be glad to validate this and share results. Just wanted to check if there are any known architectural limitations between DCP and offloading that we should keep in mind before diving deeper?

It is unsupported but we'll definitely look into whether we can extend support for it.
I opened up #40992 to track it.

**Comment by BenWongCityuCS** [comment]
> > Given your comment that you haven't tested the offloading connector with DCP/PCP, should we treat DCP + KV Offloading as an unsupported combo for now, or is this a path you plan to harden? We’d be glad to validate this and share results. Just wanted to check if there are any known architectural limitations between DCP and offloading that we should keep in mind before diving deeper?
> 
> It is unsupported but we'll definitely look into whether we can extend support for it. I opened up [#40992](https://github.com/vllm-project/vllm/issues/40992) to track it.

Thanks for the patch and for opening the dedicated issue to track the DCP + KV offloading integration!

​I’m currently busy with finals, but I will try your latest commit as soon as I finish my exams this Thursday.

​One thing I should mention is that I am currently an intern here. While I should have access to these compute resources for the next month or two, my ability to test depends on the company's internal priorities. If we need to deploy new models in production later on, I might lose access to these GPUs and won't be able to verify further updates. In that case, you might need to find other contributors to help with testing.

​Regarding the architecture, I believe DCP is highly valuable as it effectively scales the KV cache capacity by the TP size. However, from my observation, as concurrency increases with long-context requests, we will eventually hit the same "death spiral" bottleneck again—DCP significantly raises the threshold for this issue, but doesn't eliminate it entirely. This is why we are so keen on offloading!

**Comment by Etelis** [comment]
Hey @BenWongCityuCS 
Could you try #41549?

**Comment by BenWongCityuCS** [comment]
> Hey [@BenWongCityuCS](https://github.com/BenWongCityuCS) Could you try [#41549](https://github.com/vllm-project/vllm/pull/41549)?

Hi @Etelis,

Thank you so much for the quick fix on the DCP/PCP compatibility issue!

I wanted to explain my current situation: my server is in an air-gapped environment without public internet access. Over the past few days, I've been trying to build a Docker image based on orozery@3ff936e but kept running into failures—mostly due to the complexity of resolving PyTorch/CUDA dependencies and the long compilation time for the CUDA kernels in an offline setting.

Would it be possible to get this bug fix merged into main? Once it's in the main branch, I could download the official nightly Docker image (vllm/vllm-openai:latest or vllm/vllm-openai:nightly) on a machine with internet access, transfer the image tarball to my offline server, and test the fix there. This would be much more feasible for me than compiling from source in a restricted environment.

As I mentioned earlier, I'm currently an intern with limited GPU access duration, so the ability to use pre-built images would really help me validate this fix before my internship ends.

Thanks again for your excellent work on the KV offloading features!

**Comment by BenWongCityuCS** [comment]
Hi @Etelis @orozery,

Thanks for your fixes and continued tracking in #41549 and #40992.

A quick timeline note: although I saw that #41549 ([Bugfix][KVConnector] Support DCP/PCP in OffloadingConnector) was merged into main last week, our 8×H20 cluster nodes were fully occupied by other tasks from Monday through Thursday this week (5/11–5/14), so I had no chance to validate it immediately.

**v0.21.0** has now been officially released and includes this fix. I just finished testing it and can confirm that everything works correctly.

- **Image**: `vllm/vllm-openai:v0.21.0-cu129`

**Validation result**: Under this version, Kimi-K2.6 with DCP + KV Offloading runs without issues; the previous errors no longer reproduce.

---

### Serve Command

```bash
docker run --rm -it --name vllm-kimi-k2.6 \
  --gpus '"device=0,1,2,3,4,5,6,7"' \
  --ipc=host \
  --ulimit memlock=-1 \
  --ulimit stack=67108864 \
  -v /model_files:/models \
  -p 8000:8000 \
  vllm/vllm-openai:v0.21.0-cu129 \
  --model /models/kimi-k2.6 \
  --compilation_config.pass_config.fuse_allreduce_rms true \
  --served-model-name /model_files/h20/Kimi-K2.5 \
  --max-num-seqs 25 \
  --max-num-batched-tokens 8192 \
  --enable-chunked-prefill \
  --enable-prefix-caching \
  --host 0.0.0.0 \
  --port 8000 \
  --trust-remote-code \
  --tensor-parallel-size 8 \
  --tool-call-parser kimi_k2 \
  --reasoning-parser kimi_k2 \
  --enable-auto-tool-choice \
  --mm-encoder-tp-mode data \
  --mm-processor-cache-type shm \
  --mm-processor-cache-gb 128 \
  --decode-context-parallel-size 8 \
  --gpu-memory-utilization 0.9472 \
  --disable-hybrid-kv-cache-manager \
  --safetensors-load-strategy=prefetch \
  --kv-offloading-size 800
```

---

### Benchmark Results

**Test 1: random, 120 prompts, 20 req/s, max-concurrency 20**

```bash
vllm bench serve --host localhost --port 8000 --endpoint /v1/chat/completions \
  --model /model_files/h20/Kimi-K2.5 --tokenizer /model_files/kimi-k2.6 \
  --backend openai-chat --dataset-name random --num-prompts 120 \
  --request-rate 20 --max-concurrency 20 --save-result --result-dir "./log/" \
  --trust-remote-code
```

- **Successful requests: 120 / 120**
- **Failed requests: 0**
- **Benchmark duration: 40.24 s**
- **Request throughput: 2.98 req/s**
- **Total Token throughput: 3435.51 tok/s**

**Test 2: sharegpt, 120 prompts, 20 req/s, max-concurrency 20**

```bash
vllm bench serve --host localhost --port 8000 --endpoint /v1/chat/completions \
  --model /model_files/h20/Kimi-K2.5 --tokenizer /model_files/kimi-k2.6 \
  --backend openai-chat --dataset-name sharegpt \
  --dataset-path ./ShareGPT_V3_unfiltered_cleaned_split.json \
  --num-prompts 120 --request-rate 20 --max-concurrency 20 \
  --save-result --result-dir "./log/" --trust-remote-code
```

- **Successful requests: 120 / 120**
- **Failed requests: 0**
- **Benchmark duration: 53.32 s**
- **Request throughput: 2.25 req/s**
- **Total Token throughput: 983.35 tok/s**

---

### Conclusion

In **v0.21.0**, which includes the fix from #41549, I tested Kimi-K2.6 with `--decode-context-parallel-size 8` + `--kv-offloading-size 800` + EP enabled. The `AssertionError` previously triggered at `offloading/scheduler.py`, as well as the subsequent cascade failure, **did not reproduce; all 120/120 requests succeeded with no errors during the tests**.

Over the next few weeks, I will continue validating and then deploy this configuration to production.  
A special thanks for this fix—it finally lets us put the **1.2 TB of DRAM** sitting on our server to good use instead of leaving it idle!

Thanks again!  
Ben

**Comment by Etelis** [comment]
> Hi @Etelis @orozery,
> 
> Thanks for your fixes and continued tracking in #41549 and #40992.
> 
> A quick timeline note: although I saw that #41549 ([Bugfix][KVConnector] Support DCP/PCP in OffloadingConnector) was merged into main last week, our 8×H20 cluster nodes were fully occupied by other tasks from Monday through Thursday this week (5/11–5/14), so I had no chance to validate it immediately.
> 
> **v0.21.0** has now been officially released and includes this fix. I just finished testing it and can confirm that everything works correctly.
> 
> - **Image**: `vllm/vllm-openai:v0.21.0-cu129`
> 
> **Validation result**: Under this version, Kimi-K2.6 with DCP + KV Offloading runs without issues; the previous errors no longer reproduce.
> 
> ---
> 
> ### Serve Command
> 
> ```bash
> docker run --rm -it --name vllm-kimi-k2.6 \
>   --gpus '"device=0,1,2,3,4,5,6,7"' \
>   --ipc=host \
>   --ulimit memlock=-1 \
>   --ulimit stack=67108864 \
>   -v /model_files:/models \
>   -p 8000:8000 \
>   vllm/vllm-openai:v0.21.0-cu129 \
>   --model /models/kimi-k2.6 \
>   --compilation_config.pass_config.fuse_allreduce_rms true \
>   --served-model-name /model_files/h20/Kimi-K2.5 \
>   --max-num-seqs 25 \
>   --max-num-batched-tokens 8192 \
>   --enable-chunked-prefill \
>   --enable-prefix-caching \
>   --host 0.0.0.0 \
>   --port 8000 \
>   --trust-remote-code \
>   --tensor-parallel-size 8 \
>   --tool-call-parser kimi_k2 \
>   --reasoning-parser kimi_k2 \
>   --enable-auto-tool-choice \
>   --mm-encoder-tp-mode data \
>   --mm-processor-cache-type shm \
>   --mm-processor-cache-gb 128 \
>   --decode-context-parallel-size 8 \
>   --gpu-memory-utilization 0.9472 \
>   --disable-hybrid-kv-cache-manager \
>   --safetensors-load-strategy=prefetch \
>   --kv-offloading-size 800
> ```
> 
> ---
> 
> ### Benchmark Results
> 
> **Test 1: random, 120 prompts, 20 req/s, max-concurrency 20**
> 
> ```bash
> vllm bench serve --host localhost --port 8000 --endpoint /v1/chat/completions \
>   --model /model_files/h20/Kimi-K2.5 --tokenizer /model_files/kimi-k2.6 \
>   --backend openai-chat --dataset-name random --num-prompts 120 \
>   --request-rate 20 --max-concurrency 20 --save-result --result-dir "./log/" \
>   --trust-remote-code
> ```
> 
> - **Successful requests: 120 / 120**
> - **Failed requests: 0**
> - **Benchmark duration: 40.24 s**
> - **Request throughput: 2.98 req/s**
> - **Total Token throughput: 3435.51 tok/s**
> 
> **Test 2: sharegpt, 120 prompts, 20 req/s, max-concurrency 20**
> 
> ```bash
> vllm bench serve --host localhost --port 8000 --endpoint /v1/chat/completions \
>   --model /model_files/h20/Kimi-K2.5 --tokenizer /model_files/kimi-k2.6 \
>   --backend openai-chat --dataset-name sharegpt \
>   --dataset-path ./ShareGPT_V3_unfiltered_cleaned_split.json \
>   --num-prompts 120 --request-rate 20 --max-concurrency 20 \
>   --save-result --result-dir "./log/" --trust-remote-code
> ```
> 
> - **Successful requests: 120 / 120**
> - **Failed requests: 0**
> - **Benchmark duration: 53.32 s**
> - **Request throughput: 2.25 req/s**
> - **Total Token throughput: 983.35 tok/s**
> 
> ---
> 
> ### Conclusion
> 
> In **v0.21.0**, which includes the fix from #41549, I tested Kimi-K2.6 with `--decode-context-parallel-size 8` + `--kv-offloading-size 800` + EP enabled. The `AssertionError` previously triggered at `offloading/scheduler.py`, as well as the subsequent cascade failure, **did not reproduce; all 120/120 requests succeeded with no errors during the tests**.
> 
> Over the next few weeks, I will continue validating and then deploy this configuration to production.  
> A special thanks for this fix—it finally lets us put the **1.2 TB of DRAM** sitting on our server to good use instead of leaving it idle!
> 
> Thanks again!  
> Ben

YEY! Thank you for checking!!!

**Comment by yoonhoqpt** [comment]
Hi Ben, I read through the full investigation, including the separate FP8 issue, the unsupported DCP + KV offloading combination, and your successful validation on v0.21.

I’m an SRE independently researching how teams qualify complex inference-stack changes before production. Would you be open to a brief off-thread conversation about how you selected the validation cases, what else you planned to test before production, and how the air-gapped environment affected the process?

Feel free to email me at y.tommyc@gmail.com
