### ISSUE TITLE
[Bug]: win10 WSL2中vllm0.4.0 无法启动

### ISSUE THREAD

**Issue by kir1to00** [vllm-project/vllm#4140]
### Your current environment

```text
PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.2
Libc version: glibc-2.35

Python version: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 536.23
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      39 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             28
On-line CPU(s) list:                0-27
Vendor ID:                          GenuineIntel
Model name:                         Intel(R) Core(TM) i7-14700KF
CPU family:                         6
Model:                              183
Thread(s) per core:                 2
Core(s) per socket:                 14
Socket(s):                          1
Stepping:                           1
BogoMIPS:                           6835.19
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves umip gfni vaes vpclmulqdq rdpid fsrm flush_l1d arch_capabilities
Hypervisor vendor:                  Microsoft
Virtualization type:                full
L1d cache:                          672 KiB (14 instances)
L1i cache:                          448 KiB (14 instances)
L2 cache:                           28 MiB (14 instances)
L3 cache:                           33 MiB (1 instance)
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Unknown: No mitigations
Vulnerability Retbleed:             Mitigation; Enhanced IBRS
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.1.2
[pip3] triton==2.1.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] torch                     2.1.2                    pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypiROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.4.0
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS                             N/A
GPU1    SYS      X                              N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### 🐛 Describe the bug

我在基于win10的wsl2中，vllm0.3.3版本时使用cupy可以正常启动两张卡部署模型，升级到0.4.0后单卡正常运行，多卡报错。
 ```
INFO 04-17 16:06:59 api_server.py:148] vLLM API server version 0.4.0
INFO 04-17 16:06:59 api_server.py:149] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, served_model_name='qwen15', lora_modules=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/mnt/d/ai/llm/Qwen1.5-14B-Chat', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='float16', kv_cache_dtype='auto', max_model_len=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, use_v2_block_manager=False, seed=0, swap_space=4, gpu_memory_utilization=0.9, forced_num_gpu_blocks=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=None, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_chunked_prefill=False, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
WARNING 04-17 16:06:59 config.py:748] Casting torch.bfloat16 to torch.float16.
2024-04-17 16:07:01,513 INFO worker.py:1752 -- Started a local Ray instance.
INFO 04-17 16:07:01 llm_engine.py:75] Initializing an LLM engine (v0.4.0) with config: model='/mnt/d/ai/llm/Qwen1.5-14B-Chat', tokenizer='/mnt/d/ai/llm/Qwen1.5-14B-Chat', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=2, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
WARNING 04-17 16:07:04 utils.py:350] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
(RayWorkerVllm pid=11490) WARNING 04-17 16:07:04 utils.py:350] Using 'pin_memory=False' as WSL is detected. This may slow down the performance.
INFO 04-17 16:07:04 selector.py:34] Cannot use FlashAttention backend for Volta and Turing GPUs.
INFO 04-17 16:07:04 selector.py:21] Using XFormers backend.
(RayWorkerVllm pid=11490) INFO 04-17 16:07:04 selector.py:34] Cannot use FlashAttention backend for Volta and Turing GPUs.
(RayWorkerVllm pid=11490) INFO 04-17 16:07:04 selector.py:21] Using XFormers backend.
INFO 04-17 16:07:04 pynccl_utils.py:45] vLLM is using nccl==2.18.1
(RayWorkerVllm pid=11490) INFO 04-17 16:07:04 pynccl_utils.py:45] vLLM is using nccl==2.18.1
Traceback (most recent call last):
  File "/root/anaconda3/envs/vllm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/vllm/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 156, in <module>
    engine = AsyncLLMEngine.from_engine_args(
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 348, in from_engine_args
    engine = cls(
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 311, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 422, in _init_engine
    return engine_class(*args, **kwargs)
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 111, in __init__
    self.model_executor = executor_class(model_config, cache_config,
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 62, in __init__
    self._init_workers_ray(placement_group)
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 191, in _init_workers_ray
    self._run_workers("init_device")
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 324, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker.py", line 100, in init_device
    init_distributed_environment(self.parallel_config, self.rank,
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker.py", line 287, in init_distributed_environment
    pynccl_utils.init_process_group(
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/pynccl_utils.py", line 46, in init_process_group
    comm = NCCLCommunicator(init_method=init_method,
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/pynccl.py", line 236, in __init__
    dist.broadcast(tensor, src=0)
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
    work = default_pg.broadcast([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.1
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Cuda failure 'invalid argument'
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44] Error executing method init_device. This might cause deadlock in distributed execution.
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44] Traceback (most recent call last):
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/ray_utils.py", line 37, in execute_method
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44]     return executor(*args, **kwargs)
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker.py", line 100, in init_device
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44]     init_distributed_environment(self.parallel_config, self.rank,
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker.py", line 287, in init_distributed_environment
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44]     pynccl_utils.init_process_group(
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/pynccl_utils.py", line 46, in init_process_group
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44]     comm = NCCLCommunicator(init_method=init_method,
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/pynccl.py", line 236, in __init__
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44]     dist.broadcast(tensor, src=0)
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44]     return func(*args, **kwargs)
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1906, in broadcast
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44]     work = default_pg.broadcast([tensor], opts)
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44] torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1333, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.18.1
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44] ncclUnhandledCudaError: Call to CUDA function failed.
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44] Last error:
(RayWorkerVllm pid=11490) ERROR 04-17 16:07:05 ray_utils.py:44] Cuda failure 'invalid argument'
Exception ignored in: <function NCCLCommunicator.__del__ at 0x7f730b5229e0>
Traceback (most recent call last):
  File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/parallel_utils/pynccl.py", line 264, in __del__
    _c_ncclCommDestroy(self.comm)
AttributeError: 'NCCLCommunicator' object has no attribute 'comm'
 ```
不胜感激

**Comment by HelloCard** [comment]
和我很像啊，我也是win10，双卡2080ti，z170ar主板，安装并启用nvlink。不过我在wsl2里安装了最新版本的vllm以后一切正常。

**Comment by kir1to00** [comment]
> 和我很像啊，我也是win10，双卡2080ti，z170ar主板，安装并启用nvlink。不过我在wsl2里安装了最新版本的vllm以后一切正常。

@HelloCard 用了tensor-parallel-size参数吗？

**Comment by kir1to00** [comment]
使用nvidia-nccl-cu12==2.19.3 vllm=0.4.0.post1 成功启动

**Comment by HelloCard** [comment]
> > 和我很像啊，我也是win10，双卡2080ti，z170ar主板，安装并启用nvlink。不过我在wsl2里安装了最新版本的vllm以后一切正常。
> 
> @HelloCard 用了tensor-parallel-size参数吗？

用了tensor-parallel-size 2，运行了BagelMIsteryTour-v2-8x7B-AWQ、Qwen1.5-32B-Chat-AWQ、DaringMaid-20B-AWQ、orca-2-13B-AWQ

**Comment by kir1to00** [comment]
> > > 和我很像啊，我也是win10，双卡2080ti，z170ar主板，安装并启用nvlink。不过我在wsl2里安装了最新版本的vllm以后一切正常。
> > 
> > 
> > @HelloCard 用了tensor-parallel-size参数吗？
> 
> 用了tensor-parallel-size 2，运行了BagelMIsteryTour-v2-8x7B-AWQ、Qwen1.5-32B-Chat-AWQ、DaringMaid-20B-AWQ、orca-2-13B-AWQ

已经解决拉 @HelloCard
