### ISSUE TITLE
Recurring CUDA kernel hang on 2x DGX Spark (GB10, sm_12.1) with MiniMax-M2.7-NVFP4, TP=2 across 2 nodes

### ISSUE THREAD

**Issue by lesserevil** [vllm-project/vllm#41725]
## Environment

- **vLLM version**: 0.19.1
- **Model**: nvidia/MiniMax-M2.7-NVFP4
- **Hardware**: 2x NVIDIA DGX Spark, each with 1x GB10 Superchip (sm_12.1 / CUDA capability 12.1)
- **Interconnect**: C2C link (169.254.x.x/16), 900 GB/s, RoCE over enp1s0f0np0 / rocep1s0f0
- **CUDA**: 13.0
- **NCCL**: 2.28.9+cuda13.0
- **PyTorch**: 2.9.0+cu130
- **OS**: Ubuntu (kernel 6.17.0-nvidia)

## Launch configuration

```bash
export NCCL_IB_HCA=rocep1s0f0
export NCCL_SOCKET_IFNAME=enp1s0f0np0
export NCCL_P2P_DISABLE=1
export NCCL_NET_GDR_LEVEL=5
export NCCL_DEBUG=WARN
export TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC=120
export VLLM_NVFP4_GEMM_BACKEND=flashinfer-cutlass
export VLLM_USE_FLASHINFER_MOE_FP4=1

vllm serve nvidia/MiniMax-M2.7-NVFP4 \
  --trust-remote-code \
  --compilation-config '{"mode":3,"pass_config":{"fuse_minimax_qk_norm":true}}' \
  -cc.pass_config.fuse_allreduce_rms=False \
  --tensor-parallel-size 2 \
  --nnodes 2 \
  --node-rank 0 \  # (node-rank 1 on second node, with --headless)
  --master-addr 169.254.205.76 \
  --tool-call-parser minimax_m2 \
  --enable-auto-tool-choice \
  --gpu-memory-utilization 0.80 \
  --enforce-eager \
  --moe-backend marlin \
  --port 8888 \
  --reasoning-parser minimax_m2
```

## Symptom

After 35–55 minutes of serving inference requests, both nodes simultaneously enter a state where:

1. GPU utilization on both nodes locks at **96–99%** indefinitely
2. No errors appear in the NCCL debug log (`NCCL_DEBUG=WARN`) — the log only ever contains the version banner
3. The vLLM `shm_broadcast` ring times out with one warning per minute:
   ```
   No available shared memory broadcast block found in 60 seconds.
   ```
4. After `TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC=120` seconds, the PyTorch NCCL watchdog fires and kills the EngineCore
5. The API server exits cleanly (exit 0), and `Restart=always` recovers the service in ~10 minutes

The hang is **not** detected by NCCL itself — the debug log stays empty throughout. Both nodes are simultaneously pegged at high GPU utilization, which rules out a simple network stall (one side waiting for the other).

## What has been tried (none resolved the hang)

| Change | Result |
|---|---|
| `NCCL_IB_HCA=rocep1s0f0` (pin to stable C2C RoCE adapter) | No change |
| `NCCL_IB_DISABLE=1` (force TCP-only) | No change; also made restart harder |
| Remove `--enable-expert-parallel` | No change |
| Remove `--moe-backend marlin` | Hang occurred faster (~5 min instead of ~45 min) |
| `NCCL_P2P_DISABLE=1` + `NCCL_NET_GDR_LEVEL=5` | No change |
| NetworkManager unmanaged on secondary RoCE interface | Fixed a separate startup crash; unrelated |

## Crash log excerpt

```
(EngineCore) ERROR [shm_broadcast.py:681] No available shared memory broadcast block found in 60 seconds.
(EngineCore) ERROR [shm_broadcast.py:681] No available shared memory broadcast block found in 60 seconds.
(EngineCore) ERROR [shm_broadcast.py:681] No available shared memory broadcast block found in 60 seconds.
(EngineCore) ERROR [shm_broadcast.py:681] No available shared memory broadcast block found in 60 seconds.
(APIServer) ERROR [async_llm.py:707] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue.
(APIServer) INFO: Shutting down
```

The NCCL debug log (`/tmp/nccl-<hostname>.log`) contains only:
```
# NCCL version 2.28.9+cuda13.0
```

## Suspected cause

The hang occurs inside a CUDA kernel during the TP forward pass (AllReduce). Because both nodes are simultaneously at high GPU utilization with no NCCL-level error, the deadlock appears to be at the CUDA compute layer rather than in the collective transport. This may be related to GB10 (sm_12.1) being outside the stated supported compute capability range for the PyTorch version in use (PyTorch 2.9.0 states max supported capability 12.0), though the same hang occurs with and without RDMA transport enabled.

Closest related issues: #40969 (GB10 CUDA hang after N requests), #33041 (TP=2 hang on Blackwell).

## Reporter

Shawn Edwards (lesserevil)

**Comment by majinghe** [comment]
Ray + vLLM works on my side  to deploy MiniMax-M2.7-NVFP4, 2 sparks

```
  vllm serve /model_weight \
    --served-model-name lukealonso/MiniMax-M2.7-NVFP4 \
    --api-key token-xxxx\
    --host 0.0.0.0 \
    --port 8000 \
    --trust-remote-code \
    --quantization modelopt \
    --moe-backend cutlass \
    --max-model-len 32768 \
    --gpu-memory-utilization 0.85 \
    --kv-cache-dtype fp8 \
    --max-num-seqs 16 \
    --data-parallel-size 1 \
    --max-num-batched-tokens 8192 \
    --enable-auto-tool-choice \
    --tool-call-parser minimax_m2 \
    --tensor-parallel-size 2 \
    --pipeline-parallel-size 1 \
    --distributed-executor-backend ray \
    --reasoning-parser minimax_m2 \
    --disable-custom-all-reduce
```

Environment info for  Ray head

```
      - NCCL_SOCKET_IFNAME=enp1s0f1np1
      - GLOO_SOCKET_IFNAME=enp1s0f1np1
      - NCCL_IB_HCA=rocep1s0f1
      - NCCL_IB_GID_INDEX=3
      - NCCL_DEBUG=INFO
      - VLLM_HOST_IP=192.168.100.1
      - RAY_ADDRESS=192.168.100.1:6379
      - VLLM_ENV_PREFIXES=HF_,HUGGING_FACE_,LMCACHE_,NCCL_,UCX_,VLLM_,GLOO_
      - RAY_local_node_ip=192.168.100.1
      - TP_SOCKET_IFNAME=enp1s0f1np1
  ```


For Ray worker

```
      - NCCL_SOCKET_IFNAME=enp1s0f1np1
      - GLOO_SOCKET_IFNAME=enp1s0f1np1
      - NCCL_IB_HCA=rocep1s0f1
      - NCCL_IB_GID_INDEX=5
      - NCCL_DEBUG=INFO
      - VLLM_HOST_IP=192.168.100.2
      - TP_SOCKET_IFNAME=enp1s0f1np1
      - RAY_local_node_ip=192.168.100.2
```

**Comment by tbraun96** [comment]
Disclosure: I work on [Atlas](https://github.com/Avarok-Cybersecurity/atlas). Dropping a data point because we run this exact topology on the same hardware.

MiniMax-M2.7-NVFP4 across 2x DGX Spark over EP=2 has been stable for us using the docker-run pattern in our public QUICKSTART. Verbatim, two nodes, no orchestrator:

**Node 0 (head, `<HEAD_IP>`):**
```bash
sudo docker run -d \
  --name atlas-minimax-r0 \
  --network host --gpus all --ipc=host \
  --device=/dev/infiniband --cap-add=IPC_LOCK --cap-add=SYS_NICE --ulimit memlock=-1 \
  -e NCCL_SOCKET_IFNAME=enp1s0f0np0 \
  -e NCCL_IB_DISABLE=0 -e NCCL_IB_HCA=rocep1s0f0 \
  -e NCCL_IB_ROCE_VERSION_NUM=2 -e NCCL_IB_ADDR_FAMILY=AF_INET \
  -e NCCL_NET_GDR_LEVEL=0 -e NCCL_NET_GDR_C2C=0 -e NCCL_DMABUF_ENABLE=0 \
  -e NCCL_PROTO=Simple -e NCCL_ALGO=Ring \
  -v ~/.cache/huggingface:/root/.cache/huggingface \
  avarok/atlas-gb10:latest \
  serve lukealonso/MiniMax-M2.7-NVFP4 \
    --port 8888 \
    --rank 0 --world-size 2 \
    --tp-size 1 --ep-size 2 \
    --master-addr <HEAD_IP> --master-port 29500 \
    --max-seq-len 16384 --max-batch-size 1 \
    --gpu-memory-utilization 0.90 \
    --kv-cache-dtype bf16 \
    --enable-prefix-caching \
    --oom-guard-mb 512
```

**Node 1 (worker):**
```bash
sudo docker run -d \
  --name atlas-minimax-r1 \
  --network host --gpus all --ipc=host \
  --device=/dev/infiniband --cap-add=IPC_LOCK --cap-add=SYS_NICE --ulimit memlock=-1 \
  -e NCCL_SOCKET_IFNAME=enp1s0f0np0 \
  -e NCCL_IB_DISABLE=0 -e NCCL_IB_HCA=rocep1s0f0 \
  -e NCCL_IB_ROCE_VERSION_NUM=2 -e NCCL_IB_ADDR_FAMILY=AF_INET \
  -e NCCL_NET_GDR_LEVEL=0 -e NCCL_NET_GDR_C2C=0 -e NCCL_DMABUF_ENABLE=0 \
  -e NCCL_PROTO=Simple -e NCCL_ALGO=Ring \
  -v ~/.cache/huggingface:/root/.cache/huggingface \
  avarok/atlas-gb10:latest \
  serve lukealonso/MiniMax-M2.7-NVFP4 \
    --port 0 \
    --rank 1 --world-size 2 \
    --tp-size 1 --ep-size 2 \
    --master-addr <HEAD_IP> --master-port 29500 \
    --max-seq-len 16384 --max-batch-size 1 \
    --gpu-memory-utilization 0.90 \
    --kv-cache-dtype bf16 \
    --enable-prefix-caching \
    --oom-guard-mb 512
```

The API serves from rank 0 only (`http://<HEAD_IP>:8888/v1/chat/completions`). The canonical script with the full NCCL/RDMA env block (and a slight superset of these args) is [`scripts/start-minimax-ep2.sh`](https://github.com/Avarok-Cybersecurity/atlas/blob/main/scripts/start-minimax-ep2.sh). For the 122B equivalent and a step-by-step the same shape, see [`QUICKSTART.md` §7](https://github.com/Avarok-Cybersecurity/atlas/blob/main/QUICKSTART.md#7-qwen35-122b-moe--ep2-two-dgx-sparks-51-toks).

Three things in there that look directly relevant to the hang class you're seeing:

**1. MiniMax-M2.7-NVFP4 has no MTP weights in the public checkpoint.** `--speculative` is OFF on both ranks. If `num_speculative_tokens > 0` is set anywhere on rank 1 only, MTP verify lands in the worker's SSM layer with no buffers allocated and the next collective deadlocks. The symptom reads as a NCCL hang but the root cause is rank imbalance in layer work.

**2. `--kv-cache-dtype bf16`, not fp8 / not nvfp4.** FP8/NVFP4 KV on the compressed-latent attention path corrupts the latent reconstruction. We caught it once with `cutlass_scaled_mm` errors that turned out to be eating already-corrupted input. Pinning to BF16 made the cross-node hangs go away on top of fixing the numerics.

**3. GDR off, dmabuf off, `NCCL_PROTO=Simple`.** GB10's PCIe topology doesn't actually do peer-to-peer DMA to the NIC the way Hopper does, so leaving GDR on quietly hangs on the first cross-node MoE allreduce. Took us a couple of evenings to find this one.

If these three are already pinned in your repro and it still hangs, we've got a different problem than what we saw and I'd love to see your trace. If they're not, at least the commands above will give you a working serve while the vLLM TP=2 path gets unwedged.

**Comment by camerono** [comment]
Same hang class here. Two ASUS Ascent GX10 (same SoC as Spark), single QSFP56 cable, vLLM 0.20.1.dev + Ray 2.49 + `RedHatAI/Qwen3-Coder-Next-NVFP4`, TP=2 across both nodes.

Server starts cleanly, `/health` returns 200, an 18-token smoke request returns correct output. First real bench request (~2.7k token prompt) lands one inference, then dies ~60s in with:

```
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling cublasGemmEx(...)
  File "vllm/model_executor/layers/utils.py", line 98, in default_unquantized_gemm
    return torch.nn.functional.linear(x, weight, bias)
```

The failing op is the plain BF16 linear path, not the NVFP4 path. EngineCore dies, Ray DAG tears down, server shuts down.

What got it stable on the serve invocation:

```
VLLM_USE_RAY_COMPILED_DAG=0
VLLM_USE_RAY_SPMD_WORKER=0
VLLM_NVFP4_GEMM_BACKEND=marlin
VLLM_USE_FLASHINFER_MOE_FP4=0
CUBLAS_WORKSPACE_CONFIG=:4096:8
```

Plus `--enforce-eager`, `--max-num-seqs 4`, `--max-num-batched-tokens 4096`. Disabling Ray Compiled DAG was the load-bearing change. With these flags I ran the full Aider polyglot Python 34-exercise bench through TP=2 cleanly: pass@1 38.2, pass@2 61.8, 86.3 sec/case, 100% well-formed, no further crashes. Cost is ~37% per-case latency vs the same model single-node TP=1 (62.9 sec/case) — basically pricing the disabled torch.compile / cudagraph path.

NCCL side, single cable but both PCIe-domain halves of the cabled port are IP-configured and listed in `NCCL_IB_HCA=rocep1s0f1,roceP2p1s0f1` with `NCCL_IB_MERGE_NICS=1`. Allreduce sits around 24 Gbps which matches the community ceiling for this platform.

Haven't tried `--disable-custom-all-reduce` from majinghe's working config yet, planning to next round to see if it lets me drop `--enforce-eager`.

**Comment by nuk3s** [comment]
Same hang on the same class of hardware. I instrumented it and caught the live stall: the root cause is a per-rank CUDA-driver spin inside `sample_tokens`, not a NCCL or transport hang.

Setup: 2× DGX Spark (GB10, sm_121), MiniMax-M2.7 (AWQ-4bit), TP=2 across both nodes over RoCE, Ray executor, vLLM 0.21.1rc1.dev292, CUDA graphs on (`FULL_AND_PIECEWISE`). Serves fine for hours, then under concurrent long-context decode the API server dies with `RPC call to sample_tokens timed out`, preceded by `shm_broadcast "No available shared memory broadcast block found in 60 seconds"` repeating for 2-3 min. KV cache 15-30%, no Xid, not OOM. Time-to-hang ranges from 2h to 19h.

The NCCL flight recorder is useless for this: heartbeat never fires, dump dir empty every time. So I wrote a sniffer that watches the journal for the "No available shm block" line and fires py-spy + gdb at both ranks before the 180s timeout kills them. It caught one 118s before death.

If you try the same on Grace/ARM64: `py-spy dump --native` fails with `UNW_EBADREG`, and `docker exec py-spy` hits EPERM (no `CAP_SYS_PTRACE`, host `ptrace_scope=1`). What works is running the container's py-spy from the host under sudo against the worker's host PID (root bypasses yama scope), plus host `gdb -p <hostpid>` for the native frames.

The hang is asymmetric between the two ranks.

rank0 is stuck inside `sample_tokens`, native thread spinning in the CUDA driver:
```
py-spy:  worker_busy_loop (multiproc_executor.py:957) -> gpu_model_runner.sample_tokens
         -> _sample -> update_async_output_token_ids (gpu_input_batch.py:1042)
gdb:     #1 libcuda.so.1
         #2 libcuda.so.1   "previous frame identical to this frame"   (tight driver spin)
```

rank1 is idle, already back at the top of the loop waiting for the next task, not in any CUDA call:
```
py-spy:  worker_busy_loop (multiproc_executor.py:948) -> dequeue -> recv -> zmq_poll
gdb:     __poll -> zmq_poll   (no CUDA frames)
```

EngineCore is downstream: blocked in `shm_broadcast.acquire_read` waiting on rank0's response until the 180s timeout. NCCL watchdog and heartbeat threads are alive and idle on both ranks, which is why the flight recorder stays empty. So it's not a stuck collective. rank0's GPU work in `sample_tokens` is waiting on an event/stream sync that never signals while rank1 has already moved on. The two ranks desync (note the different loop line numbers, :957 vs :948) and the executor deadlocks.

The nvidia-smi reading matches the "GPUs pegged at 96-99%" reports, but I think it's being misread: both GPUs show 96% util at only ~15W, and a healthy decode step on this box pulls ~32W at the same util. The SMs are parked on a spin, not doing work.

Two things that don't help, confirmed by the capture:
- `--disable-custom-all-reduce`: no-op on a 2-node group. Custom AR is already auto-disabled cross-node ("Custom allreduce is disabled because this process group spans across nodes"); the TP all-reduce backend is pynccl. Configs that "fixed it" with this flag on multi-node weren't touching the all-reduce path.
- `--enforce-eager`: doesn't fix it (matches the thread), and the capture shows why: the spin is in the driver sync, not in graph dispatch.

The fix I'm testing now is `cudagraph_mode=FULL_DECODE_ONLY` (was `FULL_AND_PIECEWISE`). The stuck step is a graph-replayed decode+sample; this mode keeps decode-shape graphs but drops the mixed full/piecewise capture around the sampler, so no real decode-throughput cost. It's run ~48 min under the exact concurrent load that killed `FULL_AND_PIECEWISE` in ~45 min, with zero recurrences. Not calling it fixed given the 2-19h variance, but it's the first lever that's survived that load. I'll follow up with a longer run.

Env: driver 580.159.03, CUDA 13.2, torch 2.11, NCCL 2.30.4 loaded (torch's header reports 2.28.9, just the build header). I can post the full stacks or the capture script if useful.

**Comment by tbraun96** [comment]
@nuk3s this is a great capture, and the asymmetry you caught is the tell. Disclosure so it's on the table: I work on [Atlas](https://github.com/Avarok-Cybersecurity/atlas), a separate Rust runtime we run on the same 2x GB10 boxes, so this is a parallel data point rather than a vLLM fix.

We hit the same class of brick on concurrent long-context decode on GB10, and the signature you described (one rank parked in a driver spin at 96% util but only ~15W, the other rank already advanced to the next loop iteration, no stuck collective) is exactly what a per-step scratch buffer aliased across two consumers looks like. In our runtime it was two distinct bugs that both presented as this same "rank0 waiting on an event that never signals" stall:

1. A decode-metadata buffer colliding with a MoE shared-gate scratch region inside the logits buffer on mixed-shape batches. The sampler read a slot another consumer had already reused, so the stream sync it was waiting on never resolved.
2. Under concurrency >= 4 with deep (~8k) context, an SSM slot-pool exhaustion plus a slot-leak-on-abort that bricked the pool. Same outward symptom, different root.

The reason I bring it up: your `FULL_DECODE_ONLY` result is consistent with cause #1. The mixed full/piecewise capture is exactly the window where a per-step buffer gets reused across the sampler and a neighbor op, and dropping the mixed capture around the sampler closes that aliasing window without touching decode throughput. So I would not be surprised if it holds.

The 15W-at-96%-util reading is a good diagnostic to keep. A healthy decode step on this box pulls roughly 2x the wattage at the same util, so "pegged but cold" is a clean way to distinguish a spin from real work, which py-spy native already confirmed for you.

```
# the part of your capture I keep coming back to:
rank0: worker_busy_loop (multiproc_executor.py:957) -> sample_tokens  [spinning in libcuda]
rank1: worker_busy_loop (multiproc_executor.py:948) -> zmq_poll       [already next iter]
# different loop line numbers = the two ranks desynced, and the sampler step is where it shows
```

@nuk3s has `FULL_DECODE_ONLY` cleared the full 2-19h window yet, or just the 45-min repro so far? And I would genuinely like the journal-sniffer-plus-py-spy script if you are willing to drop it. The empty flight recorder problem is universal on these boxes and a reusable trigger would save everyone here a lot of time.

**Comment by nuk3s** [comment]
The fix of employing `FULL_DECODE_ONLY` has held for ~2 days for me at this point.  I will continue to conduct more reliability testing, but for my non-production load this is working fine.

**Comment by nuk3s** [comment]
I was hammering the GB10 stack today and, unfortunately, the fix did NOT hold and was triggered in the same manner with `rank0` stuck in `sample_tokens` and `rank1` idle at `zmq_poll`. I had removed my testing harness so I will re-instrument the stack , wait for another crash, and then report back.

**Comment by nNemy** [comment]
## vLLM 0.23.0, RTX 5090 sm_120, Qwen3.6-35B-A3B-NVFP4, single-GPU TP=1

### Environment

| | |
|---|---|
| GPU | RTX 5090 (Blackwell, sm_120), 32 GB, driver 595.x (open kernel modules), CUDA 13.x |
| vLLM | 0.23.0 |
| torch / flashinfer | 2.11.0 / 0.6.12 |
| Model | `nvidia/Qwen3.6-35B-A3B-NVFP4` — modelopt MIXED_PRECISION (NVFP4 MoE experts + FP8 linear-attn/GDN projections), FP8 KV, served text-only |
| Parallelism | TP=1, single GPU, no NCCL/multi-node |
| Flags | `max-model-len 131072`, `gpu-memory-utilization 0.85`, `max-num-seqs 3`, `kv-cache-dtype fp8`, `attention-backend flashinfer`, `enable-prefix-caching`, chunked-prefill on, `cudagraph_mode=FULL_AND_PIECEWISE` (default), async scheduling on (default) |

### How it was hit

Sustained chat-completion traffic (mixed prompt lengths, high prefix-cache hit rate, 1–3 concurrent requests) against the above config. After some hours the engine stops emitting tokens and does not recover until restart.

### State at the hang

- `vllm:num_requests_running = 1`, `num_requests_waiting = 0`, `num_preemptions_total = 0`
- `vllm:generation_tokens_total` and `prompt_tokens_total` frozen (identical across a 10s poll)
- `Avg ... throughput` stats line silent for ~70 min; no exception, no traceback
- `/health` and `/v1/models` return 200 throughout
- `nvidia-smi`: 100% util, ~112 W
- `/proc/<engine-main-tid>/`: `State: R`, `wchan: 0`; all other threads on `futex_do_wait`/`ep_poll`; CUDA driver threads (`cuda-EvtHandlr`) on `poll_schedule_timeout`

### py-spy (EngineCore MainThread, identical across repeated samples)

```
Thread (active): "MainThread"
    update_async_output_token_ids   (vllm/v1/worker/gpu_input_batch.py:1042)
    _sample                         (vllm/v1/worker/gpu_model_runner.py:3540)
    sample_tokens                   (vllm/v1/worker/gpu_model_runner.py:4420)
    sample_tokens                   (vllm/v1/worker/gpu_worker.py:803)
    run_method                      (vllm/v1/serial_utils.py:510)
    collective_rpc                  (vllm/v1/executor/uniproc_executor.py:96)
    sample_tokens                   (vllm/v1/executor/uniproc_executor.py:124)
    step_with_batch_queue           (vllm/v1/engine/core.py:530)
    _process_engine_step            (vllm/v1/engine/core.py:1268)
    run_busy_loop                   (vllm/v1/engine/core.py:1229)
    run_engine_core                 (vllm/v1/engine/core.py:1188)
```

Non-returning call:

```python
# vllm/v1/worker/gpu_input_batch.py  (update_async_output_token_ids)
if sampled_token_ids is None:
    assert self.async_copy_ready_event is not None
    self.async_copy_ready_event.synchronize()      # does not return
    sampled_token_ids = self.sampled_token_ids_cpu.tolist()
```

### Mitigation applied

`cudagraph_mode=FULL_DECODE_ONLY`. Will report recurrence or absence after extended runtime.

**Comment by marksunner** [comment]
Cross-linking a related RFC for TP deadlock detection and recovery, field-validated on 4× DGX Spark GB10 with two live deadlock captures (Type A collective desync + Type B event-sync hang), zero false triggers over multi-hour healthy soak. See #48720.

Key finding: NCCL RAS (already running on localhost:28028 since 2.24) shows per-rank collective counts that diagnose this class of wedge natively. The RFC proposes first-classing it.

**Comment by marksunner** [comment]
# Comment for vllm-project/vllm #41725 (sm_12x sampler event-sync hang) — for posting by Mark/Tars

We chased several multi-day hang classes on a 4× DGX Spark (GB10/sm_121)
GLM-5.2 TP=4 deployment and can contribute two data points to this issue's
class — all ranks frozen with equal per-rank collective counts, blocked in
`sample_tokens`:

1. We captured one hang matching this issue's class exactly (2026-07-15,
   "Type B" in our notes): all four ranks frozen with equal per-rank NCCL
   collective counts (NCCL RAS `ras_spread=0`), engine steps frozen equal,
   the stuck RPC being `sample_tokens`, no NCCL involvement — while a
   separate per-step cross-rank fingerprint detector we run showed zero
   pre-step divergence. NCCL RAS (enabled by default, port 28028) makes a
   cheap first discriminator between this class and collective-desync hangs:
   `echo -e "set format json\nverbose status" | nc localhost 28028` gives
   per-rank launched-op counts; equal-and-frozen points at this issue's
   class, spread>0 at a desync/wedge class. It is a first-pass sort, not a
   definitive classifier — confirm with stacks (py-spy/cuda-gdb) before
   attributing.

2. Most of what we initially attributed to sampler/event-sync hangs on this
   platform turned out to be a different bug entirely: the flashinfer
   `sparse_mla_sm120` attention kernels can livelock on GB10 (single block
   spinning forever at an mbarrier `SYNCS.PHASECHK.TRANS64.TRYWAIT`,
   cuda-gdb receipt; GPU reports 96 % util at ~18 W). Anyone debugging
   "96 % SM, low power, hosts stuck in cuLaunchKernel" hangs on sm_121
   sparse-MLA models should check that first — details in our RFC #48720
   thread update. Since routing the main model's attention to the Triton
   sparse-MLA path we have had zero wedges of any class: 560+ context-ceiling
   sessions (500 consecutive under our strictest config, ~25–27 tok/s at the
   120K boundary) plus a full cold staged climb to 200,000 tokens with a
   clean boundary completion at ~26 tok/s — the exact workload that
   previously wedged 8/8.

Practical debug notes for this platform: py-spy/cuda-gdb inside the
container require `docker exec -u root --privileged`; `nvidia-smi` power
draw is the fastest spin-vs-compute discriminator; and NCCL RAS is the
best always-on desync detector.

---
Full write-up, evidence pack, and related PR drafts: https://github.com/marksunner/glm52-dgx-spark-deadlock-evidence

**Comment by fank** [comment]
Possible fix for this, verified on 2× DGX Spark (GB10, SM121), vLLM 0.25.1, TP=2 `mp` backend: **swap the pip-bundled NCCL for the DGX-OS system NCCL.**

We hit what looks like exactly this hang (rank stuck spinning at ~96% GPU / ~20 W drawing no real power, peer blocked in `ncclAllReduce`, `shm_broadcast: No available shared memory broadcast block` as a downstream symptom, MTBF ~20–26 min under 4-way concurrent load). Like this thread, we burned time on levers that only shifted the MTBF: attention/MoE backend swaps, `--enforce-eager` (~doubles MTBF, doesn't fix), Ray + `--disable-custom-all-reduce` (changed the crash into a silent indefinite hang — arguably worse).

The one change that eliminated it (from #42354): the pip `nvidia-nccl-cu13` wheel and the DGX-OS apt `libnccl2` are both **2.28.9** but are **different builds** (219 MB / Build ID `a7f420a1…` vs 190 MB / `c0db9360…`). Symlinking the system lib over the wheel's path:

```bash
mv /usr/local/lib/python3.12/dist-packages/nvidia/nccl/lib/libnccl.so.2{,.pipbak}
ln -sf /usr/lib/aarch64-linux-gnu/libnccl.so.2 \
   /usr/local/lib/python3.12/dist-packages/nvidia/nccl/lib/libnccl.so.2
```

took the same config from watchdog-kill-at-~20-min (`_ALLGATHER_BASE` timeout after 600 s) to a clean **60-min soak, 420/420 requests, zero stall signatures**. After the swap we re-enabled CUDA graphs, FlashInfer attention, and FlashInfer CUTLASS MoE one at a time — all clean. On our boxes the NCCL build was the sole root cause.

Since @majinghe's report here was that Ray + `--disable-custom-all-reduce` "worked" — worth noting our Ray run also looked fine for ~26 min before silently stalling; a short check can mislead on this bug (it misled us twice). If you still have the setup, the NCCL swap + a ≥40-min sustained-load test would be a good validation datapoint.
