### ISSUE TITLE
[Performance]: Qwen3-VL-235B-A22B-Instruct NVFP4 Performance dropped at upstream main

### ISSUE THREAD

**Issue by Victor49152** [vllm-project/vllm#42096]
### Proposal to improve performance

# Performance regression on Qwen3-VL-235B-A22B-Instruct (NVFP4, GB300 / CUDA 13) — TTFT P99 +55-67%, plus several rough edges in current main

## TL;DR

Running Qwen3-VL-235B-A22B-Instruct (NVFP4 via compressed-tensors) on GB300 with TP=4 against the latest upstream nightly (`vllm/vllm-openai:nightly`, vllm `0.20.2rc1.dev93+g51f22dcfd`, May 7 2026, cu130, torch 2.11.0+cu130) shows a significant prefill-path regression vs a fork branched from main near `1cbbcfe8a334bab004c43a60be201c8ab528e0d2` (Mar 23 2026):

- **TTFT P99: +55%** (fp8 ViT static scale) to **+67%** (fp8 ViT OFF)
- **LAT  P99: +28% to +36%**
- **TPOT P99: ~0% (slightly faster, −7%)** — decode itself is fine in upstream

Plus three smaller papercuts that are worth filing alongside (see "Workarounds needed").

## Setup

- Hardware: GB300 (compute capability 10.0), 4 GPUs, NVLink, NVIDIA driver 580.159.04
- Model: `nvidia/Qwen3-VL-235B-A22B-Instruct-NVFP4-MLPerf-Inference-Closed-V6.0` (compressed-tensors NVFP4)
- Workload: online benchmark, target QPS=5 (Poisson), 1000 samples, num_workers=5, mixed multimodal Shopify product-catalogue dataset
- Engine config: TP=4, `max_model_len=32768`, `max_num_seqs=1024`
- Each cell: 1 cold + 3 warm runs against the same warmed server; mean is over the 3 warm runs (CV < 2%)

## Workarounds needed to make upstream nightly serve at all

These came up while preparing the comparison and should probably be tracked as separate bugs / docs gaps:

1. **`flashinfer_autotune` crashes on GB300 with `CUDA error: an illegal memory access`** during `kernel_warmup`. Stack trace points to `flashinfer.fused_moe.core` → `flashinfer.autotuner._prepare_input_tensors` → `torch.rand` on the routing-logits tensor. Workaround: `--kernel-config '{"enable_flashinfer_autotune": false}'`.

## Reproducer

```bash
# Container: vllm/vllm-openai:nightly  (multi-arch; pulls cu130+torch2.11 on aarch64)

# 1) one-time fp8 ViT scale calibration
vllm serve nvidia/Qwen3-VL-235B-A22B-Instruct-NVFP4-MLPerf-Inference-Closed-V6.0 \
  --tensor-parallel-size=4 --async-scheduling \
  --max-model-len=32768 --max-num-seqs=1024 --max-num-batched-tokens=13824 \
  --mm-encoder-attn-backend=FLASHINFER \
  --mm-encoder-attn-dtype=fp8 \
  --mm-encoder-fp8-scale-save-path=/tmp/q3vl_fp8_scales.json \
  --no-enable-prefix-caching \
  --kernel-config='{"enable_flashinfer_autotune": false}' \
  --compilation-config='{"cudagraph_mm_encoder":"true","encoder_cudagraph_token_budgets":[1024,2048,3072,4096,5120,6144,7168,8192],"encoder_cudagraph_max_vision_items_per_batch":16,"encoder_cudagraph_max_frames_per_batch":16,"max_cudagraph_capture_size":13824}' \
  &
# fire >=16 multimodal requests so the amax history wraps and scales are dumped to /tmp/q3vl_fp8_scales.json,
# then kill the server.

# 2) actual run with static scales
vllm serve nvidia/Qwen3-VL-235B-A22B-Instruct-NVFP4-MLPerf-Inference-Closed-V6.0 \
  --tensor-parallel-size=4 --async-scheduling \
  --max-model-len=32768 --max-num-seqs=1024 --max-num-batched-tokens=13824 \
  --mm-encoder-attn-backend=FLASHINFER \
  --mm-encoder-attn-dtype=fp8 \
  --mm-encoder-fp8-scale-path=/tmp/q3vl_fp8_scales.json \
  --no-enable-prefix-caching \
  --kernel-config='{"enable_flashinfer_autotune": false}' \
  --compilation-config='{...same as above...}'
```

Then run an online Poisson benchmark at QPS=5 for 1000 samples; report `latency.percentiles["99"]`, `ttft.percentiles["99"]`, `tpot.percentiles["99"]` from the warm-state samples (we discard the first cold bench).

## Numbers (warm-mean of 3 reps; ms unless noted; CV < 2%)

| cell                                          | LAT P50 | **LAT P99** | TTFT P50 | **TTFT P99** | TPOT P50 | **TPOT P99** |
|-----------------------------------------------|---------|-------------|----------|--------------|----------|--------------|
| Reference fork @ main `1cbbcfe8` (Mar 23)     | 608.7   | **1621.3**  | 103.7    | **744.2**    | 11.6     | **27.7**     |
| Upstream nightly `51f22dcfd` (May 7) fp8 stat | 585.2   | **2067.6**  | 140.4    | **1151.7**   | 10.3     | **25.7**     |
| Upstream nightly `51f22dcfd` (May 7) fp8 OFF  | 596.6   | **2205.7**  | 154.9    | **1244.9**   | 10.2     | **26.5**     |

Regression vs reference fork:

| metric    | upstream fp8 static | upstream fp8 OFF |
|-----------|--------------------:|-----------------:|
| LAT P50   |   −3.9 %            |   −2.0 %         |
| **LAT P99**   | **+27.5 %**     | **+36.0 %**      |
| TTFT P50  |  +35.4 %            |  +49.4 %         |
| **TTFT P99**  | **+54.8 %**     | **+67.3 %**      |
| TPOT P50  |  −11.2 %            |  −12.1 %         |
| TPOT P99  |   −7.2 %            |   −4.3 %         |

**Reading**: TPOT (decode) is unchanged-to-slightly-faster on upstream. The LAT P99 widening is driven entirely by TTFT — the prefill / encoder-side path is markedly slower in current upstream main than in the Mar 23 fork point.

## Internal bisection signal (for reviewers)

We did extensive ablations on a separate fork (B-fork ≈ main as of Apr 16) that also shows a regression vs the same Mar 23 base. The decomposition (warm steady-state, **same node**, B vs A on the fork):

| factor                                              | TTFT P99 closure | LAT P99 closure | TPOT P99 closure |
|----------------------------------------------------|-----------------:|----------------:|-----------------:|
| Encoder cudagraph (vllm #38061)                     | ~0pp            | ~0pp            | ~0pp             |
| FlashInfer 0.6.6 ⇄ 0.6.7 (whole dist-packages tar)  | 3.2pp           | 2.9pp           | 6.1pp            |
| compressed-tensors 0.14 ⇄ 0.15                      | 0.7pp           | 1.5pp           | 8.4pp            |
| FlashInfer FP4 MoE: `VLLM_USE_FLASHINFER_MOE_FP4=1`→`0` (B side only) | 1.3pp | 8.6pp | 11.9pp |
| FlashInfer sampler: `VLLM_USE_FLASHINFER_SAMPLER=1`→`0` (B side only) | 5.7pp | 1.4pp | ~0pp |
| Async scheduling                                    | ~0pp            | ~0pp            | ~0pp             |
| transformers 4.57 ⇄ 5.6 + tokenizers + huggingface_hub | ~0pp         | ~0pp            | ~0pp             |
| FP8 ViT attn ON vs OFF (intra-container)            | (perf ~+17%)    | (perf ~+17%)    | (perf ~+10%)     |
| **Residual (vllm code, torch 2.10→2.11, cublas/cudnn libs)** | **~14pp** | **~9pp**    | **~1pp**         |

**Notes on the two FlashInfer env-var ablations:**

- `VLLM_USE_FLASHINFER_MOE_FP4=0` makes the MoE layer of `Qwen3-VL-235B-A22B-Instruct-NVFP4` skip FlashInfer's NVFP4 fused-MoE GEMM and fall back to the default vllm MoE path (CUTLASS / triton, depending on layer). It only flips on the **B (regressed) side**, so the closure value is the difference between `B-with-FP4-MoE-env=1` and `B-with-FP4-MoE-env=0`, both compared against the same A baseline (which already runs with `=1`). Closure means "how much of the B vs A gap goes away when we disable the new FlashInfer FP4 MoE on B". `VLLM_FLASHINFER_MOE_BACKEND=latency` was kept the default in both cases (we also tried `=throughput`; it hung A and made B worse, so it's irrelevant).

- `VLLM_USE_FLASHINFER_SAMPLER=0` disables the FlashInfer Top-K/Top-P / sample-fused kernel and falls back to the default vllm sampler (`vllm/v1/sample/sampler.py`). Same protocol — flipped only on B. Closure = `(B/A with sampler env=1) − (B/A with sampler env=0)`.

(Numbers caveated by ~3pp inter-node hardware variance on GB300 — same-node measurements are tight, < 1.5% σ at LAT P99.)

The "residual" bucket — what's left after we ablate every available flag/env/library swap — is what the `+55-67%` TTFT P99 widening on upstream most likely lives in.

Likely-affected files (based on the affected window):
- `vllm/v1/attention/` — encoder attention dispatch
- `vllm/model_executor/models/qwen3_vl.py` and `qwen3_omni_moe_thinker.py`
- `vllm/v1/worker/gpu_model_runner.py`
- `vllm/compilation/` — encoder cudagraph capture path

### Your current environment (if you think it is necessary)

```text
The output of `python collect_env.py`
```

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by wangshangsam** [comment]
Thanks a lot, @Victor49152 ! Assigning this issue to @soodoshll and @BolinSNLHM

cc @ywang96

**Comment by wangshangsam** [comment]
@Victor49152 could you clarify how did you measure TTFT and TPOT? Through MLPerf Endpoints?

**Comment by Victor49152** [comment]
> flashinfer_autotune crashes on GB300 with CUDA error: an illegal memory access during kernel_warmup. Stack trace points to flashinfer.fused_moe.core → flashinfer.autotuner._prepare_input_tensors → torch.rand on the routing-logits tensor. Workaround: --kernel-config '{"enable_flashinfer_autotune": false}'.

This issue is fixed when manually upgrade flashinfer from 0.6.8.post1 to 0.6.10.post1

**Comment by Victor49152** [comment]
> [@Victor49152](https://github.com/Victor49152) could you clarify how did you measure TTFT and TPOT? Through MLPerf Endpoints?

Yes, these measurements are statistics report from MLPerf Endpoints, following the instruction [Here](https://github.com/mlcommons/endpoints/tree/main/examples/08_Qwen3-VL-235B-A22B_Example) and measured with online scenario (load_pattern: possion), QPS=5 and 1000 uniformly sampled subset from full Shopify/product-catalogue dataset

**Comment by ywang96** [comment]
@Victor49152 Can you try a setting without flashinfer/cuda graph-related code paths (i.e., the default setting) and see if it's affected too?

**Comment by Victor49152** [comment]
Flags used for a vanilla run where most settings remain default
- `--enforce-eager`
- No `--mm-encoder-attn-dtype=fp8`
- `--mm-encoder-attn-backend=TORCH_SDPA` (no FlashInfer for the encoder; needed because upstream's `vllm_flash_attn` cute SM100 kernel hardcodes `sm_100 ≤ arch ≤ sm_110f` and rejects GB300's actual `sm_103`)
- `VLLM_USE_FLASHINFER_SAMPLER=0`, `VLLM_USE_FLASHINFER_MOE_FP4=0` 
- `--no-enable-prefix-caching`

Results:
| cell        | LAT P99 (ms) | TTFT P99 (ms) | TPOT P99 (ms) |
|-------------|-------------:|--------------:|--------------:|
| A_basic     |     13142.6  |      1416.6   |       255.8   |
| B_basic     |     16194.5  |      1761.8   |       310.4   |
| C_basic     |     18015.5  |      1907.3   |       340.9   |


| comparison        | LAT P99 | TTFT P99 | TPOT P99 |
|-------------------|--------:|---------:|---------:|
| **B basic / A basic** | **+23.2 %** | **+24.4 %** | **+21.3 %** |
| **C basic / A basic** | **+37.1 %** | **+34.6 %** | **+33.3 %** |

A quick overview is that, the regression persists, and TPOT benefits is gone with no flashinfer/cudagraph.

**Comment by ywang96** [comment]
I'm pretty sure this is a TTFT regression only, but at the same time I'm wondering if it's a regression on the GPU side (ViT forward pass) or the preprocessing side.

It would be great if you can set output len for these runs to 1 (so we're running prefill only) and help getting some traces out of these runs!

**Comment by Victor49152** [comment]
Thanks @soodoshll for exploring the commit in between, based on his experiments, here is a commit map with related perf analysis.

```
  ┌──────┬───────────┬───────────────┬──────────────────────────────────────┐
  │ Date │    SHA    │      QPS      │                Notes                 │
  ├──────┼───────────┼───────────────┼──────────────────────────────────────┤
  │ 3/1  │ 8b5014d3d │ 14.15         │ baseline                             │
  ├──────┼───────────┼───────────────┼──────────────────────────────────────┤
  │ 3/30 │ bea23536f │ 14.62         │                                      │
  ├──────┼───────────┼───────────────┼──────────────────────────────────────┤
  │ 4/7  │ 2111997f9 │ 10.66         │ torch 2.11 upgrade — dip starts here │
  ├──────┼───────────┼───────────────┼──────────────────────────────────────┤
  │ 4/16 │ 17d87168d │ 10.59         │ still dipped                         │
  ├──────┼───────────┼───────────────┼──────────────────────────────────────┤
  │ 4/24 │ 51adca74e │ 14.51         │ recovered                            │
  ├──────┼───────────┼───────────────┼──────────────────────────────────────┤
 
```


However, we have concluded that vllm main perf drop has been restored at May 7th nightly, there was a env missing OMP_NUM_THREADS=64 at experiment about Upstream nightly 51f22dcfd (May 7) in the issue description, which caused the ttft drop. So i think this issue can be close now.  @ywang96 Just curious, is the drop between 3/30 and 4/16 has been studied somehow?
