### ISSUE TITLE
[Bug]: NameError: name 'vllm_ops' is not defined

### ISSUE THREAD

**Issue by yananchen1989** [vllm-project/vllm#4229]
### Your current environment

vllm version: 0.4.0.post1

### 🐛 Describe the bug

`CUDA_VISIBLE_DEVICES="4"  python -u -m vllm.entrypoints.openai.api_server     --model mistralai/Mistral-7B-Instruct-v0.2     --dtype auto --api-key yanan     --tensor-parallel-size 1 --port 1703 --host 0.0.0.0     --worker-use-ray --gpu-memory-utilization 1`

error:

> INFO 04-20 20:39:58 api_server.py:149] vLLM API server version 0.4.1
> INFO 04-20 20:39:58 api_server.py:150] args: Namespace(host='0.0.0.0', port=1703, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key='yanan', served_model_name=None, lora_modules=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='mistralai/Mistral-7B-Instruct-v0.2', tokenizer=None, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', worker_use_ray=True, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=1.0, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=5, disable_log_stats=False, quantization=None, enforce_eager=False, max_context_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', max_cpu_loras=None, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, scheduler_delay_factor=0.0, enable_chunked_prefill=False, speculative_model=None, num_speculative_tokens=None, model_loader_extra_config=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
> 2024-04-20 20:40:01,364 INFO worker.py:1749 -- Started a local Ray instance.
> INFO 04-20 20:40:02 llm_engine.py:98] Initializing an LLM engine (v0.4.1) with config: model='mistralai/Mistral-7B-Instruct-v0.2', speculative_config=None, tokenizer='mistralai/Mistral-7B-Instruct-v0.2', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0)
> INFO 04-20 20:40:05 utils.py:580] Found nccl from library /home/chenyanan/.config/vllm/nccl/cu12/libnccl.so.2.18.1
> INFO 04-20 20:40:06 selector.py:77] Cannot use FlashAttention backend because the flash_attn package is not found. Please install it for better performance.
> INFO 04-20 20:40:06 selector.py:33] Using XFormers backend.
> INFO 04-20 20:40:08 weight_utils.py:193] Using model weights format ['*.safetensors']
> INFO 04-20 20:40:10 model_runner.py:173] Loading model weights took 13.4966 GB
> ERROR 04-20 20:40:11 worker_base.py:153] Error executing method determine_num_available_blocks. This might cause deadlock in distributed execution.
> ERROR 04-20 20:40:11 worker_base.py:153] Traceback (most recent call last):
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/vllm/vllm/worker/worker_base.py", line 145, in execute_method
> ERROR 04-20 20:40:11 worker_base.py:153]     return executor(*args, **kwargs)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
> ERROR 04-20 20:40:11 worker_base.py:153]     return func(*args, **kwargs)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/vllm/vllm/worker/worker.py", line 138, in determine_num_available_blocks
> ERROR 04-20 20:40:11 worker_base.py:153]     self.model_runner.profile_run()
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
> ERROR 04-20 20:40:11 worker_base.py:153]     return func(*args, **kwargs)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/vllm/vllm/worker/model_runner.py", line 927, in profile_run
> ERROR 04-20 20:40:11 worker_base.py:153]     self.execute_model(seqs, kv_caches)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
> ERROR 04-20 20:40:11 worker_base.py:153]     return func(*args, **kwargs)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/vllm/vllm/worker/model_runner.py", line 848, in execute_model
> ERROR 04-20 20:40:11 worker_base.py:153]     hidden_states = model_executable(**execute_model_kwargs)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
> ERROR 04-20 20:40:11 worker_base.py:153]     return self._call_impl(*args, **kwargs)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
> ERROR 04-20 20:40:11 worker_base.py:153]     return forward_call(*args, **kwargs)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/vllm/vllm/model_executor/models/llama.py", line 360, in forward
> ERROR 04-20 20:40:11 worker_base.py:153]     hidden_states = self.model(input_ids, positions, kv_caches,
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
> ERROR 04-20 20:40:11 worker_base.py:153]     return self._call_impl(*args, **kwargs)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
> ERROR 04-20 20:40:11 worker_base.py:153]     return forward_call(*args, **kwargs)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/vllm/vllm/model_executor/models/llama.py", line 286, in forward
> ERROR 04-20 20:40:11 worker_base.py:153]     hidden_states, residual = layer(
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
> ERROR 04-20 20:40:11 worker_base.py:153]     return self._call_impl(*args, **kwargs)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
> ERROR 04-20 20:40:11 worker_base.py:153]     return forward_call(*args, **kwargs)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/vllm/vllm/model_executor/models/llama.py", line 224, in forward
> ERROR 04-20 20:40:11 worker_base.py:153]     hidden_states = self.input_layernorm(hidden_states)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
> ERROR 04-20 20:40:11 worker_base.py:153]     return self._call_impl(*args, **kwargs)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
> ERROR 04-20 20:40:11 worker_base.py:153]     return forward_call(*args, **kwargs)
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/vllm/vllm/model_executor/layers/layernorm.py", line 60, in forward
> ERROR 04-20 20:40:11 worker_base.py:153]     ops.rms_norm(
> ERROR 04-20 20:40:11 worker_base.py:153]   File "/home/chenyanan/vllm/vllm/_custom_ops.py", line 106, in rms_norm
> ERROR 04-20 20:40:11 worker_base.py:153]     vllm_ops.rms_norm(out, input, weight, epsilon)
> ERROR 04-20 20:40:11 worker_base.py:153] NameError: name 'vllm_ops' is not defined
> Traceback (most recent call last):
>   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/home/chenyanan/vllm/vllm/entrypoints/openai/api_server.py", line 157, in <module>
>     engine = AsyncLLMEngine.from_engine_args(
>   File "/home/chenyanan/vllm/vllm/engine/async_llm_engine.py", line 356, in from_engine_args
>     engine = cls(
>   File "/home/chenyanan/vllm/vllm/engine/async_llm_engine.py", line 319, in __init__
>     self.engine = self._init_engine(*args, **kwargs)
>   File "/home/chenyanan/vllm/vllm/engine/async_llm_engine.py", line 432, in _init_engine
>     return engine_class(*args, **kwargs)
>   File "/home/chenyanan/vllm/vllm/engine/llm_engine.py", line 153, in __init__
>     self._initialize_kv_caches()
>   File "/home/chenyanan/vllm/vllm/engine/llm_engine.py", line 228, in _initialize_kv_caches
>     self.model_executor.determine_num_available_blocks())
>   File "/home/chenyanan/vllm/vllm/executor/ray_gpu_executor.py", line 199, in determine_num_available_blocks
>     num_blocks = self._run_workers("determine_num_available_blocks", )
>   File "/home/chenyanan/vllm/vllm/executor/ray_gpu_executor.py", line 323, in _run_workers
>     driver_worker_output = self.driver_worker.execute_method(
>   File "/home/chenyanan/vllm/vllm/worker/worker_base.py", line 154, in execute_method
>     raise e
>   File "/home/chenyanan/vllm/vllm/worker/worker_base.py", line 145, in execute_method
>     return executor(*args, **kwargs)
>   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/chenyanan/vllm/vllm/worker/worker.py", line 138, in determine_num_available_blocks
>     self.model_runner.profile_run()
>   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/chenyanan/vllm/vllm/worker/model_runner.py", line 927, in profile_run
>     self.execute_model(seqs, kv_caches)
>   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/chenyanan/vllm/vllm/worker/model_runner.py", line 848, in execute_model
>     hidden_states = model_executable(**execute_model_kwargs)
>   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/chenyanan/vllm/vllm/model_executor/models/llama.py", line 360, in forward
>     hidden_states = self.model(input_ids, positions, kv_caches,
>   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/chenyanan/vllm/vllm/model_executor/models/llama.py", line 286, in forward
>     hidden_states, residual = layer(
>   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/chenyanan/vllm/vllm/model_executor/models/llama.py", line 224, in forward
>     hidden_states = self.input_layernorm(hidden_states)
>   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/home/chenyanan/anaconda3/envs/vllm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/home/chenyanan/vllm/vllm/model_executor/layers/layernorm.py", line 60, in forward
>     ops.rms_norm(
>   File "/home/chenyanan/vllm/vllm/_custom_ops.py", line 106, in rms_norm
>     vllm_ops.rms_norm(out, input, weight, epsilon)
> NameError: name 'vllm_ops' is not defined

**Comment by cybrtooth** [comment]
I just received this error as well. Seems to only happen on non-quantized mistral-7B models.

**Comment by yananchen1989** [comment]
using langchain can works, as an alternative.

https://python.langchain.com/docs/integrations/llms/vllm/
```
from langchain_community.llms import VLLM

llm_vllm = VLLM(model='mistralai/Mistral-7B-Instruct-v0.2',
           trust_remote_code=True,  # mandatory for hf models
           max_new_tokens=2048,
           temperature=1,
           # tensor_parallel_size=... # for distributed inference
)
```

**Comment by Bellk17** [comment]
I'm seeing the same issue.

Catching the import error gives:
`No module named 'vllm._C'`

Also seeing warnings during install:
```
...
CMake Warning at /home/tensorwave/install_vllm/venv/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
  static library kineto_LIBRARY-NOTFOUND not found.
Call Stack (most recent call first):
  /home/tensorwave/install_vllm/venv/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
  CMakeLists.txt:67 (find_package)


CMake Warning at CMakeLists.txt:124 (message):
  Pytorch version 2.1.1 expected for ROCMm 6.x build, saw 2.4.0 instead.


-- HIP supported arches: gfx906;gfx908;gfx90a;gfx940;gfx941;gfx942;gfx1030;gfx1100
-- HIP target arches: gfx942;gfx942;gfx942;gfx942;gfx942;gfx942;gfx942;gfx942
CMake Warning at CMakeLists.txt:266 (message):
  Unable to create _punica_C target because none of the requested
  architectures (gfx942;gfx942;gfx942;gfx942;gfx942;gfx942;gfx942;gfx942) are
  supported, i.e.  >= 8.0
...
```

Works when TP is not set.

Currently trying to get working with MI300x on ROCm 6.1.

**Comment by Bellk17** [comment]
Found fix; for me it was an issue for running benchmark test from the package directory. During installation, the `_C` module is compiled into the site-packages directory of the pip installation. When running from the source directory, the script is getting the code from source and not the installed package containing the compiled module.

Command:
- FROM `vllm` dir
- python3 benchmarks/benchmark_throughput.py --input-len=50 --output-len=100 --enforce-eager --tensor-parallel-size=6

Error:
`   
...
File "~/workspace/vllm/vllm/_custom_ops.py", line 176, in reshape_and_cache
     vllm_cache_ops.reshape_and_cache(key, value, key_cache, value_cache,
 NameError: name 'vllm_cache_ops' is not defined
 (Caught error: No module named 'vllm._C')
`

The script is picking up on the local module at `~/workspace/vllm/vllm` instead of the installed module. Running the command from a different directory, such as the benchmarks directory, fixes this.

@yananchen1989 I notice your stack trace is also coming from source, `/home/chenyanan/vllm/vllm/_custom_ops.py`, try running from a separate directory after installing source. Let me know if this fixes the issue.

That being said, the try / except imports are causing unhelpful stack traces; I will look into doing an audit of compiled modules and adding useful warnings when not detected.

**Comment by leiwen83** [comment]
tests/ folder also suffer from this vllm_ops not defined issue.

And I create this PR for pytest, https://github.com/vllm-project/vllm/pull/4231, which force pytest to search module from installed place.

**Comment by dagelf** [comment]
I get this error after doing a clean install with `pip install -e .` of commit 26f2fb51133c85ad8a57a87c8037f750dda757f4. There were no errors during the installation... but this runtime error might be because I used too new dependencies (Python 3.10.12, Pytorch 2.3, Cuda 12.4)?

**Comment by chrisociepa** [comment]
it looks like Pytorch 2.3.0 causes the problem

**Comment by Semihal** [comment]
I have this error:

```
INFO 05-22 14:25:08 utils.py:660] Found nccl from library /lib64/libnccl.so.2
INFO 05-22 14:25:09 selector.py:81] Cannot use FlashAttention-2 backend because the flash_attn package is not found. Please install it for better performance.
INFO 05-22 14:25:09 selector.py:32] Using XFormers backend.
INFO 05-22 14:25:34 model_runner.py:175] Loading model weights took 13.5516 GB
[rank0]: Traceback (most recent call last):
[rank0]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank0]:   File "<frozen runpy>", line 88, in _run_code
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/entrypoints/openai/api_server.py", line 168, in <module>
[rank0]:     engine = AsyncLLMEngine.from_engine_args(
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 366, in from_engine_args
[rank0]:     engine = cls(
[rank0]:              ^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 324, in __init__
[rank0]:     self.engine = self._init_engine(*args, **kwargs)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/async_llm_engine.py", line 442, in _init_engine
[rank0]:     return engine_class(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/llm_engine.py", line 172, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/engine/llm_engine.py", line 249, in _initialize_kv_caches
[rank0]:     self.model_executor.determine_num_available_blocks())
[rank0]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/executor/gpu_executor.py", line 106, in determine_num_available_blocks
[rank0]:     return self.driver_worker.determine_num_available_blocks()
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/worker/worker.py", line 139, in determine_num_available_blocks
[rank0]:     self.model_runner.profile_run()
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/worker/model_runner.py", line 888, in profile_run
[rank0]:     self.execute_model(seqs, kv_caches)
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/worker/model_runner.py", line 808, in execute_model
[rank0]:     hidden_states = model_executable(**execute_model_kwargs)
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 316, in forward
[rank0]:     hidden_states = self.model(input_ids, positions, kv_caches,
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 253, in forward
[rank0]:     hidden_states, residual = layer(
[rank0]:                               ^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/model_executor/models/qwen2.py", line 202, in forward
[rank0]:     hidden_states = self.input_layernorm(hidden_states)
[rank0]:                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/model_executor/layers/layernorm.py", line 60, in forward
[rank0]:     ops.rms_norm(
[rank0]:   File "/usr/local/lib64/python3.11/site-packages/vllm/_custom_ops.py", line 106, in rms_norm
[rank0]:     vllm_ops.rms_norm(out, input, weight, epsilon)
[rank0]:     ^^^^^^^^
[rank0]: NameError: name 'vllm_ops' is not defined
```

**Comment by dong-liuliu** [comment]
> Found fix; for me it was an issue for running benchmark test from the source directory. During installation, the `_C` module is compiled into the site-packages directory of the pip installation. When running from the source directory, the script is getting the code from source and not the installed package containing the compiled module.
> 
> Command:
> 
> * FROM `vllm` dir
> * python3 benchmarks/benchmark_throughput.py --input-len=50 --output-len=100 --enforce-eager --tensor-parallel-size=6
> 
> Error: ` ... File "~/workspace/vllm/vllm/_custom_ops.py", line 176, in reshape_and_cache vllm_cache_ops.reshape_and_cache(key, value, key_cache, value_cache, NameError: name 'vllm_cache_ops' is not defined (Caught error: No module named 'vllm._C')`
> 
> The script is picking up on the local module at `~/workspace/vllm/vllm` instead of the installed module. Running the command from a different directory, such as the benchmarks directory, fixes this.
> 
> @yananchen1989 I notice your stack trace is also coming from source, `/home/chenyanan/vllm/vllm/_custom_ops.py`, try running from a separate directory after installing / compiling source. Let me know if this fixes the issue.
> 
> That being said, the try / except imports are causing unhelpful stack traces; I will look into doing an audit of compiled modules and adding useful warnings when not detected.

I also met this error. And **it was fixed after changing working directory out of the vllm source code.**
If your error stack trace has shown with your specific path, then try to 'cd' out.

Probably many of us have a same habit to directly run tests or getting-start at the source code dir :)

**Comment by DarkLight1337** [comment]
Fixed by #5009

**Comment by DarkLight1337** [comment]
Please follow [these instructions from the docs](https://docs.vllm.ai/en/stable/getting_started/installation.html#build-from-source).
