### ISSUE TITLE
[Doc]: Integration Issue: Qwen3.6-27B-FP8 with Codex via vLLM Server

### ISSUE THREAD

**Issue by lazyn1997** [vllm-project/vllm#42475]
### 📚 The doc issue

Issue Description:
I followed the tutorial in the codex.mddocumentation to integrate the Qwen3.6-27B model into Codex. The vLLM server configuration is as follows:
``` bash
#!/bin/bash
set -e

MODEL_PATH="/home/user/vllm-server/models/Qwen3.6-27B-FP8"
MODEL_NAME=$(basename "$MODEL_PATH" | tr '[:upper:]' '[:lower:]')

export CUDA_VISIBLE_DEVICES=0,1
export NCCL_P2P_DISABLE=0
export NCCL_IB_DISABLE=1
export NCCL_SHM_DISABLE=0
export NCCL_DEBUG=WARN
export CUDA_DEVICE_MAX_CONNECTIONS=1

source ~/miniconda3/etc/profile.d/conda.sh
conda activate vllm

exec vllm serve "$MODEL_PATH" \
  --tensor-parallel-size 2 \
  --kv-cache-dtype fp8 \
  --max-model-len 204800 \
  --max-num-seqs 8 \
  --gpu-memory-utilization 0.92 \
  --disable-custom-all-reduce \
  --trust-remote-code \
  --enable-auto-tool-choice \
  --tool-call-parser qwen3_coder \
  --chat-template-content-format openai \
  --enable-chunked-prefill \
  --host 0.0.0.0 \
  --port 8001 \
  --served-model-name "$MODEL_NAME"
```
After issuing a command in Codex, the following error occurred:

```
{"error":{"message":"18 validation errors:\n {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'FunctionTool', 'type'), 'msg': \"Input should be 'function'\", 'input': 'namespace', 'ctx': {'expected': \"'function'\"}}\n {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'FileSearchTool', 'type'), 'msg': \"Input should be 'file_search'\", 'input': 'namespace', 'ctx': {'expected': \"'file_search'\"}}\n {'type': 'missing', 'loc': ('body', 'tools', 11, 'FileSearchTool', 'vector_store_ids'), 'msg': 'Field required', 'input': {'type': 'namespace', 'name': 'codex_app', 'description': 'Tools in the codex_app namespace.', 'tools': [{'type': 'function', 'name': 'automation_update', 'description': 'Create, update, view, or delete recurring automations in the Codex app. Use this when the user asks for an automation, recurring run, repeated task, reminder, follow-up, monitor, or asks you to watch something, keep an eye on it, check back later, wake up later, notify them, or keep working later. Cron automations run as standalone jobs against workspaces. Heartbeat automations are proactive follow-ups attached to the current local thread. Prefer heartbeats for requests to continue this thread later, especially below one hour. Use suggested_create or suggested_update when proposing a worktree automation with a local environment setup config so the user can review it before it is saved. Never write raw automation directives by hand, show raw RRULE strings to the user, or create a workaround cron automation for a thread heartbeat unless the user explicitly asks for that. For requests about existing automations, inspect $CODEX_HOME/automations/*/automation.toml to find matching automation ids by name or prompt. Prefer updating an existing automation over creating a duplicate. For updates, preserve existing fields unless the user asks to change them, and call automation_update with the resolved id and full updated fields.', 'strict': False, 'parameters': {'type': 'object', 'properties': {'cwds': {'description': 'Cron automations only. Workspace directories for the automation; can be a JSON array or comma-separated string.', 'anyOf': [{'type': 'string'}, {'type': 'array', 'items': {'type': 'string'}}]}, 'destination': {'type': 'string', 'description': 'Optional automation destination. Use thread for heartbeat automations attached to the current local thread.'}, 'executionEnvironment': {'type': 'string', 'description': 'One of worktree or local. Cron automations only.'}, 'id': {'type': 'string', 'description': 'Automation id. Required for mode=view, mode=update, mode=delete, and mode=suggested_update. Omit for mode=create and mode=suggested_create.'}, 'kind': {'type': 'string', 'description': 'One of cron or heartbeat. Required for create, update, suggested_create, and suggested_update. Use cron for detached workspace jobs. Use heartbeat when the user wants this thread to wake up later and continue the conversation.'}, 'localEnvironmentConfigPath': {'type': ['string', 'null'], 'description': 'Optional local environment config path for worktree setup scripts. Immediate worktree create calls with a non-null value and immediate worktree update calls that preserve or set a setup config are rejected; use suggested_create/suggested_update for user review. Pass null to clear or run without setup. Cron automations only.'}, 'mode': {'type': 'string', 'description': 'One of view, create, update, delete, suggested_create, or suggested_update. Use view to show an existing automation, create/update/delete to mutate immediately, and suggested_create/suggested_update to present a proposal for the user to review.'}, 'model': {'type': 'string', 'description': 'Model to use for cron automations.'}, 'name': {'type': 'string', 'description': 'Short human-readable automation name. If the user does not provide one, choose a concise name.'}, 'prompt': {'type': 'string', 'description': 'The automation prompt. Describe only the task itself; do not include schedule, workspace, or thread details because those are provided separately. Keep it self-sufficient, include output expectations when useful, and do not ask it to write a file or announce nothing to do unless the user explicitly asked for that.'}, 'reasoningEffort': {'type': 'string', 'description': 'Reasoning effort to use for cron automations. One of none, minimal, low, medium, high, or xhigh.'}, 'rrule': {'type': 'string', 'description': \"RRULE schedule string. Interpret requested times in the user's locale. Cron automations use hourly interval or weekly schedules. Heartbeat automations attached to a thread can use minute-based intervals such as FREQ=MINUTELY;INTERVAL=30 or daily/weekly wall-clock schedules.\"}, 'status': {'type': 'string', 'description': 'One of ACTIVE or PAUSED. Default to ACTIVE unless the user asks to start paused.'}, 'targetThreadId': {'type': 'string', 'description': 'Target thread id for heartbeat automations. Prefer destination=thread for the current local thread instead of inventing or copying raw thread ids.'}}, 'additionalProperties': False}}]}}\n {'type': 'missing', 'loc': ('body', 'tools', 11, 'ComputerTool', 'display_height'), 'msg': 'Field required', 'input': {'type': 'namespace', 'name': 'codex_app', 'description': 'Tools in the codex_app namespace.', 'tools': [{'type': 'function', 'name': 'automation_update', 'description': 'Create, update, view, or delete recurring automations in the Codex app. Use this when the user asks for an automation, recurring run, repeated task, reminder, follow-up, monitor, or asks you to watch something, keep an eye on it, check back later, wake up later, notify them, or keep working later. Cron automations run as standalone jobs against workspaces. Heartbeat automations are proactive follow-ups attached to the current local thread. Prefer heartbeats for requests to continue this thread later, especially below one hour. Use suggested_create or suggested_update when proposing a worktree automation with a local environment setup config so the user can review it before it is saved. Never write raw automation directives by hand, show raw RRULE strings to the user, or create a workaround cron automation for a thread heartbeat unless the user explicitly asks for that. For requests about existing automations, inspect $CODEX_HOME/automations/*/automation.toml to find matching automation ids by name or prompt. Prefer updating an existing automation over creating a duplicate. For updates, preserve existing fields unless the user asks to change them, and call automation_update with the resolved id and full updated fields.', 'strict': False, 'parameters': {'type': 'object', 'properties': {'cwds': {'description': 'Cron automations only. Workspace directories for the automation; can be a JSON array or comma-separated string.', 'anyOf': [{'type': 'string'}, {'type': 'array', 'items': {'type': 'string'}}]}, 'destination': {'type': 'string', 'description': 'Optional automation destination. Use thread for heartbeat automations attached to the current local thread.'}, 'executionEnvironment': {'type': 'string', 'description': 'One of worktree or local. Cron automations only.'}, 'id': {'type': 'string', 'description': 'Automation id. Required for mode=view, mode=update, mode=delete, and mode=suggested_update. Omit for mode=create and mode=suggested_create.'}, 'kind': {'type': 'string', 'description': 'One of cron or heartbeat. Required for create, update, suggested_create, and suggested_update. Use cron for detached workspace jobs. Use heartbeat when the user wants this thread to wake up later and continue the conversation.'}, 'localEnvironmentConfigPath': {'type': ['string', 'null'], 'description': 'Optional local environment config path for worktree setup scripts. Immediate worktree create calls with a non-null value and immediate worktree update calls that preserve or set a setup config are rejected; use suggested_create/suggested_update for user review. Pass null to clear or run without setup. Cron automations only.'}, 'mode': {'type': 'string', 'description': 'One of view, create, update, delete, suggested_create, or suggested_update. Use view to show an existing automation, create/update/delete to mutate immediately, and suggested_create/suggested_update to present a proposal for the user to review.'}, 'model': {'type': 'string', 'description': 'Model to use for cron automations.'}, 'name': {'type': 'string', 'description': 'Short human-readable automation name. If the user does not provide one, choose a concise name.'}, 'prompt': {'type': 'string', 'description': 'The automation prompt. Describe only the task itself; do not include schedule, workspace, or thread details because those are provided separately. Keep it self-sufficient, include output expectations when useful, and do not ask it to write a file or announce nothing to do unless the user explicitly asked for that.'}, 'reasoningEffort': {'type': 'string', 'description': 'Reasoning effort to use for cron automations. One of none, minimal, low, medium, high, or xhigh.'}, 'rrule': {'type': 'string', 'description': \"RRULE schedule string. Interpret requested times in the user's locale. Cron automations use hourly interval or weekly schedules. Heartbeat automations attached to a thread can use minute-based intervals such as FREQ=MINUTELY;INTERVAL=30 or daily/weekly wall-clock schedules.\"}, 'status': {'type': 'string', 'description': 'One of ACTIVE or PAUSED. Default to ACTIVE unless the user asks to start paused.'}, 'targetThreadId': {'type': 'string', 'description': 'Target thread id for heartbeat automations. Prefer destination=thread for the current local thread instead of inventing or copying raw thread ids.'}}, 'additionalProperties': False}}]}}\n {'type': 'missing', 'loc': ('body', 'tools', 11, 'ComputerTool', 'display_width'), 'msg': 'Field required', 'input': {'type': 'namespace', 'name': 'codex_app', 'description': 'Tools in the codex_app namespace.', 'tools': [{'type': 'function', 'name': 'automation_update', 'description': 'Create, update, view, or delete recurring automations in the Codex app. Use this when the user asks for an automation, recurring run, repeated task, reminder, follow-up, monitor, or asks you to watch something, keep an eye on it, check back later, wake up later, notify them, or keep working later. Cron automations run as standalone jobs against workspaces. Heartbeat automations are proactive follow-ups attached to the current local thread. Prefer heartbeats for requests to continue this thread later, especially below one hour. Use suggested_create or suggested_update when proposing a worktree automation with a local environment setup config so the user can review it before it is saved. Never write raw automation directives by hand, show raw RRULE strings to the user, or create a workaround cron automation for a thread heartbeat unless the user explicitly asks for that. For requests about existing automations, inspect $CODEX_HOME/automations/*/automation.toml to find matching automation ids by name or prompt. Prefer updating an existing automation over creating a duplicate. For updates, preserve existing fields unless the user asks to change them, and call automation_update with the resolved id and full updated fields.', 'strict': False, 'parameters': {'type': 'object', 'properties': {'cwds': {'description': 'Cron automations only. Workspace directories for the automation; can be a JSON array or comma-separated string.', 'anyOf': [{'type': 'string'}, {'type': 'array', 'items': {'type': 'string'}}]}, 'destination': {'type': 'string', 'description': 'Optional automation destination. Use thread for heartbeat automations attached to the current local thread.'}, 'executionEnvironment': {'type': 'string', 'description': 'One of worktree or local. Cron automations only.'}, 'id': {'type': 'string', 'description': 'Automation id. Required for mode=view, mode=update, mode=delete, and mode=suggested_update. Omit for mode=create and mode=suggested_create.'}, 'kind': {'type': 'string', 'description': 'One of cron or heartbeat. Required for create, update, suggested_create, and suggested_update. Use cron for detached workspace jobs. Use heartbeat when the user wants this thread to wake up later and continue the conversation.'}, 'localEnvironmentConfigPath': {'type': ['string', 'null'], 'description': 'Optional local environment config path for worktree setup scripts. Immediate worktree create calls with a non-null value and immediate worktree update calls that preserve or set a setup config are rejected; use suggested_create/suggested_update for user review. Pass null to clear or run without setup. Cron automations only.'}, 'mode': {'type': 'string', 'description': 'One of view, create, update, delete, suggested_create, or suggested_update. Use view to show an existing automation, create/update/delete to mutate immediately, and suggested_create/suggested_update to present a proposal for the user to review.'}, 'model': {'type': 'string', 'description': 'Model to use for cron automations.'}, 'name': {'type': 'string', 'description': 'Short human-readable automation name. If the user does not provide one, choose a concise name.'}, 'prompt': {'type': 'string', 'description': 'The automation prompt. Describe only the task itself; do not include schedule, workspace, or thread details because those are provided separately. Keep it self-sufficient, include output expectations when useful, and do not ask it to write a file or announce nothing to do unless the user explicitly asked for that.'}, 'reasoningEffort': {'type': 'string', 'description': 'Reasoning effort to use for cron automations. One of none, minimal, low, medium, high, or xhigh.'}, 'rrule': {'type': 'string', 'description': \"RRULE schedule string. Interpret requested times in the user's locale. Cron automations use hourly interval or weekly schedules. Heartbeat automations attached to a thread can use minute-based intervals such as FREQ=MINUTELY;INTERVAL=30 or daily/weekly wall-clock schedules.\"}, 'status': {'type': 'string', 'description': 'One of ACTIVE or PAUSED. Default to ACTIVE unless the user asks to start paused.'}, 'targetThreadId': {'type': 'string', 'description': 'Target thread id for heartbeat automations. Prefer destination=thread for the current local thread instead of inventing or copying raw thread ids.'}}, 'additionalProperties': False}}]}}\n {'type': 'missing', 'loc': ('body', 'tools', 11, 'ComputerTool', 'environment'), 'msg': 'Field required', 'input': {'type': 'namespace', 'name': 'codex_app', 'description': 'Tools in the codex_app namespace.', 'tools': [{'type': 'function', 'name': 'automation_update', 'description': 'Create, update, view, or delete recurring automations in the Codex app. Use this when the user asks for an automation, recurring run, repeated task, reminder, follow-up, monitor, or asks you to watch something, keep an eye on it, check back later, wake up later, notify them, or keep working later. Cron automations run as standalone jobs against workspaces. Heartbeat automations are proactive follow-ups attached to the current local thread. Prefer heartbeats for requests to continue this thread later, especially below one hour. Use suggested_create or suggested_update when proposing a worktree automation with a local environment setup config so the user can review it before it is saved. Never write raw automation directives by hand, show raw RRULE strings to the user, or create a workaround cron automation for a thread heartbeat unless the user explicitly asks for that. For requests about existing automations, inspect $CODEX_HOME/automations/*/automation.toml to find matching automation ids by name or prompt. Prefer updating an existing automation over creating a duplicate. For updates, preserve existing fields unless the user asks to change them, and call automation_update with the resolved id and full updated fields.', 'strict': False, 'parameters': {'type': 'object', 'properties': {'cwds': {'description': 'Cron automations only. Workspace directories for the automation; can be a JSON array or comma-separated string.', 'anyOf': [{'type': 'string'}, {'type': 'array', 'items': {'type': 'string'}}]}, 'destination': {'type': 'string', 'description': 'Optional automation destination. Use thread for heartbeat automations attached to the current local thread.'}, 'executionEnvironment': {'type': 'string', 'description': 'One of worktree or local. Cron automations only.'}, 'id': {'type': 'string', 'description': 'Automation id. Required for mode=view, mode=update, mode=delete, and mode=suggested_update. Omit for mode=create and mode=suggested_create.'}, 'kind': {'type': 'string', 'description': 'One of cron or heartbeat. Required for create, update, suggested_create, and suggested_update. Use cron for detached workspace jobs. Use heartbeat when the user wants this thread to wake up later and continue the conversation.'}, 'localEnvironmentConfigPath': {'type': ['string', 'null'], 'description': 'Optional local environment config path for worktree setup scripts. Immediate worktree create calls with a non-null value and immediate worktree update calls that preserve or set a setup config are rejected; use suggested_create/suggested_update for user review. Pass null to clear or run without setup. Cron automations only.'}, 'mode': {'type': 'string', 'description': 'One of view, create, update, delete, suggested_create, or suggested_update. Use view to show an existing automation, create/update/delete to mutate immediately, and suggested_create/suggested_update to present a proposal for the user to review.'}, 'model': {'type': 'string', 'description': 'Model to use for cron automations.'}, 'name': {'type': 'string', 'description': 'Short human-readable automation name. If the user does not provide one, choose a concise name.'}, 'prompt': {'type': 'string', 'description': 'The automation prompt. Describe only the task itself; do not include schedule, workspace, or thread details because those are provided separately. Keep it self-sufficient, include output expectations when useful, and do not ask it to write a file or announce nothing to do unless the user explicitly asked for that.'}, 'reasoningEffort': {'type': 'string', 'description': 'Reasoning effort to use for cron automations. One of none, minimal, low, medium, high, or xhigh.'}, 'rrule': {'type': 'string', 'description': \"RRULE schedule string. Interpret requested times in the user's locale. Cron automations use hourly interval or weekly schedules. Heartbeat automations attached to a thread can use minute-based intervals such as FREQ=MINUTELY;INTERVAL=30 or daily/weekly wall-clock schedules.\"}, 'status': {'type': 'string', 'description': 'One of ACTIVE or PAUSED. Default to ACTIVE unless the user asks to start paused.'}, 'targetThreadId': {'type': 'string', 'description': 'Target thread id for heartbeat automations. Prefer destination=thread for the current local thread instead of inventing or copying raw thread ids.'}}, 'additionalProperties': False}}]}}\n {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'ComputerTool', 'type'), 'msg': \"Input should be 'computer_use_preview'\", 'input': 'namespace', 'ctx': {'expected': \"'computer_use_preview'\"}}\n {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'WebSearchTool', 'type'), 'msg': \"Input should be 'web_search' or 'web_search_2025_08_26'\", 'input': 'namespace', 'ctx': {'expected': \"'web_search' or 'web_search_2025_08_26'\"}}\n {'type': 'missing', 'loc': ('body', 'tools', 11, 'Mcp', 'server_label'), 'msg': 'Field required', 'input': {'type': 'namespace', 'name': 'codex_app', 'description': 'Tools in the codex_app namespace.', 'tools': [{'type': 'function', 'name': 'automation_update', 'description': 'Create, update, view, or delete recurring automations in the Codex app. Use this when the user asks for an automation, recurring run, repeated task, reminder, follow-up, monitor, or asks you to watch something, keep an eye on it, check back later, wake up later, notify them, or keep working later. Cron automations run as standalone jobs against workspaces. Heartbeat automations are proactive follow-ups attached to the current local thread. Prefer heartbeats for requests to continue this thread later, especially below one hour. Use suggested_create or suggested_update when proposing a worktree automation with a local environment setup config so the user can review it before it is saved. Never write raw automation directives by hand, show raw RRULE strings to the user, or create a workaround cron automation for a thread heartbeat unless the user explicitly asks for that. For requests about existing automations, inspect $CODEX_HOME/automations/*/automation.toml to find matching automation ids by name or prompt. Prefer updating an existing automation over creating a duplicate. For updates, preserve existing fields unless the user asks to change them, and call automation_update with the resolved id and full updated fields.', 'strict': False, 'parameters': {'type': 'object', 'properties': {'cwds': {'description': 'Cron automations only. Workspace directories for the automation; can be a JSON array or comma-separated string.', 'anyOf': [{'type': 'string'}, {'type': 'array', 'items': {'type': 'string'}}]}, 'destination': {'type': 'string', 'description': 'Optional automation destination. Use thread for heartbeat automations attached to the current local thread.'}, 'executionEnvironment': {'type': 'string', 'description': 'One of worktree or local. Cron automations only.'}, 'id': {'type': 'string', 'description': 'Automation id. Required for mode=view, mode=update, mode=delete, and mode=suggested_update. Omit for mode=create and mode=suggested_create.'}, 'kind': {'type': 'string', 'description': 'One of cron or heartbeat. Required for create, update, suggested_create, and suggested_update. Use cron for detached workspace jobs. Use heartbeat when the user wants this thread to wake up later and continue the conversation.'}, 'localEnvironmentConfigPath': {'type': ['string', 'null'], 'description': 'Optional local environment config path for worktree setup scripts. Immediate worktree create calls with a non-null value and immediate worktree update calls that preserve or set a setup config are rejected; use suggested_create/suggested_update for user review. Pass null to clear or run without setup. Cron automations only.'}, 'mode': {'type': 'string', 'description': 'One of view, create, update, delete, suggested_create, or suggested_update. Use view to show an existing automation, create/update/delete to mutate immediately, and suggested_create/suggested_update to present a proposal for the user to review.'}, 'model': {'type': 'string', 'description': 'Model to use for cron automations.'}, 'name': {'type': 'string', 'description': 'Short human-readable automation name. If the user does not provide one, choose a concise name.'}, 'prompt': {'type': 'string', 'description': 'The automation prompt. Describe only the task itself; do not include schedule, workspace, or thread details because those are provided separately. Keep it self-sufficient, include output expectations when useful, and do not ask it to write a file or announce nothing to do unless the user explicitly asked for that.'}, 'reasoningEffort': {'type': 'string', 'description': 'Reasoning effort to use for cron automations. One of none, minimal, low, medium, high, or xhigh.'}, 'rrule': {'type': 'string', 'description': \"RRULE schedule string. Interpret requested times in the user's locale. Cron automations use hourly interval or weekly schedules. Heartbeat automations attached to a thread can use minute-based intervals such as FREQ=MINUTELY;INTERVAL=30 or daily/weekly wall-clock schedules.\"}, 'status': {'type': 'string', 'description': 'One of ACTIVE or PAUSED. Default to ACTIVE unless the user asks to start paused.'}, 'targetThreadId': {'type': 'string', 'description': 'Target thread id for heartbeat automations. Prefer destination=thread for the current local thread instead of inventing or copying raw thread ids.'}}, 'additionalProperties': False}}]}}\n {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'Mcp', 'type'), 'msg': \"Input should be 'mcp'\", 'input': 'namespace', 'ctx': {'expected': \"'mcp'\"}}\n {'type': 'missing', 'loc': ('body', 'tools', 11, 'CodeInterpreter', 'container'), 'msg': 'Field required', 'input': {'type': 'namespace', 'name': 'codex_app', 'description': 'Tools in the codex_app namespace.', 'tools': [{'type': 'function', 'name': 'automation_update', 'description': 'Create, update, view, or delete recurring automations in the Codex app. Use this when the user asks for an automation, recurring run, repeated task, reminder, follow-up, monitor, or asks you to watch something, keep an eye on it, check back later, wake up later, notify them, or keep working later. Cron automations run as standalone jobs against workspaces. Heartbeat automations are proactive follow-ups attached to the current local thread. Prefer heartbeats for requests to continue this thread later, especially below one hour. Use suggested_create or suggested_update when proposing a worktree automation with a local environment setup config so the user can review it before it is saved. Never write raw automation directives by hand, show raw RRULE strings to the user, or create a workaround cron automation for a thread heartbeat unless the user explicitly asks for that. For requests about existing automations, inspect $CODEX_HOME/automations/*/automation.toml to find matching automation ids by name or prompt. Prefer updating an existing automation over creating a duplicate. For updates, preserve existing fields unless the user asks to change them, and call automation_update with the resolved id and full updated fields.', 'strict': False, 'parameters': {'type': 'object', 'properties': {'cwds': {'description': 'Cron automations only. Workspace directories for the automation; can be a JSON array or comma-separated string.', 'anyOf': [{'type': 'string'}, {'type': 'array', 'items': {'type': 'string'}}]}, 'destination': {'type': 'string', 'description': 'Optional automation destination. Use thread for heartbeat automations attached to the current local thread.'}, 'executionEnvironment': {'type': 'string', 'description': 'One of worktree or local. Cron automations only.'}, 'id': {'type': 'string', 'description': 'Automation id. Required for mode=view, mode=update, mode=delete, and mode=suggested_update. Omit for mode=create and mode=suggested_create.'}, 'kind': {'type': 'string', 'description': 'One of cron or heartbeat. Required for create, update, suggested_create, and suggested_update. Use cron for detached workspace jobs. Use heartbeat when the user wants this thread to wake up later and continue the conversation.'}, 'localEnvironmentConfigPath': {'type': ['string', 'null'], 'description': 'Optional local environment config path for worktree setup scripts. Immediate worktree create calls with a non-null value and immediate worktree update calls that preserve or set a setup config are rejected; use suggested_create/suggested_update for user review. Pass null to clear or run without setup. Cron automations only.'}, 'mode': {'type': 'string', 'description': 'One of view, create, update, delete, suggested_create, or suggested_update. Use view to show an existing automation, create/update/delete to mutate immediately, and suggested_create/suggested_update to present a proposal for the user to review.'}, 'model': {'type': 'string', 'description': 'Model to use for cron automations.'}, 'name': {'type': 'string', 'description': 'Short human-readable automation name. If the user does not provide one, choose a concise name.'}, 'prompt': {'type': 'string', 'description': 'The automation prompt. Describe only the task itself; do not include schedule, workspace, or thread details because those are provided separately. Keep it self-sufficient, include output expectations when useful, and do not ask it to write a file or announce nothing to do unless the user explicitly asked for that.'}, 'reasoningEffort': {'type': 'string', 'description': 'Reasoning effort to use for cron automations. One of none, minimal, low, medium, high, or xhigh.'}, 'rrule': {'type': 'string', 'description': \"RRULE schedule string. Interpret requested times in the user's locale. Cron automations use hourly interval or weekly schedules. Heartbeat automations attached to a thread can use minute-based intervals such as FREQ=MINUTELY;INTERVAL=30 or daily/weekly wall-clock schedules.\"}, 'status': {'type': 'string', 'description': 'One of ACTIVE or PAUSED. Default to ACTIVE unless the user asks to start paused.'}, 'targetThreadId': {'type': 'string', 'description': 'Target thread id for heartbeat automations. Prefer destination=thread for the current local thread instead of inventing or copying raw thread ids.'}}, 'additionalProperties': False}}]}}\n {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'CodeInterpreter', 'type'), 'msg': \"Input should be 'code_interpreter'\", 'input': 'namespace', 'ctx': {'expected': \"'code_interpreter'\"}}\n {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'ImageGeneration', 'type'), 'msg': \"Input should be 'image_generation'\", 'input': 'namespace', 'ctx': {'expected': \"'image_generation'\"}}\n {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'LocalShell', 'type'), 'msg': \"Input should be 'local_shell'\", 'input': 'namespace', 'ctx': {'expected': \"'local_shell'\"}}\n {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'FunctionShellTool', 'type'), 'msg': \"Input should be 'shell'\", 'input': 'namespace', 'ctx': {'expected': \"'shell'\"}}\n {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'CustomTool', 'type'), 'msg': \"Input should be 'custom'\", 'input': 'namespace', 'ctx': {'expected': \"'custom'\"}}\n {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'WebSearchPreviewTool', 'type'), 'msg': \"Input should be 'web_search_preview' or 'web_search_preview_2025_03_11'\", 'input': 'namespace', 'ctx': {'expected': \"'web_search_preview' or 'web_search_preview_2025_03_11'\"}}\n {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'ApplyPatchTool', 'type'), 'msg': \"Input should be 'apply_patch'\", 'input': 'namespace', 'ctx': {'expected': \"'apply_patch'\"}}\n\n File \"/home/user/.local/lib/python3.10/site-packages/vllm/entrypoints/utils.py\", line 48, in create_responses\n POST /v1/responses [{'type': 'literal_error', 'loc': ('body', 'tools', 11, 'FunctionTool', 'type'), 'msg': \"Input should be 'function'\", 'input': 'namespace', 'ctx': {'expected': \"'function'\"}}, {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'FileSearchTool', 'type'), 'msg': \"Input should be 'file_search'\", 'input': 'namespace', 'ctx': {'expected': \"'file_search'\"}}, {'type': 'missing', 'loc': ('body', 'tools', 11, 'FileSearchTool', 'vector_store_ids'), 'msg': 'Field required', 'input': {'type': 'namespace', 'name': 'codex_app', 'description': 'Tools in the codex_app namespace.', 'tools': [{'type': 'function', 'name': 'automation_update', 'description': 'Create, update, view, or delete recurring automations in the Codex app. Use this when the user asks for an automation, recurring run, repeated task, reminder, follow-up, monitor, or asks you to watch something, keep an eye on it, check back later, wake up later, notify them, or keep working later. Cron automations run as standalone jobs against workspaces. Heartbeat automations are proactive follow-ups attached to the current local thread. Prefer heartbeats for requests to continue this thread later, especially below one hour. Use suggested_create or suggested_update when proposing a worktree automation with a local environment setup config so the user can review it before it is saved. Never write raw automation directives by hand, show raw RRULE strings to the user, or create a workaround cron automation for a thread heartbeat unless the user explicitly asks for that. For requests about existing automations, inspect $CODEX_HOME/automations/*/automation.toml to find matching automation ids by name or prompt. Prefer updating an existing automation over creating a duplicate. For updates, preserve existing fields unless the user asks to change them, and call automation_update with the resolved id and full updated fields.', 'strict': False, 'parameters': {'type': 'object', 'properties': {'cwds': {'description': 'Cron automations only. Workspace directories for the automation; can be a JSON array or comma-separated string.', 'anyOf': [{'type': 'string'}, {'type': 'array', 'items': {'type': 'string'}}]}, 'destination': {'type': 'string', 'description': 'Optional automation destination. Use thread for heartbeat automations attached to the current local thread.'}, 'executionEnvironment': {'type': 'string', 'description': 'One of worktree or local. Cron automations only.'}, 'id': {'type': 'string', 'description': 'Automation id. Required for mode=view, mode=update, mode=delete, and mode=suggested_update. Omit for mode=create and mode=suggested_create.'}, 'kind': {'type': 'string', 'description': 'One of cron or heartbeat. Required for create, update, suggested_create, and suggested_update. Use cron for detached workspace jobs. Use heartbeat when the user wants this thread to wake up later and continue the conversation.'}, 'localEnvironmentConfigPath': {'type': ['string', 'null'], 'description': 'Optional local environment config path for worktree setup scripts. Immediate worktree create calls with a non-null value and immediate worktree update calls that preserve or set a setup config are rejected; use suggested_create/suggested_update for user review. Pass null to clear or run without setup. Cron automations only.'}, 'mode': {'type': 'string', 'description': 'One of view, create, update, delete, suggested_create, or suggested_update. Use view to show an existing automation, create/update/delete to mutate immediately, and suggested_create/suggested_update to present a proposal for the user to review.'}, 'model': {'type': 'string', 'description': 'Model to use for cron automations.'}, 'name': {'type': 'string', 'description': 'Short human-readable automation name. If the user does not provide one, choose a concise name.'}, 'prompt': {'type': 'string', 'description': 'The automation prompt. Describe only the task itself; do not include schedule, workspace, or thread details because those are provided separately. Keep it self-sufficient, include output expectations when useful, and do not ask it to write a file or announce nothing to do unless the user explicitly asked for that.'}, 'reasoningEffort': {'type': 'string', 'description': 'Reasoning effort to use for cron automations. One of none, minimal, low, medium, high, or xhigh.'}, 'rrule': {'type': 'string', 'description': \"RRULE schedule string. Interpret requested times in the user's locale. Cron automations use hourly interval or weekly schedules. Heartbeat automations attached to a thread can use minute-based intervals such as FREQ=MINUTELY;INTERVAL=30 or daily/weekly wall-clock schedules.\"}, 'status': {'type': 'string', 'description': 'One of ACTIVE or PAUSED. Default to ACTIVE unless the user asks to start paused.'}, 'targetThreadId': {'type': 'string', 'description': 'Target thread id for heartbeat automations. Prefer destination=thread for the current local thread instead of inventing or copying raw thread ids.'}}, 'additionalProperties': False}}]}}, {'type': 'missing', 'loc': ('body', 'tools', 11, 'ComputerTool', 'display_height'), 'msg': 'Field required', 'input': {'type': 'namespace', 'name': 'codex_app', 'description': 'Tools in the codex_app namespace.', 'tools': [{'type': 'function', 'name': 'automation_update', 'description': 'Create, update, view, or delete recurring automations in the Codex app. Use this when the user asks for an automation, recurring run, repeated task, reminder, follow-up, monitor, or asks you to watch something, keep an eye on it, check back later, wake up later, notify them, or keep working later. Cron automations run as standalone jobs against workspaces. Heartbeat automations are proactive follow-ups attached to the current local thread. Prefer heartbeats for requests to continue this thread later, especially below one hour. Use suggested_create or suggested_update when proposing a worktree automation with a local environment setup config so the user can review it before it is saved. Never write raw automation directives by hand, show raw RRULE strings to the user, or create a workaround cron automation for a thread heartbeat unless the user explicitly asks for that. For requests about existing automations, inspect $CODEX_HOME/automations/*/automation.toml to find matching automation ids by name or prompt. Prefer updating an existing automation over creating a duplicate. For updates, preserve existing fields unless the user asks to change them, and call automation_update with the resolved id and full updated fields.', 'strict': False, 'parameters': {'type': 'object', 'properties': {'cwds': {'description': 'Cron automations only. Workspace directories for the automation; can be a JSON array or comma-separated string.', 'anyOf': [{'type': 'string'}, {'type': 'array', 'items': {'type': 'string'}}]}, 'destination': {'type': 'string', 'description': 'Optional automation destination. Use thread for heartbeat automations attached to the current local thread.'}, 'executionEnvironment': {'type': 'string', 'description': 'One of worktree or local. Cron automations only.'}, 'id': {'type': 'string', 'description': 'Automation id. Required for mode=view, mode=update, mode=delete, and mode=suggested_update. Omit for mode=create and mode=suggested_create.'}, 'kind': {'type': 'string', 'description': 'One of cron or heartbeat. Required for create, update, suggested_create, and suggested_update. Use cron for detached workspace jobs. Use heartbeat when the user wants this thread to wake up later and continue the conversation.'}, 'localEnvironmentConfigPath': {'type': ['string', 'null'], 'description': 'Optional local environment config path for worktree setup scripts. Immediate worktree create calls with a non-null value and immediate worktree update calls that preserve or set a setup config are rejected; use suggested_create/suggested_update for user review. Pass null to clear or run without setup. Cron automations only.'}, 'mode': {'type': 'string', 'description': 'One of view, create, update, delete, suggested_create, or suggested_update. Use view to show an existing automation, create/update/delete to mutate immediately, and suggested_create/suggested_update to present a proposal for the user to review.'}, 'model': {'type': 'string', 'description': 'Model to use for cron automations.'}, 'name': {'type': 'string', 'description': 'Short human-readable automation name. If the user does not provide one, choose a concise name.'}, 'prompt': {'type': 'string', 'description': 'The automation prompt. Describe only the task itself; do not include schedule, workspace, or thread details because those are provided separately. Keep it self-sufficient, include output expectations when useful, and do not ask it to write a file or announce nothing to do unless the user explicitly asked for that.'}, 'reasoningEffort': {'type': 'string', 'description': 'Reasoning effort to use for cron automations. One of none, minimal, low, medium, high, or xhigh.'}, 'rrule': {'type': 'string', 'description': \"RRULE schedule string. Interpret requested times in the user's locale. Cron automations use hourly interval or weekly schedules. Heartbeat automations attached to a thread can use minute-based intervals such as FREQ=MINUTELY;INTERVAL=30 or daily/weekly wall-clock schedules.\"}, 'status': {'type': 'string', 'description': 'One of ACTIVE or PAUSED. Default to ACTIVE unless the user asks to start paused.'}, 'targetThreadId': {'type': 'string', 'description': 'Target thread id for heartbeat automations. Prefer destination=thread for the current local thread instead of inventing or copying raw thread ids.'}}, 'additionalProperties': False}}]}}, {'type': 'missing', 'loc': ('body', 'tools', 11, 'ComputerTool', 'display_width'), 'msg': 'Field required', 'input': {'type': 'namespace', 'name': 'codex_app', 'description': 'Tools in the codex_app namespace.', 'tools': [{'type': 'function', 'name': 'automation_update', 'description': 'Create, update, view, or delete recurring automations in the Codex app. Use this when the user asks for an automation, recurring run, repeated task, reminder, follow-up, monitor, or asks you to watch something, keep an eye on it, check back later, wake up later, notify them, or keep working later. Cron automations run as standalone jobs against workspaces. Heartbeat automations are proactive follow-ups attached to the current local thread. Prefer heartbeats for requests to continue this thread later, especially below one hour. Use suggested_create or suggested_update when proposing a worktree automation with a local environment setup config so the user can review it before it is saved. Never write raw automation directives by hand, show raw RRULE strings to the user, or create a workaround cron automation for a thread heartbeat unless the user explicitly asks for that. For requests about existing automations, inspect $CODEX_HOME/automations/*/automation.toml to find matching automation ids by name or prompt. Prefer updating an existing automation over creating a duplicate. For updates, preserve existing fields unless the user asks to change them, and call automation_update with the resolved id and full updated fields.', 'strict': False, 'parameters': {'type': 'object', 'properties': {'cwds': {'description': 'Cron automations only. Workspace directories for the automation; can be a JSON array or comma-separated string.', 'anyOf': [{'type': 'string'}, {'type': 'array', 'items': {'type': 'string'}}]}, 'destination': {'type': 'string', 'description': 'Optional automation destination. Use thread for heartbeat automations attached to the current local thread.'}, 'executionEnvironment': {'type': 'string', 'description': 'One of worktree or local. Cron automations only.'}, 'id': {'type': 'string', 'description': 'Automation id. Required for mode=view, mode=update, mode=delete, and mode=suggested_update. Omit for mode=create and mode=suggested_create.'}, 'kind': {'type': 'string', 'description': 'One of cron or heartbeat. Required for create, update, suggested_create, and suggested_update. Use cron for detached workspace jobs. Use heartbeat when the user wants this thread to wake up later and continue the conversation.'}, 'localEnvironmentConfigPath': {'type': ['string', 'null'], 'description': 'Optional local environment config path for worktree setup scripts. Immediate worktree create calls with a non-null value and immediate worktree update calls that preserve or set a setup config are rejected; use suggested_create/suggested_update for user review. Pass null to clear or run without setup. Cron automations only.'}, 'mode': {'type': 'string', 'description': 'One of view, create, update, delete, suggested_create, or suggested_update. Use view to show an existing automation, create/update/delete to mutate immediately, and suggested_create/suggested_update to present a proposal for the user to review.'}, 'model': {'type': 'string', 'description': 'Model to use for cron automations.'}, 'name': {'type': 'string', 'description': 'Short human-readable automation name. If the user does not provide one, choose a concise name.'}, 'prompt': {'type': 'string', 'description': 'The automation prompt. Describe only the task itself; do not include schedule, workspace, or thread details because those are provided separately. Keep it self-sufficient, include output expectations when useful, and do not ask it to write a file or announce nothing to do unless the user explicitly asked for that.'}, 'reasoningEffort': {'type': 'string', 'description': 'Reasoning effort to use for cron automations. One of none, minimal, low, medium, high, or xhigh.'}, 'rrule': {'type': 'string', 'description': \"RRULE schedule string. Interpret requested times in the user's locale. Cron automations use hourly interval or weekly schedules. Heartbeat automations attached to a thread can use minute-based intervals such as FREQ=MINUTELY;INTERVAL=30 or daily/weekly wall-clock schedules.\"}, 'status': {'type': 'string', 'description': 'One of ACTIVE or PAUSED. Default to ACTIVE unless the user asks to start paused.'}, 'targetThreadId': {'type': 'string', 'description': 'Target thread id for heartbeat automations. Prefer destination=thread for the current local thread instead of inventing or copying raw thread ids.'}}, 'additionalProperties': False}}]}}, {'type': 'missing', 'loc': ('body', 'tools', 11, 'ComputerTool', 'environment'), 'msg': 'Field required', 'input': {'type': 'namespace', 'name': 'codex_app', 'description': 'Tools in the codex_app namespace.', 'tools': [{'type': 'function', 'name': 'automation_update', 'description': 'Create, update, view, or delete recurring automations in the Codex app. Use this when the user asks for an automation, recurring run, repeated task, reminder, follow-up, monitor, or asks you to watch something, keep an eye on it, check back later, wake up later, notify them, or keep working later. Cron automations run as standalone jobs against workspaces. Heartbeat automations are proactive follow-ups attached to the current local thread. Prefer heartbeats for requests to continue this thread later, especially below one hour. Use suggested_create or suggested_update when proposing a worktree automation with a local environment setup config so the user can review it before it is saved. Never write raw automation directives by hand, show raw RRULE strings to the user, or create a workaround cron automation for a thread heartbeat unless the user explicitly asks for that. For requests about existing automations, inspect $CODEX_HOME/automations/*/automation.toml to find matching automation ids by name or prompt. Prefer updating an existing automation over creating a duplicate. For updates, preserve existing fields unless the user asks to change them, and call automation_update with the resolved id and full updated fields.', 'strict': False, 'parameters': {'type': 'object', 'properties': {'cwds': {'description': 'Cron automations only. Workspace directories for the automation; can be a JSON array or comma-separated string.', 'anyOf': [{'type': 'string'}, {'type': 'array', 'items': {'type': 'string'}}]}, 'destination': {'type': 'string', 'description': 'Optional automation destination. Use thread for heartbeat automations attached to the current local thread.'}, 'executionEnvironment': {'type': 'string', 'description': 'One of worktree or local. Cron automations only.'}, 'id': {'type': 'string', 'description': 'Automation id. Required for mode=view, mode=update, mode=delete, and mode=suggested_update. Omit for mode=create and mode=suggested_create.'}, 'kind': {'type': 'string', 'description': 'One of cron or heartbeat. Required for create, update, suggested_create, and suggested_update. Use cron for detached workspace jobs. Use heartbeat when the user wants this thread to wake up later and continue the conversation.'}, 'localEnvironmentConfigPath': {'type': ['string', 'null'], 'description': 'Optional local environment config path for worktree setup scripts. Immediate worktree create calls with a non-null value and immediate worktree update calls that preserve or set a setup config are rejected; use suggested_create/suggested_update for user review. Pass null to clear or run without setup. Cron automations only.'}, 'mode': {'type': 'string', 'description': 'One of view, create, update, delete, suggested_create, or suggested_update. Use view to show an existing automation, create/update/delete to mutate immediately, and suggested_create/suggested_update to present a proposal for the user to review.'}, 'model': {'type': 'string', 'description': 'Model to use for cron automations.'}, 'name': {'type': 'string', 'description': 'Short human-readable automation name. If the user does not provide one, choose a concise name.'}, 'prompt': {'type': 'string', 'description': 'The automation prompt. Describe only the task itself; do not include schedule, workspace, or thread details because those are provided separately. Keep it self-sufficient, include output expectations when useful, and do not ask it to write a file or announce nothing to do unless the user explicitly asked for that.'}, 'reasoningEffort': {'type': 'string', 'description': 'Reasoning effort to use for cron automations. One of none, minimal, low, medium, high, or xhigh.'}, 'rrule': {'type': 'string', 'description': \"RRULE schedule string. Interpret requested times in the user's locale. Cron automations use hourly interval or weekly schedules. Heartbeat automations attached to a thread can use minute-based intervals such as FREQ=MINUTELY;INTERVAL=30 or daily/weekly wall-clock schedules.\"}, 'status': {'type': 'string', 'description': 'One of ACTIVE or PAUSED. Default to ACTIVE unless the user asks to start paused.'}, 'targetThreadId': {'type': 'string', 'description': 'Target thread id for heartbeat automations. Prefer destination=thread for the current local thread instead of inventing or copying raw thread ids.'}}, 'additionalProperties': False}}]}}, {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'ComputerTool', 'type'), 'msg': \"Input should be 'computer_use_preview'\", 'input': 'namespace', 'ctx': {'expected': \"'computer_use_preview'\"}}, {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'WebSearchTool', 'type'), 'msg': \"Input should be 'web_search' or 'web_search_2025_08_26'\", 'input': 'namespace', 'ctx': {'expected': \"'web_search' or 'web_search_2025_08_26'\"}}, {'type': 'missing', 'loc': ('body', 'tools', 11, 'Mcp', 'server_label'), 'msg': 'Field required', 'input': {'type': 'namespace', 'name': 'codex_app', 'description': 'Tools in the codex_app namespace.', 'tools': [{'type': 'function', 'name': 'automation_update', 'description': 'Create, update, view, or delete recurring automations in the Codex app. Use this when the user asks for an automation, recurring run, repeated task, reminder, follow-up, monitor, or asks you to watch something, keep an eye on it, check back later, wake up later, notify them, or keep working later. Cron automations run as standalone jobs against workspaces. Heartbeat automations are proactive follow-ups attached to the current local thread. Prefer heartbeats for requests to continue this thread later, especially below one hour. Use suggested_create or suggested_update when proposing a worktree automation with a local environment setup config so the user can review it before it is saved. Never write raw automation directives by hand, show raw RRULE strings to the user, or create a workaround cron automation for a thread heartbeat unless the user explicitly asks for that. For requests about existing automations, inspect $CODEX_HOME/automations/*/automation.toml to find matching automation ids by name or prompt. Prefer updating an existing automation over creating a duplicate. For updates, preserve existing fields unless the user asks to change them, and call automation_update with the resolved id and full updated fields.', 'strict': False, 'parameters': {'type': 'object', 'properties': {'cwds': {'description': 'Cron automations only. Workspace directories for the automation; can be a JSON array or comma-separated string.', 'anyOf': [{'type': 'string'}, {'type': 'array', 'items': {'type': 'string'}}]}, 'destination': {'type': 'string', 'description': 'Optional automation destination. Use thread for heartbeat automations attached to the current local thread.'}, 'executionEnvironment': {'type': 'string', 'description': 'One of worktree or local. Cron automations only.'}, 'id': {'type': 'string', 'description': 'Automation id. Required for mode=view, mode=update, mode=delete, and mode=suggested_update. Omit for mode=create and mode=suggested_create.'}, 'kind': {'type': 'string', 'description': 'One of cron or heartbeat. Required for create, update, suggested_create, and suggested_update. Use cron for detached workspace jobs. Use heartbeat when the user wants this thread to wake up later and continue the conversation.'}, 'localEnvironmentConfigPath': {'type': ['string', 'null'], 'description': 'Optional local environment config path for worktree setup scripts. Immediate worktree create calls with a non-null value and immediate worktree update calls that preserve or set a setup config are rejected; use suggested_create/suggested_update for user review. Pass null to clear or run without setup. Cron automations only.'}, 'mode': {'type': 'string', 'description': 'One of view, create, update, delete, suggested_create, or suggested_update. Use view to show an existing automation, create/update/delete to mutate immediately, and suggested_create/suggested_update to present a proposal for the user to review.'}, 'model': {'type': 'string', 'description': 'Model to use for cron automations.'}, 'name': {'type': 'string', 'description': 'Short human-readable automation name. If the user does not provide one, choose a concise name.'}, 'prompt': {'type': 'string', 'description': 'The automation prompt. Describe only the task itself; do not include schedule, workspace, or thread details because those are provided separately. Keep it self-sufficient, include output expectations when useful, and do not ask it to write a file or announce nothing to do unless the user explicitly asked for that.'}, 'reasoningEffort': {'type': 'string', 'description': 'Reasoning effort to use for cron automations. One of none, minimal, low, medium, high, or xhigh.'}, 'rrule': {'type': 'string', 'description': \"RRULE schedule string. Interpret requested times in the user's locale. Cron automations use hourly interval or weekly schedules. Heartbeat automations attached to a thread can use minute-based intervals such as FREQ=MINUTELY;INTERVAL=30 or daily/weekly wall-clock schedules.\"}, 'status': {'type': 'string', 'description': 'One of ACTIVE or PAUSED. Default to ACTIVE unless the user asks to start paused.'}, 'targetThreadId': {'type': 'string', 'description': 'Target thread id for heartbeat automations. Prefer destination=thread for the current local thread instead of inventing or copying raw thread ids.'}}, 'additionalProperties': False}}]}}, {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'Mcp', 'type'), 'msg': \"Input should be 'mcp'\", 'input': 'namespace', 'ctx': {'expected': \"'mcp'\"}}, {'type': 'missing', 'loc': ('body', 'tools', 11, 'CodeInterpreter', 'container'), 'msg': 'Field required', 'input': {'type': 'namespace', 'name': 'codex_app', 'description': 'Tools in the codex_app namespace.', 'tools': [{'type': 'function', 'name': 'automation_update', 'description': 'Create, update, view, or delete recurring automations in the Codex app. Use this when the user asks for an automation, recurring run, repeated task, reminder, follow-up, monitor, or asks you to watch something, keep an eye on it, check back later, wake up later, notify them, or keep working later. Cron automations run as standalone jobs against workspaces. Heartbeat automations are proactive follow-ups attached to the current local thread. Prefer heartbeats for requests to continue this thread later, especially below one hour. Use suggested_create or suggested_update when proposing a worktree automation with a local environment setup config so the user can review it before it is saved. Never write raw automation directives by hand, show raw RRULE strings to the user, or create a workaround cron automation for a thread heartbeat unless the user explicitly asks for that. For requests about existing automations, inspect $CODEX_HOME/automations/*/automation.toml to find matching automation ids by name or prompt. Prefer updating an existing automation over creating a duplicate. For updates, preserve existing fields unless the user asks to change them, and call automation_update with the resolved id and full updated fields.', 'strict': False, 'parameters': {'type': 'object', 'properties': {'cwds': {'description': 'Cron automations only. Workspace directories for the automation; can be a JSON array or comma-separated string.', 'anyOf': [{'type': 'string'}, {'type': 'array', 'items': {'type': 'string'}}]}, 'destination': {'type': 'string', 'description': 'Optional automation destination. Use thread for heartbeat automations attached to the current local thread.'}, 'executionEnvironment': {'type': 'string', 'description': 'One of worktree or local. Cron automations only.'}, 'id': {'type': 'string', 'description': 'Automation id. Required for mode=view, mode=update, mode=delete, and mode=suggested_update. Omit for mode=create and mode=suggested_create.'}, 'kind': {'type': 'string', 'description': 'One of cron or heartbeat. Required for create, update, suggested_create, and suggested_update. Use cron for detached workspace jobs. Use heartbeat when the user wants this thread to wake up later and continue the conversation.'}, 'localEnvironmentConfigPath': {'type': ['string', 'null'], 'description': 'Optional local environment config path for worktree setup scripts. Immediate worktree create calls with a non-null value and immediate worktree update calls that preserve or set a setup config are rejected; use suggested_create/suggested_update for user review. Pass null to clear or run without setup. Cron automations only.'}, 'mode': {'type': 'string', 'description': 'One of view, create, update, delete, suggested_create, or suggested_update. Use view to show an existing automation, create/update/delete to mutate immediately, and suggested_create/suggested_update to present a proposal for the user to review.'}, 'model': {'type': 'string', 'description': 'Model to use for cron automations.'}, 'name': {'type': 'string', 'description': 'Short human-readable automation name. If the user does not provide one, choose a concise name.'}, 'prompt': {'type': 'string', 'description': 'The automation prompt. Describe only the task itself; do not include schedule, workspace, or thread details because those are provided separately. Keep it self-sufficient, include output expectations when useful, and do not ask it to write a file or announce nothing to do unless the user explicitly asked for that.'}, 'reasoningEffort': {'type': 'string', 'description': 'Reasoning effort to use for cron automations. One of none, minimal, low, medium, high, or xhigh.'}, 'rrule': {'type': 'string', 'description': \"RRULE schedule string. Interpret requested times in the user's locale. Cron automations use hourly interval or weekly schedules. Heartbeat automations attached to a thread can use minute-based intervals such as FREQ=MINUTELY;INTERVAL=30 or daily/weekly wall-clock schedules.\"}, 'status': {'type': 'string', 'description': 'One of ACTIVE or PAUSED. Default to ACTIVE unless the user asks to start paused.'}, 'targetThreadId': {'type': 'string', 'description': 'Target thread id for heartbeat automations. Prefer destination=thread for the current local thread instead of inventing or copying raw thread ids.'}}, 'additionalProperties': False}}]}}, {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'CodeInterpreter', 'type'), 'msg': \"Input should be 'code_interpreter'\", 'input': 'namespace', 'ctx': {'expected': \"'code_interpreter'\"}}, {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'ImageGeneration', 'type'), 'msg': \"Input should be 'image_generation'\", 'input': 'namespace', 'ctx': {'expected': \"'image_generation'\"}}, {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'LocalShell', 'type'), 'msg': \"Input should be 'local_shell'\", 'input': 'namespace', 'ctx': {'expected': \"'local_shell'\"}}, {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'FunctionShellTool', 'type'), 'msg': \"Input should be 'shell'\", 'input': 'namespace', 'ctx': {'expected': \"'shell'\"}}, {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'CustomTool', 'type'), 'msg': \"Input should be 'custom'\", 'input': 'namespace', 'ctx': {'expected': \"'custom'\"}}, {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'WebSearchPreviewTool', 'type'), 'msg': \"Input should be 'web_search_preview' or 'web_search_preview_2025_03_11'\", 'input': 'namespace', 'ctx': {'expected': \"'web_search_preview' or 'web_search_preview_2025_03_11'\"}}, {'type': 'literal_error', 'loc': ('body', 'tools', 11, 'ApplyPatchTool', 'type'), 'msg': \"Input should be 'apply_patch'\", 'input': 'namespace', 'ctx': {'expected': \"'apply_patch'\"}}]","type":"Bad Request","param":null,"code":400}}
```

Could you please advise on how to resolve this issue?

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by Liuzin521** [comment]
Hi, I tried to reproduce this on current vLLM main with a minimal `/v1/responses` request containing a namespace-style tool.

Environment:

- vLLM version: `0.21.1rc1.dev3+g95cfe102a`
- Model: local `Qwen3-0.6B`
- Endpoint: `/v1/responses`
- Served model name: `test-model`

I tested two payloads:

1. A minimal `type: "namespace"` tool containing one nested function tool.
2. A namespace tool containing a nested function tool with `strict: false` and `additionalProperties: false`, closer to the schema shown in the original error.

Both requests completed successfully. The response also preserved the namespace-style tool in the returned `tools` field, e.g.

```json
{
  "type": "namespace",
  "name": "codex_app",
  "tools": [
    {
      "type": "function",
      "name": "automation_update",
      "strict": false
    }
  ]
}

**Comment by lazyn1997** [comment]
I don't have the qwen3 model, so I'm unable to reproduce it. Could you please use the qwen3.6 for testing? Or can you determine the cause of the problem from my startup configuration?
Additionally, I connected this model in trae and it works normally.

**Comment by Liuzin521** [comment]
Thanks. Since the same model works in Trae, the model checkpoint itself is probably fine. Trae and Codex may be using different API paths or request formats.

I tested again with Qwen3.6-27B-FP8 on current vLLM main:

- vLLM version: `0.21.1rc1.dev3+g95cfe102a`
- Endpoint: `/v1/responses`
- Served model name: `qwen3.6-27b-fp8`
- TP size: 2
- KV cache dtype: fp8
- Tool parser: `qwen3_coder`
- `--enable-auto-tool-choice`
- `--chat-template-content-format openai`

A namespace-style tool payload with a nested function tool completed successfully, and the response preserved `type: "namespace"` in the returned `tools` field.

So I still could not reproduce the `Input should be 'function'` / `input: 'namespace'` validation error on current main.

Could you share the exact vLLM version you are using?
You can use
 ```bash

python -c "import vllm; print(vllm.__version__); print(vllm.__file__)"

**Comment by lazyn1997** [comment]
```
python -c "import vllm; print(vllm.__version__); print(vllm.__file__)"
0.21.0
/home/user/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/__init__.py
```
My version is 0.21.0, and my config.toml is:
```model = "qwen3.6-27b-fp8"
model_provider = "vllm"
model_reasoning_effort = "high"

[model_providers.vllm]
name = "qwen3.6-27b-fp8"
base_url = "http://192.168.1.58:8001/v1"
wire_api = "responses"

[windows]
sandbox = "elevated"

```
Is there anything wrong？

**Comment by lazyn1997** [comment]
Issues #41828 and #42407 have mentioned this problem, but this change has not yet been incorporated into the official version?

**Comment by Liuzin521** [comment]
I was able to reproduce this issue.

It looks like the error depends on the installed `openai` Python package version, not only on the vLLM version.

After upgrading the openai Python package to a version that includes openai.types.responses.namespace_tool.NamespaceTool, the same payload succeeds.

So a possible fixis to upgrade the openai dependency.  You can try `pip install -U openai`

**Comment by lazyn1997** [comment]
my openai version is the latest.
```
(vllm_server) (base) user@user-System-Product-Name:~/vllm_server$ pip install -U openai
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: openai in ./.venv/lib/python3.12/site-packages (2.37.0)
Requirement already satisfied: anyio<5,>=3.5.0 in ./.venv/lib/python3.12/site-packages (from openai) (4.13.0)
Requirement already satisfied: distro<2,>=1.7.0 in ./.venv/lib/python3.12/site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in ./.venv/lib/python3.12/site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in ./.venv/lib/python3.12/site-packages (from openai) (0.14.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in ./.venv/lib/python3.12/site-packages (from openai) (2.13.4)
Requirement already satisfied: sniffio in ./.venv/lib/python3.12/site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in ./.venv/lib/python3.12/site-packages (from openai) (4.67.3)
Requirement already satisfied: typing-extensions<5,>=4.11 in ./.venv/lib/python3.12/site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in ./.venv/lib/python3.12/site-packages (from anyio<5,>=3.5.0->openai) (3.15)
Requirement already satisfied: certifi in ./.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->openai) (2026.4.22)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.12/site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.12/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in ./.venv/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->openai) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in ./.venv/lib/python3.12/site-packages (from pydantic<3,>=1.9.0->openai) (0.4.2)
```

**Comment by Liuzin521** [comment]
One thing still looks worth checking: the environment used by `pip install -U openai` may not be the same environment used to start the vLLM server.

Your `pip install -U openai` command was run under:

```bash
(vllm_server) (base) ~/vllm_server$
```
But the startup script in the issue activates another conda environment before launching vLLM:
```bash
source ~/miniconda3/etc/profile.d/conda.sh
conda activate vllm
```
So the vLLM server is likely running inside the vllm conda environment, not the vllm_server environment where openai==2.37.0 was installed.

**Comment by lazyn1997** [comment]
I currently only have one vllm environment. I created the environment using uv according to the official tutorial, and deleted the conda environment. The current startup script is as follows:
```
#!/bin/bash
set -e

MODEL_PATH="/data3/llm_models/Qwen3.6-27B-FP8"
MODEL_NAME=$(basename "$MODEL_PATH" | tr '[:upper:]' '[:lower:]')

VENV_PATH="/home/user/vllm_server/.venv"

export CUDA_VISIBLE_DEVICES=0,1
export NCCL_P2P_DISABLE=0
export NCCL_IB_DISABLE=1
export NCCL_SHM_DISABLE=0
export NCCL_DEBUG=WARN
export CUDA_DEVICE_MAX_CONNECTIONS=1

source "${VENV_PATH}/bin/activate"

exec python -m vllm.entrypoints.openai.api_server \
  --model  "$MODEL_PATH" \
  --tensor-parallel-size 2 \
  --kv-cache-dtype fp8 \
  --max-model-len 262144 \
  --max-num-seqs 8 \
  --gpu-memory-utilization 0.92 \
  --disable-custom-all-reduce \
  --trust-remote-code \
  --reasoning-parser qwen3 \
  --enable-auto-tool-choice \
  --tool-call-parser qwen3_coder \
  --chat-template-content-format openai \
  --enable-chunked-prefill \
  --host 0.0.0.0 \
  --port 8001 \
  --served-model-name "$MODEL_NAME"
```

**Comment by Liuzin521** [comment]
I cannot reproduce this with a minimal `/v1/responses` namespace-tool payload on vLLM `0.21.0` + OpenAI `2.37.0`.

Unless there is a minimal failing curl request that reproduces the validation error directly against vLLM, I do not think I can investigate this further. The remaining difference may be the full Codex request payload or local environment details.

**Comment by lazyn1997** [comment]
My codex version is the lasted, too. And I reinstalled the Codex, but the problem still persists.
```
(base) PS E:\Documents> codex --version
codex-cli 0.131.0
```
