### ISSUE TITLE
[Bug]: name 'ncclGetVersion' is not defined

### ISSUE THREAD

**Issue by DefTruth** [vllm-project/vllm#4257]
### Your current environment

```text
Collecting environment information...
PyTorch version: 2.2.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.2
Libc version: glibc-2.35

Python version: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-240.el8.x86_64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.3.107
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA L20
GPU 1: NVIDIA L20
GPU 2: NVIDIA L20
GPU 3: NVIDIA L20
GPU 4: NVIDIA L20
GPU 5: NVIDIA L20
GPU 6: NVIDIA L20
GPU 7: NVIDIA L20

Nvidia driver version: 550.54.15
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_engines_precompiled.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_graph.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_heuristic.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops.so.9.0.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          128
On-line CPU(s) list:             0-127
Vendor ID:                       GenuineIntel
BIOS Vendor ID:                  Intel(R) Corporation
Model name:                      Intel(R) Xeon(R) Gold 6430
BIOS Model name:                 Intel(R) Xeon(R) Gold 6430
CPU family:                      6
Model:                           143
Thread(s) per core:              2
Core(s) per socket:              32
Socket(s):                       2
Stepping:                        8
Frequency boost:                 enabled
CPU max MHz:                     2101.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4200.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid cldemote movdiri movdir64b md_clear pconfig flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       3 MiB (64 instances)
L1i cache:                       2 MiB (64 instances)
L2 cache:                        128 MiB (64 instances)
L3 cache:                        120 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-31,64-95
NUMA node1 CPU(s):               32-63,96-127
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Vulnerable: __user pointer sanitization and usercopy barriers only; no swapgs barriers
Vulnerability Spectre v2:        Vulnerable, IBPB: disabled, STIBP: disabled
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.19.3
[pip3] torch==2.2.1
[pip3] triton==2.2.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-nccl-cu12          2.19.3                   pypi_0    pypi
[conda] torch                     2.2.1                    pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypiROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.4.1
vLLM Build Flags:
CUDA Archs: 5.2 6.0 6.1 7.0 7.2 7.5 8.0 8.6 8.7 9.0+PTX; ROCm: Disabled; Neuron: Disabled
GPU Topology:
[4mGPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	CPU Affinity	NUMA Affinity	GPU NUMA ID[0m
GPU0	 X 	PIX	PIX	PIX	SYS	SYS	SYS	SYS	0-31,64-95	0		N/A
GPU1	PIX	 X 	PIX	PIX	SYS	SYS	SYS	SYS	0-31,64-95	0		N/A
GPU2	PIX	PIX	 X 	PIX	SYS	SYS	SYS	SYS	0-31,64-95	0		N/A
GPU3	PIX	PIX	PIX	 X 	SYS	SYS	SYS	SYS	0-31,64-95	0		N/A
GPU4	SYS	SYS	SYS	SYS	 X 	PIX	PIX	PIX	32-63,96-127	1		N/A
GPU5	SYS	SYS	SYS	SYS	PIX	 X 	PIX	PIX	32-63,96-127	1		N/A
GPU6	SYS	SYS	SYS	SYS	PIX	PIX	 X 	PIX	32-63,96-127	1		N/A
GPU7	SYS	SYS	SYS	SYS	PIX	PIX	PIX	 X 	32-63,96-127	1		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### 🐛 Describe the bug

```bash
INFO 04-22 15:53:32 utils.py:580] Found nccl from library libnccl.so.2
ldd: ./libnccl.so.2: No such file or directory
ERROR 04-22 15:53:32 pynccl.py:44] Failed to load NCCL library from libnccl.so.2 .It is expected if you are not running on NVIDIA/AMD GPUs.Otherwise, the nccl library might not exist, be corrupted or it does not support the current platform Linux-4.18.0-240.el8.x86_64-x86_64-with-glibc2.35.One solution is to download libnccl2 version 2.18 from https://developer.download.nvidia.com/compute/cuda/repos/ and extract the libnccl.so.2 file. If you already have the library, please set the environment variable VLLM_NCCL_SO_PATH to point to the correct nccl library path.
INFO 04-22 15:53:32 pynccl_utils.py:17] Failed to import NCCL library: Failed to load NCCL library from libnccl.so.2 .
ERROR 04-22 15:53:33 worker_base.py:153] Error executing method init_device. This might cause deadlock in distributed execution.
ERROR 04-22 15:53:33 worker_base.py:153] Traceback (most recent call last):
ERROR 04-22 15:53:33 worker_base.py:153]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 145, in execute_method
ERROR 04-22 15:53:33 worker_base.py:153]     return executor(*args, **kwargs)
ERROR 04-22 15:53:33 worker_base.py:153]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker.py", line 110, in init_device
ERROR 04-22 15:53:33 worker_base.py:153]     init_worker_distributed_environment(self.parallel_config, self.rank,
ERROR 04-22 15:53:33 worker_base.py:153]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker.py", line 301, in init_worker_distributed_environment
ERROR 04-22 15:53:33 worker_base.py:153]     pynccl_utils.init_process_group(
ERROR 04-22 15:53:33 worker_base.py:153]   File "/root/anaconda3/envs/vllm/lib/python3.10/site-packages/vllm/distributed/device_communicators/pynccl_utils.py", line 45, in init_process_group
ERROR 04-22 15:53:33 worker_base.py:153]     logger.info(f"vLLM is using nccl=={ncclGetVersion()}")
ERROR 04-22 15:53:33 worker_base.py:153] NameError: name 'ncclGetVersion' is not defined
Traceback (most recent call last):
  File "/workspace/dev/vipdev/triton/benchmarks/vllm/benchmark_prefix_caching.py", line 268, in <module>
    main(args)
```
Already found Found nccl from library libnccl.so.2(the one in official NGC image) but ldd ./libnccl.so.2 failed.
```bash
INFO 04-22 15:53:32 utils.py:580] Found nccl from library libnccl.so.2
ldd: ./libnccl.so.2: No such file or directory
```

**Comment by DefTruth** [comment]
@robertgshaw2-neuralmagic

**Comment by TNT3530** [comment]
This issue also happens on ROCm with the latest 0.4.1 docker built from source. 
I was able to work around it by setting `VLLM_NCCL_SO_PATH=/opt/rocm/lib/librccl.so.1` as recommended in https://github.com/vllm-project/vllm/issues/4224, so I assume the same can be done for the CUDA equivalent library.

**Comment by DefTruth** [comment]
> This issue also happens on ROCm with the latest 0.4.1 docker built from source. I was able to work around it by setting `VLLM_NCCL_SO_PATH=/opt/rocm/lib/librccl.so.1` as recommended in #4224, so I assume the same can be done for the CUDA equivalent library.

I have submit a PR to fix it https://github.com/vllm-project/vllm/pull/4259, it works for me.

**Comment by youkaichao** [comment]
> [pip3] nvidia-nccl-cu12==2.19.3

@DefTruth I would say your environment is broken. If you follow https://docs.vllm.ai/en/latest/getting_started/installation.html , you should have `vllm-nccl-cu12` installed. Then it should work well.

> This issue also happens on ROCm with the latest 0.4.1 docker built from source.

For ROCm, this is indeed an issue, I need to further check with amd.

**Comment by youkaichao** [comment]
@TNT3530 you can have a try with https://github.com/vllm-project/vllm/pull/4271 .

**Comment by TNT3530** [comment]
@youkaichao Can confirm this PR fixes the issue, thanks!

**Comment by DefTruth** [comment]
> > https://docs.vllm.ai/en/latest/getting_started/installation.html
> 
> @youkaichao many thanks for you reply, I will try vLLM with the latest commit.

work for me.

**Comment by v-yunbin** [comment]
install  vllm==0.4.1，i still get same error:
```
(RayWorkerWrapper pid=5957) INFO 04-23 15:46:38 utils.py:608] Found nccl from library /usr/local/cuda-10.0/lib64/libnccl.so.2 [repeated 2x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(RayWorkerWrapper pid=5957) ldd: /usr/local/cuda-10.0/lib64/libnccl.so.2: 没有那个文件或目录 [repeated 2x across cluster]
(RayWorkerWrapper pid=5957) ERROR 04-23 15:46:38 pynccl.py:44] Failed to load NCCL library from /usr/local/cuda-10.0/lib64/libnccl.so.2 .It is expected if you are not running on NVIDIA/AMD GPUs.Otherwise, the nccl library might not exist, be corrupted or it does not support the current platform Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.23.One solution is to download libnccl2 version 2.18 from https://developer.download.nvidia.com/compute/cuda/repos/ and extract the libnccl.so.2 file. It is expected if you are not running on NVIDIA/AMD GPUs.Otherwise, the nccl library might not exist, be corrupted or it does not support the current platform Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.23.One solution is to download libnccl2 version 2.18 from https://developer.download.nvidia.com/compute/cuda/repos/ and extract the libnccl.so.2 file. If you already have the library, please set the environment variable VLLM_NCCL_SO_PATH to point to the correct nccl library path.(RayWorkerWrapper pid=5957) INFO 04-23 15:46:38 pynccl_utils.py:17] Failed to import NCCL library: Failed to load NCCL library from /usr/local/cuda-10.0/lib64/libnccl.so.2 . [repeated 2x across cluster]
```

**Comment by youkaichao** [comment]
> Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.23

It's crazy that you are using linux kernel 3.10 . That's deprecated for ten years. We cannot answer any question w.r.t. this. It is too old for us to support. Please upgrade your OS.

**Comment by v-yunbin** [comment]
it‘s strange that it  find "libnccl.so.2" in "/usr/local/cuda-10.0" but not "/usr/local/cuda"

**Comment by youkaichao** [comment]
> it‘s strange that it find "libnccl.so.2" in "/usr/local/cuda-10.0" but not "/usr/local/cuda"

You can always use `VLLM_NCCL_SO_PATH` to point to the path you want.

**Comment by plutogeek** [comment]
I meet this question too, and solved it . My linux environment is centos7 & gcc4.8.5
I download and upload the nccl install package from the official website https://developer.nvidia.com/nccl/nccl-legacy-downloads.


after then 
```
rpm -ivh nccl-local-repo-rhel7-2.16.2-cuda11.8-1.0-1.x86_64.rpm
```
after then in /var/rpm -ivh nccl-local-repo-rhel7-2.16.2-cuda11.8/  and execute the command

```
 rpm -ivh libnccl-static-*.rpm
```
