### ISSUE TITLE
[Bug] custom_all_reduce IPC handle fails with expandable_segments when DP>1 AND TP>1

### ISSUE THREAD

**Issue by jing-4369** [vllm-project/vllm#42609]
## Summary

With `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True`, starting vllm with
both DP>1 and TP>1 crashes during worker init in `custom_all_reduce.cuh:455`
(`cudaIpcGetMemHandle` returns `invalid argument`). Either dim alone works.

## Environment

- vllm 0.20.2
- 4× H200 (1 node)

## Repro

```bash
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
vllm serve Qwen/Qwen3-0.6B --data-parallel-size 2 --tensor-parallel-size 2
```

```
Failed: Cuda error custom_all_reduce.cuh:455 'invalid argument'
EngineCore failed to start: Worker proc VllmWorker-* died unexpectedly
```

## Matrix (Qwen3-0.6B, expandable_segments enabled)

| DP | TP | result |
|----|----|--------|
| 2  | 1  | ✓ |
| 1  | 2  | ✓ |
| 2  | 2  | ✗ (crash as above) |

Independent of `--enable-sleep-mode` (reproduced with and without it).

## Root cause (best guess)

`expandable_segments` reserves virtual address ranges via `cuMemAddressReserve`
and commits physical memory lazily with `cuMemMap`. The base pointer returned
by `cuPointerGetAttribute(..., rangeStartAddrAttr, ...)` in
`get_graph_buffer_ipc_meta` is the head of such a VA range, which is not a
valid source for `cudaIpcGetMemHandle` — IPC handles require memory backed by
a single `cudaMalloc`/`cuMemCreate` allocation. DP=1 or TP=1 doesn't trigger
the path because cross-process IPC isn't needed.

## Workaround

Drop `expandable_segments` or pass `--disable-custom-all-reduce`.

## Suggested fix

PR #40812 already temporarily disables `expandable_segments` around the cumem
sleep-mode pool. The `custom_all_reduce` IPC graph buffer registration needs
the same treatment — either temporarily switch off expandable segments while
the graph buffers are being allocated/registered, or detect the cumem-backed
pointer and skip custom-all-reduce IPC fallback.

@youkaichao could you take a look?

**Comment by mgabor3141** [comment]
[AGENT] Independent repro on different hardware, with a minimal model-free reproducer and two findings that may help.

**Broader trigger than the matrix suggests.** You list `DP=1, TP=2` as passing, but we crash at the same `custom_all_reduce.cuh:455` with **plain TP=2, DP=1** on 2x RTX 3090 (SM 8.6) over NVLink. Tensor parallelism alone exercises the IPC graph-buffer path; DP>1 is not required. (vLLM `0.20.2rc1.dev371+gbf610c2f5`, NCCL 2.28.9.)

**Minimal reproducer** (2 GPUs, no model, no `vllm serve`), isolating `capture()` -> `register_graph_buffers()`:

```python
# torchrun --nproc_per_node=2 car_min.py
import os, torch, torch.distributed as dist
from vllm.distributed.device_communicators.custom_all_reduce import CustomAllreduce

R = int(os.environ["RANK"]); L = int(os.environ["LOCAL_RANK"])
torch.cuda.set_device(L)
dist.init_process_group("gloo")
car = CustomAllreduce(group=dist.group.WORLD, device=L)
assert not car.disabled, f"rank{R}: CAR disabled, cannot reproduce"

inp = torch.ones(4096, dtype=torch.float16, device=f"cuda:{L}")
g = torch.cuda.CUDAGraph()
with car.capture():                 # register_graph_buffers() runs on __exit__
    with torch.cuda.graph(g):
        out = car.custom_all_reduce(inp)
g.replay(); torch.cuda.synchronize()
print(f"rank{R}: OK out[0]={out[0].item()}", flush=True)
dist.destroy_process_group()
```

Crashes at line 455 with `expandable_segments:True`, prints `OK` with it off. Confirms your VA-range analysis.

**Misleading symptom.** Inside `vllm serve` this does not present as a CUDA error: the worker dies during capture and the user sees EngineCore crash-looping on `RuntimeError: cancelled` (`shm_broadcast.py`, `acquire_read`). The `cuh:455 'invalid argument'` line is easy to miss above it, so it is worth indexing for anyone searching the `cancelled` symptom.

Happy to turn this into a test or draft the graceful-disable guard if useful.

**Comment by steamEngineer** [comment]
Another data point: we hit the identical `custom_all_reduce.cuh:455 'invalid argument'` crash at **TP=2, DP=1** (no data parallelism) — so the `DP=1 / TP=2 -> ✓` cell in the matrix isn't universal.

**Environment**
- 2x RTX 3090 (Ampere, sm_86), NVLink (NV4), PCIe
- vLLM v0.22.0 (`vllm/vllm-openai:v0.22.0`)
- Qwen3.6-27B AutoRound-INT4, `--tensor-parallel-size 2 --pipeline-parallel-size 1` (DP=1), MTP n=3 speculative, `--kv-cache-dtype fp8_e5m2`, CUDA graphs on (`enforce_eager=false`, `cudagraph_mode=FULL_AND_PIECEWISE`), custom all-reduce ON, `NCCL_P2P_LEVEL=NVL`.

**Crash**
```
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True,max_split_size_mb:512   # custom all-reduce ON
...
Failed: Cuda error /workspace/csrc/custom_all_reduce.cuh:455 'invalid argument'
Worker proc VllmWorker-1 died unexpectedly, shutting down executor.
```
It fires after weight load + torch.compile, during graph-buffer registration — consistent with your `get_graph_buffer_ipc_meta` / cuMemMap-VA root-cause analysis.

**What flips it (same rig, all else equal)**
- Strip `expandable_segments` (keep custom all-reduce **ON**) -> `PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:512` -> boots clean, registers cuda graph addresses, serves normally.
- `--disable-custom-all-reduce` also avoids it (as you noted).

So at least on Ampere + NVLink, the trigger is **custom-AR IPC × expandable_segments** and **TP>1 alone is sufficient — DP>1 is not required**. The `DP=1/TP=2 ✓` result may be hardware/model/version-specific (yours: H200 + Qwen3-0.6B + 0.20.2; ours: 3090 + 27B + 0.22.0). Looks like the same class as #42583 (Qwen3.5 + LoRA, TP=4) and #45604 (MiniMax, TP=4), which are also TP-only.

**Re the suggested fix:** #40812 is already merged (v0.20.1, so it's in the v0.22.0 we tested) but it only auto-disables `expandable_segments` around the **cumem sleep-mode memory pool** (`CuMemAllocator.use_memory_pool`) — it does **not** cover the `custom_all_reduce` graph-buffer registration path, which is why v0.22.0 still crashes here. The open PR that targets this exact path is #43923. Until that lands in a release we pin, we ship a launch-time guard that strips `expandable_segments` only on the custom-AR path: noonghunna/club-3090#449.

**Comment by Suppressor72** [comment]
Proposed fix (expandable_segments toggle during capture + pre-capture VMM fallback + tests):

https://github.com/vllm-project/vllm/pull/51903

**Comment by Suppressor72** [comment]
Update: I have closed #51903 after re-reviewing its overlap with #43923. The
crash and our TP=2 reproduction remain valid, but #43923 is the smaller existing
fix and has independent normal-serving validation.

The unique pre-capture fallback in #51903 was demonstrated only in a
constructed direct custom-all-reduce test, not as a residual normal-serving
failure after applying #43923. For the upstream fix, please follow #43923. I
have offered its author focused regression-test and dual-RTX-5090 validation
help rather than maintaining a competing implementation.

**Comment by trakshan-mishra** [comment]
Picking this up — opened #56193, which takes the conservative half of your suggested fix.

Two more duplicates for the pile, both with `expandable_segments:True` set and both fixed by removing it: #49101 (4xH100, DSpark spec decode) and #56180 (2xRTX 5090, Qwen3.5 + MTP). Same failure, different line number in the older releases.

Your root-cause read matches what I found. The `cudaIpcGetMemHandle` call in `get_graph_buffer_ipc_meta` sits behind the `CUDACHECK` macro, which is a `printf` plus `exit(EXIT_FAILURE)` — that's why the worker dies with no Python traceback, which is most of what makes this so hard to diagnose from the logs.

The PR does two things:

1. Disables custom allreduce in `CustomAllreduce.__init__` when expandable segments are on, so we fall back to NCCL with an explanatory warning instead of aborting. This mirrors how `__init__` already handles unsupported world sizes / missing P2P, and follows `VllmConfig._verify_kv_transfer_compat`, which already rejects this same env var for KV connectors.
2. Makes the `cudaIpcGetMemHandle` call site throw instead of `exit(1)`, so any other trigger for this failure at least surfaces with a traceback and an actionable message.

I did not exempt the cumem allocator, on the strength of your note that this reproduces both with and without `--enable-sleep-mode` — it only disables expandable segments around its own pool, which does not cover graph capture.

What the PR deliberately does *not* do is your first suggestion: toggling expandable segments off around graph buffer allocation so custom allreduce keeps working. That's clearly the better outcome performance-wise, and I'm happy to attempt it instead if that's the preferred direction.

Caveat worth stating plainly: **I don't have a multi-GPU machine.** The Python-side behaviour has CPU unit tests, but the end-to-end path is unverified. @mgabor3141, your model-free reproducer hits exactly this code — if you get a chance to run it against the PR branch, it should now log the warning and complete rather than abort.
