### ISSUE TITLE
[Bug]: Distributed Inference Infiniband mlx5 NCCL GPU RDMA on vLLM fails /lib/x86_64-linux-gnu/libmlx5.so: undefined symbol: mlx5dv_get_data_direct_sysfs_path

### ISSUE THREAD

**Issue by inheaden-admin** [vllm-project/vllm#42750]
### Your current environment

The output of <code>python collect_env.py</code></summary>
Plain Container Image: vllm/vllm-openai:v0.20.2
```text
Collecting environment information...
==============================
        System Info
==============================
OS                           : Ubuntu 22.04.5 LTS (x86_64)
GCC version                  : (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0
Clang version                : Could not collect
CMake version                : Could not collect
Libc version                 : glibc-2.35

==============================
       PyTorch Info
==============================
PyTorch version              : 2.11.0+cu130
Is debug build               : False
CUDA used to build PyTorch   : 13.0
ROCM used to build PyTorch   : N/A
XPU used to build PyTorch    : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.13 (main, May  8 2026, 20:13:12) [GCC 11.4.0] (64-bit runtime)
Python platform              : Linux-6.18.29-talos-x86_64-with-glibc2.35
    
==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : 13.0.88
CUDA_MODULE_LOADING set to   : 
GPU models and configuration : 
GPU 0: NVIDIA A100-SXM4-80GB
GPU 1: NVIDIA A100-SXM4-80GB
GPU 2: NVIDIA A100-SXM4-80GB
GPU 3: NVIDIA A100-SXM4-80GB
GPU 4: NVIDIA A100-SXM4-80GB
GPU 5: NVIDIA A100-SXM4-80GB
GPU 6: NVIDIA A100-SXM4-80GB
GPU 7: NVIDIA A100-SXM4-80GB

Nvidia driver version        : 580.159.03
cuDNN version                : Could not collect
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                            x86_64
CPU op-mode(s):                          32-bit, 64-bit
Address sizes:                           48 bits physical, 48 bits virtual
Byte Order:                              Little Endian
CPU(s):                                  32
On-line CPU(s) list:                     0-31
Vendor ID:                               AuthenticAMD
Model name:                              AMD EPYC 7313 16-Core Processor
CPU family:                              25
Model:                                   1
Thread(s) per core:                      1
Core(s) per socket:                      16
Socket(s):                               2
Stepping:                                1
BogoMIPS:                                5989.12
Flags:                                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate pti ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local user_shstk clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin brs arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm debug_swap
L1d cache:                               1 MiB (32 instances)
L1i cache:                               1 MiB (32 instances)
L2 cache:                                16 MiB (32 instances)
L3 cache:                                256 MiB (8 instances)
NUMA node(s):                            8
NUMA node0 CPU(s):                       0-3
NUMA node1 CPU(s):                       4-7
NUMA node2 CPU(s):                       8-11
NUMA node3 CPU(s):                       12-15
NUMA node4 CPU(s):                       16-19
NUMA node5 CPU(s):                       20-23
NUMA node6 CPU(s):                       24-27
NUMA node7 CPU(s):                       28-31
Vulnerability Gather data sampling:      Not affected
Vulnerability Ghostwrite:                Not affected
Vulnerability Indirect target selection: Not affected
Vulnerability Itlb multihit:             Not affected
Vulnerability L1tf:                      Not affected
Vulnerability Mds:                       Not affected
Vulnerability Meltdown:                  Not affected
Vulnerability Mmio stale data:           Not affected
Vulnerability Old microcode:             Not affected
Vulnerability Reg file data sampling:    Not affected
Vulnerability Retbleed:                  Not affected
Vulnerability Spec rstack overflow:      Mitigation; Safe RET
Vulnerability Spec store bypass:         Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:                Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:                Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP disabled; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                     Not affected
Vulnerability Tsa:                       Vulnerable: No microcode
Vulnerability Tsx async abort:           Not affected
Vulnerability Vmscape:                   Mitigation; IBPB before exit to userspace

==============================
Versions of relevant libraries
==============================
[pip3] flashinfer-python==0.6.8.post1
[pip3] numpy==2.2.6
[pip3] nvidia-cublas==13.1.0.3
[pip3] nvidia-cuda-cupti==13.0.85
[pip3] nvidia-cuda-nvrtc==13.0.88
[pip3] nvidia-cuda-runtime==13.0.96
[pip3] nvidia-cudnn-cu13==9.19.0.56
[pip3] nvidia-cudnn-frontend==1.18.0
[pip3] nvidia-cufft==12.0.0.61
[pip3] nvidia-cufile==1.15.1.6
[pip3] nvidia-curand==10.4.0.35
[pip3] nvidia-cusolver==12.0.4.66
[pip3] nvidia-cusparse==12.6.3.3
[pip3] nvidia-cusparselt-cu13==0.8.0
[pip3] nvidia-cutlass-dsl==4.5.0
[pip3] nvidia-cutlass-dsl-libs-base==4.5.0
[pip3] nvidia-ml-py==13.595.45
[pip3] nvidia-nccl-cu13==2.28.9
[pip3] nvidia-nvjitlink==13.0.88
[pip3] nvidia-nvshmem-cu13==3.4.5
[pip3] nvidia-nvtx==13.0.85
[pip3] pyzmq==27.1.0
[pip3] torch==2.11.0+cu130
[pip3] torch_c_dlpack_ext==0.1.5
[pip3] torchaudio==2.11.0+cu130
[pip3] torchvision==0.26.0+cu130
[pip3] transformers==5.8.0
[pip3] triton==3.6.0
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
vLLM Version                 : 0.20.2
vLLM Build Flags:
  CUDA Archs: 7.5 8.0 8.6 8.9 9.0 10.0 12.0+PTX; ROCm: Disabled; XPU: Disabled
GPU Topology:
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV12    NV12    NV12    NV12    NV12    NV12    NV12    SYS     PXB     SYS     SYS     12-15   3               N/A
GPU1    NV12     X      NV12    NV12    NV12    NV12    NV12    NV12    SYS     PXB     SYS     SYS     12-15   3               N/A
GPU2    NV12    NV12     X      NV12    NV12    NV12    NV12    NV12    PXB     SYS     SYS     SYS     4-7     1               N/A
GPU3    NV12    NV12    NV12     X      NV12    NV12    NV12    NV12    PXB     SYS     SYS     SYS     4-7     1               N/A
GPU4    NV12    NV12    NV12    NV12     X      NV12    NV12    NV12    SYS     SYS     SYS     PXB     28-31   7               N/A
GPU5    NV12    NV12    NV12    NV12    NV12     X      NV12    NV12    SYS     SYS     SYS     PXB     28-31   7               N/A
GPU6    NV12    NV12    NV12    NV12    NV12    NV12     X      NV12    SYS     SYS     PXB     SYS     20-23   5               N/A
GPU7    NV12    NV12    NV12    NV12    NV12    NV12    NV12     X      SYS     SYS     PXB     SYS     20-23   5               N/A
NIC0    SYS     SYS     PXB     PXB     SYS     SYS     SYS     SYS      X      SYS     SYS     SYS
NIC1    PXB     PXB     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      SYS     SYS
NIC2    SYS     SYS     SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS      X      SYS
NIC3    SYS     SYS     SYS     SYS     PXB     PXB     SYS     SYS     SYS     SYS     SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3

==============================
     Environment Variables
==============================
NVIDIA_VISIBLE_DEVICES=GPU-82b46503-e6b2-2c50-fa2d-90d82d1bc165,GPU-5cb9ed85-4063-0206-100f-728d2138a387,GPU-9ba5e7be-f171-ea64-b1bc-40492e2b4daa,GPU-ba8ff172-b13b-9f05-f269-f82524aed498,GPU-1bd43040-3d51-2564-b923-e049c8cef47f,GPU-c8e70bad-7c2e-b068-60c1-a5c9404ba245,GPU-57cd8373-5637-13fd-f7f9-f70f1a5e6302,GPU-3bfb638f-b977-48fc-d332-74c06fcf03d7
NCCL_TEST_LEADER_PORT=tcp://10.98.23.237:20000
NVIDIA_REQUIRE_CUDA=cuda>=13.0 brand=unknown,driver>=535,driver<536 brand=grid,driver>=535,driver<536 brand=tesla,driver>=535,driver<536 brand=nvidia,driver>=535,driver<536 brand=quadro,driver>=535,driver<536 brand=quadrortx,driver>=535,driver<536 brand=nvidiartx,driver>=535,driver<536 brand=vapps,driver>=535,driver<536 brand=vpc,driver>=535,driver<536 brand=vcs,driver>=535,driver<536 brand=vws,driver>=535,driver<536 brand=cloudgaming,driver>=535,driver<536 brand=unknown,driver>=550,driver<551 brand=grid,driver>=550,driver<551 brand=tesla,driver>=550,driver<551 brand=nvidia,driver>=550,driver<551 brand=quadro,driver>=550,driver<551 brand=quadrortx,driver>=550,driver<551 brand=nvidiartx,driver>=550,driver<551 brand=vapps,driver>=550,driver<551 brand=vpc,driver>=550,driver<551 brand=vcs,driver>=550,driver<551 brand=vws,driver>=550,driver<551 brand=cloudgaming,driver>=550,driver<551 brand=unknown,driver>=565,driver<566 brand=grid,driver>=565,driver<566 brand=tesla,driver>=565,driver<566 brand=nvidia,driver>=565,driver<566 brand=quadro,driver>=565,driver<566 brand=quadrortx,driver>=565,driver<566 brand=nvidiartx,driver>=565,driver<566 brand=vapps,driver>=565,driver<566 brand=vpc,driver>=565,driver<566 brand=vcs,driver>=565,driver<566 brand=vws,driver>=565,driver<566 brand=cloudgaming,driver>=565,driver<566 brand=unknown,driver>=570,driver<571 brand=grid,driver>=570,driver<571 brand=tesla,driver>=570,driver<571 brand=nvidia,driver>=570,driver<571 brand=quadro,driver>=570,driver<571 brand=quadrortx,driver>=570,driver<571 brand=nvidiartx,driver>=570,driver<571 brand=vapps,driver>=570,driver<571 brand=vpc,driver>=570,driver<571 brand=vcs,driver>=570,driver<571 brand=vws,driver>=570,driver<571 brand=cloudgaming,driver>=570,driver<571 brand=unknown,driver>=575,driver<576 brand=grid,driver>=575,driver<576 brand=tesla,driver>=575,driver<576 brand=nvidia,driver>=575,driver<576 brand=quadro,driver>=575,driver<576 brand=quadrortx,driver>=575,driver<576 brand=nvidiartx,driver>=575,driver<576 brand=vapps,driver>=575,driver<576 brand=vpc,driver>=575,driver<576 brand=vcs,driver>=575,driver<576 brand=vws,driver>=575,driver<576 brand=cloudgaming,driver>=575,driver<576
NCCL_TEST_LEADER_SERVICE_PORT_HTTP=20000
TORCH_CUDA_ARCH_LIST=7.5 8.0 8.6 8.9 9.0 10.0 12.0+PTX
NCCL_SOCKET_IFNAME=ibs17
NCCL_DEBUG_SUBSYS=INIT,NET,ENV
NCCL_TEST_LEADER_PORT_20000_TCP_ADDR=10.98.23.237
NVIDIA_DRIVER_CAPABILITIES=compute,utility
NCCL_DEBUG=TRACE
NCCL_TEST_LEADER_PORT_20000_TCP=tcp://10.98.23.237:20000
NCCL_IB_HCA=mlx5
VLLM_USAGE_SOURCE=production-docker-image
NCCL_IB_GID_INDEX=3
CUDA_VERSION=13.0.2
NCCL_TEST_LEADER_PORT_20000_TCP_PROTO=tcp
VLLM_ENABLE_CUDA_COMPATIBILITY=0
NCCL_TEST_LEADER_SERVICE_HOST=10.98.23.237
NCCL_TEST_LEADER_PORT_20000_TCP_PORT=20000
LD_LIBRARY_PATH=/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64
NCCL_IB_DISABLE=0
OMP_NUM_THREADS=1
NCCL_TEST_LEADER_SERVICE_PORT=20000
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_root
```
</details>

### 🐛 Describe the bug

We are trying to run a NCCL Test Script to check if Infiniband is running properly.
Script:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nccl-test-script
  namespace: debug
data:
  test_nccl.py: |
    # Test PyTorch NCCL
    import torch
    import torch.distributed as dist
    dist.init_process_group(backend="nccl")
    local_rank = dist.get_rank() % torch.cuda.device_count()
    torch.cuda.set_device(local_rank)
    data = torch.FloatTensor([1,] * 128).to("cuda")
    dist.all_reduce(data, op=dist.ReduceOp.SUM)
    torch.cuda.synchronize()
    value = data.mean().item()
    world_size = dist.get_world_size()
    assert value == world_size, f"Expected {world_size}, got {value}"

    print("PyTorch NCCL is successful!")

    # Test PyTorch GLOO
    gloo_group = dist.new_group(ranks=list(range(world_size)), backend="gloo")
    cpu_data = torch.FloatTensor([1,] * 128)
    dist.all_reduce(cpu_data, op=dist.ReduceOp.SUM, group=gloo_group)
    value = cpu_data.mean().item()
    assert value == world_size, f"Expected {world_size}, got {value}"

    print("PyTorch GLOO is successful!")

    if world_size <= 1:
        exit()

    # Test vLLM NCCL, with cuda graph
    from vllm.distributed.device_communicators.pynccl import PyNcclCommunicator

    pynccl = PyNcclCommunicator(group=gloo_group, device=local_rank)
    pynccl.disabled = False

    s = torch.cuda.Stream()
    with torch.cuda.stream(s):
        data.fill_(1)
        out = pynccl.all_reduce(data, stream=s)
        value = out.mean().item()
        assert value == world_size, f"Expected {world_size}, got {value}"

    print("vLLM NCCL is successful!")

    g = torch.cuda.CUDAGraph()
    with torch.cuda.graph(cuda_graph=g, stream=s):
        out = pynccl.all_reduce(data, stream=torch.cuda.current_stream())

    data.fill_(1)
    g.replay()
    torch.cuda.current_stream().synchronize()
    value = out.mean().item()
    assert value == world_size, f"Expected {world_size}, got {value}"

    print("vLLM NCCL with cuda graph is successful!")

    dist.destroy_process_group(gloo_group)
    dist.destroy_process_group()
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nccl-config
  namespace: debug
data:
  OMP_NUM_THREADS: "1"
  NCCL_DEBUG: "TRACE"
  NCCL_DEBUG_SUBSYS: "INIT,NET,ENV"
  NCCL_IB_GID_INDEX: "3"
  NCCL_IB_HCA: "mlx5"
  NCCL_SOCKET_IFNAME: "ibs17"
  NCCL_IB_DISABLE: "0"
  GLOO_SOCKET_IFNAME: "ibs17"
---
apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: nccl-test
  namespace: debug
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 2
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          role: leader
      spec:
        hostNetwork: true
        hostIPC: true
        dnsPolicy: ClusterFirstWithHostNet
        nodeSelector:
          kubernetes.io/hostname: "cn76"
        runtimeClassName: nvidia
        tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "present"
          effect: "NoSchedule"
        containers:
          - name: nccl-test-leader
            image: vllm/vllm-openai:v0.20.2
            envFrom:
              - configMapRef:
                  name: nccl-config
            command:
              - /bin/sh
              - -c
              - >
                torchrun
                --nnodes=2
                --nproc_per_node=8
                --rdzv_id=nccl-test
                --rdzv_backend=c10d
                --rdzv_endpoint=$(LWS_LEADER_ADDRESS):20000
                /mnt/scripts/test_nccl.py
            securityContext:
              capabilities:
                add: [ "IPC_LOCK", "CAP_SYS_ADMIN" ]
            resources:
              requests:
                cpu: "4"
                memory: "32Gi"
                nvidia.com/gpu: "8"
              limits:
                cpu: "4"
                memory: "32Gi"
                nvidia.com/gpu: "8"
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              - name: scripts
                mountPath: /mnt/scripts
              - name: infiniband
                mountPath: /dev/infiniband
              - name: ib-sys
                mountPath: /sys/class/infiniband
                readOnly: true
              - name: ib-sys-devices
                mountPath: /sys/devices
                readOnly: true
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
          - name: scripts
            configMap:
              name: nccl-test-script
          - name: infiniband
            hostPath:
              path: /dev/infiniband
              type: Directory
          - name: ib-sys
            hostPath:
              path: /sys/class/infiniband
          - name: ib-sys-devices
            hostPath:
              path: /sys/devices
    workerTemplate:
      spec:
        nodeSelector:
          kubernetes.io/hostname: "cn77"
        runtimeClassName: nvidia
        hostNetwork: true
        hostIPC: true
        dnsPolicy: ClusterFirstWithHostNet
        tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          value: "present"
          effect: "NoSchedule"
        containers:
          - name: nccl-test-worker
            image: vllm/vllm-openai:v0.20.2
            envFrom:
              - configMapRef:
                  name: nccl-config
            command:
              - /bin/sh
              - -c
              - >
                torchrun
                --nnodes=2
                --nproc_per_node=8
                --rdzv_id=nccl-test
                --rdzv_backend=c10d
                --rdzv_endpoint=$(LWS_LEADER_ADDRESS):20000
                /mnt/scripts/test_nccl.py
            securityContext:
              capabilities:
                add: [ "IPC_LOCK", "CAP_SYS_ADMIN" ]
            resources:
              requests:
                cpu: "4"
                memory: "32Gi"
                nvidia.com/gpu: "8"
              limits:
                cpu: "4"
                memory: "32Gi"
                nvidia.com/gpu: "8"
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              - name: scripts
                mountPath: /mnt/scripts
              - name: infiniband
                mountPath: /dev/infiniband
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
          - name: scripts
            configMap:
              name: nccl-test-script
          - name: infiniband
            hostPath:
              path: /dev/infiniband
              type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: nccl-test-leader
  namespace: debug
spec:
  ports:
    - name: http
      port: 20000
      protocol: TCP
      targetPort: 20000
  selector:
    leaderworkerset.sigs.k8s.io/name: nccl-test
    role: leader
  type: ClusterIP
```

Log Output:

```
cn76:155:155 [5] NCCL INFO cudaDriverVersion 13000
cn76:155:155 [5] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ibs17
cn76:155:155 [5] NCCL INFO NCCL_SOCKET_IFNAME set to ibs17
cn76:155:155 [5] NCCL INFO NCCL version 2.28.9+cuda13.0
cn76:155:155 [5] NCCL INFO Comm config Blocking set to 1
cn76:154:154 [4] NCCL INFO ENV/Plugin: Could not find: libnccl-env.so
cn76:154:154 [4] NCCL INFO cudaDriverVersion 13000
cn76:154:154 [4] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ibs17
cn76:154:154 [4] NCCL INFO NCCL_SOCKET_IFNAME set to ibs17
cn76:154:154 [4] NCCL INFO NCCL version 2.28.9+cuda13.0
cn76:154:154 [4] NCCL INFO Comm config Blocking set to 1
cn76:157:157 [7] NCCL INFO ENV/Plugin: Could not find: libnccl-env.so
cn76:157:157 [7] NCCL INFO cudaDriverVersion 13000
cn76:157:157 [7] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ibs17
cn76:157:157 [7] NCCL INFO NCCL_SOCKET_IFNAME set to ibs17
cn76:157:157 [7] NCCL INFO NCCL version 2.28.9+cuda13.0
cn76:157:157 [7] NCCL INFO Comm config Blocking set to 1
cn76:156:156 [6] NCCL INFO NET/Plugin: Could not find: libnccl-net.so
cn76:156:156 [6] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
cn76:156:156 [6] NCCL INFO dlvsym failed on mlx5dv_get_data_direct_sysfs_path - /lib/x86_64-linux-gnu/libmlx5.so: undefined symbol: mlx5dv_get_data_direct_sysfs_path, version MLX5_1.25 version MLX5_1.25
cn76:156:156 [6] NCCL INFO dlvsym failed on mlx5dv_reg_dmabuf_mr - /lib/x86_64-linux-gnu/libmlx5.so: undefined symbol: mlx5dv_reg_dmabuf_mr, version MLX5_1.25 version MLX5_1.25
cn76:156:156 [6] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ibs17
cn76:156:156 [6] NCCL INFO NCCL_IB_HCA set to mlx5

[2026-05-15 11:40:19] cn76:156:156 [6] misc/ibvwrap.cc:127 NCCL WARN Call to ibv_open_device failed

[2026-05-15 11:40:19] cn76:156:156 [6] transport/net_ib.cc:715 NCCL WARN NET/IB : Unable to open device mlx5_0

[2026-05-15 11:40:19] cn76:156:156 [6] misc/ibvwrap.cc:127 NCCL WARN Call to ibv_open_device failed

[2026-05-15 11:40:19] cn76:156:156 [6] transport/net_ib.cc:715 NCCL WARN NET/IB : Unable to open device mlx5_1

[2026-05-15 11:40:19] cn76:156:156 [6] misc/ibvwrap.cc:127 NCCL WARN Call to ibv_open_device failed

[2026-05-15 11:40:19] cn76:156:156 [6] transport/net_ib.cc:715 NCCL WARN NET/IB : Unable to open device mlx5_2

[2026-05-15 11:40:19] cn76:156:156 [6] misc/ibvwrap.cc:127 NCCL WARN Call to ibv_open_device failed

[2026-05-15 11:40:19] cn76:156:156 [6] transport/net_ib.cc:715 NCCL WARN NET/IB : Unable to open device mlx5_3
cn76:156:156 [6] NCCL INFO NET/IB : No device found.
cn76:156:156 [6] NCCL INFO NET/IB : Using [RO]; OOB ibs17:10.148.92.116<0>
cn76:156:156 [6] NCCL INFO Failed to initialize NET plugin IB
cn76:156:156 [6] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ibs17
cn76:156:156 [6] NCCL INFO NET/Socket : Using [0]ibs17:10.148.92.116<0>
cn76:156:156 [6] NCCL INFO Initialized NET plugin Socket
cn76:156:156 [6] NCCL INFO Assigned NET plugin Socket to comm
cn76:156:156 [6] NCCL INFO Using network Socket
cn76:150:150 [0] NCCL INFO NET/Plugin: Could not find: libnccl-net.so
cn76:150:150 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 0.
cn76:150:150 [0] NCCL INFO dlvsym failed on mlx5dv_get_data_direct_sysfs_path - /lib/x86_64-linux-gnu/libmlx5.so: undefined symbol: mlx5dv_get_data_direct_sysfs_path, version MLX5_1.25 version MLX5_1.25
cn76:150:150 [0] NCCL INFO dlvsym failed on mlx5dv_reg_dmabuf_mr - /lib/x86_64-linux-gnu/libmlx5.so: undefined symbol: mlx5dv_reg_dmabuf_mr, version MLX5_1.25 version MLX5_1.25
cn76:150:150 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ibs17
cn76:150:150 [0] NCCL INFO NCCL_IB_HCA set to mlx5
```

Expectation:

```
nccl-test:179:179 [0] NCCL INFO NET/IB : Using [0]mlx5_0:1/IB [1]mlx5_1:1/IB [2]mlx5_2:1/IB [3]mlx5_3:1/IB [RO]; OOB eth0:10.0.0.1<0>
nccl-test:179:179 [0] NCCL INFO Using network IB  # ← KEY LINE!
nccl-test:179:179 [0] NCCL INFO NCCL_IB_HCA set to mlx5_0,mlx5_1,mlx5_2,mlx5_3
nccl-test:179:179 [0] NCCL INFO Channel 00/0 : 0[0] -> 8[0] [send] via NET/IB/0/GDRDMA  # ← IB + GPUDirect!
nccl-test:179:179 [0] NCCL INFO Channel 00/0 : 8[0] -> 0[0] [receive] via NET/IB/0/GDRDMA
```

Further information we provided here for the Hardware side:

https://github.com/siderolabs/docs/issues/566

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by inheaden-admin** [comment]
We solved the issue with the following approach:

**a) Load the gdrdrv device Kernel modules according to:
https://github.com/siderolabs/extensions/tree/main/nvidia-gpu/nvidia-gdrdrv-device**

```
machine:
  kernel:
    modules:
      - name: gdrdrv
        parameters:
          - dbg_enabled=0
          - info_enabled=0
          - use_persistent_mapping=1
```

**b) Mount /dev/gdrdrv into the pod**
```
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
              - name: model-storage
                mountPath: /mnt/llm-models
              - name: infiniband
                mountPath: /dev/infiniband
              - name: gdrdrv
                mountPath: /dev/gdrdrv  # GPU memory access
        volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: infiniband
          hostPath:
            path: /dev/infiniband
            type: Directory
```

**Result**

```
cn76:154:154 [5] NCCL INFO Connected to proxy localRank 5 -> connection 0x7f4d90006500
cn76:154:154 [5] NCCL INFO Channel 23/0 : 5[5] -> 0[0] via P2P/CUMEM/read
cn76:154:385 [5] NCCL INFO New proxy send connection 47 from local rank 5, transport 0
cn76:154:154 [5] NCCL INFO Connected to proxy localRank 5 -> connection 0x7f4d90006578
cn76:154:385 [5] NCCL INFO New proxy send connection 48 from local rank 4, transport 0
cn76:154:154 [5] NCCL INFO Connected to proxy localRank 4 -> connection 0x7efebc0065f0
cn76:154:154 [5] NCCL INFO Connected to proxy localRank 0 -> connection 0x7f9c2c006668
cn76:154:385 [5] NCCL INFO New proxy send connection 49 from local rank 0, transport 0
cn76:154:154 [5] NCCL INFO Connected all rings, use ring PXN 0 GDR 1
cn76:154:154 [5] NCCL INFO Initialized NET plugin IB
cn76:154:154 [5] NCCL INFO Assigned NET plugin IB to comm
cn76:154:154 [5] NCCL INFO Assigned GIN plugin GIN_IB_GDAKI to comm
cn76:154:154 [5] NCCL INFO Using network IB
cn76:154:154 [5] NCCL INFO DMA-BUF is available on GPU device 5
cn76:154:154 [5] NCCL INFO ncclCommInitRank comm 0x55ec6e806950 rank 0 nranks 2 cudaDev 5 nvmlDev 5 busId 8b000 commId 0xac211f8337a54293 - Init START
cn76:154:154 [5] NCCL INFO NET/IB : GPU Direct RDMA Enabled for HCA 0 'mlx5_0'
cn76:154:154 [5] NCCL INFO NET/IB : GPU Direct RDMA Enabled for HCA 1 'mlx5_1'
cn76:154:154 [5] NCCL INFO NET/IB : GPU Direct RDMA Enabled for HCA 2 'mlx5_2'
cn76:154:154 [5] NCCL INFO NET/IB : GPU Direct RDMA Enabled for HCA 3 'mlx5_3'
cn76:154:154 [5] NCCL INFO GPU Direct RDMA Enabled for GPU 0 / HCA 3 (distance 5 <= 5), read 0 mode Default
cn76:154:154 [5] NCCL INFO GPU Direct RDMA Enabled for GPU 0 / HCA 3 (distance 5 <= 5), read 0 mode Default
cn76:154:154 [5] NCCL INFO ncclTopoGetCpuAffinity: Affinity for GPU 5 is 28-31. (GPU affinity = 28-31 ; CPU affinity = 0-31).
cn76:154:154 [5] NCCL INFO comm 0x55ec6e806950 rank 0 nRanks 2 nNodes 2 localRanks 1 localRank 0 MNNVL 0
cn76:154:154 [5] NCCL INFO Channel 00/02 : 0 1
cn76:154:154 [5] NCCL INFO Channel 01/02 : 0 1
cn76:154:154 [5] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] -1/-1/-1->0->1
cn76:154:154 [5] NCCL INFO P2P Chunksize set to 131072
cn76:154:154 [5] NCCL INFO Check P2P Type isAllDirectP2p 1 directMode 0 isAllCudaP2p 1
cn76:154:557 [0] NCCL INFO [Proxy Service] Device 5 CPU core 30
cn76:154:154 [5] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
cn76:154:154 [5] NCCL INFO 2 coll channels, 2 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
cn76:154:154 [5] NCCL INFO CC Off, workFifoBytes 1048576
cn76:154:558 [0] NCCL INFO [Proxy Service UDS] Device 5 CPU core 29
cn76:154:154 [5] NCCL INFO ncclCommInitRank comm 0x55ec6e806950 rank 0 nranks 2 cudaDev 5 nvmlDev 5 busId 8b000 commId 0xac211f8337a54293 - Init COMPLETE
cn76:154:154 [5] NCCL INFO Init timings - ncclCommInitRank: rank 0 nranks 2 total 0.04 (kernels 0.00, alloc 0.00, bootstrap 0.00, allgathers 0.01, topo 0.02, graphs 0.00, connections 0.00, rest 0.00)
cn76:154:154 [5] NCCL INFO GPU Direct RDMA Enabled for GPU 0 / HCA 3 (distance 5 <= 5), read 0 mode Default
cn76:154:557 [5] NCCL INFO New proxy recv connection 0 from local rank 0, transport 2(Worker pid=149) INFO 05-16 10:31:52 [parallel_state.py:1715] rank 0 in world size 16 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A, EPLB rank N/A
```

Ref: https://github.com/siderolabs/docs/issues/566
