### ISSUE TITLE
[Bug]: vLLM crashes with `EngineDeadError` when serving Qwen3.5-4B under 2-way concurrent image requests

### ISSUE THREAD

**Issue by WackyGem** [vllm-project/vllm#43473]
### Your current environment

<details>
<summary>The output of <code>python collect_env.py</code></summary>

```text
==============================
        System Info
==============================
OS                           : Ubuntu 26.04 LTS (x86_64)
GCC version                  : (Ubuntu 15.2.0-16ubuntu1) 15.2.0
Clang version                : Could not collect
CMake version                : Could not collect
Libc version                 : glibc-2.43

==============================
       PyTorch Info
==============================
PyTorch version              : 2.11.0+cu130
Is debug build               : False
CUDA used to build PyTorch   : 13.0
ROCM used to build PyTorch   : N/A
XPU used to build PyTorch    : N/A

==============================
      Python Environment
==============================
Python version               : 3.12.13 (main, May 10 2026, 19:30:01) [Clang 22.1.3 ] (64-bit runtime)
Python platform              : Linux-7.0.0-15-generic-x86_64-with-glibc2.43
    
==============================
       CUDA / GPU Info
==============================
Is CUDA available            : True
CUDA runtime version         : Could not collect
CUDA_MODULE_LOADING set to   : 
GPU models and configuration : GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version        : 595.71.05
cuDNN version                : Could not collect
HIP runtime version          : N/A
MIOpen runtime version       : N/A
Is XNNPACK available         : True

==============================
          CPU Info
==============================
Architecture:                            x86_64
CPU op-mode(s):                          32-bit, 64-bit
Address sizes:                           46 bits physical, 48 bits virtual
Byte Order:                              Little Endian
CPU(s):                                  20
On-line CPU(s) list:                     0-19
Vendor ID:                               GenuineIntel
Model name:                              Intel(R) Xeon(R) CPU E5-2666 v3 @ 2.90GHz
CPU family:                              6
Model:                                   63
Thread(s) per core:                      2
Core(s) per socket:                      10
Socket(s):                               1
Stepping:                                2
CPU(s) scaling MHz:                      65%
CPU max MHz:                             3500.0000
CPU min MHz:                             1200.0000
BogoMIPS:                                5799.64
Flags:                                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts vnmi md_clear flush_l1d
Virtualization:                          VT-x
L1d cache:                               320 KiB (10 instances)
L1i cache:                               320 KiB (10 instances)
L2 cache:                                2.5 MiB (10 instances)
L3 cache:                                25 MiB (1 instance)
NUMA node(s):                            1
NUMA node0 CPU(s):                       0-19
Vulnerability Gather data sampling:      Not affected
Vulnerability Ghostwrite:                Not affected
Vulnerability Indirect target selection: Not affected
Vulnerability Itlb multihit:             KVM: Mitigation: Split huge pages
Vulnerability L1tf:                      Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:                       Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:                  Mitigation; PTI
Vulnerability Mmio stale data:           Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Old microcode:             Not affected
Vulnerability Reg file data sampling:    Not affected
Vulnerability Retbleed:                  Not affected
Vulnerability Spec rstack overflow:      Not affected
Vulnerability Spec store bypass:         Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:                Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:                Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP conditional; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                     Not affected
Vulnerability Tsa:                       Not affected
Vulnerability Tsx async abort:           Not affected
Vulnerability Vmscape:                   Mitigation; IBPB before exit to userspace

==============================
Versions of relevant libraries
==============================
[pip3] No relevant packages
[conda] Could not collect

==============================
         vLLM Info
==============================
ROCM Version                 : Could not collect
vLLM Version                 : 0.21.0
vLLM Build Flags:
  CUDA Archs: Not Set; ROCm: Disabled; XPU: Disabled
GPU Topology:
  	GPU0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	0-19	0		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

==============================
     Environment Variables
==============================
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_aurora
```

</details>

## Describe the bug
When I serve `Qwen3.5-4B` with vLLM and send multiple concurrent image analysis requests, the engine crashes during attention metadata construction.  
The failure happens while handling concurrent requests through the OpenAI-compatible `/v1/chat/completions` endpoint. In my case, the crash appears when using 2-way concurrency on the client side, with the server configured with `--max-num-seqs 2`. It works fine when requests are processed sequentially, but crashes when there are two concurrent requests.

Minimal reproduction client:

```python
import asyncio
import base64
import mimetypes
import sys
from pathlib import Path

import aiohttp

URL = "http://127.0.0.1:8088/v1/chat/completions"
MODEL = "Qwen3.5-4B"


def image_to_data_url(path: Path) -> str:
    mime_type = mimetypes.guess_type(path)[0] or "image/png"
    encoded = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:{mime_type};base64,{encoded}"


def build_payload(image_path: Path) -> dict:
    return {
        "model": MODEL,
        "messages": [
            {
                "role": "system",
                "content": [
                    {
                        "type": "text",
                        "text": (
                            'Extract the image info into this JSON schema. '
                            'Return valid JSON array only, no other text.'
                        ),
                    }
                ],
            },
            {
                "role": "user",
                "content": [
                    {
                        "type": "image_url",
                        "image_url": {"url": image_to_data_url(image_path)},
                    }
                ],
            },
        ],
        "max_tokens": 8192,
        "temperature": 0.6,
        "top_p": 0.95,
        "top_k": 20,
        "presence_penalty": 0.0,
        "repetition_penalty": 1.0,
        "include_reasoning": False,
        "response_format": {
            "type": "json_schema",
            "json_schema": {
                "name": "stock_theme",
                "schema": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "stock_name": {"type": "string"},
                            "first_theme": {"type": "string"},
                            "second_theme": {"type": "string"},
                            "third_theme": {"type": "string"},
                            "relevance": {"type": "string"},
                            "sources": {"type": "string"},
                        },
                        "required": [
                            "stock_name",
                            "first_theme",
                            "second_theme",
                            "third_theme",
                            "relevance",
                            "sources",
                        ],
                        "additionalProperties": False,
                    },
                },
                "strict": True,
            },
        },
        "chat_template_kwargs": {"enable_thinking": False},
    }


async def request_one(session: aiohttp.ClientSession, image_path: Path):
    async with session.post(URL, json=build_payload(image_path)) as response:
        text = await response.text()
        print(image_path.name, response.status, text[:500])


async def main():
    image_paths = [Path(p) for p in sys.argv[1:5]]
    timeout = aiohttp.ClientTimeout(total=300)
    async with aiohttp.ClientSession(timeout=timeout) as session:
        await asyncio.gather(*(request_one(session, path) for path in image_paths))


asyncio.run(main())
```
Server startup command from my Docker Compose setup:

```yaml
services:
  ocr-server:
    image: vllm/vllm-openai:latest
    container_name: ocr-server
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      - VLLM_LOGGING_LEVEL=DEBUG
    volumes:
      - /storage/program/models/:/models:rw
    command:
      - /models/Qwen3.5-4B
      - --served-model-name
      - Qwen3.5-4B
      - --tensor-parallel-size
      - "1"
      - --dtype
      - "float16"
      - --kv-cache-dtype
      - "float16"
      - --max-model-len
      - "20480"
      - --max-num-seqs
      - "2"
      - --gpu-memory-utilization
      - "0.8"
      - --host
      - 0.0.0.0
      - --port
      - "8088"
      - --enable-prefix-caching
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "--silent", "http://localhost:8088/health"]
      interval: 10s
      timeout: 10s
      start_period: 30s
      retries: 3

networks:
  default:
    name: ocr_default
```

Run it with 2 local image files:

```bash
python repro.py image1.png image2.png
```
## Actual behavior
The engine crashes during request processing and the API returns 500 responses.

Relevant traceback:

```text
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1133, in run_engine_core
    engine_core.run_busy_loop()
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core.py", line 1213, in _process_engine_step
    outputs, model_executed = self.step_fn()
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 4053, in execute_model
    self._build_attention_metadata(
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/worker/gpu_model_runner.py", line 2300, in _build_attn_group_metadata
    attn_metadata_i = builder.build(
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/attention/backends/flashinfer.py", line 1213, in build
    decode_wrapper = self._get_decode_wrapper(
  File "/usr/local/lib/python3.12/dist-packages/vllm/v1/attention/backends/flashinfer.py", line 800, in _get_decode_wrapper
    decode_wrapper = BatchDecodeWithPagedKVCacheWrapper(
  File "/usr/local/lib/python3.12/dist-packages/flashinfer/decode.py", line 752, in __init__
    self._pin_memory_int_workspace_buffer = torch.empty(
torch.AcceleratorError: CUDA error: OS call failed or operation not supported on this OS
```

Relevant `dump_input.py` log lines:

```text
[dump_input.py:79] Dumping scheduler output for model execution: SchedulerOutput(scheduled_new_reqs=[], scheduled_cached_reqs=CachedRequestData(req_ids=['chatcmpl-a4044f52d4c452a6-9d1f2bc6', 'chatcmpl-a09412ca46855553-a4fac64b'],resumed_req_ids=set(),new_token_ids_lens=[],all_token_ids_lens={},new_block_ids=[None, ([0, 0, 19], [0, 0, 20], [0, 0, 21], [22, 23, 24])],num_computed_tokens=[1041, 2112],num_output_tokens=[1, 0]), num_scheduled_tokens={chatcmpl-a09412ca46855553-a4fac64b: 1584, chatcmpl-a4044f52d4c452a6-9d1f2bc6: 1}, total_num_scheduled_tokens=1585, scheduled_spec_decode_tokens={}, scheduled_encoder_inputs={}, num_common_prefix_blocks=[0, 0, 0, 0], finished_req_ids=[], free_encoder_mm_hashes=[], preempted_req_ids=[], has_structured_output_requests=true, pending_structured_output_tokens=true, num_invalid_spec_tokens=null, kv_connector_metadata=null, ec_connector_metadata=null, new_block_ids_to_zero=[22, 23, 24])
[dump_input.py:81] Dumping scheduler stats: SchedulerStats(num_running_reqs=2, num_waiting_reqs=0, num_skipped_waiting_reqs=0, step_counter=0, current_wave=0, kv_cache_usage=0.048648648648648596, prefix_cache_stats=PrefixCacheStats(reset=False, requests=0, queries=0, hits=0, preempted_requests=0, preempted_queries=0, preempted_hits=0), connector_prefix_cache_stats=None, kv_cache_eviction_events=[], spec_decoding_stats=None, kv_connector_stats=None, waiting_lora_adapters={}, running_lora_adapters={}, cudagraph_stats=None, perf_stats=None)
```
I have attached the complete log file with the environment variable `VLLM_LOGGING_LEVEL=DEBUG`. The log is too long and exceeds the character limit of the current input field.

[vllm_logs.txt](https://github.com/user-attachments/files/28172898/vllm_logs.txt)

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by ricky-chaoju** [comment]
I tried to reproduce this locally but could not hit the crash.
My setup is different though: I tested on an RTX 5090 with the same local `Qwen3.5-4B` model, `--max-num-seqs 2`, and two concurrent image requests. Both requests returned 200 and I did not see `EngineDeadError`.

**Comment by WackyGem** [comment]
> I tried to reproduce this locally but could not hit the crash.我尝试在本地重现这个问题，但未能重现崩溃情况。 My setup is different though: I tested on an RTX 5090 with the same local `Qwen3.5-4B` model, `--max-num-seqs 2`, and two concurrent image requests. Both requests returned 200 and I did not see `EngineDeadError`.我的设置略有不同：我用的是 RTX 5090 显卡，本地镜像型号也是 `Qwen3.5-4B` ，设置了 `--max-num-seqs 2` 参数，并同时发起了两个镜像请求。两个请求都返回了 200，没有出现 `EngineDeadError` 。

Yes, the 4090 graphics card works fine on my Ubuntu 24 os. I think the potential issue might lie with the 2080 Ti graphics card hardware or the Ubuntu 26 os.  It might be a compatibility issue.

**Comment by jshaofa-ui** [comment]
# Solution: vllm #43473 — EngineDeadError with Concurrent Image Requests

## Issue Summary
**GitHub**: vllm-project/vllm #43473
**Title**: vLLM crashes with `EngineDeadError` when serving Qwen3.5-4B under 2-way concurrent image requests
**Labels**: bug
**Competition**: Low (2 comments, no PRs)
**Quote**: $1,500-$2,500

## Root Cause Analysis

### Primary Root Cause: Multi-Modal Engine State Corruption Under Concurrency

The `EngineDeadError` indicates that the vLLM engine process (or CUDA context) has crashed or become unresponsive. Under concurrent multi-modal (image + text) requests, the engine's state management for vision encoder + LLM pipeline has a race condition or resource contention that leads to engine death.

### Failure Chain

```
Request 1: text + image → Vision encoder → LLM
Request 2: text + image → Vision encoder → LLM
  → Concurrent vision encoding
  → Shared CUDA stream / memory pool contention
  → Engine process crashes or becomes unresponsive
  → EngineDeadError propagated to API
```

### Contributing Factors

1. **Vision Encoder Resource Contention**: Qwen3.5-4B's vision encoder shares CUDA resources with the LLM. Under concurrent image requests, the vision encoder may exhaust shared memory or CUDA stream resources.

2. **Engine Process Watchdog**: The engine process may have a watchdog that kills the process if it detects a hang (e.g., CUDA kernel timeout). Concurrent image processing may trigger this watchdog.

3. **CUDA Graph Capture Conflict**: If CUDA graphs are enabled, concurrent requests may trigger graph capture/replay conflicts that corrupt engine state.

### Evidence Pattern

| Signal | Interpretation |
|--------|---------------|
| EngineDeadError | Engine process crashed or hung |
| 2-way concurrent | Triggered by concurrency, not single request |
| Qwen3.5-4B | Specific model — may have vision encoder quirks |
| RTX 2080 Ti | Older GPU — may have memory/CUDA limitations |

## Proposed Fix

### Fix 1: Vision Encoder Concurrency Guard

**File**: `vllm/model_executor/models/qwen2_5_vl.py` (or equivalent)

```python
import asyncio
from contextlib import asynccontextmanager

class VisionEncoderPool:
    """Limit concurrent vision encoding to prevent resource exhaustion."""
    
    def __init__(self, max_concurrent: int = 1):
        self._semaphore = asyncio.Semaphore(max_concurrent)
    
    @asynccontextmanager
    async def acquire(self):
        async with self._semaphore:
            yield

# Apply to vision encoding path
_vision_pool = VisionEncoderPool(max_concurrent=1)

async def _encode_images_with_guard(images, **kwargs):
    async with _vision_pool.acquire():
        return await _encode_images_raw(images, **kwargs)
```

### Fix 2: Engine Health Check + Auto-Recovery

**File**: `vllm/engine/async_llm_engine.py`

```python
class AsyncLLMEngine:
    async def _check_engine_health(self):
        """Periodic health check for engine process."""

**Comment by WackyGem** [comment]
> I tried to reproduce this locally but could not hit the crash. My setup is different though: I tested on an RTX 5090 with the same local `Qwen3.5-4B` model, `--max-num-seqs 2`, and two concurrent image requests. Both requests returned 200 and I did not see `EngineDeadError`.

I downgraded Ubuntu from version 26 to 24, and now the environment is working properly.  I suspect there was a compatibility issue between FlashInfer and the Linux-7.0.0-15-generic kernel. Now that my issue has been resolved, I will close this issue.  Thank you for your reply. @ricky-chaoju
