### ISSUE TITLE
[DSv4] [SM 12.0] fp8_einsum has no SM 12.0 fallback — blocks mainline serve on consumer Blackwell (follow-up to #41834)

### ISSUE THREAD

**Issue by pasta-paul** [vllm-project/vllm#43743]
## DSv4 attention `fp8_einsum` has no SM 12.0 fallback in mainline — blocks consumer Blackwell serve

> _Disclosure (per [`AGENTS.md`](https://github.com/vllm-project/vllm/blob/main/AGENTS.md#accountability)): drafted with AI assistance; all references verified by hand against vllm-project/vllm@`e19b9b104` and jasl/vllm@`27fd665b` source trees on 2026-05-27. The human submitter (@pasta-paul / canada-quant) defends every claim._

### Summary

On RTX PRO 6000 Blackwell (SM 12.0), vllm-project/vllm@main + [`#43722`](https://github.com/vllm-project/vllm/pull/43722) + [`#43723`](https://github.com/vllm-project/vllm/pull/43723) + [`#41834`](https://github.com/vllm-project/vllm/pull/41834) (full overlay) + [`#40923`](https://github.com/vllm-project/vllm/pull/40923) + [`#43655`](https://github.com/vllm-project/vllm/pull/43655) (rebased) gets DSv4-Flash artifacts past engine init + Marlin/Triton dispatch + cudagraph capture, then **fails at first forward pass** with:

```
RuntimeError: Assertion error (csrc/apis/../jit_kernels/impls/../heuristics/../../utils/layout.hpp:39): t.dim() == N
  at vllm/utils/deep_gemm.py:317 fp8_einsum
  at vllm/models/deepseek_v4/attention.py (forward)
```

Root cause: `vllm.utils.deep_gemm.fp8_einsum` resolves to DeepGEMM's Hopper-only `fp8_einsum` impl on consumer Blackwell, which asserts a tensor rank that the SM 12.0 call site doesn't satisfy.

### Why this is separate from #41834

[`#41834`](https://github.com/vllm-project/vllm/pull/41834) cleanly addresses one of the DeepGEMM Hopper-only call sites — `tf32_hc_prenorm_gemm` — via `_tf32_hc_prenorm_gemm_sm12x` dispatch in `vllm/utils/deep_gemm.py` and a Triton fallback in `vllm/models/deepseek_v4/nvidia/ops/sm12x_deep_gemm_fallbacks.py`. With #41834's full overlay applied, that first crash is gone. But the **second DeepGEMM call**, `fp8_einsum`, has no SM 12.0 dispatch in mainline OR in #41834.

### Where jasl/vllm solves this

[jasl/vllm@`27fd665b`](https://github.com/jasl/vllm/tree/27fd665bdc3ba58afc5c34cbb9034c9fc1a95029) ships these files in `vllm/models/deepseek_v4/nvidia/ops/` that are absent from mainline:

| File | Purpose | LoC |
|---|---|---|
| `fp8_einsum.py` | SM 12.0 Triton fallback (`_deepseek_v4_sm12x_fp8_einsum_kernel`) + a `direct_register_custom_op(deepseek_v4_fp8_einsum)` that dispatches between `deepseek_v4_sm12x_fp8_einsum` (Triton, SM 12.0) and the DeepGEMM `fp8_einsum` (Hopper) | 294 |
| `cutedsl_utils.py` | CuteDSL helpers used by the SM 12.0 dispatch glue | 178 |

The dispatch pattern (in jasl's `fp8_einsum.py`):

```python
def deepseek_v4_fp8_einsum(equation, a, a_scale, b, b_scale, out, *, recipe):
    if _use_deepseek_v4_sm12x_triton_fp8_einsum(equation, recipe, b_scale):
        deepseek_v4_sm12x_fp8_einsum(a, a_scale, b, b_scale, out)
    else:
        fp8_einsum(equation, (a, a_scale), (b, b_scale), out, recipe=tuple(recipe))
```

And jasl's `attention.py:32`:

```python
from vllm.models.deepseek_v4.nvidia.ops.fp8_einsum import (
    deepseek_v4_fp8_einsum_config,
)
# ... then forward calls torch.ops.vllm.deepseek_v4_fp8_einsum(...)
```

i.e. the dispatch lives **inside a registered custom op**, not in `deep_gemm.py`. Mainline's `vllm/models/deepseek_v4/attention.py` (post-#43149 refactor) calls `fp8_einsum(...)` from `vllm.utils.deep_gemm` directly, with no custom-op wrapper.

### What's needed for mainline SM 12.0 viability

Port jasl's pattern to mainline:

1. **Add** `vllm/models/deepseek_v4/fp8_einsum.py` (note: top-level after #43149, not `nvidia/ops/`) containing:
   - `_deepseek_v4_sm12x_fp8_einsum_kernel` Triton kernel
   - `deepseek_v4_sm12x_fp8_einsum` wrapper
   - `deepseek_v4_fp8_einsum` dispatcher
   - `direct_register_custom_op("deepseek_v4_fp8_einsum", ...)`
2. **Add** `vllm/models/deepseek_v4/cutedsl_utils.py` (CuteDSL helpers)
3. **Update** `vllm/models/deepseek_v4/attention.py` (line ~32) to import from the new module and call the registered op instead of bare `fp8_einsum`.

This unblocks mainline DSv4 serve on SM 12.0 (after #41834, #43722, #43723, #40923, #43655 also land). Estimated diff size: ~500 lines (most of it is the existing Triton kernel + a custom-op wrapper).

### What we'd offer

We have an RTX PRO 6000 Server Edition box + canada-quant artifacts + verified jasl-based reference. Can test any proposed mainline port within 24h. The jasl files are MIT/Apache-2.0 licensed (same as vLLM) and can be copy-ported with attribution.

### Cross-references

- Parent tracker [#43564](https://github.com/vllm-project/vllm/issues/43564) — full Phase A summary at https://github.com/vllm-project/vllm/issues/43564#issuecomment-4550184475
- PR [`#41834`](https://github.com/vllm-project/vllm/pull/41834) — fixes `tf32_hc_prenorm_gemm` SM 12.0 dispatch; this issue is its follow-up for `fp8_einsum`
- jasl source: https://github.com/jasl/vllm/blob/ds4-sm120-preview-dev/vllm/models/deepseek_v4/nvidia/ops/fp8_einsum.py + https://github.com/jasl/vllm/blob/ds4-sm120-preview-dev/vllm/models/deepseek_v4/nvidia/ops/cutedsl_utils.py
- Today's verified working stack on jasl@27fd665b: Card D AIME-30 c=4 thinking = 24/30 correct, 0 CUDA errors, 91.61% MTP acceptance — [bench JSON](https://github.com/canada-quant/dsv4-flash-w4a16-fp8-mtp/blob/main/benchmarks/rtxpro6000/aime30_c4_thinking_jasl27fd665b.json)

cc @jasl @mgoin @pavanimajety @robertgshaw2-redhat @tlrmchlsmth @yewentao256 @zyongye.

**Comment by AasthaPJoshi** [comment]
The proposed `fp8_einsum` fallback makes sense locally, but I wonder if this is exposing a broader dispatch invariant worth tightening for SM12x support.

We now have several places where “Blackwell-capable” is not equivalent to “this specific backend/kernel is valid on SM100 and SM120.” `fp8_einsum` is one instance, but the same class of failure can appear anywhere an architecture-family check selects a kernel whose ISA/layout assumptions are narrower than that family.

I’d try to preserve an invariant like:

> A kernel may be selected only through an explicit capability predicate for that kernel/recipe, not from a coarse architecture-family assumption.

That could still be implemented with simple predicates, e.g. `supports_deepgemm_fp8_einsum(...)`, but it gives each call site one source of truth for:

* supported compute capabilities
* recipe/layout constraints
* dtype/scale-format requirements
* fallback availability

Then SM120 coverage can be tested as a capability matrix instead of discovering the next unsupported DeepGEMM entry point during first forward.

For this specific patch, I’d also add a dispatch test that forces the SM120 capability path and asserts the registered op selects the Triton fallback without invoking the Hopper/SM100 DeepGEMM implementation. That seems more durable than only testing the fallback kernel numerically.

**Comment by ivanusto** [comment]
This one also appears to be resolved upstream, by the DeepGEMM pin rather than by any of the vLLM PRs in that overlay.

#52035 (merged Aug 12) moved `cmake/external_projects/deepgemm.cmake` from `vllm-project/DeepGEMM@e21c821` to `deepseek-ai/DeepGEMM@8b1392b`. The dispatch in `csrc/apis/einsum.hpp` is the relevant difference:

- `e21c821`: includes only `sm90_bmk_bnk_mn.hpp` and `sm100_bmk_bnk_mn.hpp`, and dispatches `arch_major == 9` or `== 10`, otherwise `DG_HOST_UNREACHABLE("Unsupported architecture")`. A capability 12 device matched nothing, which is the shape of the rank assert you saw once it was routed to the Hopper implementation.
- `8b1392b`: adds `sm120_bmk_bnk_mn.hpp`, `sm120_bf16_gemm.hpp` and `sm120_fp8_fp4_gemm_1d1d.hpp`, and dispatches `arch_major == 12` to `sm120_bmn_bnk_mn_gemm`.

I exercised this live rather than only reading it. On two GB10 nodes at TP=2 with stock `vllm/vllm-openai:nightly-aarch64` (`0.26.1rc1.dev1219+g46638857f`), no patches and no DeepGEMM environment variables, `DeepSeek-V4-Flash-0731-NVFP4` starts and serves, and decode goes through `deep_gemm_fp8_o_proj` and its `fp8_einsum` call on every step:

```
Model loading took 77.84 GiB memory and 569.280317 seconds
GPU KV cache size: 93,770 tokens
INFO:     Application startup complete.
```

A 400 token completion took 15.15 s with no assertion in either rank's log.

Two caveats. I am on sm_121 and you are on SM 12.0, and while the fix is written as `arch_major == 12` and covers both, I have no RTX PRO 6000 to confirm on. Separately, the call site itself is unchanged: `fp8_einsum` in `deep_gemm_fp8_o_proj` still has neither an `is_deep_gemm_supported()` check nor a torch fallback. It works now because the kernel supports the architecture, not because the call site got safer, so the hardening argument in this issue still has merit even though the immediate blocker is gone.

I hit the same call site from the sm_121 side and filed #52732, now closed for this reason. Worth retesting on any build after Aug 12 before carrying that overlay forward.
