### ISSUE TITLE
[Bug]: Initialising LLM on multiple GPUs stuck at "Started a local Ray instance"

### ISSUE THREAD

**Issue by timbmg** [vllm-project/vllm#4431]
### Your current environment

```text
PyTorch version: 2.2.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Rocky Linux 8.8 (Green Obsidian) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-20)
Clang version: Could not collect
CMake version: version 3.29.2
Libc version: glibc-2.28

Python version: 3.9.13 (main, Oct 13 2022, 21:15:33)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-513.9.1.el8_9.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA H100 PCIe
GPU 1: NVIDIA H100 PCIe

Nvidia driver version: 535.129.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              256
On-line CPU(s) list: 0-255
Thread(s) per core:  2
Core(s) per socket:  64
Socket(s):           2
NUMA node(s):        2
Vendor ID:           AuthenticAMD
CPU family:          25
Model:               17
Model name:          AMD EPYC 9534 64-Core Processor
Stepping:            1
CPU MHz:             3700.121
CPU max MHz:         3718.0659
CPU min MHz:         1500.0000
BogoMIPS:            4900.22
Virtualization:      AMD-V
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            32768K
NUMA node0 CPU(s):   0-63,128-191
NUMA node1 CPU(s):   64-127,192-255
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 invpcid_single hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp ibrs_enhanced vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr wbnoinvd amd_ppin cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif x2avic v_spec_ctrl avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid overflow_recov succor smca fsrm flush_l1d

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.19.3
[pip3] torch==2.2.1
[pip3] triton==2.2.0
[pip3] vllm-nccl-cu12==2.18.1.0.4.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-nccl-cu12          2.19.3                   pypi_0    pypi
[conda] torch                     2.2.1                    pypi_0    pypi
[conda] triton                    2.2.0                    pypi_0    pypi
[conda] vllm-nccl-cu12            2.18.1.0.4.0             pypi_0    pypiROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.4.1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0	GPU1	NIC0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	X 	SYS	PHB		1		N/A
GPU1	SYS	X 	SYS		1		N/A
NIC0	PHB	SYS	X 				

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_bond_0
```

### 🐛 Describe the bug

I am trying to run an LLM on multiple GPUs (2x H100), however, it seems stuck at after starting the local Ray instance. I have also tried setting `NCCL_P2P_DISABLE=1` as suggest in other issues, however, this did not solve my problem.

```python3
from vllm import LLM
llm = LLM(
    model="CohereForAI/c4ai-command-r-v01", 
    max_model_len=2**15, # limit context to 32k
    gpu_memory_utilization=0.95,
    dtype="float16",
    tensor_parallel_size=2
) 
# 2024-04-27 15:26:35,737	INFO worker.py:1749 -- Started a local Ray instance.
```

`nvidia-smi` gives:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA H100 PCIe               On  | 00000000:61:00.0 Off |                    0 |
| N/A   31C    P0              47W / 350W |      2MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA H100 PCIe               On  | 00000000:E1:00.0 Off |                    0 |
| N/A   30C    P0              46W / 350W |      2MiB / 81559MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by sweetning0809** [comment]
how about try first
# On head node
ray start --head

# On worker nodes
ray start --address=<ray-head-address>

**Comment by timbmg** [comment]
I am just running this in a jupyter notebook.

I tried running `ray start --head` before (i.e. `!ray start --head` in a previous cell). When I do this, it also does not work; the message is slightly different (attached to running Ray server).

**Comment by sweetning0809** [comment]
using ray start --head you can get feedback from your shell (an ip) and using the second command ray start --address=(ip) to connect to the head, i'm not sure,run in the same problem and fixed by those

**Comment by shangshng** [comment]
same problem here. using vllm==0.3.3

**Comment by timbmg** [comment]
> using ray start --head you can get feedback from your shell (an ip) and using the second command ray start --address=(ip) to connect to the head, i'm not sure,run in the same problem and fixed by those

I see; but how would I do this with jupyter notebook? Should I run these commands before? From my understanding when initializing the `LLM` object, it calls `ray.init()`, thereby connecting to the ray head node.

I tried to run `ray --head` before in a separate terminal, then init the `LLM`. This gives:
```text
2024-04-29 09:43:37,270	INFO worker.py:1564 -- Connecting to existing Ray cluster at address: 10.167.11.167:6379...
2024-04-29 09:43:37,286	INFO worker.py:1749 -- Connected to Ray cluster.
```
But after 10 mins of waiting no progress, cell is still running, and when checking `nvidia-smi` it does not seem that the model is starting to get loaded onto the GPUs.

**Comment by timbmg** [comment]
I was able to solve this, here were my issues:

For multi-gpu, it is necessary to load the NCCL library properly (for single GPU I was also getting an error when initilizing `LLM`, however, inference still worked properly). In my case, on the server I was running the code, I did not have access to the original home directory where the config and `libnccl.so.2.18.1` file is stored. Therefore, I first copied the $HOME/.config/vllm dir, and then set `/ukp-storage-1/baumgaertner/.config/vllm/nccl/cu12/libnccl.so.2.18.1`.

For ray to work properly, I had to start ray before initializing `LLM`. For this, I created a new screen and ran `ray --logging-level=debug start --head --disable-usage-stats --num-cpus=10`.

**Comment by chrisbraddock** [comment]
> @timbmg thanks for this! I've been struggling getting vLLM running reliably w/ dual GPUs for a while. My scenario sounds a little different than yours. This did the trick for me, added to my vLLM startup script:

```shell
export LD_LIBRARY_PATH=$HOME/.config/vllm/nccl/cu12:$LD_LIBRARY_PATH
```

**Comment by RomanKoshkin** [comment]
This is what worked for me:

Not running in a container, just a conda environment with `vLLM` installed with `pip install vllm` (running `pip list | grep "vllm"` shows: 
```
vllm                      0.4.1
vllm-nccl-cu12            2.18.1.0.4.0
```

Then, as @timbmg suggested, in a separate terminal session

```bash
ray --logging-level=debug start --head --disable-usage-stats --num-cpus=10
```

Then, in the other terminal session run:
```bash
export LD_LIBRARY_PATH=$HOME/.config/vllm/nccl/cu12
python testtest.py
```

`testtest.py` is as follows:

```python
from vllm import LLM, SamplingParams


sampling_params = SamplingParams(
    min_tokens=2,
    max_tokens=10,
    include_stop_str_in_output=True,
)



llm = LLM(
    model="meta-llama/Meta-Llama-3-8B-Instruct", 
    max_model_len=8192,
    tensor_parallel_size=4,
    download_dir=<PATH_TO_YOUR_HUGGINGFACE_CACHE>,
) 

outputs = llm.generate(
        prompts="I like cheese",
        sampling_params=sampling_params)

print(outputs)
```
