### ISSUE TITLE
[Bug]: NCCL timed out during inference

### ISSUE THREAD

**Issue by enkiid** [vllm-project/vllm#4653]
### Your current environment

Using:
* vllm 0.4.1
* nccl 2.18.1
* pytorch 2.2.1

### 🐛 Describe the bug

During inference I sometimes get this error:

```bash
(RayWorkerWrapper pid=2376582) [rank1]:[E ProcessGroupNCCL.cpp:523] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=50404, OpType=GATHER, NumelIn=8000, NumelOut=0, Timeout(ms)=600000) ran for 600327 milliseconds before timing out.
```

Havn't seen it in earlier versions of vllm, any thoughts?

**Comment by Ch3ngY1** [comment]
The same issue, which occurs randomly on my dataset. 
vllm 0.4.1
torch 2.2.0+cu118

**Comment by DefTruth** [comment]
i have encountered the same issue,  try `--disable-custom-all-reduce` and `--enforce-eager` is worked for me.

**Comment by changyuanzhangchina** [comment]
Please refer to https://github.com/vllm-project/vllm/issues/4430
1. --disable-custom-all-reduce = True
2. --enforce-eager = True (may be unnecessary)
3.  update to the https://github.com/vllm-project/vllm/pull/4557

This three can solve the watchdog problem for me
before this, nccl watchdog error happens several times per day,
and now, it works well

**Comment by yunfeng-scale** [comment]
we're seeing this on 0.4.2 as well with mixtral 8x22b. --disable-custom-all-reduce resolves the problem.

**Comment by yunfeng-scale** [comment]
can we again disable custom all reduce by default?

**Comment by syr-cn** [comment]
> i have encountered the same issue, try `--disable-custom-all-reduce` and `--enforce-eager` is worked for me.

Works for me! thanks a lot!

**Comment by fake-warrior8** [comment]
> i have encountered the same issue, try `--disable-custom-all-reduce` and `--enforce-eager` is worked for me.

My code use vllm for evaluation, how to set these parameters to vllm.LLM?

from vllm import LLM, SamplingParams
