### ISSUE TITLE
[Bug]: unhandled system error with NCCL on v0.5.0.post1

### ISSUE THREAD

**Issue by eByteTheDust** [vllm-project/vllm#5828]
### Your current environment

```text
Collecting environment information...
PyTorch version: 2.3.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.2
Libc version: glibc-2.35

Python version: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.5.0-1022-azure-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 535.171.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Address sizes:                      48 bits physical, 48 bits virtual
Byte Order:                         Little Endian
CPU(s):                             4
On-line CPU(s) list:                0-3
Vendor ID:                          AuthenticAMD
Model name:                         AMD EPYC 7V12 64-Core Processor
CPU family:                         23
Model:                              49
Thread(s) per core:                 1
Core(s) per socket:                 4
Socket(s):                          1
Stepping:                           0
BogoMIPS:                           4890.88
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru arat umip rdpid
Hypervisor vendor:                  Microsoft
Virtualization type:                full
L1d cache:                          128 KiB (4 instances)
L1i cache:                          128 KiB (4 instances)
L2 cache:                           2 MiB (4 instances)
L3 cache:                           16 MiB (1 instance)
NUMA node(s):                       1
NUMA node0 CPU(s):                  0-3
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Mitigation; untrained return thunk; SMT disabled
Vulnerability Spec rstack overflow: Vulnerable: Safe RET, no microcode
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines; STIBP disabled; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] sentence-transformers==2.7.0
[pip3] torch==2.3.0+cu121
[pip3] transformers==4.40.1
[pip3] triton==2.3.0
[pip3] vllm-nccl-cu12==2.18.1.0.4.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] sentence-transformers     2.7.0                    pypi_0    pypi
[conda] torch                     2.3.0+cu121              pypi_0    pypi
[conda] transformers              4.40.1                   pypi_0    pypi
[conda] triton                    2.3.0                    pypi_0    pypi
[conda] vllm-nccl-cu12            2.18.1.0.4.0             pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.4.2
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    NIC0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     0-3     0               N/A
NIC0    SYS      X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
```

### 🐛 Describe the bug

vllm won't load with v0.5.0 or v0.5.0.post1, when downgrading to 0.4.2 it works fine. 

v0.5.0.post1 throws this error: RuntimeError: NCCL Error 2: unhandled system error. More details below:

INFO 06-25 15:26:04 api_server.py:177] vLLM API server version 0.5.0.post1
INFO 06-25 15:26:04 api_server.py:178] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/ai/Meta-Llama-3-8B-Instruct', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='half', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=4096, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=True, pipeline_parallel_size=1, tensor_parallel_size=2, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=True, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=0.96, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=True, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=True, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, device='auto', image_input_type=None, image_token_id=None, image_input_shape=None, image_feature_size=None, image_processor=None, image_processor_revision=None, disable_image_processor=False, scheduler_delay_factor=0.0, enable_chunked_prefill=False, speculative_model=None, num_speculative_tokens=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, model_loader_extra_config=None, preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, engine_use_ray=False, disable_log_requests=True, max_log_len=None)
WARNING 06-25 15:26:04 config.py:1222] Casting torch.bfloat16 to torch.float16.
2024-06-25 15:26:04,681 INFO worker.py:1568 -- Connecting to existing Ray cluster at address: 10.1.0.10:6379...
2024-06-25 15:26:04,687 INFO worker.py:1753 -- Connected to Ray cluster.
INFO 06-25 15:26:04 llm_engine.py:161] Initializing an LLM engine (v0.5.0.post1) with config: model='/ai/Meta-Llama-3-8B-Instruct', speculative_config=None, tokenizer='/ai/Meta-Llama-3-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), seed=0, served_model_name=/ai/Meta-Llama-3-8B-Instruct)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 06-25 15:26:09 selector.py:131] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 06-25 15:26:09 selector.py:51] Using XFormers backend.
(RayWorkerWrapper pid=67451, ip=10.1.0.7) INFO 06-25 15:26:09 selector.py:131] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
(RayWorkerWrapper pid=67451, ip=10.1.0.7) INFO 06-25 15:26:09 selector.py:51] Using XFormers backend.
INFO 06-25 15:26:10 utils.py:637] Found nccl from library libnccl.so.2
INFO 06-25 15:26:10 pynccl.py:63] vLLM is using nccl==2.20.5
(RayWorkerWrapper pid=67451, ip=10.1.0.7) INFO 06-25 15:26:10 utils.py:637] Found nccl from library libnccl.so.2
(RayWorkerWrapper pid=67451, ip=10.1.0.7) INFO 06-25 15:26:10 pynccl.py:63] vLLM is using nccl==2.20.5
WARNING 06-25 15:26:10 custom_all_reduce.py:117] Custom allreduce is disabled because this process group spans across nodes.
INFO 06-25 15:26:10 selector.py:131] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 06-25 15:26:10 selector.py:51] Using XFormers backend.
(RayWorkerWrapper pid=67451, ip=10.1.0.7) WARNING 06-25 15:26:10 custom_all_reduce.py:117] Custom allreduce is disabled because this process group spans across nodes.
(RayWorkerWrapper pid=67451, ip=10.1.0.7) INFO 06-25 15:26:10 selector.py:131] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
(RayWorkerWrapper pid=67451, ip=10.1.0.7) INFO 06-25 15:26:10 selector.py:51] Using XFormers backend.
INFO 06-25 15:26:13 model_runner.py:160] Loading model weights took 7.4829 GB
(RayWorkerWrapper pid=67451, ip=10.1.0.7) INFO 06-25 15:26:16 model_runner.py:160] Loading model weights took 7.4829 GB
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148] Error executing method determine_num_available_blocks. This might cause deadlock in distributed execution.
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148] Traceback (most recent call last):
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/vllm/worker/worker_base.py", line 140, in execute_method
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     return executor(*args, **kwargs)
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]            ^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     return func(*args, **kwargs)
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]            ^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/vllm/worker/worker.py", line 162, in determine_num_available_blocks
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     self.model_runner.profile_run()
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     return func(*args, **kwargs)
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]            ^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 844, in profile_run
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     self.execute_model(seqs, kv_caches)
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     return func(*args, **kwargs)
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]            ^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/vllm/worker/model_runner.py", line 758, in execute_model
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     logits = self.model.compute_logits(hidden_states, sampling_metadata)
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/vllm/model_executor/models/llama.py", line 377, in compute_logits
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     logits = self.logits_processor(self.lm_head.weight, hidden_states,
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     return self._call_impl(*args, **kwargs)
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     return forward_call(*args, **kwargs)
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/vllm/model_executor/layers/logits_processor.py", line 52, in forward
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     logits = self._get_logits(hidden_states, embedding, embedding_bias)
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/vllm/model_executor/layers/logits_processor.py", line 69, in _get_logits
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     logits = tensor_model_parallel_gather(logits)
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/vllm/distributed/communication_op.py", line 24, in tensor_model_parallel_gather
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     return get_tp_group().gather(input_, dst, dim)
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/vllm/distributed/parallel_state.py", line 301, in gather
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     torch.distributed.gather(input_,
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     return func(*args, **kwargs)
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]            ^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]   File "/home/efleisc222/miniconda3/envs/ai/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 3133, in gather
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]     work = group.gather(output_tensors, input_tensors, opts)
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(RayWorkerWrapper pid=67451, ip=10.1.0.7) ERROR 06-25 15:28:30 worker_base.py:148] RuntimeError: NCCL Error 2: unhandled system error (run with NCCL_DEBUG=INFO for details)

**Comment by youkaichao** [comment]
can you follow https://docs.vllm.ai/en/latest/getting_started/debugging.html to dig out the cause of the error?

**Comment by eByteTheDust** [comment]
I solved the problem setting NCCL_SOCKET_IFNAME=eth0 on both ray head and nodes. Now it loads with no errors. P.S.: another error message I found in the log was: _"Error executing method determine_num_available_blocks. This might cause deadlock in distributed execution"_

but again, settting NCCL_SOCKET_IFNAME solved the problem and v0.5.0.post1 loads with no errors.

**Comment by youkaichao** [comment]
glad it works. I just added `NCCL_SOCKET_IFNAME` in https://docs.vllm.ai/en/latest/getting_started/debugging.html
