### ISSUE TITLE
[Performance]: Multi-node Pipeline Parallel double bandwidth, no change in performance

### ISSUE THREAD

**Issue by drikster80** [vllm-project/vllm#6610]
### Misc discussion on performance

I've been running some simple tests on multi-node parallel pipeline with NCCL. I doubled the bandwidth between the nodes but saw no increase in t/s or throughput. I tested with 400Gbps and 800Gbps between nodes and was getting the same t/s, although [nccl-tests](https://github.com/NVIDIA/nccl-tests) showed the 2x bandwidth between GPUs.

## Questions:
1. What would be the bottleneck in multi-node parallel pipelines, if not inter-node connectivity?
2. What other tests or profiling can be done to figure out the bottleneck on parallel pipelines?
3. Are there currently any benchmarks in vllm (such as `benchmark_throughput.py` or `benchmark_latency.py`) that can be run with `--pipeline-parallel-size` (required Async: `Pipeline parallelism is only supported through AsyncLLMEngine as performance will be severely degraded otherwise.`)?

## Environment:
(2) x GH200 nodes (aarch64) - 800Gbps Ethernet between nodes
**Model:** L3-70B-Instruct

## Test 1:

(4)x 200Gbps Connections (800Gbps total)
### NCCL-Test:
Execution Command
```
mpirun -np 2 -host localhost,10.5.6.103 ./build/{all_reduce_perf,all_gather_perf,alltoall_perf} -b 512k -e 1024M -f 2 -g 1
```
NCCL Test (all_reduce_perf):  algbw = 70.83GB/s, busbw = 70.83
NCCL Test (all_gather_perf):  algbw = 137.76GB/s, busbw = 68.88
NCCL Test (alltoall_perf):  algbw = 47.32GB/s, busbw = 23.66

### VLLM Test:
(Using Open WebUI and OpenAI API)
```bash
python -m vllm.entrypoints.openai.api_server --model /models/Meta-Llama-3-70B-Instruct --pipeline-parallel-size 2 --distributed-executor-backend ray
```

Logs:
```
INFO 07-20 15:57:52 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.2%, CPU KV cache usage: 0.0%.
INFO 07-20 15:57:57 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.1 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%.
INFO 07-20 15:58:02 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%.
```

## Test 2:

(2)x 200Gbps Connections (400Gbps total)
### NCCL-Test:
Execution Command
```
mpirun -np 2 -host localhost,10.5.6.103 ./build/{all_reduce_perf,all_gather_perf,alltoall_perf} -b 512k -e 1024M -f 2 -g 1
```
NCCL Test (all_reduce_perf):  algbw = 45.42 GB/s, busbw = 45.42 GB/s
NCCL Test (all_gather_perf):  algbw = 91.32 GB/s, busbw = 45.66  GB/s
NCCL Test (alltoall_perf):  algbw = 49.29 GB/s, busbw = 24.64 GB/s

### VLLM Test:
(Using Open WebUI and OpenAI API)
```bash
python -m vllm.entrypoints.openai.api_server --model /models/Meta-Llama-3-70B-Instruct --pipeline-parallel-size 2 --distributed-executor-backend ray
```

Logs:
```
INFO 07-20 17:44:20 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.3%, CPU KV cache usage: 0.0%.
INFO 07-20 17:44:25 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.4%, CPU KV cache usage: 0.0%.
INFO 07-20 17:44:30 metrics.py:295] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 21.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%.
```
### Start-up Logs showing `nccl==2.21.5` is used during inference.
```
INFO 07-20 17:27:16 api_server.py:212] vLLM API server version 0.5.2
INFO 07-20 17:27:16 api_server.py:213] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], model='/models/Meta-Llama-3-70B-Instruct', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend='ray', worker_use_ray=False, pipeline_parallel_size=2, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', scheduler_delay_factor=0.0, enable_chunked_prefill=False, speculative_model=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, model_loader_extra_config=None, preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
2024-07-20 17:27:16,258 INFO worker.py:1603 -- Connecting to existing Ray cluster at address: 10.5.6.100:6379...
2024-07-20 17:27:16,262 INFO worker.py:1788 -- Connected to Ray cluster.
INFO 07-20 17:27:16 llm_engine.py:174] Initializing an LLM engine (v0.5.2) with config: model='/models/Meta-Llama-3-70B-Instruct', speculative_config=None, tokenizer='/models/Meta-Llama-3-70B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=2, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=/models/Meta-Llama-3-70B-Instruct, use_v2_block_manager=False, enable_prefix_caching=False)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO 07-20 17:27:20 utils.py:737] Found nccl from library libnccl.so.2
INFO 07-20 17:27:20 pynccl.py:63] vLLM is using nccl==2.21.5
(RayWorkerWrapper pid=593, ip=10.5.6.103) INFO 07-20 17:27:20 utils.py:737] Found nccl from library libnccl.so.2
(RayWorkerWrapper pid=593, ip=10.5.6.103) INFO 07-20 17:27:20 pynccl.py:63] vLLM is using nccl==2.21.5
INFO 07-20 17:34:54 model_runner.py:266] Loading model weights took 67.6673 GB
(RayWorkerWrapper pid=593, ip=10.5.6.103) INFO 07-20 17:34:57 model_runner.py:266] Loading model weights took 67.6673 GB
INFO 07-20 17:34:59 distributed_gpu_executor.py:56] # GPU blocks: 6149, # CPU blocks: 1638
INFO 07-20 17:35:00 model_runner.py:1007] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 07-20 17:35:00 model_runner.py:1011] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
(RayWorkerWrapper pid=593, ip=10.5.6.103) INFO 07-20 17:35:00 model_runner.py:1007] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
(RayWorkerWrapper pid=593, ip=10.5.6.103) INFO 07-20 17:35:00 model_runner.py:1011] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
(RayWorkerWrapper pid=593, ip=10.5.6.103) INFO 07-20 17:35:12 model_runner.py:1208] Graph capturing finished in 12 secs.
```

### Current Environment

```text
Collecting environment information...
WARNING 07-20 21:08:09 _custom_ops.py:14] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
/vllm/vllm/usage/usage_lib.py:19: RuntimeWarning: Failed to read commit hash:
No module named 'vllm.commit_id'
  from vllm.version import __version__ as VLLM_VERSION
PyTorch version: 2.4.0a0+f70bd71a48.nv24.06
Is debug build: False
CUDA used to build PyTorch: 12.5
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.3
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-6.8.0-1009-nvidia-64k-aarch64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.5.40
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GH200 480GB
Nvidia driver version: 555.42.06
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.9.1.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv.so.9.1.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn.so.9.1.0
/usr/lib/aarch64-linux-gnu/libcudnn_engines_precompiled.so.9.1.0
/usr/lib/aarch64-linux-gnu/libcudnn_engines_runtime_compiled.so.9.1.0
/usr/lib/aarch64-linux-gnu/libcudnn_graph.so.9.1.0
/usr/lib/aarch64-linux-gnu/libcudnn_heuristic.so.9.1.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops.so.9.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         aarch64
CPU op-mode(s):                       64-bit
Byte Order:                           Little Endian
CPU(s):                               72
On-line CPU(s) list:                  0-71
Vendor ID:                            ARM
Model name:                           Neoverse-V2
Model:                                0
Thread(s) per core:                   1
Core(s) per cluster:                  72
Socket(s):                            -
Cluster(s):                           1
Stepping:                             r0p0
Frequency boost:                      disabled
CPU max MHz:                          3483.0000
CPU min MHz:                          81.0000
BogoMIPS:                             2000.00
Flags:                                fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp sve2 sveaes svepmull svebitperm svesha3 svesm4 flagm2 frint svei8mm svebf16 i8mm bf16 dgh bti
L1d cache:                            4.5 MiB (72 instances)
L1i cache:                            4.5 MiB (72 instances)
L2 cache:                             72 MiB (72 instances)
L3 cache:                             114 MiB (1 instance)
NUMA node(s):                         9
NUMA node0 CPU(s):                    0-71
NUMA node1 CPU(s):
NUMA node2 CPU(s):
NUMA node3 CPU(s):
NUMA node4 CPU(s):
NUMA node5 CPU(s):
NUMA node6 CPU(s):
NUMA node7 CPU(s):
NUMA node8 CPU(s):
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Not affected
Vulnerability Spectre v1:             Mitigation; __user pointer sanitization
Vulnerability Spectre v2:             Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==1.24.4
[pip3] onnx==1.16.0
[pip3] optree==0.11.0
[pip3] pytorch-quantization==2.1.2
[pip3] pytorch-triton==3.0.0+989adb9a2
[pip3] torch==2.4.0a0+f70bd71a48.nv24.6
[pip3] torch-tensorrt==2.4.0a0
[pip3] torchvision==0.19.0a0
[pip3] transformers==4.42.4
[pip3] triton==3.0.0
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.2
vLLM Build Flags:
CUDA Archs: 9.0+PTX; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    NIC0    NIC1    NIC2    NIC3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     SYS     SYS     SYS     0-71    0               1
NIC0    SYS      X      PIX     SYS     SYS
NIC1    SYS     PIX      X      SYS     SYS
NIC2    SYS     SYS     SYS      X      PIX
NIC3    SYS     SYS     SYS     PIX      X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3

```

**Comment by youkaichao** [comment]
you can use https://github.com/vllm-project/vllm/blob/main/benchmarks/benchmark_serving.py to benchmark the performance.

how do you double the bandwidth? if it is some infiniband or roce network, make sure NCCL is using it correctly

**Comment by drikster80** [comment]
Doubled bandwidth by adding an additional bluefield-3 card to each server.

I'll mess with the `benchmark_serving.py` and see if I can get more thorough test results.

Network is a RoCE and validated all infiniband tests and NCCL worked as expected. VLLM shows the use of nccl correctly:
```
INFO 07-20 17:27:20 pynccl.py:63] vLLM is using nccl==2.21.5
(RayWorkerWrapper pid=593, ip=10.5.6.103) INFO 07-20 17:27:20 utils.py:737] Found nccl from library libnccl.so.2
(RayWorkerWrapper pid=593, ip=10.5.6.103) INFO 07-20 17:27:20 pynccl.py:63] vLLM is using nccl==2.21.5
```

I'm also running inside of docker container (required for aarch64). Not sure if that has affect on bandwidth.

**Comment by youkaichao** [comment]
use `export NCCL_DEBUG=TRACE` to see nccl information. chances are rdma is not used, and nccl is still using socket.

**Comment by drikster80** [comment]
Thanks for the tip!! You were right that IB wasn't being used and NCCL was using socket.
Setting `--privileged` for the container solved that. However, I'm still seeing the same throughput. I'll do some more testing and report back if I figure out some more optimizations.

Cheers.

**Comment by drikster80** [comment]
Old ticket that I opened and can now be closed.

The original issue came from a misunderstanding of pipeline-parallel vs tensor-parallel. When using pipeline-parallelism, adding additional bandwidth would have no effect. The solution was to use tensor-parallel instead, which significantly increased throughput with additional bandwidth.
