### ISSUE TITLE
[Bug]: Broken accuracy on LLaMa 3.1 70B -- worse than even 8B

### ISSUE THREAD

**Issue by pseudotensor** [vllm-project/vllm#6760]
### Your current environment

4*H100 for 70Bs or for 8B 1*H100

Docker 0.5.3.post1 for both, ran like:

```
docker pull vllm/vllm-openai:latest
docker run -d --restart=always \
    --runtime=nvidia \
    --gpus '"device=4,5,6,7"' \
    --shm-size=10.24gb \
    -p 5020:5020 \
        -e NCCL_IGNORE_DISABLED_P2P=1 \
    -e HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN \
    -e VLLM_NCCL_SO_PATH=/usr/local/lib/python3.10/dist-packages/nvidia/nccl/lib/libnccl.so.2 \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -u `id -u`:`id -g` \
    -v "${HOME}"/.cache:$HOME/.cache/ -v "${HOME}"/.config:$HOME/.config/   -v "${HOME}"/.triton:$HOME/.triton/  \
    --network host \
    --name llama31-70b \
    vllm/vllm-openai:latest \
        --port=5020 \
        --host=0.0.0.0 \
        --model=meta-llama/Meta-Llama-3.1-70B-Instruct \
        --seed 1234 \
        --tensor-parallel-size=4 \
        --max-model-len=131072 \
        --max-num-batched-tokens=131072 --max-log-len=100 \
        --served-model-name meta-llama/Meta-Llama-3.1-70B-Instruct meta-llama/Meta-Llama-3-70B-Instruct \
        --download-dir=$HOME/.cache/huggingface/hub &>> logs.vllm_server.llama31.txt
```
and for 8B:
```
docker pull vllm/vllm-openai:latest
docker run -d --restart=always \
    --runtime=nvidia \
    --gpus '"device=0"' \
    --shm-size=10.24gb \
    -p 5000:5000 \
        -e NCCL_IGNORE_DISABLED_P2P=1 \
    -e HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN \
    -e VLLM_NCCL_SO_PATH=/usr/local/lib/python3.10/dist-packages/nvidia/nccl/lib/libnccl.so.2 \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -u `id -u`:`id -g` \
    -v "${HOME}"/.cache:$HOME/.cache/ -v "${HOME}"/.config:$HOME/.config/   -v "${HOME}"/.triton:$HOME/.triton/  \
    --network host \
    --name llama31_8b \
    vllm/vllm-openai:latest \
        --port=5000 \
        --host=0.0.0.0 \
        --model=meta-llama/Meta-Llama-3.1-8B-Instruct \
        --seed 1234 \
        --tensor-parallel-size=1 \
        --max-model-len=131072 \
        --max-num-batched-tokens=131072 --max-log-len=100 \
        --served-model-name meta-llama/Meta-Llama-3.1-8B-Instruct meta-llama/Meta-Llama-3-8B-Instruct \
        --download-dir=$HOME/.cache/huggingface/hub &>> logs.vllm_server.llama3-8b.txt
```

and for good measure, we tried TGI that only didn't fail up to 32K:
```
docker stop llama31-70b-tgi ; docker remove llama31-70b-tgi
source ~/h2ogpt_ops/gr_exports.sh
sudo docker run -d --restart=always --gpus '"device=0,1,2,3"' \
             --shm-size 10.24gb \
             -e HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN \
             -e TRANSFORMERS_CACHE="/.cache/" -p \
             5005:80 \
             -v $HOME/.cache:/.cache/ \
             -v $HOME/.cache/huggingface/hub/:/data \
             --name llama31-70b-tgi \
             ghcr.io/huggingface/text-generation-inference:2.2.0 \
             --model-id meta-llama/Meta-Llama-3.1-70B-Instruct \
             --max-input-length 32768 \
             --max-total-tokens 40960 \
              --max-stop-sequences 6 \
              --num-shard 4 --sharded true &>> logs.llama3.1-70b.tgi.txt
```

### 🐛 Describe the bug

Then ran the attached script:
[llama70b_issue1_posted.py.zip](https://github.com/user-attachments/files/16367794/llama70b_issue1_posted.py.zip)

One gets for 70B:
```
$174,870
$174,870
```
for TGI:
```
$174,870
Long-term debt at the end of 2022 was $174,870 million.
```
and for 8B:
```
According to Table 10.1 on page 141 of the document, the total long-term debt at the end of 2022 was $174,870 million.
According to Table 10.2 on page 142 of the document, the total long-term debt as of December 31, 2022, is $174,870 million.
```

If we run same for old llama 3 70B, they are more like llama 3.1 8B.  The very brief answer is quite odd.

We have been tracking RAG performance for about a year now with many models, cycling all the time.  Here is a brief run of a subset of models and shows how 3.1 70B is doing much worse:

![image](https://github.com/user-attachments/assets/3d7e2f81-8660-41b6-88e6-ecb97b432c2d)

The issue is that the model seems to be responding overly briefly quite commonly, and when it does it gets a wrong answer.

Now this isn't just a vLLM issue but also TGI shows this.  I presume direct HF transformers would show too.  However, I presume updates are often taken from HF transformers, so all stuff could be broken due to some bug.

So possibilities:

* llama 70B 3.1 is busted for RAG -- seems most possible, but disappointing
* multi-GPU is busted for vLLM and TGI -- seems unlikely both would be same issues
* model card related things are broken (but I compared 8B and 70B and all match except for arch differences in config.json)

I'll x-post this on transformers.

**Comment by pseudotensor** [comment]
One can also reduce the prompt to the only relevant part and still can happen.  As I reduce, it can sometimes respond "normally" with "According to..." but many times not.  i.e. this prompt:
```
prompt = """Pay attention and remember the information below. You will need to use only any chat history, any images given, or any document text in order to answer the question or imperative at the end.
<all_documents>
<doc>
<name>wellsfargo-2022-annual-report.pdf</name>
<page>142</page>
<text>
Note 10: Long-Term Debt (continued)
(continued from previous page)
December 31,
2022
2021
(in millions)
Maturity
date(s)
Stated
interest rate(s)
Other consolidated su
bsidiaries
Senior
Fixed-rate
notes
2023
3.46%
$
369
398
Structured
notes
(1)
911
1,147
Total
long-term
debt
–
Other
consolidated
subsidiaries
1,280
1,545
Total
long-term
debt
(6)
$
174,870
160,689
(1)
Includes certain structured notes that have coupon or repayment terms linked to the performance of debt or equity securities, an embedded equity, commodity, or currency index, or basket of
indices, for which the maturity may be accelerated based on the value of a referenced index or security. In addition, a major portion consists of zero coupon notes where interest is paid as part of the
final redemption amount.
(2)
Includes fixed-rate subordinated notes issued by the Parent at a discount of $121 million and $123 million at December 31, 2022 and 2021, respectively, and debt issuance costs of $2 million at both
December 31, 2022 and 2021, to effect a modification of Wells Fargo Bank, N.A., notes. These subordinated notes are carried at their par amount on the consolidated balance sheet of the Parent
presented in Note 26 (Parent-Only Financial Statements).
</text>
</doc>

<doc>
<name>wellsfargo-2022-annual-report.pdf</name>
<page>61</page>
<text>
We issue long-term debt in a variety of maturities and currenci
es
to achieve cost-efficient funding and to maintain an appropriat
e
maturity profile. Proceeds from securities issued were used fo
r
general corporate purposes unless otherwise specified in the
applicable prospectus or prospectus supplement, and we expect
the
proceeds
from securities issued in the future will be used for
the same purposes. Depending on market conditions and our
liquidity position, we may redeem or repurchase, and
subsequently retire, our outstanding debt securities in privately
negotiated or open market transactions, by tender offer, or
otherwise.
Table 37
presents a summary of our long-term debt. For
additional information on our long-term debt, including
contractual maturities, see
Note 10
(Long-Term Debt
), and for
information on the classification of our long-term debt, see
Note
1 (
Summary of Significant Accounting Policies
) to Financial
Statements
in this Report
.
Table 37: Long-Term Debt
(in millions)
December 31, 2022
December 31, 2021
Wells Fargo & Company (Parent Only)
$
134,401
146,286
Wells Fargo Bank, N.A., and other bank entities (Bank) (1)
39,189
12,858
Other consolidated subsidiaries
1,280
1,545
Total
$
174,870
160,689
(1)
Includes $27.0 billion and $0 of FHLB advances at December 31, 2022 and 2021, respectively.
</text>
</doc>

<doc>
<name>wellsfargo-2022-annual-report.pdf</name>
<page>142</page>
<text>
Table 10.2: Maturity of Long-Term Debt
December 31, 2022
(in millions)
2023
2024
2025
2026
2027
Thereafter
Total
Wells Fargo & Company (Parent Only)
Senior debt
$
3,712
11,116
14,030
23,189
7,392
52,413
111,852
Subordinated debt
2,620
702
951
2,631
2,343
12,132
21,379
Junior subordinated debt
—
—
—
—
343
827
1,170
Total long-term debt – Parent
6,332
11,818
14,981
25,820
10,078
65,372
134,401
Wells Fargo Bank, N.A., and other bank entities (Bank)
Senior debt
10,003
17,003
176
82
3
134
27,401
Subordinated debt
894
—
149
—
27
3,235
4,305
Junior subordinated debt
—
—
—
—
401
—
401
Other bank debt
2,815
1,613
488
163
54
1,949
7,082
Total long-term debt – Bank
13,712
18,616
813
245
485
5,318
39,189
Other consolidated subsidiaries
Senior debt
463
86
413
222
—
96
1,280
Total long-term debt – Other consolidated subsidiaries
463
86
413
222
—
96
1,280
Total long-term debt
$
20,507
30,520
16,207
26,287
10,563
70,786
174,870
As part of
</text>
</doc>
</all_documents>
According to only the information in any chat history, any images given, or any document text provided within the context above, 
What was long-term debt at the end of 2022?"""
```

still can easily give for llama3.1 70b:
```
$174,870
$174,870
```

Just really stupid model or bug.

**Comment by pseudotensor** [comment]
I can also prefill the assistant prompt, so it at least heads in right direction.  But about 1/4 times the response is really bad, like:
```
messages = [
    {
        "role": "user",
        "content": prompt,
    },
    {
        "role": "assistant",
        "content": 'According to',
    }
]
```

gives:

```
able 10.1: Long-Term Debt, the total long-term debt at the end of 2022 was $174,870 million.
<doc>
<name>wellsfargo-2022-annual-report.pdf</name>
<page>67</page>
<text>
Table 49: Components Used to Calculate TLAC and Eligible Unsecured
Long-Term Debt Requirements
TLAC requirement
Greater of:
7.50%
of
total
leverage
exposure
(the
denominator
of
the
SLR
calculation)
+
External
TLAC
leverage
buffer
(equal
to
2.00%
of
total
leverage
exposure)
18.00%
of
RWAs
+
TLAC
buffer
(equal
to
2.50%
of
RWAs
+
method
one
G-SIB
capital
surcharge
+
any
countercyclical
buffer)
Minimum amount of eligible unsecured long-term debt
Greater of:
6.00%
of
RWAs
+
Greater
of
method
one
and
method
two
G-SIB
capital
surcharge
4.50% of total leverage exposure
Under the Proposed SLR rules, the 2.00% external TLAC
leverage buffer would be replaced with a buffer equal to one-half
of our applicable G-SIB capital surcharge, and the leverage
component for calculating the minimum amount of eligible
unsecured long-term debt would be modified from 4.50% of
total leverage exposure to 2.50% of total leverage exposure plus
one-half of our applicable G-SIB capital surcharge.
Table 50
provides our TLAC and eligible unsecured long
-
term debt and related ratios.
</text>
</doc>
```

Just spews back much of the input.

**Comment by pseudotensor** [comment]
One can run a repeat test of the prompt, and while it varies, 8B always gets the right answer with "million" part, e.g. `$174,870 million` while 70B gets it right only 1/20th of the time, most of the time no units and sometimes "billion" instead.

**Comment by pseudotensor** [comment]
But prefilling for 8B always works, it responds normally.

But prefilling for 70B is always odd with just the number `$174,870` most of the time.  makes no sense.

**Comment by pseudotensor** [comment]
I'll close vLLM issue for now, since TGI does it to, so more issue for HF or Meta, or one has to aggressively prompt for llama 70b.

**Comment by robertgshaw2-neuralmagic** [comment]
Note - this issue was resolved by https://github.com/vllm-project/vllm/pull/9549/files

**Comment by pseudotensor** [comment]
Interesting, how did you connect that bug fix to this issue?
