### ISSUE TITLE
[Bug]:  error: Segmentation fault(SIGSEGV received at time)

### ISSUE THREAD

**Issue by Archmilio** [vllm-project/vllm#6918]
### Your current environment

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-25-generic-x86_64-with-glibc2.35
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration:
GPU 0: NVIDIA H100 80GB HBM3
GPU 1: NVIDIA H100 80GB HBM3
GPU 2: NVIDIA H100 80GB HBM3
GPU 3: NVIDIA H100 80GB HBM3
GPU 4: NVIDIA H100 80GB HBM3
GPU 5: NVIDIA H100 80GB HBM3
GPU 6: NVIDIA H100 80GB HBM3
GPU 7: NVIDIA H100 80GB HBM3

Nvidia driver version: 535.86.10
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   52 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          96
On-line CPU(s) list:             0-95
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8468
CPU family:                      6
Model:                           143
Thread(s) per core:              1
Core(s) per socket:              48
Socket(s):                       2
Stepping:                        8
CPU max MHz:                     2100.0000
CPU min MHz:                     800.0000
BogoMIPS:                        4200.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr avx512_fp16 flush_l1d arch_capabilities
L1d cache:                       4.5 MiB (96 instances)
L1i cache:                       3 MiB (96 instances)
L2 cache:                        192 MiB (96 instances)
L3 cache:                        210 MiB (2 instances)
NUMA node(s):                    8
NUMA node0 CPU(s):               0-11
NUMA node1 CPU(s):               12-23
NUMA node2 CPU(s):               24-35
NUMA node3 CPU(s):               36-47
NUMA node4 CPU(s):               48-59
NUMA node5 CPU(s):               60-71
NUMA node6 CPU(s):               72-83
NUMA node7 CPU(s):               84-95
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] transformers==4.42.3
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: N/A
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6    NIC7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NV18    NV18    NV18    NV18    NV18    NV18    PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS     0-11    0               N/A
GPU1    NV18     X      NV18    NV18    NV18    NV18    NV18    NV18    PXB     SYS     SYS     SYS     SYS     SYS     SYS     SYS     0-11    0               N/A
GPU2    NV18    NV18     X      NV18    NV18    NV18    NV18    NV18    SYS     PIX     PIX     PXB     SYS     SYS     SYS     SYS     24-35   2               N/A
GPU3    NV18    NV18    NV18     X      NV18    NV18    NV18    NV18    SYS     PXB     PXB     PIX     SYS     SYS     SYS     SYS     24-35   2               N/A
GPU4    NV18    NV18    NV18    NV18     X      NV18    NV18    NV18    SYS     SYS     SYS     SYS     PIX     PIX     PXB     SYS     48-59   4               N/A
GPU5    NV18    NV18    NV18    NV18    NV18     X      NV18    NV18    SYS     SYS     SYS     SYS     PXB     PXB     PIX     SYS     48-59   4               N/A
GPU6    NV18    NV18    NV18    NV18    NV18    NV18     X      NV18    SYS     SYS     SYS     SYS     SYS     SYS     SYS     PXB     72-83   6               N/A
GPU7    NV18    NV18    NV18    NV18    NV18    NV18    NV18     X      SYS     SYS     SYS     SYS     SYS     SYS     SYS     PIX     72-83   6               N/A
NIC0    PIX     PXB     SYS     SYS     SYS     SYS     SYS     SYS      X      SYS     SYS     SYS     SYS     SYS     SYS     SYS
NIC1    SYS     SYS     PIX     PXB     SYS     SYS     SYS     SYS     SYS      X      PIX     PXB     SYS     SYS     SYS     SYS
NIC2    SYS     SYS     PIX     PXB     SYS     SYS     SYS     SYS     SYS     PIX      X      PXB     SYS     SYS     SYS     SYS
NIC3    SYS     SYS     PXB     PIX     SYS     SYS     SYS     SYS     SYS     PXB     PXB      X      SYS     SYS     SYS     SYS
NIC4    SYS     SYS     SYS     SYS     PIX     PXB     SYS     SYS     SYS     SYS     SYS     SYS      X      PIX     PXB     SYS
NIC5    SYS     SYS     SYS     SYS     PIX     PXB     SYS     SYS     SYS     SYS     SYS     SYS     PIX      X      PXB     SYS
NIC6    SYS     SYS     SYS     SYS     PXB     PIX     SYS     SYS     SYS     SYS     SYS     SYS     PXB     PXB      X      SYS
NIC7    SYS     SYS     SYS     SYS     SYS     SYS     PXB     PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
  NIC4: mlx5_4
  NIC5: mlx5_5
  NIC6: mlx5_6
  NIC7: mlx5_7

### 🐛 Describe the bug

(RayWorkerWrapper pid=5993) *** SIGSEGV received at time=1722289279 on cpu 61 ***
(RayWorkerWrapper pid=5993) PC: @     0x7f0c73d2944a  (unknown)  addProxyOpIfNeeded()
(RayWorkerWrapper pid=5993)     @     0x7f3c7fab6090  1954032864  (unknown)
(RayWorkerWrapper pid=5993)     @                0xd        240  (unknown)
(RayWorkerWrapper pid=5993)     @        0x100000001  (unknown)  (unknown)
(RayWorkerWrapper pid=5993)     @     0x7f0c6ed5a2f0  (unknown)  (unknown)
(RayWorkerWrapper pid=5993)     @ 0x4f3625ff0c74321c  (unknown)  (unknown)
(RayWorkerWrapper pid=5993) [2024-07-29 21:41:19,242 E 5993 5993] logging.cc:440: *** SIGSEGV received at time=1722289279 on cpu 61 ***
(RayWorkerWrapper pid=5993) [2024-07-29 21:41:19,242 E 5993 5993] logging.cc:440: PC: @     0x7f0c73d2944a  (unknown)  addProxyOpIfNeeded()
(RayWorkerWrapper pid=5993) [2024-07-29 21:41:19,243 E 5993 5993] logging.cc:440:     @     0x7f3c7fab6090  1954032864  (unknown)
(RayWorkerWrapper pid=5993) [2024-07-29 21:41:19,244 E 5993 5993] logging.cc:440:     @                0xd        240  (unknown)
(RayWorkerWrapper pid=5993) [2024-07-29 21:41:19,247 E 5993 5993] logging.cc:440:     @        0x100000001  (unknown)  (unknown)
(RayWorkerWrapper pid=5993) [2024-07-29 21:41:19,248 E 5993 5993] logging.cc:440:     @     0x7f0c6ed5a2f0  (unknown)  (unknown)
(RayWorkerWrapper pid=5993) [2024-07-29 21:41:19,249 E 5993 5993] logging.cc:440:     @ 0x4f3625ff0c74321c  (unknown)  (unknown)
(RayWorkerWrapper pid=5993) Fatal Python error: Segmentation fault
(RayWorkerWrapper pid=5993)
(RayWorkerWrapper pid=5993) Stack (most recent call first):
(RayWorkerWrapper pid=5993)   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl_wrapper.py", line 257 in ncclAllReduce
(RayWorkerWrapper pid=5993)   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl.py", line 118 in all_reduce
(RayWorkerWrapper pid=5993)   File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 312 in all_reduce
(RayWorkerWrapper pid=5993)
(RayWorkerWrapper pid=5993) Extension modules: msgpack._cmsgpack, google._upb._message, psutil._psutil_linux, psutil._psutil_posix, setproctitle, yaml._yaml, charset_normalizer.md, uvloop.loop, ray._raylet, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, sentencepiece._sentencepiece, multidict._multidict, yarl._quoting_c, aiohttp._helpers, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket, frozenlist._frozenlist, pyarrow.lib, pyarrow._json, PIL._imaging, zmq.backend.cython._zmq (total: 41)

I am testing llama3.1 405b in a Multi-Node Multi-GPU (tensor parallel plus pipeline parallel inference) environment. The engine runs properly with tensor parallel size set to 8 and pipeline parallel size set to 2, but timeouts or segmentation faults occur when the tensor parallel size is set to 16. Can you identify the cause of this issue?

**Comment by liurupeng** [comment]
+1, we have the seen the similar issue. We deployed a Ray cluster on 2 GPU nodes with pp as 2 and tp as 8. Anyone knows how to fix this? thanks!

**Comment by Edwinhr716** [comment]
+1, I also was able to replicate the same issue, but with meta-llama/Meta-Llama-3-70B instead. 
My setup includes 2GPU Nodes, 4xA100 each, 8tp. 

Might be related to using A100. I was able to deploy meta-llama/Meta-Llama-3-70B on a setup of 8GPU Nodes, 1xL4 each, 8tp without any issues.

**Comment by MFajcik** [comment]
It seems enforcing eager mode with `enforce_eager=True` helped in my case as a workaround. I was able to run 70b models.

**Comment by MFajcik** [comment]
I was also able to run 405b llama31 like that (64x tp).

**Comment by robinren03** [comment]
> I was also able to run 405b llama31 like that (64x tp, 8 nodes).

Out of curious, what GPU do you run on in this case? @MFajcik

**Comment by MFajcik** [comment]
> > I was also able to run 405b llama31 like that (64x tp, 8 nodes).
> 
> Out of curious, what GPU do you run on in this case? @MFajcik


8 nodes, 8xA100 40G each

**Comment by raffenet** [comment]
> It seems enforcing eager mode with `enforce_eager=True` helped in my case as a workaround. I was able to run 70b models.

I was also able to workaround segfaults in my setup by setting `enforce_eager=True`. 2 nodes, each with 8x A100 GPUs and 12x ConnectX-6 ports.

**Comment by BrennanCode1** [comment]
Enforce eager did not work for me ):

**Comment by akhil-k-m** [comment]
I am having error for llama 3.1 405B FP-8
I tested - " vllm serve meta-llama/Llama-3.1-405B-Instruct-FP8 --tensor-parallel-size 8 "
on 8xA100 - 80 gb and it worked fine
but on 8xH100 - 80gb it shows - "RuntimeError: Engine process failed to start. See stack trace for the root cause."

i tried running by
from vllm import LLM, SamplingParams
from transformers import AutoTokenizer

model_id = "meta-llama/Llama-3.1-405B-Instruct-FP8"
number_gpus = 8

sampling_params = SamplingParams(temperature=0.6, top_p=0.9, max_tokens=256)

tokenizer = AutoTokenizer.from_pretrained(model_id)

messages = [
{"role": "system", "content": "You are a pirate chatbot who always responds in pirate speak!"},
{"role": "user", "content": "Who are you?"},
]

prompts = tokenizer.apply_chat_template(messages, add_generation_prompt=True, tokenize=False)

llm = LLM(model=model_id, tensor_parallel_size=number_gpus, max_model_len=4096)

But got the error as "segmentation fault".

Anyone who can help ?

**Comment by rothn** [comment]
I'm having this problem, specifically on Dockerfile.cpu. I also commented on https://github.com/vllm-project/vllm/issues/11715 , which appears to be related
