### ISSUE TITLE
[Bug]: Distributed inference with Ray: cuda errors if I import torch

### ISSUE THREAD

**Issue by denadai2** [vllm-project/vllm#7013]
### Your current environment

(cuda is not available here below because I run it in the driver node, without cuda)

```text
PyTorch version: 2.3.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.0
Libc version: glibc-2.35

Python version: 3.10.14 (main, Mar 21 2024, 16:24:04) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.1.85+-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        46 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               32
On-line CPU(s) list:                  0-31
Vendor ID:                            GenuineIntel
Model name:                           Intel(R) Xeon(R) CPU @ 2.00GHz
CPU family:                           6
Model:                                85
Thread(s) per core:                   2
Core(s) per socket:                   16
Socket(s):                            1
Stepping:                             3
BogoMIPS:                             3999.99
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities
Hypervisor vendor:                    KVM
Virtualization type:                  full
L1d cache:                            512 KiB (16 instances)
L1i cache:                            512 KiB (16 instances)
L2 cache:                             16 MiB (16 instances)
L3 cache:                             38.5 MiB (1 instance)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-31
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Mitigation; PTE Inversion
Vulnerability Mds:                    Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:               Mitigation; PTI
Vulnerability Mmio stale data:        Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Mitigation; IBRS
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; IBRS; IBPB conditional; STIBP conditional; RSB filling; PBRSB-eIBRS Not affected; BHI SW loop, KVM SW loop
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Mitigation; Clear CPU buffers; SMT Host state unknown

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy==1.10.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] optree==0.11.0
[pip3] sentence-transformers==2.7.0
[pip3] torch==2.3.1
[pip3] torch-tb-profiler==0.4.3
[pip3] torchaudio==2.3.0
[pip3] torchelastic==0.2.2
[pip3] torchvision==0.18.1
[pip3] transformers==4.43.1
[pip3] triton==2.3.1
[pip3] tritonclient==2.41.1
[pip3] vector-quantize-pytorch==1.15.2
[conda] blas                      1.0                         mkl
[conda] libjpeg-turbo             2.0.0                h9bf148f_0    pytorch
[conda] mkl                       2023.1.0         h213fc3f_46344
[conda] mkl-service               2.4.0           py310h5eee18b_1
[conda] mkl_fft                   1.3.8           py310h5eee18b_0
[conda] mkl_random                1.2.4           py310hdb19cb5_0
[conda] numpy                     1.26.4          py310h5f9d8c6_0
[conda] numpy-base                1.26.4          py310hb5e798b_0
[conda] optree                    0.11.0                   pypi_0    pypi
[conda] pytorch                   2.3.0           py3.10_cuda12.1_cudnn8.9.2_0    pytorch
[conda] pytorch-cuda              12.1                 ha16c6d3_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.3.0               py310_cu121    pytorch
[conda] torchelastic              0.2.2                    pypi_0    pypi
[conda] torchtriton               2.3.0                     py310    pytorch
[conda] torchvision               0.18.0              py310_cu121    pytorch
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.3.post1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
Could not collect
```

### 🐛 Describe the bug

I found out a weird bug on the example https://github.com/vllm-project/vllm/blob/main/examples/offline_inference_distributed.py. If I just import torch and call e.g. `torch.cuda.is_available()` in the constructor of the predictor, I get

```
(_MapWorker pid=158704, ip=10.169.4.72) ERROR 07-31 23:10:15 worker_base.py:382] Error executing method init_device. This might cause deadlock in distributed execution.
(_MapWorker pid=158704, ip=10.169.4.72) ERROR 07-31 23:10:15 worker_base.py:382] Traceback (most recent call last):
(_MapWorker pid=158704, ip=10.169.4.72) ERROR 07-31 23:10:15 worker_base.py:382]   File "/home/ray/.local/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 374, in execute_method
(_MapWorker pid=158704, ip=10.169.4.72) ERROR 07-31 23:10:15 worker_base.py:382]     return executor(*args, **kwargs)
(_MapWorker pid=158704, ip=10.169.4.72) ERROR 07-31 23:10:15 worker_base.py:382]   File "/home/ray/.local/lib/python3.10/site-packages/vllm/worker/worker.py", line 123, in init_device
(_MapWorker pid=158704, ip=10.169.4.72) ERROR 07-31 23:10:15 worker_base.py:382]     torch.cuda.set_device(self.device)
(_MapWorker pid=158704, ip=10.169.4.72) ERROR 07-31 23:10:15 worker_base.py:382]   File "/home/ray/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 399, in set_device
(_MapWorker pid=158704, ip=10.169.4.72) ERROR 07-31 23:10:15 worker_base.py:382]     torch._C._cuda_setDevice(device)
(_MapWorker pid=158704, ip=10.169.4.72) ERROR 07-31 23:10:15 worker_base.py:382]   File "/home/ray/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 293, in _lazy_init
(_MapWorker pid=158704, ip=10.169.4.72) ERROR 07-31 23:10:15 worker_base.py:382]     torch._C._cuda_init()
(_MapWorker pid=158704, ip=10.169.4.72) ERROR 07-31 23:10:15 worker_base.py:382] RuntimeError: No CUDA GPUs are available
(_MapWorker pid=158704, ip=10.169.4.72) Exception ignored in: <function RayGPUExecutor.__del__ at 0x7f7591e549d0>
(_MapWorker pid=158704, ip=10.169.4.72) Traceback (most recent call last):
(_MapWorker pid=158704, ip=10.169.4.72)   File "/home/ray/.local/lib/python3.10/site-packages/vllm/executor/ray_gpu_executor.py", line 396, in __del__
(_MapWorker pid=158704, ip=10.169.4.72)     if self.forward_dag is not None:
(_MapWorker pid=158704, ip=10.169.4.72) AttributeError: 'RayGPUExecutor' object has no attribute 'forward_dag'
```
It is a blocker for me :(

Reproducible script:

```
"""
This example shows how to use Ray Data for running offline batch inference
distributively on a multi-nodes cluster.

Learn more about Ray Data in https://docs.ray.io/en/latest/data/data.html
"""

from typing import Any, Dict, List

import numpy as np
import ray
from packaging.version import Version
from ray.util.scheduling_strategies import PlacementGroupSchedulingStrategy

assert Version(ray.__version__) >= Version(
    "2.22.0"), "Ray version must be at least 2.22.0"


# Set tensor parallelism per instance.
tensor_parallel_size = 2

# Set number of instances. Each instance will use tensor_parallel_size GPUs.
num_instances = 1

# Create a class to do batch inference.
class LLMPredictor:

    def __init__(self, tensor_parallel_size):
        # Create an LLM.
        import torch
        torch.cuda.is_available()
        from vllm import LLM
        self.llm = LLM(model="/data/prolific-models/exported/prism_v3_1B/mdenadai/20240716_it_search_only/tiny_llama2_chat_1.1b",
                       tensor_parallel_size=tensor_parallel_size)

    def __call__(self, batch: Dict[str, np.ndarray], b=2) -> Dict[str, list]:
        # Generate texts from the prompts.
        # The output is a list of RequestOutput objects that contain the prompt,
        # generated text, and other information.
        # Create a sampling params object.
        from vllm import SamplingParams

        sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
        outputs = self.llm.generate(batch["item"], sampling_params)
        prompt: List[str] = []
        generated_text: List[str] = []
        for output in outputs:
            prompt.append(output.prompt)
            generated_text.append(' '.join([o.text for o in output.outputs]))
        return {
            "prompt": prompt,
            "generated_text": generated_text,
        }


# Read one text file from S3. Ray Data supports reading multiple files
# from cloud storage (such as JSONL, Parquet, CSV, binary format).
ds = ray.data.from_items(["1"] * 1000)


# For tensor_parallel_size > 1, we need to create placement groups for vLLM
# to use. Every actor has to have its own placement group.
def scheduling_strategy_fn():
    # One bundle per tensor parallel worker
    pg = ray.util.placement_group(
        [{
            "GPU": 1,
            "CPU": 1
        }] * tensor_parallel_size,
        strategy="STRICT_PACK",
    )
    return dict(scheduling_strategy=PlacementGroupSchedulingStrategy(
        pg, placement_group_capture_child_tasks=True))


resources_kwarg: Dict[str, Any] = {}
if tensor_parallel_size == 1:
    # For tensor_parallel_size == 1, we simply set num_gpus=1.
    resources_kwarg["num_gpus"] = 1
else:
    # Otherwise, we have to set num_gpus=0 and provide
    # a function that will create a placement group for
    # each instance.
    resources_kwarg["num_gpus"] = 0
    resources_kwarg["ray_remote_args_fn"] = scheduling_strategy_fn

# Apply batch inference for all input data.
ds = ds.map_batches(
    LLMPredictor,
    # Set the concurrency to the number of LLM instances.
    concurrency=num_instances,
    # Specify the batch size for inference.
    batch_size=32,
    fn_constructor_kwargs={"tensor_parallel_size": tensor_parallel_size},
    fn_kwargs={"b": 3},
    batch_format="pandas",
    **resources_kwarg,
)

# Peek first 10 results.
# NOTE: This is for local testing and debugging. For production use case,
# one should write full result out as shown below.
outputs = ds.take(limit=10)
for output in outputs:
    prompt = output["prompt"]
    generated_text = output["generated_text"]
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")

# Write inference output data out as Parquet files to S3.
# Multiple files would be written to the output destination,
# and each task would write one or more files separately.
#
# ds.write_parquet("s3://<your-output-bucket>")
```

thx for your help :(

**Comment by youkaichao** [comment]
cc @richardliaw @rkooo567

**Comment by rkooo567** [comment]
NOTE: `(_MapWorker pid=158704, ip=10.169.4.72) AttributeError: 'RayGPUExecutor' object has no attribute 'forward_dag'
` -> this error message should be fixed in the master. But the main issue is `RuntimeError: No CUDA GPUs are available`. 

actually we've faced this issue before in our internal deployment. https://github.com/pytorch/pytorch/blob/63d5e9221bedd1546b7d364b5ce4171547db12a9/torch/cuda/__init__.py#L742 this caches the device count value. The issue is your torch import & usage of `torch.cuda.is_available()` creates cuda context, and they are created before CUDA_VISIBLE_DEVICES are set by vllm. Because CUDA_VISIBLE_DEVICES is not set, `torch.cuda.is_available()` caches 0 GPU, and you are seeing that error message. 

This issue is fixed in the torch master, so when we upgraded torch, it won't happen anymore. https://github.com/pytorch/pytorch/blob/bdd83c4c7f1ede5f528ffc49ee8eb348f20a26bd/torch/cuda/__init__.py#L891. For the short term, you probably should resolve it by avoiding to import torch modules before initializing vllm.

**Comment by denadai2** [comment]
oh thanks for the prompt answer!! That makes sense.

> For the short term, you probably should resolve it by avoiding to import torch modules before initializing vllm.

Unfortunately I cannot do this. I mean, I import vllm inside the LLMPredictor init. There, I can do it as first thing. However, I import torch outside the Ray Actor, so it takes precedence. Is there a "trick" another trick? :(

**Comment by youkaichao** [comment]
there is a function that might help:

https://github.com/vllm-project/vllm/blob/c8a7e93273ff4338d6f89f8a63ff16426ac240b8/vllm/utils.py#L926

You can replace `torch.cuda.is_available()` to some alternative functions, like `torch.version.cuda is not None`.

**Comment by youkaichao** [comment]
Just to clarify, `import torch` is fine. Just don't call `torch.cuda.is_available()` .

**Comment by rkooo567** [comment]
oh yeah good point @youkaichao. importing torch is fine, but using any API with device_count() can cause this issue

**Comment by youkaichao** [comment]
the latest main branch already fixed this, via upgrading to pytorch 2.4
