### ISSUE TITLE
pip install error - CUDA version mismatch

### ISSUE THREAD

**Issue by zxia545** [vllm-project/vllm#763]
I have the torch version 2.0.1+cu117

```
import torch
print(torch.__version__)
print(torch.version.cuda)
2.0.1+cu117
11.7
```
However pip install vllm fails with
```

File "/tmp/pip-build-env-jw9yras7/overlay/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.2) mismatches the version that was used to compile
      PyTorch (11.7). Please make sure to use the same CUDA versions.
      
      [end of output]
```
      
nvidia-smi
```
Tue Aug 15 11:43:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A40          On   | 00000000:35:00.0 Off |                    0 |
|  0%   39C    P8    61W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A40          On   | 00000000:36:00.0 Off |                    0 |
|  0%   39C    P0    41W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A40          On   | 00000000:39:00.0 Off |                    0 |
|  0%   39C    P0    42W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA A40          On   | 00000000:3D:00.0 Off |                    0 |
|  0%   40C    P0    61W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  NVIDIA A40          On   | 00000000:CE:00.0 Off |                    0 |
|  0%   38C    P0    58W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  NVIDIA A40          On   | 00000000:CF:00.0 Off |                    0 |
|  0%   40C    P0    25W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  NVIDIA A40          On   | 00000000:D2:00.0 Off |                    0 |
|  0%   38C    P0    21W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  NVIDIA A40          On   | 00000000:D6:00.0 Off |                    0 |
|  0%   39C    P0    25W / 300W |      0MiB / 46068MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

ls /usr/local | grep cuda
```
cuda
cuda-12
cuda-12.2
```

**Comment by WoosukKwon** [comment]
Hi @zxia545, thanks for trying out vLLM. I believe this is fixed at the latest release (v0.1.4) since our pypi wheels include pre-compiled CUDA binaries. Please retry `pip install vllm`.

**Comment by sherryxiao1988** [comment]
building from source failed for me with the same error.

torch version:
```
Python 3.10.11 (main, May 16 2023, 00:28:57) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
2.0.1+cu118
>>> 
```
nvidia-smai
``` 
 nvidia-smi
Fri Sep 15 15:24:14 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A6000               On  | 00000000:52:00.0  On |                  Off |
| 30%   43C    P8              30W / 300W |    695MiB / 49140MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1794      G   /usr/lib/xorg/Xorg                          279MiB |
|    0   N/A  N/A      2162      G   /usr/bin/gnome-shell                         70MiB |
|    0   N/A  N/A      2972    C+G   ...21299458,2722028716369240243,262144      202MiB |
|    0   N/A  N/A      4921      G   ...ures=SpareRendererForSitePerProcess       22MiB |
|    0   N/A  N/A      6209      G   ...sion,SpareRendererForSitePerProcess       43MiB |
+---------------------------------------------------------------------------------------+
```

Running `pip install -e .` gives:
```
Building wheels for collected packages: vllm
  Building editable for vllm (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for vllm (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [124 lines of output]
      No ROCm runtime is found, using ROCM_HOME='/opt/rocm-5.6.0'
      running editable_wheel
      creating /tmp/pip-wheel-bvv3xiqn/.tmp-dz1vpsxq/vllm.egg-info
      writing /tmp/pip-wheel-bvv3xiqn/.tmp-dz1vpsxq/vllm.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-wheel-bvv3xiqn/.tmp-dz1vpsxq/vllm.egg-info/dependency_links.txt
      writing requirements to /tmp/pip-wheel-bvv3xiqn/.tmp-dz1vpsxq/vllm.egg-info/requires.txt
      writing top-level names to /tmp/pip-wheel-bvv3xiqn/.tmp-dz1vpsxq/vllm.egg-info/top_level.txt
      writing manifest file '/tmp/pip-wheel-bvv3xiqn/.tmp-dz1vpsxq/vllm.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-wheel-bvv3xiqn/.tmp-dz1vpsxq/vllm.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file '/tmp/pip-wheel-bvv3xiqn/.tmp-dz1vpsxq/vllm.egg-info/SOURCES.txt'
      creating '/tmp/pip-wheel-bvv3xiqn/.tmp-dz1vpsxq/vllm-0.1.7.dist-info'
      creating /tmp/pip-wheel-bvv3xiqn/.tmp-dz1vpsxq/vllm-0.1.7.dist-info/WHEEL
      running build_py
      running build_ext
      Traceback (most recent call last):
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 156, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 345, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 268, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 295, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.2) mismatches the version that was used to compile
      PyTorch (11.7). Please make sure to use the same CUDA versions.
      
      /tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py:988: _DebuggingTips: Problem in editable installation.
      !!
      
              ********************************************************************************
              An error happened while installing `vllm` in editable mode.
      
              The following steps are recommended to help debug this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
      
      !!
        cmd_obj.run()
      Traceback (most recent call last):
        File "/home/shundan/miniconda3/envs/hip/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/shundan/miniconda3/envs/hip/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/shundan/miniconda3/envs/hip/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 273, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 463, in build_editable
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 179, in <module>
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 156, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 345, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 268, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 295, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/tmp/pip-build-env-4xnh4rb6/overlay/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 387, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.2) mismatches the version that was used to compile
      PyTorch (11.7). Please make sure to use the same CUDA versions.

```

**Comment by ckgresla** [comment]
any luck with this one? I am trying to setup vllm locally for some development and am running into the same issue.

**Comment by ckgresla** [comment]
If anyone comes across this issue, I managed to remedy it on a Ubuntu box by installing an alternate CUDA Toolkit, used `conda install -c "nvidia/label/cuda-11.7.1" cuda-toolkit` as per the versions on- https://anaconda.org/nvidia/cuda-toolkit

When building the environment

**Comment by sherryxiao1988** [comment]
@ckgresla thanks for providing your solutions. It seems the project sometime asks for cuda 12.2, and sometime asks for 11.7. I was very confused and ended up installing multiple versions of cuda as you did.

**Comment by ckgresla** [comment]
I hope you were able to solve the issues for your use case!

**Comment by elslush** [comment]
I had a similar issue with building from source.

torch version:
```
Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
2.1.0+cu121
>>> 
```
nvidia-smi
```
nvidia-smi
Tue Oct 24 17:23:19 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2070         On | 00000000:25:00.0 Off |                  N/A |
| 16%   27C    P8               13W / 175W|      1MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 3080         On | 00000000:26:00.0 Off |                  N/A |
|  0%   32C    P8               18W / 340W|      1MiB / 10240MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

My solution was to change the requirements.txt file from:
```
torch == 2.0.1
xformers == 0.0.22
```
to
```
torch >= 2.0.1
xformers >= 0.0.22
```
That is when I got the error:

> The detected CUDA version (12.2) mismatches the version that was used to compile
>       PyTorch (11.7). Please make sure to use the same CUDA versions.

The solution to this was to change the pyproject.toml file from:
```
[build-system]
requires = [
    "ninja",
    "packaging",
    "setuptools",
    "torch == 2.0.1",
    "wheel",
]
build-backend = "setuptools.build_meta"
```
to
```
[build-system]
requires = [
    "ninja",
    "packaging",
    "setuptools",
    "torch >= 2.0.1",
    "wheel",
]
build-backend = "setuptools.build_meta"
```

Hopefully this helps!

**Comment by jtchira** [comment]
Sinceramente cuda y pyton y todo eso es una mierda!!!

**Comment by JustinKai0527** [comment]
I done by comment this two lines of code in cpp_extension _check_cuda_version, but anyone can tell me why I comment this two line and then can be download pretty well
![image](https://github.com/user-attachments/assets/25b58ac4-5cc6-4d61-8912-f6d062908d71)
