### ISSUE TITLE
[Bug]: vLLM hang at nccl step when trying to use multiple GPUs

### ISSUE THREAD

**Issue by BiboyQG** [vllm-project/vllm#8058]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-190-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A40
GPU 1: NVIDIA A40
GPU 2: NVIDIA A40

Nvidia driver version: 535.183.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                       x86_64
CPU op-mode(s):                     32-bit, 64-bit
Byte Order:                         Little Endian
Address sizes:                      43 bits physical, 48 bits virtual
CPU(s):                             64
On-line CPU(s) list:                0-63
Thread(s) per core:                 2
Core(s) per socket:                 16
Socket(s):                          2
NUMA node(s):                       2
Vendor ID:                          AuthenticAMD
CPU family:                         23
Model:                              49
Model name:                         AMD EPYC 7302 16-Core Processor
Stepping:                           0
CPU MHz:                            3225.936
BogoMIPS:                           5989.09
Virtualization:                     AMD-V
L1d cache:                          1 MiB
L1i cache:                          1 MiB
L2 cache:                           16 MiB
L3 cache:                           256 MiB
NUMA node0 CPU(s):                  0-15,32-47
NUMA node1 CPU(s):                  16-31,48-63
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Vulnerable
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:           Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP conditional; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected
Flags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monit
or ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd
 mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean
flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca sme sev sev_es

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] nvidia-nvjitlink-cu12==12.6.68
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pyzmq==26.2.0
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] transformers==4.44.2
[pip3] triton==3.0.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
[conda] nvidia-ml-py              12.560.30                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.6.68                  pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
[conda] pyzmq                     26.2.0                   pypi_0    pypi
[conda] torch                     2.4.0                    pypi_0    pypi
[conda] torchvision               0.19.0                   pypi_0    pypi
[conda] transformers              4.44.2                   pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.5.5@09c7792610ada9f88bbf87d32b472dd44bf23cc2
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0    GPU1    GPU2    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     SYS     0-15,32-47      0               N/A
GPU1    SYS      X      NODE    16-31,48-63     1               N/A
GPU2    SYS     NODE     X      16-31,48-63     1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

</details>

### 🐛 Describe the bug

When trying to run `VLLM_LOGGING_LEVEL=DEBUG CUDA_LAUNCH_BLOCKING=1 NCCL_DEBUG=TRACE VLLM_TRACE_FUNCTION=1 CUDA_VISIBLE_DEVICES=0,1 vllm serve Qwen/Qwen2-72B-Instruct-AWQ --max-model-len=20480 --max-num-seqs=1 --gpu-memory-utilization=0.98 --trust-remote-code --tensor-parallel-size 2`, output of the program shows:
```
/scratch/banghao2/miniforge3/envs/spin/lib/python3.10/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
INFO 08-31 09:50:38 api_server.py:440] vLLM API server version 0.5.5
INFO 08-31 09:50:38 api_server.py:441] args: Namespace(model_tag='Qwen/Qwen2-72B-Instruct-AWQ', host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None
, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, model='Qwen/Qwen2-72
B-Instruct-AWQ', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=True, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=No
ne, max_model_len=20480, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=2, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching
=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.98, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=1, max_logprobs=20, disable_log_stats=F
alse, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm
_per_prompt=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token
=0, device='auto', num_scheduler_steps=1, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, speculative_model_quantization=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, spe
culative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_
during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, collect_detailed_traces=None, engine_use_ray=False, disable_log_requests=False, max_
log_len=None, dispatch_function=<function serve at 0x7f24dae48310>)
INFO 08-31 09:50:38 awq_marlin.py:89] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 08-31 09:50:38 api_server.py:144] Multiprocessing frontend to use ipc:///tmp/0eb5eda7-0568-447f-9cd5-964a8a12e3c5 for RPC Path.
INFO 08-31 09:50:38 api_server.py:161] Started engine process with PID 1927386
INFO 08-31 09:50:44 awq_marlin.py:89] The model is convertible to awq_marlin during runtime. Using awq_marlin kernel.
INFO 08-31 09:50:44 config.py:813] Defaulting to use mp for distributed inference
INFO 08-31 09:50:44 llm_engine.py:184] Initializing an LLM engine (v0.5.5) with config: model='Qwen/Qwen2-72B-Instruct-AWQ', speculative_config=None, tokenizer='Qwen/Qwen2-72B-Instruct-AWQ', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=20480, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=awq_marlin, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen/Qwen2-72B-Instruct-AWQ, use_v2_block_manager=False, enable_prefix_caching=False)
WARNING 08-31 09:50:44 multiproc_gpu_executor.py:59] Reducing Torch parallelism from 32 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 08-31 09:50:44 custom_cache_manager.py:17] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
(VllmWorkerProcess pid=1927518) WARNING 08-31 09:50:44 logger.py:147] VLLM_TRACE_FUNCTION is enabled. It will record every function executed by Python. This will slow down the code. It is suggested to be used for debugging hang or crashes only.
WARNING 08-31 09:50:44 logger.py:147] VLLM_TRACE_FUNCTION is enabled. It will record every function executed by Python. This will slow down the code. It is suggested to be used for debugging hang or crashes only.
(VllmWorkerProcess pid=1927518) INFO 08-31 09:50:44 logger.py:151] Trace frame log is saved to /tmp/vllm/vllm-instance-f766c21106bb40cc8562cc2dbb135395/VLLM_TRACE_FUNCTION_for_process_1927518_thread_140351761319744_at_2024-08-31_09:50:44.838658.log
INFO 08-31 09:50:44 logger.py:151] Trace frame log is saved to /tmp/vllm/vllm-instance-f766c21106bb40cc8562cc2dbb135395/VLLM_TRACE_FUNCTION_for_process_1927386_thread_140351761319744_at_2024-08-31_09:50:44.838511.log
(VllmWorkerProcess pid=1927518) INFO 08-31 09:50:45 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
DEBUG 08-31 09:50:46 parallel_state.py:845] world_size=2 rank=0 local_rank=0 distributed_init_method=tcp://127.0.0.1:39423 backend=nccl
(VllmWorkerProcess pid=1927518) DEBUG 08-31 09:50:46 parallel_state.py:845] world_size=2 rank=1 local_rank=1 distributed_init_method=tcp://127.0.0.1:39423 backend=nccl
INFO 08-31 09:50:46 utils.py:975] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=1927518) INFO 08-31 09:50:46 utils.py:975] Found nccl from library libnccl.so.2
INFO 08-31 09:50:46 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=1927518) INFO 08-31 09:50:46 pynccl.py:63] vLLM is using nccl==2.20.5
osprey1:1927386:1927386 [0] NCCL INFO Bootstrap : Using eno1:128.174.136.27<0>
osprey1:1927386:1927386 [0] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
osprey1:1927386:1927386 [0] NCCL INFO cudaDriverVersion 12020
NCCL version 2.20.5+cuda12.4
osprey1:1927518:1927518 [1] NCCL INFO cudaDriverVersion 12020
osprey1:1927518:1927518 [1] NCCL INFO Bootstrap : Using eno1:128.174.136.27<0>
osprey1:1927518:1927518 [1] NCCL INFO NET/Plugin : dlerror=libnccl-net.so: cannot open shared object file: No such file or directory No plugin found (libnccl-net.so), using internal implementation
osprey1:1927386:1927386 [0] NCCL INFO Failed to open libibverbs.so[.1]
osprey1:1927386:1927386 [0] NCCL INFO NET/Socket : Using [0]eno1:128.174.136.27<0> [1]br-a2d004c4515a:10.201.0.1<0>
osprey1:1927386:1927386 [0] NCCL INFO Using non-device net plugin version 0
osprey1:1927386:1927386 [0] NCCL INFO Using network Socket
osprey1:1927518:1927518 [1] NCCL INFO Failed to open libibverbs.so[.1]
osprey1:1927518:1927518 [1] NCCL INFO NET/Socket : Using [0]eno1:128.174.136.27<0> [1]br-a2d004c4515a:10.201.0.1<0>
osprey1:1927518:1927518 [1] NCCL INFO Using non-device net plugin version 0
osprey1:1927518:1927518 [1] NCCL INFO Using network Socket
osprey1:1927386:1927386 [0] NCCL INFO comm 0x557604abfaa0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 21000 commId 0x45ad6db7a099ff2f - Init START
osprey1:1927518:1927518 [1] NCCL INFO comm 0x557604abee90 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId 81000 commId 0x45ad6db7a099ff2f - Init START
osprey1:1927518:1927518 [1] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.
osprey1:1927518:1927518 [1] NCCL INFO Setting affinity for GPU 1 to ffff0000,ffff0000
osprey1:1927386:1927386 [0] NCCL INFO NCCL_CUMEM_ENABLE set by environment to 0.
osprey1:1927386:1927386 [0] NCCL INFO Setting affinity for GPU 0 to ffff,0000ffff
osprey1:1927518:1927518 [1] NCCL INFO comm 0x557604abee90 rank 1 nRanks 2 nNodes 1 localRanks 2 localRank 1 MNNVL 0
osprey1:1927518:1927518 [1] NCCL INFO Trees [0] -1/-1/-1->1->0 [1] -1/-1/-1->1->0
osprey1:1927386:1927386 [0] NCCL INFO comm 0x557604abfaa0 rank 0 nRanks 2 nNodes 1 localRanks 2 localRank 0 MNNVL 0
osprey1:1927518:1927518 [1] NCCL INFO P2P Chunksize set to 131072
osprey1:1927386:1927386 [0] NCCL INFO Channel 00/02 :    0   1
osprey1:1927386:1927386 [0] NCCL INFO Channel 01/02 :    0   1
osprey1:1927386:1927386 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 1/-1/-1->0->-1
osprey1:1927386:1927386 [0] NCCL INFO P2P Chunksize set to 131072
osprey1:1927518:1927518 [1] NCCL INFO Channel 00/0 : 1[1] -> 0[0] via P2P/IPC
osprey1:1927518:1927518 [1] NCCL INFO Channel 01/0 : 1[1] -> 0[0] via P2P/IPC
osprey1:1927386:1927386 [0] NCCL INFO Channel 00/0 : 0[0] -> 1[1] via P2P/IPC
osprey1:1927386:1927386 [0] NCCL INFO Channel 01/0 : 0[0] -> 1[1] via P2P/IPC
osprey1:1927518:1927518 [1] NCCL INFO Connected all rings
osprey1:1927386:1927386 [0] NCCL INFO Connected all rings
osprey1:1927518:1927518 [1] NCCL INFO Connected all trees
osprey1:1927386:1927386 [0] NCCL INFO Connected all trees
osprey1:1927518:1927518 [1] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
osprey1:1927518:1927518 [1] NCCL INFO 2 coll channels, 0 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
osprey1:1927386:1927386 [0] NCCL INFO threadThresholds 8/8/64 | 16/8/64 | 512 | 512
osprey1:1927386:1927386 [0] NCCL INFO 2 coll channels, 0 collnet channels, 0 nvls channels, 2 p2p channels, 2 p2p channels per peer
osprey1:1927518:1927518 [1] NCCL INFO comm 0x557604abee90 rank 1 nranks 2 cudaDev 1 nvmlDev 1 busId 81000 commId 0x45ad6db7a099ff2f - Init COMPLETE
osprey1:1927386:1927386 [0] NCCL INFO comm 0x557604abfaa0 rank 0 nranks 2 cudaDev 0 nvmlDev 0 busId 21000 commId 0x45ad6db7a099ff2f - Init COMPLETE
```
and hang from here. I wonder if anyone has experienced this before, and if so, please notify me if there's any solutions. Thanks in advance!

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by BiboyQG** [comment]
Problem is solved by adding environment `NCCL_P2P_DISABLE=1` in front of the command, since this log shows some problem happening between the P2P communication. Closing this now.

**Comment by xxxjjhhh** [comment]
great!!!!!
