### ISSUE TITLE
[Bug]: OutOfMemoryError error using Llama3 with speculative decoding 

### ISSUE THREAD

**Issue by captify-sivakhno** [vllm-project/vllm#8073]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
PyTorch version: 2.3.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1067-aws-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A10G
Nvidia driver version: 535.161.07
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.7
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        48 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               16
On-line CPU(s) list:                  0-15
Vendor ID:                            AuthenticAMD
Model name:                           AMD EPYC 7R32
CPU family:                           23
Model:                                49
Thread(s) per core:                   2
Core(s) per socket:                   8
Socket(s):                            1
Stepping:                             0
BogoMIPS:                             5600.00
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr rdpru wbnoinvd arat npt nrip_save rdpid
Hypervisor vendor:                    KVM
Virtualization type:                  full
L1d cache:                            256 KiB (8 instances)
L1i cache:                            256 KiB (8 instances)
L2 cache:                             4 MiB (8 instances)
L3 cache:                             32 MiB (2 instances)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-15
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Mitigation; untrained return thunk; SMT enabled with STIBP protection
Vulnerability Spec rstack overflow:   Mitigation; safe RET
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] optree==0.12.1
[pip3] sentence-transformers==2.7.0
[pip3] torch==2.3.1+cu121
[pip3] torcheval==0.0.7
[pip3] torchvision==0.18.1+cu121
[pip3] transformers==4.41.2
[pip3] triton==2.3.1
[conda] Could not collect
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: N/A
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
GPU0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	0-15	0		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

</details>

### 🐛 Describe the bug

I get an out of memory error when using speculative decoding (SD). This happens in the middle of generation or after several batches completed successfully even after have reduced `max_model_len`, `max_num_batched_tokens` and `gpu_memory_utilization`.

**Usage** 
```python
llm = LLM("nvidia/Llama-3.1-Minitron-4B-Width-Base", enable_prefix_caching=True, block_size=3, gpu_memory_utilization=0.8, max_num_batched_tokens=11000,  max_model_len=11000, speculative_model="ibm-fms/llama3-8b-accelerator", num_speculative_tokens=1, use_v2_block_manager=True)
sampling_params = SamplingParams(temperature=0.5, top_p=0.2, max_tokens=1)
formatted_prompts = ["array of len 10000 to 400000, each around 100-200 tokens"] 
from outlines import models, generate
model = models.VLLM(llm)
generator = generate.choice(model, ["yes", "no"])
predictions = generator(formatted_prompts, sampling_params=sampling_params)
```

In contrast, when SD is disabled, runs always complete even at high max_model_len`, `max_num_batched_tokens` and `gpu_memory_utilization`.

```python
llm = LLM("nvidia/Llama-3.1-Minitron-4B-Width-Base", enable_prefix_caching=True, block_size=3,max_num_batched_tokens=20000, gpu_memory_utilization=0.95, max_model_len=20000, use_v2_block_manager=True)
```

**Error trace**
```python
OutOfMemoryError: CUDA out of memory. Tried to allocate 1.86 GiB. GPU 0 has a total capacity of 21.99 GiB of which 337.38 MiB is free. Process 30125 has 21.64 GiB memory in use. Of the allocated memory 18.20 GiB is allocated by PyTorch, with 27.10 MiB allocated in private pools (e.g., CUDA Graphs), and 2.26 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
File <command-1108086693486187>, line 1
----> 1 predictions = generator(formatted_prompts, sampling_params=sampling_params)
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-6e87dd7d-c6c7-4a06-8001-d206e2d3c391/lib/python3.11/site-packages/outlines/generate/api.py:503, in SequenceGeneratorAdapter.__call__(self, prompts, max_tokens, stop_at, seed, **model_specific_params)
    497         return self.format_sequence(sequences)
    499 generation_params = self.prepare_generation_parameters(
    500     max_tokens, stop_at, seed
    501 )
--> 503 completions = self.model.generate(
    504     prompts,
    505     generation_params,
    506     self.logits_processor,
    507     self.sampling_params,
    508     **model_specific_params,
    509 )
    511 return format(completions)
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-6e87dd7d-c6c7-4a06-8001-d206e2d3c391/lib/python3.11/site-packages/outlines/models/vllm.py:105, in VLLM.generate(self, prompts, generation_parameters, logits_processor, sampling_parameters, sampling_params)
    102 if sampler == "beam_search":
    103     sampling_params.use_beam_search = True
--> 105 results = self.model.generate(
    106     prompts, sampling_params=sampling_params, lora_request=self.lora_request
    107 )
    108 results = [[sample.text for sample in batch.outputs] for batch in results]
    110 batch_size = len(results)
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-6e87dd7d-c6c7-4a06-8001-d206e2d3c391/lib/python3.11/site-packages/vllm/utils.py:1030, in deprecate_kwargs.<locals>.wrapper.<locals>.inner(*args, **kwargs)
   1023             msg += f" {additional_message}"
   1025         warnings.warn(
   1026             DeprecationWarning(msg),
   1027             stacklevel=3,  # The inner function takes up one level
   1028         )
-> 1030 return fn(*args, **kwargs)
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-6e87dd7d-c6c7-4a06-8001-d206e2d3c391/lib/python3.11/site-packages/vllm/entrypoints/llm.py:345, in LLM.generate(self, prompts, sampling_params, prompt_token_ids, use_tqdm, lora_request, prompt_adapter_request, guided_options_request)
    336     sampling_params = SamplingParams()
    338 self._validate_and_add_requests(
    339     inputs=inputs,
    340     params=sampling_params,
    341     lora_request=lora_request,
    342     prompt_adapter_request=prompt_adapter_request,
    343     guided_options=guided_options_request)
--> 345 outputs = self._run_engine(use_tqdm=use_tqdm)
    346 return LLMEngine.validate_outputs(outputs, RequestOutput)
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-6e87dd7d-c6c7-4a06-8001-d206e2d3c391/lib/python3.11/site-packages/vllm/entrypoints/llm.py:686, in LLM._run_engine(self, use_tqdm)
    684 total_out_toks = 0
    685 while self.llm_engine.has_unfinished_requests():
--> 686     step_outputs = self.llm_engine.step()
    687     for output in step_outputs:
    688         if output.finished:
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-6e87dd7d-c6c7-4a06-8001-d206e2d3c391/lib/python3.11/site-packages/vllm/engine/llm_engine.py:1325, in LLMEngine.step(self)
   1315     finished_requests_ids = self.scheduler[
   1316         0].get_and_reset_finished_requests_ids()
   1317     execute_model_req = ExecuteModelRequest(
   1318         seq_group_metadata_list=seq_group_metadata_list,
   1319         blocks_to_swap_in=scheduler_outputs.blocks_to_swap_in,
   (...)
   1323         running_queue_size=scheduler_outputs.running_queue_size,
   1324         finished_requests_ids=finished_requests_ids)
-> 1325     output = self.model_executor.execute_model(
   1326         execute_model_req=execute_model_req)
   1327 else:
   1328     output = []
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-6e87dd7d-c6c7-4a06-8001-d206e2d3c391/lib/python3.11/site-packages/vllm/executor/gpu_executor.py:129, in GPUExecutor.execute_model(self, execute_model_req)
    126 def execute_model(
    127     self, execute_model_req: ExecuteModelRequest
    128 ) -> Optional[List[Union[SamplerOutput, PoolerOutput]]]:
--> 129     output = self.driver_worker.execute_model(execute_model_req)
    130     return output
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-6e87dd7d-c6c7-4a06-8001-d206e2d3c391/lib/python3.11/site-packages/torch/utils/_contextlib.py:116, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    113 @functools.wraps(func)
    114 def decorate_context(*args, **kwargs):
    115     with ctx_factory():
--> 116         return func(*args, **kwargs)
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-6e87dd7d-c6c7-4a06-8001-d206e2d3c391/lib/python3.11/site-packages/vllm/spec_decode/spec_decode_worker.py:402, in SpecDecodeWorker.execute_model(self, execute_model_req)
    398 self._maybe_disable_speculative_tokens(
    399     disable_all_speculation, execute_model_req.seq_group_metadata_list)
    401 if no_spec:
--> 402     return self._run_no_spec(execute_model_req,
    403                              skip_proposer=disable_all_speculation)
    404 return self._run_speculative_decoding_step(execute_model_req,
    405                                            num_lookahead_slots)
File /usr/lib/python3.11/contextlib.py:81, in ContextDecorator.__call__.<locals>.inner(*args, **kwds)
     78 @wraps(func)
     79 def inner(*args, **kwds):
     80     with self._recreate_cm():
---> 81         return func(*args, **kwds)
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-6e87dd7d-c6c7-4a06-8001-d206e2d3c391/lib/python3.11/site-packages/vllm/spec_decode/spec_decode_worker.py:494, in SpecDecodeWorker._run_no_spec(self, execute_model_req, skip_proposer)
    491         self.previous_hidden_states = HiddenStates(
    492             hidden_states, execute_model_req.seq_group_metadata_list)
    493     else:
--> 494         self.previous_hidden_states.update(
    495             hidden_states, execute_model_req.seq_group_metadata_list)
    497 if not skip_proposer:
    498     # We prepare the prefill hidden states here so that there no
    499     # additional complexity in worker for spec_decode vs non_spec_decode
    500     # flow and execute_model doesn't need additional modifications.
    501     execute_model_req.previous_hidden_states = \
    502         prepare_prefill_hidden_states(
    503             sampler_output.prefill_hidden_states)
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-6e87dd7d-c6c7-4a06-8001-d206e2d3c391/lib/python3.11/site-packages/vllm/sequence.py:1217, in HiddenStates.update(self, hidden_states, seq_group_metadata_list, second_last_token_hidden_states)
   1215 assert len(seq_group_metadata_list) == len(hidden_states)
   1216 self._seq_ids.extend(get_all_seq_ids(seq_group_metadata_list))
-> 1217 self.hidden_states = torch.cat([self.hidden_states, hidden_states])
   1219 if self.second_last_token_hidden_states is not None:
   1220     # Adding dummy hidden_states to this to maintain same shape
   1221     self.second_last_token_hidden_states = torch.cat([
   1222         self.second_last_token_hidden_states,
   1223         torch.zeros_like(hidden_states)
   1224         if second_last_token_hidden_states is None else
   1225         second_last_token_hidden_states
   1226     ])```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by hav4ik** [comment]
Same issue here with Qwen 2.5 models (7b and 0.5b).

vllm version: 0.6.2
GPU: 2x3090 (tensor_parallel_size=2)

```
llm = vllm.LLM(
    model=main_model_name,
    tokenizer=main_model_name,
    tensor_parallel_size=2,
    dtype="bfloat16",
    speculative_model=speculative_model_name,
    num_speculative_tokens=5,
    use_v2_block_manager=True,
    gpu_memory_utilization=0.8,
    enforce_eager=True,
    max_seq_len_to_capture=2048,
)
```

**Comment by anttttti** [comment]
Same issue with n-gram speculative decoding. I've tried everything to go around this, but still happens. This happens with every version of vLLM from at least 0.6.1 to current, with Pytorch 2.5.1 and 2.4.0, and different vLLMs options for enable-eager, prefix caching etc.

In some cases the engine processes hundred or more requests ok, sometimes the crash happens soon after the first requests. Doesn't seem to happen on the first request.

This makes speculative decoding not usable for production, as the servers would throw errors and require frequent restarts.

**Comment by BaohaoLiao** [comment]
reducing max_num_seqs works for me

**Comment by ComposerKevin** [comment]
Same happens to me, I could run with `--max-model-len 86000` without speculative decoding, but with it on, memory profiling shows peak activation memory bumps a lot, and I could only run `--max-model-len 14000`.
