### ISSUE TITLE
[Usage]: Distributed inference with edge case: model fits multiple GPUs, but number of GPUs cannot divide the model size evenly

### ISSUE THREAD

**Issue by leszekhanusz** [vllm-project/vllm#8270]
### Your current environment

```text
Collecting environment information...
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 24.04.1 LTS (x86_64)
GCC version: (Ubuntu 13.2.0-23ubuntu4) 13.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.39

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.8.0-41-generic-x86_64-with-glibc2.39
Is CUDA available: True
CUDA runtime version: 12.0.140
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090
GPU 4: NVIDIA GeForce RTX 3090
GPU 5: NVIDIA GeForce RTX 3090
GPU 6: NVIDIA GeForce RTX 3090

Nvidia driver version: 550.90.07
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        48 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               32
On-line CPU(s) list:                  0-31
Vendor ID:                            AuthenticAMD
Model name:                           AMD Ryzen Threadripper PRO 5955WX 16-Cores
CPU family:                           25
Model:                                8
Thread(s) per core:                   2
Core(s) per socket:                   16
Socket(s):                            1
Stepping:                             2
Frequency boost:                      enabled
CPU(s) scaling MHz:                   36%
CPU max MHz:                          7031.2500
CPU min MHz:                          1800.0000
BogoMIPS:                             7985.50
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local user_shstk clzero irperf xsaveerptr rdpru wbnoinvd amd_ppin brs arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm debug_swap
Virtualization:                       AMD-V
L1d cache:                            512 KiB (16 instances)
L1i cache:                            512 KiB (16 instances)
L2 cache:                             8 MiB (16 instances)
L3 cache:                             64 MiB (2 instances)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-31
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Mitigation; Safe RET
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-ml-py==12.560.30
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] nvidia-nvjitlink-cu12==12.6.68
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pyzmq==26.2.0
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] transformers==4.44.2
[pip3] triton==3.0.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
[conda] nvidia-ml-py              12.560.30                pypi_0    pypi
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.6.68                  pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
[conda] pyzmq                     26.2.0                   pypi_0    pypi
[conda] torch                     2.4.0                    pypi_0    pypi
[conda] torchvision               0.19.0                   pypi_0    pypi
[conda] transformers              4.44.2                   pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: 0.6.0@32e7db25365415841ebc7c4215851743fbb1bad1
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
[4mGPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	CPU Affinity	NUMA Affinity	GPU NUMA ID[0m
GPU0	 X 	PHB	PHB	SYS	SYS	SYS	SYS	0-31	0		N/A
GPU1	PHB	 X 	PHB	SYS	SYS	SYS	SYS	0-31	0		N/A
GPU2	PHB	PHB	 X 	SYS	SYS	SYS	SYS	0-31	0		N/A
GPU3	SYS	SYS	SYS	 X 	PHB	SYS	SYS	0-31	0		N/A
GPU4	SYS	SYS	SYS	PHB	 X 	SYS	SYS	0-31	0		N/A
GPU5	SYS	SYS	SYS	SYS	SYS	 X 	PHB	0-31	0		N/A
GPU6	SYS	SYS	SYS	SYS	SYS	PHB	 X 	0-31	0		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
```

### How would you like to use vllm

I'm just starting with vllm and for a first test I would like to run inference on LLama 3.1 70B on my system with 7 GPU.

I have quantized the model to F16 to the gguf format (I know I could/should quantize it further but it's a first test).

I can load this model fine with llama.cpp using text-generation-webui if the context is not too big.

Now I want to test vllm and I'm trying to load that model.

I first started with to load the model with `tensor_parallel_size=7` but ran into the #4232 issue.

It has been suggested to use `pipeline_parallel_size=7` instead and that's what I'm trying to do now, but it seems that vllm is trying to fit too much on the first GPU and I have quickly a memory error.

The code I'm using right now is simply:
```python
from vllm import LLM

llm = LLM(
    "/home/leszek/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-70B/snapshots/7740ff69081bd553f4879f71eebcc2d6df2fbcb3/Meta-Llama-3.1-70B-F16.gguf",
    tensor_parallel_size=1,
    pipeline_parallel_size=7,
    max_seq_len_to_capture=8192,
)
```

And as I `watch nvidia-smi`, I can see that after all my GPUs are loaded with about 575MiB, only the first GPU is starting to fill up, until I get the `torch.OutOfMemoryError` error.

The output is:

```
$ python test.py 
INFO 09-07 23:30:12 config.py:1647] Downcasting torch.float32 to torch.float16.
WARNING 09-07 23:30:12 config.py:330] gguf quantization is not fully optimized yet. The speed can be slower than non-quantized models.
INFO 09-07 23:30:12 config.py:890] Defaulting to use mp for distributed inference
WARNING 09-07 23:30:12 arg_utils.py:862] Chunked prefill is enabled by default for models with max_model_len > 32K. Currently, chunked prefill might not work with some features or models. If you encounter any issues, please disable chunked prefill by setting --enable-chunked-prefill=False.
INFO 09-07 23:30:12 config.py:999] Chunked prefill is enabled with max_num_batched_tokens=512.
WARNING 09-07 23:30:12 config.py:359] Async output processing can not be enabled with pipeline parallel
INFO 09-07 23:30:12 llm_engine.py:213] Initializing an LLM engine (v0.6.0) with config: model='/home/leszek/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-70B/snapshots/7740ff69081bd553f4879f71eebcc2d6df2fbcb3/Meta-Llama-3.1-70B-F16.gguf', speculative_config=None, tokenizer='/home/leszek/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-70B/snapshots/7740ff69081bd553f4879f71eebcc2d6df2fbcb3/Meta-Llama-3.1-70B-F16.gguf', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=131072, download_dir=None, load_format=LoadFormat.GGUF, tensor_parallel_size=1, pipeline_parallel_size=7, disable_custom_all_reduce=False, quantization=gguf, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/home/leszek/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-70B/snapshots/7740ff69081bd553f4879f71eebcc2d6df2fbcb3/Meta-Llama-3.1-70B-F16.gguf, use_v2_block_manager=False, num_scheduler_steps=1, enable_prefix_caching=False, use_async_output_proc=False)
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'LlamaTokenizer'. 
The class this function is called from is 'PreTrainedTokenizerFast'.
WARNING 09-07 23:30:28 multiproc_gpu_executor.py:56] Reducing Torch parallelism from 16 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 09-07 23:30:28 custom_cache_manager.py:17] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
(VllmWorkerProcess pid=244159) INFO 09-07 23:30:28 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=244160) INFO 09-07 23:30:28 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=244161) INFO 09-07 23:30:28 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=244162) INFO 09-07 23:30:28 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=244163) INFO 09-07 23:30:28 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
(VllmWorkerProcess pid=244164) INFO 09-07 23:30:28 multiproc_worker_utils.py:215] Worker ready; awaiting tasks
INFO 09-07 23:30:29 utils.py:977] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=244159) INFO 09-07 23:30:29 utils.py:977] Found nccl from library libnccl.so.2
INFO 09-07 23:30:29 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=244159) INFO 09-07 23:30:29 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=244160) INFO 09-07 23:30:29 utils.py:977] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=244160) INFO 09-07 23:30:29 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=244162) INFO 09-07 23:30:29 utils.py:977] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=244161) INFO 09-07 23:30:29 utils.py:977] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=244162) INFO 09-07 23:30:29 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=244161) INFO 09-07 23:30:29 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=244163) INFO 09-07 23:30:29 utils.py:977] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=244164) INFO 09-07 23:30:29 utils.py:977] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=244163) INFO 09-07 23:30:29 pynccl.py:63] vLLM is using nccl==2.20.5
(VllmWorkerProcess pid=244164) INFO 09-07 23:30:29 pynccl.py:63] vLLM is using nccl==2.20.5
INFO 09-07 23:30:29 model_runner.py:915] Starting to load model /home/leszek/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-70B/snapshots/7740ff69081bd553f4879f71eebcc2d6df2fbcb3/Meta-Llama-3.1-70B-F16.gguf...
(VllmWorkerProcess pid=244159) INFO 09-07 23:30:29 model_runner.py:915] Starting to load model /home/leszek/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-70B/snapshots/7740ff69081bd553f4879f71eebcc2d6df2fbcb3/Meta-Llama-3.1-70B-F16.gguf...
(VllmWorkerProcess pid=244160) INFO 09-07 23:30:29 model_runner.py:915] Starting to load model /home/leszek/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-70B/snapshots/7740ff69081bd553f4879f71eebcc2d6df2fbcb3/Meta-Llama-3.1-70B-F16.gguf...
(VllmWorkerProcess pid=244163) INFO 09-07 23:30:29 model_runner.py:915] Starting to load model /home/leszek/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-70B/snapshots/7740ff69081bd553f4879f71eebcc2d6df2fbcb3/Meta-Llama-3.1-70B-F16.gguf...
(VllmWorkerProcess pid=244162) INFO 09-07 23:30:29 model_runner.py:915] Starting to load model /home/leszek/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-70B/snapshots/7740ff69081bd553f4879f71eebcc2d6df2fbcb3/Meta-Llama-3.1-70B-F16.gguf...
(VllmWorkerProcess pid=244161) INFO 09-07 23:30:29 model_runner.py:915] Starting to load model /home/leszek/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-70B/snapshots/7740ff69081bd553f4879f71eebcc2d6df2fbcb3/Meta-Llama-3.1-70B-F16.gguf...
(VllmWorkerProcess pid=244164) INFO 09-07 23:30:29 model_runner.py:915] Starting to load model /home/leszek/.cache/huggingface/hub/models--meta-llama--Meta-Llama-3.1-70B/snapshots/7740ff69081bd553f4879f71eebcc2d6df2fbcb3/Meta-Llama-3.1-70B-F16.gguf...
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/leszek/tmp/vllmtest/test.py", line 4, in <module>
[rank0]:     llm = LLM(
[rank0]:   File "/home/leszek/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 177, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/home/leszek/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 538, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/home/leszek/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 305, in __init__
[rank0]:     self.model_executor = executor_class(
[rank0]:   File "/home/leszek/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 26, in __init__
[rank0]:     super().__init__(*args, **kwargs)
[rank0]:   File "/home/leszek/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 47, in __init__
[rank0]:     self._init_executor()
[rank0]:   File "/home/leszek/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 125, in _init_executor
[rank0]:     self._run_workers("load_model",
[rank0]:   File "/home/leszek/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 199, in _run_workers
[rank0]:     driver_worker_output = driver_worker_method(*args, **kwargs)
[rank0]:   File "/home/leszek/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/worker.py", line 182, in load_model
[rank0]:     self.model_runner.load_model()
[rank0]:   File "/home/leszek/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 917, in load_model
[rank0]:     self.model = get_model(model_config=self.model_config,
[rank0]:   File "/home/leszek/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/model_loader/__init__.py", line 19, in get_model
[rank0]:     return loader.load_model(model_config=model_config,
[rank0]:   File "/home/leszek/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/model_loader/loader.py", line 1085, in load_model
[rank0]:     model.load_weights(
[rank0]:   File "/home/leszek/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/models/llama.py", line 508, in load_weights
[rank0]:     weight_loader(param, loaded_weight, shard_id)
[rank0]:   File "/home/leszek/miniconda3/envs/vllm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 555, in weight_loader
[rank0]:     param_data.copy_(loaded_weight)
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 448.00 MiB. GPU 0 has a total capacity of 23.68 GiB of which 425.81 MiB is free. Including non-PyTorch memory, this process has 23.26 GiB memory in use. Of the allocated memory 22.86 GiB is allocated by PyTorch, and 1.63 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
ERROR 09-07 23:30:55 multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 244161 died, exit code: -15
INFO 09-07 23:30:55 multiproc_worker_utils.py:123] Killing local vLLM worker processes
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by youkaichao** [comment]
`pipeline_parallel_size` is not supported in `LLM`, you should use the openai api server instead.

**Comment by leszekhanusz** [comment]
The exact same thing happens if I use `vllm serve`:

[vllm serve log.txt](https://github.com/user-attachments/files/16920176/vllm.serve.log.txt)

**Comment by youkaichao** [comment]
what does it mean for `70B-F16` ? is it fp16 with 70B model? that would be 140GB already. Your GPUs might not be enough to hold the model.

**Comment by leszekhanusz** [comment]
Yes, the model is quite large at fp16: 131 GiB

I know it does not really make sense to run inference with 16 bits and 8 bits is more than enough.
I'll try to quantize it to 8 bits to see if it works then.

But it works with llama.cpp with less than 21.5GB / GPU with 16 bits with 8192 context.

Here is the llama.cpp output for comparison:

```
02:15:17-325920 INFO     Loading "Meta-Llama-3.1-70B-F16.gguf"                                
02:15:17-505805 INFO     llama.cpp weights detected: "models/Meta-Llama-3.1-70B-F16.gguf"     
llama_model_loader: loaded meta data with 27 key-value pairs and 724 tensors from models/Meta-Llama-3.1-70B-F16.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = 7740ff69081bd553f4879f71eebcc2d6df2fbcb3
llama_model_loader: - kv   3:                           general.finetune str              = 7740ff69081bd553f4879f71eebcc2d6df2fbcb3
llama_model_loader: - kv   4:                         general.size_label str              = 71B
llama_model_loader: - kv   5:                            general.license str              = llama3.1
llama_model_loader: - kv   6:                               general.tags arr[str,6]       = ["facebook", "meta", "pytorch", "llam...
llama_model_loader: - kv   7:                          general.languages arr[str,8]       = ["en", "de", "fr", "it", "pt", "hi", ...
llama_model_loader: - kv   8:                          llama.block_count u32              = 80
llama_model_loader: - kv   9:                       llama.context_length u32              = 131072
llama_model_loader: - kv  10:                     llama.embedding_length u32              = 8192
llama_model_loader: - kv  11:                  llama.feed_forward_length u32              = 28672
llama_model_loader: - kv  12:                 llama.attention.head_count u32              = 64
llama_model_loader: - kv  13:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv  14:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv  15:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  16:                          general.file_type u32              = 1
llama_model_loader: - kv  17:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv  18:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  19:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  20:                         tokenizer.ggml.pre str              = llama-bpe
llama_model_loader: - kv  21:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  22:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  23:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  24:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  25:                tokenizer.ggml.eos_token_id u32              = 128001
llama_model_loader: - kv  26:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:  162 tensors
llama_model_loader: - type  f16:  562 tensors
llm_load_vocab: special tokens cache size = 256
llm_load_vocab: token to piece cache size = 0.7999 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 128256
llm_load_print_meta: n_merges         = 280147
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 131072
llm_load_print_meta: n_embd           = 8192
llm_load_print_meta: n_layer          = 80
llm_load_print_meta: n_head           = 64
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 8
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 28672
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_ctx_orig_yarn  = 131072
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 70B
llm_load_print_meta: model ftype      = F16
llm_load_print_meta: model params     = 70.55 B
llm_load_print_meta: model size       = 131.42 GiB (16.00 BPW) 
llm_load_print_meta: general.name     = 7740ff69081bd553f4879f71eebcc2d6df2fbcb3
llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
llm_load_print_meta: EOS token        = 128001 '<|end_of_text|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'
llm_load_print_meta: max token length = 256
llm_load_tensors: ggml ctx size =    2.71 MiB
llm_load_tensors: offloading 80 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 81/81 layers to GPU
llm_load_tensors:        CPU buffer size =  2004.00 MiB
llm_load_tensors:      CUDA0 buffer size = 19584.75 MiB
llm_load_tensors:      CUDA1 buffer size = 19584.75 MiB
llm_load_tensors:      CUDA2 buffer size = 17952.69 MiB
llm_load_tensors:      CUDA3 buffer size = 19584.75 MiB
llm_load_tensors:      CUDA4 buffer size = 17952.69 MiB
llm_load_tensors:      CUDA5 buffer size = 19584.75 MiB
llm_load_tensors:      CUDA6 buffer size = 18324.66 MiB
....................................................................................................
llama_new_context_with_model: n_ctx      = 8192
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 500000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:      CUDA0 KV buffer size =   384.00 MiB
llama_kv_cache_init:      CUDA1 KV buffer size =   384.00 MiB
llama_kv_cache_init:      CUDA2 KV buffer size =   352.00 MiB
llama_kv_cache_init:      CUDA3 KV buffer size =   384.00 MiB
llama_kv_cache_init:      CUDA4 KV buffer size =   352.00 MiB
llama_kv_cache_init:      CUDA5 KV buffer size =   384.00 MiB
llama_kv_cache_init:      CUDA6 KV buffer size =   320.00 MiB
llama_new_context_with_model: KV self size  = 2560.00 MiB, K (f16): 1280.00 MiB, V (f16): 1280.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     0.49 MiB
llama_new_context_with_model: pipeline parallelism enabled (n_copies=4)
llama_new_context_with_model:      CUDA0 compute buffer size =  1216.01 MiB
llama_new_context_with_model:      CUDA1 compute buffer size =  1216.01 MiB
llama_new_context_with_model:      CUDA2 compute buffer size =  1216.01 MiB
llama_new_context_with_model:      CUDA3 compute buffer size =  1216.01 MiB
llama_new_context_with_model:      CUDA4 compute buffer size =  1216.01 MiB
llama_new_context_with_model:      CUDA5 compute buffer size =  1216.01 MiB
llama_new_context_with_model:      CUDA6 compute buffer size =  1216.02 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =    80.02 MiB
llama_new_context_with_model: graph nodes  = 2566
llama_new_context_with_model: graph splits = 8
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | AVX512_BF16 = 0 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | 
Model metadata: {'tokenizer.ggml.eos_token_id': '128001', 'general.quantization_version': '2', 'tokenizer.ggml.model': 'gpt2', 'llama.rope.dimension_count': '128', 'llama.vocab_size': '128256', 'general.file_type': '1', 'llama.attention.layer_norm_rms_epsilon': '0.000010', 'general.architecture': 'llama', 'llama.rope.freq_base': '500000.000000', 'tokenizer.ggml.bos_token_id': '128000', 'llama.attention.head_count': '64', 'tokenizer.ggml.pre': 'llama-bpe', 'llama.context_length': '131072', 'general.name': '7740ff69081bd553f4879f71eebcc2d6df2fbcb3', 'general.finetune': '7740ff69081bd553f4879f71eebcc2d6df2fbcb3', 'general.type': 'model', 'general.size_label': '71B', 'general.license': 'llama3.1', 'llama.feed_forward_length': '28672', 'llama.embedding_length': '8192', 'llama.block_count': '80', 'llama.attention.head_count_kv': '8'}
Using fallback chat format: llama-2
02:16:56-962177 INFO     Loaded "Meta-Llama-3.1-70B-F16.gguf" in 99.63 seconds.               
02:16:57-007652 INFO     LOADER: "llama.cpp"                                                  
02:16:57-008348 INFO     TRUNCATION LENGTH: 8192                                              
02:16:57-009061 INFO     INSTRUCTION TEMPLATE: "Alpaca"
```

**Comment by youkaichao** [comment]
you are hitting an extreme edge case, trying to use 7 GPUs to serve 131GB model. so you need to care about lots of things:

1. the default `gpu_memory_utilization` is 0.9 . You might need to increase it to 0.95 or 0.98
2. the default partition of pipeline parallel is to evenly partition the layers, but the first gpu also needs to store the word embedding, while the last gpu needs to store the lm head. if you want to balance the gpu memory pressure, you can set the environment variable `VLLM_PP_LAYER_PARTITION` to the partition you want, e.g. set a small value for the first and the last. see https://github.com/vllm-project/vllm/blob/main/tests/distributed/test_pipeline_partition.py for example to see how to set it.
3. the ultimate solution is to offload some weights to cpu, at the cost of slow execution. see the `--cpu-offload-gb` section in https://docs.vllm.ai/en/latest/models/engine_args.html

**Comment by leszekhanusz** [comment]
Thanks for all your clarifications.

I've quantized the model to Q6_K to reduce the size to a more reasonable 54GiB and now it is working correctly with vllm, spreading the load on all the gpus.

But vllm still uses way more VRAM than llama.cpp just for loading the model. I've compared using nvidia-smi to check the VRAM used just after the model has been loaded.

### memory usage for each GPU in MiB

#### vllm

16645
15355
15355
15355
15355
15355
20459

Total: 113879 MiB

#### llama.cpp

9897
9897
9195
9897
9195
9897
9317

Total: 67295 MiB

So vllm uses ~70% more VRAM than llama.cpp just after loading the model, and the load is much more balanced between the gpus by default. Using your `VLLM_PP_LAYER_PARTITION` might equalize the situation a bit.

Closing this issue as it now works.

**Comment by youkaichao** [comment]
I think vllm and llama.cpp have different purpose. vllm aims for high throughput serving, and will take as much memory as possible.

if you want vllm to take less memory, adjust `gpu_memory_utilization` .

**Comment by IEI-mjx** [comment]
Hi, @youkaichao 
I encountered this  error when using `VLLM_PP_LAYER_PARTITION`
![image](https://github.com/user-attachments/assets/7487ab10-da8d-4ab1-9508-632106bd0f2f)
