### ISSUE TITLE
[Usage]: OOM when using Llama-3.2-11B-Vision-Instruct

### ISSUE THREAD

**Issue by hrson-1203** [vllm-project/vllm#8879]
### Your current environment

```text
The output of `python collect_env.py`
```
Collecting environment information...
PyTorch version: 2.4.0+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.31

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-117-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 12.1.66
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA A100 80GB PCIe
GPU 1: NVIDIA A100 80GB PCIe

Nvidia driver version: 535.171.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Byte Order:                           Little Endian
Address sizes:                        46 bits physical, 57 bits virtual
CPU(s):                               64
On-line CPU(s) list:                  0-63
Thread(s) per core:                   2
Core(s) per socket:                   16
Socket(s):                            2
NUMA node(s):                         2
Vendor ID:                            GenuineIntel
CPU family:                           6
Model:                                106
Model name:                           Intel(R) Xeon(R) Gold 6326 CPU @ 2.90GHz
Stepping:                             6
CPU MHz:                              806.789
CPU max MHz:                          3500.0000
CPU min MHz:                          800.0000
BogoMIPS:                             5800.00
Virtualization:                       VT-x
L1d cache:                            1.5 MiB
L1i cache:                            1 MiB
L2 cache:                             40 MiB
L3 cache:                             48 MiB
NUMA node0 CPU(s):                    0-15,32-47
NUMA node1 CPU(s):                    16-31,48-63
Vulnerability Gather data sampling:   Mitigation; Microcode
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI SW loop, KVM SW loop
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==9.1.0.70
[pip3] nvidia-cufft-cu12==11.0.2.54
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-ml-py==12.535.161
[pip3] nvidia-nccl-cu12==2.20.5
[pip3] nvidia-nvjitlink-cu12==12.6.68
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] pyzmq==25.1.2
[pip3] torch==2.4.0
[pip3] torchvision==0.19.0
[pip3] transformers==4.45.0
[pip3] triton==3.0.0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
[conda] nvidia-ml-py              12.535.161               pypi_0    pypi
[conda] nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.6.68                  pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
[conda] pyzmq                     26.2.0                   pypi_0    pypi
[conda] torch                     2.4.0                    pypi_0    pypi
[conda] torchvision               0.19.0                   pypi_0    pypi
[conda] transformers              4.45.0                   pypi_0    pypi
[conda] triton                    3.0.0                    pypi_0    pypi
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: N/A
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
[4mGPU0	GPU1	CPU Affinity	NUMA Affinity	GPU NUMA ID[0m
GPU0	 X 	NV12	0-15,32-47	0		N/A
GPU1	NV12	 X 	0-15,32-47	0		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

### How would you like to use vllm

I want to run inference of a [meta-llama/Llama-3.2-11B-Vision-Instruct](https://huggingface.co/meta-llama/Llama-3.2-11B-Vision-Instruct). 

I tried to load the multi-modal model into vllm and proceed with inference.
However, even with two A100s, an OOM error occurred while loading the 11B model.

The error message below indicates that only A100 was used.
Even if both are used, the same OOM occurs.

How can I load the Llama-3.2-11B-Vision-Instruct model with vllm?

```Error Message
- Using vLLM
Args - Namespace(gpu_devices='0', model='meta-llama/Llama-3.2-11B-Vision-Instruct', model_len=4096)
INFO 09-27 11:18:06 llm_engine.py:226] Initializing an LLM engine (v0.6.1.dev238+ge2c6e0a82) with config: model='meta-llama/Llama-3.2-11B-Vision-Instruct', speculative_config=None, tokenizer='meta-llama/Llama-3.2-11B-Vision-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=meta-llama/Llama-3.2-11B-Vision-Instruct, use_v2_block_manager=False, num_scheduler_steps=1, multi_step_stream_outputs=False, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=False, mm_processor_kwargs=None)
INFO 09-27 11:18:07 enc_dec_model_runner.py:140] EncoderDecoderModelRunner requires XFormers backend; overriding backend auto-selection and forcing XFormers.
INFO 09-27 11:18:07 selector.py:116] Using XFormers backend.
/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/xformers/ops/fmha/flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/xformers/ops/fmha/flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
INFO 09-27 11:18:16 model_runner.py:1014] Starting to load model meta-llama/Llama-3.2-11B-Vision-Instruct...
INFO 09-27 11:18:17 selector.py:116] Using XFormers backend.
INFO 09-27 11:18:18 weight_utils.py:242] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/5 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  20% Completed | 1/5 [00:00<00:00,  4.18it/s]
Loading safetensors checkpoint shards:  40% Completed | 2/5 [00:01<00:01,  1.64it/s]
Loading safetensors checkpoint shards:  60% Completed | 3/5 [00:01<00:01,  1.37it/s]
Loading safetensors checkpoint shards:  80% Completed | 4/5 [00:02<00:00,  1.28it/s]
Loading safetensors checkpoint shards: 100% Completed | 5/5 [00:03<00:00,  1.25it/s]
Loading safetensors checkpoint shards: 100% Completed | 5/5 [00:03<00:00,  1.36it/s]

INFO 09-27 11:18:22 model_runner.py:1025] Loading model weights took 19.9073 GB
INFO 09-27 11:18:35 enc_dec_model_runner.py:297] Starting profile run for multi-modal models.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/home/heerak/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
[rank0]:     cli.main()
[rank0]:   File "/home/heerak/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
[rank0]:     run()
[rank0]:   File "/home/heerak/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
[rank0]:     runpy.run_path(target, run_name="__main__")
[rank0]:   File "/home/heerak/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
[rank0]:     return _run_module_code(code, init_globals, run_name,
[rank0]:   File "/home/heerak/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
[rank0]:     _run_code(code, mod_globals, init_globals,
[rank0]:   File "/home/heerak/.vscode-server/extensions/ms-python.debugpy-2024.10.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/home/heerak/workspace/cw-llm-eval/generator.py", line 37, in <module>
[rank0]:     llm = LLM(
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 214, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 564, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 339, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 474, in _initialize_kv_caches
[rank0]:     self.model_executor.determine_num_available_blocks())
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 114, in determine_num_available_blocks
[rank0]:     return self.driver_worker.determine_num_available_blocks()
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/worker/worker.py", line 223, in determine_num_available_blocks
[rank0]:     self.model_runner.profile_run()
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/worker/enc_dec_model_runner.py", line 348, in profile_run
[rank0]:     self.execute_model(model_input, kv_caches, intermediate_tensors)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/worker/enc_dec_model_runner.py", line 201, in execute_model
[rank0]:     hidden_or_intermediate_states = model_executable(
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/model_executor/models/mllama.py", line 1084, in forward
[rank0]:     cross_attention_states = self.vision_model(pixel_values,
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/model_executor/models/mllama.py", line 556, in forward
[rank0]:     output = self.transformer(
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/model_executor/models/mllama.py", line 430, in forward
[rank0]:     hidden_states = encoder_layer(
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/model_executor/models/mllama.py", line 398, in forward
[rank0]:     hidden_state = self.mlp(hidden_state)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/model_executor/models/clip.py", line 278, in forward
[rank0]:     hidden_states, _ = self.fc1(hidden_states)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 367, in forward
[rank0]:     output_parallel = self.quant_method.apply(self, input_, bias)
[rank0]:   File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 135, in apply
[rank0]:     return F.linear(x, layer.weight, bias)
[rank0]: torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 15.70 GiB. GPU 0 has a total capacity of 79.15 GiB of which 4.05 GiB is free. Including non-PyTorch memory, this process has 75.09 GiB memory in use. Of the allocated memory 62.54 GiB is allocated by PyTorch, and 12.05 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by DarkLight1337** [comment]
To split the model across GPUs, you should set `tensor_parallel_size` argument to the number of GPUs.

**Comment by hrson-1203** [comment]
> To split the model across GPUs, you should set `tensor_parallel_size` argument to the number of GPUs.

Of course, I tried it with 2 A100 settings.

If it's 11B, wouldn't it be possible to use approximately 22GB of memory?

**Comment by DarkLight1337** [comment]
You should also consider the memory required for inference, not just the model weights. If you run into OOM issues, you may need to reduce `max_model_len` and/or `max_num_seqs` as shown in [the example script](https://github.com/vllm-project/vllm/blob/main/examples/offline_inference_vision_language.py).

**Comment by hrson-1203** [comment]
> You should also consider the memory required for inference, not just the model weights. If you run into OOM issues, you may need to reduce `max_model_len` and/or `max_num_seqs` as shown in [the example script](https://github.com/vllm-project/vllm/blob/main/examples/offline_inference_vision_language.py).

@DarkLight1337 
```python
llm = LLM(
    model="meta-llama/Llama-3.2-11B-Vision-Instruct",
    tensor_parallel_size=2,
    max_model_len=4096,
    gpu_memory_utilization=0.8,
    trust_remote_code=True,  # !
)
```

When you run the above code, lines 338 to 339 of llm_engine.py
```python
if not self.model_config.embedding_mode:
    self._initialize_kv_caches()
```
An error occurs when running here.

**Comment by DarkLight1337** [comment]
How did you install vLLM? I see in the output of `collect_env.py`

```
ROCM Version: Could not collect
Neuron SDK Version: N/A
vLLM Version: N/A
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
�[4mGPU0 GPU1 CPU Affinity NUMA Affinity GPU NUMA ID�[0m
GPU0 X NV12 0-15,32-47 0 N/A
GPU1 NV12 X 0-15,32-47 0 N/A
```

**Comment by hrson-1203** [comment]
> How did you install vLLM? I see in the output of `collect_env.py`
> 
> ```
> ROCM Version: Could not collect
> Neuron SDK Version: N/A
> vLLM Version: N/A
> vLLM Build Flags:
> CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
> GPU Topology:
> �[4mGPU0 GPU1 CPU Affinity NUMA Affinity GPU NUMA ID�[0m
> GPU0 X NV12 0-15,32-47 0 N/A
> GPU1 NV12 X 0-15,32-47 0 N/A
> ```

I don't know why vllm version is not included;;

I'm using `vllm==0.6.2`

**Comment by DarkLight1337** [comment]
What is the command you used to install vLLM?

**Comment by hrson-1203** [comment]
> What is the command you used to install vLLM?

I created a conda virtual environment and installed vllm using the `pip install vllm` command.

**Comment by DarkLight1337** [comment]
@youkaichao @dtrifiro There seems to be something wrong with `collect_env.py`, can you look into this? I suspect it has something to do with the recent change to using setuptools-scm.

**Comment by DarkLight1337** [comment]
> When �I run the above code, lines 338 to 339 of llm_engine.py
> 
> ```python
> if not self.model_config.embedding_mode:
>     self._initialize_kv_caches()
> ```
> 
> An error occurs when running here.

Can you show more about the error?

**Comment by hrson-1203** [comment]
> > When �I run the above code, lines 338 to 339 of llm_engine.py
> > ```python
> > if not self.model_config.embedding_mode:
> >     self._initialize_kv_caches()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > An error occurs when running here.
> 
> Can you show more about the error?

I'm continuing debugging now;; 
Other than the error message that appeared when I first wrote the issue, nothing appears.

I'm still debugging so I don't know exactly where the error occurred.

**Comment by hrson-1203** [comment]
File "/home/heerak/miniconda3/envs/eval/lib/python3.10/site-packages/vllm/model_executor/models/mllama.py", line 1084, in forward
cross_attention_states = self.vision_model(pixel_values,

In this part, OOM occurs as the memory continues to increase as it passes forward.

**Comment by ywang96** [comment]
@hrson-1203 You should only need to set `max_num_seqs=16` and `enforce_eager=True` in order to launch the model.

**Comment by hrson-1203** [comment]
> `max_num_seqs=16` and `enforce_eager=True`

Oh, it finally works.

Could you also explain why we need to use `max_num_seqs=16` and `enforce_eager=True`?

**Comment by ywang96** [comment]
> Could you also explain why we need to use `max_num_seqs=16` and `enforce_eager=True`?

Mostly because of its architecture.

`max_num_seqs=16`: this model has a context length of 128k+ plus the additional block tables for cross-attention layers, so the default setting `max_num_seqs=256` won't work.

`enforce_eager=True`: By default we turned on cuda graph for decoder-only language models, the cross attention layers in this model are only needed at inference time if there's an image. This dynamic nature is compatible with the current cuda graph implementation, and supporting it is WIP.

**Comment by hrson-1203** [comment]
> > Could you also explain why we need to use `max_num_seqs=16` and `enforce_eager=True`?
> 
> Mostly because of its architecture.
> 
> `max_num_seqs=16`: this model has a context length of 128k+ plus the additional block tables for cross-attention layers, so the default setting `max_num_seqs=256` won't work.
> 
> `enforce_eager=True`: By default we turned on cuda graph for decoder-only language models, but the cross attention layers in this model are only needed at inference time if there's an image. This dynamic nature is compatible with the current cuda graph implementation, and supporting it is WIP.

thank you so much for explaining

Thanks to you, I was able to test it.

What parts of each model should I look at to figure out if such a setting is necessary?

**Comment by ywang96** [comment]
> What parts of each model should I look at to figure out if such a setting is necessary?

For most models, you don't need to worry about enforcing eager mode unless you need additional VRAM (This is because cuda graphs themselves also consume some memory), and if you run into OOM issue, always try lowering `max_num_seqs`.

**Comment by swapnil3597** [comment]
I'm trying to run `meta-llama/Llama-3.2-11B-Vision-Instruct` using vLLM docker:

**GPU Server specifications:**

- GPU Count: 4
- GPU Type: A100 - 80GB

**vLLM Docker run command:**
```bash
docker run  --gpus all \
    -v /data/hf_cache/ \
    --env "HUGGING_FACE_HUB_TOKEN=<token>" \
    -p 8000:8000 \
    --ipc=host \
    vllm/vllm-openai:latest \
    --model meta-llama/Llama-3.2-11B-Vision-Instruct \
    --tensor-parallel-size 4 \
    --max-model-len 4096 \
    --download_dir /data/vllm_cache \
    --enforce-eager
```

Facing similar issue.

**Comment by DarkLight1337** [comment]
> I'm trying to run `meta-llama/Llama-3.2-11B-Vision-Instruct` using vLLM docker:
> 
> **GPU Server specifications:**
> 
> * GPU Count: 4
> * GPU Type: A100 - 80GB
> 
> **vLLM Docker run command:**
> 
> ```shell
> docker run  --gpus all \
>     -v /data/hf_cache/ \
>     --env "HUGGING_FACE_HUB_TOKEN=<token>" \
>     -p 8000:8000 \
>     --ipc=host \
>     vllm/vllm-openai:latest \
>     --model meta-llama/Llama-3.2-11B-Vision-Instruct \
>     --tensor-parallel-size 4 \
>     --max-model-len 4096 \
>     --download_dir /data/vllm_cache \
>     --enforce-eager
> ```
> 
> Facing similar issue.

As mentioned above, you should limit `--max-num-seqs` to a smaller value, e.g. 16.

**Comment by dtrifiro** [comment]
@DarkLight1337 fix is included in https://github.com/vllm-project/vllm/pull/8900

**Comment by Reichenbachian** [comment]
Found this very useful. Appreciate the guidance @DarkLight1337

**Comment by rdaiello** [comment]
Thank you @DarkLight1337. This solved my issue as well.

**Comment by SMAntony** [comment]
> Found this thread very useful. Appreciate the guidance and generally all your work on the vllm multimodal models @DarkLight1337

Thanks for conveying my exact thoughts. Appreciate ur help @DarkLight1337.

**Comment by hahmad2008** [comment]
@ywang96 @DarkLight1337 

I encountered issue while loading this model with the latest vLLM `0.8.3` using the same arguments you recommended. Even with `  VLLM_USE_V1=0 `

- resources: 4 A10 (each with 24G)
- command: `  vllm serve  unsloth/Llama-3.2-11B-Vision-Instruct  --tensor-parallel-size 4   --enforce-eager --max-num-seqs 16 `
- error:
```
INFO 04-15 19:30:49 [__init__.py:239] Automatically detected platform cuda.
INFO 04-15 19:30:59 [api_server.py:1034] vLLM API server version 0.8.3
INFO 04-15 19:30:59 [api_server.py:1035] args: Namespace(subparser='serve', model_tag='unsloth/Llama-3.2-11B-Vision-Instruct', config='', host=None, port=8000, uvicorn_log_level='info', disable_uvicorn_access_log=False, allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, chat_template_content_format='auto', response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, enable_ssl_refresh=False, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, enable_request_id_headers=False, enable_auto_tool_choice=False, tool_call_parser=None, tool_parser_plugin='', model='unsloth/Llama-3.2-11B-Vision-Instruct', task='auto', tokenizer=None, hf_config_path=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, allowed_local_media_path=None, download_dir=None, load_format='auto', config_format=<ConfigFormat.AUTO: 'auto'>, dtype='auto', kv_cache_dtype='auto', max_model_len=None, guided_decoding_backend='xgrammar', logits_processor_pattern=None, model_impl='auto', distributed_executor_backend=None, pipeline_parallel_size=1, tensor_parallel_size=4, data_parallel_size=1, enable_expert_parallel=False, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=None, enable_prefix_caching=None, prefix_caching_hash_algo='builtin', disable_sliding_window=False, use_v2_block_manager=True, num_lookahead_slots=0, seed=None, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_partial_prefills=1, max_long_partial_prefills=1, long_prefill_token_threshold=0, max_num_seqs=16, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, hf_overrides=None, enforce_eager=True, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, limit_mm_per_prompt=None, mm_processor_kwargs=None, disable_mm_preprocessor_cache=False, enable_lora=False, enable_lora_bias=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', num_scheduler_steps=1, use_tqdm_on_load=True, multi_step_stream_outputs=True, scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_config=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, disable_async_output_proc=False, scheduling_policy='fcfs', scheduler_cls='vllm.core.scheduler.Scheduler', override_neuron_config=None, override_pooler_config=None, compilation_config=None, kv_transfer_config=None, worker_cls='auto', worker_extension_cls='', generation_config='auto', override_generation_config=None, enable_sleep_mode=False, calculate_kv_scales=False, additional_config=None, enable_reasoning=False, reasoning_parser=None, disable_cascade_attn=False, disable_log_requests=False, max_log_len=None, disable_fastapi_docs=False, enable_prompt_tokens_details=False, enable_server_load_tracking=False, dispatch_function=<function ServeSubcommand.cmd at 0x70b803e67160>)
INFO 04-15 19:31:23 [config.py:600] This model supports multiple tasks: {'reward', 'generate', 'classify', 'score', 'embed'}. Defaulting to 'generate'.
WARNING 04-15 19:31:31 [arg_utils.py:1708] ['MllamaForConditionalGeneration'] is not supported by the V1 Engine. Falling back to V0. 
WARNING 04-15 19:31:31 [arg_utils.py:1581] The model has a long context length (131072). This may causeOOM during the initial memory profiling phase, or result in low performance due to small KV cache size. Consider setting --max-model-len to a smaller value.
INFO 04-15 19:31:32 [config.py:1600] Defaulting to use mp for distributed inference
WARNING 04-15 19:31:32 [cuda.py:96] To see benefits of async output processing, enable CUDA graph. Since, enforce-eager is enabled, async output processor cannot be used
INFO 04-15 19:31:32 [api_server.py:246] Started engine process with PID 32156
INFO 04-15 19:31:35 [__init__.py:239] Automatically detected platform cuda.
INFO 04-15 19:31:37 [llm_engine.py:242] Initializing a V0 LLM engine (v0.8.3) with config: model='unsloth/Llama-3.2-11B-Vision-Instruct', speculative_config=None, tokenizer='unsloth/Llama-3.2-11B-Vision-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=auto, tensor_parallel_size=4, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar', reasoning_backend=None), observability_config=ObservabilityConfig(show_hidden_metrics=False, otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=None, served_model_name=unsloth/Llama-3.2-11B-Vision-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=False, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=True, 
WARNING 04-15 19:31:38 [multiproc_worker_utils.py:306] Reducing Torch parallelism from 24 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 04-15 19:31:39 [cuda.py:292] Using Flash Attention backend.
INFO 04-15 19:31:41 [__init__.py:239] Automatically detected platform cuda.
INFO 04-15 19:31:41 [__init__.py:239] Automatically detected platform cuda.
INFO 04-15 19:31:41 [__init__.py:239] Automatically detected platform cuda.
(VllmWorkerProcess pid=32287) INFO 04-15 19:31:42 [multiproc_worker_utils.py:225] Worker ready; awaiting tasks
(VllmWorkerProcess pid=32286) INFO 04-15 19:31:42 [multiproc_worker_utils.py:225] Worker ready; awaiting tasks
(VllmWorkerProcess pid=32288) INFO 04-15 19:31:42 [multiproc_worker_utils.py:225] Worker ready; awaiting tasks
(VllmWorkerProcess pid=32287) INFO 04-15 19:31:44 [cuda.py:292] Using Flash Attention backend.
(VllmWorkerProcess pid=32286) INFO 04-15 19:31:44 [cuda.py:292] Using Flash Attention backend.
(VllmWorkerProcess pid=32288) INFO 04-15 19:31:44 [cuda.py:292] Using Flash Attention backend.
INFO 04-15 19:31:47 [utils.py:990] Found nccl from library libnccl.so.2
INFO 04-15 19:31:47 [pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=32286) INFO 04-15 19:31:47 [utils.py:990] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=32286) INFO 04-15 19:31:47 [pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=32287) INFO 04-15 19:31:47 [utils.py:990] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=32287) INFO 04-15 19:31:47 [pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=32288) INFO 04-15 19:31:47 [utils.py:990] Found nccl from library libnccl.so.2
(VllmWorkerProcess pid=32288) INFO 04-15 19:31:47 [pynccl.py:69] vLLM is using nccl==2.21.5
(VllmWorkerProcess pid=32286) WARNING 04-15 19:31:49 [custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
(VllmWorkerProcess pid=32287) WARNING 04-15 19:31:49 [custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
(VllmWorkerProcess pid=32288) WARNING 04-15 19:31:49 [custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
WARNING 04-15 19:31:49 [custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
INFO 04-15 19:31:49 [shm_broadcast.py:264] vLLM message queue communication handle: Handle(local_reader_ranks=[1, 2, 3], buffer_handle=(3, 4194304, 6, 'psm_40a32e37'), local_subscribe_addr='ipc:///tmp/b95cda4f-e26a-43cd-a759-fbf4b6d99695', remote_subscribe_addr=None, remote_addr_ipv6=False)
(VllmWorkerProcess pid=32288) INFO 04-15 19:31:49 [parallel_state.py:957] rank 3 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 3
INFO 04-15 19:31:49 [parallel_state.py:957] rank 0 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 0
(VllmWorkerProcess pid=32287) INFO 04-15 19:31:49 [parallel_state.py:957] rank 2 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 2
(VllmWorkerProcess pid=32286) INFO 04-15 19:31:49 [parallel_state.py:957] rank 1 in world size 4 is assigned as DP rank 0, PP rank 0, TP rank 1
INFO 04-15 19:31:49 [model_runner.py:1110] Starting to load model unsloth/Llama-3.2-11B-Vision-Instruct...
(VllmWorkerProcess pid=32287) INFO 04-15 19:31:49 [model_runner.py:1110] Starting to load model unsloth/Llama-3.2-11B-Vision-Instruct...
(VllmWorkerProcess pid=32288) INFO 04-15 19:31:49 [model_runner.py:1110] Starting to load model unsloth/Llama-3.2-11B-Vision-Instruct...
(VllmWorkerProcess pid=32286) INFO 04-15 19:31:49 [model_runner.py:1110] Starting to load model unsloth/Llama-3.2-11B-Vision-Instruct...
INFO 04-15 19:31:50 [weight_utils.py:265] Using model weights format ['*.safetensors']
(VllmWorkerProcess pid=32286) INFO 04-15 19:31:50 [weight_utils.py:265] Using model weights format ['*.safetensors']
(VllmWorkerProcess pid=32287) INFO 04-15 19:31:50 [weight_utils.py:265] Using model weights format ['*.safetensors']
(VllmWorkerProcess pid=32288) INFO 04-15 19:31:50 [weight_utils.py:265] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/5 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  40% Completed | 2/5 [00:00<00:00,  4.26it/s]
Loading safetensors checkpoint shards:  60% Completed | 3/5 [00:00<00:00,  3.10it/s]
Loading safetensors checkpoint shards:  80% Completed | 4/5 [00:01<00:00,  2.75it/s]
Loading safetensors checkpoint shards: 100% Completed | 5/5 [00:01<00:00,  2.58it/s]
Loading safetensors checkpoint shards: 100% Completed | 5/5 [00:01<00:00,  2.81it/s]

INFO 04-15 19:31:53 [loader.py:447] Loading weights took 1.87 seconds
INFO 04-15 19:31:53 [model_runner.py:1146] Model loading took 5.1131 GiB and 3.217802 seconds
(VllmWorkerProcess pid=32287) INFO 04-15 19:31:53 [loader.py:447] Loading weights took 1.81 seconds
(VllmWorkerProcess pid=32287) INFO 04-15 19:31:53 [model_runner.py:1146] Model loading took 5.1131 GiB and 3.419883 seconds
(VllmWorkerProcess pid=32288) INFO 04-15 19:31:53 [loader.py:447] Loading weights took 1.86 seconds
(VllmWorkerProcess pid=32288) INFO 04-15 19:31:53 [model_runner.py:1146] Model loading took 5.1131 GiB and 3.722966 seconds
(VllmWorkerProcess pid=32286) INFO 04-15 19:31:53 [loader.py:447] Loading weights took 1.85 seconds
(VllmWorkerProcess pid=32286) INFO 04-15 19:31:53 [model_runner.py:1146] Model loading took 5.1131 GiB and 3.953340 seconds
(VllmWorkerProcess pid=32288) INFO 04-15 19:31:54 [enc_dec_model_runner.py:278] Starting profile run for multi-modal models.
(VllmWorkerProcess pid=32287) INFO 04-15 19:31:54 [enc_dec_model_runner.py:278] Starting profile run for multi-modal models.
(VllmWorkerProcess pid=32286) INFO 04-15 19:31:54 [enc_dec_model_runner.py:278] Starting profile run for multi-modal models.
INFO 04-15 19:31:54 [enc_dec_model_runner.py:278] Starting profile run for multi-modal models.
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238] Exception in worker VllmWorkerProcess while processing method determine_num_available_blocks.
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238] Traceback (most recent call last):
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/executor/multiproc_worker_utils.py", line 232, in _run_worker_process
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     output = run_method(worker, method, args, kwargs)
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/utils.py", line 2347, in run_method
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/worker/worker.py", line 229, in determine_num_available_blocks
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     self.model_runner.profile_run()
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/worker/enc_dec_model_runner.py", line 329, in profile_run
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     self.execute_model(model_input, None, intermediate_tensors)
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/worker/enc_dec_model_runner.py", line 182, in execute_model
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     hidden_or_intermediate_states = model_executable(
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/model_executor/models/mllama.py", line 1446, in forward
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     assert actual_len >= last_group_len
(VllmWorkerProcess pid=32287) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238] AssertionError
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238] Exception in worker VllmWorkerProcess while processing method determine_num_available_blocks.
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238] Traceback (most recent call last):
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/executor/multiproc_worker_utils.py", line 232, in _run_worker_process
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     output = run_method(worker, method, args, kwargs)
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/utils.py", line 2347, in run_method
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/worker/worker.py", line 229, in determine_num_available_blocks
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     self.model_runner.profile_run()
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/worker/enc_dec_model_runner.py", line 329, in profile_run
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     self.execute_model(model_input, None, intermediate_tensors)
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/worker/enc_dec_model_runner.py", line 182, in execute_model
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     hidden_or_intermediate_states = model_executable(
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/model_executor/models/mllama.py", line 1446, in forward
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     assert actual_len >= last_group_len
(VllmWorkerProcess pid=32286) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238] AssertionError
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238] Exception in worker VllmWorkerProcess while processing method determine_num_available_blocks.
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238] Traceback (most recent call last):
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/executor/multiproc_worker_utils.py", line 232, in _run_worker_process
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     output = run_method(worker, method, args, kwargs)
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/utils.py", line 2347, in run_method
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/worker/worker.py", line 229, in determine_num_available_blocks
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     self.model_runner.profile_run()
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/worker/enc_dec_model_runner.py", line 329, in profile_run
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     self.execute_model(model_input, None, intermediate_tensors)
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return func(*args, **kwargs)
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/worker/enc_dec_model_runner.py", line 182, in execute_model
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     hidden_or_intermediate_states = model_executable(
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return self._call_impl(*args, **kwargs)
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     return forward_call(*args, **kwargs)
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]   File "/lib/python3.9/site-packages/vllm/model_executor/models/mllama.py", line 1446, in forward
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238]     assert actual_len >= last_group_len
(VllmWorkerProcess pid=32288) ERROR 04-15 19:31:59 [multiproc_worker_utils.py:238] AssertionError
ERROR 04-15 19:31:59 [engine.py:448] 
Traceback (most recent call last):
  File "/lib/python3.9/site-packages/vllm/engine/multiprocessing/engine.py", line 436, in run_mp_engine
    engine = MQLLMEngine.from_vllm_config(
  File "/lib/python3.9/site-packages/vllm/engine/multiprocessing/engine.py", line 128, in from_vllm_config
    return cls(
  File "/lib/python3.9/site-packages/vllm/engine/multiprocessing/engine.py", line 82, in __init__
    self.engine = LLMEngine(*args, **kwargs)
  File "/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 284, in __init__
    self._initialize_kv_caches()
  File "/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 433, in _initialize_kv_caches
    self.model_executor.determine_num_available_blocks())
  File "/lib/python3.9/site-packages/vllm/executor/executor_base.py", line 103, in determine_num_available_blocks
    results = self.collective_rpc("determine_num_available_blocks")
  File "/lib/python3.9/site-packages/vllm/executor/executor_base.py", line 331, in collective_rpc
    return self._run_workers(method, *args, **(kwargs or {}))
  File "/lib/python3.9/site-packages/vllm/executor/mp_distributed_executor.py", line 185, in _run_workers
    driver_worker_output = run_method(self.driver_worker, sent_method,
  File "/lib/python3.9/site-packages/vllm/utils.py", line 2347, in run_method
    return func(*args, **kwargs)
  File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/lib/python3.9/site-packages/vllm/worker/worker.py", line 229, in determine_num_available_blocks
    self.model_runner.profile_run()
  File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/lib/python3.9/site-packages/vllm/worker/enc_dec_model_runner.py", line 329, in profile_run
    self.execute_model(model_input, None, intermediate_tensors)
  File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/lib/python3.9/site-packages/vllm/worker/enc_dec_model_runner.py", line 182, in execute_model
    hidden_or_intermediate_states = model_executable(
  File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/lib/python3.9/site-packages/vllm/model_executor/models/mllama.py", line 1446, in forward
    assert actual_len >= last_group_len
AssertionError
ERROR 04-15 19:32:00 [multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 32286 died, exit code: -15
ERROR 04-15 19:32:00 [multiproc_worker_utils.py:120] Worker VllmWorkerProcess pid 32288 died, exit code: -15
Process SpawnProcess-1:
INFO 04-15 19:32:00 [multiproc_worker_utils.py:124] Killing local vLLM worker processes
Traceback (most recent call last):
  File "/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/lib/python3.9/site-packages/vllm/engine/multiprocessing/engine.py", line 450, in run_mp_engine
    raise e
  File "/lib/python3.9/site-packages/vllm/engine/multiprocessing/engine.py", line 436, in run_mp_engine
    engine = MQLLMEngine.from_vllm_config(
  File "/lib/python3.9/site-packages/vllm/engine/multiprocessing/engine.py", line 128, in from_vllm_config
    return cls(
  File "/lib/python3.9/site-packages/vllm/engine/multiprocessing/engine.py", line 82, in __init__
    self.engine = LLMEngine(*args, **kwargs)
  File "/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 284, in __init__
    self._initialize_kv_caches()
  File "/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 433, in _initialize_kv_caches
    self.model_executor.determine_num_available_blocks())
  File "/lib/python3.9/site-packages/vllm/executor/executor_base.py", line 103, in determine_num_available_blocks
    results = self.collective_rpc("determine_num_available_blocks")
  File "/lib/python3.9/site-packages/vllm/executor/executor_base.py", line 331, in collective_rpc
    return self._run_workers(method, *args, **(kwargs or {}))
  File "/lib/python3.9/site-packages/vllm/executor/mp_distributed_executor.py", line 185, in _run_workers
    driver_worker_output = run_method(self.driver_worker, sent_method,
  File "/lib/python3.9/site-packages/vllm/utils.py", line 2347, in run_method
    return func(*args, **kwargs)
  File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/lib/python3.9/site-packages/vllm/worker/worker.py", line 229, in determine_num_available_blocks
    self.model_runner.profile_run()
  File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/lib/python3.9/site-packages/vllm/worker/enc_dec_model_runner.py", line 329, in profile_run
    self.execute_model(model_input, None, intermediate_tensors)
  File "/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/lib/python3.9/site-packages/vllm/worker/enc_dec_model_runner.py", line 182, in execute_model
    hidden_or_intermediate_states = model_executable(
  File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/lib/python3.9/site-packages/vllm/model_executor/models/mllama.py", line 1446, in forward
    assert actual_len >= last_group_len
AssertionError
[rank0]:[W415 19:32:01.448795244 ProcessGroupNCCL.cpp:1496] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
Traceback (most recent call last):
  File "/bin/vllm", line 8, in <module>
    sys.exit(main())
  File "/lib/python3.9/site-packages/vllm/entrypoints/cli/main.py", line 51, in main
    args.dispatch_function(args)
  File "/lib/python3.9/site-packages/vllm/entrypoints/cli/serve.py", line 27, in cmd
    uvloop.run(run_server(args))
  File "/lib/python3.9/site-packages/uvloop/__init__.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/lib/python3.9/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "/lib/python3.9/site-packages/vllm/entrypoints/openai/api_server.py", line 1069, in run_server
    async with build_async_engine_client(args) as engine_client:
  File "/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/lib/python3.9/site-packages/vllm/entrypoints/openai/api_server.py", line 146, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/lib/python3.9/site-packages/vllm/entrypoints/openai/api_server.py", line 269, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.
/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 3 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by hahmad2008** [comment]
Thanks @DarkLight1337 worked for VLLM  version`0.8.4`.
But I have a couple questions:
- Can I only pass `max-model-len`?  what is the max len then?
- What the `max-num-seq` represent here? if we pass `max-model-len` or not?
- why do we need `--enforce-eager` as well? can't work without it?

what about this warning:
```
WARNING 04-16 07:00:25 [profiling.py:217] The encoder sequence length used for profiling (max_num_batched_tokens / max_num_seqs = 1000)  is too short to hold the multi-modal embeddings in the worst case (6404 tokens in total, out of which {'image': 6404} are reserved for multi-modal embeddings). This may cause certain multi-modal inputs to fail during inference, even when the input text is short. To avoid this, you should increase `max_model_len`, reduce `max_num_seqs`, and/or reduce `mm_counts`.
```
@ywang96

**Comment by DarkLight1337** [comment]
`max_model_len` is basically the model's context length, while `max_num_seqs` is the maximum batch size to schedule in vLLM.

By default, CUDA graph is used to enhance the performance but that may lead to additional memory usage to store the graph. This is disabled by `--enforce-eager` flag.

**Comment by DarkLight1337** [comment]
It varies from model to model, mostly based on the model's config
