### ISSUE TITLE
[Bug]: vllm.LLM does not seem to re-initialize for distributed inference with subsequent models with Offline Inference

### ISSUE THREAD

**Issue by lhl** [vllm-project/vllm#9727]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
WARNING 10-27 01:12:13 rocm.py:13] `fork` method is not supported by ROCm. VLLM_WORKER_MULTIPROC_METHOD is overridden to `spawn` instead.
PyTorch version: 2.6.0.dev20241015+rocm6.2
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 6.2.41133-dd7f95766

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.30.5
Libc version: glibc-2.35

Python version: 3.11.10 | packaged by conda-forge | (main, Sep 30 2024, 18:08:57) [GCC 13.3.0] (64-bit runtime)
Python platform: Linux-6.8.0-47-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Instinct MI300X (gfx942:sramecc+:xnack-)
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 6.2.41133
MIOpen runtime version: 3.2.0
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        46 bits physical, 57 bits virtual
Byte Order:                           Little Endian
CPU(s):                               208
On-line CPU(s) list:                  0-207
Vendor ID:                            GenuineIntel
Model name:                           Intel(R) Xeon(R) Platinum 8470
CPU family:                           6
Model:                                143
Thread(s) per core:                   2
Core(s) per socket:                   52
Socket(s):                            2
Stepping:                             8
CPU max MHz:                          3800.0000
CPU min MHz:                          800.0000
BogoMIPS:                             4000.00
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect user_shstk avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts vnmi avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr ibt amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
Virtualization:                       VT-x
L1d cache:                            4.9 MiB (104 instances)
L1i cache:                            3.3 MiB (104 instances)
L2 cache:                             208 MiB (104 instances)
L3 cache:                             210 MiB (2 instances)
NUMA node(s):                         2
NUMA node0 CPU(s):                    0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62,64,66,68,70,72,74,76,78,80,82,84,86,88,90,92,94,96,98,100,102,104,106,108,110,112,114,116,118,120,122,124,126,128,130,132,134,136,138,140,142,144,146,148,150,152,154,156,158,160,162,164,166,168,170,172,174,176,178,180,182,184,186,188,190,192,194,196,198,200,202,204,206
NUMA node1 CPU(s):                    1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63,65,67,69,71,73,75,77,79,81,83,85,87,89,91,93,95,97,99,101,103,105,107,109,111,113,115,117,119,121,123,125,127,129,131,133,135,137,139,141,143,145,147,149,151,153,155,157,159,161,163,165,167,169,171,173,175,177,179,181,183,185,187,189,191,193,195,197,199,201,203,205,207
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI BHI_DIS_S
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] lion-pytorch==0.2.2
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] pytorch-triton-rocm==3.1.0+cf34004b8a
[pip3] pyzmq==26.2.0
[pip3] torch==2.6.0.dev20241015+rocm6.2
[pip3] torchao==0.5.0
[pip3] torchaudio==2.5.0.dev20241015+rocm6.2
[pip3] torchtune==0.3.1
[pip3] torchvision==0.20.0.dev20241015+rocm6.2
[pip3] transformers==4.45.2
[pip3] triton==3.1.0
[conda] lion-pytorch              0.2.2                    pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] pytorch-triton-rocm       3.1.0+cf34004b8a          pypi_0    pypi
[conda] pyzmq                     26.2.0          py311h7deb3e3_3    conda-forge
[conda] torch                     2.6.0.dev20241015+rocm6.2          pypi_0    pypi
[conda] torchao                   0.5.0                    pypi_0    pypi
[conda] torchaudio                2.5.0.dev20241015+rocm6.2          pypi_0    pypi
[conda] torchtune                 0.3.1                    pypi_0    pypi
[conda] torchvision               0.20.0.dev20241015+rocm6.2          pypi_0    pypi
[conda] transformers              4.45.2                   pypi_0    pypi
[conda] triton                    3.1.0                    pypi_0    pypi
ROCM Version: 6.2.41134-65d174c3e
Neuron SDK Version: N/A
vLLM Version: 0.6.3.post2.dev90+gb7df53cd
vLLM Build Flags:
CUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled
GPU Topology:
============================ ROCm System Management Interface ============================
================================ Weight between two GPUs =================================
       GPU0         GPU1         GPU2         GPU3         GPU4         GPU5         GPU6         GPU7
GPU0   0            15           15           15           15           15           15           15
GPU1   15           0            15           15           15           15           15           15
GPU2   15           15           0            15           15           15           15           15
GPU3   15           15           15           0            15           15           15           15
GPU4   15           15           15           15           0            15           15           15
GPU5   15           15           15           15           15           0            15           15
GPU6   15           15           15           15           15           15           0            15
GPU7   15           15           15           15           15           15           15           0

================================= Hops between two GPUs ==================================
       GPU0         GPU1         GPU2         GPU3         GPU4         GPU5         GPU6         GPU7
GPU0   0            1            1            1            1            1            1            1
GPU1   1            0            1            1            1            1            1            1
GPU2   1            1            0            1            1            1            1            1
GPU3   1            1            1            0            1            1            1            1
GPU4   1            1            1            1            0            1            1            1
GPU5   1            1            1            1            1            0            1            1
GPU6   1            1            1            1            1            1            0            1
GPU7   1            1            1            1            1            1            1            0

=============================== Link Type between two GPUs ===============================
       GPU0         GPU1         GPU2         GPU3         GPU4         GPU5         GPU6         GPU7
GPU0   0            XGMI         XGMI         XGMI         XGMI         XGMI         XGMI         XGMI
GPU1   XGMI         0            XGMI         XGMI         XGMI         XGMI         XGMI         XGMI
GPU2   XGMI         XGMI         0            XGMI         XGMI         XGMI         XGMI         XGMI
GPU3   XGMI         XGMI         XGMI         0            XGMI         XGMI         XGMI         XGMI
GPU4   XGMI         XGMI         XGMI         XGMI         0            XGMI         XGMI         XGMI
GPU5   XGMI         XGMI         XGMI         XGMI         XGMI         0            XGMI         XGMI
GPU6   XGMI         XGMI         XGMI         XGMI         XGMI         XGMI         0            XGMI
GPU7   XGMI         XGMI         XGMI         XGMI         XGMI         XGMI         XGMI         0

======================================= Numa Nodes =======================================
GPU[0]          : (Topology) Numa Node: 0
GPU[0]          : (Topology) Numa Affinity: 0
GPU[1]          : (Topology) Numa Node: 0
GPU[1]          : (Topology) Numa Affinity: 0
GPU[2]          : (Topology) Numa Node: 0
GPU[2]          : (Topology) Numa Affinity: 0
GPU[3]          : (Topology) Numa Node: 0
GPU[3]          : (Topology) Numa Affinity: 0
GPU[4]          : (Topology) Numa Node: 1
GPU[4]          : (Topology) Numa Affinity: 1
GPU[5]          : (Topology) Numa Node: 1
GPU[5]          : (Topology) Numa Affinity: 1
GPU[6]          : (Topology) Numa Node: 1
GPU[6]          : (Topology) Numa Affinity: 1
GPU[7]          : (Topology) Numa Node: 1
GPU[7]          : (Topology) Numa Affinity: 1
================================== End of ROCm SMI Log ===================================
```
</details>

### 🐛 Describe the bug

I am using `vllm.LLM` for offline inference, similar to https://docs.vllm.ai/en/latest/getting_started/examples/offline_inference.html

I am running the script for multiple models and reinit the LLM with a new one like:

```
        self.llm = LLM(
            model=model_name,
            trust_remote_code=True,
            tensor_parallel_size=8,
            gpu_memory_utilization=0.95,
            max_num_batched_tokens=1024,
            max_num_seqs=1024,
            max_model_len=1024,
            quantization="fp8",
        )
```

The first model load always loads and runs as expected:
```
Processing nvidia/Llama-3.1-Nemotron-70B-Instruct-HF: 100%|██████████████████████████████████████████████████████| 4066/4066 [06:47<00:00,  9.97examples/s]
INFO 10-26 18:45:38 multiproc_worker_utils.py:134] Terminating local vLLM worker processes
(VllmWorkerProcess pid=84353) INFO 10-26 18:45:38 multiproc_worker_utils.py:242] Worker exiting
(VllmWorkerProcess pid=84348) INFO 10-26 18:45:38 multiproc_worker_utils.py:242] Worker exiting
(VllmWorkerProcess pid=84349) INFO 10-26 18:45:38 multiproc_worker_utils.py:242] Worker exiting
(VllmWorkerProcess pid=84354) INFO 10-26 18:45:38 multiproc_worker_utils.py:242] Worker exiting
(VllmWorkerProcess pid=84352) INFO 10-26 18:45:38 multiproc_worker_utils.py:242] Worker exiting
(VllmWorkerProcess pid=84351) INFO 10-26 18:45:38 multiproc_worker_utils.py:242] Worker exiting
(VllmWorkerProcess pid=84350) INFO 10-26 18:45:38 multiproc_worker_utils.py:242] Worker exiting
2024-10-26 18:45:39,168 - INFO -
--------------------------------------------------
2024-10-26 18:45:39,171 - INFO - Results for nvidia/Llama-3.1-Nemotron-70B-Instruct-HF:
2024-10-26 18:45:39,172 - INFO - Backend: vLLM
2024-10-26 18:45:39,173 - INFO - Model load time: 424.43 seconds
2024-10-26 18:45:39,174 - INFO - Processing time: 407.85 seconds
2024-10-26 18:45:39,177 - INFO - Total time: 832.28 seconds
2024-10-26 18:45:39,179 - INFO - Speed: 9.97 examples/second
2024-10-26 18:45:39,179 - INFO - Total examples: 4066
2024-10-26 18:45:39,180 - INFO - Batch size: 1024
2024-10-26 18:45:39,180 - INFO - --------------------------------------------------
```

But on loading the second model I get this type of error (happens with each model I combo I sequence through, when loaded first, no problems, the subsequent models always have the same issue):
```
2024-10-26 18:45:39,182 - INFO - Attempting to load Qwen/Qwen2.5-32B-Instruct with vLLM backend...
INFO 10-26 18:45:45 config.py:887] Defaulting to use mp for distributed inference
INFO 10-26 18:45:45 config.py:916] Disabled the custom all-reduce kernel because it is not supported on AMD GPUs.
INFO 10-26 18:45:45 llm_engine.py:237] Initializing an LLM engine (v0.6.4.dev9+g5d264f4a) with config: model='Qwen/Qwen2.5-32B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-32B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=1024, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=8, pipeline_parallel_size=1, disable_custom_all_reduce=True, quantization=fp8, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=Qwen/Qwen2.5-32B-Instruct, use_v2_block_manager=True, num_scheduler_steps=1, chunked_prefill_enabled=False multi_step_stream_outputs=True, enable_prefix_caching=False, use_async_output_proc=True, use_cached_outputs=False, mm_processor_kwargs=None)
(VllmWorkerProcess pid=98756) INFO 10-26 18:45:56 selector.py:120] Using ROCmFlashAttention backend.
(VllmWorkerProcess pid=98754) INFO 10-26 18:45:56 selector.py:120] Using ROCmFlashAttention backend.
(VllmWorkerProcess pid=98755) INFO 10-26 18:45:56 selector.py:120] Using ROCmFlashAttention backend.
(VllmWorkerProcess pid=98757) INFO 10-26 18:45:56 selector.py:120] Using ROCmFlashAttention backend.
(VllmWorkerProcess pid=98758) INFO 10-26 18:45:56 selector.py:120] Using ROCmFlashAttention backend.
(VllmWorkerProcess pid=98759) INFO 10-26 18:45:56 selector.py:120] Using ROCmFlashAttention backend.
(VllmWorkerProcess pid=98756) INFO 10-26 18:45:56 multiproc_worker_utils.py:216] Worker ready; awaiting tasks
(VllmWorkerProcess pid=98753) INFO 10-26 18:45:56 selector.py:120] Using ROCmFlashAttention backend.
(VllmWorkerProcess pid=98754) INFO 10-26 18:45:56 multiproc_worker_utils.py:216] Worker ready; awaiting tasks
(VllmWorkerProcess pid=98755) INFO 10-26 18:45:56 multiproc_worker_utils.py:216] Worker ready; awaiting tasks
(VllmWorkerProcess pid=98757) INFO 10-26 18:45:56 multiproc_worker_utils.py:216] Worker ready; awaiting tasks
(VllmWorkerProcess pid=98758) INFO 10-26 18:45:56 multiproc_worker_utils.py:216] Worker ready; awaiting tasks
(VllmWorkerProcess pid=98759) INFO 10-26 18:45:56 multiproc_worker_utils.py:216] Worker ready; awaiting tasks
(VllmWorkerProcess pid=98753) INFO 10-26 18:45:56 multiproc_worker_utils.py:216] Worker ready; awaiting tasks
[E1026 18:54:43.118551298 socket.cpp:1010] [c10d] The client socket has timed out after 600000ms while trying to connect to (127.0.0.1, 35933).
[W1026 18:54:43.118923898 TCPStore.cpp:345] [c10d] TCP client failed to connect/validate to host 127.0.0.1:35933 - retrying (try=0, timeout=600000ms, delay=89056ms): The client socket has timed out after 600000ms while trying to connect to (127.0.0.1, 35933).
Exception raised from throwTimeoutError at ../torch/csrc/distributed/c10d/socket.cpp:1012 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7c73d3dede06 in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x15eb578 (0x7c73be1eb578 in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x605ff95 (0x7c73c2c5ff95 in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x6060136 (0x7c73c2c60136 in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x60605a4 (0x7c73c2c605a4 in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x601cb86 (0x7c73c2c1cb86 in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::TCPStore::TCPStore(std::string, c10d::TCPStoreOptions const&) + 0x20c (0x7c73c2c1facc in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0xdc3faf (0x7c73d2dc3faf in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x4d0374 (0x7c73d24d0374 in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x1f94d6 (0x5ffb8a2c74d6 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #10: _PyObject_MakeTpCall + 0x29b (0x5ffb8a2a4a2b in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #11: <unknown function> + 0x227586 (0x5ffb8a2f5586 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #12: _PyObject_Call + 0x12b (0x5ffb8a2e0e5b in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #13: <unknown function> + 0x210494 (0x5ffb8a2de494 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #14: <unknown function> + 0x1d6ce1 (0x5ffb8a2a4ce1 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #15: <unknown function> + 0x4cebbb (0x7c73d24cebbb in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #16: _PyObject_MakeTpCall + 0x29b (0x5ffb8a2a4a2b in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x70a (0x5ffb8a2b20da in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #18: <unknown function> + 0x273397 (0x5ffb8a341397 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #19: <unknown function> + 0x1ffe03 (0x5ffb8a2cde03 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #20: PyObject_Vectorcall + 0x2c (0x5ffb8a2bec0c in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #21: _PyEval_EvalFrameDefault + 0x70a (0x5ffb8a2b20da in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #22: _PyFunction_Vectorcall + 0x17f (0x5ffb8a2d6dbf in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #23: PyObject_Call + 0x134 (0x5ffb8a2e0be4 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #24: _PyEval_EvalFrameDefault + 0x45d7 (0x5ffb8a2b5fa7 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #25: _PyFunction_Vectorcall + 0x17f (0x5ffb8a2d6dbf in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #26: PyObject_Call + 0x134 (0x5ffb8a2e0be4 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #27: _PyEval_EvalFrameDefault + 0x45d7 (0x5ffb8a2b5fa7 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #28: <unknown function> + 0x227d02 (0x5ffb8a2f5d02 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #29: <unknown function> + 0x2275d0 (0x5ffb8a2f55d0 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #30: _PyEval_EvalFrameDefault + 0x45d7 (0x5ffb8a2b5fa7 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #31: _PyFunction_Vectorcall + 0x17f (0x5ffb8a2d6dbf in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #32: PyObject_Call + 0x134 (0x5ffb8a2e0be4 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x45d7 (0x5ffb8a2b5fa7 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #34: <unknown function> + 0x29b10d (0x5ffb8a36910d in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #35: PyEval_EvalCode + 0x9f (0x5ffb8a36884f in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #36: <unknown function> + 0x2b877a (0x5ffb8a38677a in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #37: <unknown function> + 0x2b4403 (0x5ffb8a382403 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #38: PyRun_StringFlags + 0x62 (0x5ffb8a376e52 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #39: PyRun_SimpleStringFlags + 0x3c (0x5ffb8a376c0c in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #40: Py_RunMain + 0x24c (0x5ffb8a39155c in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #41: Py_BytesMain + 0x37 (0x5ffb8a358ac7 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #42: <unknown function> + 0x29d90 (0x7c73d4a29d90 in /lib/x86_64-linux-gnu/libc.so.6)
frame #43: __libc_start_main + 0x80 (0x7c73d4a29e40 in /lib/x86_64-linux-gnu/libc.so.6)
frame #44: <unknown function> + 0x28a97a (0x5ffb8a35897a in /home/hotaisle/miniforge3/envs/vllm/bin/python)

[E1026 18:55:11.267807549 socket.cpp:1010] [c10d] The client socket has timed out after 600000ms while trying to connect to (127.0.0.1, 35933).
[W1026 18:55:11.268683495 TCPStore.cpp:345] [c10d] TCP client failed to connect/validate to host 127.0.0.1:35933 - retrying (try=0, timeout=600000ms, delay=65332ms): The client socket has timed out after 600000ms while trying to connect to (127.0.0.1, 35933).
Exception raised from throwTimeoutError at ../torch/csrc/distributed/c10d/socket.cpp:1012 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x753d368dde06 in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x15eb578 (0x753d20deb578 in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x605ff95 (0x753d2585ff95 in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x6060136 (0x753d25860136 in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x60605a4 (0x753d258605a4 in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x601cb86 (0x753d2581cb86 in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #6: c10d::TCPStore::TCPStore(std::string, c10d::TCPStoreOptions const&) + 0x20c (0x753d2581facc in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0xdc3faf (0x753d359c3faf in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x4d0374 (0x753d350d0374 in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x1f94d6 (0x6395f716d4d6 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #10: _PyObject_MakeTpCall + 0x29b (0x6395f714aa2b in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #11: <unknown function> + 0x227586 (0x6395f719b586 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #12: _PyObject_Call + 0x12b (0x6395f7186e5b in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #13: <unknown function> + 0x210494 (0x6395f7184494 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #14: <unknown function> + 0x1d6ce1 (0x6395f714ace1 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #15: <unknown function> + 0x4cebbb (0x753d350cebbb in /home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/lib/libtorch_python.so)
frame #16: _PyObject_MakeTpCall + 0x29b (0x6395f714aa2b in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x70a (0x6395f71580da in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #18: <unknown function> + 0x273397 (0x6395f71e7397 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #19: <unknown function> + 0x1ffe03 (0x6395f7173e03 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #20: PyObject_Vectorcall + 0x2c (0x6395f7164c0c in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #21: _PyEval_EvalFrameDefault + 0x70a (0x6395f71580da in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #22: _PyFunction_Vectorcall + 0x17f (0x6395f717cdbf in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #23: PyObject_Call + 0x134 (0x6395f7186be4 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #24: _PyEval_EvalFrameDefault + 0x45d7 (0x6395f715bfa7 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #25: _PyFunction_Vectorcall + 0x17f (0x6395f717cdbf in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #26: PyObject_Call + 0x134 (0x6395f7186be4 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #27: _PyEval_EvalFrameDefault + 0x45d7 (0x6395f715bfa7 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #28: <unknown function> + 0x227d02 (0x6395f719bd02 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #29: <unknown function> + 0x2275d0 (0x6395f719b5d0 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #30: _PyEval_EvalFrameDefault + 0x45d7 (0x6395f715bfa7 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #31: _PyFunction_Vectorcall + 0x17f (0x6395f717cdbf in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #32: PyObject_Call + 0x134 (0x6395f7186be4 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x45d7 (0x6395f715bfa7 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #34: <unknown function> + 0x29b10d (0x6395f720f10d in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #35: PyEval_EvalCode + 0x9f (0x6395f720e84f in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #36: <unknown function> + 0x2b877a (0x6395f722c77a in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #37: <unknown function> + 0x2b4403 (0x6395f7228403 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #38: PyRun_StringFlags + 0x62 (0x6395f721ce52 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #39: PyRun_SimpleStringFlags + 0x3c (0x6395f721cc0c in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #40: Py_RunMain + 0x24c (0x6395f723755c in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #41: Py_BytesMain + 0x37 (0x6395f71feac7 in /home/hotaisle/miniforge3/envs/vllm/bin/python)
frame #42: <unknown function> + 0x29d90 (0x753d37629d90 in /lib/x86_64-linux-gnu/libc.so.6)
frame #43: __libc_start_main + 0x80 (0x753d37629e40 in /lib/x86_64-linux-gnu/libc.so.6)
frame #44: <unknown function> + 0x28a97a (0x6395f71fe97a in /home/hotaisle/miniforge3/envs/vllm/bin/python)

... eventually dies ...

(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231] Exception in worker VllmWorkerProcess while processing method init_device: The client socket has timed out after 600000ms while trying to connect to (127.0.0.1, 33057)., Traceback (most recent call last):
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]   File "/home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/vllm-0.6.4.dev9+g5d264f4a.rocm624-py3.11-linux-x86_64.egg/vllm/executor/multiproc_worker_utils.py", line 224, in _run_worker_process
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]     output = executor(*args, **kwargs)
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]              ^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]   File "/home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/vllm-0.6.4.dev9+g5d264f4a.rocm624-py3.11-linux-x86_64.egg/vllm/worker/worker.py", line 176, in init_device
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]     init_worker_distributed_environment(self.parallel_config, self.rank,
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]   File "/home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/vllm-0.6.4.dev9+g5d264f4a.rocm624-py3.11-linux-x86_64.egg/vllm/worker/worker.py", line 453, in init_worker_distributed_environment
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]     init_distributed_environment(parallel_config.world_size, rank,
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]   File "/home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/vllm-0.6.4.dev9+g5d264f4a.rocm624-py3.11-linux-x86_64.egg/vllm/distributed/parallel_state.py", line 938, in init_distributed_environment
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]     torch.distributed.init_process_group(
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]   File "/home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]     return func(*args, **kwargs)
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]            ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]   File "/home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 97, in wrapper
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]     func_return = func(*args, **kwargs)
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]                   ^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]   File "/home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1605, in init_process_group
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]     store, rank, world_size = next(rendezvous_iterator)
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]                               ^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]   File "/home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages
/torch/distributed/rendezvous.py", line 226, in _tcp_rendezvous_handler
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]     store = _create_c10d_store(
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]             ^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]   File "/home/hotaisle/miniforge3/envs/vllm/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 194, in _create_c10d_store
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]     return TCPStore(
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]            ^^^^^^^^^
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231] torch.distributed.DistNetworkError: The client socket has timed out after 600000ms while trying to connect to (127.0.0.1, 33057).
(VllmWorkerProcess pid=234037) ERROR 10-26 21:27:04 multiproc_worker_utils.py:231]
ERROR 10-26 21:27:05 multiproc_worker_utils.py:117] Worker VllmWorkerProcess pid 98753 died, exit code: -15
INFO 10-26 21:27:05 multiproc_worker_utils.py:121] Killing local vLLM worker processes
ERROR 10-26 21:27:05 multiproc_worker_utils.py:117] Worker VllmWorkerProcess pid 118929 died, exit code: -15
INFO 10-26 21:27:05 multiproc_worker_utils.py:121] Killing local vLLM worker processes
ERROR 10-26 21:27:05 multiproc_worker_utils.py:117] Worker VllmWorkerProcess pid 234037 died, exit code: -15
INFO 10-26 21:27:05 multiproc_worker_utils.py:121] Killing local vLLM worker processes
[rank0]:[W1026 21:27:05.873259430 ProcessGroupNCCL.cpp:1326] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
/home/hotaisle/miniforge3/envs/vllm/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Is this a known issue where the vllm.LLM library does not correctly re-initialize for multiple models and the entire process needs to be reloaded for each process or is this a bug specific to my setup?

This looks like potentially a torch.distributed error, so maybe a multi-gpu only thing? It looks like there's a resource cleanup issue? Is this PyTorch version specific?

(For now, my easy workaround is just moving the loop to an external script and calling the vllm script to force proper cleanup.)

### Before submitting a new issue...

- [X] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

**Comment by haqishen** [comment]
I met the same issue.
I have a 2-stage inference pipeline, and I cannot load the 2nd vllm model into multiple GPUs after cleanup the 1st one by:

```
def cleanup_vllm():
    destroy_model_parallel()
    destroy_distributed_environment()
    with contextlib.suppress(AssertionError):
        torch.distributed.destroy_process_group()
    gc.collect()
    torch.cuda.empty_cache()
```

**Comment by vatsal-kr** [comment]
@haqishen I have a similar pipeline. did you manage to find a fix?

**Comment by longsco** [comment]
i have the same issue did you find a fix or workaround?

**Comment by vatsal-kr** [comment]
I found a solution that works for me in `vllm==0.6.4post1`. I use a chat setting and structured decoding in my experiment, but it should work without them as well (hopefully). However, if I don't initialize the guided_decoding_params and sampling AFTER deleting the llm instance, the second llm generates pure garbage. Wrapping the code in `if __name__=="__main__"` is important too, because the second llm is processed with the `spawn` multiprocessing method instead of `fork`

```python
def get_output():
    messages = [
        [
            {"role": "system", "content": "You are a helpful assistant"},
            {"role": "user", "content": "Hello!"},
        ],
        [
            {"role": "system", "content": "You are a helpful assistant"},
            {"role": "user", "content": "Who is the president of the United States"},
        ],
        [
            {"role": "system", "content": "You are a helpful assistant"},
            {"role": "user", "content": "What is the capital of France"},
        ],
    ]

    guided_decoding_params = GuidedDecodingParams(json=Response.model_json_schema())
    sampling_params = SamplingParams(temperature=0.8, max_tokens=10000, guided_decoding=guided_decoding_params)
    llm = LLM(model="meta-llama/Llama-3.1-8B-Instruct", tensor_parallel_size=2, trust_remote_code=True, disable_custom_all_reduce=True)
    outputs = llm.chat(messages, sampling_params)
    outputs [x.outputs[0].text for x in outputs]
    print(outputs)

    destroy_model_parallel()
    destroy_distributed_environment()
    del llm.llm_engine.model_executor
    del llm
    gc.collect()
    torch.cuda.empty_cache()
    with contextlib.suppress(AssertionError):
        torch.distributed.destroy_process_group()
    time.sleep(10)
    subprocess.run(["nvidia-smi"], check=True)

    guided_decoding_params = GuidedDecodingParams(json=Response.model_json_schema())
    sampling_params = SamplingParams(temperature=0.8, max_tokens=10000, guided_decoding=guided_decoding_params)
    llm = LLM(model="Qwen/Qwen2.5-Coder-14B-Instruct", tensor_parallel_size=2, trust_remote_code=True, disable_custom_all_reduce=True)
    outputs = llm.chat(messages, sampling_params)
    outputs [x.outputs[0].text for x in outputs]
    print(outputs)

if __name__ == "__main__":
    get_output()
```

**Comment by dhayanesh** [comment]
Hi, is anyone able to resolve this issue?
I tried following the above method, but it still struck with "worker ready: awaiting tasks"

**Comment by xlei77** [comment]
same issue

**Comment by jiangzizi** [comment]
same issue
